# -*- coding: utf-8 -*-
"""Bank celów SMART — KPOF wersja B (5 lat). 44 twierdzenia, 9 obszarów ICF."""

WERSJA = dict(
    kod="B", etykieta="5 lat", zakres="44 twierdzenia · d1–d9",
    dziecko="wersja B · grupa starsza",
    opis="Wiek współdziałania i reguły. Cele przenoszą ciężar z dorosłego na rówieśnika: warunkiem "
         "sukcesu przestaje być obecność nauczyciela, a staje się nią zrozumiała zasada.",
)

AREAS = [
 dict(rom="I", icf="d1", name="Uczenie się i stosowanie wiedzy", pts=25,
  zasob="Dziecko z wynikiem 4–5 prowadzi „minutę zagadki” na kręgu porannym — układa zadanie dla grupy, "
        "przez co samo przechodzi z odtwarzania do tworzenia.",
  items=[
   dict(n=1, t="Słucha opowiadania, wiersza, bajki i odpowiada na proste pytania o treść",
        icf="d115–d132", pp="PP 3.3·3.12",
        g3="Wysłucha 3-minutowego fragmentu opowiadania w małej grupie i wskaże obrazek pasujący do treści spośród dwóch — w 3 z 5 czytań.",
        g2="Wysłucha całego opowiadania i odpowie na 2 pytania o treść, korzystając z historyjki obrazkowej jako podpowiedzi — w 3 z 5 czytań.",
        g1="Wysłucha opowiadania i odpowie na 4 pytania o treść, w tym jedno o przyczynę zdarzenia, bez podpowiedzi wizualnej — w 4 z 5 czytań.",
        m="zestaw 4 pytań do tekstu · zapis odpowiedzi"),
   dict(n=2, t="Klasyfikuje przedmioty według wielkości, kształtu, koloru, przeznaczenia; układa szeregi i rytmy",
        icf="d137", pp="PP 4.5·4.14",
        g3="Posegreguje 8 przedmiotów według jednej cechy podanej przez nauczyciela, po pokazie wzorca — w 3 z 5 prób.",
        g2="Posegreguje zbiór według 2 cech kolejno i ułoży rytm dwuelementowy według wzoru — w 3 z 5 prób.",
        g1="Samodzielnie ustali kryterium klasyfikacji, nazwie je i ułoży rytm trzyelementowy, kontynuując go przez 6 powtórzeń — w 4 z 5 prób.",
        m="zestaw materiału logicznego · karta zadania"),
   dict(n=3, t="Przelicza elementy zbiorów w zabawie, posługuje się liczebnikami głównymi",
        icf="d150", pp="PP 4.6",
        g3="Policzy 3 elementy, dotykając każdego, wspólnie z nauczycielem wypowiadającym liczebniki — w 3 z 5 prób.",
        g2="Policzy 6 elementów samodzielnie, zachowując zasadę jeden do jednego, i poda wynik — w 3 z 5 prób.",
        g1="Policzy zbiór do 10, poda wynik bez ponownego liczenia i porówna dwa zbiory („gdzie więcej”) — w 4 z 5 prób.",
        m="zadania liczbowe w zabawie · karta wyników"),
   dict(n=4, t="Skupia uwagę na zadaniu kierowanym przez czas adekwatny do wieku (ok. 15 minut)",
        icf="d160", pp="PP 2.6",
        g3="Pozostanie przy zadaniu kierowanym 5 minut, siedząc na wyznaczonym miejscu z ograniczoną liczbą bodźców — w 3 z 5 zajęć.",
        g2="Pozostanie przy zadaniu 10 minut, korzystając z wizualnego licznika kroków zadania — w 3 z 5 zajęć.",
        g1="Utrzyma uwagę przez pełne 15-minutowe zajęcie kierowane, także przy hałasie w tle — w 4 z 5 zajęć.",
        m="pomiar czasu na zadaniu · zapis przerwań"),
   dict(n=5, t="Rozpoznaje wybrane litery i cyfry, którymi jest zainteresowane na skutek zabawy",
        icf="d140", pp="PP 3.17·4.9",
        g3="Rozpozna pierwszą literę swojego imienia wśród trzech liter, po wskazaniu wzorca — w 3 z 5 prób.",
        g2="Rozpozna 5 liter i 5 cyfr w zabawie, dopasowując je do wzorca — w 3 z 5 prób.",
        g1="Rozpozna i nazwie 10 liter oraz cyfry 1–10 w różnych krojach pisma i odszuka je w otoczeniu sali — w 4 z 5 prób.",
        m="karty liter i cyfr · zapis rozpoznań"),
  ]),

 dict(rom="II", icf="d2", name="Ogólne zadania i wymagania", pts=25,
  zasob="Dziecko sprawnie organizujące sobie pracę zostaje „mistrzem stanowiska”: przygotowuje materiały "
        "dla stolika, co utrwala planowanie i daje mu widoczną, docenianą rolę.",
  items=[
   dict(n=6, t="Wykonuje zadanie według instrukcji od początku do końca",
        icf="d210", pp="PP 7.1",
        g3="Wykona zadanie 2-etapowe, gdy nauczyciel podaje kolejne polecenia po jednym i potwierdza wykonanie — w 3 z 5 zadań.",
        g2="Wykona zadanie 3-etapowe korzystając z instrukcji obrazkowej, bez dodatkowych poleceń — w 3 z 5 zadań.",
        g1="Wykona zadanie 4-etapowe podane raz, słownie, i sprawdzi jego kompletność przed zgłoszeniem końca — w 4 z 5 zadań.",
        m="karta instrukcji · liczba wykonanych etapów"),
   dict(n=7, t="Przechodzi między aktywnościami dnia bez większych trudności",
        icf="d230", pp="PP WSR·Zad.2",
        g3="Przejdzie do kolejnej aktywności po indywidualnym uprzedzeniu i pokazaniu obrazka, w ciągu 2 minut — w 3 z 5 przejść.",
        g2="Przejdzie do kolejnej aktywności po sygnale grupowym i jednym przypomnieniu, w ciągu 1 minuty — w 3 z 5 przejść.",
        g1="Samodzielnie kończy aktywność i przechodzi do kolejnej po sygnale, także gdy przerywa ulubioną zabawę — w 4 z 5 przejść.",
        m="rejestr przejść · pomiar czasu reakcji"),
   dict(n=8, t="Czeka na swoją kolej, panuje nad nieprzyjemną emocją w sytuacji odroczenia",
        icf="d240", pp="PP 2.9·2.12",
        g3="Poczeka na swoją kolej 30 sekund, trzymając przedmiot-znacznik kolejki i mając dorosłego obok — w 3 z 5 sytuacji.",
        g2="Poczeka na swoją kolej 2 minuty w zabawie z regułą, korzystając z wizualnej kolejki — w 3 z 5 sytuacji.",
        g1="Czeka na swoją kolej do końca zabawy grupowej i nazywa emocję niezadowolenia bez reakcji zakłócającej — w 4 z 5 sytuacji.",
        m="zabawa z regułą · rejestr zachowań w kolejce"),
   dict(n=9, t="Organizuje sobie miejsce zabawy i pracy, sprząta po skończonej aktywności",
        icf="d220", pp="PP 2.5",
        g3="Przyniesie 2 potrzebne materiały wskazane przez nauczyciela i odłoży je po pracy z jego pomocą — w 3 z 5 zajęć.",
        g2="Przygotuje stanowisko według listy obrazkowej i posprząta je po skończonej pracy — w 3 z 5 zajęć.",
        g1="Samodzielnie zaplanuje, jakie materiały będą potrzebne, przygotuje je i uporządkuje stanowisko bez przypomnienia — w 4 z 5 zajęć.",
        m="lista obrazkowa stanowiska · zdjęcie po pracy"),
   dict(n=10, t="W sytuacjach trudnych szuka wsparcia, korzysta z podpowiedzi dorosłego",
        icf="d240", pp="PP 2.11",
        g3="W sytuacji trudności użyje umówionego znaku (kartonik „pomoc”) po przypomnieniu zasady — w 3 z 5 sytuacji.",
        g2="Poprosi o pomoc słownie po podjęciu jednej samodzielnej próby — w 3 z 5 sytuacji.",
        g1="Nazwie trudność, poprosi o konkretną pomoc i wykorzysta otrzymaną podpowiedź do dokończenia zadania — w 4 z 5 sytuacji.",
        m="zadania z celową trudnością · rejestr próśb"),
  ]),

 dict(rom="III", icf="d3", name="Porozumiewanie się", pts=25,
  zasob="Dziecko z bogatą mową prowadzi „kącik opowiadacza”: opowiada grupie historyjkę obrazkową, "
        "co czyni z jego zasobu narzędzie pracy nad obszarem I i VIII u pozostałych dzieci.",
  items=[
   dict(n=11, t="Mówi zdaniami rozwiniętymi, w mowie zrozumiałej także dla osób spoza rodziny",
        icf="d330", pp="PP 3.2",
        g3="Zbuduje zdanie 3-wyrazowe opisujące obrazek po pytaniu naprowadzającym nauczyciela — w 3 z 5 prób.",
        g2="Zbuduje zdanie rozwinięte (5 wyrazów) o zdarzeniu z sali, zrozumiałe dla nauczyciela — w 3 z 5 prób.",
        g1="Wypowie się zdaniami rozwiniętymi zrozumiałymi dla osoby spoza przedszkola, utrzymując temat przez 4 wypowiedzi — w 4 z 5 rozmów.",
        m="próbka mowy · nagranie 5 minut raz w tygodniu"),
   dict(n=12, t="Opowiada o zdarzeniach z przedszkola, własnych przeżyciach i obserwacjach",
        icf="d330", pp="PP 3.12",
        g3="Opowie o jednym zdarzeniu z dnia, korzystając ze zdjęcia z zajęć jako podpowiedzi — w 3 z 5 prób.",
        g2="Opowie o zdarzeniu w 3 zdaniach, zachowując kolejność, przy wsparciu historyjki obrazkowej — w 3 z 5 prób.",
        g1="Samodzielnie opowie o wydarzeniu z zachowaniem kolejności i poda, co czuł — w 4 z 5 prób.",
        m="karta opowieści dnia · zapis wypowiedzi"),
   dict(n=13, t="Prowadzi rozmowę: aktywnie słucha rozmówcy, odpowiada, zadaje pytania i dopytuje",
        icf="d350", pp="PP 3.1·3.5",
        g3="Odpowie na pytanie rówieśnika skierowane do niego indywidualnie, po przypomnieniu przez dorosłego — w 3 z 5 sytuacji.",
        g2="Utrzyma wymianę zdań z rówieśnikiem przez 2 rundy (pytanie–odpowiedź–pytanie) — w 3 z 5 rozmów.",
        g1="Utrzyma rozmowę przez 4 rundy, zada pytanie doprecyzowujące i nie przerwie rozmówcy — w 4 z 5 rozmów.",
        m="obserwacja rozmowy w parze · liczba rund"),
   dict(n=14, t="Recytuje wierszyki, eksperymentuje z językiem, tworzy rymowanki i zagadki",
        icf="d330", pp="PP 3.10·3.11",
        g3="Powtórzy 2-wersowy fragment wiersza za nauczycielem, dodając gest — w 3 z 5 prób.",
        g2="Wyrecytuje 4-wersową zwrotkę z pamięci, przy podpowiedzi pierwszego słowa wersu — w 3 z 5 prób.",
        g1="Wyrecytuje wiersz przed grupą i ułoży własną parę rymów do podanego wyrazu — w 4 z 5 prób.",
        m="karta recytacji · rejestr rymów dziecka"),
   dict(n=15, t="Adekwatnie używa komunikatów niewerbalnych (gest, mimika, ruch)",
        icf="d335", pp="PP 3.2",
        g3="Użyje gestu wskazania lub podania, aby pokazać, czego chce, po modelowaniu dorosłego — w 3 z 5 sytuacji.",
        g2="Dopasuje mimikę do treści wypowiedzi w zabawie „pokaż emocję” — w 3 z 5 prób.",
        g1="Świadomie użyje gestu i mimiki w scence, tak by grupa odgadła emocję lub czynność — w 4 z 5 prób.",
        m="zabawa pantomimiczna · trafność odczytu przez grupę"),
  ]),

 dict(rom="IV", icf="d4", name="Poruszanie się", pts=25,
  zasob="Wysoki wynik ruchowy wykorzystujemy jako wejście do obszarów trudniejszych: dziecko prowadzi tor "
        "przeszkód, wydając grupie polecenia — ćwiczy komunikację i czekanie na kolej w swoim mocnym kanale.",
  items=[
   dict(n=16, t="Wykonuje różne formy ruchu: bieżne, skoczne, z czworakowaniem, rzutne",
        icf="d455", pp="PP 9.4",
        g3="Wykona 2 formy ruchu (bieg, czworakowanie) na sygnał, naśladując nauczyciela — w 3 z 5 zajęć.",
        g2="Wykona 4 formy ruchu na sygnał słowny, bez pokazu, zachowując kierunek — w 3 z 5 zajęć.",
        g1="Wykona sekwencję 4 form ruchu według zapamiętanej kolejności i nazwie ją — w 4 z 5 zajęć.",
        m="tor sprawnościowy · karta prób"),
   dict(n=17, t="Utrzymuje równowagę (stanie na jednej nodze, chodzenie po wyznaczonej linii)",
        icf="d415", pp="PP 9.4",
        g3="Ustoi na jednej nodze 2 sekundy, trzymając się poręczy lub ręki dorosłego — w 3 z 5 prób.",
        g2="Ustoi na jednej nodze 5 sekund bez podparcia i przejdzie 2 metry po linii — w 3 z 5 prób.",
        g1="Ustoi na jednej nodze 10 sekund i przejdzie po ławeczce, niosąc lekki przedmiot — w 4 z 5 prób.",
        m="próba równowagi · pomiar czasu"),
   dict(n=18, t="Sprawnie posługuje się nożyczkami, lepi, nawleka, majsterkuje",
        icf="d440", pp="PP 9.5·6.3",
        g3="Wykona 3 nacięcia nożyczkami w kartce trzymanej przez dorosłego — w 3 z 5 prób.",
        g2="Przetnie kartkę wzdłuż grubej linii prostej i wylepi kulkę oraz wałek z plasteliny — w 3 z 5 prób.",
        g1="Wytnie kształt po linii łamanej, zachowując margines 5 mm, i wykona pracę przestrzenną według wzoru — w 4 z 5 prób.",
        m="wytwór dziecka · ocena dokładności cięcia"),
   dict(n=19, t="Trzyma kredkę i ołówek chwytem zbliżonym do pisarskiego, kontroluje siłę nacisku",
        icf="d440", pp="PP 9.6",
        g3="Utrzyma kredkę chwytem trójpalcowym przez 2 minuty rysowania, z nasadką korygującą — w 3 z 5 prób.",
        g2="Utrzyma prawidłowy chwyt przez całą pracę plastyczną i zamaluje pole bez przedzierania kartki — w 3 z 5 prac.",
        g1="Utrzyma prawidłowy chwyt i stały nacisk, kreśląc szlaczki w liniaturze przez 10 minut — w 4 z 5 prac.",
        m="obserwacja chwytu · karta prac graficznych"),
   dict(n=20, t="Posługuje się przedmiotami o różnej wielkości i ciężarze, także wymagającymi precyzji",
        icf="d430–d440", pp="PP 9.5",
        g3="Przeniesie oburącz przedmiot średniej wielkości na odległość 3 metrów, bez upuszczenia — w 3 z 5 prób.",
        g2="Przesypie kaszę łyżką między naczyniami i przeniesie tacę z 2 kubkami, nie rozlewając — w 3 z 5 prób.",
        g1="Wykona zadanie wymagające precyzji (nalanie wody do kreski, użycie pipety) i dostosuje siłę chwytu do przedmiotu — w 4 z 5 prób.",
        m="zadania praktyczne · karta prób precyzji"),
  ]),

 dict(rom="V", icf="d5", name="Dbanie o siebie", pts=25,
  zasob="Dziecko samodzielne w samoobsłudze prowadzi „szatnianego asystenta”: pokazuje młodszym kolejność "
        "ubierania — utrwala nawyk i buduje kompetencje z obszaru VII.",
  items=[
   dict(n=21, t="Samodzielnie wykonuje podstawowe czynności higieniczne",
        icf="d510–d520", pp="PP 9.7",
        g3="Wykona mycie rąk według instrukcji obrazkowej z jednym podprowadzeniem fizycznym — w 4 z 5 prób.",
        g2="Wykona mycie rąk i wytarcie ich samodzielnie po jednym przypomnieniu słownym — w 3 z 5 sytuacji.",
        g1="Samodzielnie dba o higienę rąk i nosa we wszystkich sytuacjach dnia, bez przypomnień — w 4 z 5 dni.",
        m="lista kontrolna higieny · zapis dzienny"),
   dict(n=22, t="Ubiera się i rozbiera samodzielnie",
        icf="d540", pp="PP 9.7",
        g3="Ubierze 3 części garderoby, gdy dorosły podaje je w kolejności i pomaga przy zapięciach — w 3 z 5 wyjść.",
        g2="Ubierze się samodzielnie korzystając z planu obrazkowego, prosząc o pomoc tylko przy suwaku — w 3 z 5 wyjść.",
        g1="Ubierze się i rozbierze samodzielnie w czasie przewidzianym dla grupy, zapinając guziki i suwak — w 4 z 5 wyjść.",
        m="pomiar czasu ubierania · liczba próśb o pomoc"),
   dict(n=23, t="Spożywa posiłki z użyciem sztućców, zachowuje się kulturalnie przy stole",
        icf="d550", pp="PP 9.7·WSR",
        g3="Zje posiłek łyżką, siedząc przy stole przez 10 minut, z przypomnieniem o pozycji ciała — w 4 z 5 posiłków.",
        g2="Zje posiłek widelcem i łyżką, użyje serwetki i podziękuje po posiłku — w 3 z 5 posiłków.",
        g1="Zje posiłek z użyciem sztućców, nałoży sobie porcję, poprosi o dokładkę i posprząta miejsce — w 4 z 5 posiłków.",
        m="obserwacja posiłku · karta kultury stołu"),
   dict(n=24, t="Przestrzega prostych zasad bezpieczeństwa w sali i na placu zabaw",
        icf="d571", pp="PP 9.11",
        g3="Zatrzyma się na sygnał dźwiękowy podczas zabawy na placu, po dodatkowym przywołaniu imieniem — w 3 z 5 wyjść.",
        g2="Wymieni 3 zasady bezpieczeństwa i zastosuje je po jednym przypomnieniu grupowym — w 3 z 5 wyjść.",
        g1="Samodzielnie przestrzega zasad bezpieczeństwa, zgłasza nauczycielowi sytuacje niebezpieczne — w 4 z 5 wyjść.",
        m="tablica zasad · rejestr zdarzeń"),
   dict(n=25, t="Komunikuje potrzebę ruchu i odpoczynku, poszukuje bezpiecznych i przyjaznych przestrzeni",
        icf="d571", pp="PP 9.10",
        g3="Skorzysta z kącika wyciszenia po zaproponowaniu go przez nauczyciela, pozostając tam 3 minuty — w 3 z 5 sytuacji.",
        g2="Zgłosi potrzebę ruchu lub odpoczynku umówionym komunikatem i skorzysta z niej — w 3 z 5 sytuacji.",
        g1="Samodzielnie rozpozna narastające napięcie, nazwie je i wybierze przestrzeń oraz aktywność regulującą — w 4 z 5 sytuacji.",
        m="karta samoregulacji · zapis zgłoszeń dziecka"),
  ]),

 dict(rom="VI", icf="d6", name="Życie domowe (czynności użyteczne)", pts=20, opis_flag=True,
  zasob="Obszar opisowy — poza wynikiem ogólnym. Dyżury to najtańsze narzędzie budowania sprawczości: "
        "dziecko z zasobem wprowadza kolejne dziecko w rolę dyżurnego.",
  items=[
   dict(n=26, t="Samodzielnie sprząta po sobie miejsce zabawy i pracy",
        icf="d640", pp="PP 2.5·WSR",
        g3="Posprząta swoje miejsce, gdy nauczyciel wskazuje kolejne przedmioty do odłożenia — w 3 z 5 dni.",
        g2="Posprząta miejsce pracy po sygnale, sprawdzając efekt według zdjęcia wzorcowego — w 3 z 5 dni.",
        g1="Samodzielnie sprząta po każdej aktywności bez sygnału i pomaga domknąć porządek w kąciku — w 4 z 5 dni.",
        m="zdjęcie wzorcowe · zapis dzienny"),
   dict(n=27, t="Pomaga w dyżurach: rozdawanie, zbieranie, porządkowanie materiałów, pomoc innym",
        icf="d640", pp="PP 1.10·WSR",
        g3="Wykona 1 czynność dyżurnego z dorosłym obok, według obrazka — w 3 z 5 dyżurów.",
        g2="Wykona pełny dyżur 2-etapowy według planu obrazkowego, bez pomocy dorosłego — w 3 z 5 dyżurów.",
        g1="Pełni dyżur samodzielnie, planuje kolejność czynności i pomaga koledze, który sobie nie radzi — w 4 z 5 dyżurów.",
        m="grafik dyżurów · karta samooceny dziecka"),
   dict(n=28, t="Dba o zabawki i materiały, uzgadnia zasady dzielenia się rzeczami wspólnymi",
        icf="d650", pp="PP 1.3·2.5",
        g3="Odda zabawkę na sygnał kończący zabawę, po zapowiedzi z wyprzedzeniem — w 3 z 5 sytuacji.",
        g2="Uzgodni z jednym dzieckiem kolejność korzystania z zabawki przy wsparciu nauczyciela — w 3 z 5 sytuacji.",
        g1="Samodzielnie ustali z grupą zasadę dzielenia się wspólnym materiałem i będzie jej przestrzegać przez całą zabawę — w 4 z 5 sytuacji.",
        m="obserwacja zabawy swobodnej · rejestr uzgodnień"),
   dict(n=29, t="Pakuje swoje rzeczy (worek, plecak), przygotowuje się do wyjścia na zewnątrz",
        icf="d640", pp="PP 2.5·WSR",
        g3="Spakuje 2 rzeczy do worka wskazywane kolejno przez dorosłego — w 3 z 5 dni.",
        g2="Spakuje swoje rzeczy według listy obrazkowej, sprawdzając ją na końcu — w 3 z 5 dni.",
        g1="Samodzielnie spakuje się do wyjścia, uwzględniając pogodę, i sprawdzi kompletność rzeczy — w 4 z 5 dni.",
        m="lista obrazkowa · kontrola kompletności"),
  ]),

 dict(rom="VII", icf="d7", name="Wzajemne kontakty i związki międzyludzkie", pts=25,
  zasob="Kompetencja społeczna to najsilniejsza dźwignia całego profilu: dziecko z wynikiem 4–5 zostaje "
        "„kolegą wspierającym” w zabawie dziecka z Poziomu II lub III — z konkretną, wyćwiczoną instrukcją.",
  items=[
   dict(n=30, t="Nawiązuje relacje rówieśnicze, ma ulubionych partnerów zabaw, szanuje upodobania innych",
        icf="d750", pp="PP 1.2·1.8",
        g3="Podejmie zabawę obok wskazanego dziecka przez 5 minut w aktywności zaaranżowanej przez nauczyciela — w 3 z 5 dni.",
        g2="Podejmie wspólną zabawę z jednym stałym partnerem przez 10 minut — w 3 z 5 dni.",
        g1="Samodzielnie zaprosi do zabawy wybrane dziecko, także spoza stałej pary, i uwzględni jego pomysł — w 4 z 5 dni.",
        m="socjogram grupy · obserwacja zabawy swobodnej"),
   dict(n=31, t="Współdziała z dziećmi, zgłasza własne pomysły, uzgadnia zasady dzielenia się",
        icf="d720", pp="PP 1.2·1.3",
        g3="Wykona swoją część wspólnego zadania przydzieloną przez nauczyciela, pracując obok innych — w 3 z 5 zadań.",
        g2="Zgłosi 1 własny pomysł w pracy w parze i uzgodni podział materiału — w 3 z 5 zadań.",
        g1="Współdziała w 3-osobowym zespole: proponuje, słucha propozycji innych i przyjmuje wspólne rozwiązanie — w 4 z 5 zadań.",
        m="karta pracy zespołowej · obserwacja"),
   dict(n=32, t="Stosuje zwroty grzecznościowe: powitanie, pożegnanie, przepraszanie",
        icf="d710", pp="PP 1.5",
        g3="Odpowie na powitanie gestem lub słowem po modelowaniu nauczyciela — w 3 z 5 sytuacji.",
        g2="Użyje 3 zwrotów grzecznościowych po jednym przypomnieniu w sytuacji naturalnej — w 3 z 5 sytuacji.",
        g1="Samodzielnie stosuje zwroty grzecznościowe wobec dzieci i dorosłych, także wobec osób nowych — w 4 z 5 sytuacji.",
        m="rejestr zwrotów grzecznościowych · zapis dzienny"),
   dict(n=33, t="Mówi o emocjach, które ludzie mogą przeżywać, wczuwa się w emocje innych",
        icf="d710", pp="PP 1.7·1.11",
        g3="Wskaże na ilustracji dziecko smutne i wesołe, po nazwaniu emocji przez nauczyciela — w 3 z 5 prób.",
        g2="Nazwie emocję bohatera opowiadania i poda jej przyczynę przy pytaniu naprowadzającym — w 3 z 5 prób.",
        g1="Rozpozna emocję kolegi w sytuacji realnej, nazwie ją i zaproponuje sposób pomocy — w 4 z 5 sytuacji.",
        m="historyjki społeczne · zapis wypowiedzi"),
   dict(n=34, t="Szuka rozwiązań w sytuacjach spornych, rozwiązuje proste konflikty z pomocą dorosłych lub dzieci",
        icf="d720", pp="PP 1.9",
        g3="W sytuacji sporu zatrzyma działanie na sygnał dorosłego i przyjmie zaproponowane rozwiązanie — w 3 z 5 konfliktów.",
        g2="Powie, o co się pokłócił, i wybierze jedno z dwóch rozwiązań zaproponowanych przez nauczyciela — w 3 z 5 konfliktów.",
        g1="Samodzielnie zaproponuje rozwiązanie sporu i uzgodni je z drugim dzieckiem bez udziału dorosłego — w 4 z 5 konfliktów.",
        m="karta konfliktu · zapis rozwiązań"),
  ]),

 dict(rom="VIII", icf="d8", name="Główne obszary życia (edukacja przedszkolna i zabawa)", pts=25,
  zasob="Twórczość i zabawa tematyczna to obszar, w którym najłatwiej pokazać dziecku jego mocną stronę "
        "publicznie: wystawa prac, koncert grupy, prezentacja budowli z uzasadnieniem pomysłu.",
  items=[
   dict(n=35, t="Aktywnie uczestniczy w zajęciach kierowanych, podejmuje aktywności realizujące własne pomysły",
        icf="d815", pp="PP 1.2·2.1",
        g3="Wykona 1 zadanie zajęcia kierowanego przy indywidualnym zachęceniu nauczyciela — w 3 z 5 zajęć.",
        g2="Wykona wszystkie zadania zajęcia i zgłosi się raz do odpowiedzi — w 3 z 5 zajęć.",
        g1="Aktywnie uczestniczy w zajęciu i zaproponuje własny sposób wykonania zadania — w 4 z 5 zajęć.",
        m="karta aktywności na zajęciach · zapis zgłoszeń"),
   dict(n=36, t="Rozwija zabawę tematyczną z podziałem ról (np. w sklep, w dom)",
        icf="d880", pp="PP 1.12·8.6",
        g3="Przyjmie rolę przydzieloną przez nauczyciela i wykona w niej 2 czynności — w 3 z 5 zabaw.",
        g2="Uzgodni rolę z jednym dzieckiem i utrzyma ją przez 10 minut zabawy — w 3 z 5 zabaw.",
        g1="Zaplanuje z grupą scenariusz zabawy, rozdzieli role i rozwinie fabułę przez 20 minut — w 4 z 5 zabaw.",
        m="obserwacja zabawy tematycznej · 20 minut"),
   dict(n=37, t="Wyraża ekspresję twórczą: tworzy budowle, prace plastyczne, szuka ulepszeń",
        icf="d880", pp="PP 8.1·6.3",
        g3="Wykona pracę plastyczną według wzoru, wykonując 2 kroki po pokazie — w 3 z 5 prac.",
        g2="Wykona pracę na zadany temat, dobierając samodzielnie 2 techniki lub materiały — w 3 z 5 prac.",
        g1="Zaplanuje pracę, wykona ją i wskaże, co zmieniłby następnym razem — w 4 z 5 prac.",
        m="teczka prac · karta samooceny wytworu"),
   dict(n=38, t="Uczestniczy w zbiorowym muzykowaniu, śpiewa piosenki, tańczy",
        icf="d880", pp="PP 8.4",
        g3="Zagra na instrumencie perkusyjnym w takt muzyki przez 1 minutę, naśladując nauczyciela — w 3 z 5 zajęć.",
        g2="Zaśpiewa refren znanej piosenki z grupą i zagra swoją partię w prostym akompaniamencie — w 3 z 5 zajęć.",
        g1="Zaśpiewa zwrotkę i refren z pamięci, utrzyma rytm w zespole i zatańczy układ do końca — w 4 z 5 zajęć.",
        m="obserwacja zajęć umuzykalniających"),
   dict(n=39, t="Pełni rolę przedszkolaka: reaguje na polecenia kierowane do całej grupy",
        icf="d815", pp="PP 1.6·3.5",
        g3="Wykona polecenie grupowe po powtórzeniu go indywidualnie z użyciem imienia — w 3 z 5 poleceń.",
        g2="Wykona polecenie skierowane do całej grupy po jednym powtórzeniu ogólnym — w 3 z 5 poleceń.",
        g1="Wykona polecenie grupowe podane raz, bez zwracania się do niego indywidualnie — w 4 z 5 poleceń.",
        m="rejestr poleceń grupowych · 5 dziennie"),
  ]),

 dict(rom="IX", icf="d9", name="Życie społeczne, lokalne i obywatelskie", pts=25,
  zasob="Zasób w tym obszarze przekłada się na role reprezentacyjne: prowadzenie części uroczystości, "
        "oprowadzanie gościa po sali, przedstawienie grupy — z widoczną wartością dla całego zespołu.",
  items=[
   dict(n=40, t="Odczuwa przynależność do grupy przedszkolnej i wyraża ją (nazwa grupy, zwyczaje)",
        icf="d910", pp="PP 1.16",
        g3="Wskaże znak i nazwę swojej grupy spośród trzech, po podpowiedzi wzrokowej — w 3 z 5 prób.",
        g2="Poda nazwę swojej grupy i wymieni 1 zwyczaj grupowy — w 3 z 5 prób.",
        g1="Opowie o swojej grupie: nazwie ją, wymieni 3 zwyczaje i powie, co w niej lubi — w 4 z 5 prób.",
        m="rozmowa kierowana · zapis wypowiedzi"),
   dict(n=41, t="Odgrywa uzgodnioną z dziećmi rolę w przygotowaniu i realizacji występu lub uroczystości",
        icf="d910", pp="PP DE-R.5",
        g3="Weźmie udział w próbie występu, stojąc na swoim miejscu przez 5 minut przy wsparciu dorosłego — w 3 z 4 prób.",
        g2="Wykona swoją krótką rolę w występie (jedno zdanie, jeden ruch) po przygotowaniu wizualnym — w 3 z 4 występów.",
        g1="Uzgodni z dziećmi swoją rolę, przygotuje ją i wykona przed publicznością — w 4 z 4 występów.",
        m="karta przygotowania uroczystości · zapis roli"),
   dict(n=42, t="Korzysta z rekreacji: przygotowuje wspólne wyjścia, uczestniczy w zabawach sezonowych na powietrzu",
        icf="d920", pp="PP DE-R.4·9.1",
        g3="Weźmie udział w 10-minutowej zabawie sezonowej na powietrzu, przy wsparciu dorosłego — w 3 z 5 wyjść.",
        g2="Uczestniczy w całej zabawie na powietrzu i pomoże przygotować sprzęt do wyjścia — w 3 z 5 wyjść.",
        g1="Zaproponuje zabawę sezonową dla grupy, przygotuje potrzebny sprzęt i poprowadzi ją — w 4 z 5 wyjść.",
        m="karta wyjść · zapis inicjatyw dziecka"),
   dict(n=43, t="Jest odbiorcą sztuki: teatrzyki, koncerty, wystawy; wyraża swoje opinie o dziełach",
        icf="d9202", pp="PP DE-R.1·8.3",
        g3="Wysłucha 10-minutowego teatrzyku, siedząc na swoim miejscu, z możliwością wyciszenia bodźców — w 3 z 4 wydarzeń.",
        g2="Obejrzy całe wydarzenie i wskaże, co mu się podobało, wybierając spośród dwóch propozycji — w 3 z 4 wydarzeń.",
        g1="Wypowie własną opinię o przedstawieniu i uzasadni ją („podobało mi się, bo…”) — w 4 z 4 wydarzeń.",
        m="karta odbioru sztuki · zapis opinii dziecka"),
   dict(n=44, t="Posługuje się swoim imieniem i nazwiskiem",
        icf="d910", pp="PP 1.1",
        g3="Odpowie na wywołanie imieniem, kierując wzrok na osobę wywołującą — w 4 z 5 sytuacji.",
        g2="Poda swoje imię i nazwisko na pytanie dorosłego — w 3 z 5 sytuacji.",
        g1="Poda imię, nazwisko i nazwę grupy osobie nieznanej oraz rozpozna swoje imię zapisane — w 4 z 5 sytuacji.",
        m="rozmowa kierowana · karta danych osobowych"),
  ]),
]
