# -*- coding: utf-8 -*-
"""Bank celów SMART — uzupełnienia do podstawy 2026 (wersja U).

To NIE są twierdzenia z arkuszy KPOF. To propozycje domykające pokrycie
podstawy programowej: 48 celów do punktów, których wersje A, B i C nie
dotykają. Trzymamy je osobno, żeby arkusze KPOF pozostały nienaruszone —
po akceptacji można je przenieść do właściwej wersji wiekowej.

Obszary odpowiadają dziewięciu obszarom osiągnięć nowej podstawy
(rozporządzenie MEN z 11 marca 2026 r., Dz. U. 2026 poz. 378), a nie
obszarom ICF — dlatego numer rzymski czyta się tu jako numer obszaru
podstawy. Kod ICF przy każdym celu zostaje, bo wiąże cel z WOPF i IPET.
"""

WERSJA = dict(
    kod="U", etykieta="uzupełnienia", zakres="48 celów · domknięcie podstawy 2026",
    dziecko="wersja U · propozycje uzupełnień, 5–6 lat",
    opis="Cele do punktów podstawy, których arkusze KPOF jeszcze nie obejmują — najwięcej "
         "w obszarach technicznym, przyrodniczym i cyfrowym. Poziomy wsparcia opisane tak samo "
         "jak w pozostałych wersjach; miary gotowe do wpisania w IPET.",
)

AREAS = [
 dict(rom="I", icf="d8–d9", name="Obszar społeczny", pts=4,
  zasob="Dziecko z wynikiem 4–5 prowadzi „skarbonkę grupy”: pilnuje wspólnej puli na wybrany cel "
        "i tłumaczy młodszym, po co się oszczędza.",
  items=[
   dict(n=1, t="Wyjaśnia, na czym polega oszczędzanie i dlaczego warto oszczędzać",
        icf="d860", pp="PP 1.15",
        g3="Wskaże w zabawie, że po wydaniu pieniędzy nie można kupić kolejnej rzeczy — po pytaniu naprowadzającym, w 3 z 5 sytuacji.",
        g2="Odłoży część żetonów na wskazany cel zamiast wydać wszystkie i powie, na co odkłada — w 3 z 5 zabaw.",
        g1="Zaplanuje w zabawie zakup wymagający odłożenia żetonów przez kilka dni i wyjaśni, dlaczego warto było poczekać — w 4 z 5 sytuacji.",
        m="zabawa w sklep · skarbonka grupy · zapis wypowiedzi"),
   dict(n=2, t="Wskazuje funkcje różnych instytucji społecznych (rodzina, przedszkole, przychodnia)",
        icf="d910", pp="PP 1.18",
        g3="Dopasuje 3 obrazki instytucji do osób, które w nich pracują — przy podpowiedzi obrazkowej, w 3 z 5 prób.",
        g2="Powie, po co idzie się do 4 wskazanych instytucji — w 3 z 5 prób.",
        g1="Wyjaśni, do której instytucji zwrócić się w 5 opisanych sytuacjach, i uzasadni wybór — w 4 z 5 prób.",
        m="karty instytucji · zapis wypowiedzi · scenki"),
   dict(n=3, t="Charakteryzuje wybrane elementy dziedzictwa kulturowego swojego regionu",
        icf="d910", pp="PP 1.20",
        g3="Rozpozna 2 elementy regionu pokazane na zdjęciach (herb, budowla, strój) — po nazwaniu przez nauczyciela, w 3 z 5 prób.",
        g2="Opowie o 3 elementach dziedzictwa regionu dwoma zdaniami o każdym — w 3 z 5 prób.",
        g1="Przygotuje kącik regionu z 4 elementami i oprowadzi po nim kolegę, tłumacząc, czym jest każdy — w 4 z 5 prób.",
        m="album regionu · kącik tematyczny · nagranie oprowadzania"),
   dict(n=4, t="Pracując w grupie, planuje i podejmuje działanie na rzecz innych",
        icf="d740", pp="PP DE-P.3",
        g3="Wykona jedną przydzieloną czynność w akcji grupy (np. przygotuje jedną kartkę), przy wsparciu dorosłego — w 3 z 5 działań.",
        g2="Zaproponuje, komu grupa może pomóc, i wykona swoją część zadania do końca — w 3 z 5 działań.",
        g1="Zaplanuje z grupą działanie dla młodszych dzieci lub osób starszych, rozdzieli zadania i opowie, co się udało — raz w roku, z dokumentacją.",
        m="karta projektu · zdjęcia z działania · zapis podsumowania"),
  ]),

 dict(rom="II", icf="d1", name="Obszar osobisty", pts=1,
  zasob="Dziecko z wynikiem 4–5 prowadzi „ścianę mocnych stron”: pomaga innym nazwać, w czym są dobrzy.",
  items=[
   dict(n=5, t="Odkrywa swoje zainteresowania i nazywa swoje mocne strony",
        icf="d177", pp="PP 2.2",
        g3="Wskaże obrazek czynności, którą lubi, spośród trzech propozycji — w 3 z 5 rozmów.",
        g2="Powie, w czym jest dobre i co lubi robić, podając po jednym przykładzie — w 3 z 5 rozmów.",
        g1="Wymieni trzy swoje mocne strony, poda sytuację, w której się przydały, i wskaże, czego chce się nauczyć — w 4 z 5 rozmów.",
        m="karta mocnych stron · rozmowa indywidualna · portfolio dziecka"),
  ]),

 dict(rom="III", icf="d1–d3", name="Obszar językowy", pts=7,
  zasob="Dziecko z wynikiem 4–5 prowadzi „redakcję grupy”: zbiera wiadomości, sprawdza je i przedstawia innym.",
  items=[
   dict(n=6, t="Dostrzega informacje niewiarygodne lub wykluczające się",
        icf="d163", pp="PP 3.6",
        g3="Zauważy, że w dwóch zdaniach coś się nie zgadza, po pytaniu nauczyciela „czy to możliwe?” — w 3 z 5 prób.",
        g2="Wskaże w krótkim opowiadaniu zdanie, które nie może być prawdziwe, i powie dlaczego — w 3 z 5 prób.",
        g1="Porówna dwie sprzeczne relacje o tym samym zdarzeniu i wskaże, czego trzeba, żeby sprawdzić, która jest prawdziwa — w 4 z 5 prób.",
        m="zestaw zdań-pułapek · zapis uzasadnień"),
   dict(n=7, t="Ocenia zgodność uzyskiwanych informacji z własnymi obserwacjami",
        icf="d163", pp="PP 3.7",
        g3="Potwierdzi lub zaprzeczy zdaniu o pogodzie po spojrzeniu za okno — przy pytaniu naprowadzającym, w 3 z 5 prób.",
        g2="Sprawdzi w otoczeniu, czy usłyszana informacja jest prawdziwa, i powie wynik — w 3 z 5 prób.",
        g1="Zaplanuje, jak sprawdzić usłyszaną informację, wykona sprawdzenie i przedstawi wniosek grupie — w 4 z 5 prób.",
        m="dziennik obserwacji · zapis wniosków"),
   dict(n=8, t="Dzieli się wyobrażeniami i pomysłami typu „co by było, gdyby”",
        icf="d163", pp="PP 3.9",
        g3="Dokończy zdanie „co by było, gdyby…” jednym pomysłem, po podaniu przykładu — w 3 z 5 prób.",
        g2="Poda dwa różne zakończenia sytuacji „co by było, gdyby…” — w 3 z 5 prób.",
        g1="Rozwinie pomysł „co by było, gdyby…” w krótką opowieść z konsekwencjami dla bohatera — w 4 z 5 prób.",
        m="karty pytań otwartych · nagranie wypowiedzi"),
   dict(n=9, t="Odczytuje znaczenie symboli i znaków, tworzy własne symbole",
        icf="d325", pp="PP 3.13",
        g3="Dopasuje 3 znane znaki (zakaz, wyjście, toaleta) do sytuacji — przy podpowiedzi, w 3 z 5 prób.",
        g2="Odczyta 5 znaków z otoczenia i narysuje własny znak dla zasady w sali — w 3 z 5 prób.",
        g1="Zaprojektuje zestaw znaków dla kącika i wyjaśni grupie, co każdy oznacza, tak by inni z nich korzystali — w 4 z 5 prób.",
        m="zestaw znaków · tablica zasad grupy"),
   dict(n=10, t="Nazywa obiekty z najbliższego otoczenia w języku obcym nowożytnym",
        icf="d330", pp="PP 3.18",
        g3="Wskaże przedmiot po usłyszeniu jego nazwy w języku obcym — spośród trzech, w 3 z 5 prób.",
        g2="Nazwie 6 przedmiotów z sali w języku obcym — w 3 z 5 prób.",
        g1="Nazwie 10 przedmiotów i użyje ich w prostym zwrocie („this is…”) — w 4 z 5 prób.",
        m="karty obrazkowe · zapis odpowiedzi"),
   dict(n=11, t="Uczestniczy w prostej sytuacji komunikacyjnej w języku obcym",
        icf="d310", pp="PP 3.20",
        g3="Odpowie gestem albo jednym słowem na powitanie w języku obcym — w 3 z 5 sytuacji.",
        g2="Odpowie zdaniem na pytanie o imię i samopoczucie w języku obcym — w 3 z 5 sytuacji.",
        g1="Poprowadzi krótki dialog powitalny z kolegą, zadając i odpowiadając na dwa pytania — w 4 z 5 sytuacji.",
        m="scenki dialogowe · nagranie"),
   dict(n=12, t="Powtarza wierszyki i śpiewa piosenki w języku obcym",
        icf="d330", pp="PP 3.21",
        g3="Włączy się gestem albo refrenem do piosenki w języku obcym — w 3 z 5 zajęć.",
        g2="Zaśpiewa całą zwrotkę znanej piosenki w języku obcym — w 3 z 5 zajęć.",
        g1="Zaśpiewa piosenkę z pamięci i powtórzy wierszyk, zachowując rytm i wymowę — w 4 z 5 zajęć.",
        m="repertuar grupy · nagranie audio"),
  ]),

 dict(rom="IV", icf="d1–d6", name="Obszar matematyczny", pts=7,
  zasob="Dziecko z wynikiem 4–5 prowadzi „kantorek problemów”: zbiera kłopoty grupy i szuka rozwiązań z innymi.",
  items=[
   dict(n=13, t="Opisuje sytuacje problemowe bliskie swojemu doświadczeniu i rozpoznaje ich przyczyny",
        icf="d175", pp="PP 4.1",
        g3="Pokaże na obrazku, co poszło nie tak, po pytaniu nauczyciela — w 3 z 5 sytuacji.",
        g2="Opowie, na czym polega problem, i poda jedną jego przyczynę — w 3 z 5 sytuacji.",
        g1="Opisze problem, poda dwie możliwe przyczyny i powie, którą uważa za ważniejszą — w 4 z 5 sytuacji.",
        m="karty sytuacji problemowych · zapis wypowiedzi"),
   dict(n=14, t="Stosuje wybrane rozwiązanie i ocenia jego skuteczność",
        icf="d175", pp="PP 4.3",
        g3="Wypróbuje rozwiązanie wskazane przez nauczyciela i powie, czy pomogło — w 3 z 5 sytuacji.",
        g2="Wybierze rozwiązanie spośród dwóch, zastosuje je i oceni wynik — w 3 z 5 sytuacji.",
        g1="Zastosuje własne rozwiązanie, oceni skuteczność i zaproponuje poprawkę, gdy nie zadziałało — w 4 z 5 sytuacji.",
        m="karta „problem – próba – wynik” · obserwacja"),
   dict(n=15, t="Wyznacza wynik dodawania i odejmowania na zbiorach zastępczych",
        icf="d172", pp="PP 4.7",
        g3="Doliczy jeden element do zbioru i poda wynik, licząc na palcach z nauczycielem — w 3 z 5 prób.",
        g2="Doda i odejmie w zakresie 5, licząc na liczmanach — w 3 z 5 prób.",
        g1="Doda i odejmie w zakresie 10, wybierając sposób liczenia i uzasadniając wynik — w 4 z 5 prób.",
        m="liczmany · karty działań · zapis wyników"),
   dict(n=16, t="Przedstawia wartości liczbowe na różne sposoby graficzne",
        icf="d172", pp="PP 4.10",
        g3="Ułoży tyle klocków, ile pokazuje kropkowa karta — przy wzorze, w 3 z 5 prób.",
        g2="Przedstawi liczbę na dwa sposoby: kropkami i paskiem — w 3 z 5 prób.",
        g1="Zrobi wykres słupkowy z wynikiem zliczania w grupie i odczyta z niego, czego jest najwięcej — w 4 z 5 prób.",
        m="karty liczbowe · wykres grupy"),
   dict(n=17, t="Określa kierunki i relacje przestrzenne między obiektami",
        icf="d137", pp="PP 4.11",
        g3="Położy przedmiot „na” i „pod” według polecenia z pokazem — w 3 z 5 prób.",
        g2="Użyje określeń nad, pod, obok, za, przed, opisując położenie 5 przedmiotów — w 3 z 5 prób.",
        g1="Poprowadzi kolegę po sali samymi wskazówkami kierunkowymi do ukrytego przedmiotu — w 4 z 5 prób.",
        m="tor przeszkód · gra „ciepło-zimno” · obserwacja"),
   dict(n=18, t="Rozpoznaje figury geometryczne płaskie i niektóre bryły",
        icf="d137", pp="PP 4.13",
        g3="Dopasuje koło, trójkąt i kwadrat do wzoru — w 3 z 5 prób.",
        g2="Nazwie 4 figury płaskie i wskaże je w przedmiotach z sali — w 3 z 5 prób.",
        g1="Nazwie figury i dwie bryły, wskaże różnicę między kwadratem a sześcianem — w 4 z 5 prób.",
        m="zestaw figur i brył · karta obserwacji"),
   dict(n=19, t="Planuje i robi w grupie zakupy w sklepie",
        icf="d620", pp="PP DE-P.4",
        g3="Poda sprzedawcy jeden produkt z listy obrazkowej, przy wsparciu dorosłego — raz w roku.",
        g2="Odnajdzie 3 produkty z listy obrazkowej i zapłaci przygotowaną kwotą — raz w roku.",
        g1="Ułoży z grupą listę zakupów, odnajdzie produkty, zapłaci i sprawdzi resztę — raz w roku, z dokumentacją.",
        m="lista zakupów · zdjęcia z wyjścia · karta rozliczenia"),
  ]),

 dict(rom="V", icf="d1–d6", name="Obszar przyrodniczy", pts=9,
  zasob="Dziecko z wynikiem 4–5 prowadzi „dziennik przyrody” grupy: zapisuje obserwacje i przypomina "
        "innym, co zmieniło się od ostatniego tygodnia.",
  items=[
   dict(n=20, t="Rozpoznaje i nazywa rośliny, zwierzęta i elementy przyrody nieożywionej z najbliższego otoczenia",
        icf="d137", pp="PP 5.1",
        g3="Wskaże drzewo, kamień i ptaka na spacerze po nazwaniu ich przez nauczyciela — w 3 z 5 wyjść.",
        g2="Nazwie 6 roślin i zwierząt z ogrodu przedszkolnego — w 3 z 5 wyjść.",
        g1="Nazwie 10 elementów przyrody, dzieląc je na ożywione i nieożywione, i uzasadni podział — w 4 z 5 wyjść.",
        m="atlas grupy · karta spaceru badawczego"),
   dict(n=21, t="Bada otoczenie, wyciąga wnioski z obserwacji i opisuje zmiany oraz zjawiska pogodowe",
        icf="d163", pp="PP 5.2",
        g3="Powie, czy dziś jest ciepło czy zimno, po wspólnym sprawdzeniu za oknem — w 3 z 5 dni.",
        g2="Opisze pogodę trzema określeniami i zaznaczy ją w kalendarzu grupy — w 3 z 5 dni.",
        g1="Porówna pogodę z całego tygodnia, wskaże zmianę i powie, co się przez nią zmieniło w zabawach na dworze — w 4 z 5 tygodni.",
        m="kalendarz pogody · zapis wniosków"),
   dict(n=22, t="Dokumentuje zaobserwowane obiekty, zjawiska i procesy przyrodnicze",
        icf="d163", pp="PP 5.4",
        g3="Narysuje obserwowany obiekt na gotowej karcie z ramką — przy wsparciu, w 3 z 5 obserwacji.",
        g2="Narysuje i podpisze obserwację, zaznaczając datę — w 3 z 5 obserwacji.",
        g1="Poprowadzi serię 5 rysunków tego samego obiektu w czasie i opowie, co się zmieniło — w 4 z 5 serii.",
        m="dziennik obserwacji · karty z datami"),
   dict(n=23, t="Wskazuje na planie, mapie lub globusie znane mu miejsca",
        icf="d137", pp="PP 5.6",
        g3="Wskaże na planie sali swoje miejsce przy stole — przy podpowiedzi, w 3 z 5 prób.",
        g2="Wskaże na planie przedszkola 3 pomieszczenia i pokaże Polskę na globusie — w 3 z 5 prób.",
        g1="Narysuje plan drogi z sali do ogrodu i wskaże na mapie miejsce, w którym mieszka — w 4 z 5 prób.",
        m="plan sali i przedszkola · globus · rysunek trasy"),
   dict(n=24, t="Opisuje Ziemię jako kulę krążącą wokół Słońca razem z innymi planetami",
        icf="d137", pp="PP 5.7",
        g3="Wskaże model Ziemi wśród trzech przedmiotów — po nazwaniu przez nauczyciela, w 3 z 5 prób.",
        g2="Powie, że Ziemia jest kulą i krąży wokół Słońca, pokazując to modelem — w 3 z 5 prób.",
        g1="Pokaże ruch Ziemi wokół Słońca i wyjaśni, skąd bierze się dzień i noc — w 4 z 5 prób.",
        m="model Układu Słonecznego · zapis wyjaśnienia"),
   dict(n=25, t="Korzysta z narzędzi ogrodniczych przy pielęgnacji roślin",
        icf="d445", pp="PP 5.8",
        g3="Użyje konewki, prowadzony ręka w rękę przez dorosłego — w 3 z 5 dyżurów.",
        g2="Samodzielnie użyje konewki i grabek zgodnie z przeznaczeniem — w 3 z 5 dyżurów.",
        g1="Dobierze narzędzie do czynności, wykona ją i odłoży narzędzie na miejsce — w 4 z 5 dyżurów.",
        m="dyżury w kąciku przyrody · karta obserwacji"),
   dict(n=26, t="Opisuje zależności między wybranymi roślinami i zwierzętami",
        icf="d137", pp="PP 5.9",
        g3="Połączy w parę zwierzę z tym, co je — przy podpowiedzi obrazkowej, w 3 z 5 prób.",
        g2="Opowie o dwóch zależnościach (pszczoła i kwiat, ptak i drzewo) — w 3 z 5 prób.",
        g1="Ułoży prosty łańcuch zależności z trzech ogniw i wyjaśni, co się stanie, gdy jednego zabraknie — w 4 z 5 prób.",
        m="karty zależności · zapis wyjaśnienia"),
   dict(n=27, t="Rozpoznaje zwierzęta i rośliny z różnych ekosystemów i stref klimatycznych",
        icf="d137", pp="PP 5.10",
        g3="Dopasuje 3 zwierzęta do tła (las, morze, pustynia) — przy wzorze, w 3 z 5 prób.",
        g2="Przyporządkuje 6 zwierząt i roślin do trzech środowisk — w 3 z 5 prób.",
        g1="Wyjaśni, dlaczego niedźwiedź polarny nie żyje w lesie, wskazując cechę przystosowania — w 4 z 5 prób.",
        m="mapa środowisk · karty zwierząt"),
   dict(n=28, t="Prowadzi i ilustruje obserwacje przyrody",
        icf="d163", pp="PP DE-R.2",
        g3="Doklei obrazek do wspólnej karty obserwacji, wybierając z dwóch — raz w roku, w cyklu grupowym.",
        g2="Poprowadzi z grupą obserwację jednej rośliny przez 2 tygodnie i zilustruje 3 etapy — raz w roku.",
        g1="Poprowadzi własną obserwację przez miesiąc, zilustruje ją i przedstawi wnioski grupie — raz w roku, z dokumentacją.",
        m="dziennik obserwacji · wystawa ilustracji"),
  ]),

 dict(rom="VI", icf="d1–d4", name="Obszar techniczny", pts=10,
  zasob="Dziecko z wynikiem 4–5 prowadzi „warsztat”: pokazuje innym, jak bezpiecznie użyć narzędzia "
        "i sprawdza, czy konstrukcja się trzyma.",
  items=[
   dict(n=29, t="Ustala właściwości różnych materiałów",
        icf="d137", pp="PP 6.1",
        g3="Wskaże materiał twardy i miękki spośród dwóch, po dotknięciu obu — w 3 z 5 prób.",
        g2="Opisze 4 materiały określeniami: twardy, miękki, gładki, szorstki — w 3 z 5 prób.",
        g1="Sprawdzi doświadczalnie, który materiał przepuszcza wodę, i wyjaśni wynik — w 4 z 5 prób.",
        m="pudełko materiałów · karta doświadczenia"),
   dict(n=30, t="Wymienia etapy budowania obiektów i rozróżnia materiały budowlane",
        icf="d137", pp="PP 6.2",
        g3="Ułoży 2 obrazki budowy we właściwej kolejności — przy wzorze, w 3 z 5 prób.",
        g2="Ułoży 4 etapy budowy domu i nazwie dwa materiały budowlane — w 3 z 5 prób.",
        g1="Opowie o budowie w 5 etapach i wyjaśni, dlaczego fundament jest pierwszy — w 4 z 5 prób.",
        m="historyjka budowy · próbki materiałów"),
   dict(n=31, t="Buduje maszyny proste — kołowrót, równię pochyłą — i wyjaśnia ich zastosowanie",
        icf="d155", pp="PP 6.4",
        g3="Spuści przedmiot po gotowej równi pochyłej i powie, że zjeżdża — w 3 z 5 prób.",
        g2="Zbuduje równię pochyłą z deski i klocków, sprawdzi, co zjeżdża szybciej — w 3 z 5 prób.",
        g1="Zbuduje kołowrót do wciągania ciężarka i wskaże urządzenie domowe, które działa podobnie — w 4 z 5 prób.",
        m="zestaw konstrukcyjny · karta doświadczenia"),
   dict(n=32, t="Buduje obwody elektryczne z żarówką, brzęczykiem i silnikiem",
        icf="d155", pp="PP 6.5",
        g3="Dołączy ostatni przewód w przygotowanym obwodzie i zobaczy zapalenie żarówki — w 3 z 5 prób.",
        g2="Zbuduje obwód z baterii, przewodów i żarówki według schematu — w 3 z 5 prób.",
        g1="Zbuduje obwód z brzęczykiem, znajdzie przyczynę, gdy nie działa, i naprawi go — w 4 z 5 prób.",
        m="zestaw obwodów bezpiecznych · schemat · obserwacja"),
   dict(n=33, t="Wskazuje przykłady urządzeń zasilanych energią z różnych źródeł",
        icf="d137", pp="PP 6.6",
        g3="Wskaże urządzenie na baterie spośród dwóch przedmiotów — przy podpowiedzi, w 3 z 5 prób.",
        g2="Przyporządkuje 4 urządzenia do źródeł: bateria, gniazdko, słońce, siła rąk — w 3 z 5 prób.",
        g1="Poda po dwa przykłady urządzeń dla trzech źródeł energii i powie, które nie zużywa prądu — w 4 z 5 prób.",
        m="karty urządzeń · tablica źródeł energii"),
   dict(n=34, t="Przestrzega zasad bezpiecznego korzystania z urządzeń elektrycznych i narzędzi",
        icf="d571", pp="PP 6.7",
        g3="Zatrzyma się na sygnał „stop” przy gniazdku lub narzędziu — w 3 z 5 sytuacji.",
        g2="Wymieni 3 zasady bezpieczeństwa i zastosuje je w pracy z narzędziem — w 3 z 5 zajęć.",
        g1="Sprawdzi przed pracą, czy stanowisko jest bezpieczne, i zwróci uwagę koledze łamiącemu zasadę — w 4 z 5 zajęć.",
        m="regulamin warsztatu · karta obserwacji"),
   dict(n=35, t="Podaje przykłady maszyn i urządzeń, które ułatwiają ludziom życie",
        icf="d137", pp="PP 6.8",
        g3="Wskaże obrazek urządzenia, które pomaga w kuchni — spośród trzech, w 3 z 5 prób.",
        g2="Poda 4 urządzenia i powie, w czym każde pomaga — w 3 z 5 prób.",
        g1="Porówna czynność wykonaną ręcznie i z urządzeniem, wskazując, co się zmienia — w 4 z 5 prób.",
        m="karty urządzeń · zapis porównania"),
   dict(n=36, t="Opisuje środki transportu i infrastrukturę w okolicy oraz bezpieczne sposoby korzystania z nich",
        icf="d470", pp="PP 6.9",
        g3="Nazwie 2 środki transportu widziane na spacerze — po nazwaniu przez nauczyciela, w 3 z 5 wyjść.",
        g2="Nazwie 4 środki transportu i wskaże przejście dla pieszych oraz przystanek — w 3 z 5 wyjść.",
        g1="Opowie, jak bezpiecznie wsiąść do autobusu i przejść przez jezdnię, i zastosuje to w praktyce — w 4 z 5 wyjść.",
        m="karta spaceru komunikacyjnego · obserwacja zachowań"),
   dict(n=37, t="Przez minimum 10 kolejnych dni tworzy własne zabawki z materiałów, w tym z odzysku",
        icf="d155", pp="PP DE-P.1",
        g3="Doklei element do wspólnej zabawki w 5 z 10 dni, przy wsparciu dorosłego — raz w edukacji przedszkolnej.",
        g2="Wykona własną zabawkę w cyklu 10 dni, wracając do niej każdego dnia — raz w edukacji przedszkolnej.",
        g1="Zaplanuje zabawkę, dobierze materiały z odzysku, poprawi ją po próbie i pokaże grupie — raz w edukacji przedszkolnej.",
        m="karta projektu 10 dni · zdjęcia etapów · wystawa"),
   dict(n=38, t="Pracując w grupie, przygotowuje makietę wybranej przestrzeni",
        icf="d155", pp="PP DE-P.2",
        g3="Umieści przydzielony element na wspólnej makiecie — przy wskazaniu miejsca, raz w edukacji przedszkolnej.",
        g2="Wykona z grupą fragment makiety okolicy i nazwie, co przedstawia — raz w edukacji przedszkolnej.",
        g1="Zaplanuje z grupą makietę, rozdzieli zadania i oprowadzi po niej gości — raz w edukacji przedszkolnej.",
        m="makieta grupy · karta podziału zadań · zdjęcia"),
  ]),

 dict(rom="VII", icf="d1–d5", name="Obszar cyfrowy", pts=4,
  zasob="Dziecko z wynikiem 4–5 pilnuje „umowy ekranowej” grupy: przypomina, kiedy odkładamy urządzenia.",
  items=[
   dict(n=39, t="Rozpoznaje urządzenia cyfrowe i określa, do czego służą",
        icf="d360", pp="PP 7.2",
        g3="Wskaże tablet spośród trzech przedmiotów po nazwaniu przez nauczyciela — w 3 z 5 prób.",
        g2="Nazwie 4 urządzenia cyfrowe i powie, do czego służy każde — w 3 z 5 prób.",
        g1="Dobierze urządzenie do zadania (zdjęcie, rozmowa, wyszukanie) i uzasadni wybór — w 4 z 5 prób.",
        m="karty urządzeń · zapis uzasadnień"),
   dict(n=40, t="Wskazuje podstawowe zasady higieny cyfrowej",
        icf="d570", pp="PP 7.3",
        g3="Odłoży urządzenie na sygnał dźwiękowy końca czasu — przy wsparciu dorosłego, w 3 z 5 sytuacji.",
        g2="Wymieni 3 zasady: przerwa dla oczu, odległość od ekranu, koniec przed snem — w 3 z 5 rozmów.",
        g1="Ułoży plan dnia z czasem na ekran i bez ekranu i wyjaśni, dlaczego przerwy są potrzebne — w 4 z 5 prób.",
        m="umowa ekranowa grupy · plan dnia · obserwacja"),
   dict(n=41, t="Wskazuje zagrożenia związane z korzystaniem z internetu, w tym z udostępniania informacji o sobie",
        icf="d571", pp="PP 7.4",
        g3="Powie „nie mówię” na pytanie o adres w scence z obcą postacią — po przypomnieniu zasady, w 3 z 5 scenek.",
        g2="Wymieni 3 informacje, których nie podaje się w sieci, i wskaże dorosłego, do którego idzie po pomoc — w 3 z 5 rozmów.",
        g1="Rozpozna w 4 scenkach sytuację niebezpieczną, powie, co zrobić, i uzasadni — w 4 z 5 scenek.",
        m="scenki bezpieczeństwa · karta „mówię dorosłemu”"),
   dict(n=42, t="Określa wpływ mediów na życie codzienne, rozpoznaje reklamy i wie, czemu służą",
        icf="d163", pp="PP 7.5",
        g3="Wskaże reklamę wśród dwóch obrazków po podpowiedzi nauczyciela — w 3 z 5 prób.",
        g2="Rozpozna reklamę i powie, że zachęca do kupienia — w 3 z 5 prób.",
        g1="Porówna reklamę z rzeczywistym produktem i wskaże, co reklama przedstawia korzystniej — w 4 z 5 prób.",
        m="zestaw reklam · zapis porównania"),
  ]),

 dict(rom="VIII", icf="d1–d9", name="Obszar artystyczny", pts=4,
  zasob="Dziecko z wynikiem 4–5 prowadzi „kącik dźwięków”: dobiera muzykę do nastroju zajęć "
        "i tłumaczy innym, dlaczego pasuje.",
  items=[
   dict(n=43, t="Łączy poznane elementy w nowe układy, w nieoczywisty sposób",
        icf="d155", pp="PP 8.2",
        g3="Dołoży jeden element do układu zaczętego przez nauczyciela — w 3 z 5 prób.",
        g2="Zbuduje własny układ z 4 różnych elementów i nazwie, co powstało — w 3 z 5 prób.",
        g1="Połączy elementy z dwóch różnych zbiorów (dźwięk i kształt) w jedną pracę i wyjaśni pomysł — w 4 z 5 prób.",
        m="pudełko tworzyw · zdjęcia prac · zapis wyjaśnień"),
   dict(n=44, t="Rozpoznaje instrumenty muzyczne, tworzy własne z różnych materiałów i gra na nich",
        icf="d920", pp="PP 8.5",
        g3="Zagra na gotowej grzechotce na sygnał nauczyciela — w 3 z 5 zajęć.",
        g2="Rozpozna 4 instrumenty po dźwięku i wykona własną grzechotkę — w 3 z 5 zajęć.",
        g1="Wykona instrument z odzysku, dobierze materiał do żądanego brzmienia i zagra partię w orkiestrze — w 4 z 5 zajęć.",
        m="zestaw instrumentów · instrumenty własne · nagranie"),
   dict(n=45, t="Zauważa różnice w dynamice, tempie, barwie i wysokości dźwięków, określa nastrój muzyki",
        icf="d115", pp="PP 8.7",
        g3="Pokaże gestem „głośno” i „cicho” w trakcie słuchania — przy wzorze nauczyciela, w 3 z 5 prób.",
        g2="Określi tempo i głośność utworu oraz powie, czy jest wesoły czy smutny — w 3 z 5 prób.",
        g1="Porówna dwa utwory pod względem tempa, barwy i nastroju i uzasadni różnicę — w 4 z 5 prób.",
        m="zestaw nagrań · karty nastrojów · zapis wypowiedzi"),
   dict(n=46, t="Wyjaśnia pojęcia określające sposoby wyrazu artystycznego w muzyce, sztukach wizualnych i teatrze",
        icf="d137", pp="PP 8.8",
        g3="Dopasuje obrazek do dziedziny: muzyka, obraz, teatr — przy podpowiedzi, w 3 z 5 prób.",
        g2="Powie, czym różni się obraz od przedstawienia, podając po jednej cesze — w 3 z 5 prób.",
        g1="Użyje określeń rytm, barwa, kompozycja, rola, opisując trzy dzieła z różnych dziedzin — w 4 z 5 prób.",
        m="reprodukcje i nagrania · słowniczek grupy"),
  ]),

 dict(rom="IX", icf="d4–d9", name="Obszar ruchowy", pts=2,
  zasob="Dziecko z wynikiem 4–5 prowadzi rozgrzewkę grupy i pilnuje, by wszyscy mieli miejsce na ruch.",
  items=[
   dict(n=47, t="Orientuje się w schemacie własnego ciała i wykorzystuje zmysły w zadaniach ruchowych",
        icf="d445", pp="PP 9.3",
        g3="Dotknie części ciała nazwanej przez nauczyciela, naśladując pokaz — w 3 z 5 prób.",
        g2="Nazwie i pokaże 8 części ciała oraz wykona ruch prawą i lewą ręką na polecenie — w 3 z 5 prób.",
        g1="Przejdzie tor przeszkód z zasłoniętymi oczami, kierując się słuchem i dotykiem, i opisze, co pomogło — w 4 z 5 prób.",
        m="tor przeszkód · karta schematu ciała · obserwacja"),
   dict(n=48, t="Uczestniczy w wydarzeniu promującym zdrowy styl życia",
        icf="d920", pp="PP DE-R.6",
        g3="Weźmie udział w jednej konkurencji, prowadzony przez dorosłego — raz w roku.",
        g2="Weźmie udział w trzech konkurencjach zawodów przedszkolnych, przestrzegając zasad — raz w roku.",
        g1="Pomoże przygotować zawody (plakat, sprzęt), weźmie w nich udział i opowie, po co dbamy o ruch — raz w roku, z dokumentacją.",
        m="karta wydarzenia · zdjęcia · zapis wypowiedzi"),
  ]),
]
