# -*- coding: utf-8 -*-
"""Bank celów SMART — KPOF wersja C (6 lat). 44 twierdzenia, 9 obszarów ICF."""

WERSJA = dict(
    kod="C", etykieta="6 lat", zakres="44 twierdzenia · d1–d9",
    dziecko="wersja C · roczne przygotowanie przedszkolne",
    opis="Rok gotowości szkolnej. Cele opisują nie samą umiejętność, lecz jej trwałość: samodzielność, "
         "wytrwałość mimo trudności i przeniesienie umiejętności na nową sytuację.",
)

AREAS = [
 dict(rom="I", icf="d1", name="Uczenie się i stosowanie wiedzy", pts=25,
  zasob="Dziecko z wynikiem 4–5 prowadzi „kącik badacza”: formułuje pytanie, sprawdza je i przedstawia "
        "wynik grupie — to najlepsze przygotowanie do roli ucznia.",
  items=[
   dict(n=1, t="Odpowiada na pytania, objaśnia kolejność zdarzeń w prostych historyjkach obrazkowych",
        icf="d163", pp="PP 3.12",
        g3="Ułoży historyjkę z 3 obrazków według wzoru pokazanego przez nauczyciela i opowie o pierwszym z nich — w 3 z 5 prób.",
        g2="Ułoży historyjkę z 4 obrazków we właściwej kolejności i opowie ją w 3 zdaniach — w 3 z 5 prób.",
        g1="Ułoży historyjkę z 5 obrazków, opowie ją z użyciem słów „najpierw – potem – na końcu” i wyjaśni przyczynę zdarzenia — w 4 z 5 prób.",
        m="zestaw historyjek obrazkowych · zapis wypowiedzi"),
   dict(n=2, t="Podejmuje próby samodzielnego czytania wyrazów i krótkich tekstów",
        icf="d140", pp="PP 3.17",
        g3="Dokona syntezy sylabowej wyrazu 2-sylabowego po podaniu sylab przez nauczyciela — w 3 z 5 prób.",
        g2="Przeczyta 5 wyrazów 2-sylabowych metodą sylabową i dopasuje je do obrazków — w 3 z 5 prób.",
        g1="Przeczyta krótkie zdanie ze zrozumieniem i wykona zapisane w nim polecenie — w 4 z 5 prób.",
        m="karty wyrazów i zdań · liczba poprawnych odczytów"),
   dict(n=3, t="Kreśli kształty literopodobne i podejmuje próby pisania liter, planuje ruch przed zapisaniem znaku",
        icf="d145", pp="PP 3.15·3.16",
        g3="Odtworzy szlaczek literopodobny po śladzie, utrzymując kierunek kreślenia, w liniaturze poszerzonej — w 3 z 5 prób.",
        g2="Napisze 5 liter w liniaturze według wzoru, zachowując kierunek i proporcje — w 3 z 5 prób.",
        g1="Napisze swoje imię i 5 wyrazów w liniaturze, planując ruch przed zapisem i mieszcząc się w liniach — w 4 z 5 prób.",
        m="karta pracy grafomotorycznej · ocena poprawności"),
   dict(n=4, t="Przelicza, odczytuje zapis cyfrowy liczb, dodaje i odejmuje w sytuacji użytkowej",
        icf="d150", pp="PP 4.6·4.9",
        g3="Policzy zbiór do 6 i dopasuje do niego cyfrę spośród trzech, po pokazie wzorca — w 3 z 5 prób.",
        g2="Odczyta cyfry 1–10 i wykona dodawanie w zakresie 5 na konkretach — w 3 z 5 prób.",
        g1="Rozwiąże zadanie użytkowe (zakupy w kąciku) z dodawaniem i odejmowaniem w zakresie 10 i uzasadni wynik — w 4 z 5 prób.",
        m="zadania użytkowe z liczbami · karta wyników"),
   dict(n=5, t="Eksperymentuje, szacuje, waży i mierzy, sprawdza trafność swoich przypuszczeń",
        icf="d175", pp="PP 4.8·5.3",
        g3="Porówna 2 przedmioty pod względem ciężaru lub długości, wskazując „większy”, po pokazie sposobu porównania — w 3 z 5 prób.",
        g2="Uszereguje 4 przedmioty według długości lub ciężaru i sprawdzi wynik miarką lub wagą — w 3 z 5 prób.",
        g1="Postawi przypuszczenie („to będzie cięższe”), sprawdzi je pomiarem i powie, czy się potwierdziło — w 4 z 5 doświadczeń.",
        m="karta doświadczenia · zapis hipotezy i wyniku"),
  ]),

 dict(rom="II", icf="d2", name="Ogólne zadania i wymagania", pts=25,
  zasob="Dziecko planujące swoją pracę zostaje „kapitanem zespołu” przy zadaniach projektowych — "
        "rozdziela etapy i pilnuje ich kolejności, ćwicząc funkcje wykonawcze w naturalnej sytuacji.",
  items=[
   dict(n=6, t="Układa plan działania prowadzący do zakładanego rezultatu i realizuje go etapami",
        icf="d220", pp="PP 2.3",
        g3="Ułoży plan 2-etapowy z gotowych obrazków, po wskazaniu pierwszego kroku przez nauczyciela — w 3 z 5 zadań.",
        g2="Ułoży plan 3-etapowy i zrealizuje go, odhaczając kolejne kroki — w 3 z 5 zadań.",
        g1="Samodzielnie zaplanuje 4 etapy pracy, zrealizuje je i sprawdzi zgodność efektu z zamiarem — w 4 z 5 zadań.",
        m="karta planu · liczba zrealizowanych etapów"),
   dict(n=7, t="Pracuje samodzielnie i wytrwale przez czas zajęć kierowanych",
        icf="d210", pp="PP 2.6",
        g3="Pracuje samodzielnie przez 5 minut zajęcia, po czym korzysta z krótkiej przerwy sensorycznej — w 3 z 5 zajęć.",
        g2="Pracuje samodzielnie przez 15 minut zajęcia, zgłaszając potrzebę pomocy zamiast przerywania — w 3 z 5 zajęć.",
        g1="Pracuje samodzielnie przez całe 25-minutowe zajęcie i doprowadza zadanie do końca — w 4 z 5 zajęć.",
        m="pomiar czasu pracy samodzielnej · zapis przerwań"),
   dict(n=8, t="Radzi sobie z przegraną i porażką, traktuje błędy jako naturalny element uczenia się",
        icf="d240", pp="PP 2.8·9.2",
        g3="Po przegranej pozostanie przy stole przez kolejną rundę gry, korzystając z umówionego gestu wsparcia — w 3 z 5 gier.",
        g2="Po przegranej nazwie swoją emocję i dokończy grę bez przerywania zabawy innym — w 3 z 5 gier.",
        g1="Przyjmie przegraną, pogratuluje zwycięzcy i wskaże, co poprawi następnym razem — w 4 z 5 gier.",
        m="gry z regułami · karta reakcji na przegraną"),
   dict(n=9, t="Stosuje się do rytmu dnia i zasad, posługuje się pojęciami następstwa czasu (wczoraj–dzisiaj–jutro)",
        icf="d230", pp="PP 4.12",
        g3="Wskaże na planie dnia aktywność „teraz” i „potem”, po pytaniu naprowadzającym — w 3 z 5 prób.",
        g2="Użyje poprawnie pojęć wczoraj–dzisiaj–jutro w rozmowie o planie dnia — w 3 z 5 rozmów.",
        g1="Opowie o wydarzeniach z wczoraj i zaplanuje jutro, posługując się nazwami dni tygodnia — w 4 z 5 rozmów.",
        m="kalendarz grupowy · zapis wypowiedzi"),
   dict(n=10, t="Doprowadza zadania do końca mimo trudności; stosuje znane sposoby radzenia sobie ze stresem",
        icf="d240", pp="PP 2.6·2.12",
        g3="W sytuacji trudności skorzysta z umówionej strategii (oddech, przerwa) zaproponowanej przez dorosłego i wróci do zadania — w 3 z 5 sytuacji.",
        g2="Samodzielnie wybierze strategię z tablicy strategii i dokończy zadanie po przerwie — w 3 z 5 sytuacji.",
        g1="Rozpozna narastające napięcie, zastosuje wybraną strategię i dokończy zadanie bez pomocy dorosłego — w 4 z 5 sytuacji.",
        m="tablica strategii · rejestr zastosowań"),
  ]),

 dict(rom="III", icf="d3", name="Porozumiewanie się", pts=25,
  zasob="Sprawność językowa daje dziecku rolę „redaktora grupy”: zapisuje (dyktuje) kronikę dnia, "
        "przez co ćwiczy planowanie wypowiedzi i wspiera dzieci z trudnością narracyjną.",
  items=[
   dict(n=11, t="Mówi płynnie i wyraźnie, prawidłowo wypowiada głoski, dba o poprawność zdań",
        icf="d330", pp="PP 3.2·3.14",
        g3="Powtórzy poprawnie ćwiczoną głoskę w izolacji i w sylabach w 8 z 10 powtórzeń podczas zajęć logopedycznych.",
        g2="Użyje ćwiczonej głoski poprawnie w wyrazach i krótkich zdaniach podczas zajęć — w 3 z 5 zajęć.",
        g1="Utrzyma poprawną wymowę ćwiczonej głoski w mowie spontanicznej w sali — w 4 z 5 obserwacji.",
        m="karta logopedyczna · próbka mowy spontanicznej"),
   dict(n=12, t="Dokonuje analizy i syntezy głoskowej wybranych wyrazów",
        icf="d310", pp="PP 3.14",
        g3="Wskaże pierwszą głoskę w wyrazie 3-głoskowym po przedłużeniu jej przez nauczyciela — w 3 z 5 prób.",
        g2="Dokona analizy głoskowej wyrazu 3-głoskowego i syntezy wyrazu podanego głoskami — w 3 z 5 prób.",
        g1="Dokona analizy i syntezy wyrazu 5-głoskowego oraz wskaże głoskę w środku wyrazu — w 4 z 5 prób.",
        m="zestaw wyrazów do analizy · karta wyników"),
   dict(n=13, t="Odtwarza i przekształca treść bajek, tworzy własne historie, opowiada historyjki obrazkowe",
        icf="d330", pp="PP 3.8·3.12",
        g3="Odtworzy 2 wydarzenia z wysłuchanej bajki, korzystając z obrazków jako podpowiedzi — w 3 z 5 prób.",
        g2="Opowie treść bajki w 4 zdaniach z zachowaniem kolejności zdarzeń — w 3 z 5 prób.",
        g1="Ułoży własne zakończenie znanej bajki i opowie je grupie w spójnej, 6-zdaniowej wypowiedzi — w 4 z 5 prób.",
        m="karta narracji · zapis wypowiedzi dziecka"),
   dict(n=14, t="Uczestniczy w rozmowie, przedstawia i próbuje uzasadnić swoją opinię wobec dziecka i grupy",
        icf="d350", pp="PP 3.1",
        g3="Wypowie się na temat w kręgu po wywołaniu imieniem i podaniu początku zdania — w 3 z 5 spotkań.",
        g2="Przedstawi swoje zdanie w rozmowie grupowej, czekając na swoją kolej — w 3 z 5 spotkań.",
        g1="Przedstawi opinię i uzasadni ją („uważam tak, ponieważ…”), odnosząc się do zdania innego dziecka — w 4 z 5 spotkań.",
        m="krąg dyskusyjny · rejestr wypowiedzi"),
   dict(n=15, t="Reaguje na proste polecenia w języku obcym nowożytnym",
        icf="d310", pp="PP 3.19",
        g3="Zareaguje ruchem na 2 znane polecenia w języku obcym poparte gestem — w 3 z 5 zajęć.",
        g2="Zareaguje poprawnie na 5 poleceń w języku obcym bez gestu wspierającego — w 3 z 5 zajęć.",
        g1="Zareaguje na polecenia i odpowie pojedynczymi słowami w języku obcym w zabawie — w 4 z 5 zajęć.",
        m="obserwacja zajęć języka obcego · karta reakcji"),
  ]),

 dict(rom="IV", icf="d4", name="Poruszanie się", pts=25,
  zasob="Sprawność motoryczna sześciolatka jest bezpośrednim zapleczem pisania — dziecko z zasobem "
        "prowadzi rozgrzewkę dłoni dla grupy przed pracą przy stoliku.",
  items=[
   dict(n=16, t="Wykazuje koordynację, równowagę, zwinność i sprawność pozwalające na naukę czytania i pisania",
        icf="d455", pp="PP 9.4·3.15",
        g3="Wykona 3 ćwiczenia koordynacji wzrokowo-ruchowej z pokazem nauczyciela, utrzymując pozycję — w 3 z 5 zajęć.",
        g2="Wykona zestaw 5 ćwiczeń koordynacyjnych po instrukcji słownej, przekraczając linię środkową ciała — w 3 z 5 zajęć.",
        g1="Wykona sekwencję ćwiczeń naprzemiennych w zadanym tempie i utrzyma równowagę przez 10 sekund — w 4 z 5 zajęć.",
        m="zestaw prób sprawnościowych · karta wyników"),
   dict(n=17, t="Dba o prawidłową postawę ciała podczas aktywności i pracy przy stoliku",
        icf="d415", pp="PP 9.8",
        g3="Utrzyma prawidłową pozycję przy stoliku przez 5 minut, korzystając z podnóżka i przypomnienia dorosłego — w 3 z 5 zajęć.",
        g2="Utrzyma prawidłową postawę przez 10 minut po jednym przypomnieniu wizualnym — w 3 z 5 zajęć.",
        g1="Samodzielnie koryguje swoją postawę podczas całej pracy przy stoliku — w 4 z 5 zajęć.",
        m="obserwacja pozycji przy stoliku · zapis korekt"),
   dict(n=18, t="Prawidłowo trzyma narzędzie pisarskie i kontroluje siłę nacisku podczas kreślenia liter",
        icf="d440", pp="PP 9.6·3.15",
        g3="Utrzyma chwyt trójpalcowy przez 5 minut kreślenia, z nasadką korygującą — w 3 z 5 prób.",
        g2="Utrzyma prawidłowy chwyt i nacisk przez całą kartę pracy, bez przedzierania papieru — w 3 z 5 kart.",
        g1="Utrzyma prawidłowy chwyt i równy nacisk podczas 15-minutowego pisania w liniaturze — w 4 z 5 zajęć.",
        m="karty pracy · ocena nacisku i chwytu"),
   dict(n=19, t="Wykonuje czynności precyzyjne: zapinanie guzików, wiązanie sznurowadeł",
        icf="d440", pp="PP 9.7·9.5",
        g3="Zapnie 2 duże guziki na pomocy dydaktycznej po pokazie i podaniu materiału — w 3 z 5 prób.",
        g2="Zapnie guziki i suwak we własnym ubraniu oraz wykona pierwszy węzeł sznurowadła — w 3 z 5 wyjść.",
        g1="Zawiąże sznurowadła i zapnie wszystkie zapięcia samodzielnie, w czasie przewidzianym dla grupy — w 4 z 5 wyjść.",
        m="obserwacja w szatni · karta czynności precyzyjnych"),
   dict(n=20, t="Wyraża ruchem charakter muzyki, tworzy improwizacje ruchowe, reaguje na sygnały",
        icf="d455", pp="PP 8.4",
        g3="Zmieni rodzaj ruchu na sygnał dźwiękowy, naśladując nauczyciela — w 3 z 5 zajęć.",
        g2="Dopasuje ruch do charakteru muzyki (wolno–szybko) bez pokazu — w 3 z 5 zajęć.",
        g1="Stworzy własną improwizację ruchową do utworu i zaprezentuje ją grupie — w 4 z 5 zajęć.",
        m="obserwacja zajęć rytmicznych · zapis improwizacji"),
  ]),

 dict(rom="V", icf="d5", name="Dbanie o siebie", pts=25,
  zasob="Pełna samoobsługa sześciolatka to warunek startu szkolnego — dziecko z zasobem pełni funkcję "
        "„przewodnika po szatni” dla młodszej grupy podczas wspólnych wyjść.",
  items=[
   dict(n=21, t="Wykonuje precyzyjne czynności samoobsługowe: guziki, suwaki, sznurowadła",
        icf="d540", pp="PP 9.7",
        g3="Zapnie suwak, gdy dorosły złączy jego początek, oraz 2 guziki we własnym ubraniu — w 3 z 5 wyjść.",
        g2="Zapnie samodzielnie suwak i wszystkie guziki, prosząc o pomoc wyłącznie przy sznurowadłach — w 3 z 5 wyjść.",
        g1="Wykona wszystkie czynności samoobsługowe samodzielnie, także w pośpiechu i przy zmęczeniu — w 4 z 5 wyjść.",
        m="karta samoobsługi · pomiar czasu w szatni"),
   dict(n=22, t="Spożywa posiłki z użyciem sztućców, nakłada je sobie samodzielnie",
        icf="d550", pp="PP 9.7·WSR",
        g3="Nałoży sobie porcję z podanego naczynia z pomocą dorosłego przy trzymaniu łyżki serwującej — w 3 z 5 posiłków.",
        g2="Nałoży sobie porcję samodzielnie i zje posiłek z użyciem noża i widelca — w 3 z 5 posiłków.",
        g1="Zaplanuje wielkość porcji, nałoży ją, zje kulturalnie i posprząta miejsce po sobie — w 4 z 5 posiłków.",
        m="obserwacja posiłku · karta samodzielności"),
   dict(n=23, t="Dba o higienę samodzielnie i z własnej inicjatywy, wyjaśnia zasady zdrowego stylu życia",
        icf="d510–d520", pp="PP 9.7·9.8",
        g3="Wykona czynności higieniczne po przypomnieniu indywidualnym, według instrukcji obrazkowej — w 4 z 5 sytuacji.",
        g2="Wykona czynności higieniczne z własnej inicjatywy w sytuacjach rutynowych — w 3 z 5 dni.",
        g1="Dba o higienę z własnej inicjatywy i wyjaśni innym 3 zasady zdrowego stylu życia — w 4 z 5 dni.",
        m="lista kontrolna higieny · rozmowa o zdrowiu"),
   dict(n=24, t="Przestrzega zasad bezpieczeństwa, w tym prawidłowego zachowania na drodze i w środkach komunikacji",
        icf="d571", pp="PP 1.6·9.11",
        g3="Zatrzyma się przed krawężnikiem na sygnał dorosłego, idąc w parze i trzymając za rękę — w 4 z 5 wyjść.",
        g2="Wymieni 3 zasady bezpiecznego przechodzenia przez jezdnię i zastosuje je pod nadzorem — w 3 z 5 wyjść.",
        g1="Przestrzega zasad ruchu drogowego i zachowania w autobusie, przypominając o nich młodszym dzieciom — w 4 z 5 wyjść.",
        m="karta wyjść poza teren · obserwacja"),
   dict(n=25, t="Rozpoznaje u siebie zmęczenie i przeciążenie oraz sytuacje zagrażające bezpieczeństwu lub autonomii",
        icf="d571", pp="PP 9.9·9.10",
        g3="Wskaże na skali obrazkowej swój poziom zmęczenia po pytaniu dorosłego — w 3 z 5 sytuacji.",
        g2="Zgłosi zmęczenie lub przeciążenie zanim pojawi się reakcja emocjonalna, korzystając z umówionego sygnału — w 3 z 5 sytuacji.",
        g1="Rozpozna i nazwie sytuację zagrażającą (przekroczenie granic, presja rówieśnicza), odmówi i zgłosi ją dorosłemu — w 4 z 5 sytuacji.",
        m="skala obrazkowa · rejestr zgłoszeń dziecka"),
  ]),

 dict(rom="VI", icf="d6", name="Życie domowe (czynności użyteczne)", pts=20, opis_flag=True,
  zasob="Obszar opisowy — poza wynikiem ogólnym. U sześciolatka to gotowe pole ćwiczenia obowiązku "
        "szkolnego: stały dyżur, rozliczany co tydzień, uczy odpowiedzialności lepiej niż pogadanka.",
  items=[
   dict(n=26, t="Nakrywa do stołu, samodzielnie nakłada posiłek i sprząta po posiłku",
        icf="d640", pp="PP WSR·Zad.7",
        g3="Rozłoży sztućce dla 2 osób według wzoru obrazkowego, przy dorosłym obok — w 3 z 5 posiłków.",
        g2="Nakryje do stołu dla całego stolika według wzoru i posprząta swoje naczynia — w 3 z 5 posiłków.",
        g1="Nakryje, obsłuży stolik i posprząta po posiłku samodzielnie, planując kolejność czynności — w 4 z 5 posiłków.",
        m="grafik dyżurów · karta wykonania"),
   dict(n=27, t="Pełni dyżury i drobne obowiązki na rzecz grupy",
        icf="d640", pp="PP 1.10·WSR",
        g3="Wykona 1 czynność dyżurnego według obrazka, po przypomnieniu indywidualnym — w 3 z 5 dyżurów.",
        g2="Wykona pełny dyżur bez przypomnień, zgłaszając jego zakończenie — w 3 z 5 dyżurów.",
        g1="Pełni dyżur tygodniowy, planuje czynności i rozlicza się z niego na kręgu podsumowującym — w 4 z 5 tygodni.",
        m="grafik dyżurów · karta rozliczenia tygodnia"),
   dict(n=28, t="Utrzymuje porządek w swoich rzeczach i najbliższej przestrzeni",
        icf="d650", pp="PP 2.5",
        g3="Uporządkuje swoją półkę, gdy dorosły wskazuje kolejne rzeczy do odłożenia — w 3 z 5 dni.",
        g2="Uporządkuje swoje miejsce i półkę po sygnale, sprawdzając efekt według zdjęcia — w 3 z 5 dni.",
        g1="Utrzymuje porządek w swoich rzeczach przez cały dzień bez przypomnień i reaguje na nieporządek w kąciku — w 4 z 5 dni.",
        m="zdjęcie wzorcowe półki · zapis dzienny"),
   dict(n=29, t="Wykonuje czynności użyteczne: podlewa i pielęgnuje rośliny, opiekuje się kącikiem przyrody",
        icf="d640–d650", pp="PP 5.5·DE-R.3",
        g3="Podleje roślinę odmierzoną porcją wody, prowadzony przez dorosłego — w 3 z 5 dyżurów.",
        g2="Wykona pielęgnację 2 roślin według instrukcji obrazkowej, bez pomocy — w 3 z 5 dyżurów.",
        g1="Prowadzi kącik przyrody: planuje podlewanie, obserwuje zmiany i relacjonuje je grupie — w 4 z 5 tygodni.",
        m="dziennik kącika przyrody · zapis obserwacji"),
  ]),

 dict(rom="VII", icf="d7", name="Wzajemne kontakty i związki międzyludzkie", pts=25,
  zasob="U sześciolatka zasób społeczny wykorzystujemy w mediacji rówieśniczej: dziecko uczy się roli "
        "„pomocnika w sporze” według stałego, trzykrokowego schematu.",
  items=[
   dict(n=30, t="Bierze udział w podejmowaniu decyzji w grupie i akceptuje wspólne decyzje, nawet niezgodne z jego oczekiwaniami",
        icf="d720", pp="PP 1.3·1.4",
        g3="Weźmie udział w głosowaniu grupowym, wskazując swój wybór na kartce, i pozostanie w aktywności po ogłoszeniu wyniku — w 3 z 5 decyzji.",
        g2="Zaakceptuje decyzję większości bez protestu i włączy się w wybraną aktywność — w 3 z 5 decyzji.",
        g1="Przedstawi swoją propozycję, przyjmie decyzję grupy i wyjaśni, dlaczego wspólny wybór jest wiążący — w 4 z 5 decyzji.",
        m="krąg decyzyjny · rejestr reakcji na wynik"),
   dict(n=31, t="Przestrzega zasad zachowania w grupie, szanuje różne upodobania i potrzeby dzieci",
        icf="d720", pp="PP 1.6·1.8",
        g3="Zastosuje 2 zasady grupy po przypomnieniu indywidualnym z użyciem piktogramu — w 3 z 5 dni.",
        g2="Przestrzega wszystkich zasad kodeksu grupy po jednym przypomnieniu grupowym — w 3 z 5 dni.",
        g1="Przestrzega zasad samodzielnie i uwzględnia odmienne potrzeby kolegi w zabawie (np. potrzebę ciszy) — w 4 z 5 dni.",
        m="kodeks grupy · rejestr odstępstw"),
   dict(n=32, t="Stosuje zwroty grzecznościowe, przeprasza, przewiduje i nazywa konsekwencje swoich zachowań",
        icf="d710", pp="PP 1.5·2.4",
        g3="Użyje zwrotu „przepraszam” po modelowaniu dorosłego w sytuacji konfliktu — w 3 z 5 sytuacji.",
        g2="Przeprosi z własnej inicjatywy i nazwie, co zrobił niewłaściwie — w 3 z 5 sytuacji.",
        g1="Przewidzi konsekwencję swojego zachowania przed działaniem i zmieni je („jak to zrobię, to…”) — w 4 z 5 sytuacji.",
        m="karta sytuacji społecznych · zapis wypowiedzi"),
   dict(n=33, t="Pomaga innym w wykonaniu zadania, wspiera dzieci w pokonywaniu smutku i bezradności",
        icf="d710", pp="PP 1.10·1.11",
        g3="Poda koledze potrzebny materiał na prośbę nauczyciela — w 3 z 5 sytuacji.",
        g2="Zauważy trudność kolegi wskazaną przez dorosłego i zaproponuje jeden sposób pomocy — w 3 z 5 sytuacji.",
        g1="Samodzielnie zauważy, że kolega jest smutny lub nie radzi sobie, i udzieli adekwatnej pomocy — w 4 z 5 sytuacji.",
        m="obserwacja zachowań prospołecznych · rejestr"),
   dict(n=34, t="Buduje trwalsze przyjaźnie, wskazuje wypowiedzi i zachowania, które mogłyby kogoś skrzywdzić",
        icf="d750", pp="PP 1.8",
        g3="Wskaże na ilustracji zachowanie, które sprawia przykrość, po omówieniu przez nauczyciela — w 3 z 5 prób.",
        g2="Nazwie 3 zachowania krzywdzące i powie, co czuje osoba pokrzywdzona — w 3 z 5 rozmów.",
        g1="Utrzyma trwałą relację z wybranym kolegą przez miesiąc i zareaguje, gdy ktoś w grupie jest krzywdzony — w 4 z 5 obserwacji tygodniowych.",
        m="socjogram · karta sytuacji społecznych"),
  ]),

 dict(rom="VIII", icf="d8", name="Główne obszary życia (edukacja przedszkolna i zabawa)", pts=25,
  zasob="Gotowość do roli ucznia najlepiej ćwiczy się w prezentacji: dziecko z zasobem przedstawia grupie "
        "efekt pracy zespołu i odpowiada na pytania kolegów.",
  items=[
   dict(n=35, t="Wykazuje gotowość do roli ucznia: pracuje w zespole i prezentuje efekty wspólnych działań",
        icf="d815", pp="PP 1.2·DE-R.7",
        g3="Wykona przydzieloną część zadania zespołowego, siedząc przy wspólnym stole, przy wsparciu dorosłego — w 3 z 5 zadań.",
        g2="Wykona swoją część zadania i pokaże efekt grupie, mówiąc jedno zdanie — w 3 z 5 zadań.",
        g1="Uzgodni podział pracy w zespole, wykona swoją część i zaprezentuje wspólny efekt grupie — w 4 z 5 zadań.",
        m="karta pracy zespołowej · zapis prezentacji"),
   dict(n=36, t="Doprowadza aktywność edukacyjną do efektu i wyraża satysfakcję z wykonanego zadania",
        icf="d815", pp="PP 2.6·2.7",
        g3="Doprowadzi zadanie do końca przy 2 przypomnieniach dorosłego i pokaże efekt — w 3 z 5 zadań.",
        g2="Doprowadzi zadanie do końca bez przypomnień i oceni je na skali obrazkowej — w 3 z 5 zadań.",
        g1="Doprowadzi zadanie do końca, oceni efekt i powie, z czego jest zadowolony i co poprawi — w 4 z 5 zadań.",
        m="karta samooceny wytworu · teczka prac"),
   dict(n=37, t="Uczestniczy w grach z regułami, uczy się zasad współzawodnictwa",
        icf="d880", pp="PP 1.6·9.2",
        g3="Weźmie udział w grze z jedną regułą, przy nadzorze dorosłego pilnującego kolejności — w 3 z 5 gier.",
        g2="Zagra w grę z 2–3 regułami, czekając na swoją kolej przez całą rozgrywkę — w 3 z 5 gier.",
        g1="Zagra w grę zespołową z regułami, przypomni je innym i przyjmie wynik rywalizacji — w 4 z 5 gier.",
        m="gry planszowe i ruchowe · karta przestrzegania reguł"),
   dict(n=38, t="Rozpoznaje monety i banknoty, wyjaśnia do czego służą pieniądze, wykonuje proste obliczenia",
        icf="d860", pp="PP 4.15·1.14",
        g3="Rozpozna 2 monety spośród czterech po pokazie wzorca — w 3 z 5 prób.",
        g2="Rozpozna monety 1, 2 i 5 zł, wyjaśni, do czego służą pieniądze, i „zapłaci” w kąciku sklep — w 3 z 5 zabaw.",
        g1="Wykona zakup w kąciku sklep: policzy kwotę w zakresie 10 zł, zapłaci i sprawdzi resztę — w 4 z 5 zabaw.",
        m="kącik „sklep” · karta obliczeń"),
   dict(n=39, t="Podejmuje samodzielną aktywność poznawczą, korzysta z różnych źródeł informacji",
        icf="d815", pp="PP 2.1·3.4",
        g3="Wskaże, gdzie w sali szukać informacji na dany temat (album, plansza), po podpowiedzi dorosłego — w 3 z 5 prób.",
        g2="Wyszuka informację w albumie lub atlasie z pomocą nauczyciela i opowie, czego się dowiedział — w 3 z 5 prób.",
        g1="Sformułuje własne pytanie, wybierze źródło, znajdzie odpowiedź i przedstawi ją grupie — w 4 z 5 prób.",
        m="karta małego badacza · zapis pytań i źródeł"),
  ]),

 dict(rom="IX", icf="d9", name="Życie społeczne, lokalne i obywatelskie", pts=25,
  zasob="Wiedza o sobie i wspólnocie to naturalne pole ról reprezentacyjnych: powitanie gości, "
        "przedstawienie grupy, poprowadzenie fragmentu uroczystości przedszkolnej.",
  items=[
   dict(n=40, t="Odczuwa i wyjaśnia przynależność do rodziny, grupy przedszkolnej, społeczności lokalnej i narodowej",
        icf="d910", pp="PP 1.16",
        g3="Wskaże na zdjęciach członków swojej rodziny i znak swojej grupy, po pytaniu naprowadzającym — w 3 z 5 prób.",
        g2="Opowie, kto należy do jego rodziny i grupy, oraz poda nazwę miejscowości — w 3 z 5 rozmów.",
        g1="Wyjaśni, czym jest rodzina, grupa i ojczyzna, i poda po jednym przykładzie przynależności — w 4 z 5 rozmów.",
        m="rozmowa kierowana · karta wypowiedzi"),
   dict(n=41, t="Wymienia nazwę kraju i stolicy, rozpoznaje symbole narodowe, pielęgnuje tradycje",
        icf="d910", pp="PP 1.17·1.19",
        g3="Wskaże flagę Polski spośród trzech flag, po pokazie wzorca — w 3 z 5 prób.",
        g2="Poda nazwę kraju i stolicy oraz rozpozna godło i flagę — w 3 z 5 prób.",
        g1="Poda nazwę kraju i stolicy, rozpozna symbole narodowe i zachowa się właściwie podczas hymnu — w 4 z 5 sytuacji.",
        m="karta wiedzy o Polsce · obserwacja uroczystości"),
   dict(n=42, t="Udziela informacji o sobie: imię, nazwisko, adres zamieszkania — i wie, komu może ich udzielać",
        icf="d910", pp="PP 1.1",
        g3="Poda swoje imię i nazwisko na pytanie znanego dorosłego — w 4 z 5 prób.",
        g2="Poda imię, nazwisko i miejscowość zamieszkania oraz wskaże, kto jest osobą zaufaną — w 3 z 5 prób.",
        g1="Poda pełne dane adresowe wyłącznie osobie uprawnionej i wyjaśni, dlaczego nie podaje ich obcym — w 4 z 5 prób.",
        m="scenki bezpieczeństwa · karta danych"),
   dict(n=43, t="Korzysta z dóbr przyrody z poszanowaniem zasad: segreguje odpady, rozważnie korzysta z zasobów",
        icf="d920", pp="PP 5.11·5.12",
        g3="Wrzuci odpad do właściwego pojemnika po wskazaniu koloru przez dorosłego — w 3 z 5 prób.",
        g2="Posegreguje 5 odpadów do 3 pojemników samodzielnie — w 3 z 5 prób.",
        g1="Segreguje odpady, zakręca wodę i gasi światło z własnej inicjatywy oraz uzasadnia, po co to robimy — w 4 z 5 dni.",
        m="kącik ekologiczny · rejestr zachowań proekologicznych"),
   dict(n=44, t="Charakteryzuje pracę osób wykonujących różne zawody, przyjmuje role społeczne w zabawie",
        icf="d910", pp="PP 1.13·1.12",
        g3="Dopasuje 3 atrybuty do zawodów na obrazkach, po omówieniu przez nauczyciela — w 3 z 5 prób.",
        g2="Opowie, czym zajmuje się osoba w 3 wybranych zawodach, i odegra jedną z ról w zabawie — w 3 z 5 prób.",
        g1="Scharakteryzuje 5 zawodów, wskaże potrzebne w nich narzędzia i rozwinie zabawę w wybranej roli przez 15 minut — w 4 z 5 zabaw.",
        m="kącik zawodów · obserwacja zabawy tematycznej"),
  ]),
]
