# -*- coding: utf-8 -*-
"""Bank celów SMART — KPOF wersja A (3–4 lata). 42 twierdzenia, 9 obszarów ICF."""

WERSJA = dict(
    kod="A", etykieta="3–4 lata", zakres="42 twierdzenia · d1–d9",
    dziecko="wersja A · młodsza grupa przedszkolna",
    opis="Wiek adaptacji i naśladowania. Cele budujemy na rutynie dnia, modelowaniu dorosłego "
         "i krótkich, wielokrotnie powtarzanych próbach — nie na instrukcji słownej.",
)

AREAS = [
 dict(rom="I", icf="d1", name="Uczenie się i stosowanie wiedzy", pts=25,
  zasob="Dziecko z wynikiem 4–5 w tym obszarze prowadzi „kącik pokazów”: prezentuje młodszym sposób "
        "użycia nowej zabawki, co utrwala jego uwagę i buduje pozycję w grupie.",
  items=[
   dict(n=1, t="Przygląda się i przysłuchuje z zainteresowaniem temu, co pokazuje i mówi nauczyciel",
        icf="d110–d115", pp="PP 3.5",
        g3="Podczas 3-minutowego pokazu przy stoliku, siedząc obok nauczyciela i z dotykowym sygnałem przywołującym, skieruje wzrok na pokazywany przedmiot w 3 z 5 prób.",
        g2="Podczas zajęcia w małej grupie (do 4 dzieci) utrzyma uwagę wzrokową na pokazie przez 3 minuty po jednym przypomnieniu słownym — w 3 z 5 zajęć.",
        g1="Podczas zajęcia z całą grupą samodzielnie skupi wzrok i słuch na pokazie nauczyciela przez 5 minut i wskaże pokazywany przedmiot — w 4 z 5 zajęć.",
        m="arkusz próbek uwagi · 5 prób w tygodniu"),
   dict(n=2, t="Naśladuje proste czynności, ruchy i gesty dorosłego lub dzieci",
        icf="d130", pp="PP 9.1",
        g3="W zabawie „rób to, co ja” z fizycznym podprowadzeniem ręki odtworzy 1 ruch dużej motoryki (klaśnięcie, tupnięcie) w 3 z 5 prób.",
        g2="Po pokazie nauczyciela odtworzy sekwencję 2 ruchów bez podprowadzania fizycznego, wyłącznie po wzorze wzrokowym — w 3 z 5 prób.",
        g1="Samodzielnie odtworzy sekwencję 3 ruchów pokazanych przez nauczyciela lub rówieśnika i włączy ją do zabawy naśladowczej — w 4 z 5 prób.",
        m="karta obserwacji zabawy ruchowej · 2 razy w tygodniu"),
   dict(n=3, t="Skupia uwagę na zabawie lub prostym zadaniu przez kilka minut",
        icf="d160", pp="PP 2.6",
        g3="Przy stoliku z ograniczoną liczbą bodźców (1 zabawka, parawan) pozostanie przy zadaniu 2 minuty z towarzyszeniem dorosłego — w 3 z 5 dni.",
        g2="Pozostanie przy wybranym przez siebie zadaniu 4 minuty, korzystając z klepsydry jako sygnału końca — w 3 z 5 dni.",
        g1="Samodzielnie doprowadzi 6-minutową zabawę tematyczną do umówionego końca, nie zmieniając aktywności — w 4 z 5 dni.",
        m="pomiar czasu (klepsydra/stoper) · zapis dzienny"),
   dict(n=4, t="Dopasowuje i sortuje przedmioty według jednej cechy (kolor, wielkość)",
        icf="d137", pp="PP 4.4",
        g3="Z dwóch przedmiotów kontrastowych (duży–mały) wskaże ten wskazany przez nauczyciela, po pokazie wzorca, w 3 z 5 prób.",
        g2="Posegreguje 6 przedmiotów na 2 pojemniki według koloru po jednorazowym pokazie wzorca — w 3 z 5 prób.",
        g1="Samodzielnie posegreguje 10 przedmiotów według jednej wybranej przez siebie cechy i nazwie kryterium („bo są czerwone”) — w 4 z 5 prób.",
        m="zadanie sortowania · zestaw 10 elementów"),
   dict(n=5, t="Podejmuje próby rozwiązania prostego problemu w zabawie (np. sięga po narzędzie, prosi o pomoc)",
        icf="d175", pp="PP 4.2",
        g3="W sytuacji zablokowanej zabawy (zamknięte pudełko) zasygnalizuje trudność gestem lub podaniem przedmiotu dorosłemu, po modelowaniu, w 3 z 5 prób.",
        g2="W sytuacji trudności podejmie samodzielnie 1 próbę rozwiązania (obróci, pociągnie), zanim poprosi o pomoc — w 3 z 5 prób.",
        g1="Samodzielnie wypróbuje co najmniej 2 sposoby rozwiązania problemu w zabawie i dopiero potem poprosi o pomoc słowami — w 4 z 5 prób.",
        m="próby zaaranżowane · 5 sytuacji w tygodniu"),
  ]),

 dict(rom="II", icf="d2", name="Ogólne zadania i wymagania", pts=25,
  zasob="Dziecko sprawne w tym obszarze zostaje „strażnikiem rytmu dnia”: pokazuje kolejny obrazek "
        "z planu dnia całej grupie — utrwala własną samoregulację i wspiera dzieci z Poziomu II i III.",
  items=[
   dict(n=6, t="Podejmuje proste zadanie lub zabawę zaproponowaną przez dorosłego",
        icf="d210", pp="PP 1.2",
        g3="Po propozycji przedstawionej obrazkiem i przy wspólnym rozpoczęciu przez dorosłego przystąpi do zadania w ciągu 1 minuty — w 3 z 5 propozycji.",
        g2="Po propozycji słownej z pokazem materiału przystąpi do zadania bez wspólnego rozpoczynania — w 3 z 5 propozycji.",
        g1="Samodzielnie przystąpi do zadania zaproponowanego słownie całej grupie, w ciągu 1 minuty od polecenia — w 4 z 5 propozycji.",
        m="lista kontrolna propozycji · zapis dzienny"),
   dict(n=7, t="Kończy krótką, rozpoczętą czynność przy wsparciu dorosłego",
        icf="d210", pp="PP 2.6",
        g3="Dokończy 2-elementowe zadanie (włożyć, zamknąć) prowadzony krok po kroku podpowiedzią fizyczną — w 3 z 5 prób.",
        g2="Dokończy 3-elementowe zadanie korzystając z planu obrazkowego i jednego przypomnienia słownego — w 3 z 5 prób.",
        g1="Samodzielnie dokończy rozpoczęte zadanie i odłoży materiały na miejsce, bez przypomnień — w 4 z 5 prób.",
        m="plan obrazkowy z odhaczaniem kroków"),
   dict(n=8, t="Odnajduje się w rytmie dnia przedszkolnego (posiłek, zabawa, odpoczynek)",
        icf="d230", pp="PP WSR·Zad.2",
        g3="Po sygnale dźwiękowym i pokazaniu obrazka przejdzie do kolejnej aktywności prowadzony za rękę, bez protestu trwającego dłużej niż 1 minutę — w 3 z 5 przejść.",
        g2="Po sygnale dźwiękowym i uprzedzeniu „za chwilę kończymy” przejdzie do kolejnej aktywności samodzielnie — w 3 z 5 przejść.",
        g1="Samodzielnie odczyta plan dnia i przejdzie do kolejnej aktywności po sygnale, bez uprzedzania indywidualnego — w 4 z 5 przejść.",
        m="rejestr przejść między aktywnościami · 5 dziennie"),
   dict(n=9, t="Akceptuje proste zasady obowiązujące w zabawie i w sali",
        icf="d230", pp="PP 1.6",
        g3="Zastosuje 1 zasadę sali (chodzimy w sali) po pokazaniu piktogramu i przypomnieniu indywidualnym — w 3 z 5 sytuacji.",
        g2="Zastosuje 3 zasady grupy po jednym przypomnieniu grupowym, bez interwencji indywidualnej — w 3 z 5 dni.",
        g1="Samodzielnie przestrzega zasad sali i przypomina o nich innym dzieciom w formie akceptowalnej — w 4 z 5 dni.",
        m="tablica zasad · dzienny zapis odstępstw"),
   dict(n=10, t="Uspokaja się po trudnej emocjonalnie sytuacji przy pomocy dorosłego",
        icf="d240", pp="PP 2.11",
        g3="Przyjmie wsparcie dorosłego (bliskość, przedmiot kojący) i wyciszy się w ciągu 5 minut od zdarzenia — w 3 z 5 sytuacji.",
        g2="Po zaproponowaniu przez dorosłego skorzysta z kącika wyciszenia i wróci do grupy w ciągu 3 minut — w 3 z 5 sytuacji.",
        g1="Samodzielnie wybierze jedną ze znanych strategii wyciszania (oddech, kącik, ulubiona książka) i wróci do zabawy w ciągu 3 minut — w 4 z 5 sytuacji.",
        m="karta zdarzeń trudnych ABC · czas powrotu"),
  ]),

 dict(rom="III", icf="d3", name="Porozumiewanie się", pts=25,
  zasob="Mocna komunikacja to naturalne stanowisko „tłumacza grupy”: dziecko powtarza polecenie "
        "koledze, który go nie usłyszał — i samo utrwala rozumienie instrukcji.",
  items=[
   dict(n=11, t="Rozumie i wykonuje proste polecenia kierowane do niego indywidualnie",
        icf="d310", pp="PP 3.5",
        g3="Wykona 1-elementowe polecenie („daj kubek”) poparte gestem wskazującym i pokazem — w 3 z 5 poleceń.",
        g2="Wykona 2-elementowe polecenie poparte gestem („weź kubek i postaw na stole”) — w 3 z 5 poleceń.",
        g1="Wykona 2-elementowe polecenie podane wyłącznie słownie, bez gestu i powtórzenia — w 4 z 5 poleceń.",
        m="próby zaaranżowane w rutynie · 5 poleceń dziennie"),
   dict(n=12, t="Komunikuje swoje potrzeby słowem, gestem lub innym czytelnym sygnałem (w razie potrzeby AAC)",
        icf="d330·d335", pp="PP 2.10·3.2",
        g3="Zasygnalizuje potrzebę picia i toalety wskazaniem symbolu AAC z tablicy 4-polowej po podaniu tablicy przez dorosłego — w 3 z 5 sytuacji.",
        g2="Samodzielnie sięgnie po tablicę AAC lub użyje słowa-klucza, aby zgłosić 4 podstawowe potrzeby — w 3 z 5 sytuacji.",
        g1="Zgłosi swoją potrzebę pełnym komunikatem („chcę pić”) skierowanym do konkretnej osoby, także w hałasie sali — w 4 z 5 sytuacji.",
        m="rejestr komunikatów funkcjonalnych · zapis dzienny"),
   dict(n=13, t="Buduje proste zdania zrozumiałe dla najbliższego otoczenia",
        icf="d330", pp="PP 3.2",
        g3="W odpowiedzi na pytanie o obrazek użyje wyrazu-etykiety lub zestawienia 2 wyrazów po modelowaniu przez dorosłego — w 3 z 5 prób.",
        g2="Zbuduje zdanie 3-wyrazowe (podmiot–orzeczenie–dopełnienie) opisujące obrazek, po pytaniu naprowadzającym — w 3 z 5 prób.",
        g1="Samodzielnie zbuduje zdanie proste zrozumiałe dla osoby spoza grupy, opisując zdarzenie z sali — w 4 z 5 prób.",
        m="próbka mowy · nagranie 5-minutowe raz w tygodniu"),
   dict(n=14, t="Odpowiada na proste pytania: kto? co? gdzie?",
        icf="d350", pp="PP 3.1",
        g3="Odpowie na pytanie „co to?” wskazaniem obrazka spośród dwóch — w 3 z 5 pytań.",
        g2="Odpowie słownie na pytania „kto?” i „co?” dotyczące ilustracji lub sytuacji w sali — w 3 z 5 pytań.",
        g1="Odpowie słownie na pytania „kto? co? gdzie?” dotyczące zdarzenia sprzed kilku godzin — w 4 z 5 pytań.",
        m="karta pytań diagnostycznych · 5 pytań w serii"),
   dict(n=15, t="Rozumie komunikaty pozawerbalne: mimikę, gesty, ton głosu",
        icf="d315", pp="PP 3.5",
        g3="Zareaguje zatrzymaniem na gest „stop” i wyraz twarzy nauczyciela, po jednorazowym powtórzeniu gestu — w 3 z 5 sytuacji.",
        g2="Wskaże na obrazkach twarz wesołą i smutną oraz dopasuje ją do sytuacji z sali — w 3 z 5 prób.",
        g1="Odczyta z mimiki i tonu głosu dorosłego, że zabawa się kończy lub że coś jest niebezpieczne, i dostosuje zachowanie — w 4 z 5 sytuacji.",
        m="próby sytuacyjne · obserwacja uczestnicząca"),
  ]),

 dict(rom="IV", icf="d4", name="Poruszanie się", pts=25,
  zasob="Sprawność ruchowa jest najlepszą dźwignią dla obszarów II, III i VII: dziecko prowadzi "
        "rozgrzewkę dla grupy, ćwicząc przy okazji czekanie na kolej i komunikat kierowany do wielu osób.",
  items=[
   dict(n=16, t="Chodzi i biega pewnie, omija i pokonuje przeszkody",
        icf="d450–d455", pp="PP 9.1·9.4",
        g3="Przejdzie tor z 3 przeszkodami, trzymając dorosłego za rękę, bez upadku — w 3 z 5 prób.",
        g2="Przebiegnie tor z 3 przeszkodami samodzielnie, zwalniając przed przeszkodą — w 3 z 5 prób.",
        g1="Przebiegnie tor z 5 przeszkodami w tempie zabawy, omijając dzieci biegnące z naprzeciwka — w 4 z 5 prób.",
        m="tor przeszkód · pomiar prób i upadków"),
   dict(n=17, t="Wchodzi i schodzi po schodach",
        icf="d455", pp="PP 9.4",
        g3="Wejdzie i zejdzie po 5 stopniach krokiem dostawnym, trzymając poręcz i rękę dorosłego — w 3 z 5 przejść.",
        g2="Wejdzie po schodach krokiem naprzemiennym trzymając poręcz, zejdzie krokiem dostawnym — w 3 z 5 przejść.",
        g1="Pokona całą kondygnację krokiem naprzemiennym w górę i w dół, bez trzymania poręczy, niosąc lekki przedmiot — w 4 z 5 przejść.",
        m="obserwacja w rutynie wyjścia na plac zabaw"),
   dict(n=18, t="Rzuca piłkę i podejmuje próby jej łapania",
        icf="d445", pp="PP 9.4·9.5",
        g3="Poda piłkę oburącz dorosłemu z odległości 1 metra po pokazie — w 3 z 5 prób.",
        g2="Rzuci piłkę oburącz do celu z odległości 2 metrów i podejmie próbę złapania toczonej piłki — w 3 z 5 prób.",
        g1="Rzuci i złapie piłkę oburącz w parze z rówieśnikiem, utrzymując wymianę przez 4 podania — w 4 z 5 prób.",
        m="zabawa w parach · liczba udanych wymian"),
   dict(n=19, t="Buduje wieżę z klocków, nawleka duże elementy, dopasowuje kształty",
        icf="d440", pp="PP 9.5·6.3",
        g3="Ułoży wieżę z 3 dużych klocków, gdy dorosły podaje kolejny klocek do ręki — w 3 z 5 prób.",
        g2="Ułoży wieżę z 6 klocków i nawlecze 4 duże koraliki na sztywną żyłkę samodzielnie — w 3 z 5 prób.",
        g1="Ułoży budowlę według prostego wzoru obrazkowego i nawlecze 8 elementów w zadanej kolejności kolorów — w 4 z 5 prób.",
        m="wytwór dziecka · zdjęcie do teczki obserwacji"),
   dict(n=20, t="Uczestniczy w zabawach ruchowych, rytmicznych i naśladowczych",
        icf="d455", pp="PP 9.1·8.4",
        g3="Pozostanie w kole podczas 2-minutowej zabawy rytmicznej, trzymając za rękę dorosłego — w 3 z 5 zabaw.",
        g2="Wykona ruchy zabawy rytmicznej z naśladowania przez całą zwrotkę, pozostając w kole — w 3 z 5 zabaw.",
        g1="Samodzielnie odtworzy układ ruchowy do znanej piosenki i zaproponuje własny ruch dla grupy — w 4 z 5 zabaw.",
        m="obserwacja zajęć rytmicznych · 2 razy w tygodniu"),
  ]),

 dict(rom="V", icf="d5", name="Dbanie o siebie", pts=25,
  zasob="Samodzielność w samoobsłudze uwalnia czas nauczyciela i daje dziecku rolę „pomocnika "
        "szatni” — modeluje kolejność ubierania dla dzieci z Poziomu II i III.",
  items=[
   dict(n=21, t="Zgłasza potrzeby fizjologiczne, korzysta z toalety z niewielką pomocą",
        icf="d530", pp="PP 9.7",
        g3="Skorzysta z toalety w stałych, zaplanowanych porach (co 2 godziny) prowadzony przez dorosłego, bez protestu — w 4 z 5 dni.",
        g2="Zgłosi potrzebę gestem lub słowem i skorzysta z toalety z pomocą przy ubraniu — w 3 z 5 sytuacji.",
        g1="Samodzielnie zgłosi potrzebę, skorzysta z toalety, ubierze się i umyje ręce, wymagając jedynie nadzoru — w 4 z 5 sytuacji.",
        m="karta samoobsługi · zapis dzienny"),
   dict(n=22, t="Myje ręce z przypomnieniem dorosłego",
        icf="d510", pp="PP 9.7",
        g3="Wykona mycie rąk prowadzony ręką dorosłego przez wszystkie 4 kroki instrukcji obrazkowej — w 4 z 5 prób.",
        g2="Wykona 4 kroki mycia rąk korzystając z instrukcji obrazkowej przy umywalce i jednego przypomnienia — w 3 z 5 prób.",
        g1="Samodzielnie umyje i wytrze ręce przed posiłkiem i po toalecie bez przypomnienia dorosłego — w 4 z 5 sytuacji.",
        m="instrukcja obrazkowa 4 kroki · obserwacja"),
   dict(n=23, t="Je samodzielnie łyżką i widelcem, pije z kubka",
        icf="d550·d560", pp="PP 9.7·WSR",
        g3="Zje 5 łyżek posiłku, gdy dorosły nakłada i podaje sztuciec do ręki — w 4 z 5 posiłków.",
        g2="Zje samodzielnie cały posiłek łyżką i napije się z otwartego kubka, z pomocą przy nabieraniu — w 3 z 5 posiłków.",
        g1="Zje posiłek widelcem i łyżką, naleje sobie wodę z małego dzbanka i posprząta miejsce — w 4 z 5 posiłków.",
        m="obserwacja posiłku · 5 posiłków w tygodniu"),
   dict(n=24, t="Podejmuje próby samodzielnego ubierania się i rozbierania",
        icf="d540", pp="PP 9.7",
        g3="Zdejmie 1 część garderoby (czapka, kapcie) po rozpoczęciu ruchu przez dorosłego — w 3 z 5 prób.",
        g2="Ubierze i zdejmie 3 części garderoby korzystając z planu obrazkowego kolejności ubierania — w 3 z 5 prób.",
        g1="Ubierze się samodzielnie do wyjścia na plac zabaw w czasie przewidzianym dla grupy, prosząc o pomoc tylko przy zamku — w 4 z 5 wyjść.",
        m="pomiar czasu ubierania · plan obrazkowy"),
   dict(n=25, t="Komunikuje zmęczenie, głód, złe samopoczucie, potrzebę ruchu lub odpoczynku",
        icf="d571", pp="PP 9.10",
        g3="Wskaże symbol „odpoczynek” lub „boli” na tablicy podanej przez dorosłego w sytuacji dyskomfortu — w 3 z 5 sytuacji.",
        g2="Samodzielnie sięgnie po symbol lub użyje słowa, by zgłosić zmęczenie albo głód — w 3 z 5 sytuacji.",
        g1="Powie dorosłemu, co czuje i czego potrzebuje („jestem zmęczony, chcę usiąść”), zanim pojawi się reakcja emocjonalna — w 4 z 5 sytuacji.",
        m="karta sygnałów dziecka · zapis zdarzeń"),
  ]),

 dict(rom="VI", icf="d6", name="Życie domowe (czynności użyteczne)", pts=15, opis_flag=True,
  zasob="Obszar opisowy — nie wchodzi do wyniku ogólnego, ale bywa najszybszą drogą do poczucia "
        "sprawczości: dziecko z zasobem zostaje dyżurnym i przekazuje rolę kolejnym dzieciom.",
  items=[
   dict(n=26, t="Sprząta zabawki po skończonej zabawie przy wsparciu dorosłego",
        icf="d650", pp="PP 2.5·WSR",
        g3="Odłoży 3 zabawki do pojemnika podawane kolejno przez dorosłego, po sygnale sprzątania — w 3 z 5 dni.",
        g2="Posprząta swój obszar zabawy po sygnale i pokazaniu zdjęcia „jak ma wyglądać kącik” — w 3 z 5 dni.",
        g1="Po sygnale samodzielnie posprząta kącik, w którym się bawił, i sprawdzi efekt według zdjęcia wzorcowego — w 4 z 5 dni.",
        m="zdjęcie wzorcowe kącika · zapis dzienny"),
   dict(n=27, t="Odkłada swoje rzeczy na wyznaczone miejsce (kapcie, kubek, worek)",
        icf="d650", pp="PP 2.5",
        g3="Odłoży kapcie do swojej półki oznaczonej zdjęciem, prowadzony przez dorosłego — w 4 z 5 dni.",
        g2="Odłoży 2 swoje rzeczy na miejsca oznaczone znakiem rozpoznawczym po przypomnieniu grupowym — w 3 z 5 dni.",
        g1="Samodzielnie odkłada wszystkie swoje rzeczy na wyznaczone miejsca po przyjściu i przed wyjściem — w 4 z 5 dni.",
        m="lista kontrolna szatni · zapis dzienny"),
   dict(n=28, t="Pomaga w prostych czynnościach porządkowych w sali",
        icf="d640", pp="PP WSR·Zad.7",
        g3="Wykona 1 czynność porządkową (przyniesie ściereczkę) na prośbę skierowaną indywidualnie i poparta gestem — w 3 z 5 próśb.",
        g2="Wykona 2-etapową czynność dyżurnego (rozdanie serwetek, zebranie kubków) z dorosłym obok — w 3 z 5 dyżurów.",
        g1="Samodzielnie pełni dyżur według planu obrazkowego i zgłasza jego zakończenie nauczycielowi — w 4 z 5 dyżurów.",
        m="grafik dyżurów · potwierdzenie wykonania"),
  ]),

 dict(rom="VII", icf="d7", name="Wzajemne kontakty i związki międzyludzkie", pts=25,
  zasob="Dziecko o wysokiej kompetencji społecznej pełni funkcję „kolegi powitalnego” dla dziecka "
        "nowego lub wracającego po chorobie — to najskuteczniejszy sposób pracy nad obszarem VII u innych.",
  items=[
   dict(n=29, t="Obdarza uwagą inne dzieci i osoby dorosłe",
        icf="d710", pp="PP 3.5",
        g3="Skieruje spojrzenie na dziecko, które wypowiada jego imię, po dodatkowym sygnale dotykowym — w 3 z 5 prób.",
        g2="Zwróci się twarzą do mówiącego rówieśnika i wytrzyma kontakt przez całą krótką wypowiedź — w 3 z 5 sytuacji.",
        g1="Wysłucha wypowiedzi rówieśnika w kręgu i odniesie się do niej gestem lub słowem — w 4 z 5 spotkań w kręgu.",
        m="obserwacja kręgu porannego · 5 spotkań"),
   dict(n=30, t="Podejmuje krótkie interakcje z rówieśnikami (podanie zabawki, wspólny śmiech)",
        icf="d710", pp="PP 1.2",
        g3="Poda zabawkę wskazanemu dziecku w zabawie zaaranżowanej przez dorosłego, przy jego obecności — w 3 z 5 prób.",
        g2="Podejmie wymianę zabawki z rówieśnikiem w zabawie równoległej, po jednorazowej podpowiedzi — w 3 z 5 sytuacji.",
        g1="Samodzielnie zainicjuje krótką zabawę z wybranym kolegą i utrzyma ją przez 5 minut — w 4 z 5 dni.",
        m="socjogram zabawy · obserwacja 15-minutowa"),
   dict(n=31, t="Rozstaje się z rodzicami bez nasilonego lęku, czuje się w grupie bezpiecznie",
        icf="d760", pp="PP Zad.2",
        g3="Przejdzie z rodzica do nauczyciela z przedmiotem przejściowym z domu i wyciszy się w ciągu 10 minut — w 3 z 5 poranków.",
        g2="Rozstanie się z rodzicem po ustalonym rytuale pożegnania i włączy się w aktywność w ciągu 5 minut — w 3 z 5 poranków.",
        g1="Samodzielnie wejdzie do sali, pożegna rodzica i podejmie zabawę w ciągu 2 minut — w 4 z 5 poranków.",
        m="karta adaptacji · czas wyciszenia po rozstaniu"),
   dict(n=32, t="Okazuje podstawowe emocje w sposób czytelny i adekwatny do sytuacji",
        icf="d710", pp="PP 2.9",
        g3="Wskaże symbol emocji (radość, złość) opisujący jego stan, gdy dorosły poda tablicę i nazwie obie możliwości — w 3 z 5 sytuacji.",
        g2="Nazwie swoją emocję jednym słowem po pytaniu dorosłego „co czujesz?” — w 3 z 5 sytuacji.",
        g1="Samodzielnie nazwie emocję swoją i kolegi w sytuacji zabawy oraz poda jej przyczynę — w 4 z 5 sytuacji.",
        m="koło emocji · rejestr nazwań"),
   dict(n=33, t="Zwraca się o pomoc do znanego dorosłego",
        icf="d710", pp="PP 2.11",
        g3="Podejdzie do nauczyciela i pociągnie za rękę lub poda przedmiot w sytuacji trudności, po przypomnieniu zasady — w 3 z 5 sytuacji.",
        g2="Poprosi o pomoc słowem lub symbolem, kierując komunikat do konkretnej osoby dorosłej — w 3 z 5 sytuacji.",
        g1="Poprosi o pomoc, nazywając problem („nie mogę otworzyć”), także w sytuacji poza salą — w 4 z 5 sytuacji.",
        m="próby zaaranżowane · rejestr próśb o pomoc"),
  ]),

 dict(rom="VIII", icf="d8", name="Główne obszary życia (edukacja przedszkolna i zabawa)", pts=25,
  zasob="Dziecko z bogatą zabawą tematyczną jest naturalnym „reżyserem kącika” — wprowadza w rolę "
        "dzieci, które w zabawie funkcjonują jeszcze na poziomie manipulacji.",
  items=[
   dict(n=34, t="Adaptuje się do grupy przedszkolnej i nowego otoczenia",
        icf="d815", pp="PP Zad.2·1.16",
        g3="Pozostanie w sali przez 3 godziny bez nasilonej reakcji lękowej, korzystając ze stałego miejsca-bazy — w 3 z 5 dni.",
        g2="Weźmie udział w 3 kolejnych elementach rytmu dnia bez wycofania, korzystając z planu obrazkowego — w 3 z 5 dni.",
        g1="Uczestniczy w pełnym dniu przedszkolnym, w tym w sytuacjach zmienionych (zastępstwo, inna sala) — w 4 z 5 dni.",
        m="karta adaptacji · obserwacja całodzienna"),
   dict(n=35, t="Podejmuje zabawę swobodną i pierwsze zabawy tematyczne (przyjmuje proste role)",
        icf="d880", pp="PP WSR·1.12",
        g3="Wykona 2 czynności na przedmiotach zgodnie z ich przeznaczeniem (karmi misia łyżką) po pokazie dorosłego — w 3 z 5 prób.",
        g2="Podejmie prostą rolę w zabawie („jestem mamą”) zaproponowaną przez dorosłego i utrzyma ją 5 minut — w 3 z 5 zabaw.",
        g1="Samodzielnie wybierze rolę, nazwie ją i odegra scenkę z rówieśnikiem przez 10 minut — w 4 z 5 zabaw.",
        m="obserwacja zabawy swobodnej · 15 minut"),
   dict(n=36, t="Uczestniczy w krótkich zajęciach zorganizowanych dla grupy",
        icf="d815", pp="PP 1.2",
        g3="Pozostanie na dywanie przez 5 minut zajęcia, siedząc na wyznaczonej poduszce obok nauczyciela — w 3 z 5 zajęć.",
        g2="Weźmie udział w całym 10-minutowym zajęciu, wykonując 2 zadania kierowane — w 3 z 5 zajęć.",
        g1="Uczestniczy aktywnie w 15-minutowym zajęciu, zgłasza się do odpowiedzi i czeka na swoją kolej — w 4 z 5 zajęć.",
        m="obserwacja zajęć kierowanych · zapis dzienny"),
   dict(n=37, t="Inicjuje zabawy konstrukcyjne, buduje z klocków i różnych materiałów",
        icf="d880", pp="PP 6.3",
        g3="Połączy 3 elementy konstrukcyjne po pokazie i podaniu materiału przez dorosłego — w 3 z 5 prób.",
        g2="Zbuduje prostą konstrukcję (dom, garaż) i nazwie ją, korzystając z materiału wybranego samodzielnie — w 3 z 5 prób.",
        g1="Zaplanuje budowlę słowem („zrobię most”), zbuduje ją i wykorzysta w zabawie tematycznej — w 4 z 5 prób.",
        m="zdjęcie wytworu · teczka obserwacji"),
   dict(n=38, t="Włącza się w zabawy grupowe prowadzone przez nauczyciela",
        icf="d880", pp="PP 1.2·9.1",
        g3="Dołączy do koła i pozostanie w nim przez 2 minuty, trzymając za ręce dwie znane osoby — w 3 z 5 zabaw.",
        g2="Wykona swoją część zabawy grupowej z jednym przypomnieniem zasad — w 3 z 5 zabaw.",
        g1="Uczestniczy w zabawie z prostą regułą, czeka na swoją kolej i akceptuje wynik — w 4 z 5 zabaw.",
        m="obserwacja zabaw grupowych · 2 razy w tygodniu"),
  ]),

 dict(rom="IX", icf="d9", name="Życie społeczne, lokalne i obywatelskie", pts=20,
  zasob="W tym obszarze zasób dziecka najlepiej wykorzystać w rolach reprezentacyjnych: powitanie "
        "gościa, wręczenie kwiatka, poprowadzenie grupy w parze podczas spaceru.",
  items=[
   dict(n=39, t="Uczestniczy w uroczystościach grupowych (urodziny, święta grupy)",
        icf="d910", pp="PP DE-R.5·1.16",
        g3="Pozostanie w sali podczas 10-minutowej uroczystości, siedząc obok znanego dorosłego, z możliwością zasłonięcia uszu — w 3 z 4 uroczystości.",
        g2="Weźmie udział w jednym elemencie uroczystości (wręczy laurkę, zaśpiewa refren) po przygotowaniu wizualnym — w 3 z 4 uroczystości.",
        g1="Uczestniczy w całej uroczystości grupowej, zna jej przebieg i wykonuje ustaloną rolę — w 4 z 4 uroczystości.",
        m="karta wydarzeń grupowych · zapis po każdej uroczystości"),
   dict(n=40, t="Uczestniczy w spacerach i wyjściach poza salę przedszkolną",
        icf="d910", pp="PP DE-R.4·WSR",
        g3="Przejdzie trasę 100 metrów trzymając za rękę dorosłego, zatrzymując się na sygnał — w 3 z 5 wyjść.",
        g2="Przejdzie całą trasę spaceru w parze z rówieśnikiem, reagując na sygnał zatrzymania — w 3 z 5 wyjść.",
        g1="Idzie w parze przez cały spacer, przestrzega zasad przechodzenia przez jezdnię i opowiada o tym, co zobaczył — w 4 z 5 wyjść.",
        m="karta wyjść · obserwacja podczas spaceru"),
   dict(n=41, t="Podejmuje zabawy na świeżym powietrzu z zachowaniem prostych zasad",
        icf="d920", pp="PP 9.11·1.6",
        g3="Pozostanie w wyznaczonej, oznaczonej strefie placu zabaw przy stałym towarzyszeniu dorosłego — w 3 z 5 wyjść.",
        g2="Korzysta z 2 urządzeń placu zabaw zgodnie z zasadą kolejki, po jednym przypomnieniu — w 3 z 5 wyjść.",
        g1="Samodzielnie bawi się na placu, przestrzega zasad bezpieczeństwa i wraca do grupy na sygnał — w 4 z 5 wyjść.",
        m="obserwacja pobytu na placu · zapis dzienny"),
   dict(n=42, t="Z zainteresowaniem odbiera muzykę, teatrzyk, książkę czytaną przez dorosłego",
        icf="d9202", pp="PP DE-R.1·3.3",
        g3="Wysłucha 3-minutowego fragmentu opowiadania, siedząc na wyznaczonym miejscu z przedmiotem do trzymania w rękach — w 3 z 5 czytań.",
        g2="Wysłucha całego krótkiego opowiadania i wskaże obrazek pasujący do treści — w 3 z 5 czytań.",
        g1="Wysłucha teatrzyku lub opowiadania i opowie o nim jednym zdaniem oraz powie, co mu się podobało — w 4 z 5 sytuacji.",
        m="karta odbioru sztuki · zapis wypowiedzi dziecka"),
  ]),
]
