# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VII (wzajemne kontakty i związki), wersja B (5 lat)."""

KONSPEKTY_5_D7 = {
 ("B", 30): dict(
  nr="B7-30", tytul="Zaproszenie do zabawy",
  podtytul="Nawiązywanie relacji rówieśniczych i szanowanie upodobań innych",
  sfera="VII WZAJEMNE KONTAKTY · Relacje rówieśnicze (ICF d750 · PP 1.2·1.8)",
  czas="20 min", forma="mała grupa (4–6 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko podejmie wspólną zabawę z jednym stałym partnerem i utrzyma ją przez 10 minut, w 3 z 5 dni, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Zaprasza kolegę i bawi się z nim we wspólną zabawę."),
    ("M","10 minut wspólnej zabawy; 3 z 5 dni."),
    ("A","Karty zaproszeń i kącik dwuosobowy ułatwiają start."),
    ("R","Relacje rówieśnicze są głównym źródłem uczenia się społecznego."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Socjogram grupy · obserwacja zabawy swobodnej.",
  pomoce=["karty zaproszeń z rysunkami zabaw","kącik dwuosobowy z jednym zestawem zabawek","tablica „z kim się dziś bawiłem”","zdjęcia dzieci na magnesach","gry wymagające dwóch osób"],
  metody=["zaproszenie jako narzędzie startu","zabawy wymagające pary","tablica relacji jako informacja zwrotna","docenianie zapraszania, nie tylko zabawy"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — pokazuje karty zaproszeń: „wybierz zabawę i kolegę”.","D — wybiera kartę i decyduje, kogo zaprosi."),
    ("N — modeluje zaproszenie: „chcesz się pobawić w…?”.","D — zaprasza kolegę własnymi słowami."),
    ("N — wskazuje kącik dwuosobowy z jednym zestawem.","D — bawi się z partnerem, dzieląc materiał."),
    ("N — obserwuje i wspiera przy sporze, nie rozstrzyga.","D — uzgadnia z kolegą sposób zabawy."),
    ("N — zaprasza do tablicy relacji.","D — przypina magnes z kolegą, z którym się bawiło.")],
  mod2=["partner wskazany przez nauczyciela","zabawa 5-minutowa","zaproszenie z pomocą karty i wzoru zdania"],
  mod3=["zabawa obok kolegi z identycznymi zabawkami","dorosły jako trzeci uczestnik","krótka, ustrukturyzowana zabawa","praca nad wspólnym polem uwagi"],
  mod1=["zaproszenie dziecka spoza stałej pary","uwzględnienie pomysłu kolegi w zabawie","zaproszenie dziecka, które zostało samo","zabawa w trójce z podziałem ról"],
  wskazowka="Jeden zestaw zabawek na dwoje dzieci tworzy naturalną potrzebę współpracy — dwa komplety dają zabawę równoległą, którą łatwo pomylić ze wspólną."),

 ("B", 31): dict(
  nr="B7-31", tytul="Zespół z pomysłem",
  podtytul="Współdziałanie z dziećmi, zgłaszanie pomysłów, uzgadnianie zasad",
  sfera="VII WZAJEMNE KONTAKTY · Współdziałanie (ICF d720 · PP 1.2·1.3)",
  czas="25 min", forma="zespoły 3-osobowe", cykl="2× w tygodniu",
  ter="Dziecko zgłosi jeden własny pomysł w pracy w parze i uzgodni podział materiału z partnerem, w 3 z 5 zadań, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Proponuje pomysł i ustala z partnerem, kto co robi."),
    ("M","1 pomysł · podział materiału; 3 z 5 zadań."),
    ("A","Celowy niedobór materiału wymusza uzgodnienie."),
    ("R","Współdziałanie to kluczowa kompetencja pracy zespołowej."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta pracy zespołowej · obserwacja podziału zadań.",
  pomoce=["zadania zespołowe: makieta, plakat, budowla","materiał w jednym komplecie na zespół","karta podziału ról (kto co robi)","tablica pomysłów","dzwonek narady zespołu"],
  metody=["celowy niedobór materiału","narada zespołu przed pracą","karta ról jako zapis ustaleń","prezentacja efektu przez cały zespół"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — ogłasza zadanie i podaje jeden komplet materiału.","D — zauważa, że materiał trzeba dzielić."),
    ("N — dzwoni na naradę: „ustalcie, kto co robi”.","D — zgłasza swój pomysł zespołowi."),
    ("N — pomaga zapisać ustalenia na karcie ról.","D — uzgadnia podział i przyjmuje swoją część."),
    ("N — obserwuje pracę, wspiera przy nieporozumieniu.","D — wykonuje swoją część, korzystając ze wspólnego materiału."),
    ("N — zaprasza zespół do prezentacji.","D — mówi, co zrobił i czyj pomysł został użyty.")],
  mod2=["praca w parze zamiast trójki","role zaproponowane przez nauczyciela do wyboru","materiał częściowo podwojony"],
  mod3=["własna część zadania przy wspólnym stole","podział ról ustalony przez dorosłego","krótkie zadanie 5-minutowe","wsparcie przy komunikacji z rówieśnikiem"],
  mod1=["praca w zespole 3-osobowym z pełnym uzgodnieniem","przyjęcie pomysłu innego dziecka mimo własnego","rola koordynatora zespołu","prezentacja wspólnego efektu grupie"],
  wskazowka="Jeden komplet materiału na zespół jest całą metodą — bez niego dzieci pracują obok siebie i nigdy nie muszą się umówić."),

 ("B", 32): dict(
  nr="B7-32", tytul="Słowa, które pomagają",
  podtytul="Stosowanie zwrotów grzecznościowych: powitanie, pożegnanie, przepraszanie",
  sfera="VII WZAJEMNE KONTAKTY · Zwroty grzecznościowe (ICF d710 · PP 1.5)",
  czas="20 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko użyje trzech zwrotów grzecznościowych w sytuacji naturalnej po jednym przypomnieniu, w 3 z 5 sytuacji dnia, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Wita się, dziękuje i przeprasza w odpowiednich sytuacjach."),
    ("M","3 zwroty · 1 przypomnienie; 3 z 5 sytuacji."),
    ("A","Scenki i plakat zwrotów z rysunkami sytuacji."),
    ("R","Zwroty grzecznościowe otwierają i naprawiają relacje."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Rejestr zwrotów grzecznościowych · zapis dzienny.",
  pomoce=["plakat zwrotów z sytuacjami","pacynki do scenek","skrzynka „miłych słów”","karteczki z podziękowaniami dla kolegów","lustro"],
  metody=["scenki z pacynkami pokazujące skutek zwrotu","skrzynka miłych słów jako codzienny rytuał","modelowanie przez dorosłych w grupie","rozmowa o tym, co czuje druga osoba"],
  rodzaj="Zajęcia wspierające kompetencje społeczne",
  przebieg=[
    ("N — pacynkami odgrywa scenkę bez przeprosin.","D — nazywa, czego zabrakło i co poczuł bohater."),
    ("N — powtarza scenkę ze zwrotem grzecznościowym.","D — porównuje obie wersje, wskazuje różnicę."),
    ("N — pokazuje plakat trzech zwrotów.","D — dopasowuje zwrot do sytuacji na obrazku."),
    ("N — proponuje ćwiczenie w parach.","D — używa zwrotów w scence z kolegą."),
    ("N — otwiera skrzynkę miłych słów.","D — wrzuca karteczkę z podziękowaniem dla kolegi.")],
  mod2=["dwa zwroty zamiast trzech","przypomnienie przed sytuacją, nie po","scenka z dorosłym"],
  mod3=["odpowiedź na powitanie gestem lub słowem","modelowanie zwrotu przy każdej sytuacji","jeden zwrot ćwiczony przez dwa tygodnie","wsparcie komunikacyjne"],
  mod1=["stosowanie zwrotów wobec osób nowych i spoza grupy","przeproszenie z własnej inicjatywy i naprawienie szkody","nazwanie, co czuje osoba, którą się urazi","przypomnienie zwrotu koledze w formie życzliwej"],
  wskazowka="Pokaż scenkę bez zwrotu i ze zwrotem — pięciolatek uczy się grzeczności, gdy zobaczy jej skutek, a nie gdy usłyszy, że „tak się mówi”."),

 ("B", 33): dict(
  nr="B7-33", tytul="Mapa uczuć",
  podtytul="Mówienie o emocjach i wczuwanie się w przeżycia innych",
  sfera="VII WZAJEMNE KONTAKTY · Empatia (ICF d710 · PP 1.7·1.11)",
  czas="20 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko nazwie emocję bohatera opowiadania i poda jej przyczynę przy pytaniu naprowadzającym, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Nazywa emocję bohatera i wskazuje, co ją wywołało."),
    ("M","Emocja + przyczyna; 3 z 5 prób."),
    ("A","Historyjki społeczne i koło emocji z czterema stanami."),
    ("R","Empatia jest podstawą przyjaźni i rozwiązywania konfliktów."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Historyjki społeczne · zapis wypowiedzi dziecka.",
  pomoce=["koło emocji (radość, złość, smutek, strach)","historyjki społeczne z ilustracjami","lustro emocji","karty sytuacji z sali","pacynki"],
  metody=["opowiadanie z wyraźną emocją bohatera","pytanie o przyczynę: „dlaczego tak się poczuł?”","przenoszenie na sytuacje z sali","propozycje pomocy bohaterowi"],
  rodzaj="Zajęcia wspierające rozwój emocjonalny / pomoc p-p",
  przebieg=[
    ("N — czyta krótką historyjkę z wyraźną emocją.","D — słucha, obserwuje ilustracje."),
    ("N — pyta: „jak się poczuł bohater?”.","D — nazywa emocję, wskazuje ją na kole."),
    ("N — pyta o przyczynę: „dlaczego tak się poczuł?”.","D — podaje przyczynę emocji zdaniem z „bo”."),
    ("N — pyta: „co mogłoby mu pomóc?”.","D — proponuje sposób pomocy bohaterowi."),
    ("N — przenosi na salę: „kiedy ty tak się czułeś?”.","D — opowiada o własnej podobnej sytuacji.")],
  mod2=["dwie emocje do wyboru","nazwanie emocji bez przyczyny","historyjka bardzo krótka, jednoscenowa"],
  mod3=["wskazanie emocji na obrazku po nazwaniu przez dorosłego","dwie karty do wyboru","emocje podstawowe: radość i smutek","praca nad rozpoznawaniem własnych stanów"],
  mod1=["rozpoznanie emocji kolegi w realnej sytuacji i zaproponowanie pomocy","nazwanie emocji złożonej","przewidzenie, co poczuje kolega po danym zachowaniu","poprowadzenie rozmowy o uczuciach w grupie"],
  wskazowka="Pytanie „co mogłoby mu pomóc” jest ważniejsze niż samo nazwanie emocji — empatia zaczyna działać dopiero wtedy, gdy prowadzi do działania."),

 ("B", 34): dict(
  nr="B7-34", tytul="Trzy kroki zgody",
  podtytul="Szukanie rozwiązań w sytuacjach spornych i rozwiązywanie konfliktów",
  sfera="VII WZAJEMNE KONTAKTY · Konflikty (ICF d720 · PP 1.9)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko powie, o co był spór, i wybierze jedno z dwóch rozwiązań zaproponowanych przez nauczyciela, w 3 z 5 konfliktów, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Opisuje sytuację sporną i wybiera rozwiązanie."),
    ("M","Opis + wybór rozwiązania; 3 z 5 konfliktów."),
    ("A","Plakat trzech kroków zgody: mówię – słucham – wybieram."),
    ("R","Rozwiązywanie sporów utrzymuje relacje w grupie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta konfliktu · zapis wybranych rozwiązań.",
  pomoce=["plakat trzech kroków zgody","stolik mediacji z dwoma krzesłami","karty rozwiązań (na zmianę, razem, losujemy)","przedmiot mówcy","pacynki do scenek"],
  metody=["stały schemat trzech kroków","stolik mediacji jako miejsce rozmowy","karty rozwiązań jako gotowe opcje","dorosły jako mediator, nie rozjemca"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — pacynkami odgrywa spór o zabawkę.","D — obserwuje i nazywa problem pacynek."),
    ("N — pokazuje plakat: mówię – słucham – wybieram.","D — powtarza trzy kroki własnymi słowami."),
    ("N — zaprasza do stolika mediacji przy realnym sporze.","D — mówi, o co poszło, trzymając przedmiot mówcy."),
    ("N — pilnuje, by druga strona wysłuchała.","D — słucha wersji kolegi bez przerywania."),
    ("N — pokazuje dwie karty rozwiązań.","D — wybiera rozwiązanie i realizuje je z kolegą.")],
  mod2=["jedno rozwiązanie zaproponowane do przyjęcia","opis sytuacji z pytaniami pomocniczymi","mediacja natychmiast po zdarzeniu"],
  mod3=["zatrzymanie działania na sygnał i przyjęcie rozwiązania dorosłego","rozdzielenie stron i rozmowa osobno","krótkie, konkretne komunikaty","analiza ABC powtarzających się konfliktów"],
  mod1=["samodzielne zaproponowanie rozwiązania i uzgodnienie go","mediacja w sporze kolegów","przewidzenie konfliktu i zapobieżenie mu","przyjęcie rozwiązania niezgodnego z własnym oczekiwaniem"],
  wskazowka="Prowadź mediację przy stoliku, nie w miejscu zdarzenia — zmiana miejsca sama obniża napięcie i sygnalizuje, że zaczyna się rozmowa, a nie kara."),
}
