# -*- coding: utf-8 -*-
"""Konspekty do celów uzupełniających — obszary VI (techniczny), VII (cyfrowy),
VIII (artystyczny), IX (ruchowy) podstawy 2026. Wersja U."""

KONSPEKTY_U_O6789 = {
 ("U", 29): dict(
  nr="U6-29", tytul="Pudełko materiałów",
  podtytul="Badanie właściwości: twarde, miękkie, gładkie, przepuszczające wodę",
  sfera="VI OBSZAR TECHNICZNY · Właściwości materiałów (ICF d137 · PP 6.1)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko sprawdzi doświadczalnie, który materiał przepuszcza wodę, i wyjaśni wynik, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Bada materiały i formułuje wniosek z doświadczenia."),
    ("M","Doświadczenie z wnioskiem; 4 z 5 prób."),
    ("A","Pudełko materiałów zawsze dostępne w kąciku badacza."),
    ("R","Wiedza o materiałach poprzedza świadome konstruowanie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta doświadczenia · rejestr wniosków.",
  pomoce=["pudełko z próbkami: gąbka, folia, tkanina, papier, drewno","miski z wodą","zakraplacz","karta doświadczenia z kolumnami","tacki"],
  metody=["swobodne badanie dotykiem","doświadczenie z zakraplaczem","zapis wyniku znakiem na karcie","porównanie przewidywania z wynikiem"],
  rodzaj="Zajęcia techniczne i badawcze",
  przebieg=[
    ("N — rozkłada próbki materiałów.","D — dotyka ich i opisuje: twardy, miękki, gładki."),
    ("N — pyta: „który przepuści wodę?”.","D — przewiduje i zaznacza typ na karcie."),
    ("N — daje zakraplacz i miskę.","D — kropi wodą na każdą próbkę."),
    ("N — pyta, co się stało.","D — obserwuje i zaznacza wynik na karcie."),
    ("N — porównuje przewidywania z wynikami.","D — mówi, co go zaskoczyło, i wyjaśnia dlaczego.")],
  mod2=["trzy materiały zamiast pięciu","przewidywanie w formie tak/nie","karta z gotowymi rysunkami"],
  mod3=["dwa kontrastowe materiały: gąbka i folia","badanie prowadzone razem z dorosłym","obserwacja bez zapisu","materiały znane z codzienności"],
  mod1=["pięć materiałów z przewidywaniem i wnioskiem","zaproponowanie własnego badania","uporządkowanie materiałów od najbardziej do najmniej chłonnego"],
  wskazowka="Przewidywanie przed doświadczeniem jest ważniejsze niż sam wynik — to moment, w którym dziecko naprawdę myśli o materiale."),

 ("U", 30): dict(
  nr="U6-30", tytul="Jak powstaje dom",
  podtytul="Etapy budowania i materiały, z których powstają budynki",
  sfera="VI OBSZAR TECHNICZNY · Budowanie (ICF d137 · PP 6.2)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko opowie o budowie w 5 etapach i wyjaśni, dlaczego fundament jest pierwszy, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Porządkuje etapy budowy i uzasadnia ich kolejność."),
    ("M","5 etapów z uzasadnieniem; 4 z 5 prób."),
    ("A","Historyjka obrazkowa budowy plus próba budowy bez fundamentu."),
    ("R","Kolejność wynikająca z konieczności to inne myślenie niż kolejność z przyzwyczajenia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Historyjka budowy · rejestr poprawnych kolejności i uzasadnień.",
  pomoce=["historyjka obrazkowa budowy domu","próbki: cegła, drewno, szkło, beton","klocki i taca z piaskiem","zdjęcia budowy z okolicy","tablica etapów"],
  metody=["układanie historyjki obrazkowej","doświadczenie: budowa na piasku bez podstawy","obserwacja budowy na spacerze","dotykanie próbek materiałów"],
  rodzaj="Zajęcia techniczne",
  przebieg=[
    ("N — rozkłada obrazki etapów budowy.","D — układa je w kolejności."),
    ("N — daje próbki materiałów.","D — dopasowuje materiał do etapu."),
    ("N — proponuje budowę wieży na luźnym piasku.","D — buduje i obserwuje, że się przewraca."),
    ("N — daje twardą podkładkę.","D — buduje ponownie i porównuje wynik."),
    ("N — pyta: „dlaczego fundament jest pierwszy?”.","D — wyjaśnia na podstawie własnego doświadczenia.")],
  mod2=["trzy etapy zamiast pięciu","materiały dopasowane parami","uzasadnienie pytaniem naprowadzającym"],
  mod3=["dwa obrazki: przed i po","budowa na gotowej podstawie","nazwanie dwóch materiałów","obserwacja doświadczenia bez wykonywania"],
  mod1=["pięć etapów z uzasadnieniem","rozpoznanie etapu budowy na spacerze","zaprojektowanie kolejności dla własnej konstrukcji"],
  wskazowka="Wieża, która przewraca się na piasku, tłumaczy fundament w trzy sekundy. Żaden obrazek tego nie zrobi."),

 ("U", 31): dict(
  nr="U6-31", tytul="Równia i kołowrót",
  podtytul="Budowanie maszyn prostych i szukanie ich w urządzeniach codziennych",
  sfera="VI OBSZAR TECHNICZNY · Maszyny proste (ICF d155 · PP 6.4)",
  czas="35 min", forma="pary", cykl="1× w tygodniu",
  ter="Dziecko zbuduje kołowrót do wciągania ciężarka i wskaże urządzenie domowe, które działa podobnie, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Buduje maszynę prostą i rozpoznaje jej zasadę w urządzeniach z otoczenia."),
    ("M","Działający kołowrót plus jedno urządzenie; 4 z 5 prób."),
    ("A","Zestaw konstrukcyjny z rolkami, sznurkiem i deskami."),
    ("R","Maszyna prosta pokazuje, że technika to zasada, a nie magia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta doświadczenia · zdjęcie konstrukcji · rejestr wskazanych urządzeń.",
  pomoce=["deski i klocki na równię","szpulki, sznurek, korba","ciężarki i autka","zdjęcia urządzeń domowych","stoper"],
  metody=["budowanie w parach","porównywanie: z równią i bez","szukanie zasady w urządzeniach domowych","pomiar czasu zjazdu"],
  rodzaj="Zajęcia techniczne i konstrukcyjne",
  przebieg=[
    ("N — stawia deskę pod kątem.","D — puszcza autko i obserwuje zjazd."),
    ("N — zmienia kąt nachylenia.","D — porównuje, kiedy autko jedzie szybciej."),
    ("N — proponuje wciągnięcie ciężarka na górę.","D — próbuje ręką i ocenia, że jest ciężko."),
    ("N — pokazuje szpulkę z korbą i sznurkiem.","D — buduje kołowrót i wciąga ciężarek."),
    ("N — pokazuje zdjęcia urządzeń domowych.","D — wskazuje to, które działa podobnie, i tłumaczy dlaczego.")],
  mod2=["gotowa równia do sprawdzenia","kołowrót częściowo złożony","urządzenie wskazane z dwóch zdjęć"],
  mod3=["obserwacja zjazdu autka","kręcenie korbą gotowego kołowrotu","porównanie ciężko–lekko","udział w budowie razem z dorosłym"],
  mod1=["kołowrót zbudowany samodzielnie z uzasadnieniem","porównanie dwóch kątów równi z pomiarem","znalezienie trzech urządzeń z tą zasadą"],
  wskazowka="Najpierw niech dziecko spróbuje podnieść ciężarek ręką. Kołowrót ma sens dopiero jako odpowiedź na doświadczony wysiłek."),

 ("U", 32): dict(
  nr="U6-32", tytul="Zapal światło",
  podtytul="Budowanie prostych obwodów elektrycznych",
  sfera="VI OBSZAR TECHNICZNY · Obwody elektryczne (ICF d155 · PP 6.5)",
  czas="30 min", forma="pary", cykl="1× w tygodniu",
  ter="Dziecko zbuduje obwód z brzęczykiem, znajdzie przyczynę, gdy nie działa, i naprawi go, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Składa obwód, diagnozuje usterkę i usuwa ją."),
    ("M","Działający obwód po naprawie; 4 z 5 prób."),
    ("A","Bezpieczny zestaw na baterie paluszki, z dużymi zaciskami."),
    ("R","Szukanie przyczyny w niedziałającym układzie to myślenie inżynierskie w pigułce."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Schemat obwodu · obserwacja diagnozy i naprawy.",
  pomoce=["baterie paluszki w koszyczku","przewody z krokodylkami","żarówka na podstawce","brzęczyk","schemat obwodu rysunkowy"],
  metody=["składanie według schematu rysunkowego","celowe rozłączenie do diagnozy","praca w parach z podziałem ról","test: świeci / nie świeci"],
  rodzaj="Zajęcia techniczne",
  przebieg=[
    ("N — pokazuje elementy i schemat rysunkowy.","D — nazywa elementy i ogląda schemat."),
    ("N — podaje ostatni przewód.","D — domyka obwód i widzi światło."),
    ("N — prosi o samodzielne złożenie całości.","D — składa obwód według schematu."),
    ("N — po cichu rozłącza jeden krokodylek.","D — sprawdza obwód i szuka miejsca przerwy."),
    ("N — pyta: „gdzie był problem?”.","D — pokazuje usterkę, naprawia i sprawdza brzęczyk.")],
  mod2=["obwód z trzema elementami","schemat z kolorowymi przewodami","podpowiedź, w którym miejscu szukać"],
  mod3=["domknięcie gotowego obwodu","obserwacja zapalania żarówki","podanie elementu do ręki","obwód złożony razem z dorosłym"],
  mod1=["obwód z brzęczykiem i wyłącznikiem","diagnoza dwóch usterek","narysowanie schematu własnego obwodu"],
  wskazowka="Rozłączaj obwód po cichu i pozwól dziecku szukać. Podpowiedź „sprawdź ten przewód” odbiera całą wartość ćwiczenia."),

 ("U", 33): dict(
  nr="U6-33", tytul="Skąd bierze się energia",
  podtytul="Urządzenia zasilane z różnych źródeł",
  sfera="VI OBSZAR TECHNICZNY · Źródła energii (ICF d137 · PP 6.6)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko poda po dwa przykłady urządzeń dla trzech źródeł energii i powie, które nie zużywa prądu, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Przyporządkowuje urządzenia do źródeł zasilania."),
    ("M","Po dwa przykłady dla trzech źródeł; 4 z 5 prób."),
    ("A","Tablica źródeł energii z realnymi przedmiotami do posortowania."),
    ("R","Świadomość źródeł energii to wstęp do myślenia o oszczędzaniu i środowisku."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Tablica źródeł energii · rejestr poprawnych przyporządkowań.",
  pomoce=["latarka na baterie","lampka na kabel","kalkulator solarny","trzepaczka ręczna i młynek","tablica z czterema polami źródeł"],
  metody=["sortowanie realnych przedmiotów","sprawdzenie działania każdego urządzenia","doświadczenie z kalkulatorem na słońcu","porównanie z siłą własnych rąk"],
  rodzaj="Zajęcia techniczne",
  przebieg=[
    ("N — rozkłada urządzenia na dywanie.","D — ogląda je i próbuje uruchomić."),
    ("N — pokazuje tablicę czterech źródeł.","D — kładzie latarkę pod znakiem baterii."),
    ("N — zasłania kalkulator solarny dłonią.","D — obserwuje, że wyświetlacz gaśnie, i sortuje go do słońca."),
    ("N — podaje trzepaczkę ręczną.","D — kręci nią i przyporządkowuje do siły rąk."),
    ("N — pyta: „które nie zużywa prądu?”.","D — wskazuje i uzasadnia wybór.")],
  mod2=["trzy urządzenia zamiast wszystkich","dwa źródła: prąd i siła rąk","podpowiedź przez pokazanie baterii"],
  mod3=["dwa kontrastowe urządzenia","sortowanie do dwóch pól","uruchomienie urządzenia z pomocą","obserwacja pokazu"],
  mod1=["po dwa przykłady dla trzech źródeł","wskazanie urządzeń w sali i ich źródeł","propozycja, jak oszczędzać prąd w grupie"],
  wskazowka="Kalkulator solarny zasłonięty dłonią jest najlepszym eksponatem — działa i przestaje działać na oczach dziecka, bez tłumaczenia."),

 ("U", 34): dict(
  nr="U6-34", tytul="Regulamin warsztatu",
  podtytul="Bezpieczne korzystanie z urządzeń elektrycznych i narzędzi",
  sfera="VI OBSZAR TECHNICZNY · Bezpieczeństwo (ICF d571 · PP 6.7)",
  czas="20 min", forma="mała grupa", cykl="przed każdymi zajęciami technicznymi",
  ter="Dziecko sprawdzi przed pracą, czy stanowisko jest bezpieczne, i zwróci uwagę koledze łamiącemu zasadę, w 4 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Kontroluje bezpieczeństwo stanowiska i reaguje na łamanie zasad."),
    ("M","Sprawdzenie plus reakcja; 4 z 5 zajęć."),
    ("A","Regulamin obrazkowy nad stołem warsztatowym i rola kontrolera."),
    ("R","Zasada, której dziecko pilnuje u innych, staje się jego własną."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Regulamin warsztatu · karta obserwacji zachowań bezpiecznych.",
  pomoce=["regulamin obrazkowy","opaska kontrolera bezpieczeństwa","narzędzia dziecięce","zaślepki do gniazdek","karta odprawy przed pracą"],
  metody=["stała odprawa przed pracą","rola kontrolera bezpieczeństwa","regulamin w obrazkach","scenki sytuacji niebezpiecznych"],
  rodzaj="Zajęcia techniczne i prozdrowotne",
  przebieg=[
    ("N — wiesza regulamin obrazkowy nad stołem.","D — czyta obrazki i nazywa zasady."),
    ("N — wyznacza kontrolera bezpieczeństwa.","D — zakłada opaskę i obchodzi stanowiska."),
    ("N — pyta: „czy tu jest bezpiecznie?”.","D — sprawdza narzędzia, kable i przestrzeń."),
    ("N — odgrywa scenkę z łamaniem zasady.","D — reaguje i przypomina zasadę."),
    ("N — otwiera pracę warsztatową.","D — pracuje zgodnie z regulaminem.")],
  mod2=["trzy zasady zamiast pięciu","kontrola w parze z dorosłym","przypomnienie zasady przed sprawdzeniem"],
  mod3=["jedna zasada w cyklu","zatrzymanie na sygnał „stop”","narzędzie podawane przez dorosłego","obserwacja odprawy bez roli kontrolera"],
  mod1=["samodzielna odprawa całej grupy","reakcja na złamanie zasady z wyjaśnieniem","dopisanie nowej zasady do regulaminu"],
  wskazowka="Rola kontrolera działa lepiej niż dziesięć przypomnień. Dziecko, które pilnuje zasad u innych, przestaje je łamać samo."),

 ("U", 35): dict(
  nr="U6-35", tytul="Co robi to za nas",
  podtytul="Maszyny i urządzenia, które ułatwiają ludziom życie",
  sfera="VI OBSZAR TECHNICZNY · Rola urządzeń (ICF d137 · PP 6.8)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko porówna czynność wykonaną ręcznie i z urządzeniem, wskazując, co się zmienia, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Porównuje pracę ręczną i zmechanizowaną i nazywa różnicę."),
    ("M","Porównanie z wnioskiem; 4 z 5 prób."),
    ("A","Doświadczenie: ubijanie piany ręcznie i mikserem, z pomiarem czasu."),
    ("R","Rozumienie roli urządzeń poprzedza świadome i oszczędne korzystanie z nich."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zapis porównania · pomiar czasu · rejestr wniosków.",
  pomoce=["trzepaczka ręczna i mikser","tarka i młynek","stoper","karty urządzeń","tablica „ręcznie / urządzeniem”"],
  metody=["doświadczenie porównawcze z pomiarem czasu","dwa stanowiska obok siebie","zapis wyniku na tablicy","rozmowa o tym, co zyskujemy i tracimy"],
  rodzaj="Zajęcia techniczne",
  przebieg=[
    ("N — stawia dwa stanowiska: trzepaczka i mikser.","D — wybiera stanowisko i próbuje ubić pianę."),
    ("N — mierzy czas stoperem.","D — obserwuje, ile trwa każdy sposób."),
    ("N — zapisuje czasy na tablicy.","D — porównuje słupki i wskazuje szybszy sposób."),
    ("N — pyta: „co się zmienia oprócz czasu?”.","D — mówi o wysiłku i zmęczeniu rąk."),
    ("N — pokazuje karty innych urządzeń.","D — dobiera urządzenie do czynności i uzasadnia.")],
  mod2=["jedno porównanie zamiast dwóch","czas pokazany klepsydrą","wniosek wybierany z dwóch zdań"],
  mod3=["obserwacja porównania bez wykonywania","wskazanie szybszego sposobu","jedno urządzenie znane z domu","porównanie „szybko – wolno”"],
  mod1=["dwa porównania z pomiarem i wnioskiem","wskazanie urządzeń w przedszkolu","opowiedzenie, jak było, zanim je wynaleziono"],
  wskazowka="Pomiar stoperem zamienia opinię w dane. Dziecko przestaje mówić „mikser jest lepszy” i zaczyna mówić „mikser zrobił to trzy razy szybciej”."),

 ("U", 36): dict(
  nr="U6-36", tytul="Spacer komunikacyjny",
  podtytul="Środki transportu, infrastruktura i bezpieczne korzystanie z nich",
  sfera="VI OBSZAR TECHNICZNY · Transport (ICF d470 · PP 6.9)",
  czas="45 min (wyjście)", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko opowie, jak bezpiecznie wsiąść do autobusu i przejść przez jezdnię, i zastosuje to w praktyce, w 4 z 5 wyjść, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Zna i stosuje zasady bezpiecznego korzystania z transportu."),
    ("M","Opis plus zastosowanie; 4 z 5 wyjść."),
    ("A","Regularne spacery komunikacyjne po tej samej okolicy."),
    ("R","Bezpieczeństwo w ruchu drogowym to umiejętność ćwiczona w ruchu, nie w sali."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta spaceru komunikacyjnego · obserwacja zachowań w terenie.",
  pomoce=["kamizelki odblaskowe","karta spaceru z piktogramami","znaki drogowe zabawkowe","zdjęcia przystanku i przejścia","makieta skrzyżowania w sali"],
  metody=["ćwiczenie na makiecie przed wyjściem","spacer po stałej trasie","zatrzymanie i omówienie przy przejściu","rola przewodnika grupy"],
  rodzaj="Zajęcia techniczne i prozdrowotne",
  przebieg=[
    ("N — rozkłada makietę skrzyżowania w sali.","D — przeprowadza pionek przez przejście, mówiąc zasady."),
    ("N — rozdaje kamizelki i wychodzi z grupą.","D — nazywa mijane środki transportu."),
    ("N — zatrzymuje grupę przed przejściem.","D — mówi zasadę: stop, patrzę w lewo, w prawo, w lewo."),
    ("N — podaje kartę spaceru.","D — zaznacza piktogramem to, co zobaczył."),
    ("N — prowadzi na przystanek.","D — pokazuje, gdzie stanąć i jak wsiąść.")],
  mod2=["dwa środki transportu do nazwania","zasada powtarzana chórem przed przejściem","karta z trzema piktogramami"],
  mod3=["trzymanie za rękę dorosłego","nazwanie jednego pojazdu","zatrzymanie na sygnał","krótka trasa bez przejścia przez jezdnię"],
  mod1=["rola przewodnika grupy przy przejściu","opowiedzenie zasad młodszym przed wyjściem","narysowanie planu bezpiecznej trasy"],
  wskazowka="Makieta w sali to próba generalna. Trasa musi być zawsze ta sama, dopóki zasady nie wejdą w nawyk — dopiero potem warto ją zmieniać."),

 ("U", 37): dict(
  nr="U6-37", tytul="Dziesięć dni z zabawką",
  podtytul="Tworzenie własnych zabawek z materiałów, w tym z odzysku",
  sfera="VI OBSZAR TECHNICZNY · Projekt długoterminowy (ICF d155 · PP DE-P.1)",
  czas="20 min dziennie przez 10 dni", forma="indywidualnie w grupie", cykl="raz w trakcie edukacji przedszkolnej",
  ter="Dziecko zaplanuje zabawkę, dobierze materiały z odzysku, poprawi ją po próbie i pokaże grupie — raz w edukacji przedszkolnej.",
  ter_smart=[
    ("S","Prowadzi własny projekt zabawki przez dziesięć kolejnych dni."),
    ("M","Codzienny powrót do pracy przez 10 dni, z prezentacją."),
    ("A","Stała półka projektowa, na której praca czeka do jutra."),
    ("R","Wracanie do niedokończonej pracy buduje wytrwałość mocniej niż jednorazowe zajęcia."),
    ("T","Raz w edukacji przedszkolnej, z dokumentacją."),
  ],
  ter_kryt="Karta projektu 10 dni · zdjęcia etapów · wystawa zabawek.",
  pomoce=["skrzynia materiałów z odzysku","karta projektu z 10 polami","półka projektowa","taśma, sznurek, klej","aparat do zdjęć etapów"],
  metody=["planowanie rysunkiem przed budową","codzienny powrót do pracy","próba i poprawka","wystawa na koniec cyklu"],
  rodzaj="Projekt techniczny",
  przebieg=[
    ("N — otwiera skrzynię materiałów z odzysku.","D — ogląda materiały i wymyśla zabawkę."),
    ("N — daje kartę projektu.","D — rysuje plan zabawki i podpisuje pierwsze pole."),
    ("N — codziennie otwiera półkę projektową.","D — wraca do pracy i zaznacza kolejny dzień."),
    ("N — proponuje próbę działania.","D — sprawdza zabawkę i poprawia to, co nie działa."),
    ("N — organizuje wystawę.","D — pokazuje zabawkę i opowiada, co zmieniał po drodze.")],
  mod2=["cykl pięciodniowy","plan wybrany z dwóch propozycji","poprawka wskazana przez nauczyciela"],
  mod3=["dołożenie jednego elementu dziennie","praca nad wspólną zabawką grupy","przypomnienie o powrocie piktogramem","cykl trzydniowy"],
  mod1=["pełne dziesięć dni z planem i poprawkami","zabawka z ruchomym elementem","instruktaż dla młodszego kolegi"],
  wskazowka="Półka projektowa musi być nietykalna. Jeśli praca zniknie na noc do pudła, dziesięciodniowy cykl się rozpada — a to on jest tu celem, nie sama zabawka."),

 ("U", 38): dict(
  nr="U6-38", tytul="Makieta naszej okolicy",
  podtytul="Wspólne budowanie modelu przestrzeni",
  sfera="VI OBSZAR TECHNICZNY · Makieta (ICF d155 · PP DE-P.2)",
  czas="45 min × 4 spotkania", forma="cała grupa", cykl="raz w trakcie edukacji przedszkolnej",
  ter="Dziecko zaplanuje z grupą makietę, przyjmie w niej zadanie i oprowadzi po niej gości — raz w edukacji przedszkolnej.",
  ter_smart=[
    ("S","Współtworzy makietę i prezentuje ją odwiedzającym."),
    ("M","Wykonany fragment plus oprowadzanie."),
    ("A","Makieta na dużej płycie, budowana etapami przez cztery spotkania."),
    ("R","Model przestrzeni łączy plan, konstrukcję i opowieść o własnym miejscu."),
    ("T","Raz w edukacji przedszkolnej, z dokumentacją."),
  ],
  ter_kryt="Makieta grupy · karta podziału zadań · nagranie oprowadzania.",
  pomoce=["duża płyta jako podstawa","pudełka, rolki, korki","farby i papier","zdjęcia okolicy ze spaceru","tabliczki z imionami przy fragmentach"],
  metody=["spacer dokumentacyjny przed budową","podział makiety na fragmenty","praca etapami","oprowadzanie gości"],
  rodzaj="Projekt techniczny i społeczny",
  przebieg=[
    ("N — organizuje spacer i fotografowanie okolicy.","D — fotografuje budynek, który chce zbudować."),
    ("N — rozkłada płytę i dzieli ją na fragmenty.","D — wybiera swój fragment i podpisuje go."),
    ("N — wydaje materiały.","D — buduje swój budynek z pudełek i rolek."),
    ("N — pomaga połączyć fragmenty drogami.","D — dokłada drogę i sprawdza, czy pasuje do sąsiada."),
    ("N — zaprasza gości.","D — oprowadza po makiecie i opowiada o swoim fragmencie.")],
  mod2=["mniejszy fragment do wykonania","budynek z gotowego pudełka","oprowadzanie w parze"],
  mod3=["dołożenie jednego elementu do makiety","umieszczenie go we wskazanym miejscu","udział w spacerze dokumentacyjnym","pokazanie swojego fragmentu bez opowiadania"],
  mod1=["fragment z kilkoma obiektami i drogą","koordynacja połączeń między fragmentami","oprowadzanie gości po całej makiecie"],
  wskazowka="Podział na fragmenty z imionami rozwiązuje największy problem wspólnych prac: każde dziecko wie, co jest jego, i nikt nie zostaje bez roli."),

 ("U", 39): dict(
  nr="U7-39", tytul="Do czego to służy",
  podtytul="Rozpoznawanie urządzeń cyfrowych i ich zastosowań",
  sfera="VII OBSZAR CYFROWY · Urządzenia (ICF d360 · PP 7.2)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko dobierze urządzenie do zadania i uzasadni wybór, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje urządzenia cyfrowe i dobiera je do celu."),
    ("M","Trafny dobór z uzasadnieniem; 4 z 5 prób."),
    ("A","Realne urządzenia w kąciku plus karty zadań."),
    ("R","Świadome „do czego to służy” poprzedza świadome korzystanie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty urządzeń · rejestr doborów i uzasadnień.",
  pomoce=["stary telefon, aparat, tablet, radio","karty zadań: zrobić zdjęcie, zadzwonić, posłuchać","tablica dopasowań","zdjęcia urządzeń w użyciu"],
  metody=["oglądanie i nazywanie realnych urządzeń","dopasowanie zadania do urządzenia","uzasadnianie wyboru","scenki użycia"],
  rodzaj="Zajęcia wspierające kompetencje cyfrowe",
  przebieg=[
    ("N — rozkłada urządzenia na dywanie.","D — ogląda je i nazywa te, które zna."),
    ("N — pyta: „do czego służy każde?”.","D — mówi po jednym zastosowaniu."),
    ("N — pokazuje kartę zadania: „zrobić zdjęcie”.","D — wybiera urządzenie i kładzie kartę przy nim."),
    ("N — pyta: „dlaczego akurat to?”.","D — uzasadnia wybór."),
    ("N — proponuje scenkę użycia.","D — odgrywa krótką scenkę z urządzeniem.")],
  mod2=["trzy urządzenia zamiast czterech","dwa urządzenia do wyboru przy zadaniu","uzasadnienie pytaniem naprowadzającym"],
  mod3=["dwa urządzenia znane z domu","wskazanie zamiast nazwania","zastosowanie pokazane obrazkiem","dopasowanie do wzoru"],
  mod1=["cztery urządzenia z uzasadnieniem","zadanie wykonalne dwoma urządzeniami i wybór lepszego","opowiedzenie, jak radzono sobie bez nich"],
  wskazowka="Stare, niedziałające urządzenia sprawdzają się lepiej niż działające — dziecko ogląda je bez pokusy uruchomienia i rozmowa naprawdę dotyczy funkcji."),

 ("U", 40): dict(
  nr="U7-40", tytul="Umowa ekranowa",
  podtytul="Podstawowe zasady higieny cyfrowej",
  sfera="VII OBSZAR CYFROWY · Higiena cyfrowa (ICF d570 · PP 7.3)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko ułoży plan dnia z czasem na ekran i bez ekranu i wyjaśni, dlaczego przerwy są potrzebne, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Planuje czas z ekranem i bez oraz uzasadnia potrzebę przerw."),
    ("M","Plan dnia z uzasadnieniem; 4 z 5 prób."),
    ("A","Umowa ekranowa grupy z klepsydrą jako sygnałem końca."),
    ("R","Nawyk przerwy powstaje w przedszkolu albo nie powstaje wcale."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Umowa ekranowa grupy · plan dnia · obserwacja reakcji na sygnał końca.",
  pomoce=["klepsydra","plakat umowy ekranowej","karty czynności z ekranem i bez","paski do układania planu dnia","obrazek zmęczonych oczu"],
  metody=["klepsydra jako sygnał, nie polecenie dorosłego","układanie planu dnia z pasków","ćwiczenie na odpoczynek oczu","wspólne ustalanie umowy"],
  rodzaj="Zajęcia prozdrowotne i cyfrowe",
  przebieg=[
    ("N — pokazuje klepsydrę i włącza film.","D — ogląda i obserwuje przesypujący się piasek."),
    ("N — czeka na koniec klepsydry.","D — odkłada urządzenie na sygnał."),
    ("N — proponuje ćwiczenie na oczy: patrz w okno.","D — wykonuje ćwiczenie i mówi, jak się czuje."),
    ("N — rozkłada paski czynności.","D — układa plan dnia z ekranem i bez ekranu."),
    ("N — pyta: „po co nam przerwy?”.","D — wyjaśnia, odwołując się do zmęczenia oczu.")],
  mod2=["plan z czterech pasków","dwie zasady zamiast trzech","sygnał dodatkowo dźwiękowy"],
  mod3=["odłożenie urządzenia na sygnał z pomocą dorosłego","jedna zasada w cyklu","klepsydra krótsza","ćwiczenie oczu razem z grupą"],
  mod1=["plan dnia z uzasadnieniem każdej przerwy","przypominanie grupie o klepsydrze","rozmowa z rodzicem o umowie domowej"],
  wskazowka="Klepsydra przejmuje rolę „złego dorosłego”. Koniec ogłasza piasek, nie nauczyciel — i to zdejmuje z sytuacji cały opór."),

 ("U", 41): dict(
  nr="U7-41", tytul="Nie mówię obcym",
  podtytul="Zagrożenia w sieci i ochrona informacji o sobie",
  sfera="VII OBSZAR CYFROWY · Bezpieczeństwo w sieci (ICF d571 · PP 7.4)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko rozpozna w 4 scenkach sytuację niebezpieczną, powie, co zrobić, i uzasadni, w 4 z 5 scenek, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje ryzyko w kontakcie online i wskazuje właściwą reakcję."),
    ("M","4 scenki; 4 z 5 prób."),
    ("A","Scenki z pacynką „nieznajomy z gry” i karta „mówię dorosłemu”."),
    ("R","Reakcja wyćwiczona w scence działa szybciej niż zapamiętana zasada."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Scenki bezpieczeństwa · karta „mówię dorosłemu” · rejestr reakcji.",
  pomoce=["pacynka nieznajomego","karty informacji prywatnych: imię, adres, zdjęcie","karta „mówię dorosłemu”","tablica: mówię / nie mówię","zdjęcia zaufanych dorosłych"],
  metody=["scenki z pacynką","sortowanie informacji na prywatne i zwykłe","ćwiczenie zdania odmowy","wskazanie zaufanego dorosłego"],
  rodzaj="Zajęcia prozdrowotne i cyfrowe",
  przebieg=[
    ("N — wprowadza pacynkę, która pyta o adres.","D — słucha pytania."),
    ("N — przypomina zasadę: to jest tajemnica.","D — mówi pacynce: „nie powiem”."),
    ("N — rozkłada karty informacji.","D — sortuje je na „mówię” i „nie mówię”."),
    ("N — pokazuje kartę „mówię dorosłemu”.","D — wskazuje, do kogo pójdzie po pomoc."),
    ("N — odgrywa kolejną scenkę z prośbą o zdjęcie.","D — odmawia i mówi o tym dorosłemu.")],
  mod2=["dwie scenki zamiast czterech","zasada przypomniana przed każdą scenką","odpowiedź wybierana z dwóch"],
  mod3=["jedna scenka z wyraźnym pytaniem o adres","odpowiedź „nie” gestem","pacynka jako jedyny rozmówca","wskazanie dorosłego na zdjęciu"],
  mod1=["cztery scenki z uzasadnieniem reakcji","rozpoznanie scenki bezpiecznej wśród niebezpiecznych","wytłumaczenie zasady młodszemu"],
  wskazowka="Ćwicz samo zdanie odmowy, na głos, wiele razy. Wiedza „nie podaję adresu” nie pomaga, jeśli dziecko nie ma gotowych słów w ustach."),

 ("U", 42): dict(
  nr="U7-42", tytul="Reklama a prawda",
  podtytul="Rozpoznawanie reklam i rozumienie, czemu służą",
  sfera="VII OBSZAR CYFROWY · Media i reklama (ICF d163 · PP 7.5)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko porówna reklamę z rzeczywistym produktem i wskaże, co reklama przedstawia korzystniej, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odróżnia reklamę od informacji i dostrzega jej perswazyjny charakter."),
    ("M","Porównanie z wnioskiem; 4 z 5 prób."),
    ("A","Zestawienie zdjęcia reklamowego z prawdziwym produktem na stole."),
    ("R","Dziecko, które porówna obraz z rzeczą, przestaje wierzyć obrazowi bezkrytycznie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw reklam · zapis porównania · rejestr wniosków.",
  pomoce=["gazetki reklamowe","prawdziwe produkty z reklam","lupa","tablica „na obrazku / naprawdę”","wagi i miarki"],
  metody=["zestawienie obrazu z rzeczą","porównanie wielkości i wyglądu","pytanie „po co ktoś to zrobił?”","tworzenie własnej reklamy"],
  rodzaj="Zajęcia wspierające krytyczny odbiór mediów",
  przebieg=[
    ("N — pokazuje gazetkę reklamową.","D — wskazuje, co reklama zachęca kupić."),
    ("N — stawia obok prawdziwy produkt.","D — porównuje go ze zdjęciem."),
    ("N — pyta: „co się zgadza, a co nie?”.","D — wskazuje różnice w wielkości i wyglądzie."),
    ("N — pyta: „po co zrobiono taką reklamę?”.","D — mówi, że po to, żeby ktoś kupił."),
    ("N — proponuje zrobienie reklamy klocków.","D — tworzy reklamę i mówi, co w niej podkreślił.")],
  mod2=["jedno porównanie zamiast kilku","różnica wskazana pytaniem","reklama produktu dobrze znanego"],
  mod3=["rozpoznanie reklamy wśród dwóch obrazków","porównanie wielkości gestem","produkt obecny na stole","potwierdzenie tak/nie"],
  mod1=["porównanie z wnioskiem o przesadzie","znalezienie reklamy w otoczeniu","stworzenie reklamy prawdziwej i przesadzonej"],
  wskazowka="Postaw prawdziwy produkt obok zdjęcia. Różnica między obrazkiem a rzeczą, którą dziecko trzyma w ręce, mówi więcej niż każde tłumaczenie."),

 ("U", 43): dict(
  nr="U8-43", tytul="Nieoczywiste połączenia",
  podtytul="Łączenie przedmiotów, dźwięków i kształtów w nowe układy",
  sfera="VIII OBSZAR ARTYSTYCZNY · Twórcze łączenie (ICF d155 · PP 8.2)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko połączy elementy z dwóch różnych zbiorów w jedną pracę i wyjaśni pomysł, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Tworzy nowe układy z niepasujących do siebie elementów i uzasadnia je."),
    ("M","Praca z dwóch zbiorów plus wyjaśnienie; 4 z 5 prób."),
    ("A","Dwa pudełka tworzyw losowane bez podglądania."),
    ("R","Twórczość to zestawianie znanego w nieznany sposób, nie wymyślanie z niczego."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Pudełko tworzyw · zdjęcia prac · zapis wyjaśnień.",
  pomoce=["dwa pudełka z różnymi tworzywami","dzwoneczki i materiały dźwiękowe","klej, sznurek, taśma","podest wystawowy","karty „co to może być?”"],
  metody=["losowanie z dwóch pudełek","zakaz odkładania wylosowanego elementu","nazywanie powstałej rzeczy","wystawa z podpisami"],
  rodzaj="Zajęcia plastyczne i twórcze",
  przebieg=[
    ("N — stawia dwa pudełka z różnymi tworzywami.","D — losuje po jednym elemencie z każdego."),
    ("N — przypomina zasadę: obu trzeba użyć.","D — ogląda elementy i szuka pomysłu."),
    ("N — udostępnia materiały łączące.","D — łączy elementy w jedną pracę."),
    ("N — pyta: „co powstało?”.","D — nazywa swoją pracę."),
    ("N — układa prace na podeście.","D — wyjaśnia grupie swój pomysł.")],
  mod2=["losowanie z jednego pudełka plus element wybrany","dwa pomysły do wyboru","nazwanie pracy jednym słowem"],
  mod3=["element podany do ręki","łączenie taśmą bez klejenia","praca wspólna z dorosłym","dowolne użycie elementu"],
  mod1=["połączenie elementów z dwóch zbiorów z uzasadnieniem","dodanie elementu dźwiękowego","zaproponowanie zawartości pudełka na kolejny raz"],
  wskazowka="Zasada „obu trzeba użyć” jest tu silnikiem pomysłu. Bez niej dziecko odłoży trudniejszy element i zrobi to, co zawsze."),

 ("U", 44): dict(
  nr="U8-44", tytul="Orkiestra z odzysku",
  podtytul="Rozpoznawanie instrumentów i tworzenie własnych",
  sfera="VIII OBSZAR ARTYSTYCZNY · Instrumenty (ICF d920 · PP 8.5)",
  czas="35 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko wykona instrument z odzysku, dobierze materiał do żądanego brzmienia i zagra partię w orkiestrze, w 4 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Buduje instrument świadomie dobierając materiał do brzmienia i gra w zespole."),
    ("M","Instrument plus partia w orkiestrze; 4 z 5 zajęć."),
    ("A","Warsztat instrumentów i cotygodniowa próba orkiestry."),
    ("R","Dobór materiału do dźwięku łączy słuch z myśleniem technicznym."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw instrumentów własnych · nagranie orkiestry.",
  pomoce=["pojemniki, ryż, groch, kasza","gumki i pudełka","nagrania instrumentów","tablica partytury obrazkowej","batuta"],
  metody=["porównanie brzmień różnych wypełnień","budowa instrumentu","partytura obrazkowa","próba orkiestry z dyrygentem"],
  rodzaj="Zajęcia muzyczne i techniczne",
  przebieg=[
    ("N — puszcza nagrania instrumentów.","D — rozpoznaje i nazywa te, które zna."),
    ("N — daje trzy wypełnienia do wyboru.","D — potrząsa każdym i porównuje brzmienie."),
    ("N — pyta: „chcesz dźwięk cichy czy głośny?”.","D — dobiera wypełnienie do zamierzonego brzmienia."),
    ("N — pomaga zamknąć i ozdobić instrument.","D — kończy instrument i sprawdza jego dźwięk."),
    ("N — pokazuje partyturę obrazkową i dyryguje.","D — gra swoją partię we właściwym momencie.")],
  mod2=["dwa wypełnienia do wyboru","instrument częściowo przygotowany","partia grana w parze"],
  mod3=["gotowa grzechotka do ozdobienia","gra na sygnał dorosłego","rozpoznanie dwóch instrumentów","udział w graniu chóralnym"],
  mod1=["instrument z uzasadnionym doborem materiału","gra partii solowej","dyrygowanie fragmentem utworu"],
  wskazowka="Pozwól potrząsać wszystkimi wypełnieniami przed decyzją. Wybór ryżu zamiast grochu ma być słyszalną decyzją, a nie przypadkiem."),

 ("U", 45): dict(
  nr="U8-45", tytul="Głośno, cicho, wesoło, smutno",
  podtytul="Dynamika, tempo, barwa i nastrój muzyki",
  sfera="VIII OBSZAR ARTYSTYCZNY · Cechy dźwięku (ICF d115 · PP 8.7)",
  czas="25 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko porówna dwa utwory pod względem tempa, barwy i nastroju i uzasadni różnicę, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Opisuje utwór cechami dźwięku i porównuje dwa utwory."),
    ("M","Porównanie trzech cech; 4 z 5 prób."),
    ("A","Karty nastrojów i ruch ciałem jako odpowiedź na muzykę."),
    ("R","Nazwanie tego, co się słyszy, pogłębia odbiór i buduje słownik muzyczny."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw nagrań · karty nastrojów · zapis porównań.",
  pomoce=["dwa kontrastowe nagrania","karty nastrojów","wstążki do ruchu","tablica cech: tempo, głośność, nastrój","instrumenty do ilustrowania"],
  metody=["ruch ciałem jako odpowiedź na muzykę","karty nastrojów zamiast słów","porównanie dwóch utworów obok siebie","ilustrowanie cech instrumentem"],
  rodzaj="Zajęcia muzyczne",
  przebieg=[
    ("N — puszcza żywy utwór i rozdaje wstążki.","D — porusza się zgodnie z tempem."),
    ("N — zmienia na utwór spokojny.","D — zmienia ruch i zauważa różnicę."),
    ("N — rozkłada karty nastrojów.","D — wybiera kartę pasującą do każdego utworu."),
    ("N — pyta o tempo i głośność.","D — określa obie cechy dla każdego utworu."),
    ("N — prosi o porównanie.","D — mówi, czym utwory się różnią, i uzasadnia.")],
  mod2=["dwie cechy zamiast trzech","karty nastrojów zamiast wypowiedzi","utwory bardzo kontrastowe"],
  mod3=["reakcja ruchem bez nazywania","wybór z dwóch kart nastroju","jedna cecha: głośno–cicho","udział w ruchu grupowym"],
  mod1=["porównanie trzech cech z uzasadnieniem","zilustrowanie nastroju instrumentem","dobranie muzyki do sytuacji w grupie"],
  wskazowka="Ruch poprzedza nazywanie. Dziecko najpierw musi poczuć tempo w nogach, żeby móc powiedzieć, że utwór jest szybki."),

 ("U", 46): dict(
  nr="U8-46", tytul="Słowniczek sztuki",
  podtytul="Pojęcia opisujące wyraz artystyczny w muzyce, obrazie i teatrze",
  sfera="VIII OBSZAR ARTYSTYCZNY · Pojęcia sztuki (ICF d137 · PP 8.8)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko użyje określeń rytm, barwa, kompozycja, rola, opisując trzy dzieła z różnych dziedzin, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Stosuje pojęcia artystyczne do opisu dzieł z różnych dziedzin."),
    ("M","Cztery pojęcia przy trzech dziełach; 4 z 5 prób."),
    ("A","Słowniczek grupy z ilustracją do każdego pojęcia."),
    ("R","Słownik pojęć zamienia „ładne” w rozmowę o tym, co konkretnie działa."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Słowniczek grupy · zapis opisów dzieł.",
  pomoce=["reprodukcje obrazów","nagrania muzyczne","zdjęcia scen teatralnych","słowniczek grupy z ilustracjami","karty pojęć"],
  metody=["jedno pojęcie na zajęcia","ilustrowanie pojęcia własną pracą","opisywanie dzieła kartami pojęć","powroty do słowniczka"],
  rodzaj="Zajęcia wspierające edukację artystyczną",
  przebieg=[
    ("N — wprowadza pojęcie „rytm” i klaszcze.","D — powtarza rytm i szuka go w obrazie."),
    ("N — wkleja pojęcie do słowniczka grupy.","D — rysuje ilustrację do pojęcia."),
    ("N — pokazuje obraz i puszcza muzykę.","D — wskazuje kartą, które pojęcie pasuje."),
    ("N — pokazuje zdjęcie ze spektaklu.","D — nazywa rolę i mówi, co robi aktor."),
    ("N — prosi o opis trzech dzieł.","D — używa pojęć ze słowniczka przy każdym.")],
  mod2=["dwa pojęcia zamiast czterech","opis jednego dzieła","pojęcie przypomniane przed opisem"],
  mod3=["jedno pojęcie w cyklu","wskazanie karty zamiast opisu","dzieło znane z poprzednich zajęć","ilustrowanie pojęcia ruchem"],
  mod1=["cztery pojęcia przy trzech dziełach","porównanie rytmu w muzyce i w obrazie","dopisanie własnego pojęcia do słowniczka"],
  wskazowka="Wprowadzaj po jednym pojęciu na zajęcia i wracaj do słowniczka. Cztery nowe słowa naraz zostaną słowami, a nie narzędziami."),

 ("U", 47): dict(
  nr="U9-47", tytul="Tor zmysłów",
  podtytul="Schemat własnego ciała i zmysły w zadaniach ruchowych",
  sfera="IX OBSZAR RUCHOWY · Schemat ciała (ICF d445 · PP 9.3)",
  czas="30 min", forma="mała grupa", cykl="2× w tygodniu",
  ter="Dziecko przejdzie tor przeszkód z zasłoniętymi oczami, kierując się słuchem i dotykiem, i opisze, co pomogło, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wykorzystuje słuch i dotyk do orientacji w ruchu i nazywa użyte zmysły."),
    ("M","Przejście toru plus opis; 4 z 5 prób."),
    ("A","Tor z wyraźnymi sygnałami dźwiękowymi i fakturami pod stopami."),
    ("R","Świadomość ciała i zmysłów poprawia koordynację i poczucie bezpieczeństwa w ruchu."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Tor przeszkód · karta schematu ciała · obserwacja przejścia.",
  pomoce=["opaska na oczy","maty o różnych fakturach","dzwonek prowadzący","karta schematu ciała","woreczki sensoryczne"],
  metody=["nazywanie części ciała przed torem","tor z fakturami i dźwiękiem","przewodnik dźwiękowy","omówienie po przejściu"],
  rodzaj="Zajęcia ruchowe i sensoryczne",
  przebieg=[
    ("N — prosi o dotknięcie nazwanych części ciała.","D — dotyka i nazywa: łokieć, kolano, pięta."),
    ("N — pokazuje tor z różnymi fakturami.","D — przechodzi tor z otwartymi oczami."),
    ("N — proponuje opaskę na oczy.","D — zakłada ją i staje na starcie."),
    ("N — dzwoni dzwonkiem na końcu toru.","D — idzie w stronę dźwięku, czując faktury stopami."),
    ("N — pyta: „co ci pomogło?”.","D — mówi o dźwięku i o tym, co czuł pod stopami.")],
  mod2=["opaska na część trasy","dzwonek dzwoniący bez przerwy","tor z trzema fakturami"],
  mod3=["tor z otwartymi oczami","przejście za rękę z dorosłym","dwie faktury kontrastowe","nazwanie części ciała przez wskazanie"],
  mod1=["cały tor z opaską i opisem użytych zmysłów","prowadzenie kolegi głosem","zaprojektowanie własnego toru"],
  wskazowka="Opaska bywa dla dziecka trudna. Daj ją jako propozycję, nie polecenie — przejście z zamkniętymi oczami działa tak samo, a nie budzi lęku."),

 ("U", 48): dict(
  nr="U9-48", tytul="Nasze zawody sportowe",
  podtytul="Udział w wydarzeniu promującym zdrowy styl życia",
  sfera="IX OBSZAR RUCHOWY · Wydarzenie prozdrowotne (ICF d920 · PP DE-R.6)",
  czas="90 min (wydarzenie)", forma="cała grupa", cykl="raz w roku szkolnym",
  ter="Dziecko pomoże przygotować zawody, weźmie w nich udział i opowie, po co dbamy o ruch — raz w roku, z dokumentacją.",
  ter_smart=[
    ("S","Współorganizuje wydarzenie prozdrowotne, uczestniczy w nim i uzasadnia jego sens."),
    ("M","Udział w przygotowaniu i w konkurencjach plus wypowiedź."),
    ("A","Zawody przygotowane przez dzieci: plakat, sprzęt, medale."),
    ("R","Wydarzenie zapamiętuje się na lata i buduje pozytywny obraz aktywności."),
    ("T","Raz w roku szkolnym, z dokumentacją."),
  ],
  ter_kryt="Karta wydarzenia · zdjęcia · zapis wypowiedzi o zdrowym stylu życia.",
  pomoce=["sprzęt do konkurencji","materiały na plakat","medale wykonane przez dzieci","tablica wyników bez rywalizacji","woda i owoce na metę"],
  metody=["przygotowanie sprzętu przez dzieci","konkurencje bez wyłaniania przegranych","medale dla wszystkich uczestników","rozmowa podsumowująca"],
  rodzaj="Wydarzenie prozdrowotne",
  przebieg=[
    ("N — ogłasza zawody i pyta o pomysły konkurencji.","D — proponuje konkurencję i pomaga ją nazwać."),
    ("N — rozdaje materiały na plakat.","D — wykonuje plakat zapraszający."),
    ("N — przygotowuje z dziećmi sprzęt i tor.","D — ustawia pachołki i sprawdza tor."),
    ("N — prowadzi zawody.","D — bierze udział w trzech konkurencjach."),
    ("N — rozdaje medale i częstuje owocami.","D — mówi, po co dbamy o ruch i zdrowe jedzenie.")],
  mod2=["udział w dwóch konkurencjach","pomoc przy jednym elemencie przygotowań","wypowiedź jednym zdaniem"],
  mod3=["udział w jednej konkurencji z dorosłym","obecność w roli kibica","uprzedzenie o hałasie i tłumie","konkurencja bez elementu ścigania się"],
  mod1=["współprowadzenie konkurencji","przywitanie gości w imieniu grupy","podsumowanie wydarzenia dla rodziców"],
  wskazowka="Medale dla wszystkich nie są tu ustępstwem. Celem jest przyjemne wspomnienie związane z ruchem — porażka na zawodach przedszkolnych działa dokładnie odwrotnie."),
}
