# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar III (porozumiewanie się), wersja C (6 lat)."""

KONSPEKTY_6_D3 = {
 ("C", 11): dict(
  nr="C3-11", tytul="Wyraźnie i płynnie",
  podtytul="Płynna, wyraźna mowa i poprawność wypowiadania głosek",
  sfera="III POROZUMIEWANIE SIĘ · Wymowa (ICF d330 · PP 3.2·3.14)",
  czas="20 min", forma="indywidualnie lub w parze", cykl="codziennie",
  ter="Dziecko użyje ćwiczonej głoski poprawnie w wyrazach i krótkich zdaniach podczas zajęć, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wymawia ćwiczoną głoskę poprawnie w wyrazach i zdaniach."),
    ("M","Wyrazy i zdania; 3 z 5 zajęć."),
    ("A","Lustro, karty obrazkowe z głoską w nagłosie i śródgłosie."),
    ("R","Poprawna wymowa warunkuje analizę głoskową i pisanie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta logopedyczna · próbka mowy spontanicznej.",
  pomoce=["lustro logopedyczne","karty obrazkowe z ćwiczoną głoską","gra planszowa z wyrazami","dyktafon","karta ćwiczeń dla rodziców"],
  metody=["ćwiczenia przed lustrem","utrwalanie w wyrazie, potem w zdaniu","gra planszowa z materiałem wyrazowym","transfer do mowy spontanicznej"],
  rodzaj="Zajęcia logopedyczne",
  przebieg=[
    ("N — pokazuje układ artykulacyjny przed lustrem.","D — powtarza głoskę, obserwując swoje usta."),
    ("N — podaje karty z wyrazami zawierającymi głoskę.","D — nazywa obrazki, kontrolując wymowę."),
    ("N — prowadzi grę planszową z tymi wyrazami.","D — używa wyrazów w zdaniach podczas gry."),
    ("N — nagrywa krótką wypowiedź dziecka.","D — słucha nagrania i wychwytuje swoje błędy."),
    ("N — przekazuje kartę ćwiczeń do domu.","D — pokazuje rodzicowi, co ćwiczy w tym tygodniu.")],
  mod2=["utrwalanie w izolacji i sylabach","wyrazy z głoską wyłącznie w nagłosie","modelowanie przed każdą próbą"],
  mod3=["ćwiczenia oddechowe i usprawniające aparat mowy","powtarzanie za dorosłym","głoska w izolacji","terapia logopedyczna z pełną diagnozą"],
  mod1=["utrzymanie poprawnej wymowy w mowie spontanicznej","autokontrola i poprawianie się bez uwagi dorosłego","dbałość o poprawność zdań","opowiadanie z zachowaniem poprawnej wymowy"],
  wskazowka="Nagranie jest najskuteczniejszą autokontrolą — dziecko, które usłyszy siebie, wyłapuje własne błędy szybciej, niż gdy poprawia je dorosły."),

 ("C", 12): dict(
  nr="C3-12", tytul="Dźwiękowe puzzle",
  podtytul="Analiza i synteza głoskowa wyrazów",
  sfera="III POROZUMIEWANIE SIĘ · Słuch fonemowy (ICF d310 · PP 3.14)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="codziennie",
  ter="Dziecko dokona analizy głoskowej wyrazu trzygłoskowego i syntezy wyrazu podanego głoskami, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Dzieli wyraz na głoski i scala głoski w wyraz."),
    ("M","Wyraz 3-głoskowy · analiza i synteza; 3 z 5 prób."),
    ("A","Liczmany głoskowe, obrazki, wolne tempo podawania."),
    ("R","Słuch fonemowy jest najsilniejszym predyktorem nauki czytania."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw wyrazów do analizy · karta wyników.",
  pomoce=["żetony-liczmany do głosek","obrazki wyrazów 3- i 4-głoskowych","pacynka mówiąca głoskami","kubeczki do układania głosek","lustro"],
  metody=["pacynka mówiąca powoli głoskami","żeton za każdą usłyszaną głoskę","od syntezy do analizy","stopniowanie: 3 głoski, potem 4 i 5"],
  rodzaj="Zajęcia wspierające przygotowanie do nauki czytania",
  przebieg=[
    ("N — pacynka mówi powoli: k–o–t.","D — scala głoski i podaje wyraz: kot."),
    ("N — pokazuje obrazek i prosi o podział.","D — dzieli wyraz na głoski, kładąc żetony."),
    ("N — pyta o pierwszą i ostatnią głoskę.","D — wskazuje odpowiedni żeton i nazywa głoskę."),
    ("N — wprowadza wyraz 4-głoskowy.","D — układa cztery żetony i nazywa głoski po kolei."),
    ("N — pyta o głoskę w środku wyrazu.","D — wskazuje środkowy żeton i nazywa głoskę.")],
  mod2=["wyrazy 3-głoskowe","synteza bez analizy","głoski podawane bardzo wolno"],
  mod3=["wyodrębnianie pierwszej głoski po przedłużeniu przez dorosłego","rozpoznawanie dźwięków otoczenia","podział na sylaby zamiast głosek","ćwiczenia słuchu fonemowego z logopedą"],
  mod1=["analiza i synteza wyrazu 5-głoskowego","wskazanie głoski w dowolnym miejscu wyrazu","układanie wyrazu z liter po analizie","wymyślanie wyrazów na daną głoskę"],
  wskazowka="Zacznij od syntezy, nie od analizy — scalanie głosek w wyraz jest dla sześciolatka łatwiejsze i daje sukces, który otwiera drogę do dzielenia."),

 ("C", 13): dict(
  nr="C3-13", tytul="Bajkopisarze",
  podtytul="Odtwarzanie i przekształcanie treści bajek, tworzenie własnych historii",
  sfera="III POROZUMIEWANIE SIĘ · Twórczość narracyjna (ICF d330 · PP 3.8·3.12)",
  czas="30 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko opowie treść bajki w czterech zdaniach z zachowaniem kolejności zdarzeń, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odtwarza fabułę bajki w spójnej, uporządkowanej wypowiedzi."),
    ("M","4 zdania w kolejności; 3 z 5 prób."),
    ("A","Kostki opowieści i mapa bajki jako rusztowanie."),
    ("R","Narracja rozwija język, pamięć i myślenie przyczynowo-skutkowe."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta narracji · zapis wypowiedzi dziecka.",
  pomoce=["kostki opowieści z symbolami","mapa bajki: bohater – problem – rozwiązanie – koniec","książka autorska grupy","pacynki bohaterów","dyktafon"],
  metody=["mapa bajki jako struktura opowiadania","kostki opowieści do przekształcania fabuły","tworzenie własnego zakończenia","zapisywanie opowieści dzieci w książce grupy"],
  rodzaj="Zajęcia wspierające rozwój językowy",
  przebieg=[
    ("N — czyta znaną bajkę i pokazuje mapę bajki.","D — wskazuje na mapie bohatera i problem."),
    ("N — prosi o odtworzenie treści według mapy.","D — opowiada bajkę w czterech zdaniach."),
    ("N — rzuca kostką opowieści: „a gdyby zamiast tego…?”.","D — przekształca fabułę zgodnie z wylosowanym symbolem."),
    ("N — proponuje wymyślenie innego zakończenia.","D — opowiada własne zakończenie bajki."),
    ("N — zapisuje historię w książce autorskiej grupy.","D — dyktuje tytuł i podpisuje swoją opowieść.")],
  mod2=["opowiadanie w 2–3 zdaniach","mapa bajki uzupełniana wspólnie","odtworzenie bez przekształcania"],
  mod3=["odtworzenie 2 wydarzeń z pomocą obrazków","odpowiedzi na pytania o treść","krótka bajka o prostej fabule","wsparcie logopedy"],
  mod1=["opowiadanie 6-zdaniowe z własnym zakończeniem","opowiedzenie bajki z perspektywy innego bohatera","wymyślenie całkiem nowej historii","przeczytanie własnej bajki grupie"],
  wskazowka="Mapa bajki z czterema polami zastępuje pytania pomocnicze — dziecko widzi strukturę opowieści i przestaje gubić się w szczegółach."),

 ("C", 14): dict(
  nr="C3-14", tytul="Debata przedszkolna",
  podtytul="Udział w rozmowie, przedstawianie i uzasadnianie własnej opinii",
  sfera="III POROZUMIEWANIE SIĘ · Argumentacja (ICF d350 · PP 3.1)",
  czas="25 min", forma="cała grupa (krąg)", cykl="2× w tygodniu",
  ter="Dziecko przedstawi swoje zdanie w rozmowie grupowej, czekając na swoją kolej, w 3 z 5 spotkań, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wypowiada własne zdanie w rozmowie z grupą."),
    ("M","1 wypowiedź · czekanie na kolej; 3 z 5 spotkań."),
    ("A","Przedmiot mówcy i zdania-wzory: „uważam, że…, ponieważ…”."),
    ("R","Umiejętność argumentowania buduje pozycję dziecka w grupie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Krąg dyskusyjny · rejestr wypowiedzi.",
  pomoce=["przedmiot mówcy","tabliczki tak/nie do głosowania","zdania-wzory na plakacie","tematy debat (czy zwierzę może mieszkać w przedszkolu?)","tablica argumentów"],
  metody=["temat bliski doświadczeniu dzieci","przedmiot mówcy regulujący kolejność","zdania-wzory jako rusztowanie argumentu","zapisywanie argumentów na tablicy"],
  rodzaj="Zajęcia wspierające rozwój językowy i społeczny",
  przebieg=[
    ("N — przedstawia temat debaty i prosi o głosowanie.","D — podnosi tabliczkę tak lub nie."),
    ("N — pokazuje zdanie-wzór: „uważam, że…, ponieważ…”.","D — formułuje swoje zdanie według wzoru."),
    ("N — przekazuje przedmiot mówcy kolejnym dzieciom.","D — czeka na swoją kolej, słuchając innych."),
    ("N — zapisuje argumenty na tablicy w dwóch kolumnach.","D — wskazuje argument, który go przekonał."),
    ("N — pyta, czy ktoś zmienił zdanie po debacie.","D — mówi, czy i dlaczego zmienił swoje zdanie.")],
  mod2=["wypowiedź po wywołaniu imieniem","zdanie-wzór podpowiadane","głosowanie bez uzasadniania"],
  mod3=["udział przez głosowanie tabliczką","wypowiedź do nauczyciela zamiast do grupy","temat bardzo konkretny","wsparcie w formułowaniu wypowiedzi"],
  mod1=["przedstawienie opinii z uzasadnieniem i odniesienie się do zdania innego dziecka","zadanie pytania rozmówcy","poprowadzenie debaty jako moderator","zmiana zdania z uzasadnieniem"],
  wskazowka="Pytanie „czy ktoś zmienił zdanie” jest sercem debaty — uczy, że słuchanie innych może coś zmienić, a to rzadka i cenna umiejętność."),

 ("C", 15): dict(
  nr="C3-15", tytul="English corner",
  podtytul="Reagowanie na proste polecenia w języku obcym nowożytnym",
  sfera="III POROZUMIEWANIE SIĘ · Język obcy (ICF d310 · PP 3.19)",
  czas="20 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko zareaguje poprawnie na 5 poleceń w języku obcym bez gestu wspierającego, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wykonuje polecenia w języku obcym bez podpowiedzi gestem."),
    ("M","5 poleceń; 3 z 5 zajęć."),
    ("A","Polecenia powtarzalne, wprowadzane metodą reagowania ruchem."),
    ("R","Osłuchanie z językiem obcym poprzedza naukę w klasie pierwszej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja zajęć języka obcego · karta reakcji.",
  pomoce=["karty obrazkowe słownictwa","maskotka mówiąca tylko po angielsku","piosenki z ruchem","kącik English corner","stemple za udział"],
  metody=["reagowanie ruchem na polecenie","maskotka jako stały bodziec językowy","piosenki z gestem","powtarzalny zestaw poleceń"],
  rodzaj="Zajęcia z języka obcego nowożytnego",
  przebieg=[
    ("N — wita maskotką: „Hello! Stand up, please”.","D — wstaje w reakcji na polecenie."),
    ("N — wydaje polecenia z gestem: sit down, clap.","D — wykonuje polecenia naśladując gest."),
    ("N — powtarza polecenia bez gestu.","D — reaguje na samo polecenie słowne."),
    ("N — prowadzi piosenkę z ruchem.","D — śpiewa refren i wykonuje ruchy."),
    ("N — żegna: „Goodbye” i przybija stempel.","D — odpowiada pożegnaniem i odbiera stempel.")],
  mod2=["3 polecenia zamiast 5","gest wspierający przy każdym poleceniu","polecenia najbardziej znane"],
  mod3=["reakcja na 2 polecenia z pokazem","naśladowanie ruchu grupy","udział w piosence bez poleceń","sprawdzenie rozumienia mowy ojczystej"],
  mod1=["reakcja na polecenia i odpowiadanie pojedynczymi słowami","nazywanie przedmiotów w języku obcym","zadanie pytania maskotce","poprowadzenie powitania dla grupy"],
  wskazowka="Maskotka, która „nie rozumie po polsku”, robi więcej niż godzina tłumaczenia — daje realny powód, by spróbować powiedzieć coś w obcym języku."),
}
