# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar V (dbanie o siebie), wersja B (5 lat)."""

KONSPEKTY_5_D5 = {
 ("B", 21): dict(
  nr="B5-21", tytul="Detektyw czystych rąk",
  podtytul="Samodzielne wykonywanie podstawowych czynności higienicznych",
  sfera="V DBANIE O SIEBIE · Higiena (ICF d510–d520 · PP 9.7)",
  czas="15 min + rutyna dnia", forma="mała grupa", cykl="codziennie",
  ter="Dziecko wykona mycie i wytarcie rąk samodzielnie po jednym przypomnieniu słownym, w 3 z 5 sytuacji dnia, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Myje i wyciera ręce w pełnym cyklu bez pomocy."),
    ("M","1 przypomnienie; 3 z 5 sytuacji dziennie."),
    ("A","Instrukcja przy umywalce; lampa UV pokazuje pominięte miejsca."),
    ("R","Higiena rąk to codzienny nawyk zdrowotny na całe życie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Lista kontrolna higieny · zapis dzienny.",
  pomoce=["farba lub brokat udający „zarazki”","instrukcja obrazkowa nad umywalką","piosenka-minutnik","lupa detektywistyczna","plakat o drobnoustrojach"],
  metody=["eksperyment z brokatem pokazujący pominięte miejsca","detektywistyczne sprawdzanie efektu","piosenka wyznaczająca czas","wyjaśnienie po co, nie tylko jak"],
  rodzaj="Kształtowanie samodzielności / edukacja zdrowotna",
  przebieg=[
    ("N — posypuje dłonie dzieci brokatem: „to nasze zarazki”.","D — ogląda brokat na dłoniach i między palcami."),
    ("N — prosi o umycie rąk tak jak zwykle.","D — myje ręce według instrukcji obrazkowej."),
    ("N — sprawdza dłonie lupą: „gdzie został brokat?”.","D — odnajduje pominięte miejsca: kciuk, między palcami."),
    ("N — pokazuje mycie tych miejsc z piosenką.","D — myje ponownie, obejmując wszystkie miejsca."),
    ("N — pyta: „po co myjemy ręce?”.","D — wyjaśnia własnymi słowami cel mycia.")],
  mod2=["instrukcja wskazywana przy każdym kroku","krótsza piosenka","sprawdzenie efektu bez lupy"],
  mod3=["prowadzenie rąk przez cały cykl","mydło podawane na dłonie","dwa kroki samodzielnie, reszta z pomocą","sprawdzenie nadwrażliwości dotykowej"],
  mod1=["higiena rąk, nosa i twarzy z własnej inicjatywy","wyjaśnienie zasad higieny młodszym dzieciom","przypomnienie koledze o pominiętym kroku","dbanie o higienę także poza salą"],
  wskazowka="Brokat pokazuje to, czego nie widać — po jednym takim eksperymencie dzieci myją kciuki i przestrzenie między palcami bez żadnego przypominania."),

 ("B", 22): dict(
  nr="B5-22", tytul="Wyścig z suwakiem",
  podtytul="Samodzielne ubieranie się i rozbieranie",
  sfera="V DBANIE O SIEBIE · Ubieranie (ICF d540 · PP 9.7)",
  czas="10 min (szatnia)", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko ubierze się samodzielnie korzystając z planu obrazkowego, prosząc o pomoc wyłącznie przy suwaku, w 3 z 5 wyjść, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Zakłada wszystkie części garderoby w prawidłowej kolejności."),
    ("M","Pomoc tylko przy suwaku; 3 z 5 wyjść."),
    ("A","Plan obrazkowy, ławeczka i stanowisko treningowe z suwakiem."),
    ("R","Samodzielność w szatni to warunek startu szkolnego."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Pomiar czasu ubierania · liczba próśb o pomoc.",
  pomoce=["plan obrazkowy kolejności ubierania","tablice manipulacyjne: suwak, guziki, rzepy","klepsydra w szatni","lustro","tabela osiągnięć szatniowych"],
  metody=["trening zapięć poza szatnią, na tablicy manipulacyjnej","stała kolejność ubierania","technika kurtki przez głowę","pomiar czasu jako motywacja, nie presja"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — na dywanie pokazuje tablicę z suwakiem.","D — ćwiczy łączenie i zasuwanie suwaka na tablicy."),
    ("N — w szatni wskazuje plan kolejności.","D — ubiera się według kolejności z planu."),
    ("N — pokazuje technikę kurtki przez głowę.","D — zakłada kurtkę samodzielnie."),
    ("N — pomaga wyłącznie przy połączeniu suwaka.","D — zasuwa suwak do góry sam."),
    ("N — zaznacza czas w tabeli osiągnięć.","D — sprawdza się w lustrze i idzie do grupy.")],
  mod2=["pomoc przy dwóch zapięciach","ubranie rozłożone przez dorosłego","bez pomiaru czasu"],
  mod3=["zakładanie dwóch części garderoby","rozpoczęcie ruchu przez dorosłego","ubranie bez trudnych zapięć","praca nad schematem ciała"],
  mod1=["pełne ubranie w czasie przewidzianym dla grupy, z zapięciami","wiązanie sznurowadeł","pomoc młodszemu dziecku","dobór ubrania do pogody i planu dnia"],
  wskazowka="Ćwicz suwak poza szatnią — w szatni jest pośpiech, kurtki i piętnaścioro dzieci; tablica manipulacyjna na dywanie daje spokój potrzebny do nauki."),

 ("B", 23): dict(
  nr="B5-23", tytul="Restauracja pod dobrą łyżką",
  podtytul="Spożywanie posiłków sztućcami i kulturalne zachowanie przy stole",
  sfera="V DBANIE O SIEBIE · Posiłki (ICF d550 · PP 9.7·WSR)",
  czas="posiłek", forma="stolik (4–6 dzieci)", cykl="codziennie",
  ter="Dziecko zje posiłek widelcem i łyżką, użyje serwetki i podziękuje po posiłku, w 3 z 5 posiłków, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Posługuje się sztućcami i stosuje zwyczaje stołu."),
    ("M","Sztućce · serwetka · podziękowanie; 3 z 5 posiłków."),
    ("A","Wzór nakrycia na podkładce; dorosły je razem z dziećmi."),
    ("R","Kultura stołu to codzienna kompetencja społeczna."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Obserwacja posiłku · karta kultury stołu.",
  pomoce=["podkładki z narysowanym nakryciem","serwetki w podajniku","widelce i łyżki dziecięce","karta zasad restauracji (4 obrazki)","dzwoneczek otwarcia restauracji"],
  metody=["scenografia restauracji nadająca rangę posiłkowi","podkładka jako wzór nakrycia","dorosły przy stole jako model","zasady stołu pokazane, nie wyliczane"],
  rodzaj="Kształtowanie samodzielności / kompetencje społeczne",
  przebieg=[
    ("N — dzwoni: „restauracja otwarta, zapraszam gości”.","D — siada przy stole, sprawdza nakrycie na podkładce."),
    ("N — pokazuje kartę zasad: sztućce, serwetka, dziękuję.","D — nazywa zasady widoczne na obrazkach."),
    ("N — je razem z dziećmi, modelując użycie widelca.","D — je widelcem i łyżką, naśladując dorosłego."),
    ("N — wskazuje serwetki w podajniku.","D — sięga po serwetkę i wyciera usta."),
    ("N — kończy posiłek: „dziękujemy kucharkom”.","D — dziękuje i odnosi naczynia.")],
  mod2=["sztućce tylko łyżka","przypomnienie o serwetce","krótszy posiłek"],
  mod3=["pomoc przy nabieraniu","kubek i miska dostosowane","cel: zjedzenie przy stole przez 10 minut","konsultacja przy trudnościach oralno-motorycznych"],
  mod1=["nakładanie sobie porcji i nalewanie napoju","poproszenie o dokładkę pełnym zdaniem","posprzątanie swojego miejsca","nakrycie stołu dla całego stolika"],
  wskazowka="Usiądź i zjedz z dziećmi — pięciolatek uczy się kultury stołu z obserwacji dorosłego przy tym samym stole, nie z instrukcji wygłaszanej nad stołem."),

 ("B", 24): dict(
  nr="B5-24", tytul="Strażnicy bezpieczeństwa",
  podtytul="Przestrzeganie zasad bezpieczeństwa w sali i na placu zabaw",
  sfera="V DBANIE O SIEBIE · Bezpieczeństwo (ICF d571 · PP 9.11)",
  czas="20 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko wymieni trzy zasady bezpieczeństwa i zastosuje je po jednym przypomnieniu grupowym, w 3 z 5 wyjść, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Nazywa zasady i stosuje je podczas zabawy na placu."),
    ("M","3 zasady · 1 przypomnienie; 3 z 5 wyjść."),
    ("A","Zasady wypracowane przez dzieci i zilustrowane ich zdjęciami."),
    ("R","Bezpieczeństwo warunkuje swobodę zabawy i samodzielność."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Tablica zasad · rejestr zdarzeń i przypomnień.",
  pomoce=["aparat do zdjęć","tablica zasad z fotografiami dzieci","odznaki strażnika bezpieczeństwa","scenki z pacynkami","plan placu zabaw z oznaczonymi strefami"],
  metody=["współtworzenie zasad przez dzieci","zdjęcia dzieci jako ilustracja zasady","scenki: co się stanie, gdy…","rola strażnika rotacyjnie w grupie"],
  rodzaj="Edukacja zdrowotna i bezpieczeństwo / pomoc p-p",
  przebieg=[
    ("N — pyta: „co może być niebezpieczne na placu?”.","D — podaje przykłady z własnego doświadczenia."),
    ("N — pacynkami odgrywa scenkę złamania zasady.","D — nazywa, co poszło nie tak i dlaczego."),
    ("N — proponuje sformułowanie trzech zasad grupy.","D — współtworzy zasady i wybiera ich brzmienie."),
    ("N — fotografuje dzieci pokazujące każdą zasadę.","D — pozuje do zdjęcia ilustrującego zasadę."),
    ("N — wręcza odznaki strażników na czas wyjścia.","D — pilnuje zasad na placu i zgłasza zagrożenia.")],
  mod2=["dwie zasady zamiast trzech","przypomnienie indywidualne przed wyjściem","odznaka strażnika jako stałe wsparcie"],
  mod3=["jedna zasada wprowadzana na dwa tygodnie","stałe towarzyszenie dorosłego","zasada pokazywana przed każdą sytuacją","ustalenie zasad indywidualnych"],
  mod1=["samodzielne przestrzeganie i zgłaszanie zagrożeń","wyjaśnienie zasad młodszej grupie","zaproponowanie nowej zasady dla sali","ocena, czy sytuacja jest bezpieczna"],
  wskazowka="Zasada wymyślona przez dzieci i zilustrowana ich zdjęciem jest przestrzegana nieporównanie lepiej niż plakat kupiony i powieszony przez dorosłego."),

 ("B", 25): dict(
  nr="B5-25", tytul="Barometr energii",
  podtytul="Komunikowanie potrzeby ruchu i odpoczynku, szukanie bezpiecznych przestrzeni",
  sfera="V DBANIE O SIEBIE · Samoregulacja (ICF d571 · PP 9.10)",
  czas="15 min + sytuacje naturalne", forma="mała grupa", cykl="codziennie",
  ter="Dziecko zgłosi potrzebę ruchu lub odpoczynku umówionym komunikatem i skorzysta z odpowiedniej przestrzeni, w 3 z 5 sytuacji dnia, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Zgłasza potrzebę ruchu lub wyciszenia i wybiera przestrzeń."),
    ("M","3 z 5 sytuacji dziennie."),
    ("A","Barometr energii na ścianie; dwa kąciki: ruchu i ciszy."),
    ("R","Rozpoznawanie własnego stanu chroni przed przeciążeniem."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta samoregulacji · zapis zgłoszeń dziecka.",
  pomoce=["barometr energii ze wskazówką (nisko – w sam raz – wysoko)","kącik ruchu: mata, poduszki do skakania","kącik ciszy: namiot, książki","karty strategii: skaczę, oddycham, piję wodę","klipsy ze zdjęciami dzieci"],
  metody=["wizualizacja poziomu energii","dwa kąciki jako realne rozwiązania","nazywanie stanu przez dorosłego jako wzór","codzienne sprawdzanie barometru przez grupę"],
  rodzaj="Zajęcia wspierające samoregulację / pomoc p-p",
  przebieg=[
    ("N — pokazuje barometr: „ile masz dziś energii?”.","D — przypina swój klips na barometrze."),
    ("N — nazywa własny stan: „mam dużo energii, muszę się poruszać”.","D — słyszy wzór opisu stanu."),
    ("N — przedstawia dwa kąciki i ich przeznaczenie.","D — wybiera kącik odpowiadający swojemu stanowi."),
    ("N — pokazuje karty strategii do wyboru.","D — korzysta ze strategii: skacze albo oddycha."),
    ("N — wraca do barometru po aktywności.","D — przesuwa klips i mówi, czy jest mu lepiej.")],
  mod2=["dwa poziomy barometru zamiast trzech","propozycja kącika przez dorosłego","stała strategia zamiast wyboru"],
  mod3=["nazwanie stanu przez dorosłego i wskazanie rozwiązania","stałe przerwy ruchowe w rytmie dnia","jeden kącik, zawsze ten sam","obserwacja pod kątem przeciążenia sensorycznego"],
  mod1=["rozpoznanie narastającego napięcia przed reakcją emocjonalną","nazwanie potrzeby pełnym zdaniem","dobranie strategii do konkretnej sytuacji","zauważenie stanu kolegi i zaproszenie go do kącika"],
  wskazowka="Nazwij głośno własny poziom energii — dorosły, który mówi „potrzebuję chwili ciszy”, uczy samoregulacji skuteczniej niż jakikolwiek plakat o emocjach."),
}
