# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar II (ogólne zadania i wymagania), wersja C (6 lat)."""

KONSPEKTY_6_D2 = {
 ("C", 6): dict(
  nr="C2-06", tytul="Plan w trzech krokach",
  podtytul="Układanie planu działania i realizowanie go etapami",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Planowanie (ICF d220 · PP 2.3)",
  czas="30 min", forma="para dzieci", cykl="3× w tygodniu",
  ter="Dziecko ułoży plan trzyetapowy i zrealizuje go, odhaczając kolejne kroki, w 3 z 5 zadań sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Układa plan przed pracą i realizuje kolejne etapy."),
    ("M","3 etapy · odhaczone kroki; 3 z 5 zadań."),
    ("A","Karty etapów do samodzielnego ułożenia; tablica planu."),
    ("R","Planowanie własnej pracy to kluczowa kompetencja ucznia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta planu · liczba zrealizowanych etapów.",
  pomoce=["karty etapów do układania","tablica planu z polami 1–3","klipsy do odhaczania","zadania projektowe: makieta, przepis, doświadczenie","karta oceny: czy efekt zgadza się z planem"],
  metody=["układanie planu przed pracą","odhaczanie etapów jako kontrola postępu","porównanie efektu z zamiarem","planowanie w parze z uzgodnieniem"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / przygotowanie do szkoły",
  przebieg=[
    ("N — przedstawia cel zadania i rozsypuje karty etapów.","D — ogląda karty i zastanawia się nad kolejnością."),
    ("N — pyta: „od czego trzeba zacząć?”.","D — układa karty na tablicy planu w kolejności."),
    ("N — odsuwa się, obserwuje realizację.","D — realizuje pierwszy etap i odhacza go klipsem."),
    ("N — przy zawahaniu wskazuje tablicę planu.","D — sprawdza plan i przechodzi do kolejnego etapu."),
    ("N — pyta: „czy wyszło tak, jak planowałeś?”.","D — porównuje efekt z zamiarem i ocenia zgodność.")],
  mod2=["plan 2-etapowy","karty etapów ułożone do połowy","pierwszy krok wskazany przez nauczyciela"],
  mod3=["realizacja planu ułożonego przez dorosłego","polecenia podawane po jednym","zadanie jednoetapowe","wsparcie pamięci sekwencyjnej"],
  mod1=["samodzielne zaplanowanie 4 etapów i sprawdzenie efektu","zaplanowanie pracy zespołu","modyfikacja planu w trakcie, gdy coś nie działa","zapisanie planu rysunkiem dla kolegi"],
  wskazowka="Pytanie „czy wyszło tak, jak planowałeś” zamyka pętlę uczenia — bez porównania efektu z zamiarem plan pozostaje ćwiczeniem układania obrazków."),

 ("C", 7): dict(
  nr="C2-07", tytul="Cicha godzina pracy",
  podtytul="Samodzielna i wytrwała praca przez czas zajęć kierowanych",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Wytrwałość (ICF d210 · PP 2.6)",
  czas="25 min", forma="indywidualnie przy stolikach", cykl="codziennie",
  ter="Dziecko pracuje samodzielnie przez 15 minut zajęcia, zgłaszając potrzebę pomocy zamiast przerywania pracy, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Pracuje bez przerywania i sygnalizuje potrzebę pomocy."),
    ("M","15 minut pracy; 3 z 5 zajęć."),
    ("A","Karta pomocy do postawienia na stoliku; zegar pracy."),
    ("R","Wytrwałość na zadaniu wprost warunkuje funkcjonowanie w klasie."),
    ("T","Weryfikacja po 12 tygodniach; potem 25 minut."),
  ],
  ter_kryt="Pomiar czasu pracy samodzielnej · zapis przerwań.",
  pomoce=["kartoniki „potrzebuję pomocy” do postawienia","zegar pracy z tarczą","teczki z zadaniami do wyboru","przegródki na prace skończone","tabela pracy własnej"],
  metody=["sygnał pomocy bez przerywania pracy innym","zegar pokazujący czas pracy","zadania w teczkach do samodzielnego wyboru","odkładanie skończonej pracy do przegródki"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / przygotowanie do szkoły",
  przebieg=[
    ("N — ogłasza cichą godzinę pracy i ustawia zegar.","D — wybiera teczkę z zadaniem i siada przy stoliku."),
    ("N — pokazuje kartonik pomocy: „postaw, gdy utkniesz”.","D — kładzie kartonik przy sobie, zaczyna pracę."),
    ("N — obchodzi salę, reaguje tylko na postawione kartoniki.","D — pracuje samodzielnie, sygnalizuje trudność kartonikiem."),
    ("N — udziela krótkiej podpowiedzi i odchodzi.","D — korzysta z podpowiedzi i kontynuuje pracę."),
    ("N — kończy cichą godzinę sygnałem.","D — odkłada pracę do przegródki i zaznacza ją w tabeli.")],
  mod2=["10 minut pracy","zadanie krótsze, dwuczęściowe","nauczyciel podchodzi co 3 minuty"],
  mod3=["5 minut pracy z przerwą ruchową","zadanie jednoczęściowe","stanowisko za parawanem","obserwacja pod kątem trudności z uwagą"],
  mod1=["25 minut pracy do końca zadania","wybór trudniejszej teczki","dokończenie pracy z poprzedniego dnia","pomoc koledze bez przerywania własnej pracy"],
  wskazowka="Kartonik pomocy uczy dwóch rzeczy naraz — proszenia o wsparcie i niewyrywania się z krzesła; bez niego dziecko przy każdej trudności wstaje i traci wątek."),

 ("C", 8): dict(
  nr="C2-08", tytul="Klub dobrych przegranych",
  podtytul="Radzenie sobie z przegraną i traktowanie błędu jako elementu uczenia się",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Porażka (ICF d240 · PP 2.8·9.2)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko po przegranej nazwie swoją emocję i dokończy grę, nie przerywając zabawy innym, w 3 z 5 gier, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa emocję po przegranej i kontynuuje grę."),
    ("M","Emocja nazwana · gra dokończona; 3 z 5 gier."),
    ("A","Kodeks dobrego gracza i zdania-wzory na kartonikach."),
    ("R","Odporność na porażkę chroni motywację w całej edukacji."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Gry z regułami · karta reakcji na przegraną.",
  pomoce=["gry planszowe z elementem losowym","kodeks dobrego gracza (4 punkty)","kartoniki ze zdaniami: „gratuluję”, „zagramy jeszcze raz”","tablica błędów, które czegoś nauczyły","medale dobrego gracza"],
  metody=["kodeks gracza ustalony przed grą","zdania-wzory na przegraną","docenianie postawy, nie wyniku","tablica pożytecznych błędów"],
  rodzaj="Zajęcia wspierające rozwój emocjonalny / kompetencje społeczne",
  przebieg=[
    ("N — przypomina kodeks dobrego gracza przed grą.","D — nazywa zasady: gram do końca, gratuluję, próbuję znowu."),
    ("N — prowadzi grę z elementem losowym.","D — gra, przestrzegając kolejności i reguł."),
    ("N — po przegranej pyta: „co teraz czujesz?”.","D — nazywa emocję: złość, rozczarowanie."),
    ("N — pokazuje kartonik: „gratuluję”.","D — gratuluje zwycięzcy i kończy grę."),
    ("N — zapisuje na tablicy błąd, który czegoś nauczył.","D — mówi, co zrobi inaczej w następnej grze.")],
  mod2=["gra krótsza, 3 rundy","gra zespołowa zamiast indywidualnej","zdanie na przegraną podpowiadane"],
  mod3=["gra z dorosłym, bez rywalizacji","przerwanie gry przed rozstrzygnięciem","gra kooperacyjna (wszyscy wygrywają razem)","praca nad regulacją emocji"],
  mod1=["przyjęcie przegranej i wskazanie, co poprawi","pogratulowanie z własnej inicjatywy","wsparcie kolegi, który przegrał","poprowadzenie gry jako sędzia"],
  wskazowka="Zacznij od gier kooperacyjnych, a rywalizację wprowadzaj dopiero po nich — sześciolatek uczy się przegrywać wtedy, gdy najpierw poczuł, że wygrywa się razem."),

 ("C", 9): dict(
  nr="C2-09", tytul="Wczoraj, dziś, jutro",
  podtytul="Stosowanie się do rytmu dnia i posługiwanie się pojęciami następstwa czasu",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Orientacja w czasie (ICF d230 · PP 4.12)",
  czas="20 min", forma="cała grupa", cykl="codziennie (krąg poranny)",
  ter="Dziecko użyje poprawnie pojęć wczoraj, dzisiaj, jutro w rozmowie o planie dnia, w 3 z 5 rozmów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Stosuje pojęcia następstwa czasu w wypowiedzi o wydarzeniach."),
    ("M","3 pojęcia poprawnie; 3 z 5 rozmów."),
    ("A","Kalendarz grupowy ze zdjęciami i osią wczoraj–dziś–jutro."),
    ("R","Orientacja w czasie porządkuje planowanie i pamięć zdarzeń."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kalendarz grupowy · zapis wypowiedzi dziecka.",
  pomoce=["kalendarz grupowy ze zdjęciami wydarzeń","oś czasu: wczoraj – dziś – jutro","karty dni tygodnia","zdjęcia z ostatnich dni","tabliczka pogody"],
  metody=["codzienny rytuał kręgu porannego","oś czasu z realnymi zdjęciami","przypominanie wczoraj i planowanie jutra","dni tygodnia w piosence"],
  rodzaj="Zajęcia wspierające orientację w czasie / przygotowanie do szkoły",
  przebieg=[
    ("N — otwiera krąg poranny przy kalendarzu.","D — wskazuje dzisiejszy dzień na kalendarzu."),
    ("N — pokazuje zdjęcie z poprzedniego dnia.","D — mówi, co robili wczoraj."),
    ("N — pyta o plan: „co robimy dzisiaj?”.","D — odczytuje plan i nazywa aktywności."),
    ("N — zapowiada wydarzenie na jutro.","D — mówi zdaniem, co będzie jutro."),
    ("N — śpiewa z grupą piosenkę o dniach tygodnia.","D — wymienia kolejne dni tygodnia.")],
  mod2=["dwa pojęcia: dziś i jutro","wypowiedź z podpowiedzią wzrokową","wybór odpowiedzi z dwóch"],
  mod3=["wskazanie zdjęcia z dzisiaj","nazwanie aktualnej aktywności","oś czasu z dwoma polami","wsparcie pamięci zdarzeń"],
  mod1=["opowiedzenie o wczoraj i zaplanowanie jutra z użyciem nazw dni","określenie, ile dni zostało do wydarzenia","prowadzenie kalendarza grupowego","posługiwanie się pojęciami tydzień i miesiąc"],
  wskazowka="Używaj realnych zdjęć z ostatnich dni — pojęcie „wczoraj” staje się zrozumiałe dopiero wtedy, gdy dziecko widzi siebie na fotografii z konkretnego dnia."),

 ("C", 10): dict(
  nr="C2-10", tytul="Skrzynka strategii",
  podtytul="Doprowadzanie zadań do końca mimo trudności i radzenie sobie ze stresem",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Radzenie sobie (ICF d240 · PP 2.6·2.12)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko samodzielnie wybierze strategię z tablicy strategii i dokończy zadanie po przerwie, w 3 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wybiera strategię radzenia sobie i wraca do zadania."),
    ("M","Wybór strategii · dokończenie zadania; 3 z 5 sytuacji."),
    ("A","Tablica strategii z czterema sprawdzonymi sposobami."),
    ("R","Samodzielne radzenie sobie z trudnością chroni przed rezygnacją."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Tablica strategii · rejestr zastosowań.",
  pomoce=["tablica strategii: oddech, przerwa, proszę o pomoc, dzielę na części","zadania o rosnącej trudności","klepsydra przerwy","skrzynka z gniotkami","karta „udało mi się mimo trudności”"],
  metody=["strategie nazwane i widoczne","przerwa jako narzędzie, nie ucieczka","dzielenie zadania na części","docenianie wytrwałości, nie tylko efektu"],
  rodzaj="Zajęcia wspierające samoregulację / przygotowanie do szkoły",
  przebieg=[
    ("N — przedstawia tablicę czterech strategii.","D — nazywa strategie i wskazuje znane sobie."),
    ("N — daje zadanie trudniejsze niż zwykle.","D — pracuje i napotyka trudność."),
    ("N — wskazuje tablicę: „którą strategię wybierasz?”.","D — wybiera strategię i stosuje ją."),
    ("N — odmierza klepsydrą czas przerwy.","D — po przerwie wraca do zadania."),
    ("N — zapisuje sukces na karcie wytrwałości.","D — mówi, która strategia mu pomogła.")],
  mod2=["dwie strategie do wyboru","strategia proponowana przez dorosłego","zadanie dzielone na części przez nauczyciela"],
  mod3=["jedna stała strategia","natychmiastowe wsparcie przy pierwszym sygnale napięcia","zadanie skrócone","współpraca z psychologiem"],
  mod1=["rozpoznanie napięcia przed jego narastaniem i samodzielne zastosowanie strategii","dokończenie zadania bez pomocy","zaproponowanie nowej strategii dla tablicy","podpowiedzenie strategii koledze"],
  wskazowka="Przerwa musi mieć wyznaczony koniec — klepsydra zamienia ucieczkę od zadania w narzędzie powrotu do niego."),
}
