# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VI (życie domowe, czynności użyteczne), wersja B (5 lat)."""

KONSPEKTY_5_D6 = {
 ("B", 26): dict(
  nr="B6-26", tytul="Zdjęcie przed i po",
  podtytul="Samodzielne sprzątanie po sobie miejsca zabawy i pracy",
  sfera="VI ŻYCIE DOMOWE · Porządkowanie (ICF d640 · PP 2.5·WSR)",
  czas="10 min", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko posprząta miejsce pracy po sygnale i sprawdzi efekt według zdjęcia wzorcowego, bez pomocy dorosłego, w 3 z 5 dni, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Porządkuje stanowisko i porównuje efekt ze wzorcem."),
    ("M","Pełne stanowisko; 3 z 5 dni."),
    ("A","Zdjęcie wzorcowe przy każdym kąciku; aparat do zdjęć „po”."),
    ("R","Sprzątanie po sobie to warunek pracy w każdej grupie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zdjęcie wzorcowe · zapis dzienny wykonania.",
  pomoce=["zdjęcia wzorcowe kącików","aparat lub tablet do zdjęć „po sprzątaniu”","etykiety na pojemnikach","tablica porównawcza przed–po","minutnik"],
  metody=["porównanie ze zdjęciem jako kryterium","dokumentowanie efektu zdjęciem","samoocena zamiast oceny dorosłego","krótki, wyznaczony czas"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — pokazuje zdjęcie wzorcowe kącika przed pracą.","D — ogląda, jak ma wyglądać miejsce po skończeniu."),
    ("N — uruchamia minutnik na sprzątanie.","D — odkłada materiały do oznaczonych pojemników."),
    ("N — podaje tablet: „zrób zdjęcie swojego miejsca”.","D — fotografuje uporządkowane stanowisko."),
    ("N — zaprasza do porównania obu zdjęć.","D — porównuje i poprawia to, co się różni."),
    ("N — wiesza zdjęcie na tablicy przed–po.","D — pokazuje efekt grupie.")],
  mod2=["sprzątanie z listą obrazkową kroków","połowa stanowiska z pomocą","dłuższy czas na minutniku"],
  mod3=["odkładanie wskazywanych przedmiotów","sprzątanie razem z dorosłym","jedno pudełko do uporządkowania","wzmocnienie po każdym odłożonym elemencie"],
  mod1=["sprzątanie bez sygnału, z własnej inicjatywy","domykanie porządku w całym kąciku","pomoc koledze bez wyręczania","zaproponowanie lepszego układu pojemników"],
  wskazowka="Zdjęcie zrobione przez dziecko zmienia sprzątanie w zadanie z widocznym efektem — porównanie dwóch obrazów ocenia lepiej niż uwaga dorosłego."),

 ("B", 27): dict(
  nr="B6-27", tytul="Dyżurni tygodnia",
  podtytul="Pełnienie dyżurów: rozdawanie, zbieranie, porządkowanie, pomaganie",
  sfera="VI ŻYCIE DOMOWE · Dyżury (ICF d640 · PP 1.10·WSR)",
  czas="15 min dziennie", forma="para dyżurnych", cykl="codziennie",
  ter="Dziecko wykona pełny dwuetapowy dyżur według planu obrazkowego, bez pomocy dorosłego, i zgłosi jego zakończenie, w 3 z 5 dyżurów, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Realizuje oba etapy dyżuru i informuje o zakończeniu."),
    ("M","2 etapy bez pomocy; 3 z 5 dyżurów."),
    ("A","Grafik tygodniowy i plan obrazkowy czynności."),
    ("R","Dyżur uczy odpowiedzialności za wspólną przestrzeń."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Grafik dyżurów · karta samooceny dziecka.",
  pomoce=["grafik tygodniowy ze zdjęciami","fartuszki i identyfikatory dyżurnych","plany obrazkowe dyżurów (stołowy, przyrodniczy, biblioteczny)","karta samooceny z uśmieszkami","dzwonek zgłoszenia zakończenia"],
  metody=["dyżury zróżnicowane, wybierane na tydzień","plan obrazkowy zamiast poleceń","samoocena po dyżurze","rozliczenie dyżuru na kręgu podsumowującym"],
  rodzaj="Kształtowanie samodzielności / kompetencje społeczne",
  przebieg=[
    ("N — w poniedziałek przedstawia grafik dyżurów.","D — wybiera dyżur na cały tydzień."),
    ("N — omawia plan obrazkowy wybranego dyżuru.","D — nazywa oba etapy swojego zadania."),
    ("N — odsuwa się i obserwuje bez ingerencji.","D — wykonuje dyżur samodzielnie."),
    ("N — czeka na sygnał zakończenia.","D — dzwoni dzwonkiem i zgłasza wykonanie."),
    ("N — na kręgu prosi o podsumowanie dyżuru.","D — ocenia swoją pracę na karcie samooceny.")],
  mod2=["dyżur jednoetapowy","dorosły obok przez cały dyżur","dyżur co drugi dzień"],
  mod3=["jedna czynność w ramach dyżuru","polecenie z gestem przy każdym kroku","dyżur w parze z dzieckiem sprawnym","wzmocnienie natychmiast po czynności"],
  mod1=["dyżur tygodniowy z planowaniem kolejności","wprowadzenie nowego dyżurnego w obowiązki","zaproponowanie nowego rodzaju dyżuru","rozliczenie dyżuru przed grupą"],
  wskazowka="Pozwól wybrać dyżur na cały tydzień — powtarzalność buduje mistrzostwo, a wybór buduje odpowiedzialność; codzienna rotacja odbiera jedno i drugie."),

 ("B", 28): dict(
  nr="B6-28", tytul="Umowa o zabawki",
  podtytul="Dbanie o zabawki i uzgadnianie zasad dzielenia się rzeczami wspólnymi",
  sfera="VI ŻYCIE DOMOWE · Wspólne rzeczy (ICF d650 · PP 1.3·2.5)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko uzgodni z jednym dzieckiem kolejność korzystania z zabawki przy wsparciu nauczyciela i dotrzyma ustalenia, w 3 z 5 sytuacji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Ustala z kolegą, kto pierwszy i na jak długo, i przestrzega tego."),
    ("M","Ustalenie dotrzymane; 3 z 5 sytuacji."),
    ("A","Klepsydra i karta umowy czynią ustalenie widocznym."),
    ("R","Umiejętność dzielenia się to fundament zabawy w grupie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Obserwacja zabawy swobodnej · rejestr uzgodnień.",
  pomoce=["karty umowy z polami na dwa imiona","klepsydry 3- i 5-minutowe","zabawki atrakcyjne w jednym egzemplarzu","szpital zabawek (pudełko na uszkodzone)","taśma i klej do napraw"],
  metody=["umowa spisana obrazkiem, nie tylko wypowiedziana","klepsydra jako neutralny rozjemca","szpital zabawek uczący dbałości","dorosły jako mediator, nie sędzia"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — pokazuje jedną atrakcyjną zabawkę na dwoje chętnych.","D — zgłasza chęć zabawy tą zabawką."),
    ("N — proponuje umowę: „kto pierwszy i na jak długo?”.","D — uzgadnia kolejność z drugim dzieckiem."),
    ("N — wpisuje imiona na karcie i stawia klepsydrę.","D — bawi się przez swój czas, widząc klepsydrę."),
    ("N — sygnalizuje koniec czasu, nie odbiera zabawki.","D — przekazuje zabawkę koledze zgodnie z umową."),
    ("N — pokazuje szpital zabawek: „co wymaga naprawy?”.","D — odkłada uszkodzoną zabawkę do naprawy.")],
  mod2=["umowa proponowana przez dorosłego do zaakceptowania","klepsydra 3-minutowa","dwa egzemplarze zabawki"],
  mod3=["zabawa równoległa z identycznymi zabawkami","przekazanie zabawki z pomocą dorosłego","uprzedzenie o zmianie z wyprzedzeniem","praca nad odraczaniem gratyfikacji"],
  mod1=["ustalenie zasady dla całej grupy i jej pilnowanie","mediacja w sporze dwójki kolegów","zaproponowanie rozwiązania, gdy zabawek jest za mało","naprawa zabawki dla grupy"],
  wskazowka="Nie odbieraj zabawki po sygnale — pozwól dziecku samemu ją przekazać. Umowa dotrzymana własnymi rękami uczy więcej niż umowa wyegzekwowana."),

 ("B", 29): dict(
  nr="B6-29", tytul="Pakowanie na wyprawę",
  podtytul="Pakowanie własnych rzeczy i przygotowanie do wyjścia",
  sfera="VI ŻYCIE DOMOWE · Organizacja rzeczy (ICF d640 · PP 2.5·WSR)",
  czas="15 min", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko spakuje swoje rzeczy według listy obrazkowej i sprawdzi jej kompletność przed wyjściem, w 3 z 5 dni, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Kompletuje rzeczy z listy i sprawdza je przed wyjściem."),
    ("M","Pełna lista · sprawdzenie na końcu; 3 z 5 dni."),
    ("A","Lista obrazkowa przypięta do worka; plecak z przegrodami."),
    ("R","Samodzielne pakowanie to codzienna umiejętność ucznia."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Lista obrazkowa · kontrola kompletności przed wyjściem.",
  pomoce=["listy obrazkowe rzeczy (worek, plecak na wycieczkę)","worki i plecaki dzieci","karty rzeczy do wyboru (potrzebne / niepotrzebne)","zdjęcia pogody","tablica odpraw przed wyjściem"],
  metody=["lista jako narzędzie kontroli","zabawa w odprawę przed wyprawą","dobieranie rzeczy do celu i pogody","sprawdzenie kompletności przez dziecko"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — ogłasza wyprawę i pokazuje zdjęcie pogody.","D — nazywa pogodę i przewiduje, co będzie potrzebne."),
    ("N — rozkłada karty rzeczy: potrzebne i niepotrzebne.","D — wybiera rzeczy odpowiednie do wyprawy."),
    ("N — podaje listę obrazkową do worka.","D — pakuje rzeczy zgodnie z listą."),
    ("N — prowadzi odprawę: „sprawdź swoją listę”.","D — sprawdza kompletność i uzupełnia braki."),
    ("N — otwiera wyprawę, gdy wszyscy gotowi.","D — zgłasza gotowość i wychodzi z grupą.")],
  mod2=["lista 2-elementowa","rzeczy rozłożone obok worka","sprawdzenie razem z dorosłym"],
  mod3=["spakowanie jednej rzeczy wskazanej przez dorosłego","rzecz podawana do ręki","stała, niezmienna lista","wsparcie pamięci sekwencyjnej"],
  mod1=["samodzielne ułożenie listy przed wyjściem","uwzględnienie pogody i długości wyprawy","pomoc koledze w sprawdzeniu kompletności","spakowanie plecaka na całodniową wycieczkę"],
  wskazowka="Zacznij od wyboru rzeczy potrzebnych i niepotrzebnych — pakowanie bez tego etapu jest przepisywaniem listy, a nie decydowaniem, co naprawdę zabieram."),
}
