# -*- coding: utf-8 -*-
"""Konspekty do celów uzupełniających — obszary I (społeczny), II (osobisty),
III (językowy) podstawy 2026. Wersja U."""

KONSPEKTY_U_O123 = {
 ("U", 1): dict(
  nr="U1-01", tytul="Skarbonka naszej grupy",
  podtytul="Oszczędzanie jako czekanie na coś ważniejszego",
  sfera="I OBSZAR SPOŁECZNY · Oszczędzanie (ICF d860 · PP 1.15)",
  czas="25 min", forma="mała grupa (6 dzieci)", cykl="2× w tygodniu przez 4 tygodnie",
  ter="Dziecko zaplanuje w zabawie zakup wymagający odkładania żetonów przez kilka dni i wyjaśni, dlaczego warto było poczekać, w 4 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odkłada żetony na wybrany cel zamiast wydać je od razu i uzasadnia czekanie."),
    ("M","4 z 5 sytuacji zakupowych."),
    ("A","Przezroczysta skarbonka grupy z obrazkiem celu — postęp widać każdego dnia."),
    ("R","Odroczenie gratyfikacji to fundament samoregulacji i planowania."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Dziennik skarbonki · liczba dni z odłożonym żetonem · zapis uzasadnień.",
  pomoce=["przezroczysta skarbonka","żetony w dwóch kolorach","obrazek celu (np. nowa gra)","dziennik skarbonki","towar do sklepiku z cenami w żetonach"],
  metody=["zabawa tematyczna w sklep","wizualizacja postępu w przezroczystym słoju","codzienny rytuał odkładania","rozmowa kierowana o czekaniu"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i ekonomiczne",
  przebieg=[
    ("N — pokazuje pusty słój i obrazek celu, pyta: „co musimy zrobić, żeby to mieć?”.","D — ogląda cel i zgłasza pomysł."),
    ("N — rozdaje po 3 żetony i otwiera sklepik z drobiazgami.","D — wybiera: kupić dziś czy odłożyć."),
    ("N — prosi, by odkładający wrzucili żeton do słoja.","D — wrzuca żeton i zaznacza dzień w dzienniku."),
    ("N — po kilku dniach pokazuje pełny słój.","D — kupuje wspólny cel i cieszy się z niego."),
    ("N — pyta: „co by było, gdybyśmy wydali wszystko pierwszego dnia?”.","D — wyjaśnia, dlaczego warto było poczekać.")],
  mod2=["wybór między dwoma drobiazgami zamiast całego sklepiku","podpowiedź obrazkowa przy decyzji","krótszy cykl — cel osiągalny w 3 dni"],
  mod3=["jeden żeton dziennie, decyzja tak/nie","dorosły trzyma żeton razem z dzieckiem","cel osiągalny tego samego dnia","nagroda za sam gest odłożenia"],
  mod1=["planowanie zakupu na kilka dni z rozpisaniem żetonów","tłumaczenie młodszym, po co jest skarbonka","porównanie dwóch celów i wybór droższego"],
  wskazowka="Skarbonka musi być przezroczysta. Dziecko w tym wieku nie utrzyma w głowie obrazu rosnącej sumy — musi ją widzieć, żeby czekanie miało sens."),

 ("U", 2): dict(
  nr="U1-02", tytul="Kto nam pomaga",
  podtytul="Funkcje instytucji społecznych w codziennym życiu dziecka",
  sfera="I OBSZAR SPOŁECZNY · Instytucje (ICF d910 · PP 1.18)",
  czas="30 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko wyjaśni, do której instytucji zwrócić się w 5 opisanych sytuacjach, i uzasadni wybór, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Dobiera instytucję do potrzeby i uzasadnia wybór."),
    ("M","5 sytuacji; 4 z 5 prób."),
    ("A","Karty instytucji i scenki „mam kłopot — gdzie idę?”."),
    ("R","Orientacja w instytucjach daje dziecku poczucie, że świat da się ogarnąć."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty sytuacji · rejestr trafnych dopasowań i uzasadnień.",
  pomoce=["karty instytucji: przedszkole, przychodnia, poczta, straż, biblioteka","karty sytuacji problemowych","rekwizyty do scenek","mapa okolicy","fotografie budynków z okolicy"],
  metody=["dopasowywanie karty do sytuacji","scenki z podziałem na role","spacer z rozpoznawaniem budynków","rozmowa kierowana"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i obywatelskie",
  przebieg=[
    ("N — rozkłada karty instytucji i pyta, kto tam pracuje.","D — nazywa osoby i czynności."),
    ("N — czyta sytuację: „boli mnie ucho”.","D — wskazuje kartę przychodni."),
    ("N — prosi o uzasadnienie: „dlaczego akurat tam?”.","D — tłumaczy, po co się tam idzie."),
    ("N — rozdaje role do scenki w wybranej instytucji.","D — odgrywa rozmowę z pracownikiem."),
    ("N — pokazuje zdjęcia budynków z okolicy.","D — rozpoznaje instytucję i mówi, co się w niej załatwia.")],
  mod2=["trzy karty do wyboru zamiast pięciu","sytuacje z bliskiego doświadczenia dziecka","podpowiedź: „kto nosi biały fartuch?”"],
  mod3=["dwie karty do wyboru","instytucje znane osobiście: przedszkole i sklep","pokaz zdjęcia z nazwą","dopasowanie przez wskazanie, bez mówienia"],
  mod1=["pięć sytuacji z uzasadnieniem","opowiedzenie o instytucji, w której było się z rodzicem","wymyślenie sytuacji dla kolegi"],
  wskazowka="Zaczynaj od instytucji, w których dziecko naprawdę było. Poczta i straż są abstrakcją, dopóki dziecko nie zobaczy budynku na spacerze."),

 ("U", 3): dict(
  nr="U1-03", tytul="Kącik naszego regionu",
  podtytul="Dziedzictwo kulturowe okolicy w rzeczach, które można dotknąć",
  sfera="I OBSZAR SPOŁECZNY · Dziedzictwo regionu (ICF d910 · PP 1.20)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu przez 6 tygodni",
  ter="Dziecko przygotuje kącik regionu z 4 elementami i oprowadzi po nim kolegę, tłumacząc, czym jest każdy, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Kompletuje elementy dziedzictwa regionu i opowiada o nich innym."),
    ("M","4 elementy; 4 z 5 oprowadzeń."),
    ("A","Stały kącik w sali, uzupełniany co tydzień o nowy eksponat."),
    ("R","Tożsamość lokalna buduje się przez rzeczy, nie przez definicje."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kącik regionu · nagranie oprowadzania · liczba nazwanych elementów.",
  pomoce=["herb miasta","fotografie znanych budowli","element stroju lub tkaniny regionalnej","lokalna legenda w wersji obrazkowej","pudełko na eksponaty przynoszone z domu"],
  metody=["kącik tematyczny uzupełniany etapami","opowiadanie legendy","oprowadzanie kolegi jako sprawdzian","przynoszenie eksponatów z domu"],
  rodzaj="Zajęcia wspierające tożsamość regionalną",
  przebieg=[
    ("N — otwiera pusty kącik i pokazuje herb miasta.","D — ogląda herb, nazywa kolory i kształty."),
    ("N — opowiada legendę związaną z okolicą.","D — wybiera scenę, którą chce narysować do kącika."),
    ("N — prosi o przyniesienie z domu czegoś „z naszych stron”.","D — przynosi przedmiot i opowiada, skąd go ma."),
    ("N — pomaga podpisać eksponaty.","D — układa je w kąciku i wymyśla podpis."),
    ("N — zaprasza kolegę z innej grupy.","D — oprowadza go, tłumacząc każdy element.")],
  mod2=["dwa elementy zamiast czterech","podpisy przygotowane wcześniej","oprowadzanie w parze z kolegą"],
  mod3=["jeden element wybrany razem z dorosłym","opowiedzenie jednego zdania o eksponacie","oprowadzanie dorosłego zamiast dziecka","zdjęcie zamiast przedmiotu"],
  mod1=["cztery elementy z samodzielnymi podpisami","opowiedzenie legendy własnymi słowami","zaprojektowanie plakatu zapraszającego do kącika"],
  wskazowka="Eksponat przyniesiony z domu działa dziesięć razy mocniej niż zdjęcie z internetu — bo dziecko opowiada wtedy nie o regionie, tylko o swojej rodzinie."),

 ("U", 4): dict(
  nr="U1-04", tytul="Zrobimy to dla innych",
  podtytul="Zaplanowane działanie grupy na rzecz kogoś spoza niej",
  sfera="I OBSZAR SPOŁECZNY · Działanie na rzecz innych (ICF d740 · PP DE-P.3)",
  czas="40 min (projekt wieloetapowy)", forma="cała grupa", cykl="raz w trakcie edukacji przedszkolnej",
  ter="Dziecko zaplanuje z grupą działanie dla młodszych dzieci lub osób starszych, przyjmie w nim zadanie i opowie, co się udało — raz w roku, z dokumentacją.",
  ter_smart=[
    ("S","Uczestniczy w planowaniu, wykonuje swoją część i podsumowuje efekt."),
    ("M","Pełny cykl: plan, wykonanie, podsumowanie."),
    ("A","Projekt rozpisany na karcie z podziałem zadań i terminami."),
    ("R","Sprawczość rośnie, gdy dziecko widzi skutek swojego działania u kogoś innego."),
    ("T","Raz w roku szkolnym, z dokumentacją fotograficzną."),
  ],
  ter_kryt="Karta projektu · podział zadań · zdjęcia · zapis podsumowania.",
  pomoce=["duża karta projektu","zdjęcia adresatów działania","materiały zależne od pomysłu","aparat do dokumentacji","tablica z zadaniami i imionami"],
  metody=["burza pomysłów","podział zadań z imionami","praca etapami z powrotami do planu","podsumowanie po dostarczeniu efektu"],
  rodzaj="Projekt społeczny",
  przebieg=[
    ("N — pyta: „komu moglibyśmy sprawić radość?”.","D — zgłasza pomysły, grupa wybiera adresata."),
    ("N — rozpisuje plan na karcie: co, kto, kiedy.","D — wybiera swoje zadanie i podpisuje się przy nim."),
    ("N — wspiera w kolejnych dniach pracy.","D — wykonuje swoją część, wraca do planu."),
    ("N — organizuje dostarczenie efektu adresatom.","D — wręcza efekt i obserwuje reakcję."),
    ("N — pokazuje zdjęcia i pyta, co się udało.","D — opowiada o swojej części i o reakcji adresatów.")],
  mod2=["zadanie o jednym kroku","przypomnienie planu przed każdym etapem","praca w parze"],
  mod3=["jedna czynność wykonana z dorosłym","udział tylko w momencie wręczenia","obrazkowy plan z jednym zadaniem","uprzedzenie o wizycie u adresatów"],
  mod1=["prowadzenie planu i pilnowanie terminów","przypominanie kolegom o zadaniach","wystąpienie w imieniu grupy przy wręczeniu"],
  wskazowka="Nie zastępuj dzieci w wykonaniu, nawet gdy efekt wyjdzie krzywy. Wartość tego projektu leży w tym, że dziecko widzi: to ja to zrobiłem i komuś się przydało."),

 ("U", 5): dict(
  nr="U2-05", tytul="W czym jestem dobry",
  podtytul="Odkrywanie zainteresowań i nazywanie własnych mocnych stron",
  sfera="II OBSZAR OSOBISTY · Mocne strony (ICF d177 · PP 2.2)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="1× w tygodniu",
  ter="Dziecko wymieni trzy swoje mocne strony, poda sytuację, w której się przydały, i wskaże, czego chce się nauczyć, w 4 z 5 rozmów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa mocne strony, ilustruje je przykładem i wskazuje kierunek rozwoju."),
    ("M","3 mocne strony z przykładami; 4 z 5 rozmów."),
    ("A","Portfolio dziecka z kartami mocnych stron i zdjęciami z działania."),
    ("R","Realistyczny obraz siebie chroni przed wyuczoną bezradnością."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Portfolio dziecka · karta mocnych stron · zapis rozmowy indywidualnej.",
  pomoce=["karty obrazkowe czynności","lustro","portfolio dziecka","zdjęcia dziecka w działaniu","ściana mocnych stron grupy"],
  metody=["rozmowa indywidualna przy zdjęciach","wybór z kart obrazkowych","ściana mocnych stron uzupełniana przez grupę","dokumentowanie sukcesów w portfolio"],
  rodzaj="Zajęcia wspierające rozwój osobisty i samoocenę",
  przebieg=[
    ("N — rozkłada karty czynności i pyta: „co lubisz robić?”.","D — wybiera karty i układa je przed sobą."),
    ("N — pokazuje zdjęcie dziecka przy tej czynności.","D — opowiada, co wtedy robiło."),
    ("N — pyta: „kiedy ci się to przydało?”.","D — podaje sytuację z życia grupy."),
    ("N — prosi kolegów o dopisanie jednej mocnej strony.","D — słucha i wybiera, którą wpisuje do portfolio."),
    ("N — pyta: „czego chcesz się nauczyć?”.","D — wskazuje jedną rzecz i mówi, jak zacznie.")],
  mod2=["wybór z sześciu kart zamiast wszystkich","przypomnienie sytuacji przez nauczyciela","dwie mocne strony zamiast trzech"],
  mod3=["wybór z dwóch kart","potwierdzenie gestem zamiast wypowiedzią","mocna strona nazwana przez dorosłego do potwierdzenia","zdjęcie zamiast wspomnienia"],
  mod1=["trzy mocne strony z przykładami i planem rozwoju","nazwanie mocnej strony kolegi","porównanie „co umiałem rok temu, a co dziś”"],
  wskazowka="Nie podpowiadaj mocnych stron pod dyktando. Jeśli dziecko mówi „umiem szybko biegać”, to jest dobra odpowiedź — z niej dopiero wyrasta rozmowa o wytrwałości."),

 ("U", 6): dict(
  nr="U3-06", tytul="Czy to możliwe?",
  podtytul="Wyłapywanie informacji, które się wykluczają albo brzmią niewiarygodnie",
  sfera="III OBSZAR JĘZYKOWY · Krytyczny odbiór informacji (ICF d163 · PP 3.6)",
  czas="25 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko porówna dwie sprzeczne relacje o tym samym zdarzeniu i wskaże, czego trzeba, żeby sprawdzić, która jest prawdziwa, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Dostrzega sprzeczność w relacjach i proponuje sposób sprawdzenia."),
    ("M","4 z 5 par relacji."),
    ("A","Zabawa „dzwonek nieprawdy” — dziecko zatrzymuje opowieść, gdy coś się nie zgadza."),
    ("R","Odróżnianie faktu od zmyślenia to podstawa bezpieczeństwa w świecie informacji."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw zdań-pułapek · rejestr trafnych wychwyceń i uzasadnień.",
  pomoce=["dzwonek lub klaskacz","zestaw krótkich opowiadań ze sprzecznością","dwie kukiełki o sprzecznych relacjach","tablica „prawda / sprawdzamy”","lupa detektywa"],
  metody=["opowieść z celową sprzecznością","sygnał dźwiękowy zamiast przerywania","dwie kukiełki mówiące co innego","wspólne planowanie sprawdzenia"],
  rodzaj="Zajęcia wspierające myślenie krytyczne",
  przebieg=[
    ("N — opowiada historię, w której coś nie może być prawdą.","D — dzwoni, gdy usłyszy coś dziwnego."),
    ("N — pyta: „co się tu nie zgadza?”.","D — wskazuje zdanie i tłumaczy dlaczego."),
    ("N — wprowadza dwie kukiełki mówiące co innego.","D — słucha obu wersji."),
    ("N — pyta: „której wierzymy i skąd to wiemy?”.","D — porównuje relacje, wskazuje różnicę."),
    ("N — pyta: „jak to sprawdzić?”.","D — proponuje sposób: zapytać, zobaczyć, policzyć.")],
  mod2=["sprzeczność wyraźna i wskazana pytaniem","jedna para zdań zamiast opowieści","podpowiedź: „czy słoń zmieści się w pudełku?”"],
  mod3=["dwa zdania: jedno prawdziwe, jedno absurdalne","potwierdzenie gestem tak/nie","ilustracja sprzeczności obrazkiem","natychmiastowe wzmocnienie za wychwycenie"],
  mod1=["dwie równie wiarygodne relacje do porównania","zaproponowanie i przeprowadzenie sprawdzenia","wymyślenie własnej historii ze sprzecznością"],
  wskazowka="Zacznij od absurdów, nie od kłamstw. „Kot ugotował obiad” dziecko wyłapie od razu — dopiero potem da się przejść do relacji, które brzmią wiarygodnie, a się wykluczają."),

 ("U", 7): dict(
  nr="U3-07", tytul="Sprawdzam sam",
  podtytul="Porównywanie usłyszanej informacji z własną obserwacją",
  sfera="III OBSZAR JĘZYKOWY · Weryfikacja informacji (ICF d163 · PP 3.7)",
  czas="20 min", forma="mała grupa", cykl="codziennie przez 3 tygodnie",
  ter="Dziecko zaplanuje, jak sprawdzić usłyszaną informację, wykona sprawdzenie i przedstawi wniosek grupie, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Planuje sprawdzenie, wykonuje je i formułuje wniosek."),
    ("M","4 z 5 sprawdzeń."),
    ("A","Codzienny rytuał: jedno zdanie do sprawdzenia rano, wniosek po południu."),
    ("R","Sprawdzanie zamiast wierzenia na słowo buduje samodzielność myślenia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Dziennik obserwacji · karta „powiedziano – sprawdziłem – wniosek”.",
  pomoce=["tablica zdania dnia","karty „sprawdzam wzrokiem / dotykiem / licząc”","termometr okienny","miarka","dziennik obserwacji grupy"],
  metody=["zdanie dnia do zweryfikowania","wybór narzędzia sprawdzenia","sprawdzenie w praktyce","przedstawienie wniosku grupie"],
  rodzaj="Zajęcia wspierające myślenie naukowe",
  przebieg=[
    ("N — zapisuje rano zdanie dnia: „dziś jest cieplej niż wczoraj”.","D — słucha i mówi, czy tak myśli."),
    ("N — pokazuje karty sposobów sprawdzania.","D — wybiera sposób: termometr, dotyk, ubrania kolegów."),
    ("N — towarzyszy przy sprawdzaniu.","D — wykonuje sprawdzenie i zapamiętuje wynik."),
    ("N — pyta: „i co wyszło?”.","D — mówi wynik i porównuje go ze zdaniem dnia."),
    ("N — zapisuje wniosek w dzienniku.","D — przedstawia wniosek grupie jednym zdaniem.")],
  mod2=["sposób sprawdzenia wskazany przez nauczyciela","zdanie o rzeczy widocznej w sali","wniosek w formie tak/nie"],
  mod3=["sprawdzenie razem z dorosłym","zdanie o czymś, co widać natychmiast","potwierdzenie gestem","jeden sposób sprawdzania w cyklu"],
  mod1=["samodzielny wybór sposobu i wykonanie","sprawdzenie zdania o czymś nieoczywistym","zaproponowanie zdania dnia dla grupy"],
  wskazowka="Zdanie dnia musi być sprawdzalne dziś i tutaj. „Jutro spadnie deszcz” nie nadaje się — dziecko potrzebuje domknięcia w tym samym dniu."),

 ("U", 8): dict(
  nr="U3-08", tytul="Co by było, gdyby",
  podtytul="Myślenie hipotetyczne i dzielenie się wyobrażeniami",
  sfera="III OBSZAR JĘZYKOWY · Wyobraźnia i hipotezy (ICF d163 · PP 3.9)",
  czas="20 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko rozwinie pomysł „co by było, gdyby…” w krótką opowieść z konsekwencjami dla bohatera, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Buduje hipotezę i wyprowadza z niej skutki dla bohatera."),
    ("M","Opowieść z co najmniej dwoma skutkami; 4 z 5 prób."),
    ("A","Pudełko pytań „co by było, gdyby” losowanych na dywanie."),
    ("R","Myślenie hipotetyczne poprzedza rozumienie przyczyny i skutku w nauce szkolnej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Pudełko pytań · nagranie wypowiedzi · liczba wyprowadzonych skutków.",
  pomoce=["pudełko z pytaniami obrazkowymi","kukiełka bohatera","karty skutków (dobre / trudne)","dywan opowieści","tablica „a potem…”"],
  metody=["losowanie pytania z pudełka","prowadzenie opowieści kukiełką","łańcuch „a potem…”","dopowiadanie w kręgu"],
  rodzaj="Zajęcia wspierające myślenie twórcze i mowę",
  przebieg=[
    ("N — losuje pytanie: „co by było, gdyby koty mówiły?”.","D — podaje pierwszy pomysł."),
    ("N — pyta: „a co by się przez to zmieniło?”.","D — wymienia jeden skutek."),
    ("N — prowadzi łańcuch „a potem…”.","D — dokłada kolejny skutek do opowieści."),
    ("N — daje kukiełkę bohatera.","D — opowiada, co bohater by wtedy zrobił."),
    ("N — prosi o zakończenie historii.","D — domyka opowieść jednym zdaniem.")],
  mod2=["pytanie z dwoma gotowymi pomysłami do wyboru","jeden skutek zamiast łańcucha","podpowiedź obrazkowa do dokończenia"],
  mod3=["pytanie o rzecz bliską: „co by było, gdyby padał deszcz na spacerze”","dokończenie zdania jednym słowem","opowieść prowadzona przez dorosłego z pauzami","kukiełka jako pośrednik"],
  mod1=["hipoteza rozwinięta w opowieść z dwoma skutkami","wymyślenie własnego pytania dla grupy","porównanie dwóch różnych zakończeń"],
  wskazowka="Nie oceniaj pomysłów jako „niemożliwych”. W tym ćwiczeniu wartość ma sam ruch myśli od założenia do skutku — realizm przyjdzie później."),

 ("U", 9): dict(
  nr="U3-09", tytul="Znaki, które mówią",
  podtytul="Odczytywanie symboli i tworzenie własnych znaków dla grupy",
  sfera="III OBSZAR JĘZYKOWY · Symbole i znaki (ICF d325 · PP 3.13)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko zaprojektuje zestaw znaków dla kącika i wyjaśni grupie, co każdy oznacza, tak by inni z nich korzystali, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odczytuje znane znaki i projektuje własne, czytelne dla innych."),
    ("M","Zestaw min. 3 znaków używanych przez grupę; 4 z 5 prób."),
    ("A","Znaki wieszane w kącikach i realnie stosowane w sali."),
    ("R","Symbol to pierwszy krok do rozumienia, że znak zastępuje treść — jak litera."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Tablica znaków grupy · sprawdzenie, czy inne dzieci znak odczytują.",
  pomoce=["zdjęcia znaków z otoczenia","kartoniki i mazaki","ramki na znaki w kącikach","znaki drogowe zabawkowe","aparat do zdjęć znaków na spacerze"],
  metody=["spacer po znaki","odczytywanie znaczeń","projektowanie własnego znaku","test czytelności na innych dzieciach"],
  rodzaj="Zajęcia wspierające kompetencje komunikacyjne",
  przebieg=[
    ("N — pokazuje zdjęcia znaków: wyjście, zakaz, toaleta.","D — mówi, co każdy oznacza."),
    ("N — pyta: „po czym poznajesz, że to zakaz?”.","D — wskazuje kolor i przekreślenie."),
    ("N — proponuje zasadę do oznaczenia: „tu mówimy cicho”.","D — projektuje znak na kartoniku."),
    ("N — wiesza znak w kąciku.","D — tłumaczy grupie, co znak oznacza."),
    ("N — sprawdza po kilku dniach, czy znak działa.","D — obserwuje, czy inni go stosują, i poprawia go w razie potrzeby.")],
  mod2=["projekt znaku według wzoru kolorystycznego","jedna zasada do oznaczenia","wyjaśnienie znaku w parze"],
  mod3=["wybór gotowego znaku spośród trzech","znak w postaci zdjęcia zamiast rysunku","umieszczenie znaku razem z dorosłym","znak dla własnej półki"],
  mod1=["zestaw trzech spójnych znaków dla kącika","wyjaśnienie zasad projektowania młodszym","poprawienie znaku, którego inni nie rozumieli"],
  wskazowka="Sprawdzian czytelności jest tu najważniejszy: znak, którego nikt poza autorem nie rozumie, nie spełnia swojej funkcji — i to odkrycie dziecko musi zrobić samo."),

 ("U", 10): dict(
  nr="U3-10", tytul="English corner — nasze przedmioty",
  podtytul="Nazywanie obiektów z najbliższego otoczenia w języku obcym",
  sfera="III OBSZAR JĘZYKOWY · Język obcy — słownictwo (ICF d330 · PP 3.18)",
  czas="20 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko nazwie 10 przedmiotów z sali w języku obcym i użyje ich w prostym zwrocie, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa przedmioty w języku obcym i osadza je w zwrocie."),
    ("M","10 przedmiotów; 4 z 5 prób."),
    ("A","Naklejki z nazwami na przedmiotach w sali, powtarzane w rutynie dnia."),
    ("R","Osłuchanie w naturalnym kontekście daje trwalsze efekty niż nauka listy słów."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty obrazkowe · rejestr poprawnych nazw · nagranie.",
  pomoce=["naklejki z nazwami na przedmiotach","karty obrazkowe","pacynka mówiąca tylko po angielsku","worek niespodzianka","piosenka z nazwami przedmiotów"],
  metody=["etykietowanie sali","pacynka jako rozmówca obcojęzyczny","worek niespodzianka","powtarzanie w rutynie dnia"],
  rodzaj="Zajęcia wspierające naukę języka obcego",
  przebieg=[
    ("N — wprowadza pacynkę, która mówi tylko po angielsku.","D — wita się z pacynką."),
    ("N — pokazuje przedmiot i nazywa go.","D — powtarza nazwę i dotyka przedmiotu."),
    ("N — chowa przedmioty w worku.","D — losuje przedmiot i nazywa go."),
    ("N — prosi o zwrot: „this is a…”.","D — buduje zwrot z wylosowanym przedmiotem."),
    ("N — prowadzi piosenkę z nazwami.","D — śpiewa i wskazuje przedmioty w sali.")],
  mod2=["6 przedmiotów zamiast 10","wskazanie zamiast nazwania przy trudnych słowach","nazwa podana chórem przed indywidualną"],
  mod3=["3 przedmioty codziennego użytku","wskazanie po usłyszeniu nazwy","powtórzenie za nauczycielem","gest zamiast słowa"],
  mod1=["10 przedmiotów w zwrotach","zadanie pytania pacynce","nauczenie młodszego kolegi trzech nazw"],
  wskazowka="Naklejki na przedmiotach pracują między zajęciami. Dziecko widzi słowo sto razy dziennie i nie musi go „uczyć się” osobno."),

 ("U", 11): dict(
  nr="U3-11", tytul="Hello, how are you?",
  podtytul="Udział w prostej sytuacji komunikacyjnej w języku obcym",
  sfera="III OBSZAR JĘZYKOWY · Język obcy — dialog (ICF d310 · PP 3.20)",
  czas="15 min", forma="pary", cykl="codziennie w rytuale powitania",
  ter="Dziecko poprowadzi krótki dialog powitalny z kolegą, zadając i odpowiadając na dwa pytania, w 4 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Zadaje pytanie i odpowiada na nie w języku obcym."),
    ("M","Dwa pytania w dialogu; 4 z 5 sytuacji."),
    ("A","Rytuał powitania w parach przy wejściu do sali."),
    ("R","Dialog w rutynie dnia utrwala język bez sytuacji egzaminacyjnej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Rytuał powitania · nagranie dialogu · rejestr udanych wymian.",
  pomoce=["karty emocji do odpowiedzi","tablica powitań przy drzwiach","pacynka","mikrofon zabawkowy","piosenka powitalna"],
  metody=["rytuał powitania przy wejściu","dialog w parach","karta emocji jako podpowiedź","modelowanie przez pacynkę"],
  rodzaj="Zajęcia wspierające naukę języka obcego",
  przebieg=[
    ("N — wita dzieci przy drzwiach po angielsku.","D — odpowiada na powitanie."),
    ("N — pokazuje karty emocji jako odpowiedzi.","D — wybiera kartę pasującą do samopoczucia."),
    ("N — modeluje dialog z pacynką.","D — obserwuje wzór wymiany."),
    ("N — dobiera dzieci w pary.","D — wita kolegę i pyta o samopoczucie."),
    ("N — podaje mikrofon chętnym.","D — prowadzi dialog przed grupą.")],
  mod2=["odpowiedź wybierana z karty","jedno pytanie zamiast dwóch","dialog z nauczycielem zamiast z kolegą"],
  mod3=["odpowiedź gestem lub jednym słowem","powitanie machnięciem ręki","udział w powitaniu chóralnym","pacynka odpowiada za dziecko"],
  mod1=["dialog z dwoma pytaniami i rozwiniętą odpowiedzią","powitanie gościa w grupie","nauczenie młodszego zwrotu powitalnego"],
  wskazowka="Powitanie przy drzwiach to najlepszy moment — dziecko używa języka w prawdziwej sytuacji, a nie w ćwiczeniu, i nikt nie ocenia wymowy."),

 ("U", 12): dict(
  nr="U3-12", tytul="Śpiewamy po angielsku",
  podtytul="Wierszyki i piosenki w języku obcym — rytm, wymowa, pamięć",
  sfera="III OBSZAR JĘZYKOWY · Język obcy — rytm i pamięć (ICF d330 · PP 3.21)",
  czas="15 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko zaśpiewa piosenkę w języku obcym z pamięci i powtórzy wierszyk, zachowując rytm i wymowę, w 4 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odtwarza z pamięci piosenkę i wierszyk w języku obcym."),
    ("M","Cała zwrotka i wierszyk; 4 z 5 zajęć."),
    ("A","Stały repertuar grupy z gestami do każdej piosenki."),
    ("R","Rytm i melodia niosą wymowę lepiej niż powtarzanie pojedynczych słów."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Repertuar grupy · nagranie audio · rejestr udziału.",
  pomoce=["nagrania piosenek","karty gestów do zwrotek","instrumenty perkusyjne","plakat z repertuarem","mikrofon zabawkowy"],
  metody=["gesty przypisane do słów","śpiewanie z podziałem na role","akompaniament perkusyjny","stały repertuar z powrotami"],
  rodzaj="Zajęcia wspierające naukę języka obcego i rozwój muzyczny",
  przebieg=[
    ("N — puszcza znaną piosenkę i pokazuje gesty.","D — włącza się gestami."),
    ("N — śpiewa zwrotkę, zatrzymując się przed rymem.","D — dopowiada brakujące słowo."),
    ("N — rozdaje instrumenty perkusyjne.","D — gra rytm w refrenie."),
    ("N — dzieli grupę na dwie części.","D — śpiewa swoją część naprzemiennie z drugą grupą."),
    ("N — podaje mikrofon.","D — śpiewa zwrotkę z pamięci.")],
  mod2=["śpiewanie refrenu zamiast zwrotki","gesty jako stałe wsparcie","śpiewanie w parze"],
  mod3=["udział samym gestem","gra na instrumencie zamiast śpiewu","obecność w kręgu bez wymogu włączenia","jedna linijka do powtórzenia"],
  mod1=["cała zwrotka z pamięci przed grupą","nauczenie gestów młodszym","wymyślenie gestu do nowego słowa"],
  wskazowka="Gest przypisany do słowa jest tu narzędziem pamięci, nie ozdobą. Dziecko, które zapomni słowo, odtworzy je z ruchu ręki."),
}
