# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar V (dbanie o siebie), wersja C (6 lat)."""

KONSPEKTY_6_D5 = {
 ("C", 21): dict(
  nr="C5-21", tytul="Gotowi w pięć minut",
  podtytul="Precyzyjne czynności samoobsługowe: guziki, suwaki, sznurowadła",
  sfera="V DBANIE O SIEBIE · Samoobsługa (ICF d540 · PP 9.7)",
  czas="10 min (szatnia)", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko zapnie samodzielnie suwak i wszystkie guziki, prosząc o pomoc wyłącznie przy sznurowadłach, w 3 z 5 wyjść, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wykonuje wszystkie zapięcia poza sznurowadłami samodzielnie."),
    ("M","Suwak i guziki bez pomocy; 3 z 5 wyjść."),
    ("A","Trening zapięć na tablicy; stały porządek ubierania."),
    ("R","Sprawna samoobsługa uwalnia czas i buduje niezależność ucznia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta samoobsługi · pomiar czasu w szatni.",
  pomoce=["tablice manipulacyjne","stoper i tabela czasów","lustro w szatni","instrukcja wiązania w obrazkach","dyplomy samodzielności"],
  metody=["trening zapięć poza sytuacją pośpiechu","pomiar czasu jako gra z samym sobą","stały porządek ubierania","pomoc wyłącznie na wyraźną prośbę"],
  rodzaj="Kształtowanie samodzielności / przygotowanie do szkoły",
  przebieg=[
    ("N — przypomina kolejność ubierania.","D — rozkłada ubranie w kolejności."),
    ("N — uruchamia stoper: „sprawdzamy swój rekord”.","D — ubiera się w swoim tempie."),
    ("N — pomaga tylko na wyraźną prośbę.","D — zapina guziki i suwak samodzielnie."),
    ("N — wskazuje instrukcję wiązania.","D — próbuje zawiązać sznurowadła według instrukcji."),
    ("N — zapisuje czas w tabeli.","D — porównuje ze swoim poprzednim wynikiem.")],
  mod2=["pomoc przy sznurowadłach i połączeniu suwaka","bez pomiaru czasu","ubranie bez drobnych guzików"],
  mod3=["zapinanie rzepów i dużych guzików","rozpoczęcie ruchu przez dorosłego","ubranie uproszczone","praca nad sprawnością manualną"],
  mod1=["pełne ubranie ze sznurowadłami w czasie grupy","radzenie sobie z nowym zapięciem","pomoc młodszemu dziecku","przygotowanie ubrania na następny dzień"],
  wskazowka="Porównuj czas dziecka z jego własnym wynikiem, nigdy z innymi — rekord pobity samemu motywuje, przegrana z kolegą zniechęca na tygodnie."),

 ("C", 22): dict(
  nr="C5-22", tytul="Sam nakładam, sam sprzątam",
  podtytul="Spożywanie posiłków sztućcami i samodzielne nakładanie porcji",
  sfera="V DBANIE O SIEBIE · Posiłki (ICF d550 · PP 9.7·WSR)",
  czas="posiłek", forma="stolik (4–6 dzieci)", cykl="codziennie",
  ter="Dziecko nałoży sobie porcję samodzielnie i zje posiłek z użyciem noża i widelca, w 3 z 5 posiłków, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nakłada porcję i posługuje się pełnym zestawem sztućców."),
    ("M","Samodzielne nałożenie · nóż i widelec; 3 z 5 posiłków."),
    ("A","Naczynia serwisowe na stole; łyżki serwujące dopasowane do dłoni."),
    ("R","Samodzielność przy posiłku to codzienna kompetencja ucznia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja posiłku · karta samodzielności.",
  pomoce=["naczynia serwisowe i łyżki do nakładania","noże i widelce dziecięce","podkładki ze wzorem nakrycia","dzbanek z wodą","karta dyżurnego stolika"],
  metody=["serwowanie rodzinne (półmiski na stole)","nakładanie porcji według własnej oceny","nóż wprowadzany na miękkich produktach","dyżurny stolika odpowiedzialny za nakrycie"],
  rodzaj="Kształtowanie samodzielności / edukacja zdrowotna",
  przebieg=[
    ("N — stawia półmiski na środku stołu.","D — nakłada sobie porcję łyżką serwującą."),
    ("N — pokazuje trzymanie noża i widelca.","D — kroi miękki produkt nożem, trzymając widelec."),
    ("N — pyta o wielkość porcji: „czy dasz radę zjeść tyle?”.","D — ocenia swoją porcję i ewentualnie dokłada."),
    ("N — wskazuje dzbanek z wodą.","D — nalewa sobie wodę, nie rozlewając."),
    ("N — przypomina o uprzątnięciu miejsca.","D — sprząta naczynia i wyciera swoje miejsce.")],
  mod2=["nakładanie z pomocą przy trzymaniu łyżki serwującej","widelec i łyżka, bez noża","porcja odmierzona przez dorosłego"],
  mod3=["porcja nałożona przez dorosłego","sztućce dostosowane","cel: samodzielne zjedzenie posiłku","konsultacja przy trudnościach motorycznych"],
  mod1=["planowanie wielkości porcji i pełna obsługa stolika","nakrycie stołu dla wszystkich","poproszenie o dokładkę pełnym zdaniem","pomoc młodszemu przy nakładaniu"],
  wskazowka="Półmisek na stole zamiast talerza nałożonego w kuchni — to jedna zmiana organizacyjna, która uczy oceny porcji, planowania i samodzielności naraz."),

 ("C", 23): dict(
  nr="C5-23", tytul="Zdrowie na talerzu",
  podtytul="Samodzielna higiena z własnej inicjatywy i zasady zdrowego stylu życia",
  sfera="V DBANIE O SIEBIE · Zdrowy styl życia (ICF d510–d520 · PP 9.7·9.8)",
  czas="25 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko wykona czynności higieniczne z własnej inicjatywy w sytuacjach rutynowych, w 3 z 5 dni, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Myje ręce i dba o higienę bez przypominania."),
    ("M","Sytuacje rutynowe; 3 z 5 dni."),
    ("A","Rutyny oznaczone piktogramami; wiedza o powodach wyjaśniona."),
    ("R","Nawyki zdrowotne kształtowane teraz zostają na całe życie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Lista kontrolna higieny · rozmowa o zdrowiu.",
  pomoce=["piramida zdrowego żywienia","piktogramy rutyn higienicznych","produkty do sortowania: zdrowe/rzadziej","plakat o śnie i ruchu","karta zdrowych nawyków tygodnia"],
  metody=["wyjaśnienie powodu, nie tylko nakazu","sortowanie produktów według piramidy","dziecko tłumaczy zasady innym","karta nawyków wypełniana samodzielnie"],
  rodzaj="Edukacja zdrowotna / kształtowanie samodzielności",
  przebieg=[
    ("N — pokazuje piramidę żywienia.","D — sortuje produkty na poziomy piramidy."),
    ("N — pyta: „dlaczego myjemy ręce przed jedzeniem?”.","D — wyjaśnia własnymi słowami powód."),
    ("N — omawia znaczenie snu i ruchu.","D — mówi, ile godzin śpi i jak się rusza."),
    ("N — rozdaje karty zdrowych nawyków.","D — zaznacza nawyki, które już ma."),
    ("N — prosi o wyjaśnienie zasad młodszej grupie.","D — tłumaczy młodszym dzieciom zasadę higieny.")],
  mod2=["sortowanie 6 produktów","wyjaśnienie z podpowiedzią","karta z dwoma nawykami"],
  mod3=["wykonanie czynności higienicznych po przypomnieniu","rozpoznanie zdrowego produktu spośród dwóch","piktogram przy każdej rutynie","wsparcie w rozumieniu pojęć"],
  mod1=["higiena z własnej inicjatywy we wszystkich sytuacjach","wyjaśnienie trzech zasad zdrowego stylu życia","zaplanowanie zdrowego posiłku","przygotowanie plakatu o zdrowiu dla grupy"],
  wskazowka="Poproś dziecko, by wytłumaczyło zasadę młodszym — nic nie utrwala wiedzy tak jak konieczność wyjaśnienia jej komuś innemu własnymi słowami."),

 ("C", 24): dict(
  nr="C5-24", tytul="Bezpieczna droga",
  podtytul="Zasady bezpieczeństwa na drodze i w środkach komunikacji",
  sfera="V DBANIE O SIEBIE · Bezpieczeństwo w ruchu (ICF d571 · PP 1.6·9.11)",
  czas="30 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko wymieni trzy zasady bezpiecznego przechodzenia przez jezdnię i zastosuje je pod nadzorem, w 3 z 5 wyjść, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa zasady i stosuje je podczas przechodzenia przez jezdnię."),
    ("M","3 zasady · zastosowanie w praktyce; 3 z 5 wyjść."),
    ("A","Miasteczko ruchu w sali; ćwiczenie przed wyjściem w teren."),
    ("R","Bezpieczeństwo w ruchu drogowym to warunek samodzielnej drogi do szkoły."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta wyjść poza teren · obserwacja zachowania na drodze.",
  pomoce=["miasteczko ruchu drogowego (taśma, znaki, przejście)","sygnalizator wykonany przez dzieci","kamizelki odblaskowe","znaki drogowe do rozpoznawania","scenki komunikacji miejskiej"],
  metody=["symulacja w sali przed sytuacją realną","zasada zatrzymaj–popatrz–posłuchaj","rozpoznawanie znaków drogowych","ćwiczenie zachowania w autobusie"],
  rodzaj="Edukacja komunikacyjna / bezpieczeństwo",
  przebieg=[
    ("N — buduje z dziećmi miasteczko ruchu w sali.","D — pomaga rozłożyć przejście i znaki."),
    ("N — uczy zasady: zatrzymaj – popatrz – posłuchaj.","D — powtarza zasadę i ćwiczy ją na przejściu."),
    ("N — pokazuje znaki drogowe do rozpoznania.","D — nazywa znaki i mówi, co oznaczają."),
    ("N — odgrywa scenkę w autobusie.","D — ćwiczy zachowanie: ustępowanie miejsca, trzymanie się."),
    ("N — wychodzi z grupą na prawdziwe przejście.","D — stosuje zasady pod nadzorem dorosłego.")],
  mod2=["dwie zasady zamiast trzech","ćwiczenie wyłącznie w miasteczku","przypomnienie przy każdym przejściu"],
  mod3=["przechodzenie za rękę dorosłego","zasada zatrzymania na krawężniku","ćwiczenia wyłącznie w sali","stałe towarzyszenie dorosłego"],
  mod1=["stosowanie zasad i przypominanie o nich młodszym","rozpoznanie sytuacji niebezpiecznej na drodze","opisanie swojej drogi do przedszkola","zaplanowanie bezpiecznej trasy na mapie"],
  wskazowka="Zbuduj miasteczko ruchu z dziećmi, nie dla dzieci — kładąc taśmę przejścia, dziecko zapamiętuje jego układ lepiej niż z dziesięciu pogadanek."),

 ("C", 25): dict(
  nr="C5-25", tytul="Moje granice",
  podtytul="Rozpoznawanie zmęczenia, przeciążenia i sytuacji zagrażających bezpieczeństwu",
  sfera="V DBANIE O SIEBIE · Granice i autonomia (ICF d571 · PP 9.9·9.10)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko zgłosi zmęczenie lub przeciążenie umówionym sygnałem, zanim pojawi się reakcja emocjonalna, w 3 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje sygnały ciała i zgłasza je przed eskalacją."),
    ("M","Zgłoszenie przed reakcją; 3 z 5 sytuacji."),
    ("A","Skala obrazkowa napięcia i umówiony sygnał; kącik regeneracji."),
    ("R","Znajomość własnych granic chroni przed przeciążeniem i przekraczaniem granic przez innych."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Skala obrazkowa · rejestr zgłoszeń dziecka.",
  pomoce=["skala napięcia 1–5 z obrazkami","karta umówionego sygnału","kącik regeneracji","historyjki o granicach (moje ciało, moja przestrzeń)","zdjęcia osób zaufanych"],
  metody=["skala napięcia jako codzienne narzędzie","nauka odmawiania w scenkach","rozróżnienie tajemnicy dobrej i złej","wskazanie osób zaufanych"],
  rodzaj="Zajęcia wspierające samoregulację i bezpieczeństwo osobiste",
  przebieg=[
    ("N — pokazuje skalę napięcia 1–5.","D — zaznacza swój aktualny poziom."),
    ("N — pyta: „po czym poznajesz, że masz już czwórkę?”.","D — nazywa sygnały ciała: gorąco, szybkie serce."),
    ("N — ustala umówiony sygnał zgłoszenia.","D — ćwiczy pokazanie sygnału."),
    ("N — odgrywa scenkę przekroczenia granicy.","D — ćwiczy stanowcze „nie chcę tego”."),
    ("N — omawia, do kogo zwrócić się o pomoc.","D — wskazuje osoby zaufane na zdjęciach.")],
  mod2=["skala trzystopniowa","sygnał zgłoszenia podpowiadany","scenki wyłącznie o zmęczeniu"],
  mod3=["nazwanie stanu przez dorosłego i wskazanie rozwiązania","stałe przerwy regeneracyjne","jeden sygnał: „potrzebuję przerwy”","współpraca z psychologiem"],
  mod1=["rozpoznanie narastającego napięcia i samodzielne zastosowanie strategii","stanowcza odmowa w sytuacji presji rówieśniczej","zgłoszenie dorosłemu sytuacji zagrażającej","zauważenie przeciążenia u kolegi"],
  wskazowka="Ucz odmawiania w scenkach, nie w rozmowie — słowo „nie” wypowiedziane głośno w bezpiecznej sytuacji zostaje w ciele i wraca wtedy, gdy jest naprawdę potrzebne."),
}
