# -*- coding: utf-8 -*-
"""Konspekty do celów uzupełniających — obszary IV (matematyczny)
i V (przyrodniczy) podstawy 2026. Wersja U."""

KONSPEKTY_U_O45 = {
 ("U", 13): dict(
  nr="U4-13", tytul="Detektywi kłopotów",
  podtytul="Opisywanie sytuacji problemowej i szukanie jej przyczyny",
  sfera="IV OBSZAR MATEMATYCZNY · Rozpoznawanie problemu (ICF d175 · PP 4.1)",
  czas="25 min", forma="mała grupa", cykl="2× w tygodniu",
  ter="Dziecko opisze problem, poda dwie możliwe przyczyny i powie, którą uważa za ważniejszą, w 4 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa problem i wskazuje jego prawdopodobne przyczyny."),
    ("M","Dwie przyczyny z wyborem ważniejszej; 4 z 5 sytuacji."),
    ("A","Skrzynka kłopotów grupy — realne sytuacje z sali, nie wymyślone."),
    ("R","Zanim dziecko zacznie rozwiązywać, musi umieć nazwać, co właściwie nie działa."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Skrzynka kłopotów · karta „problem – przyczyny” · zapis wypowiedzi.",
  pomoce=["skrzynka kłopotów grupy","karty sytuacji problemowych ze zdjęciami","lupa detektywa","tablica „dlaczego?”","znaczniki do zaznaczania ważniejszej przyczyny"],
  metody=["realne kłopoty z życia grupy","pytanie „dlaczego?” zadawane trzykrotnie","rysowanie przyczyn na tablicy","wybór przyczyny głównej znacznikiem"],
  rodzaj="Zajęcia wspierające myślenie problemowe",
  przebieg=[
    ("N — wyjmuje kartkę ze skrzynki: „wieża się przewróciła”.","D — ogląda zdjęcie i mówi, co się stało."),
    ("N — pyta: „na czym polega kłopot?”.","D — opisuje problem jednym zdaniem."),
    ("N — pyta „dlaczego?” i zapisuje odpowiedzi.","D — podaje pierwszą przyczynę."),
    ("N — pyta o inną możliwość.","D — podaje drugą przyczynę."),
    ("N — daje znacznik: „która twoim zdaniem ważniejsza?”.","D — zaznacza i uzasadnia wybór.")],
  mod2=["dwie przyczyny do wyboru zamiast wymyślania","zdjęcie sytuacji zamiast opisu","pytanie naprowadzające przy uzasadnieniu"],
  mod3=["jedna przyczyna wskazana z dwóch obrazków","problem pokazany na żywo, nie na zdjęciu","potwierdzenie gestem","kłopot dotyczący samego dziecka"],
  mod1=["dwie przyczyny z uzasadnieniem wyboru","rozpoznanie kłopotu kolegi i nazwanie go","wrzucenie własnej sprawy do skrzynki"],
  wskazowka="Bierz kłopoty prawdziwe — te z dzisiejszego poranka. Wymyślone historyjki dziecko rozwiązuje grzecznie i bez emocji, a przy własnej przewróconej wieży naprawdę myśli."),

 ("U", 14): dict(
  nr="U4-14", tytul="Próba i poprawka",
  podtytul="Stosowanie rozwiązania i ocenianie, czy zadziałało",
  sfera="IV OBSZAR MATEMATYCZNY · Skuteczność rozwiązania (ICF d175 · PP 4.3)",
  czas="30 min", forma="pary", cykl="2× w tygodniu",
  ter="Dziecko zastosuje własne rozwiązanie, oceni jego skuteczność i zaproponuje poprawkę, gdy nie zadziałało, w 4 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wdraża rozwiązanie, ocenia wynik i modyfikuje przy niepowodzeniu."),
    ("M","4 z 5 sytuacji z pełnym cyklem próba–ocena–poprawka."),
    ("A","Karta „problem – próba – wynik” wypełniana po każdym zadaniu."),
    ("R","Poprawianie po nieudanej próbie to najważniejszy nawyk przyszłego ucznia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta „problem – próba – wynik” · rejestr poprawek po niepowodzeniu.",
  pomoce=["zadania konstrukcyjne z jednym utrudnieniem","karta próby z trzema polami","stoper","klocki i taśma","tablica pomysłów pary"],
  metody=["zadanie z celowym utrudnieniem","praca w parach","zapis próby przed wykonaniem","obowiązkowa druga próba"],
  rodzaj="Zajęcia wspierające myślenie problemowe",
  przebieg=[
    ("N — stawia zadanie: „most z klocków, który uniesie autko”.","D — ogląda materiały i zadanie."),
    ("N — prosi o zapisanie pomysłu na karcie.","D — rysuje swój pomysł przed budowaniem."),
    ("N — daje czas na wykonanie.","D — buduje most według pomysłu."),
    ("N — sprawdza autkiem i pyta: „zadziałało?”.","D — ocenia wynik i mówi, co poszło nie tak."),
    ("N — daje drugą szansę.","D — poprawia konstrukcję i sprawdza ponownie.")],
  mod2=["dwa gotowe pomysły do wyboru","podpowiedź przy poprawce","zadanie o jednym kroku"],
  mod3=["rozwiązanie wskazane przez nauczyciela","ocena tak/nie gestem","poprawka wykonana wspólnie","zadanie zakończone sukcesem za pierwszym razem"],
  mod1=["własny pomysł, ocena i dwie różne poprawki","porównanie skuteczności dwóch rozwiązań","doradzenie parze obok"],
  wskazowka="Zadanie musi mieć realne ryzyko niepowodzenia — inaczej nie ma czego oceniać. Most, który zawsze się utrzyma, niczego nie uczy o poprawianiu."),

 ("U", 15): dict(
  nr="U4-15", tytul="Liczmany w akcji",
  podtytul="Dodawanie i odejmowanie na zbiorach zastępczych",
  sfera="IV OBSZAR MATEMATYCZNY · Działania (ICF d172 · PP 4.7)",
  czas="25 min", forma="mała grupa", cykl="3× w tygodniu",
  ter="Dziecko doda i odejmie w zakresie 10, wybierając sposób liczenia i uzasadniając wynik, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wykonuje działania w zakresie 10 i tłumaczy, jak doszło do wyniku."),
    ("M","Zakres 10; 4 z 5 prób."),
    ("A","Trzy zestawy liczmanów do wyboru — dziecko decyduje, czym liczy."),
    ("R","Wybór narzędzia liczenia buduje poczucie sprawstwa w matematyce."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty działań · rejestr wyników i sposobów liczenia.",
  pomoce=["kasztany, nakrętki i klocki jako trzy zestawy liczmanów","karty działań obrazkowych","tacki do rozdzielania","kostka do gry","sklepik z cenami do 10"],
  metody=["wybór własnego liczmanu","działania w kontekście sklepiku","liczenie na palcach jako pełnoprawny sposób","uzasadnianie wyniku"],
  rodzaj="Zajęcia wspierające kompetencje matematyczne",
  przebieg=[
    ("N — rozkłada trzy rodzaje liczmanów.","D — wybiera, czym będzie liczyć."),
    ("N — pokazuje kartę: 4 i 3.","D — odlicza liczmany na tacce."),
    ("N — pyta: „ile razem?”.","D — podaje wynik i pokazuje, jak liczył."),
    ("N — zabiera 2 liczmany.","D — odejmuje i podaje nowy wynik."),
    ("N — otwiera sklepik z cenami.","D — kupuje dwie rzeczy i liczy, ile zapłaci.")],
  mod2=["zakres do 5","liczmany ułożone w rzędzie przez nauczyciela","działanie z obrazkową podpowiedzią"],
  mod3=["dokładanie jednego elementu","liczenie razem z dorosłym","zakres do 3","liczmany duże i kontrastowe"],
  mod1=["zakres do 10 z uzasadnieniem","porównanie dwóch sposobów liczenia","ułożenie działania dla kolegi"],
  wskazowka="Nie zabraniaj liczenia na palcach. To pełnoprawna strategia — porzuca się ją samodzielnie, gdy wynik staje się pamięciowy."),

 ("U", 16): dict(
  nr="U4-16", tytul="Ile nas jest — wykres grupy",
  podtytul="Przedstawianie wartości liczbowych na różne sposoby graficzne",
  sfera="IV OBSZAR MATEMATYCZNY · Reprezentacje liczb (ICF d172 · PP 4.10)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko zrobi wykres słupkowy z wynikiem zliczania w grupie i odczyta z niego, czego jest najwięcej, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Buduje wykres z danych zebranych w grupie i odczytuje z niego wniosek."),
    ("M","Wykres z min. 3 słupkami; 4 z 5 prób."),
    ("A","Cotygodniowe pytanie do grupy i wspólny wykres na tablicy."),
    ("R","Wykres pokazuje liczbę jako wielkość — to podstawa rozumienia danych."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Wykresy grupy · rejestr poprawnych odczytów.",
  pomoce=["tablica z siatką na wykres","kolorowe naklejki lub kwadraty","karty pytań tygodnia","kropkowe karty liczbowe","paski do reprezentacji długością"],
  metody=["pytanie tygodnia zadawane całej grupie","układanie słupków z kwadratów","odczytywanie wykresu na głos","porównywanie długości słupków"],
  rodzaj="Zajęcia wspierające kompetencje matematyczne",
  przebieg=[
    ("N — zadaje pytanie tygodnia: „jaki masz ulubiony owoc?”.","D — odpowiada i bierze kwadrat w kolorze odpowiedzi."),
    ("N — pokazuje siatkę wykresu.","D — przykleja swój kwadrat nad właściwym obrazkiem."),
    ("N — pyta: „który słupek jest najwyższy?”.","D — wskazuje i nazywa odpowiedź."),
    ("N — prosi o przeliczenie słupka.","D — liczy kwadraty i podaje liczbę."),
    ("N — pyta: „co z tego wynika?”.","D — formułuje wniosek: „najwięcej z nas lubi…”.")],
  mod2=["dwie odpowiedzi do wyboru","kwadrat przyklejany z pomocą przy siatce","odczyt „najwięcej” przez wskazanie"],
  mod3=["wybór z dwóch obrazków","przyklejenie kwadratu razem z dorosłym","porównanie „więcej – mniej” bez liczenia","udział w zliczaniu chóralnym"],
  mod1=["wykres z czterema słupkami i pełnym wnioskiem","zaproponowanie pytania tygodnia","porównanie dwóch wykresów z różnych tygodni"],
  wskazowka="Pytanie tygodnia musi dotyczyć samych dzieci. Wykres o ulubionych owocach czytają z zapałem, wykres o czymkolwiek innym — nie."),

 ("U", 17): dict(
  nr="U4-17", tytul="Prowadzę cię słowem",
  podtytul="Kierunki i relacje przestrzenne między obiektami",
  sfera="IV OBSZAR MATEMATYCZNY · Orientacja przestrzenna (ICF d137 · PP 4.11)",
  czas="20 min", forma="pary", cykl="3× w tygodniu",
  ter="Dziecko poprowadzi kolegę po sali samymi wskazówkami kierunkowymi do ukrytego przedmiotu, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Używa określeń kierunkowych tak, by druga osoba trafiła do celu."),
    ("M","Trafienie do celu; 4 z 5 prób."),
    ("A","Zabawa w nawigatora — jedno dziecko prowadzi, drugie idzie."),
    ("R","Precyzja języka przestrzennego przekłada się wprost na czytanie map i geometrię."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zabawa nawigacyjna · rejestr trafień · lista użytych określeń.",
  pomoce=["tabliczki z określeniami: nad, pod, obok, za, przed","ukrywany skarb","opaska na oczy","tor przeszkód","mapa sali"],
  metody=["zabawa w nawigatora","polecenia bez wskazywania ręką","zamiana ról w parze","tor przeszkód z instrukcją słowną"],
  rodzaj="Zajęcia wspierające orientację przestrzenną",
  przebieg=[
    ("N — pokazuje tabliczki z określeniami kierunkowymi.","D — ustawia przedmiot zgodnie z nazwą."),
    ("N — ukrywa skarb i wskazuje nawigatora.","D — zapamiętuje miejsce ukrycia."),
    ("N — przypomina zasadę: „tylko słowami, bez pokazywania”.","D — prowadzi kolegę: „dwa kroki do przodu, teraz obok szafki”."),
    ("N — obserwuje, czy kolega trafia.","D — poprawia wskazówkę, gdy kolega zbłądzi."),
    ("N — zamienia role w parze.","D — idzie według wskazówek kolegi.")],
  mod2=["cztery określenia zamiast wszystkich","dozwolone wskazanie ręką przy jednej wskazówce","krótsza trasa"],
  mod3=["dwa określenia: przód i tył","prowadzenie z dorosłym","cel widoczny z miejsca startu","instrukcja jednokrokowa"],
  mod1=["trasa z czterema wskazówkami bez gestów","narysowanie mapy trasy","poprowadzenie młodszego dziecka"],
  wskazowka="Zakaz pokazywania ręką jest tu całym sensem ćwiczenia — dopiero wtedy dziecko musi sięgnąć po słowo zamiast po gest."),

 ("U", 18): dict(
  nr="U4-18", tytul="Figury wokół nas",
  podtytul="Rozpoznawanie figur płaskich i pierwszych brył",
  sfera="IV OBSZAR MATEMATYCZNY · Figury i bryły (ICF d137 · PP 4.13)",
  czas="25 min", forma="mała grupa", cykl="2× w tygodniu",
  ter="Dziecko nazwie figury płaskie i dwie bryły oraz wskaże różnicę między kwadratem a sześcianem, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa figury i bryły oraz odróżnia płaskie od przestrzennych."),
    ("M","4 figury i 2 bryły; 4 z 5 prób."),
    ("A","Polowanie na figury w sali i pudełko brył do dotykania."),
    ("R","Różnica płaskie–przestrzenne to pierwszy krok do geometrii szkolnej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw figur i brył · karta obserwacji · rejestr poprawnych nazw.",
  pomoce=["zestaw figur płaskich","bryły do dotykania: sześcian, kula, walec","worek dotykowy","ramki do obrysowywania","aparat do zdjęć figur w sali"],
  metody=["polowanie na figury w otoczeniu","rozpoznawanie dotykiem w worku","obrysowywanie ścianek brył","porównanie kwadrat–sześcian"],
  rodzaj="Zajęcia wspierające kompetencje matematyczne",
  przebieg=[
    ("N — rozkłada figury płaskie i nazywa je.","D — powtarza nazwy i sortuje figury."),
    ("N — wysyła na polowanie: „znajdź w sali koło”.","D — znajduje przedmiot i fotografuje go."),
    ("N — podaje worek dotykowy z bryłami.","D — rozpoznaje bryłę dotykiem i nazywa."),
    ("N — kładzie obok kwadrat i sześcian.","D — porównuje je i mówi, czym się różnią."),
    ("N — prosi o obrysowanie ścianki sześcianu.","D — obrysowuje i odkrywa, że powstał kwadrat.")],
  mod2=["trzy figury zamiast czterech","bryły oglądane, nie w worku","porównanie z podpowiedzią: „czy da się to postawić?”"],
  mod3=["dwie figury kontrastowe: koło i kwadrat","dopasowanie do wzoru","nazwa podana przez nauczyciela do powtórzenia","tylko figury płaskie"],
  mod1=["cztery figury, dwie bryły i uzasadniona różnica","znalezienie brył w sali","zbudowanie sześcianu z patyczków"],
  wskazowka="Obrysowanie ścianki sześcianu to moment olśnienia: dziecko widzi na własne oczy, że kwadrat mieszka w sześcianie. Nie zastępuj tego tłumaczeniem."),

 ("U", 19): dict(
  nr="U4-19", tytul="Idziemy na zakupy",
  podtytul="Planowanie i realizacja zakupów w prawdziwym sklepie",
  sfera="IV OBSZAR MATEMATYCZNY · Zakupy (ICF d620 · PP DE-P.4)",
  czas="90 min (wyjście)", forma="mała grupa", cykl="raz w trakcie edukacji przedszkolnej",
  ter="Dziecko ułoży z grupą listę zakupów, odnajdzie produkty, zapłaci i sprawdzi resztę — raz w edukacji przedszkolnej, z dokumentacją.",
  ter_smart=[
    ("S","Planuje listę, odnajduje produkty, dokonuje płatności i sprawdza resztę."),
    ("M","Pełny cykl zakupowy z listy min. 3 produktów."),
    ("A","Prawdziwe wyjście do sklepu z listą obrazkową i przygotowaną kwotą."),
    ("R","Zakupy łączą liczenie, planowanie i kontakt społeczny w jednej sytuacji."),
    ("T","Raz w roku szkolnym, z dokumentacją."),
  ],
  ter_kryt="Lista zakupów · karta rozliczenia · zdjęcia z wyjścia.",
  pomoce=["lista zakupów obrazkowa","portfel z odliczoną kwotą","koszyk","karta rozliczenia","aparat do dokumentacji"],
  metody=["planowanie listy w grupie","wyjście do prawdziwego sklepu","samodzielne odnajdywanie produktów","rozliczenie po powrocie"],
  rodzaj="Projekt matematyczno-społeczny",
  przebieg=[
    ("N — pyta: „co potrzebne na nasze urodziny grupy?”.","D — zgłasza produkt i rysuje go na liście."),
    ("N — pokazuje pieniądze i wyjaśnia kwotę.","D — ogląda monety i wkłada je do portfela."),
    ("N — prowadzi grupę do sklepu.","D — odnajduje produkty z listy i wkłada do koszyka."),
    ("N — towarzyszy przy kasie.","D — podaje pieniądze i odbiera resztę."),
    ("N — po powrocie rozkłada zakupy i resztę.","D — sprawdza, czy kupiono wszystko z listy.")],
  mod2=["lista trzech produktów","kwota odliczona co do złotówki","towarzyszenie dorosłego przy kasie"],
  mod3=["jeden produkt z listy","podanie produktu sprzedawcy z pomocą","przygotowanie do wyjścia obrazkowym planem","krótka wizyta bez kolejki"],
  mod1=["lista pięciu produktów z podziałem na kategorie","sprawdzenie reszty i porównanie z ceną","poinstruowanie młodszego kolegi"],
  wskazowka="Uprzedź sklep telefonicznie. Kasjer, który wie, że dzieci będą liczyć powoli, to różnica między udanym wyjściem a stresem przy kolejce."),

 ("U", 20): dict(
  nr="U5-20", tytul="Atlas naszego ogrodu",
  podtytul="Rozpoznawanie roślin, zwierząt i przyrody nieożywionej z otoczenia",
  sfera="V OBSZAR PRZYRODNICZY · Rozpoznawanie przyrody (ICF d137 · PP 5.1)",
  czas="40 min (spacer badawczy)", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko nazwie 10 elementów przyrody, dzieląc je na ożywione i nieożywione, i uzasadni podział, w 4 z 5 wyjść, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa elementy przyrody i klasyfikuje je jako żywe lub nieżywe."),
    ("M","10 elementów; 4 z 5 wyjść."),
    ("A","Atlas grupy tworzony ze zdjęć z ogrodu przedszkolnego."),
    ("R","Rozpoznawanie własnego otoczenia poprzedza wiedzę o dalekim świecie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Atlas grupy · karta spaceru badawczego · rejestr nazw.",
  pomoce=["aparat lub tablet","lupy","koszyczki na okazy","segregator atlasu","karty „żywe / nieżywe”"],
  metody=["spacer badawczy z lupą","fotografowanie okazów","sortowanie na żywe i nieżywe","budowanie atlasu grupy"],
  rodzaj="Zajęcia przyrodnicze w terenie",
  przebieg=[
    ("N — rozdaje lupy i wyznacza teren badań.","D — szuka okazów w ogrodzie."),
    ("N — nazywa znalezione okazy.","D — powtarza nazwę i fotografuje okaz."),
    ("N — rozkłada karty „żywe / nieżywe”.","D — przyporządkowuje okaz do karty."),
    ("N — pyta: „skąd wiesz, że to żywe?”.","D — uzasadnia: rośnie, oddycha, potrzebuje wody."),
    ("N — wkleja zdjęcia do atlasu.","D — podpisuje kartę atlasu swoim znakiem.")],
  mod2=["6 elementów zamiast 10","podział z podpowiedzią pytaniem","nazwy podane przed spacerem"],
  mod3=["3 elementy z najbliższego otoczenia","wskazanie zamiast nazwania","sortowanie na dwie kupki bez uzasadnienia","spacer po tym samym terenie co poprzednio"],
  mod1=["10 elementów z uzasadnionym podziałem","znalezienie okazu, którego nikt nie zna","opracowanie karty atlasu dla grupy"],
  wskazowka="Wracaj w to samo miejsce co tydzień. Ten sam krzak w kwietniu i w czerwcu to dwa różne obiekty — i to odkrycie jest cenniejsze niż dziesięć nowych nazw."),

 ("U", 21): dict(
  nr="U5-21", tytul="Kalendarz pogody",
  podtytul="Obserwacja zmian w otoczeniu i wyciąganie wniosków",
  sfera="V OBSZAR PRZYRODNICZY · Zjawiska i zmiany (ICF d163 · PP 5.2)",
  czas="15 min", forma="cała grupa", cykl="codziennie",
  ter="Dziecko porówna pogodę z całego tygodnia, wskaże zmianę i powie, co się przez nią zmieniło w zabawach na dworze, w 4 z 5 tygodni, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Zapisuje pogodę codziennie i wnioskuje z zebranych danych."),
    ("M","Porównanie tygodniowe; 4 z 5 tygodni."),
    ("A","Stały kalendarz pogody uzupełniany w rytuale porannym."),
    ("R","Codzienny zapis uczy, że wniosek bierze się z serii obserwacji, nie z jednej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kalendarz pogody · zapis wniosków tygodniowych.",
  pomoce=["kalendarz pogody z siatką","piktogramy pogodowe","termometr okienny","tablica „co się zmieniło”","zdjęcia ogrodu z różnych dni"],
  metody=["codzienny rytuał poranny","piktogramy zamiast pisania","tygodniowe podsumowanie","łączenie pogody z zabawami"],
  rodzaj="Zajęcia przyrodnicze",
  przebieg=[
    ("N — otwiera kalendarz i pyta o dzisiejszą pogodę.","D — patrzy przez okno i opisuje ją."),
    ("N — podaje piktogramy do wyboru.","D — wybiera pasujący i przypina w kalendarzu."),
    ("N — pokazuje termometr.","D — mówi, czy jest ciepło czy zimno."),
    ("N — w piątek pokazuje cały tydzień.","D — wskazuje dzień najcieplejszy i najzimniejszy."),
    ("N — pyta: „co się przez to zmieniło na dworze?”.","D — mówi, w co dało się bawić, a w co nie.")],
  mod2=["trzy piktogramy do wyboru","porównanie dwóch dni zamiast tygodnia","pytanie naprowadzające o zabawy"],
  mod3=["dwa piktogramy: słońce i deszcz","przypięcie piktogramu z pomocą","opis pogody jednym słowem","udział w rytuale bez wypowiedzi"],
  mod1=["porównanie tygodnia z wnioskiem i przewidywaniem","prowadzenie rytuału pogodowego","zestawienie dwóch tygodni"],
  wskazowka="Nie pomijaj dni pochmurnych i nudnych — właśnie one budują serię, z której da się cokolwiek wywnioskować."),

 ("U", 22): dict(
  nr="U5-22", tytul="Dziennik małego badacza",
  podtytul="Dokumentowanie obserwacji przyrodniczych rysunkiem",
  sfera="V OBSZAR PRZYRODNICZY · Dokumentowanie (ICF d163 · PP 5.4)",
  czas="20 min", forma="mała grupa", cykl="2× w tygodniu przez 5 tygodni",
  ter="Dziecko poprowadzi serię 5 rysunków tego samego obiektu w czasie i opowie, co się zmieniło, w 4 z 5 serii, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rysuje obserwowany obiekt w kolejnych momentach i opisuje zmianę."),
    ("M","Seria 5 rysunków z datami; 4 z 5 serii."),
    ("A","Dziennik obserwacji z ramkami i miejscem na datę."),
    ("R","Rysunek z datą to pierwsza forma zapisu naukowego dostępna przedszkolakowi."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Dziennik obserwacji · seria rysunków z datami · zapis wypowiedzi.",
  pomoce=["dziennik z ramkami i polem na datę","kredki i lupa","doniczka z fasolą","stempel z datą","sznurek do porównania wysokości"],
  metody=["obserwacja tego samego obiektu w czasie","rysunek w ramce","stemplowanie daty","porównanie pierwszego i ostatniego rysunku"],
  rodzaj="Zajęcia przyrodnicze i badawcze",
  przebieg=[
    ("N — daje dziennik i wskazuje obiekt obserwacji.","D — ogląda fasolę przez lupę."),
    ("N — pokazuje ramkę na dzisiejszy rysunek.","D — rysuje to, co widzi dziś."),
    ("N — podaje stempel z datą.","D — stempluje datę pod rysunkiem."),
    ("N — po kilku dniach prosi o kolejny rysunek.","D — rysuje i porównuje z poprzednim."),
    ("N — rozkłada całą serię.","D — opowiada, co się zmieniło od pierwszego rysunku.")],
  mod2=["trzy rysunki zamiast pięciu","ramka z zaznaczoną linią gruntu","porównanie tylko pierwszego z ostatnim"],
  mod3=["doklejenie gotowego obrazka do karty","rysunek jednego elementu: listka","obserwacja prowadzona wspólnie","seria dwóch rysunków"],
  mod1=["seria pięciu rysunków z pomiarem sznurkiem","opis zmiany z podaniem przyczyny","przedstawienie serii grupie"],
  wskazowka="Fasola w słoiku z watą jest niezastąpiona: korzeń widać, wzrost jest szybki, a rozczarowania rzadkie."),

 ("U", 23): dict(
  nr="U5-23", tytul="Mapa mojej drogi",
  podtytul="Odnajdywanie znanych miejsc na planie, mapie i globusie",
  sfera="V OBSZAR PRZYRODNICZY · Plan i mapa (ICF d137 · PP 5.6)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko narysuje plan drogi z sali do ogrodu i wskaże na mapie miejsce, w którym mieszka, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Tworzy prosty plan trasy i lokalizuje znane miejsca na mapie."),
    ("M","Plan trasy plus lokalizacja domu; 4 z 5 prób."),
    ("A","Plan sali w skali dywanowej, po którym da się chodzić."),
    ("R","Przejście od przestrzeni do jej obrazu z góry to trudny, ale kluczowy krok."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Plan sali i przedszkola · rysunek trasy · wskazania na mapie.",
  pomoce=["plan sali w dużym formacie","plan przedszkola","mapa miasta","globus","pionki do zaznaczania miejsc"],
  metody=["chodzenie po planie rozłożonym na podłodze","zaznaczanie pionkiem swojego miejsca","rysowanie trasy krok po kroku","odnajdywanie domu na mapie"],
  rodzaj="Zajęcia przyrodnicze i przestrzenne",
  przebieg=[
    ("N — rozkłada duży plan sali na podłodze.","D — staje na planie w miejscu odpowiadającym swojemu stolikowi."),
    ("N — pyta: „gdzie tu są drzwi?”.","D — wskazuje na planie i sprawdza w rzeczywistości."),
    ("N — prosi o narysowanie drogi do ogrodu.","D — rysuje trasę z zaznaczonymi zakrętami."),
    ("N — rozkłada mapę miasta.","D — wskazuje okolicę, w której mieszka, i stawia pionek."),
    ("N — pokazuje globus.","D — odnajduje Polskę i pokazuje ją grupie.")],
  mod2=["plan sali zamiast całego przedszkola","trasa z dwoma punktami","dom wskazany z podpowiedzią"],
  mod3=["plan z fotografiami zamiast symboli","wskazanie własnego miejsca przy stole","trasa pokonana fizycznie przed rysowaniem","globus jako kula do obejrzenia"],
  mod1=["plan trasy z legendą","wskazanie domu i drogi do przedszkola","pokazanie na globusie kraju z wakacji"],
  wskazowka="Zacznij od planu, po którym da się chodzić. Widok z góry jest dla sześciolatka abstrakcją, dopóki nie stanie stopą w miejscu, które ten plan oznacza."),

 ("U", 24): dict(
  nr="U5-24", tytul="Ziemia i Słońce",
  podtytul="Ziemia jako kula krążąca wokół Słońca — skąd bierze się dzień i noc",
  sfera="V OBSZAR PRZYRODNICZY · Ziemia w kosmosie (ICF d137 · PP 5.7)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko pokaże ruch Ziemi wokół Słońca i wyjaśni, skąd bierze się dzień i noc, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Modeluje ruch Ziemi i wiąże go z następstwem dnia i nocy."),
    ("M","Pokaz ruchu z wyjaśnieniem; 4 z 5 prób."),
    ("A","Model z latarką i globusem w zaciemnionej sali."),
    ("R","Doświadczenie z latarką daje wyjaśnienie, którego nie zastąpi obrazek."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Model Układu Słonecznego · zapis wyjaśnienia dziecka.",
  pomoce=["globus","latarka","piłki różnej wielkości","naklejka „tu jesteśmy”","zaciemnienie okien"],
  metody=["doświadczenie z latarką w ciemności","dziecko jako Ziemia obracająca się wokół latarki","naklejka lokalizująca","powtarzalny pokaz"],
  rodzaj="Zajęcia przyrodnicze",
  przebieg=[
    ("N — pokazuje globus i pyta, jaki ma kształt.","D — mówi, że to kula, i obraca globus."),
    ("N — nakleja znacznik „tu jesteśmy”.","D — odnajduje znacznik po obrocie."),
    ("N — zaciemnia salę i świeci latarką w globus.","D — obserwuje jasną i ciemną stronę."),
    ("N — obraca globus powoli.","D — mówi, kiedy u nas jest dzień, a kiedy noc."),
    ("N — prosi dziecko, by było Ziemią.","D — obraca się i okrąża latarkę, tłumacząc, co robi.")],
  mod2=["obserwacja pokazu bez odgrywania","pytanie zamknięte: „dzień czy noc?”","znacznik naklejony przez nauczyciela"],
  mod3=["oglądanie jasnej i ciemnej strony piłki","potwierdzenie gestem","udział w zaciemnianiu sali","kula jako jedyne pojęcie w cyklu"],
  mod1=["pokaz ruchu z wyjaśnieniem dnia i nocy","dodanie ruchu wokół Słońca i pór roku","poprowadzenie pokazu dla młodszych"],
  wskazowka="Nie mieszaj obrotu dobowego z obiegiem rocznym w jednych zajęciach. Najpierw dzień i noc — pory roku dopiero wtedy, gdy pierwsze jest pewne."),

 ("U", 25): dict(
  nr="U5-25", tytul="Dyżur w kąciku przyrody",
  podtytul="Korzystanie z narzędzi ogrodniczych przy pielęgnacji roślin",
  sfera="V OBSZAR PRZYRODNICZY · Narzędzia ogrodnicze (ICF d445 · PP 5.8)",
  czas="15 min", forma="dyżur indywidualny", cykl="codziennie",
  ter="Dziecko dobierze narzędzie do czynności, wykona ją i odłoży narzędzie na miejsce, w 4 z 5 dyżurów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Dobiera i używa narzędzia ogrodniczego zgodnie z przeznaczeniem."),
    ("M","Pełny cykl: dobór, użycie, odłożenie; 4 z 5 dyżurów."),
    ("A","Tablica dyżurów i wieszak z obrysami narzędzi."),
    ("R","Odkładanie na miejsce jest częścią umiejętności, nie dodatkiem do niej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Tablica dyżurów · karta obserwacji użycia narzędzi.",
  pomoce=["konewka z miarką","grabki i łopatka","spryskiwacz","wieszak z obrysami narzędzi","tablica dyżurów ze zdjęciami dzieci"],
  metody=["stały dyżur z widoczną tablicą","obrysy narzędzi jako podpowiedź odkładania","miarka na konewce","modelowanie przez dorosłego raz na początku"],
  rodzaj="Zajęcia przyrodnicze i samoobsługowe",
  przebieg=[
    ("N — pokazuje tablicę dyżurów.","D — odnajduje swoje zdjęcie i wie, że ma dyżur."),
    ("N — pyta: „czego dziś potrzebuje roślina?”.","D — ocenia wilgotność ziemi palcem."),
    ("N — wskazuje wieszak z narzędziami.","D — wybiera konewkę albo spryskiwacz."),
    ("N — przypomina o miarce.","D — nalewa wodę do kreski i podlewa."),
    ("N — wskazuje obrys na wieszaku.","D — odkłada narzędzie na właściwe miejsce.")],
  mod2=["dwa narzędzia do wyboru","przypomnienie o odłożeniu","miarka wyraźnie zaznaczona kolorem"],
  mod3=["narzędzie podane do ręki","podlewanie prowadzone ręka w rękę","jedna roślina w dyżurze","dyżur w parze z kolegą"],
  mod1=["dobór narzędzia bez podpowiedzi","ocena potrzeb trzech roślin","wprowadzenie młodszego w zasady dyżuru"],
  wskazowka="Obrysy narzędzi na wieszaku robią za instrukcję. Dziecko odkłada rzecz na miejsce, bo widzi, gdzie jest jej kształt — nie dlatego, że mu przypomniano."),

 ("U", 26): dict(
  nr="U5-26", tytul="Kto od kogo zależy",
  podtytul="Zależności między roślinami a zwierzętami",
  sfera="V OBSZAR PRZYRODNICZY · Zależności w przyrodzie (ICF d137 · PP 5.9)",
  czas="25 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko ułoży prosty łańcuch zależności z trzech ogniw i wyjaśni, co się stanie, gdy jednego zabraknie, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Buduje łańcuch zależności i przewiduje skutek usunięcia ogniwa."),
    ("M","Łańcuch trzyogniwowy z przewidywaniem; 4 z 5 prób."),
    ("A","Karty ogniw łączone sznurkiem — łańcuch da się fizycznie rozerwać."),
    ("R","Myślenie o zależnościach to podstawa rozumienia ekologii i odpowiedzialności."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty zależności · zapis wyjaśnienia skutku.",
  pomoce=["karty roślin i zwierząt","sznurek do łączenia ogniw","obrazkowe strzałki","tablica łańcucha","zdjęcia z ogrodu"],
  metody=["budowanie łańcucha z kart","fizyczne rozrywanie łańcucha","pytanie „co się stanie, gdy…”","obserwacja zależności w ogrodzie"],
  rodzaj="Zajęcia przyrodnicze",
  przebieg=[
    ("N — rozkłada karty: kwiat, pszczoła, miód.","D — ogląda karty i nazywa je."),
    ("N — pyta: „co z czym się łączy?”.","D — układa karty w kolejności i łączy sznurkiem."),
    ("N — pyta: „dlaczego akurat tak?”.","D — tłumaczy, co daje jedno drugiemu."),
    ("N — zabiera środkową kartę i przecina łańcuch.","D — obserwuje przerwany łańcuch."),
    ("N — pyta: „co się teraz stanie?”.","D — przewiduje skutek braku ogniwa.")],
  mod2=["dwa ogniwa zamiast trzech","karty ułożone przez nauczyciela do połączenia","pytanie zamknięte o skutek"],
  mod3=["para: zwierzę i jego pokarm","dopasowanie do wzoru","skutek pokazany obrazkiem","łańcuch znany z bajki"],
  mod1=["łańcuch trzyogniwowy z przewidywaniem","ułożenie własnego łańcucha z ogrodu","wyjaśnienie łańcucha młodszym"],
  wskazowka="Przetnij sznurek naprawdę. Dziecko, które zobaczy rozpadający się łańcuch, mówi o skutkach zupełnie inaczej niż to, któremu się o nich opowiedziało."),

 ("U", 27): dict(
  nr="U5-27", tytul="Gdzie kto mieszka",
  podtytul="Zwierzęta i rośliny różnych ekosystemów i stref klimatycznych",
  sfera="V OBSZAR PRZYRODNICZY · Ekosystemy (ICF d137 · PP 5.10)",
  czas="30 min", forma="mała grupa", cykl="1× w tygodniu",
  ter="Dziecko wyjaśni, dlaczego niedźwiedź polarny nie żyje w lesie, wskazując cechę przystosowania, w 4 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Przyporządkowuje organizmy do środowisk i wskazuje cechę przystosowania."),
    ("M","Uzasadnienie przez cechę; 4 z 5 prób."),
    ("A","Mata środowisk z kartami zwierząt i futerkami do dotykania."),
    ("R","Przystosowanie tłumaczy różnorodność lepiej niż lista gatunków."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Mapa środowisk · karty zwierząt · zapis uzasadnień.",
  pomoce=["mata z trzema środowiskami","karty zwierząt i roślin","próbki: futro, piasek, liście","globus z zaznaczonymi strefami","miska z lodem"],
  metody=["sortowanie na macie środowisk","dotykanie próbek","doświadczenie z lodem i futrem","pytanie o cechę przystosowania"],
  rodzaj="Zajęcia przyrodnicze",
  przebieg=[
    ("N — rozkłada matę: las, morze, kraina lodu.","D — ogląda środowiska i nazywa je."),
    ("N — rozdaje karty zwierząt.","D — kładzie kartę na właściwym środowisku."),
    ("N — pyta: „skąd wiesz, że tam?”.","D — wskazuje cechę: futro, płetwy, barwa."),
    ("N — daje do ręki futro i miskę z lodem.","D — sprawdza, że pod futrem jest cieplej."),
    ("N — pyta o niedźwiedzia polarnego w lesie.","D — wyjaśnia, dlaczego by mu tam nie pasowało.")],
  mod2=["dwa środowiska zamiast trzech","cecha wskazana pytaniem naprowadzającym","sześć kart zamiast wszystkich"],
  mod3=["dopasowanie trzech zwierząt do tła","wskazanie zamiast wyjaśnienia","środowiska kontrastowe: gorące i zimne","karta z wyraźną cechą"],
  mod1=["trzy środowiska z uzasadnieniem przez cechę","wskazanie stref na globusie","wymyślenie zwierzęcia do danego środowiska"],
  wskazowka="Doświadczenie z futrem i lodem zamienia „bo tak jest” w „bo futro grzeje”. To różnica między zapamiętaniem a zrozumieniem."),

 ("U", 28): dict(
  nr="U5-28", tytul="Obserwatorium przyrody",
  podtytul="Prowadzenie i ilustrowanie własnej obserwacji przyrodniczej",
  sfera="V OBSZAR PRZYRODNICZY · Obserwacja długoterminowa (ICF d163 · PP DE-R.2)",
  czas="20 min tygodniowo (cykl miesięczny)", forma="indywidualnie w grupie", cykl="raz w roku szkolnym",
  ter="Dziecko poprowadzi własną obserwację przyrodniczą przez miesiąc, zilustruje ją i przedstawi wnioski grupie — raz w roku, z dokumentacją.",
  ter_smart=[
    ("S","Prowadzi comiesięczną obserwację, ilustruje ją i przedstawia wnioski."),
    ("M","Min. 4 wpisy w miesiącu i prezentacja."),
    ("A","Wybór własnego obiektu obserwacji i stała półka obserwatorium."),
    ("R","Własny obiekt buduje odpowiedzialność i wytrwałość w obserwacji."),
    ("T","Raz w roku szkolnym, z dokumentacją."),
  ],
  ter_kryt="Dziennik obserwacji · wystawa ilustracji · nagranie prezentacji.",
  pomoce=["dziennik obserwacji dla każdego dziecka","półka obserwatorium","lupa i miarka","kredki i kalka","ramki na wystawę"],
  metody=["wybór własnego obiektu","cotygodniowy wpis","ilustrowanie zamiast opisywania","wystawa i prezentacja na koniec"],
  rodzaj="Projekt przyrodniczy",
  przebieg=[
    ("N — proponuje obiekty: fasola, drzewo za oknem, ślimak.","D — wybiera swój obiekt obserwacji."),
    ("N — wydaje dziennik z ramkami na cztery tygodnie.","D — wykonuje pierwszy rysunek i podpisuje datę."),
    ("N — przypomina co tydzień o wpisie.","D — obserwuje, mierzy i rysuje kolejny etap."),
    ("N — pomaga przygotować wystawę.","D — układa rysunki w kolejności i oprawia je."),
    ("N — zaprasza grupę na prezentację.","D — opowiada, co obserwował i co się zmieniło.")],
  mod2=["obiekt wybrany z dwóch propozycji","dwa wpisy zamiast czterech","prezentacja w parze"],
  mod3=["obserwacja wspólna dla całej grupy","doklejenie zdjęcia zamiast rysunku","przypomnienie o wpisie z piktogramem","prezentacja jednym zdaniem"],
  mod1=["cztery wpisy z pomiarem i wnioskiem","obserwacja obiektu zmieniającego się powoli","poprowadzenie wystawy dla rodziców"],
  wskazowka="Niech dziecko wybierze obiekt samo, nawet jeśli wybierze kamień. Miesiąc obserwacji kamienia też coś pokaże — choćby to, że rosną na nim mchy."),
}
