# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IV (poruszanie się), wersja B (5 lat)."""

KONSPEKTY_5_D4 = {
 ("B", 16): dict(
  nr="B4-16", tytul="Olimpiada czterech ruchów",
  podtytul="Wykonywanie form ruchu: bieżnych, skocznych, czworakowania i rzutnych",
  sfera="IV PORUSZANIE SIĘ · Formy ruchu (ICF d455 · PP 9.4)",
  czas="25 min", forma="cała grupa (stacje)", cykl="3× w tygodniu",
  ter="Dziecko wykona cztery formy ruchu na sygnał słowny, bez pokazu, zachowując kierunek i technikę, w 3 z 5 zajęć, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Wykonuje bieg, skok, czworakowanie i rzut na polecenie słowne."),
    ("M","4 formy bez pokazu; 3 z 5 zajęć."),
    ("A","Cztery stacje oznaczone symbolem ruchu; obieg według strzałek."),
    ("R","Różnorodność form ruchu buduje ogólną sprawność i koordynację."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Tor sprawnościowy · karta prób po każdym zajęciu.",
  pomoce=["4 stacje z symbolami ruchu","medale i dyplomy olimpijskie","szarfy w kolorach drużyn","woreczki do rzutu i obręcze","gwizdek i strzałki kierunkowe"],
  metody=["obwód stacyjny z rotacją","symbol ruchu zamiast instrukcji słownej","drużyny zamiast rywalizacji indywidualnej","podsumowanie: co było najtrudniejsze"],
  rodzaj="Zajęcia wspierające rozwój ruchowy",
  przebieg=[
    ("N — otwiera olimpiadę, rozdaje szarfy drużynowe.","D — zakłada szarfę, ustawia się przy pierwszej stacji."),
    ("N — pokazuje symbole stacji: bieg, skok, czworaki, rzut.","D — nazywa ruch przypisany każdemu symbolowi."),
    ("N — daje sygnał gwizdkiem do rotacji stacji.","D — wykonuje ruch właściwy dla swojej stacji."),
    ("N — wydaje polecenia słowne bez pokazu.","D — wykonuje formę ruchu na samo polecenie."),
    ("N — kończy dekoracją i pyta o najtrudniejszą stację.","D — odbiera medal i nazywa trudność.")],
  mod2=["dwie stacje zamiast czterech","pokaz przed każdą stacją","krótszy czas na stacji"],
  mod3=["jedna forma ruchu na zajęcia","naśladowanie nauczyciela przez cały czas","stacja bez rotacji","konsultacja z fizjoterapeutą"],
  mod1=["sekwencja 4 form w zapamiętanej kolejności","nazwanie ruchu przed wykonaniem","prowadzenie stacji jako sędzia","układ własny z trzech ruchów dla drużyny"],
  wskazowka="Symbol na stacji zwalnia nauczyciela z powtarzania poleceń — dziecko odczytuje zadanie z obrazka i całą uwagę kieruje na ruch, nie na słuchanie."),

 ("B", 17): dict(
  nr="B4-17", tytul="Linoskoczkowie",
  podtytul="Utrzymywanie równowagi w staniu i chodzie po wyznaczonej linii",
  sfera="IV PORUSZANIE SIĘ · Równowaga (ICF d415 · PP 9.4)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko ustoi na jednej nodze 5 sekund bez podparcia i przejdzie 2 metry po linii, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Stoi na jednej nodze i przechodzi po linii stopa za stopą."),
    ("M","5 sekund · 2 metry; 3 z 5 prób."),
    ("A","Lina na podłodze, parasol jako rekwizyt równoważny."),
    ("R","Równowaga warunkuje bezpieczeństwo ruchowe i pracę przy stoliku."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Próba równowagi · pomiar czasu i długości przejścia.",
  pomoce=["lina lub taśma na podłodze","parasolki i wachlarze jako rekwizyty","ławeczka gimnastyczna","woreczki do niesienia na głowie","muzyka cyrkowa"],
  metody=["scenografia cyrkowa nadająca sens ćwiczeniu","rekwizyt ułatwiający równowagę","liczenie sekund przez grupę","stopniowanie: podłoga → lina → ławeczka"],
  rodzaj="Zajęcia wspierające rozwój ruchowy",
  przebieg=[
    ("N — rozkłada linę: „to lina cyrkowa, jesteśmy linoskoczkami”.","D — staje na początku liny z parasolką."),
    ("N — pokazuje stanie na jednej nodze, liczy do pięciu.","D — stoi na jednej nodze, grupa liczy."),
    ("N — zaprasza do przejścia po linie stopa za stopą.","D — przechodzi 2 metry, patrząc przed siebie."),
    ("N — dodaje woreczek na głowę.","D — przechodzi linę, utrzymując woreczek."),
    ("N — kończy ukłonem cyrkowca i oklaskami.","D — kłania się, przechodzi ostatni raz.")],
  mod2=["stanie 3 sekundy z lekkim podparciem","lina 1 metr","przejście z trzymaniem ręki dorosłego"],
  mod3=["stanie na jednej nodze z trzymaniem poręczy","chód po szerokim pasie zamiast liny","2 sekundy jako cel","ocena napięcia posturalnego"],
  mod1=["stanie 10 sekund i przejście po ławeczce","przejście z woreczkiem i przedmiotem w ręce","przejście tyłem po linie","pokaz cyrkowy dla grupy"],
  wskazowka="Powiedz „patrz na punkt przed sobą”, nie „patrz pod nogi” — wzrok skierowany w dół rozstraja równowagę, którą właśnie ćwiczymy."),

 ("B", 18): dict(
  nr="B4-18", tytul="Pracownia nożyczek",
  podtytul="Sprawne posługiwanie się nożyczkami, lepienie, nawlekanie, majsterkowanie",
  sfera="IV PORUSZANIE SIĘ · Motoryka precyzyjna (ICF d440 · PP 9.5·6.3)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko przetnie kartkę wzdłuż grubej linii prostej i wylepi kulkę oraz wałek z masy plastycznej, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Tnie po linii i formuje z masy podstawowe kształty."),
    ("M","Cięcie po linii · 2 kształty; 3 z 5 prób."),
    ("A","Nożyczki dopasowane do ręki, linia gruba i kontrastowa."),
    ("R","Sprawność dłoni jest bezpośrednim zapleczem pisania."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Wytwór dziecka · ocena dokładności cięcia po sesji.",
  pomoce=["nożyczki dla prawo- i leworęcznych","paski z grubymi liniami do cięcia","masa plastyczna","koraliki i żyłki","kartoniki na gotowe prace"],
  metody=["stopniowanie: nacięcia → linia prosta → linia łamana","rozgrzewka dłoni przed pracą","pozycja nożyczek: kciuk do góry","wystawa prac w pracowni"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — prowadzi rozgrzewkę dłoni: ugniatanie masy.","D — ugniata masę, lepi kulkę i wałek."),
    ("N — pokazuje chwyt nożyczek: „kciuk patrzy w górę”.","D — ustawia palce w nożyczkach poprawnie."),
    ("N — podaje pasek z grubą linią.","D — tnie wzdłuż linii, trzymając papier drugą ręką."),
    ("N — podaje pasek z linią łamaną chętnym.","D — tnie po linii, obracając papier."),
    ("N — zaprasza do wystawy prac.","D — przykleja wycinankę na kartonik i podpisuje znaczkiem.")],
  mod2=["nacięcia zamiast cięcia po linii","papier sztywniejszy, łatwiejszy do trzymania","dorosły przytrzymuje kartkę"],
  mod3=["cięcie jednym ruchem, papier trzymany przez dorosłego","nożyczki treningowe (podwójne uchwyty)","tylko lepienie, bez nożyczek","ocena napięcia mięśniowego dłoni"],
  mod1=["wycięcie kształtu po linii łamanej z marginesem 5 mm","praca przestrzenna według wzoru","nawlekanie 8 elementów w zadanej kolejności","pomoc koledze w ustawieniu chwytu"],
  wskazowka="Rozgrzewka dłoni przed nożyczkami skraca naukę o tygodnie — ugniatanie masy przygotowuje te same mięśnie, które później prowadzą ostrze po linii."),

 ("B", 19): dict(
  nr="B4-19", tytul="Szlaczki na ścianie",
  podtytul="Prawidłowy chwyt narzędzia pisarskiego i kontrola siły nacisku",
  sfera="IV PORUSZANIE SIĘ · Grafomotoryka (ICF d440 · PP 9.6)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko utrzyma prawidłowy chwyt przez całą pracę plastyczną i zamaluje pole bez przedzierania kartki, w 3 z 5 prac, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Trzyma kredkę chwytem trójpalcowym i dozuje nacisk."),
    ("M","Cała praca bez przedarcia; 3 z 5 prac."),
    ("A","Praca na pionowej powierzchni ustawia nadgarstek samoczynnie."),
    ("R","Chwyt i nacisk decydują o wytrzymałości ręki przy pisaniu."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta prac graficznych · obserwacja chwytu podczas pracy.",
  pomoce=["papier przypięty do sztalugi lub ściany","kredki krótkie (wymuszają chwyt trójpalcowy)","nasadki korygujące","wzory szlaczków","kreda i tablica"],
  metody=["praca na pionie zamiast na blacie","krótkie kredki wymuszające prawidłowy chwyt","szlaczki rytmiczne z muzyką","kontrola nacisku: rysujemy cicho jak myszka"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — przypina papier do ściany: „dziś malujemy na stojąco”.","D — staje przed papierem, bierze krótką kredkę."),
    ("N — pokazuje chwyt trzema palcami: „szczypce”.","D — ustawia palce w chwycie trójpalcowym."),
    ("N — rysuje szlaczek do muzyki, wolno i rytmicznie.","D — odtwarza szlaczek na swojej części papieru."),
    ("N — proponuje: „rysujemy cicho, jak myszka”.","D — zmniejsza nacisk, kredka nie drze papieru."),
    ("N — zaprasza do zamalowania pola wewnątrz konturu.","D — zamalowuje pole bez wychodzenia i przedzierania.")],
  mod2=["nasadka korygująca na kredce","krótsza praca, jedno pole do zamalowania","przypomnienie chwytu w połowie pracy"],
  mod3=["praca kredą na dużej tablicy","chwyt korygowany fizycznie przy każdej próbie","2 minuty pracy zamiast 10","ocena napięcia mięśniowego i pozycji ciała"],
  mod1=["szlaczki w liniaturze przez 10 minut","utrzymanie stałego nacisku na całej pracy","rysowanie wzoru z pamięci","zaprojektowanie szlaczka dla kolegów"],
  wskazowka="Pionowa powierzchnia sama ustawia nadgarstek w wyproście — to najprostszy sposób poprawy chwytu, skuteczniejszy niż jakiekolwiek przypominanie."),

 ("B", 20): dict(
  nr="B4-20", tytul="Laboratorium przelewania",
  podtytul="Posługiwanie się przedmiotami o różnej wielkości i ciężarze, także wymagającymi precyzji",
  sfera="IV PORUSZANIE SIĘ · Manipulacja (ICF d430–d440 · PP 9.5)",
  czas="25 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko przesypie kaszę łyżką między naczyniami i przeniesie tacę z dwoma kubkami, nie rozlewając zawartości, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Przesypuje, przelewa i przenosi, kontrolując siłę i tempo."),
    ("M","Bez rozsypania i rozlania; 3 z 5 prób."),
    ("A","Naczynia stabilne, taca z uchwytami, praca na tacce z brzegiem."),
    ("R","Precyzja manipulacyjna przekłada się na samoobsługę i pracę szkolną."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zadania praktyczne · karta prób precyzji po sesji.",
  pomoce=["dzbanki, miski, łyżki różnej wielkości","kasza, ryż, woda barwiona","tace z uchwytami i podniesionym brzegiem","pipety i lejki","ściereczki do sprzątania"],
  metody=["praca na tacce ograniczającej rozsypanie","stopniowanie: kasza → ryż → woda","dziecko sprząta po sobie samo","zadania praktyczne z realnym celem (nakrywanie do stołu)"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — pokazuje przesypywanie łyżką: powoli, nad tacką.","D — przesypuje kaszę między dwiema miskami."),
    ("N — podaje mniejszą łyżkę: „teraz trudniej”.","D — przesypuje precyzyjniej, kontrolując ruch."),
    ("N — wprowadza wodę i lejek.","D — przelewa wodę przez lejek do butelki."),
    ("N — stawia na tacy dwa kubki: „przenieś do stolika”.","D — niesie tacę oburącz, nie rozlewając."),
    ("N — wskazuje ściereczkę przy rozsypaniu.","D — sprząta po sobie i próbuje ponownie.")],
  mod2=["większa łyżka i szersze naczynia","tylko kasza, bez wody","krótsza droga z tacą"],
  mod3=["przesypywanie ręką lub kubkiem","naczynia z podwyższonym brzegiem","przenoszenie jednego przedmiotu","wsparcie w stabilizacji tułowia"],
  mod1=["nalanie wody do zaznaczonej kreski","użycie pipety do przenoszenia kropli","nakrycie stołu dla całego stolika","dostosowanie siły chwytu do ciężaru przedmiotu"],
  wskazowka="Ściereczka w zasięgu ręki zmienia rozsypanie w naturalny element pracy — dziecko, które sprząta samo, próbuje dalej zamiast rezygnować ze wstydu."),
}
