# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VI (życie domowe), wersja C (6 lat)."""

KONSPEKTY_6_D6 = {
 ("C", 26): dict(
  nr="C6-26", tytul="Restauracja dyżurnych",
  podtytul="Nakrywanie do stołu, nakładanie posiłku i sprzątanie po nim",
  sfera="VI ŻYCIE DOMOWE · Obsługa posiłku (ICF d640 · PP WSR·Zad.7)",
  czas="15 min", forma="para dyżurnych", cykl="codziennie",
  ter="Dziecko nakryje do stołu dla całego stolika według wzoru i posprząta swoje naczynia, w 3 z 5 posiłków, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nakrywa stolik zgodnie ze wzorem i sprząta po posiłku."),
    ("M","Cały stolik; 3 z 5 posiłków."),
    ("A","Podkładka ze wzorem nakrycia; wózek na naczynia."),
    ("R","Obsługa posiłku uczy odpowiedzialności i planowania czynności."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Grafik dyżurów · karta wykonania po posiłku.",
  pomoce=["podkładki ze wzorem nakrycia","tace i wózek na naczynia","fartuszki dyżurnych","lista czynności dyżurnego","dzwonek zapraszający do stołu"],
  metody=["wzór nakrycia na podkładce","podział czynności między dyżurnych","lista kontrolna czynności","dzwonek jako sygnał gotowości"],
  rodzaj="Kształtowanie samodzielności / kompetencje społeczne",
  przebieg=[
    ("N — wskazuje grafik i rozdaje fartuszki.","D — sprawdza, jakie ma dziś czynności."),
    ("N — pokazuje podkładkę ze wzorem nakrycia.","D — rozkłada sztućce i kubki według wzoru."),
    ("N — pyta: „ile miejsc przy waszym stoliku?”.","D — przelicza miejsca i przygotowuje tyle nakryć."),
    ("N — daje sygnał do zaproszenia grupy.","D — dzwoni i zaprasza dzieci do stołu."),
    ("N — przypomina o sprzątnięciu po posiłku.","D — zbiera naczynia na wózek i wyciera stół.")],
  mod2=["nakrycie dla dwóch osób","wzór nakrycia leżący obok","jedna czynność dyżuru"],
  mod3=["rozłożenie serwetek","podanie przedmiotów kolejno przez dorosłego","dyżur w parze z dzieckiem sprawnym","wzmocnienie po każdej czynności"],
  mod1=["obsługa całego stolika z planowaniem kolejności","nakładanie posiłku innym dzieciom","wprowadzenie nowego dyżurnego","zaproponowanie usprawnienia w organizacji posiłku"],
  wskazowka="Przeliczanie miejsc przed nakryciem to ukryta matematyka — dyżur staje się wtedy zadaniem liczbowym o realnym celu."),

 ("C", 27): dict(
  nr="C6-27", tytul="Dyżury z rozliczeniem",
  podtytul="Pełnienie dyżurów i drobnych obowiązków na rzecz grupy",
  sfera="VI ŻYCIE DOMOWE · Odpowiedzialność (ICF d640 · PP 1.10·WSR)",
  czas="15 min dziennie", forma="dyżurni", cykl="codziennie",
  ter="Dziecko wykona pełny dyżur bez przypomnień i zgłosi jego zakończenie, w 3 z 5 dyżurów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Realizuje dyżur samodzielnie i informuje o zakończeniu."),
    ("M","Bez przypomnień; 3 z 5 dyżurów."),
    ("A","Grafik tygodniowy, plan czynności, krąg rozliczeniowy."),
    ("R","Systematyczne obowiązki budują odpowiedzialność szkolną."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Grafik dyżurów · karta rozliczenia tygodnia.",
  pomoce=["grafik tygodniowy dyżurów","plany czynności dla każdego dyżuru","karta rozliczenia tygodniowego","identyfikatory dyżurnych","krąg podsumowujący"],
  metody=["dyżur na cały tydzień","plan czynności zamiast poleceń","cotygodniowe rozliczenie na kręgu","dyżurni wprowadzają następców"],
  rodzaj="Kształtowanie samodzielności / kompetencje społeczne",
  przebieg=[
    ("N — w poniedziałek rozdziela dyżury na tydzień.","D — wybiera dyżur i zapoznaje się z planem."),
    ("N — obserwuje wykonanie bez przypominania.","D — realizuje dyżur samodzielnie każdego dnia."),
    ("N — czeka na zgłoszenie zakończenia.","D — informuje o wykonaniu obowiązku."),
    ("N — w piątek prowadzi krąg rozliczeniowy.","D — opowiada, jak wywiązał się z dyżuru."),
    ("N — prosi o wprowadzenie następnego dyżurnego.","D — pokazuje koledze, na czym polega dyżur.")],
  mod2=["dyżur co drugi dzień","przypomnienie na początku dnia","plan czynności wskazywany przez dorosłego"],
  mod3=["jedna czynność dyżuru","dyżur w parze","polecenie z gestem przy każdym kroku","wzmocnienie natychmiastowe"],
  mod1=["dyżur tygodniowy z planowaniem i rozliczeniem","zaproponowanie nowego dyżuru dla grupy","przeszkolenie następnego dyżurnego","przejęcie dyżuru za nieobecnego kolegę"],
  wskazowka="Rozliczenie na kręgu w piątek zamyka tydzień odpowiedzialności — bez niego dyżur jest czynnością, z nim staje się zobowiązaniem wobec grupy."),

 ("C", 28): dict(
  nr="C6-28", tytul="Porządek w mojej przestrzeni",
  podtytul="Utrzymywanie porządku w swoich rzeczach i najbliższym otoczeniu",
  sfera="VI ŻYCIE DOMOWE · Organizacja przestrzeni (ICF d650 · PP 2.5)",
  czas="15 min", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko uporządkuje swoje miejsce i półkę po sygnale, sprawdzając efekt według zdjęcia, w 3 z 5 dni, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Porządkuje półkę i miejsce pracy zgodnie ze wzorem."),
    ("M","Półka i miejsce; 3 z 5 dni."),
    ("A","Zdjęcie wzorcowe półki; przegródki z etykietami."),
    ("R","Porządek w rzeczach osobistych to codzienna kompetencja ucznia."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zdjęcie wzorcowe półki · zapis dzienny.",
  pomoce=["zdjęcia wzorcowe półek","przegródki i pudełka z etykietami","karta przeglądu tygodniowego","minutnik","aparat do dokumentacji"],
  metody=["zdjęcie wzorcowe jako kryterium","cotygodniowy przegląd rzeczy","etykiety wykonane przez dzieci","samoocena porządku"],
  rodzaj="Kształtowanie samodzielności / przygotowanie do szkoły",
  przebieg=[
    ("N — pokazuje zdjęcie wzorcowe półki.","D — porównuje swoją półkę ze zdjęciem."),
    ("N — uruchamia minutnik na porządkowanie.","D — układa rzeczy w przegródkach z etykietami."),
    ("N — proponuje przegląd: „co tu już nie jest potrzebne?”.","D — wybiera rzeczy do zabrania do domu."),
    ("N — prosi o zrobienie zdjęcia półki po porządkach.","D — fotografuje uporządkowaną półkę."),
    ("N — zaznacza przegląd w karcie tygodniowej.","D — ocenia swój porządek na karcie.")],
  mod2=["porządkowanie samej półki","zdjęcie wzorcowe przy półce","dłuższy czas"],
  mod3=["odkładanie wskazanych rzeczy","porządkowanie razem z dorosłym","jedna przegródka","wzmocnienie po każdym elemencie"],
  mod1=["utrzymywanie porządku przez cały dzień bez sygnału","zauważanie i porządkowanie nieporządku w kąciku","zaproponowanie lepszej organizacji przegródek","pomoc koledze w uporządkowaniu półki"],
  wskazowka="Cotygodniowy przegląd rzeczy jest ważniejszy niż codzienne układanie — dziecko uczy się, że porządek to także decydowanie, co zostaje, a co odchodzi."),

 ("C", 29): dict(
  nr="C6-29", tytul="Ogrodnicy z kącika przyrody",
  podtytul="Czynności użyteczne: pielęgnacja roślin i opieka nad kącikiem przyrody",
  sfera="VI ŻYCIE DOMOWE · Opieka nad przyrodą (ICF d640–d650 · PP 5.5·DE-R.3)",
  czas="20 min", forma="para dyżurnych", cykl="codziennie",
  ter="Dziecko wykona pielęgnację dwóch roślin według instrukcji obrazkowej, bez pomocy dorosłego, w 3 z 5 dyżurów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Podlewa i pielęgnuje rośliny według instrukcji."),
    ("M","2 rośliny · bez pomocy; 3 z 5 dyżurów."),
    ("A","Instrukcja obrazkowa i miarka wody przy każdej roślinie."),
    ("R","Opieka nad żywym organizmem uczy systematyczności i troski."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Dziennik kącika przyrody · zapis obserwacji.",
  pomoce=["rośliny doniczkowe i uprawy w słoikach","konewki z miarką","instrukcje pielęgnacji w obrazkach","dziennik obserwacji z rubrykami","lupy i linijki do pomiaru wzrostu"],
  metody=["instrukcja obrazkowa przy każdej roślinie","miarka wody zapobiegająca przelaniu","dziennik obserwacji prowadzony przez dzieci","pomiar wzrostu roślin"],
  rodzaj="Edukacja przyrodnicza / kształtowanie samodzielności",
  przebieg=[
    ("N — wskazuje instrukcję przy pierwszej roślinie.","D — odczytuje, ile wody potrzebuje roślina."),
    ("N — podaje konewkę z miarką.","D — odmierza wodę i podlewa roślinę."),
    ("N — pokazuje linijkę do pomiaru wzrostu.","D — mierzy roślinę i zapisuje wynik w dzienniku."),
    ("N — pyta o zmiany: „co się zmieniło od wczoraj?”.","D — opisuje obserwacje: nowy listek, kwiat."),
    ("N — prosi o relację na kręgu.","D — opowiada grupie o stanie kącika przyrody.")],
  mod2=["pielęgnacja jednej rośliny","instrukcja wskazywana przez dorosłego","pomiar bez zapisu"],
  mod3=["podlanie rośliny odmierzoną porcją z pomocą","jedna czynność","dyżur w parze","obserwacja bez zapisu"],
  mod1=["prowadzenie całego kącika z planowaniem podlewania","zapis obserwacji w dzienniku i wnioski","założenie własnej uprawy","relacjonowanie zmian całej grupie"],
  wskazowka="Miarka na konewce ratuje rośliny i uczy odmierzania — bez niej pierwszy tydzień dyżurów kończy się zwykle przelaniem wszystkich doniczek."),
}
