# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar V (dbanie o siebie), wersja A (3–4 lata)."""

KONSPEKTY_D5 = {
 ("A", 21): dict(
  nr="D5-21", tytul="Sygnał na czas",
  podtytul="Zgłaszanie potrzeb fizjologicznych i korzystanie z toalety",
  sfera="V DBANIE O SIEBIE · Toaleta (ICF d530 · PP 9.7)",
  czas="5 min przy każdej wizycie", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko zgłosi potrzebę gestem lub słowem i skorzysta z toalety, przyjmując pomoc wyłącznie przy ubraniu, w 3 z 5 sytuacji dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Sygnalizuje potrzebę i idzie do toalety."),
    ("M","3 z 5 sytuacji dziennie; pomoc tylko przy ubraniu."),
    ("A","Symbol toalety dostępny; stałe pory jako siatka bezpieczeństwa."),
    ("R","Samodzielność w toalecie buduje godność i niezależność dziecka."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta samoobsługi · zapis dzienny zgłoszeń i wizyt planowych.",
  pomoce=["symbol toalety (karta lub brelok)","stopnie i nakładka na sedes","plan obrazkowy: siusiu – spłuczka – ręce","tabela z uśmieszkami"],
  metody=["stałe pory co 2 godziny jako podstawa","symbol jako sposób zgłoszenia","plan obrazkowy w toalecie","wzmocnienie za zgłoszenie, nie za efekt"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — w stałej porze pokazuje symbol: „idziemy do toalety”.","D — bierze symbol i idzie z nauczycielem."),
    ("N — wskazuje plan obrazkowy przy toalecie.","D — wykonuje kolejne kroki według obrazków."),
    ("N — pomaga tylko przy trudnym zapięciu.","D — samodzielnie ściąga i podciąga spodenki."),
    ("N — przypomina o spłuczce i myciu rąk gestem.","D — spłukuje i myje ręce."),
    ("N — zaznacza w tabeli i chwali zgłoszenie.","D — przykleja uśmieszek w swojej tabeli.")],
  mod2=["stałe pory co 1,5 godziny","symbol podawany przez dorosłego","pomoc przy całym ubraniu"],
  mod3=["wyłącznie stałe pory, bez oczekiwania na zgłoszenie","pełna pomoc dorosłego, dziecko uczestniczy","wzmocnienie za samo wejście do toalety","rozmowa z rodzicami o wspólnym systemie"],
  mod1=["zgłoszenie, wizyta, ubranie i mycie rąk bez pomocy","zgłaszanie potrzeby także poza salą i na spacerze","przypomnienie koledze o myciu rąk","samodzielne radzenie sobie z trudnym zapięciem"],
  wskazowka="Chwal zgłoszenie, nie sam efekt — dziecko kontroluje moment powiedzenia „chcę”, a nie zawsze kontroluje resztę."),

 ("A", 22): dict(
  nr="D5-22", tytul="Cztery kroki mycia",
  podtytul="Mycie rąk według instrukcji obrazkowej",
  sfera="V DBANIE O SIEBIE · Higiena rąk (ICF d510 · PP 9.7)",
  czas="5 min przy każdym myciu", forma="mała grupa", cykl="codziennie",
  ter="Dziecko wykona cztery kroki mycia rąk korzystając z instrukcji obrazkowej przy umywalce, po jednym przypomnieniu, w 3 z 5 prób dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Wykonuje: woda – mydło – pocieranie – wytarcie."),
    ("M","4 kroki · 1 przypomnienie; 3 z 5 prób dziennie."),
    ("A","Instrukcja obrazkowa na wysokości wzroku nad umywalką."),
    ("R","Higiena rąk to podstawowy nawyk zdrowotny w grupie."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Instrukcja obrazkowa 4 kroki · obserwacja i zapis dzienny.",
  pomoce=["instrukcja obrazkowa nad umywalką","mydło w pianie z dozownikiem","piosenka-minutnik do pocierania","ręczniki papierowe w zasięgu ręki"],
  metody=["instrukcja wizualna zamiast słownej","piosenka wyznaczająca czas pocierania","łańcuch czynności od tyłu (najpierw ostatni krok samodzielnie)","wzmocnienie po pełnym cyklu"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — wskazuje pierwszy obrazek: „woda”.","D — odkręca wodę i moczy ręce."),
    ("N — wskazuje drugi obrazek i podaje dozownik.","D — nabiera mydło jednym naciśnięciem."),
    ("N — śpiewa piosenkę-minutnik.","D — pociera ręce przez całą piosenkę."),
    ("N — wskazuje obrazek ręcznika, milczy.","D — wyciera ręce i wyrzuca ręcznik."),
    ("N — pokazuje czyste dłonie grupie: „gotowe!”.","D — pokazuje ręce i wraca do sali.")],
  mod2=["dwa kroki samodzielnie, dwa z pomocą","obrazki wskazywane przy każdym kroku","krótsza piosenka"],
  mod3=["prowadzenie rąk przez wszystkie kroki","mydło podawane bezpośrednio na dłonie","jeden krok samodzielny (wytarcie)","sprawdzenie nadwrażliwości dotykowej na wodę i mydło"],
  mod1=["mycie bez przypomnienia, z własnej inicjatywy","mycie przed posiłkiem i po toalecie za każdym razem","przypomnienie koledze o kroku, który pominął","dbanie także o nos i twarz"],
  wskazowka="Zacznij uczyć od ostatniego kroku — dziecko, które samo wyciera ręce, kończy czynność sukcesem, a to zapamiętuje się najmocniej."),

 ("A", 23): dict(
  nr="D5-23", tytul="Łyżka i kubek",
  podtytul="Samodzielne jedzenie łyżką i widelcem, picie z kubka",
  sfera="V DBANIE O SIEBIE · Posiłki (ICF d550·d560 · PP 9.7·WSR)",
  czas="posiłek", forma="stolik (4 dzieci)", cykl="codziennie",
  ter="Dziecko zje samodzielnie cały posiłek łyżką i napije się z otwartego kubka, przyjmując pomoc wyłącznie przy nabieraniu, w 3 z 5 posiłków, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Je łyżką i pije z otwartego kubka bez rozlewania."),
    ("M","Cały posiłek; 3 z 5 posiłków."),
    ("A","Kubek mały, ciężki u podstawy; miska z podwyższonym brzegiem."),
    ("R","Samodzielne jedzenie to codzienna, wielokrotnie powtarzana umiejętność."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja posiłku · 5 posiłków w tygodniu · karta samodzielności.",
  pomoce=["miska z podwyższonym brzegiem","łyżka z pogrubioną rączką","mały kubek stabilny u podstawy","podkładka antypoślizgowa","śliniak lub fartuszek"],
  metody=["sprzęt dostosowany do możliwości dziecka","pomoc tylko przy nabieraniu (ręka na ręce)","dorosły je razem z dziećmi (modelowanie)","brak pośpiechu — stały czas na posiłek"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — siada przy stoliku i je razem z dziećmi.","D — obserwuje i sięga po łyżkę."),
    ("N — przy trudności prowadzi rękę tylko przy nabieraniu.","D — samodzielnie wkłada łyżkę do ust."),
    ("N — podaje kubek do połowy napełniony.","D — pije z kubka oburącz, odstawia go."),
    ("N — nie pospiesza, czeka do końca posiłku.","D — je w swoim tempie do końca porcji."),
    ("N — pokazuje, jak odnieść naczynia.","D — odnosi kubek na wózek.")],
  mod2=["pomoc przy nabieraniu przez cały posiłek","kubek z uchem i mniejszą porcją","posiłek podzielony na mniejsze części"],
  mod3=["karmienie z udziałem dziecka (dziecko trzyma łyżkę razem z dorosłym)","kubek niekapek","5 samodzielnych łyżek jako cel","konsultacja co do trudności oralno-motorycznych"],
  mod1=["jedzenie widelcem i łyżką, nalewanie wody z dzbanka","nakładanie sobie porcji","sprzątnięcie swojego miejsca po posiłku","zachowanie kulturalne: serwetka, podziękowanie"],
  wskazowka="Pomagaj tylko przy nabieraniu — droga łyżki do ust to najprzyjemniejsza część, którą dziecko powinno wykonać samo, i właśnie ona utrwala nawyk."),

 ("A", 24): dict(
  nr="D5-24", tytul="Ubieram się sam",
  podtytul="Próby samodzielnego ubierania się i rozbierania",
  sfera="V DBANIE O SIEBIE · Ubieranie (ICF d540 · PP 9.7)",
  czas="10 min (szatnia)", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko ubierze i zdejmie trzy części garderoby korzystając z planu obrazkowego kolejności ubierania, w 3 z 5 wyjść, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Zakłada i zdejmuje kurtkę, czapkę i buty."),
    ("M","3 części garderoby; 3 z 5 wyjść."),
    ("A","Plan obrazkowy w szatni; ubranie rozłożone w kolejności."),
    ("R","Samodzielność w szatni skraca przygotowanie całej grupy."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Pomiar czasu ubierania · plan obrazkowy · zapis dzienny.",
  pomoce=["plan obrazkowy kolejności ubierania","ławeczka na wysokości dziecka","znaczniki lewy/prawy but","lustro w szatni"],
  metody=["stała kolejność ubierania","ubranie rozłożone przez dziecko przed ubieraniem","technika kurtki „przez głowę”","pomoc tylko przy zamku"],
  rodzaj="Kształtowanie samodzielności / pomoc p-p",
  przebieg=[
    ("N — wskazuje plan: „najpierw spodnie, potem buty, kurtka”.","D — rozkłada ubranie w kolejności z planu."),
    ("N — pokazuje technikę zakładania kurtki przez głowę.","D — zakłada kurtkę techniką pokazaną."),
    ("N — wskazuje znaczniki w butach.","D — dopasowuje but do właściwej nogi."),
    ("N — pomaga wyłącznie przy zamku i rzepie.","D — ubiera resztę samodzielnie."),
    ("N — pokazuje dziecko w lustrze: „ubrałeś się sam!”.","D — ogląda się w lustrze, sprawdza czapkę.")],
  mod2=["dwie części garderoby zamiast trzech","ubranie podawane po kolei przez dorosłego","dłuższy czas na ubieranie"],
  mod3=["zdejmowanie jednej części (czapka, kapcie)","rozpoczęcie ruchu przez dorosłego, dokończenie przez dziecko","ubranie luźniejsze, bez zapięć","wsparcie w kształtowaniu schematu ciała"],
  mod1=["pełne ubranie w czasie przewidzianym dla grupy","zapinanie guzików i suwaka","pomoc młodszemu dziecku w szatni","dobór ubrania do pogody"],
  wskazowka="Rozłożenie ubrania w kolejności to połowa sukcesu — większość „nieudanego” ubierania zaczyna się od kurtki założonej przed spodniami."),

 ("A", 25): dict(
  nr="D5-25", tytul="Mój termometr samopoczucia",
  podtytul="Komunikowanie zmęczenia, głodu, złego samopoczucia i potrzeby odpoczynku",
  sfera="V DBANIE O SIEBIE · Sygnały ciała (ICF d571 · PP 9.10)",
  czas="10 min + sytuacje naturalne", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko samodzielnie sięgnie po symbol lub użyje słowa, aby zgłosić zmęczenie albo głód, w 3 z 5 sytuacji dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Zgłasza zmęczenie lub głód symbolem albo słowem."),
    ("M","3 z 5 sytuacji dziennie."),
    ("A","Tablica sygnałów w zasięgu dziecka; dorosły reaguje natychmiast."),
    ("R","Rozpoznawanie sygnałów ciała zapobiega reakcjom emocjonalnym."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta sygnałów dziecka · zapis zdarzeń i zgłoszeń.",
  pomoce=["tablica sygnałów: zmęczony, głodny, boli, chcę biegać","kącik odpoczynku z poduszką","symbol „odpoczynek” na breloku","zdjęcia dzieci w różnych stanach"],
  metody=["nazywanie stanu dziecka przez dorosłego","symbol jako narzędzie zgłoszenia","natychmiastowa reakcja na sygnał","łączenie sygnału z rozwiązaniem (zmęczony → poduszka)"],
  rodzaj="Zajęcia wspierające samoregulację / pomoc p-p",
  przebieg=[
    ("N — obserwuje i nazywa: „widzę, że jesteś zmęczony”.","D — słyszy nazwę swojego stanu."),
    ("N — podaje tablicę i wskazuje symbol „zmęczony”.","D — wskazuje symbol razem z nauczycielem."),
    ("N — prowadzi do kącika odpoczynku.","D — siada na poduszce, odpoczywa."),
    ("N — po odpoczynku pyta: „lepiej?” i wskazuje symbole.","D — pokazuje, że chce wrócić do zabawy."),
    ("N — w ciągu dnia zostawia tablicę w zasięgu dziecka.","D — samodzielnie sięga po symbol przy potrzebie.")],
  mod2=["dwa symbole zamiast czterech","tablica podawana przez dorosłego","nazwanie stanu przed każdym zgłoszeniem"],
  mod3=["jeden symbol: „odpoczynek”","dorosły rozpoznaje sygnały i proponuje rozwiązanie","stałe przerwy w rytmie dnia niezależnie od zgłoszeń","obserwacja pod kątem przeciążenia sensorycznego"],
  mod1=["powiedzenie zdaniem, co czuje i czego potrzebuje","zgłoszenie zanim pojawi się reakcja emocjonalna","wybór własnej strategii regulacji","zauważenie zmęczenia u kolegi"],
  wskazowka="Nazywaj stan dziecka na głos, zanim poprosisz o zgłoszenie — najpierw musi usłyszeć słowo od dorosłego, żeby móc go później użyć samo."),
}
