# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar III (porozumiewanie się), wersja B (5 lat)."""

KONSPEKTY_5_D3 = {
 ("B", 11): dict(
  nr="B3-11", tytul="Radio Przedszkole",
  podtytul="Mówienie zdaniami rozwiniętymi, zrozumiałymi także dla osób spoza rodziny",
  sfera="III POROZUMIEWANIE SIĘ · Wypowiedź (ICF d330 · PP 3.2)",
  czas="20 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko zbuduje zdanie rozwinięte (co najmniej 5 wyrazów) o zdarzeniu z sali, zrozumiałe dla słuchacza, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Wypowiada zdanie rozwinięte o wydarzeniu z przedszkola."),
    ("M","5 wyrazów · zrozumiałe dla dorosłego; 3 z 5 prób."),
    ("A","Mikrofon i rola reportera nadają wypowiedzi sens i widownię."),
    ("R","Zdania rozwinięte są warunkiem opowiadania i tłumaczenia myśli."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Próbka mowy · nagranie 5-minutowe raz w tygodniu.",
  pomoce=["mikrofon (zabawkowy lub dyktafon)","znaczek reportera","zdjęcia z wydarzeń w sali","tablica pytań reportera: kto, co, gdzie, kiedy","głośnik do odsłuchania nagrania"],
  metody=["rola reportera nadająca cel wypowiedzi","nagranie i wspólne odsłuchanie","rozszerzanie wypowiedzi pytaniem, nie poprawianiem","zdjęcie jako punkt zaczepienia"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — wręcza mikrofon: „Radio Przedszkole, mów, reporterze”.","D — bierze mikrofon i patrzy na zdjęcie wydarzenia."),
    ("N — pyta o fakt: „co się wydarzyło w ogrodzie?”.","D — mówi zdanie o wydarzeniu."),
    ("N — rozszerza pytaniem: „a kto był z tobą?”.","D — dodaje do zdania kolejne informacje."),
    ("N — nagrywa wypowiedź i odtwarza ją grupie.","D — słucha własnej wypowiedzi."),
    ("N — pyta grupę: „czy wszystko zrozumieliśmy?”.","D — uzupełnia to, co było niejasne.")],
  mod2=["zdanie 3-wyrazowe z pytaniem naprowadzającym","wypowiedź o obrazku zamiast o zdarzeniu","nagranie bez odsłuchania przy grupie"],
  mod3=["nazwanie wyrazu-etykiety, rozszerzane przez dorosłego","modelowanie zdania do powtórzenia","wypowiedź tylko do nauczyciela, nie do grupy","terapia logopedyczna równolegle"],
  mod1=["wypowiedź zrozumiała dla osoby spoza przedszkola","utrzymanie tematu przez 4 wypowiedzi","przeprowadzenie wywiadu z kolegą","relacja z wydarzenia sprzed kilku dni"],
  wskazowka="Odsłuchanie własnego nagrania robi więcej niż dziesięć poprawek — dziecko samo słyszy, czego zabrakło, i następnym razem mówi pełniej."),

 ("B", 12): dict(
  nr="B3-12", tytul="Kronika dnia",
  podtytul="Opowiadanie o zdarzeniach z przedszkola i własnych przeżyciach",
  sfera="III POROZUMIEWANIE SIĘ · Narracja (ICF d330 · PP 3.12)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko opowie o zdarzeniu w trzech zdaniach z zachowaniem kolejności, przy wsparciu historyjki obrazkowej, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Opowiada zdarzenie: początek – środek – koniec."),
    ("M","3 zdania w kolejności; 3 z 5 prób."),
    ("A","Karty najpierw–potem–na końcu porządkują wypowiedź."),
    ("R","Narracja porządkuje myślenie o czasie i przyczynie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta opowieści dnia · zapis wypowiedzi po sesji.",
  pomoce=["kronika grupy (album ze zdjęciami dnia)","karty: najpierw – potem – na końcu","zdjęcia z aparatu robione w ciągu dnia","pisak do podpisywania zdjęć","pieczątka kronikarza"],
  metody=["prowadzenie realnej kroniki grupy","trzy karty jako rusztowanie wypowiedzi","dyktowanie podpisu do zdjęcia","opowiadanie o wydarzeniu z tego samego dnia"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — pokazuje 3 zdjęcia z dzisiejszego dnia.","D — rozpoznaje wydarzenia i wybiera jedno."),
    ("N — rozkłada karty: najpierw – potem – na końcu.","D — układa zdjęcia w kolejności zdarzeń."),
    ("N — wskazuje pierwszą kartę: „od czego zaczęło się?”.","D — opowiada pierwsze zdanie."),
    ("N — prowadzi przez kolejne karty.","D — opowiada trzy zdania z zachowaniem kolejności."),
    ("N — zapisuje wypowiedź dziecka w kronice.","D — przybija pieczątkę kronikarza pod swoim wpisem.")],
  mod2=["dwa zdjęcia i dwie karty","opowiadanie o jednym wydarzeniu","podpowiedź pierwszego słowa każdego zdania"],
  mod3=["opowiedzenie o jednym zdjęciu","odpowiedzi na pytania zamiast opowiadania","zdjęcie z wyraźną, prostą akcją","wsparcie logopedy przy budowaniu zdań"],
  mod1=["opowiadanie z podaniem uczuć i przyczyny","relacja z wczorajszego dnia","opowiedzenie kroniki rodzicom przy odbiorze","zredagowanie podpisu do zdjęcia dla całej grupy"],
  wskazowka="Rób zdjęcia w ciągu dnia — pięciolatek opowiada nieporównanie chętniej o tym, co widzi na ekranie, niż o tym, co ma odtworzyć z pamięci."),

 ("B", 13): dict(
  nr="B3-13", tytul="Rozmowa przy stoliku",
  podtytul="Prowadzenie rozmowy: słuchanie, odpowiadanie, zadawanie pytań",
  sfera="III POROZUMIEWANIE SIĘ · Dialog (ICF d350 · PP 3.1·3.5)",
  czas="20 min", forma="para dzieci", cykl="3× w tygodniu",
  ter="Dziecko utrzyma wymianę zdań z rówieśnikiem przez dwie rundy (pytanie – odpowiedź – pytanie), nie przerywając rozmówcy, w 3 z 5 rozmów sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Odpowiada na pytanie kolegi i zadaje własne pytanie."),
    ("M","2 pełne rundy wymiany; 3 z 5 rozmów."),
    ("A","Przedmiot mówcy wyznacza, kto ma głos; karty pytań pomagają zacząć."),
    ("R","Dialog jest podstawą współpracy i relacji rówieśniczych."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Obserwacja rozmowy w parze · liczba rund wymiany.",
  pomoce=["przedmiot mówcy (kamyk, mikrofon)","karty startowe pytań („co lubisz…?”)","stolik do rozmów z dwoma krzesłami","piktogram: słucham – mówię","klepsydra 3-minutowa"],
  metody=["przedmiot mówcy regulujący kolejność","karty pytań jako punkt startu","modelowanie rozmowy przez dwóch dorosłych","podsumowanie: co dowiedziałem się o koledze"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i komunikację",
  przebieg=[
    ("N — z drugim dorosłym pokazuje rozmowę: pytanie i odpowiedź.","D — obserwuje, kto trzyma przedmiot mówcy."),
    ("N — sadza parę i wręcza kamyk pierwszemu dziecku.","D — zadaje pytanie z karty startowej."),
    ("N — pilnuje przekazania kamyka po odpowiedzi.","D — odpowiada i przekazuje kamyk koledze."),
    ("N — zachęca do własnego pytania, bez karty.","D — zadaje pytanie wymyślone samodzielnie."),
    ("N — pyta na koniec: „czego dowiedziałeś się o koledze?”.","D — mówi jedną rzecz o rozmówcy.")],
  mod2=["jedna runda wymiany","pytania wyłącznie z kart","rozmowa z dorosłym zamiast z rówieśnikiem"],
  mod3=["odpowiedź na pytanie skierowane indywidualnie","przypomnienie o kolejności przy każdej wymianie","rozmowa 2-zdaniowa","wsparcie w rozumieniu pytań"],
  mod1=["4 rundy wymiany z pytaniem doprecyzowującym","rozmowa bez przedmiotu mówcy","rozmowa w trójce","opowiedzenie grupie, czego dowiedziało się o koledze"],
  wskazowka="Kamyk w dłoni działa lepiej niż przypomnienie „nie przerywaj” — reguła staje się widoczna i dziecko samo pilnuje, kto ma teraz głos."),

 ("B", 14): dict(
  nr="B3-14", tytul="Rymowana kuchnia",
  podtytul="Recytowanie wierszy, tworzenie rymowanek i zagadek",
  sfera="III POROZUMIEWANIE SIĘ · Zabawy językiem (ICF d330 · PP 3.10·3.11)",
  czas="20 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko wyrecytuje czterowersową zwrotkę z pamięci przy podpowiedzi pierwszego słowa wersu, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Recytuje zwrotkę i dobiera rym do podanego wyrazu."),
    ("M","4 wersy · podpowiedź pierwszego słowa; 3 z 5 prób."),
    ("A","Wiersz z gestami i obrazkami do każdego wersu."),
    ("R","Rymy rozwijają słuch fonemowy potrzebny do nauki czytania."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta recytacji · rejestr rymów wymyślonych przez dziecko.",
  pomoce=["garnek „rymowana kuchnia” i drewniana łyżka","obrazki-składniki rymujące się parami","wiersze 4-wersowe z gestami","karty z parami rymów","fartuszki kucharskie"],
  metody=["gest przypisany każdemu wersowi","gotowanie rymów w garnku (zabawa)","podpowiedź pierwszego słowa wersu","tworzenie własnych par rymowych"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — wrzuca obrazek do garnka: „kotek… szukamy rymu!”.","D — podaje rymujący się wyraz: „płotek”."),
    ("N — recytuje wiersz z gestami, wers po wersie.","D — powtarza wersy razem z gestami."),
    ("N — podpowiada pierwsze słowo każdego wersu.","D — recytuje wers do końca samodzielnie."),
    ("N — miesza w garnku: „co się rymuje z domek?”.","D — tworzy własną parę rymów."),
    ("N — zaprasza do recytacji dla grupy.","D — recytuje zwrotkę przed kolegami.")],
  mod2=["dwa wersy zamiast czterech","recytacja wspólnie z nauczycielem","rym wybierany z dwóch podanych"],
  mod3=["powtórzenie 2-wersowego fragmentu za dorosłym","gest zamiast słowa w trudnych wersach","rozpoznanie rymu zamiast tworzenia","ćwiczenia słuchu fonemowego z logopedą"],
  mod1=["recytacja całego wiersza przed grupą","ułożenie własnej rymowanki 2-wersowej","wymyślenie zagadki rymowanej dla kolegów","dobieranie rymów do wyrazów wielosylabowych"],
  wskazowka="Gest przypisany wersowi jest najskuteczniejszą podpowiedzią — gdy zabraknie słowa, ręka sama je przypomina, bez wyręczania przez dorosłego."),

 ("B", 15): dict(
  nr="B3-15", tytul="Teatr bez słów",
  podtytul="Adekwatne używanie gestu, mimiki i ruchu w komunikacji",
  sfera="III POROZUMIEWANIE SIĘ · Komunikaty niewerbalne (ICF d335 · PP 3.2)",
  czas="20 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko dopasuje mimikę i gest do treści wypowiedzi w zabawie pantomimicznej tak, aby grupa odgadła emocję lub czynność, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Pokazuje emocję lub czynność samym gestem i mimiką."),
    ("M","Trafny odczyt przez grupę; 3 z 5 prób."),
    ("A","Karty do losowania z prostymi, znanymi sytuacjami."),
    ("R","Świadome użycie gestu wzmacnia zrozumiałość wypowiedzi."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zabawa pantomimiczna · trafność odczytu przez grupę.",
  pomoce=["karty pantomimy: emocje i czynności","kapelusz aktora","lustro w sali","fotografie min do porównania","kurtyna z materiału"],
  metody=["pantomima jako zabawa zespołowa","lustro do sprawdzania własnej miny","odczytywanie i nazywanie przez widownię","łączenie gestu ze słowem po odgadnięciu"],
  rodzaj="Zajęcia wspierające komunikację i rozwój emocjonalny",
  przebieg=[
    ("N — zakłada kapelusz aktora i pokazuje radość bez słów.","D — odgaduje i nazywa pokazaną emocję."),
    ("N — podaje kartę dziecku do zagrania.","D — pokazuje wylosowaną emocję lub czynność."),
    ("N — zachęca widownię: „jak myślicie, co to?”.","D — odgaduje pokazy kolegów."),
    ("N — proponuje lustro: „sprawdź swoją minę”.","D — poprawia mimikę, patrząc w lustro."),
    ("N — łączy gest ze słowem: „to była złość”.","D — nazywa emocję i pokazuje ją jeszcze raz.")],
  mod2=["karty tylko z emocjami podstawowymi","pokaz razem z nauczycielem","podpowiedź szeptem przed pokazem"],
  mod3=["naśladowanie miny pokazanej przez dorosłego","gest bez publiczności, w parze","wybór spośród dwóch min","praca nad rozpoznawaniem emocji"],
  mod1=["scenka 3-elementowa bez słów","pokaz emocji złożonej (zawstydzenie, duma)","reżyserowanie scenki dla kolegów","świadome wzmacnianie wypowiedzi gestem w rozmowie"],
  wskazowka="Publiczność jest tu narzędziem uczenia — dziecko poprawia gest nie na prośbę dorosłego, lecz dlatego, że koledzy nie odgadli, co pokazywało."),
}
