# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar I (uczenie się i stosowanie wiedzy), wersja C (6 lat)."""

KONSPEKTY_6_D1 = {
 ("C", 1): dict(
  nr="C1-01", tytul="Warsztat historyjek",
  podtytul="Objaśnianie kolejności zdarzeń i odpowiadanie na pytania o treść",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Kolejność zdarzeń (ICF d163 · PP 3.12)",
  czas="30 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko ułoży historyjkę z 4 obrazków we właściwej kolejności i opowie ją w trzech zdaniach, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Porządkuje obrazki i opowiada historię z zachowaniem następstwa."),
    ("M","4 obrazki · 3 zdania; 3 z 5 prób."),
    ("A","Taśma czasu z polami i słowa-łączniki na kartonikach."),
    ("R","Rozumienie następstwa zdarzeń jest warunkiem czytania ze zrozumieniem."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw historyjek obrazkowych · zapis wypowiedzi po sesji.",
  pomoce=["zestawy historyjek 4- i 5-obrazkowych","taśma czasu z ponumerowanymi polami","kartoniki: najpierw, potem, na końcu, dlatego","dyktafon","teczka autorskich historyjek"],
  metody=["układanie na taśmie czasu","słowa-łączniki jako rusztowanie wypowiedzi","opowiadanie nagrywane i odsłuchiwane","tworzenie własnych historyjek na końcu cyklu"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / przygotowanie do szkoły",
  przebieg=[
    ("N — rozsypuje 4 obrazki: „co wydarzyło się pierwsze?”.","D — ogląda obrazki i szuka początku historii."),
    ("N — wskazuje taśmę czasu z polami 1–4.","D — układa obrazki w kolejności na taśmie."),
    ("N — podaje kartoniki: najpierw – potem – na końcu.","D — opowiada historię, używając łączników."),
    ("N — pyta o przyczynę: „dlaczego tak się skończyło?”.","D — wyjaśnia związek przyczynowy zdaniem z „bo”."),
    ("N — nagrywa opowiadanie i odtwarza je grupie.","D — słucha nagrania i uzupełnia brakujące szczegóły.")],
  mod2=["historyjka 3-obrazkowa","łączniki wskazywane przez nauczyciela","opowiadanie w 2 zdaniach"],
  mod3=["układanie 3 obrazków według wzoru","opowiedzenie o pierwszym obrazku","odpowiedzi na pytania zamiast narracji","wsparcie logopedy przy budowaniu wypowiedzi"],
  mod1=["historyjka 5-obrazkowa opowiedziana w 6 zdaniach","wymyślenie własnej historyjki i narysowanie jej","opowiedzenie historii z perspektywy innego bohatera","zapisanie tytułu własnej historyjki"],
  wskazowka="Kartoniki z łącznikami są ważniejsze niż same obrazki — to one zamieniają wyliczanie scen w opowiadanie z następstwem czasu i przyczyny."),

 ("C", 2): dict(
  nr="C1-02", tytul="Sylabowa czytelnia",
  podtytul="Próby samodzielnego czytania wyrazów i krótkich tekstów",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Czytanie (ICF d140 · PP 3.17)",
  czas="25 min", forma="mała grupa (3–4 dzieci)", cykl="codziennie",
  ter="Dziecko przeczyta 5 wyrazów dwusylabowych metodą sylabową i dopasuje je do obrazków, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odczytuje wyrazy sylabami i łączy je ze znaczeniem."),
    ("M","5 wyrazów dwusylabowych; 3 z 5 prób."),
    ("A","Wyrazy z sylabami w dwóch kolorach; obrazki do dopasowania."),
    ("R","Czytanie ze zrozumieniem to główny cel roku przygotowania szkolnego."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty wyrazów i zdań · liczba poprawnych odczytów.",
  pomoce=["karty wyrazów z sylabami w dwóch kolorach","obrazki do dopasowania","suwak sylabowy","kącik czytelniczy z poduszkami","legitymacja czytelnika ze stemplami"],
  metody=["sylaby wyróżnione kolorem","suwak odsłaniający sylaby po kolei","dopasowanie do obrazka jako kontrola rozumienia","legitymacja czytelnika ze stemplem za każdy tekst"],
  rodzaj="Zajęcia wspierające przygotowanie do nauki czytania",
  przebieg=[
    ("N — pokazuje suwak: „odsłaniamy sylaba po sylabie”.","D — odczytuje pierwszą sylabę, potem drugą."),
    ("N — prosi o połączenie sylab w wyraz.","D — scala sylaby i wypowiada cały wyraz."),
    ("N — rozkłada obrazki: „gdzie jest ten wyraz?”.","D — dopasowuje wyraz do właściwego obrazka."),
    ("N — podaje krótkie zdanie z tych wyrazów.","D — czyta zdanie i wykonuje zapisane polecenie."),
    ("N — przybija stempel w legitymacji czytelnika.","D — zaznacza przeczytany tekst w swojej legitymacji.")],
  mod2=["3 wyrazy zamiast 5","sylaby odczytywane wspólnie z nauczycielem","wyrazy z otwartych sylab (ma-ma, ko-tek)"],
  mod3=["synteza wyrazu z sylab podanych przez dorosłego","rozpoznawanie sylab bez scalania","wyrazy trzyliterowe","ćwiczenia słuchu fonemowego z logopedą"],
  mod1=["czytanie krótkiego zdania ze zrozumieniem i wykonanie polecenia","czytanie tekstu 3-zdaniowego","odszukanie w tekście odpowiedzi na pytanie","przeczytanie tekstu młodszym dzieciom"],
  wskazowka="Dopasowanie do obrazka jest testem rozumienia — dziecko, które odczyta wyraz, ale nie wskaże obrazka, jeszcze nie czyta, tylko dekoduje."),

 ("C", 3): dict(
  nr="C1-03", tytul="Litery w liniaturze",
  podtytul="Kreślenie kształtów literopodobnych i planowanie ruchu przed zapisem",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Pisanie (ICF d145 · PP 3.15·3.16)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="codziennie",
  ter="Dziecko napisze 5 liter w liniaturze według wzoru, zachowując kierunek kreślenia i proporcje, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Kreśli litery we właściwym kierunku, mieszcząc się w liniaturze."),
    ("M","5 liter · kierunek i proporcje; 3 z 5 prób."),
    ("A","Wzory ze strzałkami startu; liniatura poszerzona."),
    ("R","Technika pisania decyduje o tempie i czytelności w klasie pierwszej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta pracy grafomotorycznej · ocena poprawności kreślenia.",
  pomoce=["wzory liter ze strzałkami kierunku","liniatura poszerzona i standardowa","tacka z piaskiem do kreślenia palcem","kredki krótkie i ołówki trójkątne","folia do pisania na wzorze"],
  metody=["kreślenie palcem w piasku przed zapisem","planowanie ruchu: pokazujemy palcem w powietrzu","strzałka startu przy każdej literze","porównanie własnej litery ze wzorem"],
  rodzaj="Zajęcia wspierające przygotowanie do nauki pisania",
  przebieg=[
    ("N — pokazuje literę i kreśli ją palcem w powietrzu.","D — powtarza ruch w powietrzu, potem w piasku."),
    ("N — wskazuje strzałkę startu na wzorze.","D — nazywa, gdzie zaczyna i w którą stronę prowadzi."),
    ("N — podaje folię nałożoną na wzór.","D — pisze literę po wzorze na folii."),
    ("N — podaje liniaturę poszerzoną.","D — pisze literę samodzielnie w liniaturze."),
    ("N — prosi o porównanie ze wzorem.","D — wskazuje swoją najlepszą literę i uzasadnia wybór.")],
  mod2=["3 litery zamiast 5","pisanie po śladzie","liniatura bardzo poszerzona"],
  mod3=["kreślenie szlaczków literopodobnych po śladzie","kreślenie palcem w piasku bez zapisu","litera duża, na całej kartce","ocena napięcia mięśniowego i chwytu"],
  mod1=["napisanie imienia i 5 wyrazów w liniaturze standardowej","planowanie ruchu przed zapisem bez wzoru","zapisanie krótkiego zdania","pomoc koledze w znalezieniu punktu startu litery"],
  wskazowka="Palec w piasku przed ołówkiem w liniaturze — ruch zapamiętany całym ramieniem przenosi się na papier, a wyuczony od razu na małej kratce zwykle nie."),

 ("C", 4): dict(
  nr="C1-04", tytul="Kantorek liczb",
  podtytul="Przeliczanie, odczytywanie zapisu cyfrowego, dodawanie i odejmowanie",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Liczenie (ICF d150 · PP 4.6·4.9)",
  czas="25 min", forma="para dzieci", cykl="3× w tygodniu",
  ter="Dziecko odczyta cyfry 1–10 i wykona dodawanie w zakresie 5 na konkretach, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Odczytuje cyfry i oblicza sumy na konkretach."),
    ("M","Cyfry 1–10 · dodawanie w zakresie 5; 3 z 5 prób."),
    ("A","Liczmany, karty cyfr i sytuacja zakupu nadają sens działaniom."),
    ("R","Sprawność rachunkowa to bezpośrednie przygotowanie do klasy pierwszej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zadania użytkowe z liczbami · karta wyników.",
  pomoce=["monety-żetony i portfele","karty cyfr 1–10","cenniki z kropkami i cyframi","liczmany: kasztany, guziki","kantorek z ladą i kasą"],
  metody=["działania w sytuacji zakupu","konkret przed zapisem cyfrowym","zapis działania po wykonaniu na liczmanach","zamiana ról kupujący–sprzedawca"],
  rodzaj="Zajęcia wspierające edukację matematyczną",
  przebieg=[
    ("N — otwiera kantorek i rozdaje portfele z żetonami.","D — liczy swoje żetony i podaje wynik."),
    ("N — pokazuje cennik z cyframi.","D — odczytuje cenę i odlicza tyle żetonów."),
    ("N — proponuje zakup dwóch rzeczy.","D — dokłada żetony i podaje sumę."),
    ("N — zapisuje działanie: 3 + 2 = 5.","D — odczytuje zapis i sprawdza go na liczmanach."),
    ("N — zamienia role przy ladzie.","D — jako sprzedawca sprawdza rachunek kolegi.")],
  mod2=["dodawanie w zakresie 3","cennik z kropkami zamiast cyfr","liczmany zawsze dostępne"],
  mod3=["przeliczanie do 5 z dotykaniem elementów","dopasowanie cyfry do zbioru","działania wyłącznie na konkretach","sprawdzenie rozumienia pojęcia liczby"],
  mod1=["dodawanie i odejmowanie w zakresie 10 z uzasadnieniem wyniku","rozwiązanie zadania z treścią","zapis własnego działania","sprawdzenie reszty przy zakupie"],
  wskazowka="Zapisuj działanie dopiero po wykonaniu go na liczmanach — cyfra ma być podsumowaniem czynności, nie poleceniem do odgadnięcia."),

 ("C", 5): dict(
  nr="C1-05", tytul="Laboratorium hipotez",
  podtytul="Eksperymentowanie, szacowanie, ważenie, mierzenie i sprawdzanie przypuszczeń",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Doświadczanie (ICF d175 · PP 4.8·5.3)",
  czas="30 min", forma="zespoły 3-osobowe", cykl="2× w tygodniu",
  ter="Dziecko uszereguje 4 przedmioty według długości lub ciężaru i sprawdzi wynik miarką albo wagą, w 3 z 5 prób sesji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Szereguje przedmioty i weryfikuje ustalenie pomiarem."),
    ("M","4 przedmioty · sprawdzenie pomiarem; 3 z 5 prób."),
    ("A","Waga szalkowa i miarka dostępne; karta doświadczenia prowadzi krok po kroku."),
    ("R","Stawianie i sprawdzanie hipotez to istota myślenia naukowego."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta doświadczenia · zapis hipotezy i wyniku.",
  pomoce=["waga szalkowa","miarki, sznurki, klocki jako miary","przedmioty do porównywania","karty doświadczenia: przypuszczam – sprawdzam – wynik","fartuchy laboratoryjne"],
  metody=["hipoteza przed pomiarem","pomiar jako rozstrzygnięcie sporu","karta doświadczenia jako zapis pracy","porównanie przypuszczeń w zespole"],
  rodzaj="Zajęcia wspierające edukację matematyczno-przyrodniczą",
  przebieg=[
    ("N — rozdaje fartuchy i przedmioty do zbadania.","D — ogląda przedmioty, waży je w dłoniach."),
    ("N — pyta: „który będzie najcięższy? co przypuszczasz?”.","D — stawia hipotezę i zaznacza ją na karcie."),
    ("N — udostępnia wagę szalkową.","D — sprawdza przypuszczenie, ważąc przedmioty."),
    ("N — prosi o uszeregowanie od najlżejszego.","D — układa przedmioty w kolejności i sprawdza."),
    ("N — pyta: „czy przypuszczenie się potwierdziło?”.","D — porównuje hipotezę z wynikiem i zapisuje wniosek.")],
  mod2=["porównywanie 2 przedmiotów","hipoteza wybierana z dwóch możliwości","pomiar razem z dorosłym"],
  mod3=["porównanie ciężaru dwóch wyraźnie różnych przedmiotów","wskazanie cięższego bez szeregowania","pomiar wykonany przez dorosłego","wsparcie w rozumieniu pojęć porównawczych"],
  mod1=["postawienie hipotezy słownie i uzasadnienie jej","pomiar niestandardowy i standardowy tego samego przedmiotu","zaprojektowanie własnego doświadczenia","przedstawienie wyników grupie"],
  wskazowka="Zapisz hipotezę przed pomiarem — bez tego doświadczenie zamienia się w zabawę wagą, a dziecko nigdy nie przeżywa momentu, w którym rzeczywistość zaskakuje."),
}
