# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar II (ogólne zadania i wymagania), wersja B (5 lat)."""

KONSPEKTY_5_D2 = {
 ("B", 6): dict(
  nr="B2-06", tytul="Instrukcja mistrza budowy",
  podtytul="Wykonywanie zadania według instrukcji od początku do końca",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Praca z instrukcją (ICF d210 · PP 7.1)",
  czas="25 min", forma="para dzieci", cykl="3× w tygodniu",
  ter="Dziecko wykona zadanie trzyetapowe korzystając z instrukcji obrazkowej, bez dodatkowych poleceń dorosłego, w 3 z 5 zadań sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Realizuje kolejne etapy instrukcji i zgłasza ukończenie."),
    ("M","3 etapy bez dodatkowych poleceń; 3 z 5 zadań."),
    ("A","Instrukcja obrazkowa leży przy stanowisku, etapy ponumerowane."),
    ("R","Praca z instrukcją to bezpośrednie przygotowanie do roli ucznia."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta instrukcji · liczba wykonanych etapów po każdym zadaniu.",
  pomoce=["instrukcje obrazkowe 3-etapowe (budowla, praca plastyczna, eksperyment)","kaski i identyfikatory „mistrz budowy”","materiał do zadań w pojemnikach","tablica ukończonych zleceń"],
  metody=["instrukcja wizualna zamiast polecenia słownego","praca w parze z podziałem etapów","zgłaszanie ukończenia zamiast oceny dorosłego","porównanie efektu z obrazkiem docelowym"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / pomoc p-p",
  przebieg=[
    ("N — rozdaje kaski i zlecenia: „mistrzowie, oto instrukcja”.","D — ogląda instrukcję, nazywa trzy etapy."),
    ("N — wskazuje materiał i odsuwa się od stanowiska.","D — realizuje pierwszy etap według obrazka."),
    ("N — milczy przy drugim etapie, obserwuje.","D — przechodzi do kolejnego etapu bez polecenia."),
    ("N — przy zawahaniu wskazuje instrukcję, nie podpowiada.","D — wraca do obrazka i kontynuuje pracę."),
    ("N — zaprasza do porównania efektu z instrukcją.","D — sprawdza zgodność i wiesza zlecenie na tablicy.")],
  mod2=["instrukcja 2-etapowa","potwierdzanie każdego etapu przez dorosłego","praca z dorosłym jako partnerem"],
  mod3=["polecenia podawane po jednym, z pokazem","prowadzenie przy pierwszym etapie","zadanie skrócone do jednej czynności","sprawdzenie rozumienia symboli na instrukcji"],
  mod1=["instrukcja 4-etapowa podana raz, słownie","sprawdzenie kompletności przed zgłoszeniem końca","napisanie instrukcji dla kolegi (rysunkiem)","praca według instrukcji w zespole 3-osobowym"],
  wskazowka="Wskazuj instrukcję zamiast podpowiadać — celem nie jest ukończone zadanie, lecz nawyk sięgania po instrukcję, który zostanie z dzieckiem w szkole."),

 ("B", 7): dict(
  nr="B2-07", tytul="Most między zajęciami",
  podtytul="Płynne przechodzenie między aktywnościami dnia",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Przejścia (ICF d230 · PP WSR·Zad.2)",
  czas="5 min przy każdym przejściu", forma="cała grupa", cykl="codziennie",
  ter="Dziecko przejdzie do kolejnej aktywności po sygnale grupowym i jednym przypomnieniu, w czasie do 1 minuty, w 3 z 5 przejść dnia, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Kończy aktywność i podejmuje kolejną po sygnale."),
    ("M","Do 1 minuty · 1 przypomnienie; 3 z 5 przejść."),
    ("A","Plan dnia z ruchomym wskaźnikiem; zapowiedź 2 minuty wcześniej."),
    ("R","Sprawne przejścia zwiększają czas przeznaczony na uczenie się."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Rejestr przejść · pomiar czasu reakcji po sygnale.",
  pomoce=["plan dnia z ruchomym wskaźnikiem","minutnik wizualny","rytmiczna wyliczanka porządkowa","karta „co robię, gdy skończę”"],
  metody=["zapowiedź z wyprzedzeniem","stały sygnał dla całej grupy","zadanie pomostowe (co robię, gdy skończę)","dziecko jako strażnik planu"],
  rodzaj="Wsparcie organizacji dnia / pomoc p-p",
  przebieg=[
    ("N — rano omawia plan dnia z dziećmi.","D — wskazuje kolejne punkty planu."),
    ("N — na 2 minuty przed końcem uruchamia minutnik.","D — zaczyna porządkować swoje stanowisko."),
    ("N — daje sygnał i przesuwa wskaźnik planu.","D — kończy aktywność i przechodzi dalej."),
    ("N — wskazuje kartę „co robię, gdy skończę”.","D — wykonuje zadanie pomostowe, czekając na grupę."),
    ("N — powierza dziecku rolę strażnika planu.","D — przesuwa wskaźnik i informuje grupę o zmianie.")],
  mod2=["uprzedzenie indywidualne obok dziecka","zdjęcie kolejnej aktywności podane do ręki","dziecko przechodzi jako pierwsze"],
  mod3=["prowadzenie za rękę przy przejściu","minutnik 3-minutowy i podwójna zapowiedź","możliwość zabrania przedmiotu z poprzedniej aktywności","analiza ABC przy nasilonych protestach"],
  mod1=["przejście bez przypomnienia, także gdy przerywa ulubioną zabawę","radzenie sobie ze zmianą planu","informowanie grupy o kolejnym punkcie","planowanie własnej pracy tak, by zdążyć przed sygnałem"],
  wskazowka="Zadanie pomostowe likwiduje najtrudniejszy moment — dziecko, które wie, co robić po skończeniu, nie zaczyna nowej zabawy tuż przed przejściem."),

 ("B", 8): dict(
  nr="B2-08", tytul="Kolejka po skarb",
  podtytul="Czekanie na swoją kolej i panowanie nad emocją odroczenia",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Odraczanie (ICF d240 · PP 2.9·2.12)",
  czas="20 min", forma="mała grupa (4–5 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko poczeka na swoją kolej 2 minuty w zabawie z regułą, korzystając z wizualnej kolejki, bez zachowania zakłócającego, w 3 z 5 sytuacji sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Czeka na swoją turę i podejmuje działanie we właściwym momencie."),
    ("M","2 minuty oczekiwania; 3 z 5 sytuacji."),
    ("A","Wizualna kolejka ze zdjęciami pokazuje, kto i kiedy."),
    ("R","Czekanie na kolej to warunek udziału w grach i pracy zespołowej."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zabawa z regułą · rejestr zachowań w kolejce po sesji.",
  pomoce=["tablica kolejki ze zdjęciami dzieci","klepsydra 2-minutowa","gra planszowa wielkoformatowa","skrzynia ze skarbem (nagroda zespołowa)","karty strategii czekania"],
  metody=["wizualizacja kolejności","strategia czekania podana wprost (liczę, oddycham, kibicuję)","krótkie tury z szybkim powrotem","nagroda zespołowa, nie indywidualna"],
  rodzaj="Zajęcia wspierające samoregulację / pomoc p-p",
  przebieg=[
    ("N — układa zdjęcia w kolejce: „tak będziemy szli po skarb”.","D — odnajduje swoje zdjęcie i wie, który jest."),
    ("N — pokazuje karty strategii: „co robimy, czekając?”.","D — wybiera strategię: kibicowanie koledze."),
    ("N — prowadzi grę, przesuwa znacznik kolejki.","D — czeka, obserwując grę i kibicując."),
    ("N — nazywa emocję czekania: „trudno czekać, prawda?”.","D — nazywa swoje niezadowolenie słowem."),
    ("N — otwiera skrzynię, gdy wszyscy mieli turę.","D — cieszy się wspólnym skarbem z grupą.")],
  mod2=["oczekiwanie 1 minuta","dziecko drugie w kolejce","zadanie do wykonania podczas czekania"],
  mod3=["oczekiwanie 30 sekund z przedmiotem-znacznikiem","dorosły obok przez cały czas czekania","kolejka 2-osobowa","wzmocnienie za każde udane czekanie"],
  mod1=["czekanie do końca zabawy grupowej","nazwanie emocji i wybór strategii samodzielnie","pilnowanie kolejki dla grupy","akceptacja przegranej w grze z regułą"],
  wskazowka="Daj dziecku zajęcie na czas czekania — kibicowanie koledze zamienia puste oczekiwanie w rolę, a rola jest znośna nawet dla niecierpliwych."),

 ("B", 9): dict(
  nr="B2-09", tytul="Moje stanowisko pracy",
  podtytul="Organizowanie miejsca zabawy i pracy oraz sprzątanie po aktywności",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Organizacja pracy (ICF d220 · PP 2.5)",
  czas="20 min", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko przygotuje stanowisko według listy obrazkowej i uporządkuje je po skończonej pracy, w 3 z 5 zajęć, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Kompletuje materiały przed pracą i porządkuje je po niej."),
    ("M","Pełna lista materiałów; 3 z 5 zajęć."),
    ("A","Lista obrazkowa materiałów i zdjęcie gotowego stanowiska."),
    ("R","Organizacja pracy to kompetencja przenoszona wprost do szkoły."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Lista obrazkowa stanowiska · zdjęcie miejsca po pracy.",
  pomoce=["listy obrazkowe materiałów do zadań","zdjęcie wzorcowe gotowego stanowiska","pojemniki z etykietami","tacki do pracy indywidualnej","karta samooceny porządku"],
  metody=["lista materiałów przed rozpoczęciem","zdjęcie wzorcowe jako kryterium","tacka wyznaczająca granice stanowiska","samoocena porządku po pracy"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / pomoc p-p",
  przebieg=[
    ("N — podaje listę obrazkową: „to będzie potrzebne”.","D — kompletuje materiały z pojemników."),
    ("N — pokazuje zdjęcie gotowego stanowiska.","D — układa materiały na tacce jak na zdjęciu."),
    ("N — zaprasza do pracy i odsuwa się.","D — wykonuje zadanie na przygotowanym stanowisku."),
    ("N — po pracy wskazuje listę: „wszystko wraca na miejsce”.","D — odkłada materiały do właściwych pojemników."),
    ("N — prosi o samoocenę: „czy stanowisko jest gotowe?”.","D — porównuje ze zdjęciem i zaznacza na karcie.")],
  mod2=["lista 2 materiałów","dorosły przynosi połowę materiałów","zdjęcie wzorcowe leżące na stanowisku"],
  mod3=["materiały wskazywane kolejno przez dorosłego","porządkowanie razem z dorosłym","jeden materiał do przyniesienia","skrócone zadanie"],
  mod1=["samodzielne zaplanowanie, co będzie potrzebne","przygotowanie stanowiska dla całego stolika","uporządkowanie bez przypomnienia","zaproponowanie lepszego ustawienia materiałów"],
  wskazowka="Zdjęcie gotowego stanowiska zastępuje ciąg poleceń — dziecko porównuje obraz z rzeczywistością samo, a dorosły przestaje być listą kontrolną."),

 ("B", 10): dict(
  nr="B2-10", tytul="Najpierw próbuję, potem proszę",
  podtytul="Szukanie wsparcia i korzystanie z podpowiedzi dorosłego",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Proszenie o pomoc (ICF d240 · PP 2.11)",
  czas="20 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko poprosi o pomoc słownie po podjęciu jednej samodzielnej próby rozwiązania trudności, w 3 z 5 sytuacji sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Próbuje sam, a następnie formułuje prośbę o pomoc."),
    ("M","1 próba przed prośbą; 3 z 5 sytuacji."),
    ("A","Zasada „najpierw próbuję” widoczna na plakacie; dorosły odczekuje."),
    ("R","Równowaga między samodzielnością a proszeniem chroni przed bezradnością."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zadania z celową trudnością · rejestr prób i próśb.",
  pomoce=["plakat zasady: próbuję → proszę","zadania z celową trudnością (brakujący element, ciasne zamknięcie)","kartonik „potrzebuję pomocy”","zdania-wzory: „nie mogę…, pomożesz?”"],
  metody=["zadania z zaplanowaną trudnością","odczekanie dorosłego (10 sekund)","modelowanie zdania proszącego","docenianie próby, nie tylko sukcesu"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / pomoc p-p",
  przebieg=[
    ("N — pokazuje plakat: „najpierw próbuję, potem proszę”.","D — powtarza zasadę własnymi słowami."),
    ("N — daje zadanie z brakującym elementem.","D — zauważa trudność, podejmuje próbę."),
    ("N — odczekuje 10 sekund w milczeniu.","D — próbuje drugiego sposobu lub prosi o pomoc."),
    ("N — modeluje zdanie: „nie mogę znaleźć, pomożesz?”.","D — formułuje prośbę pełnym zdaniem."),
    ("N — udziela podpowiedzi, nie robi za dziecko.","D — korzysta z podpowiedzi i kończy zadanie.")],
  mod2=["kartonik „pomoc” zamiast zdania","odczekanie skrócone do 5 sekund","trudność bardzo widoczna"],
  mod3=["prośba gestem lub symbolem","dorosły blisko, reaguje przy pierwszym sygnale","wzmocnienie każdej próby, także nieudanej","powiązanie z pracą nad komunikacją"],
  mod1=["nazwanie problemu i poproszenie o konkretną pomoc","poproszenie najpierw kolegi, potem dorosłego","wykorzystanie podpowiedzi do samodzielnego dokończenia","udzielenie pomocy koledze bez wyręczania go"],
  wskazowka="Milcz przez pełne dziesięć sekund — to najtrudniejszy element tych zajęć dla dorosłego i najważniejszy dla dziecka, które właśnie odkrywa własną skuteczność."),
}
