# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IX (życie społeczne, lokalne i obywatelskie), wersja C (6 lat)."""

KONSPEKTY_6_D9 = {
 ("C", 40): dict(
  nr="C9-40", tytul="Kręgi przynależności",
  podtytul="Odczuwanie i wyjaśnianie przynależności do rodziny, grupy i społeczności",
  sfera="IX ŻYCIE SPOŁECZNE · Przynależność (ICF d910 · PP 1.16)",
  czas="30 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko opowie, kto należy do jego rodziny i grupy, oraz poda nazwę swojej miejscowości, w 3 z 5 rozmów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa członków rodziny, grupę i miejscowość."),
    ("M","3 kręgi przynależności; 3 z 5 rozmów."),
    ("A","Plansza koncentrycznych kręgów: ja – rodzina – grupa – miasto."),
    ("R","Poczucie przynależności buduje tożsamość i bezpieczeństwo."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Rozmowa kierowana · karta wypowiedzi.",
  pomoce=["plansza kręgów przynależności","zdjęcia rodzin dzieci","mapa miejscowości","zdjęcia znanych miejsc w okolicy","album grupy"],
  metody=["kręgi koncentryczne jako model przynależności","zdjęcia własnej rodziny","rozpoznawanie miejsc w okolicy","opowiadanie o swoim miejscu"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i obywatelskie",
  przebieg=[
    ("N — pokazuje planszę kręgów: ja w środku.","D — umieszcza swoje zdjęcie w środku planszy."),
    ("N — pyta o rodzinę: „kto jest w twoim kręgu?”.","D — wymienia członków rodziny, pokazuje zdjęcie."),
    ("N — przechodzi do kręgu grupy.","D — nazywa swoją grupę i wymienia kolegów."),
    ("N — rozkłada mapę miejscowości.","D — podaje nazwę miejscowości, wskazuje znane miejsca."),
    ("N — prosi o opowiedzenie o swoim miejscu na świecie.","D — opowiada o rodzinie, grupie i mieście.")],
  mod2=["dwa kręgi: rodzina i grupa","wypowiedź z podpowiedzią zdjęciem","nazwanie miejscowości z pomocą"],
  mod3=["wskazanie członków rodziny na zdjęciu","nazwanie swojej grupy","jeden krąg przynależności","wsparcie komunikacyjne"],
  mod1=["wyjaśnienie, czym jest rodzina, grupa i ojczyzna","podanie adresu i opisanie okolicy","opowiedzenie o tradycji rodzinnej","narysowanie mapy swojej drogi do przedszkola"],
  wskazowka="Zacznij od zdjęcia dziecka w środku planszy — abstrakcyjne pojęcie przynależności staje się zrozumiałe, gdy dziecko widzi siebie w centrum kręgów."),

 ("C", 41): dict(
  nr="C9-41", tytul="Polska na mapie",
  podtytul="Nazwa kraju i stolicy, symbole narodowe i pielęgnowanie tradycji",
  sfera="IX ŻYCIE SPOŁECZNE · Tożsamość narodowa (ICF d910 · PP 1.17·1.19)",
  czas="30 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko poda nazwę kraju i stolicy oraz rozpozna godło i flagę, w 3 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Nazywa kraj, stolicę i rozpoznaje symbole narodowe."),
    ("M","Kraj, stolica, godło, flaga; 3 z 5 prób."),
    ("A","Mapa Polski, symbole w kąciku patriotycznym, hymn na nagraniu."),
    ("R","Tożsamość narodowa jest elementem podstawy programowej i wychowania."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta wiedzy o Polsce · obserwacja podczas uroczystości.",
  pomoce=["mapa Polski","godło i flaga","nagranie hymnu","kącik patriotyczny","zdjęcia miast i regionów","materiały do wykonania kotylionu"],
  metody=["kącik patriotyczny dostępny na co dzień","hymn słuchany w postawie zasadniczej","tradycje regionalne i rodzinne","wykonanie symboli własnoręcznie"],
  rodzaj="Edukacja patriotyczna i obywatelska",
  przebieg=[
    ("N — rozkłada mapę Polski i wskazuje miejscowość.","D — odnajduje swoją miejscowość na mapie."),
    ("N — pokazuje godło i flagę, nazywa je.","D — rozpoznaje symbole i nazywa kolory flagi."),
    ("N — wskazuje Warszawę: „to nasza stolica”.","D — podaje nazwę kraju i stolicy."),
    ("N — włącza hymn i pokazuje postawę.","D — stoi w postawie zasadniczej podczas hymnu."),
    ("N — proponuje wykonanie kotyliona.","D — wykonuje kotylion w barwach narodowych.")],
  mod2=["nazwa kraju i rozpoznanie flagi","stolica z podpowiedzią","krótszy fragment hymnu"],
  mod3=["rozpoznanie flagi spośród dwóch","nazwanie barw narodowych","udział w wykonaniu kotyliona","krótki udział w uroczystości"],
  mod1=["nazwa kraju, stolicy, rozpoznanie symboli i właściwa postawa podczas hymnu","wymienienie tradycji narodowej","wskazanie kilku miast na mapie","opowiedzenie o święcie narodowym"],
  wskazowka="Kącik patriotyczny dostępny codziennie działa lepiej niż akademia raz w roku — symbole poznaje się przez obecność, nie przez uroczystość."),

 ("C", 42): dict(
  nr="C9-42", tytul="Moje dane, moje bezpieczeństwo",
  podtytul="Udzielanie informacji o sobie i wiedza, komu można je przekazać",
  sfera="IX ŻYCIE SPOŁECZNE · Dane osobowe (ICF d910 · PP 1.1)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko poda imię, nazwisko i miejscowość zamieszkania oraz wskaże, kto jest osobą zaufaną, w 3 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Podaje swoje dane i rozpoznaje osoby uprawnione do ich otrzymania."),
    ("M","Dane + wskazanie osób zaufanych; 3 z 5 prób."),
    ("A","Legitymacja przedszkolaka; scenki bezpieczeństwa."),
    ("R","Znajomość danych i zasad ich podawania chroni dziecko."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Scenki bezpieczeństwa · karta danych.",
  pomoce=["legitymacje przedszkolaka do wypełnienia","zdjęcia osób zaufanych","scenki: nieznajomy pyta o dane","numer alarmowy 112 na plakacie","opaski z danymi na wycieczki"],
  metody=["legitymacja wypełniana samodzielnie","scenki z bezpiecznym ćwiczeniem odmowy","rozróżnienie osób zaufanych i nieznajomych","nauka numeru alarmowego"],
  rodzaj="Zajęcia wspierające bezpieczeństwo osobiste",
  przebieg=[
    ("N — rozdaje legitymacje przedszkolaka.","D — podaje swoje dane do wpisania."),
    ("N — pyta o miejscowość i adres.","D — podaje miejscowość zamieszkania."),
    ("N — odgrywa scenkę: nieznajomy pyta o adres.","D — ćwiczy odmowę i odejście do dorosłego."),
    ("N — pokazuje zdjęcia osób zaufanych.","D — wskazuje, komu może podać swoje dane."),
    ("N — uczy numeru alarmowego 112.","D — powtarza numer i mówi, kiedy się go używa.")],
  mod2=["imię, nazwisko i miejscowość bez adresu","wskazanie osób zaufanych z podpowiedzią","scenka z pomocą dorosłego"],
  mod3=["podanie imienia i nazwiska","rozpoznanie znanego dorosłego","opaska z danymi na wycieczkach","wsparcie komunikacyjne"],
  mod1=["podanie pełnych danych wyłącznie osobie uprawnionej i uzasadnienie zasady","zapamiętanie numeru telefonu rodzica","opisanie drogi do domu","wyjaśnienie zasady młodszym dzieciom"],
  wskazowka="Ćwicz odmowę w scenkach, nie w pogadance — dziecko musi usłyszeć własny głos mówiący „nie podam”, zanim znajdzie się w prawdziwej sytuacji."),

 ("C", 43): dict(
  nr="C9-43", tytul="Strażnicy planety",
  podtytul="Korzystanie z dóbr przyrody z poszanowaniem zasad i segregacja odpadów",
  sfera="IX ŻYCIE SPOŁECZNE · Ekologia (ICF d920 · PP 5.11·5.12)",
  czas="30 min", forma="zespoły 3-osobowe", cykl="2× w tygodniu",
  ter="Dziecko posegreguje pięć odpadów do trzech pojemników samodzielnie, w 3 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Przyporządkowuje odpady do właściwych frakcji."),
    ("M","5 odpadów · 3 pojemniki; 3 z 5 prób."),
    ("A","Pojemniki w kolorach z piktogramami; odpady czyste i bezpieczne."),
    ("R","Nawyki ekologiczne kształtowane w przedszkolu zostają na lata."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kącik ekologiczny · rejestr zachowań proekologicznych.",
  pomoce=["pojemniki w kolorach frakcji z piktogramami","czyste odpady do sortowania","plakat obiegu wody i prądu","liczniki zużycia wody","odznaki strażnika planety"],
  metody=["segregacja na realnych, czystych odpadach","eksperyment: ile wody zużywamy","codzienne nawyki: gaszenie światła, zakręcanie wody","rola strażnika planety"],
  rodzaj="Edukacja przyrodnicza i obywatelska",
  przebieg=[
    ("N — przedstawia pojemniki i piktogramy frakcji.","D — nazywa, co wrzucamy do każdego pojemnika."),
    ("N — rozdaje zestawy odpadów do segregacji.","D — segreguje pięć odpadów do właściwych pojemników."),
    ("N — pokazuje licznik zużycia wody.","D — obserwuje, ile wody leci przy myciu rąk."),
    ("N — omawia zasady oszczędzania.","D — proponuje sposoby oszczędzania wody i prądu."),
    ("N — wręcza odznaki strażników planety.","D — pilnuje zakręcania wody i gaszenia światła.")],
  mod2=["segregacja 3 odpadów do 2 pojemników","piktogram wskazywany przy każdym odpadzie","odpady wyraźnie różne"],
  mod3=["wrzucenie odpadu do pojemnika po wskazaniu koloru","jeden rodzaj odpadu","segregacja z dorosłym","wsparcie w rozumieniu kategorii"],
  mod1=["segregacja z uzasadnieniem i dbałość o zasoby z własnej inicjatywy","wyjaśnienie, po co segregujemy","zaproponowanie akcji ekologicznej dla grupy","policzenie, ile wody zaoszczędzono"],
  wskazowka="Licznik pokazujący litry zużytej wody robi wrażenie, jakiego nie zrobi żadna pogadanka — abstrakcyjne oszczędzanie staje się konkretną liczbą."),

 ("C", 44): dict(
  nr="C9-44", tytul="Kim będę, kim jestem",
  podtytul="Charakteryzowanie pracy w różnych zawodach i przyjmowanie ról społecznych",
  sfera="IX ŻYCIE SPOŁECZNE · Zawody i role (ICF d910 · PP 1.13·1.12)",
  czas="30 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko opowie, czym zajmuje się osoba w trzech wybranych zawodach, i odegra jedną z ról w zabawie, w 3 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Opisuje pracę w zawodach i odgrywa wybraną rolę."),
    ("M","3 zawody · 1 rola odegrana; 3 z 5 prób."),
    ("A","Atrybuty zawodów, spotkania z rodzicami, kącik zawodów."),
    ("R","Wiedza o zawodach buduje obraz świata i plany dziecka."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kącik zawodów · obserwacja zabawy tematycznej.",
  pomoce=["atrybuty i stroje zawodowe","karty zawodów z narzędziami","zaproszenia dla rodziców-gości","album zawodów rodziców","kącik zawodów"],
  metody=["spotkania z rodzicami opowiadającymi o pracy","dopasowywanie narzędzi do zawodów","zabawa w role zawodowe","album zawodów tworzony przez grupę"],
  rodzaj="Preorientacja zawodowa / kompetencje społeczne",
  przebieg=[
    ("N — zaprasza rodzica opowiadającego o swojej pracy.","D — słucha i zadaje pytania gościowi."),
    ("N — rozkłada karty zawodów i narzędzi.","D — dopasowuje narzędzia do zawodów."),
    ("N — pyta: „czym zajmuje się ta osoba?”.","D — opisuje pracę w trzech zawodach."),
    ("N — otwiera kącik zawodów z atrybutami.","D — wybiera rolę i odgrywa ją w zabawie."),
    ("N — dokleja stronę do albumu zawodów.","D — rysuje zawód, który go interesuje.")],
  mod2=["dwa zawody do opisania","dopasowanie narzędzi z podpowiedzią","rola zaproponowana przez nauczyciela"],
  mod3=["rozpoznanie zawodu po stroju","dopasowanie jednego narzędzia","udział w zabawie z dorosłym","krótka rola"],
  mod1=["scharakteryzowanie pięciu zawodów z narzędziami i rozwinięcie roli przez 15 minut","opowiedzenie o zawodzie rodzica","zaplanowanie zabawy w miasteczko zawodów","wyjaśnienie, dlaczego każdy zawód jest potrzebny"],
  wskazowka="Zaproś rodziców do opowiedzenia o swojej pracy — pół godziny z prawdziwym piekarzem czy pielęgniarką zostawia ślad, którego nie zostawi żadna plansza."),
}
