# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IV (poruszanie się), wersja A (3–4 lata)."""

KONSPEKTY_D4 = {
 ("A", 16): dict(
  nr="D4-16", tytul="Ścieżka leśnych zwierząt",
  podtytul="Pewne chodzenie i bieganie z omijaniem i pokonywaniem przeszkód",
  sfera="IV PORUSZANIE SIĘ · Lokomocja (ICF d450–d455 · PP 9.1·9.4)",
  czas="15 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko przebiegnie tor z 3 przeszkodami samodzielnie, zwalniając przed każdą przeszkodą i nie przewracając się, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Pokonuje tor: omija pachołek, przechodzi nad woreczkiem, wchodzi na ławeczkę."),
    ("M","3 przeszkody bez upadku; 3 z 5 prób w sesji."),
    ("A","Tor oznaczony śladami zwierząt wskazującymi kierunek."),
    ("R","Sprawność lokomocyjna warunkuje bezpieczeństwo w sali i w ogrodzie."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Tor przeszkód · pomiar prób i upadków po każdej sesji.",
  pomoce=["pachołki, woreczki, niska ławeczka","ślady zwierząt (stopki, łapki) na podłodze","opaski z uszami zwierząt","bębenek do sygnałów start/stop"],
  metody=["zabawa naśladowcza w role zwierząt","tor z wizualnym oznaczeniem drogi","stopniowanie trudności przeszkód","sygnał dźwiękowy start – stop"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — pokazuje tor i przechodzi go wolno jako pierwszy miś.","D — patrzy i idzie za nauczycielem po śladach."),
    ("N — rozdaje opaski: „teraz jesteśmy zajączkami”.","D — przechodzi tor skokami zajączka."),
    ("N — gra na bębenku: szybko-wolno, stop.","D — dostosowuje tempo, zatrzymuje się na sygnał."),
    ("N — dokłada trzecią przeszkodę i wycofuje się z toru.","D — pokonuje pełny tor samodzielnie."),
    ("N — kończy „powrotem do norki” i przeliczeniem przejść.","D — wraca na swoje miejsce, liczy z nauczycielem.")],
  mod2=["dwie przeszkody zamiast trzech","przejście za dorosłym, nie samodzielnie","tempo marszu zamiast biegu"],
  mod3=["prowadzenie za rękę przez cały tor","przeszkody nisko i szeroko rozstawione","tor skrócony do 2 metrów","konsultacja z fizjoterapeutą przy częstych upadkach"],
  mod1=["tor z 5 przeszkodami w tempie biegu","omijanie dzieci biegnących z naprzeciwka","dziecko układa własny tor dla grupy","zapamiętanie i odtworzenie kolejności przeszkód"],
  wskazowka="Ślady na podłodze pokazują drogę lepiej niż polecenie „biegnij tam” — trzylatek podąża wzrokiem za znakiem, nie za instrukcją słowną."),

 ("A", 17): dict(
  nr="D4-17", tytul="Schodki do chmurki",
  podtytul="Wchodzenie i schodzenie po schodach",
  sfera="IV PORUSZANIE SIĘ · Chodzenie po schodach (ICF d455 · PP 9.4)",
  czas="10 min", forma="indywidualnie lub w parze", cykl="codziennie (przy wyjściu)",
  ter="Dziecko wejdzie po schodach krokiem naprzemiennym trzymając poręcz i zejdzie krokiem dostawnym, bez pomocy dorosłego, w 3 z 5 przejść, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Pokonuje schody, trzymając poręcz, w rytmie krok po kroku."),
    ("M","Wejście naprzemiennie · zejście dostawnie; 3 z 5 przejść."),
    ("A","Na stopniach naklejone stópki wyznaczające, gdzie stawiać nogę."),
    ("R","Schody to codzienna droga do szatni, ogrodu i sali gimnastycznej."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja w rutynie wyjścia · zapis samodzielnych przejść.",
  pomoce=["naklejki-stópki na stopniach (lewa/prawa)","rymowanka „raz stopień, dwa stopień”","poręcz na wysokości dziecka","chmurka-cel na górze schodów"],
  metody=["oznaczenie wzrokowe kolejności stóp","rytmizacja rymowanką","stała droga i stały rytuał","stopniowe wycofywanie ręki dorosłego"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — pokazuje stópki: „lewa tu, prawa tu, do chmurki”.","D — stawia stopy na naklejkach."),
    ("N — trzyma dziecko za rękę i mówi rymowankę.","D — wchodzi w rytm rymowanki, trzymając poręcz."),
    ("N — puszcza rękę, idzie obok z drugiej strony.","D — wchodzi samodzielnie, trzymając poręcz."),
    ("N — przy schodzeniu przypomina: „nogi razem, powoli”.","D — schodzi krokiem dostawnym, patrząc pod nogi."),
    ("N — kończy zabawą „dotknij chmurki” na górze.","D — dotyka chmurki i schodzi samodzielnie.")],
  mod2=["krok dostawny w obie strony","dorosły obok, bez trzymania","tylko 5 stopni zamiast całej kondygnacji"],
  mod3=["trzymanie za obie ręce","stopnie pokonywane z odpoczynkiem co 3","niesienie dziecka przy zmęczeniu","konsultacja z fizjoterapeutą"],
  mod1=["krok naprzemienny w górę i w dół","bez trzymania poręczy","niesienie lekkiego przedmiotu podczas wchodzenia","pomoc młodszemu dziecku na schodach"],
  wskazowka="Schodzenie jest trudniejsze niż wchodzenie — nie wymagaj kroku naprzemiennego w dół, dopóki dziecko nie robi go swobodnie w górę."),

 ("A", 18): dict(
  nr="D4-18", tytul="Piłka wędrowniczka",
  podtytul="Rzucanie piłki i podejmowanie prób jej łapania",
  sfera="IV PORUSZANIE SIĘ · Rzut i chwyt (ICF d445 · PP 9.4·9.5)",
  czas="12 min", forma="para dzieci + dorosły", cykl="3× w tygodniu",
  ter="Dziecko rzuci piłkę oburącz do celu z odległości 2 metrów i podejmie próbę złapania piłki toczonej, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Rzuca piłkę oburącz do kosza i łapie piłkę toczoną po podłodze."),
    ("M","Rzut z 2 metrów · próba chwytu; 3 z 5 prób."),
    ("A","Piłka duża, lekka; kosz szeroki, oznaczony kolorem."),
    ("R","Koordynacja oko–ręka jest zapleczem manipulacji i grafomotoryki."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Zabawa w parach · liczba udanych rzutów i chwytów.",
  pomoce=["duża lekka piłka i piłka sensoryczna","szeroki kosz lub obręcz","taśma wyznaczająca linię rzutu","kolorowe znaczniki odległości"],
  metody=["stopniowanie odległości znacznikami","toczenie przed rzucaniem","zabawa w parach z dorosłym pośrodku","natychmiastowe wzmocnienie każdej próby"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — toczy piłkę do dziecka: „łap, wraca do ciebie”.","D — zatrzymuje piłkę dłońmi i toczy z powrotem."),
    ("N — stawia kosz i pokazuje rzut oburącz od klatki piersiowej.","D — naśladuje rzut z linii 1 metra."),
    ("N — przesuwa dziecko na znacznik 2 metrów.","D — rzuca do kosza z większej odległości."),
    ("N — rzuca lekko piłkę w ręce dziecka.","D — podejmuje próbę chwytu oburącz."),
    ("N — kończy wymianą w parze dzieci, stojąc obok.","D — rzuca i łapie z kolegą, licząc podania.")],
  mod2=["odległość 1 metr","piłka większa i miękka","chwyt do kosza trzymanego przy brzuchu dziecka"],
  mod3=["toczenie zamiast rzucania","piłka podawana z rąk do rąk","kosz tuż przed dzieckiem","obserwacja koordynacji wzrokowo-ruchowej"],
  mod1=["rzut i chwyt w parze przez 4 wymiany","rzut jednorącz do celu","piłka mniejsza","gra zespołowa z prostą regułą"],
  wskazowka="Łapanie zaczyna się od toczenia — piłka lecąca w powietrzu jest dla trzylatka zbyt szybka, by zdążył ustawić ręce."),

 ("A", 19): dict(
  nr="D4-19", tytul="Wieża i korale",
  podtytul="Budowanie z klocków, nawlekanie i dopasowywanie kształtów",
  sfera="IV PORUSZANIE SIĘ · Motoryka precyzyjna (ICF d440 · PP 9.5·6.3)",
  czas="12 min", forma="mała grupa (2–3 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko ułoży wieżę z 6 klocków i nawlecze 4 duże koraliki na sztywną żyłkę samodzielnie, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Stawia klocek na klocku i nawleka koraliki na żyłkę."),
    ("M","6 klocków · 4 koraliki; 3 z 5 prób w sesji."),
    ("A","Klocki duże i lekkie, żyłka sztywna z zawiązanym końcem."),
    ("R","Precyzja dłoni przygotowuje do samoobsługi i grafomotoryki."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Wytwór dziecka · zdjęcie do teczki obserwacji.",
  pomoce=["duże klocki drewniane","sztywna żyłka lub sznurowadło z końcówką","duże koraliki i makarony","sorter kształtów","podkładka antypoślizgowa"],
  metody=["praca na stabilnej podkładce","pokaz krok po kroku bez słów","stopniowanie: od dużych do mniejszych elementów","wystawa wytworów na koniec sesji"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — stawia 3 klocki i milczy, zaprasza gestem.","D — dokłada kolejne klocki, buduje wieżę."),
    ("N — przy chwiejnej wieży poprawia podkładkę, nie wieżę.","D — ustawia klocek dokładniej, wieża stoi."),
    ("N — pokazuje nawlekanie: „koralik jedzie po sznurku”.","D — nawleka pierwszy koralik z pomocą wzrokową."),
    ("N — podaje koraliki po jednym, w tempie dziecka.","D — nawleka kolejne koraliki samodzielnie."),
    ("N — robi zdjęcie wieży i korali do teczki.","D — pokazuje swój wytwór grupie.")],
  mod2=["4 klocki i 2 koraliki","koraliki bardzo duże, żyłka gruba","dorosły przytrzymuje żyłkę"],
  mod3=["klocki podawane do ręki, wieża z 3 elementów","nawlekanie na sztywny patyk zamiast żyłki","prowadzenie ręki przy pierwszych próbach","ocena napięcia mięśniowego dłoni"],
  mod1=["budowla według wzoru obrazkowego","nawlekanie w zadanej kolejności kolorów","8 elementów zamiast 4","zaprojektowanie własnego wzoru dla kolegi"],
  wskazowka="Podkładka antypoślizgowa robi więcej niż podpowiedź słowna — większość „nieudanych” wież rozpada się przez ślizgający się blat, nie przez brak precyzji."),

 ("A", 20): dict(
  nr="D4-20", tytul="Muzyczne pociągi",
  podtytul="Udział w zabawach ruchowych, rytmicznych i naśladowczych",
  sfera="IV PORUSZANIE SIĘ · Zabawy rytmiczne (ICF d455 · PP 9.1·8.4)",
  czas="12 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko wykona ruchy zabawy rytmicznej z naśladowania przez całą zwrotkę, pozostając w kole, w 3 z 5 zabaw sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Powtarza ruchy piosenki i utrzymuje miejsce w kole."),
    ("M","Cała zwrotka w kole; 3 z 5 zabaw."),
    ("A","Ruchy proste, powtarzalne, wspierane obrazkiem-symbolem."),
    ("R","Zabawy rytmiczne łączą ruch, uwagę i współdziałanie w grupie."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja zajęć rytmicznych 2× w tygodniu · karta udziału.",
  pomoce=["nagrania znanych piosenek","instrumenty perkusyjne (marakasy, bębenek)","obręcze wyznaczające miejsca w kole","karty-obrazki ruchów"],
  metody=["naśladowanie ruchu w kole","stałe miejsce wyznaczone obręczą","ruchy powtarzalne w refrenie","instrument jako wzmocnienie udziału"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / pomoc p-p",
  przebieg=[
    ("N — rozkłada obręcze i zaprasza do koła piosenką.","D — staje w swojej obręczy."),
    ("N — pokazuje 2 ruchy do refrenu, powoli.","D — naśladuje ruchy patrząc na nauczyciela."),
    ("N — włącza muzykę i prowadzi całą zwrotkę.","D — wykonuje ruchy przez całą zwrotkę w kole."),
    ("N — rozdaje instrumenty na drugą zwrotkę.","D — gra w rytmie, nie wychodząc z obręczy."),
    ("N — kończy pociągiem dookoła sali.","D — idzie w pociągu, trzymając kolegę.")],
  mod2=["udział przez sam refren","obręcz tuż obok nauczyciela","ruchy tylko rękami, bez przemieszczania"],
  mod3=["taniec w parze z dorosłym poza kołem","muzyka ciszej, krótszy fragment","możliwość obserwowania z boku przez pierwsze sesje","sprawdzenie wrażliwości słuchowej"],
  mod1=["odtworzenie układu z pamięci","dziecko proponuje własny ruch dla grupy","prowadzenie zabawy jako „dyrygent”","układ z 4 różnymi ruchami"],
  wskazowka="Obręcz wyznaczająca miejsce rozwiązuje większość problemów z rozsypującym się kołem — dziecko widzi swoją przestrzeń, zamiast szukać jej w tłumie."),
}
