# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VIII (główne obszary życia), wersja B (5 lat)."""

KONSPEKTY_5_D8 = {
 ("B", 35): dict(
  nr="B8-35", tytul="Mój pomysł na zajęcia",
  podtytul="Aktywny udział w zajęciach i podejmowanie własnych aktywności",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Aktywność edukacyjna (ICF d815 · PP 1.2·2.1)",
  czas="25 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko wykona wszystkie zadania zajęcia i zgłosi się raz do odpowiedzi lub prezentacji, w 3 z 5 zajęć, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Uczestniczy w zadaniach i zabiera głos na zajęciach."),
    ("M","Wszystkie zadania · 1 zgłoszenie; 3 z 5 zajęć."),
    ("A","Znaczniki zgłoszeń i widoczny plan zajęcia."),
    ("R","Aktywny udział przygotowuje do roli ucznia w szkole."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta aktywności na zajęciach · zapis zgłoszeń.",
  pomoce=["plan zajęcia z 3 punktami","znaczniki zgłoszeń (patyczki z imionami)","skrzynka pomysłów dzieci","materiały do zadań w tackach","dzwonek prezentacji"],
  metody=["plan zajęcia widoczny od początku","patyczki zamiast podnoszenia rąk","skrzynka pomysłów: dzieci proponują temat","przestrzeń na własny sposób wykonania zadania"],
  rodzaj="Zajęcia dydaktyczne / pomoc p-p",
  przebieg=[
    ("N — pokazuje plan zajęcia: trzy punkty.","D — odczytuje z obrazków, co będzie robione."),
    ("N — prowadzi pierwsze zadanie z materiałem dla każdego.","D — wykonuje zadanie na swojej tacce."),
    ("N — losuje patyczek albo prosi o zgłoszenie.","D — zgłasza się i odpowiada lub pokazuje pracę."),
    ("N — zachęca: „możesz zrobić to po swojemu”.","D — proponuje własny sposób wykonania zadania."),
    ("N — otwiera skrzynkę pomysłów na kolejne zajęcia.","D — wrzuca rysunek tematu, który go interesuje.")],
  mod2=["dwa zadania zamiast trzech","zgłoszenie po uprzedzeniu indywidualnym","materiał gotowy do użycia"],
  mod3=["udział w jednym zadaniu","miejsce obok nauczyciela","zgłoszenie przez pokazanie pracy, bez mówienia","krótszy czas udziału"],
  mod1=["własna propozycja sposobu wykonania zadania","poprowadzenie fragmentu zajęcia","zaproponowanie tematu kolejnych zajęć","pomoc koledze w wykonaniu zadania"],
  wskazowka="Skrzynka pomysłów naprawdę musi działać — jeśli choć raz zrealizujesz temat wrzucony przez dziecko, aktywność całej grupy zmienia się na stałe."),

 ("B", 36): dict(
  nr="B8-36", tytul="Miasto z podziałem ról",
  podtytul="Rozwijanie zabawy tematycznej z podziałem ról",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Zabawa tematyczna (ICF d880 · PP 1.12·8.6)",
  czas="30 min", forma="mała grupa (4–6 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko uzgodni rolę z jednym dzieckiem i utrzyma ją przez 10 minut zabawy tematycznej, w 3 z 5 zabaw, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Przyjmuje rolę, uzgadnia ją i działa w niej z partnerem."),
    ("M","Rola utrzymana 10 minut; 3 z 5 zabaw."),
    ("A","Kąciki tematyczne z atrybutami i tablicą ról."),
    ("R","Zabawa w role rozwija język, negocjacje i myślenie symboliczne."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Obserwacja zabawy tematycznej · 20 minut · zapis czasu w roli.",
  pomoce=["kąciki: sklep, dom, przychodnia, warsztat","atrybuty ról i identyfikatory","tablica ról z klipsami","rekwizyty otwarte (pudełka, tkaniny)","kasa, recepty, narzędzia"],
  metody=["tablica ról jako miejsce uzgodnień","dorosły w roli, nie jako organizator","rekwizyty otwarte pobudzające fabułę","rozbudowa fabuły pytaniem w roli"],
  rodzaj="Zajęcia wspierające rozwój społeczny i poznawczy",
  przebieg=[
    ("N — prezentuje kąciki i tablicę ról.","D — wybiera rolę i przypina klips przy swoim imieniu."),
    ("N — pomaga uzgodnić role między dziećmi.","D — ustala z kolegą, kto kim jest w zabawie."),
    ("N — wchodzi do zabawy w roli klienta lub pacjenta.","D — działa w swojej roli, obsługując dorosłego."),
    ("N — pyta w roli: „a co, jeśli zabraknie towaru?”.","D — rozwija fabułę, proponuje rozwiązanie."),
    ("N — kończy zabawę w roli i zaprasza do porządków.","D — kończy rolę i porządkuje kącik.")],
  mod2=["rola zaproponowana przez nauczyciela","zabawa 5-minutowa","atrybut wyraźnie oznaczający rolę"],
  mod3=["czynności typowe dla roli po pokazie","zabawa w parze z dorosłym","jedna czynność w roli","obserwacja poziomu zabawy symbolicznej"],
  mod1=["zaplanowanie scenariusza zabawy z grupą","rozdzielenie ról i rozwinięcie fabuły na 20 minut","wprowadzenie nowego wątku do zabawy","zaproszenie do zabawy dziecka spoza grupy"],
  wskazowka="Wejdź w rolę klienta, nie w rolę nauczyciela — pytanie zadane z wnętrza zabawy rozwija fabułę, pytanie z zewnątrz ją kończy."),

 ("B", 37): dict(
  nr="B8-37", tytul="Pracownia ulepszeń",
  podtytul="Ekspresja twórcza: budowle, prace plastyczne, szukanie ulepszeń",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Twórczość (ICF d880 · PP 8.1·6.3)",
  czas="30 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko wykona pracę na zadany temat, dobierając samodzielnie dwie techniki lub materiały, w 3 z 5 prac, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Tworzy pracę, wybierając materiały i techniki samodzielnie."),
    ("M","2 techniki lub materiały; 3 z 5 prac."),
    ("A","Otwarta pracownia z materiałami w zasięgu ręki."),
    ("R","Twórczość rozwija sprawczość i myślenie dywergencyjne."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Teczka prac · karta samooceny wytworu.",
  pomoce=["materiały recyklingowe i plastyczne w otwartych pojemnikach","karty technik (wydzieranka, stempel, kolaż)","galeria prac na ścianie","karta samooceny: co poprawię","aparat do dokumentacji"],
  metody=["pracownia otwarta zamiast jednej techniki dla wszystkich","temat zamiast wzoru do odtworzenia","pytanie o ulepszenie po skończeniu","galeria z podpisami autorów"],
  rodzaj="Zajęcia artystyczne / wspierające twórczość",
  przebieg=[
    ("N — podaje temat: „pojazd, który jeszcze nie istnieje”.","D — ogląda materiały i planuje swoją pracę."),
    ("N — pokazuje karty technik do wyboru.","D — wybiera dwie techniki lub materiały."),
    ("N — nie podaje wzoru, wspiera pytaniami.","D — tworzy pracę według własnego pomysłu."),
    ("N — pyta: „co byś zmienił następnym razem?”.","D — wskazuje jedno możliwe ulepszenie."),
    ("N — zaprasza do galerii i podpisania pracy.","D — wiesza pracę i opowiada o swoim pomyśle.")],
  mod2=["wybór z dwóch technik","temat zawężony z przykładem","materiały wstępnie przygotowane"],
  mod3=["praca według wzoru z pokazem kroków","jedna technika","materiał podawany kolejno","wzmocnienie każdego etapu"],
  mod1=["zaplanowanie pracy przed rozpoczęciem i realizacja planu","wskazanie ulepszenia i wykonanie drugiej wersji","praca zespołowa nad wspólnym projektem","oprowadzenie grupy po galerii"],
  wskazowka="Pytanie „co byś zmienił” zamienia pracę plastyczną w projektowanie — i jest jedyną oceną, która nie odbiera dziecku poczucia autorstwa."),

 ("B", 38): dict(
  nr="B8-38", tytul="Orkiestra przedszkolna",
  podtytul="Udział w zbiorowym muzykowaniu, śpiewaniu i tańcu",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Muzykowanie (ICF d880 · PP 8.4)",
  czas="25 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko zaśpiewa refren znanej piosenki z grupą i zagra swoją partię w prostym akompaniamencie, w 3 z 5 zajęć, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Śpiewa refren i gra przypisaną partię instrumentalną."),
    ("M","Refren + partia; 3 z 5 zajęć."),
    ("A","Partytura obrazkowa z kolorami instrumentów."),
    ("R","Muzykowanie rozwija słuch, rytm i współdziałanie w grupie."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Obserwacja zajęć umuzykalniających · karta udziału.",
  pomoce=["instrumenty perkusyjne w trzech kolorach","partytura obrazkowa (kolorowe pola)","batuta dyrygenta","nagrania piosenek","krzesełka ustawione w orkiestrę"],
  metody=["partytura obrazkowa zamiast instrukcji słownej","podział na sekcje instrumentów","rola dyrygenta rotacyjnie","koncert dla innej grupy jako cel"],
  rodzaj="Zajęcia artystyczne / umuzykalniające",
  przebieg=[
    ("N — rozdaje instrumenty według sekcji kolorystycznych.","D — bierze instrument i siada w swojej sekcji."),
    ("N — pokazuje partyturę: „gramy, gdy świeci nasz kolor”.","D — odczytuje, kiedy przypada jego partia."),
    ("N — dyryguje: śpiew w zwrotce, instrumenty w refrenie.","D — śpiewa refren i gra we właściwym momencie."),
    ("N — przekazuje batutę dziecku.","D — dyryguje sekcją, obserwując partyturę."),
    ("N — zapowiada koncert dla młodszej grupy.","D — gra i śpiewa podczas koncertu.")],
  mod2=["gra tylko w refrenie","instrument o prostym sposobie gry","partytura z dwoma kolorami"],
  mod3=["gra razem z dorosłym","instrument cichszy i mniej wymagający","udział przez część utworu","możliwość użycia słuchawek wygłuszających"],
  mod1=["śpiew zwrotki i refrenu z pamięci, utrzymanie rytmu w zespole","rola dyrygenta całej orkiestry","zaproponowanie własnego akompaniamentu","nauczenie młodszych dzieci partii"],
  wskazowka="Partytura z kolorami zastępuje ciągłe „teraz wy” — dzieci patrzą na planszę zamiast na nauczyciela i po raz pierwszy naprawdę grają razem."),

 ("B", 39): dict(
  nr="B8-39", tytul="Polecenie dla całej grupy",
  podtytul="Pełnienie roli przedszkolaka i reagowanie na polecenia grupowe",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Rola przedszkolaka (ICF d815 · PP 1.6·3.5)",
  czas="20 min", forma="cała grupa", cykl="codziennie",
  ter="Dziecko wykona polecenie skierowane do całej grupy po jednym powtórzeniu ogólnym, bez zwracania się do niego indywidualnie, w 3 z 5 poleceń dnia, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Reaguje na polecenie kierowane do wszystkich."),
    ("M","1 powtórzenie ogólne; 3 z 5 poleceń."),
    ("A","Sygnał uwagi przed poleceniem; polecenia krótkie i jednoznaczne."),
    ("R","Reagowanie na polecenia grupowe to kluczowa kompetencja szkolna."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Rejestr poleceń grupowych · 5 dziennie · zapis reakcji.",
  pomoce=["dzwonek lub klaśnięcie jako sygnał uwagi","piktogramy najczęstszych poleceń","gra „Simon says” w wersji polskiej","tablica poleceń dnia","stoper"],
  metody=["stały sygnał uwagi przed poleceniem","polecenia krótkie, jedno zdanie","gra ćwicząca słuchanie poleceń grupowych","pomiar czasu reakcji jako zabawa"],
  rodzaj="Zajęcia dydaktyczne / pomoc p-p",
  przebieg=[
    ("N — wprowadza sygnał uwagi: klaśnięcie w rytmie.","D — powtarza rytm i milknie, patrząc na nauczyciela."),
    ("N — wydaje krótkie polecenie do całej grupy.","D — wykonuje polecenie razem z innymi."),
    ("N — prowadzi grę: „grupa robi to, co mówię”.","D — reaguje tylko na polecenia poprzedzone sygnałem."),
    ("N — mierzy czas reakcji grupy stoperem.","D — stara się zareagować szybciej niż poprzednio."),
    ("N — kończy poleceniem porządkowym bez powtórzeń.","D — wykonuje polecenie za pierwszym razem.")],
  mod2=["polecenie powtórzone dwa razy","dodatkowy gest wspierający","wzrok nauczyciela skierowany na dziecko"],
  mod3=["polecenie powtórzone indywidualnie z imieniem","polecenie jednoelementowe z pokazem","dziecko blisko nauczyciela","sprawdzenie rozumienia i słuchu"],
  mod1=["wykonanie polecenia podanego raz, bez sygnału wzrokowego","przekazanie polecenia grupie","wykonanie polecenia złożonego z dwóch części","przypomnienie polecenia koledze"],
  wskazowka="Stały sygnał uwagi przed poleceniem jest ważniejszy niż samo polecenie — dziecko nie ignoruje treści, tylko nie wie, że komunikat właśnie się zaczął."),
}
