# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar II (ogólne zadania i wymagania), wersja A (3–4 lata)."""

KONSPEKTY_D2 = {
 ("A", 6): dict(
  nr="D2-06", tytul="Zaproszenie od misia",
  podtytul="Podejmowanie zadania lub zabawy zaproponowanej przez dorosłego",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Podejmowanie zadania (ICF d210 · PP 1.2)",
  czas="10 min", forma="mała grupa (3–4 dzieci)", cykl="codziennie",
  ter="Dziecko przystąpi do zabawy zaproponowanej obrazkiem-zaproszeniem w ciągu 1 minuty od propozycji, bez wspólnego rozpoczynania przez dorosłego, w 3 z 5 propozycji dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Podchodzi do stolika i zaczyna zaproponowaną zabawę."),
    ("M","Start do 1 minuty; 3 z 5 propozycji dziennie."),
    ("A","Zaproszenie ma formę obrazka wręczanego do ręki przez pacynkę."),
    ("R","Warunkuje udział we wszystkich zajęciach kierowanych."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Lista kontrolna propozycji · zapis dzienny (5 propozycji).",
  pomoce=["pacynka-miś „zapraszacz”","karty-zaproszenia ze zdjęciem zabawy","2 stoliki z gotowymi zestawami","koszyk na wykorzystane zaproszenia"],
  metody=["zaproszenie wizualne zamiast polecenia słownego","prawo wyboru z dwóch propozycji","gotowe stanowisko (materiał już wyłożony)","wzmocnienie natychmiastowe przy starcie"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / pomoc p-p",
  przebieg=[
    ("N — miś wręcza dziecku kartę-zaproszenie ze zdjęciem zabawy.","D — bierze kartę i ogląda zdjęcie."),
    ("N — pokazuje ręką stolik: „tam czeka twoja zabawa”.","D — idzie do stolika ze zdjęciem w ręce."),
    ("N — dopasowuje kartę do stanowiska i odsuwa się.","D — wkłada kartę do koszyka i zaczyna zabawę."),
    ("N — podaje drugie zaproszenie: wybór z dwóch.","D — wybiera jedną kartę i idzie samodzielnie."),
    ("N — kończy podliczeniem zaproszeń przyjętych przez grupę.","D — pokazuje misiowi, co zrobiło przy stoliku.")],
  mod2=["dorosły idzie z dzieckiem do stolika","zaproszenie tylko jedno, bez wyboru","zabawa z ulubionego kącika dziecka"],
  mod3=["wspólne rozpoczęcie: dorosły wykonuje pierwszy ruch","zaproszenie to sam przedmiot podany do rąk","czas startu wydłużony do 3 minut","obserwacja przyczyn odmowy (ABC)"],
  mod1=["zaproszenie słowne, bez obrazka","dziecko roznosi zaproszenia innym dzieciom","propozycja przyjęta także wtedy, gdy trzeba przerwać ulubioną zabawę","dziecko samo proponuje zabawę koledze"],
  wskazowka="Zaproszenie działa, gdy stanowisko jest już gotowe — jeśli dziecko musi czekać na wyłożenie materiału, motywacja gaśnie, zanim zabawa się zacznie."),

 ("A", 7): dict(
  nr="D2-07", tytul="Dwa kroki do końca",
  podtytul="Kończenie rozpoczętej czynności przy wsparciu dorosłego",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Doprowadzanie do końca (ICF d210 · PP 2.6)",
  czas="10 min", forma="indywidualnie lub w parze", cykl="codziennie",
  ter="Dziecko wykona zadanie 3-etapowe do końca, korzystając z planu obrazkowego i odhaczając kolejne kroki, przy nie więcej niż jednym przypomnieniu słownym, w 3 z 5 prób dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Wykonuje wszystkie 3 kroki zadania i zgłasza koniec."),
    ("M","3 kroki · maks. 1 przypomnienie; 3 z 5 prób dziennie."),
    ("A","Plan obrazkowy leży przy zadaniu, kroki odhaczane klipsem."),
    ("R","Buduje wytrwałość potrzebną w każdym zadaniu przedszkolnym."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Plan obrazkowy z odhaczaniem kroków · zapis liczby wykonanych etapów.",
  pomoce=["paski z planem obrazkowym (2–3 kroki)","klipsy lub żetony do odhaczania","zadania 3-etapowe: nawlekanie, przesypywanie, układanka","pudełko „skończone”"],
  metody=["wizualizacja etapów zadania","odhaczanie kroków jako wzmocnienie","zasada „do pudełka skończone”","wycofywanie podpowiedzi (od pełnej do żadnej)"],
  rodzaj="Zajęcia wspierające funkcje wykonawcze / pomoc p-p",
  przebieg=[
    ("N — pokazuje pasek: „tu są trzy kroki, potem koniec”.","D — patrzy na plan i nazywa (lub wskazuje) pierwszy krok."),
    ("N — po pierwszym kroku wskazuje klips: „odhacz”.","D — przesuwa klips na kolejny obrazek."),
    ("N — milczy przy drugim kroku, czeka.","D — wykonuje drugi krok bez polecenia."),
    ("N — przy zawahaniu wskazuje plan zamiast mówić.","D — patrzy na plan i wraca do zadania."),
    ("N — po ostatnim kroku: „skończone!” i wskazuje pudełko.","D — wkłada pracę do pudełka i zgłasza koniec.")],
  mod2=["plan 2-krokowy zamiast 3","dorosły odhacza razem z dzieckiem","zadanie krótsze (mniej elementów)"],
  mod3=["prowadzenie ręki przy każdym kroku","po każdym kroku wzmocnienie sensoryczne","jeden krok na sesję, reszta wykonana przez dorosłego","sprawdzenie, czy zadanie nie przekracza możliwości manualnych"],
  mod1=["plan 4-krokowy podany raz, słownie","dziecko samo układa plan z obrazków przed pracą","sprawdzenie kompletności przed zgłoszeniem końca","pomoc koledze w odhaczaniu jego planu"],
  wskazowka="Wskazuj plan palcem zamiast powtarzać polecenie — dziecko uczy się wtedy korzystać z podpowiedzi wzrokowej, a nie czekać na głos dorosłego."),

 ("A", 8): dict(
  nr="D2-08", tytul="Pociąg dnia",
  podtytul="Odnajdywanie się w rytmie dnia i przechodzenie między aktywnościami",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Rytm dnia (ICF d230 · PP WSR·Zad.2)",
  czas="5 min przy każdym przejściu", forma="cała grupa", cykl="codziennie",
  ter="Dziecko po sygnale dźwiękowym i uprzedzeniu „za chwilę kończymy” przejdzie do kolejnej aktywności samodzielnie, bez protestu dłuższego niż 1 minuta, w 3 z 5 przejść dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Kończy aktywność i przechodzi do kolejnego wagonika pociągu dnia."),
    ("M","Protest do 1 minuty; 3 z 5 przejść dziennie."),
    ("A","Plan dnia w formie pociągu z ruchomą lokomotywką-wskaźnikiem."),
    ("R","Płynne przejścia zmniejszają liczbę sytuacji trudnych w grupie."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Rejestr przejść między aktywnościami (5 dziennie) · pomiar czasu reakcji.",
  pomoce=["plan dnia „pociąg” ze zdjęciami aktywności","magnetyczna lokomotywka-wskaźnik","dzwonek lub grzechotka sygnałowa","klepsydra 1-minutowa „ostatnia chwila”"],
  metody=["wizualny plan dnia","uprzedzanie z wyprzedzeniem (klepsydra)","stały sygnał dźwiękowy dla całej grupy","rytuał przesuwania lokomotywki"],
  rodzaj="Wsparcie organizacji dnia / pomoc p-p",
  przebieg=[
    ("N — rano przechodzi z dziećmi po wagonikach pociągu dnia.","D — wskazuje, co będzie po śniadaniu."),
    ("N — na 1 minutę przed końcem stawia klepsydrę: „ostatnia chwila”.","D — kończy zabawę, odkłada zabawkę."),
    ("N — dzwoni sygnałem i przesuwa lokomotywkę.","D — patrzy na pociąg i idzie do kolejnej aktywności."),
    ("N — nazywa, co się dzieje: „teraz jedziemy do stolików”.","D — zajmuje swoje miejsce bez przypominania."),
    ("N — na koniec dnia podsumowuje przejechane wagoniki.","D — sam przesuwa lokomotywkę na ostatni wagonik.")],
  mod2=["uprzedzenie indywidualne, imieniem, obok dziecka","zdjęcie kolejnej aktywności podane do ręki","dziecko przechodzi jako pierwsze, przed grupą"],
  mod3=["prowadzenie za rękę przy każdym przejściu","klepsydra 2-minutowa i podwójne uprzedzenie","możliwość zabrania przedmiotu z poprzedniej aktywności","analiza ABC przy protestach powyżej 3 minut"],
  mod1=["dziecko odczytuje plan i uprzedza grupę o zmianie","rola „maszynisty”: przesuwa lokomotywkę dla wszystkich","przejście bez uprzedzenia indywidualnego","radzenie sobie ze zmianą planu (wagonik-niespodzianka)"],
  wskazowka="Klepsydra przed sygnałem jest ważniejsza niż sam sygnał — dziecko protestuje nie przeciw zmianie, lecz przeciw jej nagłości."),

 ("A", 9): dict(
  nr="D2-09", tytul="Nasze trzy zasady",
  podtytul="Akceptowanie prostych zasad obowiązujących w zabawie i w sali",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Zasady grupy (ICF d230 · PP 1.6)",
  czas="12 min", forma="cała grupa", cykl="2× w tygodniu + codzienne przypomnienie",
  ter="Dziecko zastosuje trzy zasady sali po jednym przypomnieniu grupowym, bez interwencji indywidualnej, w 3 z 5 dni tygodnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Chodzi w sali, mówi spokojnie, odkłada zabawkę na miejsce."),
    ("M","3 zasady · 1 przypomnienie grupowe; 3 z 5 dni."),
    ("A","Zasady w formie piktogramów wiszą na wysokości wzroku dziecka."),
    ("R","Wspólne zasady są warunkiem bezpieczeństwa i współdziałania."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Tablica zasad · dzienny zapis odstępstw i przypomnień.",
  pomoce=["3 piktogramy zasad na tablicy","pacynka „Zapominalski” łamiąca zasady","zielone żetony „udało się”","zdjęcia dzieci przestrzegających zasad"],
  metody=["zasady pokazane, nie tylko powiedziane","uczenie przez kontrast (pacynka robi źle)","przypomnienie gestem zamiast upomnieniem","wzmocnienie grupowe na koniec dnia"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — pokazuje 3 piktogramy i nazywa zasady krótkimi zdaniami.","D — powtarza gest przypisany każdej zasadzie."),
    ("N — pacynka biega i krzyczy: „czy tak wolno?”.","D — wskazuje właściwy piktogram i poprawia pacynkę."),
    ("N — bawi się z grupą, wskazując piktogram zamiast upominać.","D — koryguje swoje zachowanie po zobaczeniu obrazka."),
    ("N — fotografuje dzieci przestrzegające zasad.","D — rozpoznaje siebie na zdjęciu przy zasadzie."),
    ("N — na koniec dnia rozdaje zielone żetony na tablicę.","D — przykleja żeton przy zasadzie, którą pamiętało.")],
  mod2=["jedna zasada wprowadzana na tydzień","piktogram noszony przez dziecko (brelok)","przypomnienie indywidualne przed sytuacją trudną"],
  mod3=["zasada pokazywana bezpośrednio przed każdą sytuacją","fizyczne ograniczenie przestrzeni (mniejszy kącik)","natychmiastowe wzmocnienie za każde zastosowanie","ustalenie zasad indywidualnych z zespołem"],
  mod1=["dziecko przypomina zasady innym w formie akceptowalnej","współtworzenie nowej zasady dla grupy","przestrzeganie zasad poza salą: szatnia, ogród","tłumaczenie zasady młodszemu dziecku"],
  wskazowka="Trzy zasady to maksimum dla trzylatka — czwarta sprawia, że żadna nie zostaje zapamiętana. Formułuj je zawsze pozytywnie: „chodzimy”, nie „nie biegamy”."),

 ("A", 10): dict(
  nr="D2-10", tytul="Wyspa spokoju",
  podtytul="Uspokajanie się po trudnej emocjonalnie sytuacji przy pomocy dorosłego",
  sfera="II OGÓLNE ZADANIA I WYMAGANIA · Samoregulacja (ICF d240 · PP 2.11)",
  czas="5–10 min wg potrzeby", forma="indywidualnie", cykl="w sytuacjach naturalnych",
  ter="Dziecko po zaproponowaniu przez dorosłego skorzysta z kącika wyciszenia i wróci do grupy w ciągu 3 minut od wejścia na „wyspę”, w 3 z 5 sytuacji trudnych, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Idzie na wyspę spokoju i korzysta z jednego przedmiotu kojącego."),
    ("M","Powrót do grupy do 3 minut; 3 z 5 sytuacji."),
    ("A","Wyspa jest stała, dostępna i nigdy nie służy jako kara."),
    ("R","Samoregulacja warunkuje uczestnictwo w zajęciach po trudnej sytuacji."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta zdarzeń trudnych ABC · pomiar czasu powrotu do grupy.",
  pomoce=["kącik z poduszką i kocem („wyspa”)","2–3 przedmioty kojące: gniotek, butelka sensoryczna","karta z obrazkiem „idę na wyspę”","piktogram oddechu: wąchamy kwiatek – dmuchamy świeczkę"],
  metody=["kącik wyciszenia jako miejsce bezpieczne, nie kara","nazywanie emocji przez dorosłego","oddech z obrazkiem jako strategia","powrót do grupy bez omawiania zdarzenia"],
  rodzaj="Zajęcia wspierające rozwój emocjonalny / pomoc p-p",
  przebieg=[
    ("N — w sytuacji trudnej podchodzi, kuca i nazywa: „jesteś zły”.","D — słyszy nazwę emocji, zwalnia oddech."),
    ("N — pokazuje kartę „idę na wyspę” i podaje rękę.","D — idzie na wyspę spokoju z dorosłym."),
    ("N — podaje przedmiot kojący i pokazuje oddech z obrazka.","D — trzyma gniotek, oddycha z dorosłym."),
    ("N — czeka w ciszy, nie tłumaczy i nie pyta.","D — wycisza się, sygnalizuje gotowość powrotu."),
    ("N — wraca z dzieckiem do zabawy bez omawiania zdarzenia.","D — włącza się w aktywność grupy.")],
  mod2=["wyspa wskazywana przy pierwszych sygnałach napięcia","dorosły siedzi na wyspie razem z dzieckiem","stały, jeden przedmiot kojący"],
  mod3=["dorosły przenosi lub prowadzi dziecko na wyspę","wyciszanie sensoryczne: koc obciążeniowy, ciemniejszy kąt","czas powrotu wydłużony do 10 minut","analiza ABC i konsultacja z psychologiem"],
  mod1=["dziecko samo rozpoznaje napięcie i idzie na wyspę","wybiera strategię z tablicy strategii","po powrocie nazywa, co pomogło","zaprasza kolegę na wyspę, gdy ten jest smutny"],
  wskazowka="Wyspa nie może być karą ani „przemyśleniem zachowania” — jeśli raz zadziała jako konsekwencja, dziecko przestanie z niej korzystać dobrowolnie."),
}
