# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IX (życie społeczne, lokalne i obywatelskie), wersja B (5 lat)."""

KONSPEKTY_5_D9 = {
 ("B", 40): dict(
  nr="B9-40", tytul="Herb naszej grupy",
  podtytul="Odczuwanie przynależności do grupy i wyrażanie jej",
  sfera="IX ŻYCIE SPOŁECZNE · Przynależność (ICF d910 · PP 1.16)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko poda nazwę swojej grupy i wymieni jeden zwyczaj grupowy, w 3 z 5 prób, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Nazywa swoją grupę i wskazuje jej zwyczaj."),
    ("M","Nazwa + 1 zwyczaj; 3 z 5 prób."),
    ("A","Herb grupy tworzony wspólnie; zwyczaje zilustrowane zdjęciami."),
    ("R","Poczucie przynależności wzmacnia bezpieczeństwo i współpracę."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Rozmowa kierowana · zapis wypowiedzi dziecka.",
  pomoce=["duży karton na herb grupy","zdjęcia zwyczajów grupy (krąg, urodziny, dyżury)","farby i materiały plastyczne","hymn lub piosenka grupy","tabliczka z nazwą grupy"],
  metody=["wspólne tworzenie symbolu grupy","zwyczaje utrwalone zdjęciem i nazwą","hymn grupy śpiewany w stałym momencie dnia","opowiadanie o grupie gościom"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i obywatelskie",
  przebieg=[
    ("N — pyta: „co robimy tylko w naszej grupie?”.","D — wymienia zwyczaje grupowe."),
    ("N — pokazuje zdjęcia zwyczajów i nazywa je.","D — dopasowuje nazwę do zdjęcia."),
    ("N — proponuje stworzenie herbu grupy.","D — proponuje symbol i maluje jego część."),
    ("N — uczy piosenki-hymnu grupy.","D — śpiewa hymn razem z grupą."),
    ("N — prosi o opowiedzenie o grupie gościowi.","D — podaje nazwę grupy i jeden zwyczaj.")],
  mod2=["wybór zwyczaju spośród dwóch zdjęć","nazwa grupy z podpowiedzią wzrokową","udział w malowaniu bez wypowiedzi"],
  mod3=["wskazanie znaku swojej grupy spośród trzech","nazwanie grupy po podpowiedzi","udział w części zajęć","wsparcie komunikacyjne"],
  mod1=["opowiedzenie o grupie: nazwa, 3 zwyczaje, co lubię","oprowadzenie gościa po sali","zaproponowanie nowego zwyczaju grupy","przedstawienie herbu innym grupom"],
  wskazowka="Herb tworzony wspólnie działa tylko wtedy, gdy każde dziecko namaluje w nim swój fragment — symbol nadany przez dorosłego pozostaje dekoracją."),

 ("B", 41): dict(
  nr="B9-41", tytul="Nasze przedstawienie",
  podtytul="Odgrywanie uzgodnionej roli w przygotowaniu i realizacji występu",
  sfera="IX ŻYCIE SPOŁECZNE · Uroczystości (ICF d910 · PP DE-R.5)",
  czas="25 min (próby)", forma="cała grupa", cykl="2× w tygodniu przed występem",
  ter="Dziecko wykona swoją krótką rolę w występie (jedno zdanie lub jeden ruch) po przygotowaniu wizualnym, w 3 z 4 występów, w ciągu semestru.",
  ter_smart=[
    ("S","Wykonuje ustaloną rolę przed publicznością."),
    ("M","1 rola · 3 z 4 występów."),
    ("A","Rola wybrana przez dziecko, wyćwiczona i zilustrowana na planie."),
    ("R","Występ buduje odwagę społeczną i poczucie sprawstwa."),
    ("T","Weryfikacja po semestrze."),
  ],
  ter_kryt="Karta przygotowania uroczystości · zapis roli i wykonania.",
  pomoce=["plan przedstawienia w obrazkach","stroje i rekwizyty","tablica ról ze zdjęciami","nagranie próby do odsłuchania","program dla widzów"],
  metody=["wybór roli przez dziecko","plan przedstawienia widoczny podczas prób","próba generalna w pełnej scenografii","możliwość roli bez mówienia"],
  rodzaj="Zajęcia artystyczne / kompetencje społeczne",
  przebieg=[
    ("N — przedstawia historię i możliwe role.","D — wybiera rolę z tablicy ról."),
    ("N — pokazuje plan przedstawienia scena po scenie.","D — odnajduje na planie moment swojego wejścia."),
    ("N — prowadzi próbę fragmentu z rekwizytami.","D — ćwiczy swoją kwestię lub ruch."),
    ("N — nagrywa próbę i odtwarza grupie.","D — ogląda nagranie i poprawia swoją część."),
    ("N — organizuje próbę generalną w strojach.","D — wykonuje rolę w pełnej scenografii.")],
  mod2=["rola bez słów (ruch, rekwizyt)","wejście razem z kolegą","krótsza obecność na scenie"],
  mod3=["udział w chórze grupy zamiast roli indywidualnej","obecność na scenie bez zadania","obserwacja przedstawienia z widowni","stopniowe włączanie w kolejnych występach"],
  mod1=["uzgodnienie roli z dziećmi i przygotowanie jej samodzielnie","kilka kwestii w przedstawieniu","pomoc młodszym w zapamiętaniu ról","poprowadzenie fragmentu uroczystości"],
  wskazowka="Nagranie próby jest najlepszym reżyserem — dziecko, które zobaczy siebie, poprawia głos i postawę bez jednej uwagi ze strony dorosłego."),

 ("B", 42): dict(
  nr="B9-42", tytul="Wyprawa czterech pór roku",
  podtytul="Korzystanie z rekreacji i udział w zabawach sezonowych na powietrzu",
  sfera="IX ŻYCIE SPOŁECZNE · Rekreacja (ICF d920 · PP DE-R.4·9.1)",
  czas="40 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko weźmie udział w całej zabawie sezonowej na powietrzu i pomoże przygotować sprzęt do wyjścia, w 3 z 5 wyjść, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Uczestniczy w zabawie sezonowej i współprzygotowuje wyjście."),
    ("M","Cała zabawa + pomoc w przygotowaniu; 3 z 5 wyjść."),
    ("A","Lista sprzętu w obrazkach; zabawy dostosowane do pory roku."),
    ("R","Aktywność na powietrzu wspiera zdrowie i integrację grupy."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karta wyjść · zapis inicjatyw i udziału dziecka.",
  pomoce=["sprzęt sezonowy: sanki, lupy, wiaderka, latawce","lista obrazkowa sprzętu","karty zabaw sezonowych","worek na skarby przyrody","aparat do dokumentacji"],
  metody=["planowanie wyjścia przez dzieci","zabawy przypisane porze roku","zbieranie skarbów przyrody","podsumowanie wyprawy w sali"],
  rodzaj="Zajęcia wspierające rozwój ruchowy i społeczny",
  przebieg=[
    ("N — pokazuje karty zabaw sezonowych do wyboru.","D — wybiera zabawę na dzisiejsze wyjście."),
    ("N — podaje listę obrazkową sprzętu.","D — kompletuje sprzęt według listy."),
    ("N — prowadzi zabawę sezonową na powietrzu.","D — uczestniczy w całej zabawie."),
    ("N — rozdaje worki na skarby przyrody.","D — zbiera skarby i nazywa je."),
    ("N — w sali prowadzi podsumowanie wyprawy.","D — pokazuje skarby i opowiada o zabawie.")],
  mod2=["udział w połowie zabawy","sprzęt wskazywany kolejno","krótsze wyjście"],
  mod3=["udział w zabawie z dorosłym","jedno zadanie podczas wyjścia","możliwość odpoczynku na ławce","stopniowe wydłużanie pobytu"],
  mod1=["zaproponowanie zabawy sezonowej dla grupy i poprowadzenie jej","przygotowanie sprzętu dla wszystkich","opowiedzenie o wyprawie młodszej grupie","zaplanowanie wyprawy na kolejny tydzień"],
  wskazowka="Pozwól dzieciom wybrać zabawę z kart przed wyjściem — grupa, która sama zaplanowała wyprawę, wychodzi szybciej i bawi się dłużej."),

 ("B", 43): dict(
  nr="B9-43", tytul="Widzowie i krytycy",
  podtytul="Odbiór sztuki: teatrzyki, koncerty, wystawy i wyrażanie opinii",
  sfera="IX ŻYCIE SPOŁECZNE · Odbiór sztuki (ICF d9202 · PP DE-R.1·8.3)",
  czas="30 min", forma="cała grupa", cykl="1–2× w miesiącu",
  ter="Dziecko obejrzy całe wydarzenie i wskaże, co mu się podobało, wybierając spośród dwóch propozycji, w 3 z 4 wydarzeń, w ciągu semestru.",
  ter_smart=[
    ("S","Ogląda wydarzenie do końca i wyraża opinię."),
    ("M","Całe wydarzenie + wskazanie; 3 z 4 wydarzeń."),
    ("A","Zasady widza omówione wcześniej; karty opinii do wyboru."),
    ("R","Odbiór sztuki rozwija wrażliwość i język opisu przeżyć."),
    ("T","Weryfikacja po semestrze."),
  ],
  ter_kryt="Karta odbioru sztuki · zapis opinii dziecka.",
  pomoce=["karty zasad widza (4 obrazki)","karty opinii: podobało mi się / nie podobało","bilety wstępu dla dzieci","książka opinii grupy","zdjęcia z wydarzenia"],
  metody=["przygotowanie roli widza przed wydarzeniem","bilety nadające rangę wydarzeniu","karty opinii jako rusztowanie wypowiedzi","książka opinii grupy prowadzona po każdym wydarzeniu"],
  rodzaj="Zajęcia artystyczne / kompetencje społeczne",
  przebieg=[
    ("N — rozdaje bilety i omawia zasady widza.","D — bierze bilet i nazywa zasady oglądania."),
    ("N — zaprasza na przedstawienie lub koncert.","D — ogląda całe wydarzenie, siedząc na miejscu."),
    ("N — po wydarzeniu pokazuje karty opinii.","D — wskazuje, co mu się podobało."),
    ("N — pyta o uzasadnienie: „dlaczego właśnie to?”.","D — uzasadnia swój wybór zdaniem."),
    ("N — zapisuje opinię w książce opinii grupy.","D — podpisuje swoją opinię znaczkiem.")],
  mod2=["udział w połowie wydarzenia","opinia przez wskazanie zdjęcia","miejsce blisko wyjścia"],
  mod3=["udział w krótkim fragmencie","możliwość użycia słuchawek wygłuszających","obserwacja z boku sali","stopniowe wydłużanie udziału"],
  mod1=["wyrażenie własnej opinii z uzasadnieniem","porównanie dwóch obejrzanych wydarzeń","przygotowanie pytań do aktorów","zredagowanie recenzji dla książki opinii grupy"],
  wskazowka="Bilet w dłoni zmienia zachowanie widza — dziecko, które przeszło przez „wejście na widownię”, traktuje przedstawienie inaczej niż zajęcia w sali."),

 ("B", 44): dict(
  nr="B9-44", tytul="To ja — imię i nazwisko",
  podtytul="Posługiwanie się swoim imieniem i nazwiskiem",
  sfera="IX ŻYCIE SPOŁECZNE · Dane o sobie (ICF d910 · PP 1.1)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko poda swoje imię i nazwisko na pytanie dorosłego, w 3 z 5 sytuacji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Wymienia swoje imię i nazwisko na pytanie."),
    ("M","3 z 5 sytuacji."),
    ("A","Wizytówki z imieniem i nazwiskiem; zabawa w biuro."),
    ("R","Znajomość własnych danych to element bezpieczeństwa dziecka."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Rozmowa kierowana · karta danych osobowych.",
  pomoce=["wizytówki dzieci z imieniem i nazwiskiem","pieczątki i stempelki","zabawa w biuro: formularze, długopisy","lustro z ramką i podpisem","legitymacje przedszkolaka"],
  metody=["wizytówka jako wzór do odczytania","zabawa w biuro nadająca sens podawaniu danych","rozpoznawanie swojego zapisanego imienia","przećwiczenie sytuacji, w których podaje się dane"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / bezpieczeństwo",
  przebieg=[
    ("N — rozdaje wizytówki: „to twoje imię i nazwisko”.","D — odnajduje swoją wizytówkę wśród innych."),
    ("N — otwiera biuro legitymacji przedszkolaka.","D — podchodzi i podaje swoje imię i nazwisko."),
    ("N — wypisuje legitymację, powtarzając dane.","D — powtarza swoje nazwisko za nauczycielem."),
    ("N — pyta w zabawie: „jak się nazywasz?”.","D — podaje pełne dane bez wizytówki."),
    ("N — omawia, komu podajemy swoje dane.","D — wskazuje osoby zaufane na zdjęciach.")],
  mod2=["samo imię i pierwsza sylaba nazwiska","wizytówka jako stała podpowiedź","pytanie zadawane przez znanego dorosłego"],
  mod3=["reakcja na własne imię","wskazanie swojej wizytówki spośród dwóch","powtórzenie nazwiska za dorosłym","wsparcie komunikacyjne"],
  mod1=["podanie imienia, nazwiska i nazwy grupy osobie nieznanej","rozpoznanie swojego imienia zapisanego","wyjaśnienie, komu można podawać dane","napisanie swojego imienia"],
  wskazowka="Zabawa w biuro daje powód do podawania danych — bez realnego celu pytanie „jak się nazywasz?” brzmi jak sprawdzian, a nie jak rozmowa."),
}
