# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IX (życie społeczne, lokalne i obywatelskie), wersja A (3–4 lata)."""

KONSPEKTY_D9 = {
 ("A", 39): dict(
  nr="D9-39", tytul="Nasze święto",
  podtytul="Uczestniczenie w uroczystościach grupowych: urodziny i święta grupy",
  sfera="IX ŻYCIE SPOŁECZNE · Uroczystości (ICF d910 · PP DE-R.5·1.16)",
  czas="20 min", forma="cała grupa", cykl="wg kalendarza (1–2× w miesiącu)",
  ter="Dziecko weźmie udział w jednym elemencie uroczystości (wręczy laurkę lub zaśpiewa refren) po przygotowaniu wizualnym, w 3 z 4 uroczystości, w ciągu semestru.",
  ter_smart=[
    ("S","Wykonuje jedną ustaloną czynność podczas uroczystości."),
    ("M","1 element · 3 z 4 uroczystości."),
    ("A","Przebieg pokazany wcześniej na planie obrazkowym; rola wyćwiczona."),
    ("R","Udział w świętach buduje poczucie przynależności do grupy."),
    ("T","Weryfikacja po semestrze."),
  ],
  ter_kryt="Karta wydarzeń grupowych · zapis po każdej uroczystości.",
  pomoce=["plan obrazkowy uroczystości","laurki i korona urodzinowa","piosenka „Sto lat” z gestami","słuchawki wygłuszające dla chętnych"],
  metody=["przygotowanie wizualne przed wydarzeniem","jedna, wyćwiczona rola dla dziecka","możliwość wycofania się bez konsekwencji","stały, powtarzalny scenariusz święta"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — dzień wcześniej pokazuje plan: „jutro urodziny Zosi”.","D — ogląda plan, wskazuje swoją część."),
    ("N — ćwiczy z dzieckiem jego rolę: wręczenie laurki.","D — próbuje wręczyć laurkę koledze."),
    ("N — prowadzi uroczystość według pokazanego planu.","D — siedzi w kręgu, obserwuje przebieg."),
    ("N — zaprasza dziecko w jego momencie: „teraz ty”.","D — wręcza laurkę lub śpiewa refren."),
    ("N — kończy wspólnym zdjęciem grupy.","D — staje do zdjęcia z grupą.")],
  mod2=["udział przez pierwsze 10 minut","miejsce obok nauczyciela","rola bez mówienia (samo wręczenie)"],
  mod3=["obecność w sali bez roli, z możliwością zasłonięcia uszu","uroczystość skrócona dla dziecka","obserwacja z bezpiecznej odległości","stopniowe skracanie dystansu w kolejnych świętach"],
  mod1=["udział w całej uroczystości ze znajomością przebiegu","współprzygotowanie dekoracji i laurek","powitanie gościa","zaproponowanie własnego elementu święta"],
  wskazowka="Pokaż plan święta dzień wcześniej — dla trzylatka nagła zmiana rytmu dnia jest trudniejsza niż sama uroczystość."),

 ("A", 40): dict(
  nr="D9-40", tytul="Idziemy w parze",
  podtytul="Uczestniczenie w spacerach i wyjściach poza salę przedszkolną",
  sfera="IX ŻYCIE SPOŁECZNE · Wyjścia i spacery (ICF d910 · PP DE-R.4·WSR)",
  czas="30 min", forma="cała grupa (pary)", cykl="2× w tygodniu",
  ter="Dziecko przejdzie całą trasę spaceru w parze z rówieśnikiem, reagując na sygnał zatrzymania, w 3 z 5 wyjść, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Idzie w parze, trzymając kolegę za rękę, i zatrzymuje się na sygnał."),
    ("M","Cała trasa · reakcja na sygnał; 3 z 5 wyjść."),
    ("A","Stała trasa, stała para, sygnał dźwiękowy zawsze ten sam."),
    ("R","Bezpieczne poruszanie się poza terenem otwiera dostęp do świata."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta wyjść · obserwacja podczas spaceru.",
  pomoce=["kolorowe kamizelki odblaskowe","gwizdek lub grzechotka sygnałowa","zdjęcia trasy (co zobaczymy)","linka z uchwytami dla par"],
  metody=["stała trasa i stała para","sygnał dźwiękowy zamiast wołania","zapowiedź trasy zdjęciami przed wyjściem","cel spaceru nazwany i widoczny"],
  rodzaj="Wsparcie organizacji dnia / pomoc p-p",
  przebieg=[
    ("N — przed wyjściem pokazuje zdjęcia trasy i celu.","D — ogląda zdjęcia, nazywa cel spaceru."),
    ("N — dobiera pary i rozdaje kamizelki.","D — znajduje swoją parę, podaje rękę."),
    ("N — na trasie używa sygnału: „stop przed krawężnikiem”.","D — zatrzymuje się na sygnał, czeka."),
    ("N — nazywa, co widać po drodze.","D — pokazuje palcem i nazywa zaobserwowane rzeczy."),
    ("N — po powrocie porównuje zdjęcia z tym, co widzieli.","D — wskazuje na zdjęciu, gdzie byli.")],
  mod2=["para z dzieckiem sprawnym, blisko nauczyciela","trasa skrócona o połowę","dodatkowe przypomnienie przed każdym skrzyżowaniem"],
  mod3=["trzymanie za rękę dorosłego zamiast pary","trasa 100 metrów wokół budynku","trzymanie linki z uchwytem","dodatkowy dorosły przy dziecku"],
  mod1=["cała trasa w parze, przestrzeganie zasad przy jezdni","opowiedzenie po powrocie, co się widziało","prowadzenie pary na początku kolumny","pomoc młodszemu koledze w parze"],
  wskazowka="Zdjęcia trasy pokazane przed wyjściem zmniejszają lęk skuteczniej niż zapewnienia — dziecko wie wtedy, dokąd idzie i kiedy wróci."),

 ("A", 41): dict(
  nr="D9-41", tytul="Plac zabaw według zasad",
  podtytul="Zabawy na świeżym powietrzu z zachowaniem prostych zasad",
  sfera="IX ŻYCIE SPOŁECZNE · Rekreacja (ICF d920 · PP 9.11·1.6)",
  czas="30 min", forma="cała grupa", cykl="codziennie",
  ter="Dziecko skorzysta z dwóch urządzeń placu zabaw zgodnie z zasadą kolejki, po jednym przypomnieniu, w 3 z 5 wyjść, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Czeka na swoją kolej do zjeżdżalni i huśtawki."),
    ("M","2 urządzenia · 1 przypomnienie; 3 z 5 wyjść."),
    ("A","Zasady placu pokazane obrazkiem przed wyjściem; strefy oznaczone."),
    ("R","Bezpieczna zabawa na powietrzu to codzienny element dnia."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja pobytu na placu · zapis dzienny.",
  pomoce=["tablica zasad placu (3 obrazki)","chorągiewki oznaczające strefę zabawy","gwizdek do sygnału powrotu","piaskowe zabawki w koszu"],
  metody=["przypomnienie zasad przed wyjściem, nie po zdarzeniu","oznaczenie granic strefy","sygnał powrotu zawsze ten sam","dorosły przy urządzeniu z kolejką"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — przed wyjściem pokazuje 3 zasady placu.","D — powtarza gestem: czekam, nie popycham, wracam na sygnał."),
    ("N — wyznacza strefę chorągiewkami.","D — bawi się w wyznaczonej strefie."),
    ("N — stoi przy zjeżdżalni i pilnuje kolejki.","D — czeka na swoją kolej, wchodzi po schodkach."),
    ("N — przypomina zasadę obrazkiem przy trudności.","D — wraca do kolejki bez protestu."),
    ("N — daje sygnał powrotu gwizdkiem.","D — przerywa zabawę i wraca do grupy.")],
  mod2=["jedno urządzenie zamiast dwóch","dorosły stoi w kolejce razem z dzieckiem","strefa zawężona do części placu"],
  mod3=["stałe towarzyszenie dorosłego","zabawa poza urządzeniami (piaskownica)","przypomnienie zasad przy każdym urządzeniu","wcześniejszy powrót przed resztą grupy"],
  mod1=["samodzielna zabawa z przestrzeganiem zasad","zgłaszanie nauczycielowi sytuacji niebezpiecznych","zapraszanie kolegi do wspólnej zabawy","pilnowanie kolejki jako pomocnik"],
  wskazowka="Przypominaj zasady przed wyjściem, nie po zdarzeniu — na placu, w hałasie i ruchu, żadna instrukcja słowna nie dociera tak jak ta sprzed drzwi."),

 ("A", 42): dict(
  nr="D9-42", tytul="Teatrzyk i książka",
  podtytul="Odbiór muzyki, teatrzyku i książki czytanej przez dorosłego",
  sfera="IX ŻYCIE SPOŁECZNE · Odbiór sztuki (ICF d9202 · PP DE-R.1·3.3)",
  czas="15 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko wysłucha całego krótkiego opowiadania i wskaże obrazek pasujący do treści, w 3 z 5 czytań, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Słucha do końca i wskazuje obrazek związany z treścią."),
    ("M","Całe opowiadanie · 1 trafne wskazanie; 3 z 5 czytań."),
    ("A","Tekst krótki, ilustrowany, czytany z modulacją głosu."),
    ("R","Odbiór sztuki rozwija mowę, wyobraźnię i uwagę słuchową."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta odbioru sztuki · zapis wypowiedzi i wskazań dziecka.",
  pomoce=["książki z dużymi ilustracjami","pacynki bohaterów","2 obrazki do wyboru po czytaniu","poduszki do słuchania","kukiełkowy parawan"],
  metody=["czytanie z modulacją i pacynką","krótkie teksty z powtarzającym się refrenem","wybór z dwóch obrazków po czytaniu","przedmiot do trzymania w rękach podczas słuchania"],
  rodzaj="Zajęcia wspierające rozwój poznawczy i językowy",
  przebieg=[
    ("N — sadza dzieci na poduszkach, pokazuje okładkę.","D — siada, ogląda okładkę."),
    ("N — czyta z pacynką, modulując głos.","D — słucha, patrzy na ilustracje."),
    ("N — zatrzymuje się na refrenie: „a wtedy…”.","D — powtarza refren z grupą."),
    ("N — po czytaniu pokazuje 2 obrazki: „co było w bajce?”.","D — wskazuje obrazek pasujący do treści."),
    ("N — pyta, co się podobało.","D — pokazuje ulubioną ilustrację lub mówi o niej.")],
  mod2=["fragment 3-minutowy zamiast całości","przedmiot do trzymania w rękach","obrazki pokazywane w trakcie czytania"],
  mod3=["czytanie w małej grupie lub indywidualnie","książka dotykowa lub z klapkami","możliwość słuchania z boku sali","krótkie teksty, 1–2 zdania na stronę"],
  mod1=["opowiedzenie treści jednym zdaniem","powiedzenie, co się podobało i dlaczego","odegranie fragmentu bajki pacynką","wybór książki dla całej grupy"],
  wskazowka="Refren, który dzieci powtarzają, robi z biernego słuchania udział — trzylatek utrzyma uwagę dłużej, gdy ma w tekście swoją rolę."),
}
