# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar I (uczenie się i stosowanie wiedzy), wersja A (3–4 lata)."""

KONSPEKTY_D1 = {
 ("A", 1): dict(
  nr="D1-01", tytul="Czarodziejski woreczek",
  podtytul="Patrzenie i słuchanie z zainteresowaniem podczas pokazu nauczyciela",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Uwaga na pokazie (ICF d110–d115 · PP 3.5)",
  czas="10 min", forma="mała grupa (3–4 dzieci)", cykl="codziennie",
  ter="Dziecko skieruje wzrok na przedmiot wyjmowany z woreczka i utrzyma spojrzenie przez całą krótką prezentację (do 30 sekund), w 4 z 5 prezentacji sesji, w ciągu 4 tygodni.",
  ter_smart=[
    ("S","Patrzy na przedmiot wyjmowany z woreczka i na twarz pokazującego."),
    ("M","4 z 5 prezentacji w sesji; min. 2 sesje z rzędu."),
    ("A","Woreczek szeleści i „czaruje” — sygnał dźwiękowy przyciąga wzrok."),
    ("R","Uwaga na pokazie jest bramą do wszystkich zajęć kierowanych."),
    ("T","Weryfikacja po 4 tygodniach."),
  ],
  ter_kryt="Arkusz próbek uwagi po każdej sesji (codziennie); podsumowanie po 4 tyg.",
  pomoce=["błyszczący woreczek ze sznurkiem","4–5 małych przedmiotów o różnej fakturze","dzwoneczek „czaru”","poduszki wyznaczające miejsca"],
  metody=["pokaz z elementem niespodzianki","zawieszenie głosu przed wyjęciem przedmiotu","krótkie prezentacje (do 30 sekund)","natychmiastowe podanie przedmiotu do rąk"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — potrząsa woreczkiem: „coś tu mam…” i czeka w ciszy.","D — kieruje wzrok na woreczek, ucisza się."),
    ("N — powoli wyjmuje przedmiot, nazywa go i pokazuje po kole.","D — wodzi wzrokiem za przedmiotem po całym łuku."),
    ("N — dzwoni dzwoneczkiem i chowa przedmiot: „zniknął!”.","D — patrzy na woreczek w oczekiwaniu na powrót."),
    ("N — podaje przedmiot dziecku, które patrzyło.","D — bierze przedmiot, ogląda go i oddaje do woreczka."),
    ("N — kończy przeliczeniem „czarów”, chwali patrzenie.","D — wskazuje woreczek, gdy chce powtórki.")],
  mod2=["prezentacja skrócona do 15 sekund","jeden przedmiot na sesję więcej dopiero po sukcesie","dziecko siedzi na wprost nauczyciela"],
  mod3=["pokaz w parze z dorosłym, bez grupy","przedmiot prowadzony w polu widzenia dziecka","sygnał dotykowy przed każdym pokazem","konsultacja z terapeutą SI przy braku fiksacji wzroku"],
  wskazowka="Cisza działa mocniej niż zachęta — zawieś głos i odczekaj, aż spojrzenia same wrócą do woreczka, zamiast wołać dzieci po imieniu."),

 ("A", 2): dict(
  nr="D1-02", tytul="Małpka robi to, co ja",
  podtytul="Naśladowanie prostych ruchów i gestów dorosłego oraz dzieci",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Naśladowanie (ICF d130 · PP 9.1)",
  czas="10 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko odtworzy pojedynczy ruch dużej motoryki pokazany przez dorosłego lub pacynkę w ciągu 5 sekund od pokazu, w 4 z 5 prób sesji, w ciągu 4 tygodni.",
  ter_smart=[
    ("S","Powtarza ruch pokazany przez pacynkę-małpkę."),
    ("M","4 z 5 prób w sesji; min. 2 sesje z rzędu."),
    ("A","Ruchy duże i wyraziste: klaśnięcie, tupnięcie, ręce w górę."),
    ("R","Naśladowanie jest podstawowym kanałem uczenia się w tym wieku."),
    ("T","Weryfikacja po 4 tygodniach."),
  ],
  ter_kryt="Karta obserwacji zabawy ruchowej po sesji (3×/tydzień).",
  pomoce=["pacynka-małpka","bębenek do rytmu","naklejki-łapki małpki","lustro w sali (opcjonalnie)"],
  metody=["zabawa naśladowcza z pacynką","modelowanie z wyolbrzymieniem ruchu","rytm bębenka porządkujący próby","wzmocnienie natychmiastowe (przybicie łapki)"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — małpka wita się i klaszcze: „zrób to, co ja!”.","D — klaszcze, patrząc na małpkę."),
    ("N — pokazuje kolejno: tupnięcie, ręce w górę, obrót.","D — odtwarza każdy ruch po pokazie."),
    ("N — gra rytm i pokazuje ruch na akcent bębenka.","D — czeka na akcent i powtarza ruch w rytmie."),
    ("N — zaprasza dziecko do roli małpki-pokazywacza.","D — pokazuje własny ruch, grupa go naśladuje."),
    ("N — kończy „tańcem małpki” z sekwencją 2 ruchów.","D — odtwarza sekwencję i przybija łapkę małpce.")],
  mod2=["jeden ruch na próbę, bez sekwencji","pokaz powtórzony dwa razy przed próbą","dziecko naprzeciw nauczyciela, blisko"],
  mod3=["prowadzenie rąk dziecka przy pierwszych próbach","naśladowanie na materiale (odkładanie klocka jak dorosły)","sesja indywidualna przed grupową","monitoring postępu co tydzień"],
  wskazowka="Pokazuj ruch całym ciałem i z przesadą — dziecko 3-letnie naśladuje to, co widoczne i zabawne, nie to, co poprawne."),

 ("A", 3): dict(
  nr="D1-03", tytul="Klepsydra skarbów",
  podtytul="Skupienie na zabawie lub zadaniu przez kilka minut",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Skupianie uwagi (ICF d160 · PP 2.6)",
  czas="10–12 min", forma="indywidualnie lub w parze", cykl="codziennie",
  ter="Dziecko pozostanie przy wybranej zabawie przy stoliku przez czas przesypywania się klepsydry (2 minuty), nie odchodząc i nie zmieniając aktywności, w 4 z 5 prób dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Zostaje przy zadaniu, aż piasek w klepsydrze się przesypie."),
    ("M","2 minuty bez odejścia; 4 z 5 prób dziennie."),
    ("A","Stolik z jedną zabawką i parawanem ogranicza bodźce."),
    ("R","Wydłużanie uwagi warunkuje udział w zajęciach kierowanych."),
    ("T","Weryfikacja po 6 tygodniach; potem wydłużenie do 4 minut."),
  ],
  ter_kryt="Pomiar czasu przy zadaniu (klepsydra/stoper) · zapis dzienny.",
  pomoce=["klepsydra 2-minutowa","pudełko „skarb dnia” (jedna atrakcyjna zabawka)","parawan lub kącik za regałem","żetony-diamenty do naklejenia"],
  metody=["ograniczenie pola bodźców","wizualizacja czasu klepsydrą","zasada „skarb zostaje, aż piasek spadnie”","wzmocnienie żetonem po pełnej próbie"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — otwiera pudełko: „to skarb dnia — bawimy się, aż piasek spadnie”.","D — wybiera skarb i siada przy stoliku."),
    ("N — odwraca klepsydrę i odsuwa się o krok.","D — podejmuje zabawę, spogląda na klepsydrę."),
    ("N — przy próbie odejścia wskazuje klepsydrę bez słów.","D — wraca do zabawy do końca przesypywania."),
    ("N — gdy piasek spadł, ogłasza: „udało się!” i daje diament.","D — nakleja żeton na swojej karcie skarbów."),
    ("N — proponuje drugą turę z nowym skarbem.","D — decyduje: jeszcze raz albo koniec na dziś.")],
  mod2=["klepsydra 1-minutowa na start","dorosły siedzi obok przez całą próbę","skarb wybierany z dwóch, nie z pudełka"],
  mod3=["zabawa współdzielona z dorosłym (naprzemienne ruchy)","czas liczony od 30 sekund","przerwa ruchowa między próbami","obserwacja pod kątem przyczyn sensorycznych"],
  wskazowka="Klepsydra jest sędzią, nie nauczyciel — pokazuj ją palcem zamiast upominać, a spór o „jeszcze chwilę” zniknie sam."),

 ("A", 4): dict(
  nr="D1-04", tytul="Kolorowe domki",
  podtytul="Dopasowywanie i sortowanie przedmiotów według jednej cechy",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Klasyfikowanie (ICF d137 · PP 4.4)",
  czas="12 min", forma="mała grupa (2–3 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko posegreguje 6 przedmiotów do dwóch „domków” według koloru po jednorazowym pokazie wzorca, bez podpowiedzi przy kolejnych elementach, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Wkłada przedmiot do domku w tym samym kolorze."),
    ("M","6 przedmiotów · 2 kolory; 3 z 5 prób w sesji."),
    ("A","Domki-pudełka mają dach w kolorze zbioru — wzorzec stale widoczny."),
    ("R","Klasyfikowanie buduje pojęcia matematyczne i porządek myślenia."),
    ("T","Weryfikacja po 6 tygodniach; potem trzeci kolor."),
  ],
  ter_kryt="Zadanie sortowania · zestaw 6–10 elementów · zapis prób po sesji.",
  pomoce=["2 pudełka-domki z kolorowymi dachami","klocki i misie w 2 kolorach","woreczek do losowania","naklejka „mistrz porządku”"],
  metody=["sortowanie z wzorcem stale widocznym","losowanie z woreczka (element emocji)","zasada jednej cechy naraz","samokontrola: „sprawdź, czy dach pasuje”"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — stawia domki: „czerwone śpi tu, żółte tu” i wkłada po 1 wzorcu.","D — patrzy na pokaz i powtarza: czerwony – żółty."),
    ("N — podaje woreczek do losowania.","D — losuje przedmiot i nazywa (lub wskazuje) kolor."),
    ("N — pyta gestem: „gdzie mieszka?”.","D — wkłada przedmiot do właściwego domku."),
    ("N — przy pomyłce odwraca przedmiot do dachu: „pasuje?”.","D — porównuje z dachem i przekłada sam."),
    ("N — kończy przeliczeniem mieszkańców obu domków.","D — liczy z nauczycielem i przybija piątkę.")],
  mod2=["przedmioty identyczne, różne tylko kolorem","po każdej próbie potwierdzenie: „tak, czerwony”","4 elementy zamiast 6"],
  mod3=["dopasowywanie 1:1 do wzorca zamiast sortowania","prowadzenie ręki przy pierwszych 2 próbach","kolory silnie kontrastowe (czerwony–niebieski)","wydłużenie etapu przed wprowadzeniem drugiej cechy"],
  wskazowka="Jedna cecha naraz: jeśli dziecko sortuje po kolorze, wszystkie przedmioty powinny mieć ten sam kształt — inaczej zadanie sprawdza dwie rzeczy jednocześnie."),

 ("A", 5): dict(
  nr="D1-05", tytul="Pudełko z niespodzianką",
  podtytul="Próby rozwiązania prostego problemu: kombinuję, próbuję, proszę o pomoc",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Rozwiązywanie problemów (ICF d175 · PP 4.2)",
  czas="10 min + sytuacje naturalne", forma="indywidualnie", cykl="codziennie (2 próby)",
  ter="Dziecko w sytuacji zablokowanej zabawy podejmie samodzielnie co najmniej jedną próbę rozwiązania (obróci, pociągnie, potrząśnie), zanim zasygnalizuje potrzebę pomocy, w 3 z 5 prób dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Próbuje sam: obraca, pociąga, potrząsa — zanim odda zadanie dorosłemu."),
    ("M","1 samodzielna próba przed prośbą; 3 z 5 sytuacji dziennie."),
    ("A","Przeszkody dobrane tak, by dało się je pokonać jednym prostym ruchem."),
    ("R","Buduje sprawczość i wytrwałość — fundament uczenia się."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Próby zaaranżowane · rejestr prób i próśb o pomoc · zapis dzienny.",
  pomoce=["pudełka z różnymi zamknięciami (wieczko, rzep, suwak)","atrakcyjne drobiazgi-niespodzianki","słoik z zakrętką (poluzowaną)","karta „próbowałem sam”"],
  metody=["próby zaaranżowane z niespodzianką","zawieszenie pomocy (odczekanie 10 sekund)","komentarz opisowy: „obróciłeś — otworzyło się!”","stopniowanie trudności zamknięć"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — podaje pudełko z niespodzianką: „co tam mieszka?”.","D — ogląda pudełko, próbuje otworzyć."),
    ("N — czeka 10 sekund w milczeniu, nie wyciąga rąk.","D — próbuje różnych ruchów: obrót, pociągnięcie."),
    ("N — po sukcesie nazywa strategię: „potrząsnąłeś i wyszło!”.","D — wyjmuje niespodziankę, cieszy się."),
    ("N — podaje trudniejsze pudełko (rzep, suwak).","D — przenosi wypróbowany ruch na nowe zamknięcie."),
    ("N — przy realnej trudności dnia wskazuje kartę „próbowałem sam”.","D — najpierw próbuje, potem sygnalizuje „pomoc”.")],
  mod2=["jedno zamknięcie na sesję","pokaz rozwiązania na bliźniaczym pudełku","odczekanie skrócone do 5 sekund"],
  mod3=["wspólne ręce na pudełku — dorosły zaczyna ruch, dziecko kończy","niespodzianka widoczna przez przezroczyste wieczko","wzmocnienie każdej, nawet nieskutecznej próby","powiązanie z konspektem D7-33 (proszenie o pomoc)"],
  wskazowka="Najtrudniejsze dla dorosłego jest milczenie: każda podpowiedź w pierwszych 10 sekundach zabiera dziecku okazję do odkrycia własnej strategii."),
}
