# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar IV (poruszanie się), wersja C (6 lat)."""

KONSPEKTY_6_D4 = {
 ("C", 16): dict(
  nr="C4-16", tytul="Skrzyżowane ścieżki",
  podtytul="Koordynacja, równowaga i zwinność jako podstawa czytania i pisania",
  sfera="IV PORUSZANIE SIĘ · Koordynacja (ICF d455 · PP 9.4·3.15)",
  czas="25 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko wykona zestaw pięciu ćwiczeń koordynacyjnych po instrukcji słownej, przekraczając linię środkową ciała, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Wykonuje ćwiczenia naprzemienne z przekroczeniem linii środkowej."),
    ("M","5 ćwiczeń po instrukcji; 3 z 5 zajęć."),
    ("A","Ćwiczenia z zestawu kinezjologicznego, pokazane wcześniej i nazwane."),
    ("R","Koordynacja obustronna warunkuje płynne czytanie i pisanie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Zestaw prób sprawnościowych · karta wyników.",
  pomoce=["karty ćwiczeń z nazwami","wstążki dla obu rąk","muzyka rytmiczna","znaczniki na podłodze","tablica ćwiczeń dnia"],
  metody=["ćwiczenia naprzemienne z przekraczaniem osi ciała","nazwa własna każdego ćwiczenia","instrukcja słowna po etapie pokazu","rytm muzyki porządkujący ruch"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / przygotowanie do szkoły",
  przebieg=[
    ("N — pokazuje ćwiczenie: łokieć do przeciwnego kolana.","D — naśladuje ruch, przekraczając linię ciała."),
    ("N — nadaje ćwiczeniom nazwy i wiesza karty.","D — nazywa ćwiczenia razem z grupą."),
    ("N — wydaje polecenia słowne bez pokazu.","D — wykonuje ćwiczenie na samo polecenie."),
    ("N — dodaje wstążki i muzykę.","D — wykonuje ruchy naprzemienne w rytmie."),
    ("N — prosi o powtórzenie sekwencji z pamięci.","D — odtwarza kolejność pięciu ćwiczeń.")],
  mod2=["3 ćwiczenia zamiast 5","pokaz przed każdym ćwiczeniem","wolniejsze tempo"],
  mod3=["ćwiczenia jednostronne bez przekraczania osi","naśladowanie nauczyciela przez cały czas","2 ćwiczenia","konsultacja z fizjoterapeutą"],
  mod1=["sekwencja 5 ćwiczeń z pamięci w zadanym tempie","utrzymanie równowagi 10 sekund w każdej pozycji","poprowadzenie rozgrzewki dla grupy","wymyślenie własnego ćwiczenia naprzemiennego"],
  wskazowka="Ćwiczenia przekraczające linię środkową ciała są bezpośrednim treningiem dla oka wodzącego po wierszu — to nie rozgrzewka, to przygotowanie do czytania."),

 ("C", 17): dict(
  nr="C4-17", tytul="Prosty kręgosłup przy stoliku",
  podtytul="Dbanie o prawidłową postawę ciała podczas aktywności i pracy",
  sfera="IV PORUSZANIE SIĘ · Postawa ciała (ICF d415 · PP 9.8)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="codziennie",
  ter="Dziecko utrzyma prawidłową postawę przy stoliku przez 10 minut po jednym przypomnieniu wizualnym, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Siedzi prosto, stopy na podłodze, przedramiona na blacie."),
    ("M","10 minut · 1 przypomnienie; 3 z 5 zajęć."),
    ("A","Piktogram prawidłowej pozycji na stoliku; podnóżek dla niższych dzieci."),
    ("R","Postawa przy stoliku decyduje o wytrzymałości podczas pisania."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja pozycji przy stoliku · zapis korekt.",
  pomoce=["piktogram prawidłowej pozycji","podnóżki","lustro do samokontroli","woreczki na głowę do ćwiczeń postawy","krzesła dopasowane wzrostem"],
  metody=["piktogram zamiast ustnego przypominania","ćwiczenia postawy z woreczkiem","samokontrola w lustrze","przerwy ruchowe co 10 minut"],
  rodzaj="Zajęcia wspierające rozwój ruchowy / profilaktyka wad postawy",
  przebieg=[
    ("N — pokazuje piktogram: stopy, plecy, ręce.","D — nazywa trzy elementy prawidłowej pozycji."),
    ("N — prowadzi ćwiczenie z woreczkiem na głowie.","D — chodzi i siada, utrzymując woreczek."),
    ("N — sprawdza wysokość krzeseł i podaje podnóżki.","D — siada z podpartymi stopami."),
    ("N — wskazuje piktogram zamiast upominać.","D — koryguje swoją pozycję po zobaczeniu obrazka."),
    ("N — po 10 minutach prowadzi przerwę ruchową.","D — wstaje, rozciąga się i wraca do pracy.")],
  mod2=["przypomnienie co 5 minut","krótsza praca przy stoliku","podnóżek i podpórka pod plecy"],
  mod3=["praca na stojąco przy sztaludze","częste przerwy ruchowe","fizyczne ustawienie pozycji przez dorosłego","konsultacja z fizjoterapeutą"],
  mod1=["samodzielna korekta postawy przez całą pracę","przypomnienie o postawie koledze","dbanie o postawę także w kąciku czytelniczym","zauważenie źle ustawionego krzesła"],
  wskazowka="Sprawdź wysokość krzeseł, zanim zaczniesz przypominać o postawie — dziecko z nogami w powietrzu nie utrzyma prostych pleców przy najlepszych chęciach."),

 ("C", 18): dict(
  nr="C4-18", tytul="Mistrzowie ołówka",
  podtytul="Prawidłowy chwyt narzędzia pisarskiego i kontrola nacisku przy kreśleniu liter",
  sfera="IV PORUSZANIE SIĘ · Grafomotoryka (ICF d440 · PP 9.6·3.15)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="codziennie",
  ter="Dziecko utrzyma prawidłowy chwyt i nacisk przez całą kartę pracy, bez przedzierania papieru, w 3 z 5 kart, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Trzyma ołówek chwytem trójpalcowym i kontroluje nacisk."),
    ("M","Cała karta bez przedarcia; 3 z 5 kart."),
    ("A","Ołówki trójkątne, nasadki, karta pod folią do kontroli nacisku."),
    ("R","Chwyt i nacisk decydują o tempie pisania w klasie pierwszej."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karty pracy · ocena nacisku i chwytu.",
  pomoce=["ołówki trójkątne i nasadki korygujące","karty pracy grafomotorycznej","kalka do sprawdzania nacisku","gumki do ćwiczeń dłoni","tablica mistrzów ołówka"],
  metody=["rozgrzewka dłoni przed pisaniem","kalka jako wskaźnik nacisku","ćwiczenia przerywane rozluźnianiem dłoni","samoocena własnej pracy"],
  rodzaj="Zajęcia wspierające przygotowanie do nauki pisania",
  przebieg=[
    ("N — prowadzi rozgrzewkę dłoni z gumkami.","D — ćwiczy palce przed pisaniem."),
    ("N — sprawdza chwyt każdego dziecka.","D — ustawia trzy palce na ołówku."),
    ("N — podkłada kalkę pod kartę pracy.","D — kreśli wzory, kontrolując siłę nacisku."),
    ("N — pokazuje kalkę: „tu było za mocno”.","D — poprawia nacisk na kolejnym wzorze."),
    ("N — zaprasza do tablicy mistrzów ołówka.","D — wskazuje swoją najlepszą linię i uzasadnia wybór.")],
  mod2=["nasadka korygująca","krótsza karta pracy","przypomnienie chwytu w połowie"],
  mod3=["kreślenie kredą na tablicy","chwyt korygowany przy każdej próbie","5 minut pisania","ocena napięcia mięśniowego dłoni"],
  mod1=["15 minut pisania w liniaturze ze stałym naciskiem","pisanie wyrazów","utrzymanie chwytu przy zmęczeniu","pomoc koledze w ustawieniu palców"],
  wskazowka="Kalka pod kartą pokazuje nacisk, którego nie widać na wierzchu — to jedyny sposób, by dziecko samo zobaczyło, gdzie przyciska za mocno."),

 ("C", 19): dict(
  nr="C4-19", tytul="Szkoła zapinania",
  podtytul="Czynności precyzyjne: zapinanie guzików i wiązanie sznurowadeł",
  sfera="IV PORUSZANIE SIĘ · Precyzja (ICF d440 · PP 9.7·9.5)",
  czas="20 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko zapnie guziki i suwak we własnym ubraniu oraz wykona pierwszy węzeł sznurowadła, w 3 z 5 wyjść, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Zapina guziki i suwak, wykonuje węzeł na sznurowadle."),
    ("M","Guziki, suwak, węzeł; 3 z 5 wyjść."),
    ("A","Tablice manipulacyjne i buty treningowe poza szatnią."),
    ("R","Samodzielność w zapięciach to warunek startu szkolnego."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja w szatni · karta czynności precyzyjnych.",
  pomoce=["tablice manipulacyjne z guzikami, suwakami, rzepami","but treningowy ze sznurowadłami w dwóch kolorach","instrukcja wiązania w obrazkach","dyplom mistrza zapinania"],
  metody=["trening na tablicy przed sytuacją realną","sznurowadła w dwóch kolorach dla czytelności","instrukcja obrazkowa krok po kroku","przeniesienie na własne ubranie"],
  rodzaj="Kształtowanie samodzielności / rozwój ruchowy",
  przebieg=[
    ("N — rozdaje tablice manipulacyjne.","D — ćwiczy zapinanie guzików na tablicy."),
    ("N — pokazuje suwak: łączenie i zasuwanie.","D — ćwiczy suwak wielokrotnie na tablicy."),
    ("N — podaje but treningowy z dwukolorowym sznurowadłem.","D — wykonuje pierwszy węzeł według instrukcji."),
    ("N — przenosi ćwiczenie na własne ubranie dziecka.","D — zapina guziki i suwak w swojej kurtce."),
    ("N — wręcza dyplom mistrza zapinania.","D — pokazuje umiejętność grupie.")],
  mod2=["duże guziki i gruby suwak","pomoc przy połączeniu suwaka","wyłącznie guziki, bez sznurowadeł"],
  mod3=["zapinanie rzepów","tablica z bardzo dużymi elementami","prowadzenie rąk przy każdej próbie","ocena sprawności manualnej"],
  mod1=["zawiązanie kokardki samodzielnie","zapięcie wszystkich zapięć w czasie grupy","pomoc młodszemu dziecku w zapinaniu","poradzenie sobie z nowym rodzajem zapięcia"],
  wskazowka="Sznurowadło w dwóch kolorach rozwiązuje główną trudność wiązania — dziecko przestaje mylić, która końcówka idzie pod którą."),

 ("C", 20): dict(
  nr="C4-20", tytul="Ruch, który opowiada",
  podtytul="Wyrażanie ruchem charakteru muzyki i tworzenie improwizacji",
  sfera="IV PORUSZANIE SIĘ · Ekspresja ruchowa (ICF d455 · PP 8.4)",
  czas="25 min", forma="cała grupa", cykl="2× w tygodniu",
  ter="Dziecko dopasuje ruch do charakteru muzyki (wolno–szybko, cicho–głośno) bez pokazu nauczyciela, w 3 z 5 zajęć, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Dobiera rodzaj ruchu do charakteru słuchanego utworu."),
    ("M","Dopasowanie bez pokazu; 3 z 5 zajęć."),
    ("A","Utwory wyraźnie kontrastowe; chusty i wstążki jako przedłużenie ruchu."),
    ("R","Ekspresja ruchowa łączy słuchanie, interpretację i motorykę."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja zajęć rytmicznych · zapis improwizacji.",
  pomoce=["nagrania kontrastowych utworów","chusty i wstążki","instrumenty do sygnałów","karty nastrojów muzyki","aparat do nagrania improwizacji"],
  metody=["kontrast utworów zamiast opisu słownego","chusta jako przedłużenie ruchu","improwizacja bez wzoru","nagranie i wspólne obejrzenie"],
  rodzaj="Zajęcia artystyczne / rozwój ruchowy",
  przebieg=[
    ("N — puszcza dwa kontrastowe utwory.","D — słucha i wskazuje kartę nastroju."),
    ("N — rozdaje chusty: „pokażcie tę muzykę”.","D — porusza się zgodnie z charakterem utworu."),
    ("N — zmienia utwór bez zapowiedzi.","D — zmienia rodzaj ruchu wraz z muzyką."),
    ("N — proponuje improwizację indywidualną.","D — tworzy własną etiudę ruchową do utworu."),
    ("N — nagrywa i odtwarza improwizacje grupie.","D — ogląda nagranie i nazywa swój pomysł.")],
  mod2=["dwa kontrastowe utwory zamiast czterech","ruch pokazany przed każdym utworem","improwizacja w parze"],
  mod3=["naśladowanie ruchu nauczyciela","jeden rodzaj ruchu do jednego utworu","krótszy fragment muzyczny","możliwość obserwowania z boku"],
  mod1=["własna improwizacja zaprezentowana grupie","układ ruchowy do całego utworu","reakcja na zmiany tempa w obrębie jednego utworu","poprowadzenie improwizacji dla grupy"],
  wskazowka="Nie pokazuj ruchu przed słuchaniem — pokaz zamienia interpretację w naśladownictwo i odbiera dziecku moment własnego odczytania muzyki."),
}
