# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VIII (główne obszary życia: edukacja i zabawa), wersja A (3–4 lata)."""

KONSPEKTY_D8 = {
 ("A", 34): dict(
  nr="D8-34", tytul="Moje miejsce w grupie",
  podtytul="Adaptacja do grupy przedszkolnej i nowego otoczenia",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Adaptacja (ICF d815 · PP Zad.2·1.16)",
  czas="15 min", forma="mała grupa", cykl="codziennie (pierwsze tygodnie)",
  ter="Dziecko weźmie udział w trzech kolejnych elementach rytmu dnia bez wycofania się z grupy, korzystając z planu obrazkowego, w 3 z 5 dni, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Uczestniczy w kolejnych aktywnościach, pozostając z grupą."),
    ("M","3 elementy rytmu dnia; 3 z 5 dni."),
    ("A","Stałe miejsce-baza i plan obrazkowy dnia zmniejszają niepewność."),
    ("R","Adaptacja warunkuje korzystanie z całej oferty przedszkola."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta adaptacji · obserwacja całodzienna.",
  pomoce=["zdjęcie dziecka na stałym miejscu (baza)","plan dnia w obrazkach","album ze zdjęciami sali i nauczycieli","pudełko „mój skarb z domu”"],
  metody=["stałe miejsce jako punkt oparcia","przewidywalny plan dnia","stopniowe włączanie w aktywności","przedmiot przejściowy dostępny na życzenie"],
  rodzaj="Wsparcie adaptacyjne / pomoc p-p",
  przebieg=[
    ("N — pokazuje dziecku jego miejsce ze zdjęciem: „to twoja baza”.","D — siada na swoim miejscu, rozgląda się po sali."),
    ("N — przechodzi z dzieckiem po planie dnia: co teraz, co potem.","D — wskazuje aktualny obrazek na planie."),
    ("N — zaprasza do pierwszej aktywności, siedząc obok.","D — bierze udział, wracając wzrokiem do bazy."),
    ("N — przy przejściu przypomina plan i idzie obok.","D — przechodzi do kolejnej aktywności z grupą."),
    ("N — na koniec dnia przegląda z dzieckiem, co się udało.","D — wskazuje na planie, w czym brało udział.")],
  mod2=["udział w 2 elementach dnia","baza tuż przy nauczycielu","możliwość obserwowania z boku przed dołączeniem"],
  mod3=["stały opiekun-przewodnik przez cały dzień","skrócony pobyt uzgodniony z rodzicami","przedmiot z domu stale przy dziecku","konsultacja zespołu i rozmowa z rodzicami"],
  mod1=["pełny dzień, także w sytuacjach zmienionych (zastępstwo, inna sala)","oprowadzenie nowego dziecka po sali","udział w wyjściu poza teren przedszkola","opowiedzenie rodzicowi o swoim dniu"],
  wskazowka="Stałe miejsce ze zdjęciem to kotwica — dziecko, które wie, dokąd zawsze może wrócić, szybciej odważa się odejść od tego miejsca."),

 ("A", 35): dict(
  nr="D8-35", tytul="Kącik lalek i garaż",
  podtytul="Zabawa swobodna i pierwsze zabawy tematyczne z prostą rolą",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Zabawa tematyczna (ICF d880 · PP WSR·1.12)",
  czas="15 min", forma="mała grupa (2–3 dzieci)", cykl="codziennie",
  ter="Dziecko podejmie prostą rolę w zabawie zaproponowaną przez dorosłego („jestem mamą”, „jestem kierowcą”) i utrzyma ją przez 5 minut, w 3 z 5 zabaw, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Przyjmuje rolę i wykonuje w niej co najmniej 2 czynności."),
    ("M","Rola utrzymana 5 minut; 3 z 5 zabaw."),
    ("A","Atrybut roli (chusta, czapka, kierownica) czyni rolę widoczną."),
    ("R","Zabawa w role rozwija mowę, myślenie i kompetencje społeczne."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja zabawy swobodnej · 15 minut · zapis czasu w roli.",
  pomoce=["atrybuty ról: chusta, czapka, kierownica, torebka","lalki, wózek, naczynia, samochody","kąciki tematyczne wyraźnie oddzielone","zdjęcia ról na ścianie kącika"],
  metody=["dorosły jako współgracz, nie kierownik","atrybut jako wyzwalacz roli","modelowanie czynności typowych dla roli","rozbudowywanie fabuły pytaniem"],
  rodzaj="Zajęcia wspierające rozwój społeczny i poznawczy",
  przebieg=[
    ("N — zakłada chustę: „jestem mamą, karmię córeczkę”.","D — obserwuje, bierze lalkę do ręki."),
    ("N — podaje dziecku atrybut: „będziesz tatą?”.","D — zakłada czapkę i przyjmuje rolę."),
    ("N — modeluje 2 czynności w roli: kąpiel, spanie.","D — powtarza czynności na swojej lalce."),
    ("N — pyta w roli: „co teraz zrobimy z córeczką?”.","D — proponuje własną czynność i wykonuje ją."),
    ("N — kończy zabawę w roli: „nasze dzieci już śpią”.","D — odkłada atrybut i porządkuje kącik.")],
  mod2=["rola z jedną czynnością","zabawa w parze z dorosłym","czas roli skrócony do 2 minut"],
  mod3=["czynności na przedmiotach zgodnie z przeznaczeniem (karmi misia łyżką)","dorosły prowadzi całą fabułę","atrybut zakładany przez dorosłego","obserwacja poziomu zabawy (manipulacja czy symbol)"],
  mod1=["samodzielny wybór i nazwanie roli","scenka z rówieśnikiem przez 10 minut","rozbudowa fabuły o nowe wątki","zaproszenie kolegi do wspólnej roli"],
  wskazowka="Wejdź do zabawy w roli, a nie obok niej — pytanie „w co się bawisz?” przerywa zabawę, pytanie „mamo, co ugotujemy?” ją rozwija."),

 ("A", 36): dict(
  nr="D8-36", tytul="Dywanik zajęć",
  podtytul="Uczestniczenie w krótkich zajęciach zorganizowanych dla grupy",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Zajęcia kierowane (ICF d815 · PP 1.2)",
  czas="10 min", forma="cała grupa", cykl="codziennie",
  ter="Dziecko weźmie udział w całym 10-minutowym zajęciu, wykonując 2 zadania kierowane i pozostając na dywanie, w 3 z 5 zajęć, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Siedzi na swojej poduszce i wykonuje zadania zajęcia."),
    ("M","10 minut · 2 zadania; 3 z 5 zajęć."),
    ("A","Wyznaczona poduszka i widoczny plan zajęcia (3 obrazki)."),
    ("R","Udział w zajęciach kierowanych przygotowuje do roli ucznia."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja zajęć kierowanych · zapis dzienny udziału.",
  pomoce=["poduszki ze znaczkami dzieci","plan zajęcia z 3 obrazków","pacynka prowadząca zajęcie","pudełko z materiałami do zadań"],
  metody=["wyznaczone miejsce dla każdego dziecka","plan zajęcia w obrazkach","przeplatanie siedzenia z ruchem","zadanie z materiałem w rękach dziecka"],
  rodzaj="Zajęcia dydaktyczne / pomoc p-p",
  przebieg=[
    ("N — zaprasza piosenką i wskazuje poduszki ze znaczkami.","D — siada na swojej poduszce."),
    ("N — pokazuje plan: 3 obrazki, co będzie po kolei.","D — patrzy na plan, wskazuje pierwszy obrazek."),
    ("N — prowadzi pierwsze zadanie z materiałem do rąk.","D — wykonuje zadanie na swoim materiale."),
    ("N — wplata krótką zabawę ruchową między zadania.","D — wstaje, wykonuje ruch, wraca na poduszkę."),
    ("N — kończy zdjęciem obrazków z planu: „zrobiliśmy wszystko”.","D — zdejmuje ostatni obrazek, odkłada materiał.")],
  mod2=["udział przez 5 minut zajęcia","poduszka obok nauczyciela","jedno zadanie zamiast dwóch"],
  mod3=["udział w jednym elemencie zajęcia","możliwość siedzenia na kolanach dorosłego","krzesełko zamiast poduszki (wyraźniejsza granica)","obserwacja przyczyn wychodzenia (sensoryka, zmęczenie)"],
  mod1=["aktywny udział w 15-minutowym zajęciu","zgłaszanie się do odpowiedzi i czekanie na kolej","pomoc w rozdaniu materiałów","zaproponowanie zabawy na koniec zajęcia"],
  wskazowka="Materiał w rękach dziecka trzyma je na dywanie skuteczniej niż przypomnienia — puste ręce trzylatka same znajdą sobie zajęcie."),

 ("A", 37): dict(
  nr="D8-37", tytul="Budowniczowie",
  podtytul="Inicjowanie zabaw konstrukcyjnych z klocków i różnych materiałów",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Zabawa konstrukcyjna (ICF d880 · PP 6.3)",
  czas="15 min", forma="mała grupa (2–3 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko zbuduje prostą konstrukcję (dom, garaż) z materiału wybranego samodzielnie i nazwie ją, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Buduje konstrukcję z co najmniej 5 elementów i nadaje jej nazwę."),
    ("M","Konstrukcja nazwana; 3 z 5 prób."),
    ("A","Materiał dostępny w otwartych pojemnikach, na dużym dywanie."),
    ("R","Konstruowanie rozwija myślenie przestrzenne i planowanie."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Zdjęcie wytworu · teczka obserwacji.",
  pomoce=["klocki różnej wielkości i faktury","rolki, pudełka, kubeczki","zdjęcia budowli jako inspiracja","tabliczka do podpisania budowli"],
  metody=["swobodny wybór materiału","inspiracja zdjęciem, nie wzorem do skopiowania","komentarz opisowy zamiast oceny","wystawa budowli i nadawanie nazw"],
  rodzaj="Zajęcia wspierające rozwój poznawczy / pomoc p-p",
  przebieg=[
    ("N — rozkłada materiał i siada obok, buduje własną wieżę.","D — obserwuje i sięga po klocki."),
    ("N — pokazuje 2 zdjęcia budowli: „garaż czy dom?”.","D — wybiera pomysł i zaczyna budować."),
    ("N — komentuje opisowo: „postawiłeś duży na małym”.","D — kontynuuje budowanie, dokłada elementy."),
    ("N — pyta: „jak nazwiemy twoją budowlę?”.","D — nazywa budowlę, pokazuje jej części."),
    ("N — fotografuje i stawia tabliczkę z nazwą.","D — pokazuje budowlę grupie, opowiada o niej.")],
  mod2=["materiał ograniczony do jednego rodzaju klocków","pokaz pierwszych 2 elementów","budowanie w parze z dorosłym"],
  mod3=["łączenie 3 elementów po pokazie","materiał podawany do ręki","duże, lekkie klocki piankowe","wzmocnienie każdej próby połączenia"],
  mod1=["zaplanowanie budowli słowem przed budowaniem","wykorzystanie budowli w zabawie tematycznej","budowanie według wzoru obrazkowego","wspólna budowla z kolegą z podziałem zadań"],
  wskazowka="Buduj obok dziecka, nie za nie — własna wieża nauczyciela jest zaproszeniem, a poprawiona wieża dziecka bywa końcem zabawy."),

 ("A", 38): dict(
  nr="D8-38", tytul="Bawimy się razem",
  podtytul="Włączanie się w zabawy grupowe prowadzone przez nauczyciela",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Zabawy grupowe (ICF d880 · PP 1.2·9.1)",
  czas="12 min", forma="cała grupa", cykl="3× w tygodniu",
  ter="Dziecko wykona swoją część zabawy grupowej po jednym przypomnieniu zasad, pozostając w zabawie do jej końca, w 3 z 5 zabaw, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Bierze udział w zabawie z prostą regułą i czeka na swoją kolej."),
    ("M","Udział do końca zabawy · 1 przypomnienie; 3 z 5 zabaw."),
    ("A","Zasada jedna, pokazana obrazkiem; zabawa krótka i powtarzalna."),
    ("R","Zabawy grupowe uczą reguł i przynależności do grupy."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Obserwacja zabaw grupowych 3× w tygodniu · karta udziału.",
  pomoce=["chusta animacyjna","obrazek zasady zabawy","znaczniki miejsc w kole","instrumenty do sygnałów"],
  metody=["zabawy z jedną prostą regułą","chusta jako narzędzie wspólnego działania","krótkie rundy z szybkim powrotem kolejki","modelowanie przez dorosłego w kole"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — rozkłada chustę i pokazuje obrazek zasady: „trzymamy i falujemy”.","D — chwyta chustę na swoim znaczniku."),
    ("N — prowadzi falę, nazywa: „wolno – szybko – stop”.","D — dostosowuje ruch do polecenia."),
    ("N — wprowadza kolejkę: „teraz biegnie ten, kogo zawołam”.","D — czeka na swoje imię, potem przebiega pod chustą."),
    ("N — przypomina zasadę obrazkiem przy trudności.","D — wraca do zabawy, powtarza regułę."),
    ("N — kończy wspólnym schowaniem chusty.","D — pomaga złożyć chustę i wraca na miejsce.")],
  mod2=["udział przez 2 rundy zabawy","miejsce obok nauczyciela","kolejka skrócona (dziecko wywoływane jako drugie)"],
  mod3=["zabawa w małej grupie (3 dzieci)","dorosły trzyma chustę razem z dzieckiem","możliwość obserwowania rundy przed dołączeniem","krótsze rundy i natychmiastowe wzmocnienie"],
  mod1=["zabawa z 2–3 regułami","dziecko prowadzi fragment zabawy","przypominanie zasad innym dzieciom","akceptacja wyniku rywalizacji w prostej grze"],
  wskazowka="Krótka kolejka jest warunkiem sukcesu — jeśli dziecko czeka dłużej niż minutę na swoją turę, zabawa grupowa zamienia się w ćwiczenie cierpliwości."),
}
