# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VII (wzajemne kontakty), wersja C (6 lat)."""

KONSPEKTY_6_D7 = {
 ("C", 30): dict(
  nr="C7-30", tytul="Rada grupy",
  podtytul="Udział w podejmowaniu decyzji i akceptowanie wspólnych rozstrzygnięć",
  sfera="VII WZAJEMNE KONTAKTY · Decyzje grupowe (ICF d720 · PP 1.3·1.4)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko zaakceptuje decyzję większości bez protestu i włączy się w wybraną aktywność, w 3 z 5 decyzji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Głosuje, przyjmuje wynik i uczestniczy w wybranej aktywności."),
    ("M","Bez protestu; 3 z 5 decyzji."),
    ("A","Rytuał rady grupy: propozycje, głosowanie, ogłoszenie wyniku."),
    ("R","Akceptowanie decyzji większości to podstawa życia w grupie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Krąg decyzyjny · rejestr reakcji na wynik głosowania.",
  pomoce=["tablica propozycji","żetony do głosowania","urna wyborcza","protokół rady grupy","dzwonek otwierający radę"],
  metody=["stały rytuał rady grupy","głosowanie żetonami","zapisywanie decyzji w protokole","przypomnienie, że każdy głos się liczy"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i obywatelskie",
  przebieg=[
    ("N — otwiera radę grupy dzwonkiem.","D — zgłasza swoją propozycję do tablicy."),
    ("N — zapisuje wszystkie propozycje.","D — ogląda listę i wybiera swój głos."),
    ("N — rozdaje żetony do głosowania.","D — wrzuca żeton do urny przy wybranej opcji."),
    ("N — liczy głosy razem z dziećmi i ogłasza wynik.","D — przyjmuje wynik, także niezgodny z własnym głosem."),
    ("N — zapisuje decyzję w protokole rady.","D — włącza się w realizację wybranej aktywności.")],
  mod2=["wybór z dwóch propozycji","uprzedzenie przed ogłoszeniem wyniku","możliwość zgłoszenia propozycji przez dorosłego"],
  mod3=["głosowanie bez publicznego ogłaszania wyniku","aktywność alternatywna dla dziecka","przygotowanie na możliwą przegraną","wsparcie w regulacji emocji"],
  mod1=["przedstawienie propozycji z uzasadnieniem","wyjaśnienie, dlaczego decyzja większości jest wiążąca","prowadzenie rady grupy","pogodzenie się z przegraną i wsparcie zwycięskiej propozycji"],
  wskazowka="Zapisuj decyzje w protokole i wracaj do nich — rada grupy działa dopiero wtedy, gdy dzieci widzą, że ich głosowanie naprawdę coś zmieniło."),

 ("C", 31): dict(
  nr="C7-31", tytul="Kodeks naszej grupy",
  podtytul="Przestrzeganie zasad i szanowanie różnych upodobań oraz potrzeb dzieci",
  sfera="VII WZAJEMNE KONTAKTY · Zasady i różnorodność (ICF d720 · PP 1.6·1.8)",
  czas="25 min", forma="cała grupa", cykl="1× w tygodniu",
  ter="Dziecko przestrzega zasad kodeksu grupy po jednym przypomnieniu grupowym, w 3 z 5 dni, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Stosuje zasady kodeksu i uwzględnia potrzeby innych dzieci."),
    ("M","1 przypomnienie grupowe; 3 z 5 dni."),
    ("A","Kodeks wypracowany przez dzieci i podpisany przez wszystkich."),
    ("R","Wspólny kodeks buduje kulturę grupy i szacunek dla odmienności."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kodeks grupy · rejestr odstępstw i przypomnień.",
  pomoce=["plakat kodeksu z podpisami dzieci","karty sytuacji do omówienia","zdjęcia dzieci o różnych potrzebach","tablica „różnimy się”","pieczątka zgody"],
  metody=["kodeks współtworzony i podpisany przez dzieci","omawianie sytuacji z życia grupy","rozmowa o różnych potrzebach","cotygodniowy przegląd kodeksu"],
  rodzaj="Zajęcia wspierające kompetencje społeczne",
  przebieg=[
    ("N — pyta: „jakich zasad potrzebujemy w naszej grupie?”.","D — zgłasza propozycje zasad."),
    ("N — zapisuje zasady i prosi o podpisy.","D — podpisuje kodeks swoim znakiem."),
    ("N — omawia sytuację: kolega potrzebuje ciszy.","D — proponuje, jak uwzględnić tę potrzebę."),
    ("N — wskazuje kodeks przy trudnej sytuacji.","D — koryguje zachowanie, odwołując się do zasady."),
    ("N — prowadzi cotygodniowy przegląd kodeksu.","D — ocenia, które zasady działają dobrze.")],
  mod2=["dwie zasady w centrum uwagi","przypomnienie indywidualne przed sytuacją","kodeks skrócony do trzech punktów"],
  mod3=["jedna zasada wprowadzana na dwa tygodnie","piktogram przy dziecku","natychmiastowe wzmocnienie za zastosowanie","ustalenie zasad indywidualnych"],
  mod1=["przestrzeganie zasad i uwzględnianie odmiennych potrzeb kolegów","zaproponowanie nowej zasady","wyjaśnienie kodeksu nowemu dziecku","reagowanie, gdy ktoś łamie zasadę"],
  wskazowka="Podpis dziecka pod kodeksem nie jest ozdobą — to moment, w którym zasada przestaje być poleceniem dorosłego, a staje się zobowiązaniem własnym."),

 ("C", 32): dict(
  nr="C7-32", tytul="Konsekwencje moich wyborów",
  podtytul="Zwroty grzecznościowe, przepraszanie i przewidywanie skutków zachowań",
  sfera="VII WZAJEMNE KONTAKTY · Odpowiedzialność (ICF d710 · PP 1.5·2.4)",
  czas="25 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko przeprosi z własnej inicjatywy i nazwie, co zrobiło niewłaściwie, w 3 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Przeprasza i nazywa swoje zachowanie oraz jego skutek."),
    ("M","Z własnej inicjatywy; 3 z 5 sytuacji."),
    ("A","Schemat przeprosin: co zrobiłem – co poczułeś – co naprawię."),
    ("R","Naprawianie relacji jest ważniejsze niż samo słowo przepraszam."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta sytuacji społecznych · zapis wypowiedzi dziecka.",
  pomoce=["plakat schematu przeprosin","karty sytuacji: co się stanie, jeśli…","kącik naprawy relacji","historyjki obrazkowe o skutkach","dziennik dobrych naprawień"],
  metody=["schemat przeprosin zamiast pustego słowa","przewidywanie skutków przed działaniem","naprawianie szkody, nie tylko przepraszanie","omawianie sytuacji na spokojnie, po czasie"],
  rodzaj="Zajęcia wspierające kompetencje społeczne",
  przebieg=[
    ("N — pokazuje kartę: „co się stanie, jeśli zabierzesz?”.","D — przewiduje skutek zachowania."),
    ("N — przedstawia schemat przeprosin.","D — nazywa trzy kroki: zrobiłem – poczułeś – naprawię."),
    ("N — odgrywa scenkę z realną sytuacją z sali.","D — ćwiczy przeprosiny według schematu."),
    ("N — pyta: „jak można to naprawić?”.","D — proponuje konkretne naprawienie szkody."),
    ("N — zapisuje w dzienniku dobrych naprawień.","D — opowiada, co naprawił i jak to przyjęto.")],
  mod2=["schemat dwuelementowy","przeprosiny po podpowiedzi","sytuacja omawiana zaraz po zdarzeniu"],
  mod3=["użycie słowa przepraszam po modelowaniu","rozdzielenie stron przed rozmową","krótki komunikat","wsparcie w regulacji emocji"],
  mod1=["przewidzenie skutku przed działaniem i zmiana zachowania","przeprosiny z naprawieniem szkody z własnej inicjatywy","nazwanie uczuć drugiej osoby","pomoc koledze w naprawieniu relacji"],
  wskazowka="Pytanie „jak to naprawisz” zmienia przeprosiny w działanie — samo słowo bywa wyuczoną formułką, naprawienie szkody nigdy nią nie jest."),

 ("C", 33): dict(
  nr="C7-33", tytul="Pogotowie pomocne",
  podtytul="Pomaganie innym w zadaniu i wspieranie w smutku oraz bezradności",
  sfera="VII WZAJEMNE KONTAKTY · Pomaganie (ICF d710 · PP 1.10·1.11)",
  czas="25 min", forma="mała grupa (4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko zauważy trudność kolegi wskazaną przez dorosłego i zaproponuje jeden sposób pomocy, w 3 z 5 sytuacji, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje trudność kolegi i proponuje konkretną pomoc."),
    ("M","1 propozycja pomocy; 3 z 5 sytuacji."),
    ("A","Karty sposobów pomagania; zasada pomagam, nie wyręczam."),
    ("R","Pomaganie buduje więzi i poczucie własnej wartości."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Obserwacja zachowań prospołecznych · rejestr.",
  pomoce=["karty sposobów pomagania (podpowiem, przytrzymam, pocieszę)","opaski pogotowia pomocnego","tablica dobrych uczynków","historyjki o bezradności","pudełko podziękowań"],
  metody=["zasada pomagam, nie wyręczam","karty konkretnych sposobów pomocy","rotacyjny dyżur pogotowia pomocnego","podziękowania od dzieci, nie od dorosłego"],
  rodzaj="Zajęcia wspierające kompetencje społeczne",
  przebieg=[
    ("N — pokazuje karty sposobów pomagania.","D — nazywa sposoby: podpowiem, przytrzymam, pocieszę."),
    ("N — wskazuje kolegę, który ma trudność.","D — zauważa, na czym polega trudność."),
    ("N — przypomina zasadę: pomagam, nie wyręczam.","D — proponuje pomoc, nie robiąc zadania za kolegę."),
    ("N — obserwuje i docenia sposób pomocy.","D — pomaga koledze w wybrany sposób."),
    ("N — otwiera pudełko podziękowań.","D — wrzuca podziękowanie dla dziecka, które pomogło.")],
  mod2=["jeden sposób pomocy do zastosowania","trudność kolegi nazwana przez dorosłego","pomoc w parze z dorosłym"],
  mod3=["podanie potrzebnego przedmiotu na prośbę","pomoc na wyraźne polecenie","krótka, konkretna czynność","wsparcie w rozpoznawaniu emocji innych"],
  mod1=["samodzielne zauważenie trudności i udzielenie adekwatnej pomocy","pocieszenie smutnego kolegi","zaproponowanie pomocy młodszej grupie","nauczenie kolegi sposobu, zamiast zrobienia za niego"],
  wskazowka="Zasada pomagam, nie wyręczam wymaga ćwiczenia — sześciolatek najchętniej zrobi zadanie za kolegę, bo tak jest szybciej i przyjemniej."),

 ("C", 34): dict(
  nr="C7-34", tytul="Przyjaźń i słowa, które ranią",
  podtytul="Budowanie trwalszych przyjaźni i rozpoznawanie zachowań krzywdzących",
  sfera="VII WZAJEMNE KONTAKTY · Przyjaźń (ICF d750 · PP 1.8)",
  czas="25 min", forma="mała grupa (4–6 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko nazwie trzy zachowania krzywdzące i powie, co czuje osoba pokrzywdzona, w 3 z 5 rozmów, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje zachowania raniące i nazywa uczucia pokrzywdzonego."),
    ("M","3 zachowania · nazwanie uczuć; 3 z 5 rozmów."),
    ("A","Historyjki społeczne i doświadczenie z pogniecionym sercem."),
    ("R","Rozpoznanie krzywdy jest warunkiem reagowania na nią."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Socjogram · karta sytuacji społecznych.",
  pomoce=["papierowe serce do gniecenia","karty zachowań: pomocne i raniące","historyjki o przyjaźni","tablica przyjaciół grupy","książka o wykluczeniu"],
  metody=["doświadczenie z pogniecionym sercem","sortowanie zachowań na pomocne i raniące","rozmowa o wykluczeniu","budowanie mapy przyjaźni w grupie"],
  rodzaj="Zajęcia wspierające kompetencje społeczne i emocjonalne",
  przebieg=[
    ("N — rozdaje papierowe serca: „to serce kolegi”.","D — trzyma serce w dłoniach."),
    ("N — mówi raniące zdanie, prosi o zgniecenie serca.","D — gniecie serce przy każdym raniącym słowie."),
    ("N — prosi o wyprostowanie serca.","D — próbuje wygładzić serce, widzi trwałe zagniecenia."),
    ("N — sortuje z dziećmi karty zachowań.","D — wskazuje zachowania raniące i pomocne."),
    ("N — pyta, co czuje osoba pokrzywdzona.","D — nazywa uczucia i proponuje wsparcie.")],
  mod2=["dwa zachowania do nazwania","sortowanie z podpowiedzią","historyjka bardzo konkretna"],
  mod3=["wskazanie zachowania raniącego na obrazku","rozpoznanie emocji smutku","krótka scenka","praca nad rozumieniem emocji"],
  mod1=["utrzymanie trwałej relacji przez miesiąc i reagowanie na krzywdę w grupie","zauważenie dziecka wykluczonego i zaproszenie go","rozmowa z kolegą o tym, co go zraniło","zaproponowanie zasady chroniącej przed wykluczeniem"],
  wskazowka="Zagnieceń na sercu nie da się wyprostować i to jest cała lekcja — obraz zostaje w pamięci dłużej niż każde tłumaczenie o dobrych słowach."),
}
