# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VIII (główne obszary życia), wersja C (6 lat)."""

KONSPEKTY_6_D8 = {
 ("C", 35): dict(
  nr="C8-35", tytul="Zespół projektowy",
  podtytul="Gotowość do roli ucznia: praca w zespole i prezentacja efektów",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Praca zespołowa (ICF d815 · PP 1.2·DE-R.7)",
  czas="30 min", forma="zespoły 3–4-osobowe", cykl="2× w tygodniu",
  ter="Dziecko wykona swoją część zadania zespołowego i pokaże efekt grupie, mówiąc jedno zdanie, w 3 z 5 zadań, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Realizuje przydzieloną część i prezentuje efekt pracy zespołu."),
    ("M","Własna część + 1 zdanie prezentacji; 3 z 5 zadań."),
    ("A","Karta podziału ról; prezentacja przy tablicy zespołu."),
    ("R","Praca zespołowa i prezentacja to wprost kompetencje szkolne."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta pracy zespołowej · zapis prezentacji.",
  pomoce=["karty podziału ról w zespole","materiały projektowe","tablice zespołów","mikrofon do prezentacji","karta oceny współpracy"],
  metody=["projekt z podziałem ról","narada zespołu przed pracą","prezentacja każdego zespołu","ocena współpracy, nie tylko efektu"],
  rodzaj="Zajęcia dydaktyczne / przygotowanie do szkoły",
  przebieg=[
    ("N — przedstawia zadanie projektowe zespołom.","D — słucha zadania i dołącza do zespołu."),
    ("N — rozdaje karty podziału ról.","D — uzgadnia z zespołem, kto co robi."),
    ("N — obserwuje pracę, wspiera przy sporze.","D — wykonuje swoją część projektu."),
    ("N — zaprasza zespoły do prezentacji.","D — prezentuje efekt, mówiąc o swojej części."),
    ("N — prosi o ocenę współpracy w zespole.","D — mówi, co się udało w pracy zespołu.")],
  mod2=["zespół 2-osobowy","role zaproponowane przez nauczyciela","prezentacja przez pokazanie pracy"],
  mod3=["własna część przy wspólnym stole","prezentacja wyłącznie dla nauczyciela","krótkie zadanie","wsparcie w komunikacji z rówieśnikami"],
  mod1=["uzgodnienie podziału pracy i prezentacja wspólnego efektu","rola koordynatora zespołu","prezentacja przed inną grupą","ocena wkładu każdego członka zespołu"],
  wskazowka="Oceniaj współpracę osobno od efektu — zespół z ładną makietą i awanturą przy stole nie osiągnął celu, który tu ćwiczymy."),

 ("C", 36): dict(
  nr="C8-36", tytul="Skończone i pokazane",
  podtytul="Doprowadzanie aktywności do efektu i wyrażanie satysfakcji z pracy",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Efekt pracy (ICF d815 · PP 2.6·2.7)",
  czas="25 min", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko doprowadzi zadanie do końca bez przypomnień i oceni je na skali obrazkowej, w 3 z 5 zadań, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Kończy zadanie i dokonuje samooceny efektu."),
    ("M","Bez przypomnień · samoocena; 3 z 5 zadań."),
    ("A","Skala samooceny i miejsce na prace skończone."),
    ("R","Doprowadzanie pracy do końca to podstawa poczucia sprawstwa."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta samooceny wytworu · teczka prac.",
  pomoce=["skala samooceny (3 buźki)","teczki prac skończonych","tablica wystawy","karta „z czego jestem dumny”","stempel ukończenia"],
  metody=["samoocena zamiast oceny dorosłego","wystawa prac skończonych","pytanie o powód dumy","teczka pokazująca postęp w czasie"],
  rodzaj="Zajęcia dydaktyczne / przygotowanie do szkoły",
  przebieg=[
    ("N — przedstawia zadanie i kryterium ukończenia.","D — nazywa, kiedy praca będzie skończona."),
    ("N — odsuwa się, nie przypomina o pracy.","D — pracuje samodzielnie do końca."),
    ("N — podaje skalę samooceny.","D — ocenia swoją pracę na skali."),
    ("N — pyta: „z czego jesteś najbardziej dumny?”.","D — wskazuje najlepszy fragment i uzasadnia."),
    ("N — przybija stempel ukończenia.","D — wkłada pracę do teczki lub na wystawę.")],
  mod2=["jedno przypomnienie w połowie","zadanie krótsze","samoocena z pytaniami pomocniczymi"],
  mod3=["zadanie dwuetapowe z odhaczaniem","przypomnienia przy każdym etapie","wzmocnienie po każdym kroku","krótszy czas pracy"],
  mod1=["ukończenie zadania, samoocena i wskazanie, co poprawi","porównanie z pracą sprzed miesiąca","dokończenie pracy przerwanej","zaprezentowanie pracy grupie"],
  wskazowka="Pytaj, z czego dziecko jest dumne, zamiast chwalić za nie — duma nazwana samodzielnie buduje motywację trwalszą niż każda pochwała dorosłego."),

 ("C", 37): dict(
  nr="C8-37", tytul="Turniej gier z regułami",
  podtytul="Udział w grach z regułami i nauka zasad współzawodnictwa",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Gry z regułami (ICF d880 · PP 1.6·9.2)",
  czas="30 min", forma="zespoły", cykl="2× w tygodniu",
  ter="Dziecko zagra w grę z dwiema lub trzema regułami, czekając na swoją kolej przez całą rozgrywkę, w 3 z 5 gier, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Przestrzega reguł gry i czeka na swoją kolej do końca."),
    ("M","2–3 reguły · cała rozgrywka; 3 z 5 gier."),
    ("A","Reguły spisane obrazkiem; sędzia spośród dzieci."),
    ("R","Gry z regułami uczą norm, przegrywania i strategii."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Gry planszowe i ruchowe · karta przestrzegania reguł.",
  pomoce=["gry planszowe i ruchowe","tablica reguł w obrazkach","gwizdek sędziego","tabela turniejowa","medale fair play"],
  metody=["reguły spisane przed grą","sędzia wybierany spośród dzieci","turniej zespołowy, nie indywidualny","nagroda za fair play, nie za wynik"],
  rodzaj="Zajęcia wspierające kompetencje społeczne",
  przebieg=[
    ("N — przedstawia grę i spisuje reguły na tablicy.","D — powtarza reguły własnymi słowami."),
    ("N — wyznacza sędziego spośród dzieci.","D — pełni rolę sędziego lub gracza."),
    ("N — prowadzi rozgrywkę, pilnując kolejności.","D — czeka na swoją kolej przez całą grę."),
    ("N — rozstrzyga spory, odwołując się do tablicy reguł.","D — akceptuje rozstrzygnięcie zgodne z regułami."),
    ("N — wręcza medal fair play.","D — wskazuje kolegę, który grał uczciwie.")],
  mod2=["gra z jedną regułą","krótsza rozgrywka","dziecko drugie w kolejce"],
  mod3=["gra kooperacyjna bez rywalizacji","gra w parze z dorosłym","3 rundy","praca nad odraczaniem"],
  mod1=["gra zespołowa z regułami, przypominanie ich innym","przyjęcie wyniku rywalizacji","rola sędziego całego turnieju","wymyślenie reguły do znanej gry"],
  wskazowka="Medal za fair play przyznawany przez dzieci zmienia hierarchię turnieju — wygrywa nie ten, kto był pierwszy, lecz ten, kto grał uczciwie."),

 ("C", 38): dict(
  nr="C8-38", tytul="Sklep z prawdziwą kasą",
  podtytul="Rozpoznawanie monet i banknotów oraz proste obliczenia pieniężne",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Pieniądze (ICF d860 · PP 4.15·1.14)",
  czas="30 min", forma="para dzieci", cykl="2× w tygodniu",
  ter="Dziecko rozpozna monety 1, 2 i 5 zł, wyjaśni, do czego służą pieniądze, i zapłaci w kąciku sklep, w 3 z 5 zabaw, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje monety, nazywa ich wartość i dokonuje zakupu."),
    ("M","3 monety · zakup; 3 z 5 zabaw."),
    ("A","Prawdziwe monety, cenniki z cyframi, kasa z przegródkami."),
    ("R","Rozumienie wartości pieniądza to praktyczna kompetencja życiowa."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Kącik sklep · karta obliczeń.",
  pomoce=["monety 1, 2, 5 zł (prawdziwe lub wierne kopie)","cenniki z cyframi","kasa z przegródkami","towary z metkami","portfele dzieci"],
  metody=["monety wierne oryginałom","cennik z realnymi cenami","liczenie na konkretach przed zapisem","zamiana ról kupujący–sprzedawca"],
  rodzaj="Zajęcia wspierające edukację matematyczną i społeczną",
  przebieg=[
    ("N — pokazuje monety i prosi o rozpoznanie.","D — nazywa monety i ich wartość."),
    ("N — pyta: „po co ludziom pieniądze?”.","D — wyjaśnia, skąd się biorą i po co służą."),
    ("N — otwiera sklep z cennikiem.","D — wybiera towar i odczytuje cenę."),
    ("N — obserwuje płatność przy kasie.","D — odlicza monety i płaci właściwą kwotę."),
    ("N — zamienia role przy kasie.","D — jako sprzedawca sprawdza zapłatę kolegi.")],
  mod2=["dwie monety do rozpoznania","cena podana kropkami i cyfrą","płatność pojedynczymi monetami"],
  mod3=["rozpoznanie jednej monety","zakup za jedną monetę","liczenie do 5","wsparcie w rozumieniu pojęcia wartości"],
  mod1=["zakup z obliczeniem kwoty w zakresie 10 zł i sprawdzeniem reszty","porównanie cen dwóch towarów","planowanie zakupów w ramach kwoty","wyjaśnienie, czym są oszczędności"],
  wskazowka="Używaj prawdziwych monet — plastikowe żetony uczą liczenia, ale dopiero prawdziwa moneta uczy, że pieniądz ma wartość poza zabawą."),

 ("C", 39): dict(
  nr="C8-39", tytul="Mali badacze świata",
  podtytul="Samodzielna aktywność poznawcza i korzystanie z różnych źródeł informacji",
  sfera="VIII GŁÓWNE OBSZARY ŻYCIA · Poszukiwanie wiedzy (ICF d815 · PP 2.1·3.4)",
  czas="30 min", forma="mała grupa (3–4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko wyszuka informację w albumie lub atlasie z pomocą nauczyciela i opowie, czego się dowiedziało, w 3 z 5 prób, w ciągu 12 tygodni.",
  ter_smart=[
    ("S","Korzysta ze źródła informacji i relacjonuje znalezioną wiedzę."),
    ("M","1 informacja + relacja; 3 z 5 prób."),
    ("A","Kącik badacza z albumami, atlasami i lupami."),
    ("R","Samodzielne poszukiwanie wiedzy to fundament uczenia się przez całe życie."),
    ("T","Weryfikacja po 12 tygodniach."),
  ],
  ter_kryt="Karta małego badacza · zapis pytań i źródeł.",
  pomoce=["albumy, atlasy, encyklopedie dziecięce","lupy i mikroskop dziecięcy","tablica pytań grupy","karty małego badacza","aparat do dokumentacji"],
  metody=["tablica pytań, na które szukamy odpowiedzi","wybór źródła przez dziecko","relacjonowanie odkrycia grupie","dokumentowanie badań w karcie"],
  rodzaj="Zajęcia wspierające rozwój poznawczy / przygotowanie do szkoły",
  przebieg=[
    ("N — pokazuje tablicę pytań grupy.","D — wybiera pytanie, które go interesuje."),
    ("N — prezentuje dostępne źródła w kąciku badacza.","D — wybiera album lub atlas do poszukiwań."),
    ("N — pomaga odnaleźć właściwą stronę.","D — ogląda ilustracje i szuka odpowiedzi."),
    ("N — prosi o zapis w karcie badacza.","D — rysuje lub dyktuje, czego się dowiedział."),
    ("N — zaprasza do relacji przed grupą.","D — opowiada grupie o swoim odkryciu.")],
  mod2=["pytanie wybrane z dwóch","źródło wskazane przez nauczyciela","relacja przez pokazanie ilustracji"],
  mod3=["wskazanie miejsca, gdzie szukać informacji","oglądanie albumu z dorosłym","jedno konkretne pytanie","wsparcie w formułowaniu wypowiedzi"],
  mod1=["sformułowanie własnego pytania, wybór źródła i przedstawienie odpowiedzi","porównanie informacji z dwóch źródeł","przygotowanie mini-wykładu dla grupy","zapisanie odkrycia w kronice badaczy"],
  wskazowka="Tablica pytań musi być prowadzona na bieżąco — dziecko szuka odpowiedzi z zapałem tylko wtedy, gdy pytanie jest naprawdę jego, a nie zadane przez dorosłego."),
}
