# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar III (porozumiewanie się), wersja A (3–4 lata)."""

KONSPEKTY_D3 = {
 ("A", 11): dict(
  nr="D3-11", tytul="Zrób to, o co proszę",
  podtytul="Rozumienie i wykonywanie prostych poleceń kierowanych indywidualnie",
  sfera="III POROZUMIEWANIE SIĘ · Rozumienie poleceń (ICF d310 · PP 3.5)",
  czas="10 min", forma="indywidualnie lub w parze", cykl="codziennie",
  ter="Dziecko wykona dwuelementowe polecenie poparte gestem („weź kubek i postaw na stole”) bez powtórzenia, w 3 z 5 poleceń dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Wykonuje obie części polecenia we właściwej kolejności."),
    ("M","2 elementy · bez powtórzenia; 3 z 5 poleceń dziennie."),
    ("A","Polecenie krótkie, poparte gestem wskazującym przedmiot."),
    ("R","Rozumienie poleceń warunkuje udział w każdej rutynie dnia."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Próby zaaranżowane w rutynie · 5 poleceń dziennie · zapis wykonania.",
  pomoce=["przedmioty codzienne: kubek, łyżka, miś, klocek","koszyk „skrzynia zadań”","obrazki czynności (weź, połóż, daj)","pacynka wydająca polecenia"],
  metody=["polecenie krótkie, jedno zdanie","gest wskazujący jako podpowiedź","stopniowe wycofywanie gestu","natychmiastowe wzmocnienie wykonania"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — wyjmuje przedmiot ze skrzyni: „daj mi misia”, wskazuje.","D — podaje misia nauczycielowi."),
    ("N — dodaje drugi element: „weź kubek i postaw na stole”.","D — wykonuje obie części polecenia."),
    ("N — powtarza polecenie z gestem, w wolnym tempie.","D — wykonuje polecenie po jednym usłyszeniu."),
    ("N — wycofuje gest, zostawia samo słowo.","D — wykonuje polecenie bez podpowiedzi wzrokowej."),
    ("N — przenosi polecenia do rutyny: „przynieś swój kubek”.","D — wykonuje polecenie w sytuacji naturalnej.")],
  mod2=["polecenie jednoelementowe z gestem","przedmioty w zasięgu wzroku dziecka","powtórzenie polecenia raz"],
  mod3=["polecenie jednoelementowe z pokazem wykonania","prowadzenie ręki przy pierwszych próbach","wybór z dwóch przedmiotów zamiast szukania","sprawdzenie słuchu i rozumienia u logopedy"],
  mod1=["polecenie dwuelementowe bez gestu i bez powtórzenia","polecenie odroczone: „potem przynieś…”","dziecko wydaje polecenia koledze w zabawie","polecenia w sytuacjach nowych i poza salą"],
  wskazowka="Wydaj polecenie raz i odczekaj — powtarzanie w kółko uczy dziecko, że pierwsze zdanie nie jest ważne, bo zaraz padnie następne."),

 ("A", 12): dict(
  nr="D3-12", tytul="Powiem, czego chcę",
  podtytul="Komunikowanie potrzeb słowem, gestem lub symbolem (także AAC)",
  sfera="III POROZUMIEWANIE SIĘ · Komunikacja potrzeb (ICF d330·d335 · PP 2.10·3.2)",
  czas="10 min + sytuacje naturalne", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko samodzielnie sięgnie po tablicę AAC lub użyje słowa-klucza, aby zgłosić jedną z czterech podstawowych potrzeb, w 3 z 5 sytuacji dnia, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Zgłasza potrzebę: pić, jeść, toaleta, pomoc."),
    ("M","4 potrzeby · 3 z 5 sytuacji dziennie."),
    ("A","Tablica 4-polowa stale dostępna, symbole duże i kontrastowe."),
    ("R","Skuteczna komunikacja zmniejsza frustrację i zachowania trudne."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Rejestr komunikatów funkcjonalnych · zapis dzienny.",
  pomoce=["tablica AAC 4-polowa (pić, jeść, toaleta, pomoc)","brelok z symbolami przy dziecku","kubek, jabłko, symbol toalety jako konkrety","zdjęcia sytuacji"],
  metody=["próby zaaranżowane (kubek widoczny, ale niedostępny)","modelowanie: dorosły też używa tablicy","natychmiastowa realizacja zgłoszonej potrzeby","stopniowe oddalanie tablicy od dziecka"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — stawia kubek w zasięgu wzroku, poza zasięgiem ręki.","D — patrzy na kubek, sięga bezskutecznie."),
    ("N — podaje tablicę i modeluje: wskazuje symbol „pić”.","D — wskazuje symbol „pić” za nauczycielem."),
    ("N — natychmiast nalewa i podaje kubek.","D — pije — komunikat zadziałał."),
    ("N — odkłada tablicę na stały punkt w sali.","D — samodzielnie podchodzi i wskazuje symbol."),
    ("N — wzmacnia każdy komunikat w sytuacjach naturalnych.","D — zgłasza potrzeby w ciągu dnia.")],
  mod2=["tablica 2-polowa (pić, pomoc)","tablica podawana przez dorosłego","modelowanie przy każdej próbie"],
  mod3=["jeden symbol na start, konkret zamiast rysunku","podanie symbolu do ręki i wspólne wskazanie","realizacja potrzeby przy każdej próbie komunikacji","konsultacja z logopedą — dobór systemu AAC"],
  mod1=["pełny komunikat słowny („chcę pić”) do konkretnej osoby","zgłoszenie potrzeby w hałasie i przy innym dorosłym","komunikowanie potrzeb mniej oczywistych (zimno, boli)","poinformowanie kolegi o swojej potrzebie"],
  wskazowka="Każdy komunikat musi zadziałać natychmiast — jeśli wskazanie symbolu nie przynosi kubka od razu, dziecko wraca do płaczu, bo płacz działa szybciej."),

 ("A", 13): dict(
  nr="D3-13", tytul="Zdanie z obrazka",
  podtytul="Budowanie prostych zdań zrozumiałych dla najbliższego otoczenia",
  sfera="III POROZUMIEWANIE SIĘ · Budowanie zdań (ICF d330 · PP 3.2)",
  czas="12 min", forma="indywidualnie lub w parze", cykl="3× w tygodniu",
  ter="Dziecko zbuduje zdanie trzywyrazowe opisujące obrazek (kto – co robi – co) po pytaniu naprowadzającym, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Mówi zdanie: podmiot – orzeczenie – dopełnienie."),
    ("M","3 wyrazy; 3 z 5 prób w sesji."),
    ("A","Obrazek prosty, jedna czynność, wsparcie pytaniem."),
    ("R","Zdanie proste jest podstawą opowiadania i rozmowy."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Próbka mowy · nagranie 5-minutowe raz w tygodniu.",
  pomoce=["duże obrazki z jedną czynnością","paski do układania zdania (3 pola)","pacynka „ciekawska”","dyktafon lub telefon do nagrywania próbki"],
  metody=["pytanie naprowadzające zamiast poprawiania","rozszerzanie wypowiedzi dziecka o jeden wyraz","układanie zdania na 3 polach paska","modelowanie poprawnej formy bez korekty wprost"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — pokazuje obrazek: „kto tu jest?”.","D — nazywa postać: „pies”."),
    ("N — rozszerza: „pies… co robi?”.","D — dodaje czynność: „pies je”."),
    ("N — wskazuje trzecie pole paska: „co je?”.","D — kończy zdanie: „pies je kość”."),
    ("N — powtarza całe zdanie dziecka z uśmiechem.","D — powtarza pełne zdanie za nauczycielem."),
    ("N — pacynka prosi o opowiedzenie o obrazku.","D — mówi zdanie samodzielnie do pacynki.")],
  mod2=["zdanie dwuwyrazowe („pies je”)","pasek z 2 polami","obrazek z rodziny doświadczeń dziecka"],
  mod3=["nazwanie pojedynczego wyrazu-etykiety","modelowanie całego zdania do powtórzenia","wybór odpowiedzi z dwóch podanych","terapia logopedyczna równolegle"],
  mod1=["zdanie rozwinięte o przymiotnik lub miejsce","opis zdarzenia z sali zamiast obrazka","zdanie zrozumiałe dla osoby spoza grupy","opowiedzenie historyjki z 2 obrazków"],
  wskazowka="Nie poprawiaj wprost — powtórz zdanie dziecka w poprawnej formie. Korekta „nie mówi się tak” zamyka usta, a poprawny wzorzec otwiera."),

 ("A", 14): dict(
  nr="D3-14", tytul="Kto? Co? Gdzie?",
  podtytul="Odpowiadanie na proste pytania o osobę, przedmiot i miejsce",
  sfera="III POROZUMIEWANIE SIĘ · Odpowiadanie na pytania (ICF d350 · PP 3.1)",
  czas="10 min", forma="mała grupa (2–3 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko odpowie słownie na pytania „kto?” i „co?” dotyczące ilustracji lub sytuacji w sali, w 3 z 5 pytań serii, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Odpowiada słowem lub zdaniem na pytanie o osobę i przedmiot."),
    ("M","3 z 5 pytań w serii; min. 2 sesje z rzędu."),
    ("A","Pytania o to, co widoczne tu i teraz; jeden typ pytania na raz."),
    ("R","Odpowiadanie na pytania to podstawa rozmowy i uczenia się."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta pytań diagnostycznych · 5 pytań w serii · zapis odpowiedzi.",
  pomoce=["ilustracje sytuacyjne","zdjęcia dzieci i sali","kostka z symbolami pytań (kto/co/gdzie)","pacynka zadająca pytania"],
  metody=["jeden typ pytania na sesję","pytania o to, co widoczne","wybór z dwóch odpowiedzi przy trudności","kostka pytań jako element zabawy"],
  rodzaj="Zajęcia logopedyczne / wspierające komunikację",
  przebieg=[
    ("N — rzuca kostką: wypada symbol „kto?”.","D — patrzy na ilustrację, szuka postaci."),
    ("N — pyta: „kto pije mleko?”.","D — odpowiada: „kotek”."),
    ("N — przy trudności daje wybór: „kotek czy piesek?”.","D — wybiera właściwą odpowiedź."),
    ("N — zmienia typ pytania: „co on pije?”.","D — odpowiada na pytanie o przedmiot."),
    ("N — przenosi pytania na salę: „kto siedzi obok ciebie?”.","D — odpowiada o realnej sytuacji.")],
  mod2=["tylko pytania „co to?”","wybór z dwóch odpowiedzi przy każdym pytaniu","3 pytania zamiast 5"],
  mod3=["odpowiedź przez wskazanie obrazka","pytanie z jedną możliwą odpowiedzią","modelowanie odpowiedzi do powtórzenia","współpraca z logopedą"],
  mod1=["pytania „kto? co? gdzie?” w jednej serii","pytania o zdarzenie sprzed kilku godzin","dziecko zadaje pytania koledze","pytania o przyczynę: „dlaczego?”"],
  wskazowka="Pytaj o to, co dziecko widzi — pytanie o wczorajszy spacer wymaga pamięci i narracji, czyli dwóch umiejętności naraz, a ćwiczymy jedną."),

 ("A", 15): dict(
  nr="D3-15", tytul="Twarze i gesty",
  podtytul="Rozumienie komunikatów pozawerbalnych: mimiki, gestów, tonu głosu",
  sfera="III POROZUMIEWANIE SIĘ · Komunikaty niewerbalne (ICF d315 · PP 3.5)",
  czas="12 min", forma="mała grupa (3–4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko wskaże na obrazkach twarz wesołą i smutną oraz dopasuje je do sytuacji z sali, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Rozpoznaje minę wesołą i smutną i łączy ją z sytuacją."),
    ("M","2 emocje · 3 z 5 prób w sesji."),
    ("A","Duże, kontrastowe zdjęcia twarzy; sytuacje znane z sali."),
    ("R","Odczytywanie sygnałów niewerbalnych zapobiega nieporozumieniom."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Próby sytuacyjne · obserwacja uczestnicząca w ciągu dnia.",
  pomoce=["zdjęcia twarzy: wesoła, smutna","zdjęcia sytuacji z sali","gest „stop” i „chodź” na kartach","lusterko"],
  metody=["kontrast dwóch min, bez odcieni","łączenie miny z konkretną sytuacją","gest wspierany słowem, potem sam gest","zabawa w odczytywanie miny nauczyciela"],
  rodzaj="Zajęcia wspierające komunikację i rozwój emocjonalny",
  przebieg=[
    ("N — pokazuje dwie twarze: wesołą i smutną, nazywa je.","D — wskazuje twarz nazwaną przez nauczyciela."),
    ("N — pokazuje zdjęcie sytuacji: dziecku spadła wieża.","D — dopasowuje twarz smutną do sytuacji."),
    ("N — robi minę i pyta bez słów: „jaka to mina?”.","D — wskazuje odpowiednie zdjęcie twarzy."),
    ("N — pokazuje gest „stop” podczas zabawy ruchowej.","D — zatrzymuje się na sam gest."),
    ("N — w ciągu dnia używa gestu zamiast polecenia.","D — reaguje na gest i mimikę nauczyciela.")],
  mod2=["jedna emocja na sesję","mina pokazywana razem z nazwą słowną","gest zawsze wspierany słowem"],
  mod3=["reakcja na gest „stop” z dodatkowym sygnałem dźwiękowym","zdjęcia zamiast rysunków (twarze znanych osób)","powtórzenie gestu dwa razy","obserwacja kontaktu wzrokowego"],
  mod1=["rozpoznanie miny w sytuacji realnej i reakcja na nią","odczytanie z tonu głosu, że coś jest niebezpieczne","pokazanie miny dla grupy do odgadnięcia","dostosowanie zachowania do mimiki kolegi"],
  wskazowka="Ucz gestu w ruchu, nie przy stoliku — gest „stop” zapamiętuje się wtedy, gdy naprawdę zatrzymuje bieg, a nie gdy jest obrazkiem na karcie."),
}
