# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar I (uczenie się i stosowanie wiedzy), wersja B (5 lat)."""

KONSPEKTY_5_D1 = {
 ("B", 1): dict(
  nr="B1-01", tytul="Detektywi opowieści",
  podtytul="Słuchanie opowiadania i odpowiadanie na pytania o treść",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Rozumienie tekstu (ICF d115–d132 · PP 3.3·3.12)",
  czas="20 min", forma="mała grupa (4–6 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko wysłucha całego opowiadania i odpowie na 2 pytania o treść, korzystając z historyjki obrazkowej jako podpowiedzi, w 3 z 5 czytań, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Odpowiada na pytania o bohatera, zdarzenie i kolejność."),
    ("M","2 pytania na czytanie; 3 z 5 czytań."),
    ("A","Historyjka obrazkowa i lupa detektywa wspierają przypominanie."),
    ("R","Rozumienie tekstu to fundament nauki czytania w szkole."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zestaw 4 pytań do tekstu · zapis odpowiedzi po każdym czytaniu.",
  pomoce=["opowiadania 5-minutowe z wyraźną akcją","lupy detektywistyczne dla dzieci","karty historyjki obrazkowej (4 sceny)","odznaki „detektyw opowieści”","tablica z pytaniami: kto? gdzie? co się stało? dlaczego?"],
  metody=["czytanie z zawieszeniem akcji przed rozwiązaniem","detektywistyczne poszukiwanie odpowiedzi w tekście","układanie historyjki obrazkowej po czytaniu","pytania stopniowane od faktu do przyczyny"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — rozdaje lupy: „dziś jesteśmy detektywami opowieści”.","D — bierze lupę, zajmuje miejsce w kręgu."),
    ("N — czyta opowiadanie, zatrzymuje się przed rozwiązaniem.","D — słucha, zgaduje, co będzie dalej."),
    ("N — zadaje pytanie o fakt: „kto zgubił klucz?”.","D — odpowiada, wskazując scenę na karcie."),
    ("N — pyta o przyczynę: „dlaczego miś był smutny?”.","D — uzasadnia odpowiedź zdaniem z „bo”."),
    ("N — rozdaje 4 karty do ułożenia kolejności.","D — układa historyjkę i opowiada ją grupie.")],
  mod2=["opowiadanie skrócone o połowę","karty obrazkowe widoczne w trakcie czytania","2 pytania o fakty, bez pytania o przyczynę"],
  mod3=["fragment 3-minutowy, czytany indywidualnie","odpowiedź przez wskazanie obrazka spośród dwóch","pytania wyłącznie o to, co widać na ilustracji","współpraca z logopedą przy rozumieniu mowy"],
  mod1=["4 pytania, w tym o przyczynę i uczucia bohatera","opowiedzenie treści własnymi słowami","wymyślenie innego zakończenia","zadawanie pytań innym dzieciom o wysłuchany tekst"],
  wskazowka="Zatrzymaj czytanie tuż przed rozwiązaniem akcji — pięciolatek, który sam próbuje zgadnąć zakończenie, słucha reszty opowiadania inaczej niż ten, któremu wszystko podano."),

 ("B", 2): dict(
  nr="B1-02", tytul="Fabryka rytmów",
  podtytul="Klasyfikowanie według cech oraz układanie szeregów i rytmów",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Klasyfikowanie (ICF d137 · PP 4.5·4.14)",
  czas="20 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko posegreguje zbiór według dwóch cech kolejno i ułoży rytm dwuelementowy według wzoru, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Segreguje według koloru, potem według kształtu; kontynuuje rytm."),
    ("M","2 cechy · rytm 2-elementowy; 3 z 5 prób."),
    ("A","Materiał logiczny z wyraźnymi cechami; wzór rytmu na pasku."),
    ("R","Klasyfikowanie i rytmy przygotowują do matematyki szkolnej."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zestaw materiału logicznego · karta zadania po sesji.",
  pomoce=["klocki logiczne (kolor, kształt, wielkość)","paski do układania rytmów","obręcze do segregowania","taśma produkcyjna z papieru (scenografia fabryki)","karty zamówień z wzorem rytmu"],
  metody=["zabawa w fabrykę realizującą zamówienia","jedna cecha naraz, potem zmiana kryterium","wzór rytmu widoczny nad paskiem","nazywanie kryterium przez dziecko"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — ogłasza: „nasza fabryka przyjmuje zamówienia”.","D — zakłada fartuszek pracownika fabryki."),
    ("N — podaje kartę zamówienia: „posortuj po kolorze”.","D — segreguje klocki do obręczy według koloru."),
    ("N — zmienia zamówienie: „teraz według kształtu”.","D — przekłada te same klocki według nowej cechy."),
    ("N — pokazuje wzór rytmu: koło–kwadrat–koło–kwadrat.","D — kontynuuje rytm na swoim pasku."),
    ("N — pyta: „według czego posortowałeś?”.","D — nazywa kryterium: „bo wszystkie są okrągłe”.")],
  mod2=["jedna cecha na sesję","wzór rytmu ułożony do połowy przez dorosłego","materiał ograniczony do 8 elementów"],
  mod3=["sortowanie według jednej cechy po pokazie wzorca","dopasowywanie 1:1 do wzoru","elementy silnie kontrastowe","wydłużenie etapu przed wprowadzeniem rytmu"],
  mod1=["samodzielne ustalenie i nazwanie kryterium","rytm trzyelementowy kontynuowany 6 razy","ułożenie zamówienia dla kolegi","segregowanie według dwóch cech jednocześnie"],
  wskazowka="Poproś o nazwanie kryterium — dziecko, które powie „bo są okrągłe”, myśli o cesze; dziecko, które tylko układa, może kopiować układ sąsiada."),

 ("B", 3): dict(
  nr="B1-03", tytul="Sklep pod piątką",
  podtytul="Przeliczanie elementów i posługiwanie się liczebnikami głównymi",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Liczenie (ICF d150 · PP 4.6)",
  czas="20 min", forma="para dzieci (sprzedawca i klient)", cykl="3× w tygodniu",
  ter="Dziecko policzy 6 elementów samodzielnie, zachowując zasadę jeden do jednego, i poda wynik bez ponownego liczenia, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Liczy przedmioty dotykając każdego raz i podaje wynik."),
    ("M","6 elementów · wynik bez przeliczania; 3 z 5 prób."),
    ("A","Liczenie w zabawie w sklep, na konkretach, z listą zakupów."),
    ("R","Przeliczanie ze zrozumieniem to podstawa działań matematycznych."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Zadania liczbowe w zabawie · karta wyników po sesji.",
  pomoce=["kącik sklep: owoce, warzywa, koszyki","listy zakupów z kropkami zamiast cyfr","kasa i żetony","tacki do układania liczonych elementów","cyfry 1–10 na kartonikach"],
  metody=["liczenie na konkretach w sytuacji użytkowej","układanie liczonych elementów na tacce (nie w kupce)","lista z kropkami jako zadanie","pytanie „ile razem?” zamiast ponownego liczenia"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — otwiera sklep i rozdaje role: sprzedawca, klient.","D — bierze koszyk i listę zakupów z kropkami."),
    ("N — pokazuje listę: „potrzebujesz 6 jabłek”.","D — liczy kropki na liście, potem jabłka."),
    ("N — przypomina: „każde jabłko kładziemy na tacce”.","D — układa jabłka pojedynczo, licząc na głos."),
    ("N — pyta: „ile masz razem?”.","D — podaje wynik bez ponownego liczenia."),
    ("N — proponuje zamianę ról.","D — jako sprzedawca sprawdza zamówienie kolegi.")],
  mod2=["liczenie do 4","kropki na liście odpowiadające wielkością przedmiotom","liczenie wspólnie z nauczycielem na głos"],
  mod3=["liczenie 3 elementów z dotykaniem każdego","dorosły wypowiada liczebniki, dziecko dotyka","przedmioty ułożone w rzędzie","sprawdzenie rozumienia pojęcia liczby"],
  mod1=["liczenie do 10 i porównywanie dwóch zbiorów","odczytywanie cyfry i odliczanie tylu przedmiotów","proste dodawanie w zabawie („dołóż jeszcze 2”)","prowadzenie sklepu i sprawdzanie zamówień innych"],
  wskazowka="Tacka rozwiązuje najczęstszy błąd — dziecko liczące w kupce wraca do tych samych przedmiotów; przekładanie po jednym wymusza zasadę jeden do jednego."),

 ("B", 4): dict(
  nr="B1-04", tytul="Kwadrans badacza",
  podtytul="Skupianie uwagi na zadaniu przez czas adekwatny do wieku",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Uwaga (ICF d160 · PP 2.6)",
  czas="20 min", forma="indywidualnie lub w parze", cykl="codziennie",
  ter="Dziecko pozostanie przy zadaniu kierowanym 10 minut, korzystając z wizualnego licznika kroków, bez przerywania pracy, w 3 z 5 zajęć, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Pracuje przy zadaniu do zakończenia wszystkich kroków."),
    ("M","10 minut bez przerwania; 3 z 5 zajęć."),
    ("A","Licznik kroków pokazuje, ile zostało do końca."),
    ("R","Wytrwałość na zadaniu warunkuje gotowość szkolną."),
    ("T","Weryfikacja po 8 tygodniach; potem wydłużenie do 15 minut."),
  ],
  ter_kryt="Pomiar czasu na zadaniu · zapis liczby przerwań.",
  pomoce=["licznik kroków (5 pól do odhaczania)","zadania wieloetapowe: mozaika, sekwencja, sortowanie","klepsydra 10-minutowa","karta „skończone” do podpisania","słuchawki wygłuszające do wyboru"],
  metody=["wizualizacja postępu licznikiem","zadanie podzielone na widoczne kroki","stanowisko z ograniczoną liczbą bodźców","podsumowanie własnej pracy przez dziecko"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — pokazuje licznik: „pięć kroków i praca gotowa”.","D — ogląda licznik, nazywa pierwszy krok."),
    ("N — uruchamia klepsydrę i odsuwa się.","D — pracuje nad pierwszym krokiem."),
    ("N — po każdym kroku wskazuje licznik bez słów.","D — odhacza krok i przechodzi do kolejnego."),
    ("N — przy zawahaniu wskazuje, ile zostało.","D — wraca do pracy, widząc bliski koniec."),
    ("N — podpisuje kartę „skończone” razem z dzieckiem.","D — pokazuje pracę i mówi, co było trudne.")],
  mod2=["zadanie 3-krokowe zamiast 5","klepsydra 5-minutowa","dorosły siedzi obok przez całą pracę"],
  mod3=["zadanie 2-krokowe, 5 minut","przerwa ruchowa po każdym kroku","stanowisko za parawanem","obserwacja pod kątem trudności z uwagą"],
  mod1=["pełne 15-minutowe zajęcie, także przy hałasie w tle","samodzielne zaplanowanie kroków przed pracą","ocena własnej pracy na skali","dokończenie zadania przerwanego dzień wcześniej"],
  wskazowka="Licznik pokazujący, ile zostało, działa lepiej niż zegar odmierzający czas — pięciolatek nie czuje minut, ale doskonale widzi, że zostały dwa pola."),

 ("B", 5): dict(
  nr="B1-05", tytul="Polowanie na litery",
  podtytul="Rozpoznawanie liter i cyfr, którymi dziecko interesuje się w zabawie",
  sfera="I UCZENIE SIĘ I STOSOWANIE WIEDZY · Litery i cyfry (ICF d140 · PP 3.17·4.9)",
  czas="20 min", forma="mała grupa (4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko rozpozna 5 liter i 5 cyfr w zabawie, dopasowując je do wzorca, w 3 z 5 prób sesji, w ciągu 8 tygodni.",
  ter_smart=[
    ("S","Wskazuje i nazywa litery ze swojego imienia oraz cyfry 1–5."),
    ("M","5 liter i 5 cyfr; 3 z 5 prób."),
    ("A","Litery duże, drukowane; zabawa w poszukiwanie w sali."),
    ("R","Rozpoznawanie znaków poprzedza naukę czytania i pisania."),
    ("T","Weryfikacja po 8 tygodniach."),
  ],
  ter_kryt="Karty liter i cyfr · zapis rozpoznań po sesji.",
  pomoce=["karty z literami i cyframi","litery ukryte w sali (na drzwiach, pudełkach)","imiona dzieci na kartonikach","stemple z literami","masa plastyczna do lepienia liter"],
  metody=["poszukiwanie znaków w otoczeniu sali","start od liter własnego imienia","wielozmysłowo: lepimy, stemplujemy, szukamy","dopasowywanie do wzorca zamiast odpytywania"],
  rodzaj="Zajęcia wspierające funkcje poznawcze / pomoc p-p",
  przebieg=[
    ("N — rozdaje kartoniki z imionami: „to twoja pierwsza litera”.","D — odnajduje pierwszą literę swojego imienia."),
    ("N — ogłasza polowanie: „szukamy litery A w sali”.","D — chodzi po sali i wskazuje znalezione litery."),
    ("N — rozkłada karty liter i cyfr do dopasowania.","D — dopasowuje znalezione znaki do kart."),
    ("N — podaje masę plastyczną: „ulepimy naszą literę”.","D — lepi literę i nazywa ją."),
    ("N — kończy wystawą liter z imionami dzieci.","D — pokazuje swoją literę i wskazuje ją w imieniu.")],
  mod2=["3 litery i 3 cyfry","litery tylko z imienia dziecka","dopasowywanie do wzorca leżącego obok"],
  mod3=["rozpoznanie pierwszej litery imienia spośród trzech","litera w jednym kroju pisma, duża i kontrastowa","wskazanie zamiast nazwania","sprawdzenie percepcji wzrokowej"],
  mod1=["10 liter i cyfry 1–10 w różnych krojach pisma","odszukanie liter w książkach i napisach w sali","układanie swojego imienia z liter","rozpoznanie litery na początku słowa"],
  wskazowka="Zacznij od liter imienia — to jedyny napis, który pięciolatek uważa za naprawdę swój, i właśnie przy nim najszybciej odkrywa, że znaki coś znaczą."),
}
