# -*- coding: utf-8 -*-
"""Konspekty zajęć — obszar VII (wzajemne kontakty), wersja A (3–4 lata).
Struktura wg wzoru „Termometr uwagi" (EduPlaner 2026)."""

# klucz: (wersja, nr twierdzenia)
KONSPEKTY = {
 ("A", 29): dict(
  nr="D7-29", tytul="Latarnia uwagi",
  podtytul="Kierowanie wzroku i uwagi na osobę, która mówi",
  sfera="VII WZAJEMNE KONTAKTY · Obdarzanie uwagą (ICF d710 · PP 3.5)",
  czas="15 min", forma="mała grupa (3–4 dzieci)", cykl="3× w tygodniu",
  ter="Dziecko w kręgu skieruje wzrok na osobę trzymającą „latarnię” (lampion) w ciągu 3 sekund od sygnału, w 4 z 5 rund zabawy, w ciągu 4 tygodni.",
  ter_smart=[
    ("S","Kieruje wzrok na dziecko lub dorosłego trzymającego lampion."),
    ("M","4 z 5 rund w sesji; min. 2 sesje z rzędu."),
    ("A","Sygnał świetlny i dźwiękowy podpowiada, na kogo patrzeć."),
    ("R","Warunkuje udział w kręgu i rozumienie komunikatów grupowych."),
    ("T","Weryfikacja po 4 tygodniach."),
  ],
  ter_kryt="Karta rund po każdej sesji (3×/tydzień); podsumowanie po 4 tyg.",
  pomoce=["lampion-latarnia (bezpieczna lampka)","poduszki do kręgu","dzwonek sygnałowy","karta rund z uśmieszkami"],
  metody=["zabawa z regułą w kręgu","modelowanie „patrzę na ciebie”","wzmocnienie pozytywne","krótkie tury (do 20 sekund)"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — zapala lampion i mówi: „kto ma światełko, ten mówi”.","D — patrzy na lampion i na twarz nauczyciela."),
    ("N — podaje lampion dziecku, dzwonkiem daje sygnał zmiany.","D — kieruje wzrok na dziecko ze światełkiem."),
    ("N — modeluje: „patrzę na Olę, Ola mówi”.","D — powtarza gest wskazania na mówiącego."),
    ("N — wydłuża tury, gasi podpowiedź dźwiękową.","D — sam odnajduje wzrokiem mówiącego."),
    ("N — kończy rundą „komu błysnęła latarnia?”.","D — wskazuje, kto mówił, przybija piątkę.")],
  mod2=["krąg zmniejszony do 3 osób","tura skrócona do 10 sekund","dzwonek przy każdej zmianie","dziecko siedzi obok nauczyciela"],
  mod3=["zabawa w parze z dorosłym","fizyczne ukierunkowanie (dotyk ramienia)","lampion podawany do rąk dziecka","powrót do kręgu po 2 tygodniach"],
  wskazowka="Światełko zawsze wędruje razem z głosem — nie dopuszczaj, by mówiło dziecko bez lampionu, bo sygnał przestaje być czytelny."),

 ("A", 30): dict(
  nr="D7-30", tytul="Podaj misia",
  podtytul="Krótkie wymiany z rówieśnikiem: podanie, odebranie, wspólna radość",
  sfera="VII WZAJEMNE KONTAKTY · Interakcje rówieśnicze (ICF d710 · PP 1.2)",
  czas="15 min", forma="para dzieci + dorosły", cykl="3× w tygodniu",
  ter="Dziecko poda i odbierze zabawkę od rówieśnika, utrzymując wymianę przez 4 podania, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Podaje misia koledze i czeka na jego ruch."),
    ("M","4 podania bez przerwania; 3 z 5 prób w sesji."),
    ("A","Dorosły siedzi za dzieckiem i podpowiada gestem."),
    ("R","Otwiera drogę do zabawy równoległej i wspólnej."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Tablica podań (magnesy) po każdej sesji; zapis 3×/tydzień.",
  pomoce=["miś lub ulubiona maskotka","koc wyznaczający pole zabawy","tablica podań z magnesami","piosenka „podaj dalej”"],
  metody=["zabawa naprzemienna „raz ja – raz ty”","modelowanie z drugim dorosłym","łańcuszek wymian ze wzmocnieniem","śpiewanka rytmiczna"],
  rodzaj="Zajęcia wspierające kompetencje społeczne / pomoc p-p",
  przebieg=[
    ("N — sadza dzieci naprzeciw siebie na kocu, pokazuje wymianę z drugim dorosłym.","D — obserwuje pełny cykl: podaję – czekam – odbieram."),
    ("N — wręcza misia i śpiewa „podaj dalej misia już”.","D — podaje misia koledze w rytm piosenki."),
    ("N — zatrzymuje piosenkę, gdy miś utknie; czeka.","D — dokańcza podanie, by piosenka wróciła."),
    ("N — dokłada drugi krąg wymian bez śpiewu.","D — utrzymuje wymianę na sam gest kolegi."),
    ("N — kończy wspólnym „hura” i magnesem na tablicy.","D — przybija piątkę z kolegą, wskazuje swój magnes.")],
  mod2=["wymiana skrócona do 2 podań","dorosły podtrzymuje rytm piosenką przez całą sesję","większa, łatwa do chwycenia maskotka"],
  mod3=["wymiana dziecko–dorosły zamiast dziecko–dziecko","prowadzenie rąk przy podaniu","nagroda sensoryczna po każdym podaniu","rówieśnik dołącza po 2 tygodniach"],
  wskazowka="Przerwana piosenka działa lepiej niż polecenie „podaj” — cisza jest sygnałem, że ruch należy do dziecka."),

 ("A", 31): dict(
  nr="D7-31", tytul="Mostek do przedszkola",
  podtytul="Rytuał pożegnania i bezpieczne wejście w dzień przedszkolny",
  sfera="VII WZAJEMNE KONTAKTY · Separacja od rodzica (ICF d760 · PP Zad.2)",
  czas="10 min (poranek)", forma="indywidualnie", cykl="codziennie",
  ter="Dziecko przejdzie rytuał pożegnania (przytulenie – machanie z okienka – pierwsza zabawa) i wyciszy się w ciągu 5 minut od wyjścia rodzica, w 4 z 5 poranków, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Wykonuje 3 stałe kroki rytuału pożegnania."),
    ("M","Wyciszenie do 5 minut; 4 z 5 poranków."),
    ("A","Plan obrazkowy rytuału i przedmiot przejściowy z domu."),
    ("R","Warunkuje udział we wszystkich aktywnościach dnia."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta adaptacji: czas wyciszenia mierzony codziennie przez rodzica i nauczyciela.",
  pomoce=["plan obrazkowy rytuału (3 kroki)","przedmiot przejściowy z domu","zdjęcie rodziny w szatni","koszyk „pierwsza zabawa” przy drzwiach"],
  metody=["stały rytuał 3 kroków","przedmiot przejściowy","natychmiastowe zajęcie rąk (zabawa startowa)","współpraca z rodzicem (ten sam scenariusz)"],
  rodzaj="Wsparcie adaptacyjne / pomoc p-p",
  przebieg=[
    ("N — wita dziecko przy drzwiach, pokazuje plan: przytulas – okienko – zabawa.","D — wskazuje palcem kolejny krok na planie."),
    ("N — odlicza z rodzicem „jeden przytulas i machamy”.","D — przytula rodzica jeden raz i idzie do okienka."),
    ("N — stoi z dzieckiem w okienku, macha razem z nim.","D — macha rodzicowi, trzymając swój przedmiot z domu."),
    ("N — podaje koszyk „pierwsza zabawa” od razu po machaniu.","D — wybiera zabawkę i siada przy stoliku startowym."),
    ("N — po 5 minutach nazywa sukces: „poradziłeś sobie”.","D — odkłada przedmiot przejściowy na swoją półkę.")],
  mod2=["rodzic odprowadza do progu sali, nie do szatni","podwójne machanie (okienko + drzwi)","zabawa startowa wybierana poprzedniego dnia"],
  mod3=["rodzic zostaje 10 minut w sali na starcie tygodnia","skrócony pobyt uzgodniony z rodzicami","stały dorosły przejmujący dziecko z rąk rodzica","konsultacja zespołu ze specjalistą"],
  wskazowka="Rytuał chroni tylko wtedy, gdy jest identyczny każdego dnia — wydłużanie przytulania „na prośbę” wydłuża płacz, nie skraca go."),

 ("A", 32): dict(
  nr="D7-32", tytul="Lusterko emocji",
  podtytul="Czytelne pokazywanie radości i złości — mimika, gest, słowo",
  sfera="VII WZAJEMNE KONTAKTY · Okazywanie emocji (ICF d710 · PP 2.9)",
  czas="15 min", forma="mała grupa (3–4 dzieci)", cykl="2× w tygodniu",
  ter="Dziecko pokaże na twarzy i nazwie (słowem lub symbolem) radość i złość w zabawie z lusterkiem, w 3 z 5 prób sesji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Pokazuje minę i wskazuje symbol pasujący do emocji."),
    ("M","2 emocje × 3 z 5 prób; min. 2 sesje z rzędu."),
    ("A","Lustro i karty emocji podpowiadają wzorzec mimiki."),
    ("R","Zmniejsza zachowania trudne wynikające z nieczytelnych sygnałów."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Karta emocji po sesji (2×/tydzień); zapis nazwań w sytuacjach naturalnych.",
  pomoce=["lusterko dziecięce","karty emocji: radość i złość","pacynka „Zły-Wesoły Zajączek”","naklejki z buźkami"],
  metody=["zabawa przed lustrem","modelowanie mimiki pacynką","łączenie miny z symbolem","nazywanie emocji w sytuacjach naturalnych"],
  rodzaj="Zajęcia wspierające rozwój emocjonalny / pomoc p-p",
  przebieg=[
    ("N — pacynką pokazuje wielką radość: „zajączek się cieszy!”.","D — patrzy w lusterko i robi wesołą minę."),
    ("N — pokazuje złość pacynki: tupie, marszczy brwi.","D — naśladuje minę złości przed lusterkiem."),
    ("N — rozkłada 2 karty i pyta: „która to ta mina?”.","D — dopasowuje swoją minę do karty emocji."),
    ("N — opowiada mini-scenkę (zabrana zabawka).","D — pokazuje i nazywa emocję bohatera scenki."),
    ("N — w ciągu dnia wraca: „pokaż, co teraz czujesz”.","D — pokazuje minę lub kartę w sytuacji naturalnej.")],
  mod2=["jedna emocja na sesję (najpierw radość)","mina razem z nauczycielem w jednym lustrze","karta emocji stale przy dziecku (brelok)"],
  mod3=["odczytywanie emocji z twarzy dorosłego zamiast pokazywania","fotografie dziecka zamiast rysunków","wsparcie logopedy przy nazywaniu","monitoring ABC zachowań trudnych"],
  wskazowka="Nazywaj emocję dopiero, gdy mina już jest — słowo doklejone do własnej twarzy dziecka utrwala się szybciej niż słowo z karty."),

 ("A", 33): dict(
  nr="D7-33", tytul="Czarodziejskie słowo POMOC",
  podtytul="Proszenie znanego dorosłego o pomoc zamiast rezygnacji lub krzyku",
  sfera="VII WZAJEMNE KONTAKTY · Proszenie o pomoc (ICF d710 · PP 2.11)",
  czas="10 min + sytuacje naturalne", forma="indywidualnie", cykl="codziennie (2 próby)",
  ter="Dziecko w sytuacji trudności podejdzie do dorosłego i zasygnalizuje „pomoc” (słowem, gestem lub kartą), zanim pojawi się płacz lub rezygnacja, w 3 z 5 sytuacji, w ciągu 6 tygodni.",
  ter_smart=[
    ("S","Podchodzi i sygnalizuje „pomoc” słowem, gestem lub kartą."),
    ("M","3 z 5 zaaranżowanych sytuacji dziennie po 2 próby."),
    ("A","Karta POMOC w zasięgu ręki; dorosły reaguje natychmiast."),
    ("R","Zastępuje płacz i wycofanie skuteczną komunikacją."),
    ("T","Weryfikacja po 6 tygodniach."),
  ],
  ter_kryt="Rejestr próśb o pomoc (zaaranżowane i naturalne); zapis codzienny.",
  pomoce=["karta POMOC (symbol dłoni)","pudełko z trudnym zamknięciem","zakręcona butelka z ulubioną naklejką w środku","gest „pomoc” (dłoń na dłoni)"],
  metody=["próby zaaranżowane (przerwana rutyna)","modelowanie gestu i słowa","natychmiastowe wzmocnienie prośby","stopniowe oddalanie dorosłego"],
  rodzaj="Zajęcia wspierające komunikację / pomoc p-p",
  przebieg=[
    ("N — podaje pudełko z naklejką, którego nie da się otworzyć.","D — próbuje otworzyć, napotyka trudność."),
    ("N — modeluje: dłoń na dłoni i słowo „pomoc”.","D — powtarza gest lub słowo za nauczycielem."),
    ("N — natychmiast otwiera pudełko po sygnale.","D — dostaje naklejkę — prośba zadziałała."),
    ("N — powtarza próbę z innym przedmiotem, stoi dalej.","D — podchodzi do dorosłego i sygnalizuje „pomoc”."),
    ("N — wzmacnia prośby w sytuacjach naturalnych dnia.","D — używa gestu/karty przy realnej trudności.")],
  mod2=["karta POMOC przyklejona do stolika dziecka","dorosły w odległości wyciągniętej ręki","jedna próba zaaranżowana dziennie"],
  mod3=["prowadzenie ręki do gestu „pomoc”","natychmiastowa pomoc przy pierwszym sygnale niepokoju","współpraca z rodzicami — ten sam gest w domu","konsultacja z poradnią przy braku postępu"],
  wskazowka="Prośba musi być tańsza niż płacz: reaguj na sygnał „pomoc” szybciej i cieplej niż na jakikolwiek inny sposób wołania."),
}
