# -*- coding: utf-8 -*-
"""Pomoce dydaktyczne do konspektów wersji C (6 lat).

Ta sama karta co w wersjach A i B, ale ciężar przesunięty jeszcze dalej
w stronę dziecka. Sześciolatek nie tylko wykonuje — planuje, sprawdza własny
efekt, rozlicza się z dyżuru, uzasadnia zdanie. Dlatego w „trzech krokach”
nauczyciel częściej się odsuwa niż pokazuje, a polecenie mówi dziecku,
po czym pozna, że skończyło, zamiast prowadzić je za rękę.

Polecenie jest zapisane tak, jak się je mówi do dziecka — w drugiej osobie,
konkretnie, bez pytań retorycznych. To ono jest nagrywane głosem nauczycielki.

Układ karty i osadzanie mediów: `pomoce_karta`.
"""

from pomoce_karta import Zestaw

# kod → (nr konspektu, tytuł, [co przygotować], [trzy kroki], polecenie do dziecka, wskazówka)
POMOCE = {
 "c1_01": ("C1-01", "Warsztat historyjek",
   ["zestawy historyjek 4- i 5-obrazkowych, po jednym na dziecko",
    "taśma czasu z ponumerowanymi polami 1–5",
    "kartoniki z łącznikami: najpierw, potem, na końcu, dlatego",
    "dyktafon albo telefon do nagrania opowiadania",
    "teczka na autorskie historyjki grupy"],
   ["Rozsyp obrazki i poproś o odnalezienie początku, nie podpowiadając.",
    "Dziecko układa całość na taśmie czasu i dopiero wtedy opowiada.",
    "Podaj kartonik „dlaczego” i poproś o wyjaśnienie zakończenia."],
   "Rozsypałam obrazki jednej historii. Znajdź ten, od którego wszystko się zaczyna, i ułóż resztę po kolei na taśmie. Potem opowiedz mi tę historię i powiedz, dlaczego tak się skończyła.",
   "Pytanie „dlaczego” jest tu ważniejsze od kolejności. Dziecko, które ułoży obrazki dobrze, ale nie powie o przyczynie, opowiada zdarzenia, a nie historię."),

 "c1_02": ("C1-02", "Sylabowa czytelnia",
   ["karty wyrazów z sylabami w dwóch kolorach",
    "suwak sylabowy odsłaniający wyraz po kawałku",
    "obrazki do dopasowania do wyrazów",
    "kącik czytelniczy z poduszkami, poza ruchem sali",
    "legitymacja czytelnika ze stemplami za przeczytany wyraz"],
   ["Odsłaniaj suwakiem po jednej sylabie i czekaj, aż dziecko ją wypowie.",
    "Poproś o połączenie sylab w całość — bez ponownego czytania po kawałku.",
    "Dziecko dopasowuje przeczytany wyraz do obrazka i stempluje legitymację."],
   "Będziemy czytać po kawałku. Odsłonię pierwszą sylabę, ty ją przeczytasz, potem drugą. Na końcu powiedz cały wyraz naraz i połóż go przy właściwym obrazku.",
   "Dwa kolory sylab są po to, żeby dziecko widziało granicę, a nie zgadywało. Gdy scala już płynnie, przejdź na wyrazy jednobarwne — inaczej kolor zostaje protezą."),

 "c1_03": ("C1-03", "Litery w liniaturze",
   ["wzory liter ze strzałkami kierunku kreślenia",
    "liniatura poszerzona i standardowa, obie na jednej karcie",
    "tacka z piaskiem do kreślenia palcem",
    "ołówki trójkątne i kredki krótkie, wymuszające chwyt",
    "folia do pisania po wzorze, ścieralna"],
   ["Kreśl literę palcem w powietrzu, potem dziecko powtarza w piasku.",
    "Pokaż strzałkę startu i poproś, żeby dziecko nazwało kierunek.",
    "Dziecko pisze po folii, potem samodzielnie w liniaturze poszerzonej."],
   "Popatrz na strzałkę: tu zaczynamy i w tę stronę prowadzimy. Napisz literę najpierw palcem w piasku, potem po folii, a na końcu sam w liniaturze.",
   "Kolejność piasek — folia — liniatura nie jest ozdobą. Dziecko, które od razu dostaje ołówek, utrwala błędny kierunek kreślenia i potem trzeba go oduczać."),

 "c1_04": ("C1-04", "Kantorek liczb",
   ["monety-żetony i portfele, po jednym na dziecko",
    "karty cyfr od 1 do 10",
    "cenniki w dwóch wersjach: z kropkami i z cyframi",
    "liczmany do sprawdzania: kasztany, guziki",
    "lada kantorka z kasą"],
   ["Dziecko przelicza własne żetony i podaje wynik bez ponownego liczenia.",
    "Podaj cennik z cyframi; dziecko odlicza dokładnie tyle żetonów.",
    "Zapisz działanie 3 + 2 = 5 i poproś o sprawdzenie go na liczmanach."],
   "Otwieramy kantorek. Policz swoje żetony i powiedz mi, ile ich masz. Potem popatrz na cennik i odlicz dokładnie tyle, ile kosztuje towar.",
   "Zapis działania pokazuj dopiero po tym, jak dziecko wykona je na żetonach. Cyfra ma opisywać czynność, którą dziecko właśnie zrobiło, a nie ją zastępować."),

 "c1_05": ("C1-05", "Laboratorium hipotez",
   ["waga szalkowa, najlepiej przezroczysta",
    "miarki niestandardowe: sznurki, klocki, dłonie",
    "przedmioty o różnej masie, ale zbliżonej wielkości",
    "karty doświadczenia z trzema polami: przypuszczam – sprawdzam – wynik",
    "fartuchy laboratoryjne"],
   ["Dziecko waży przedmioty w dłoniach i stawia hipotezę na karcie.",
    "Dopiero po zapisaniu przypuszczenia udostępnij wagę szalkową.",
    "Porównajcie hipotezę z wynikiem — bez oceniania, czy było trafne."],
   "Zanim cokolwiek zważysz, powiedz mi, co przypuszczasz: który przedmiot będzie najcięższy. Zaznacz to na karcie. Dopiero potem sprawdzimy na wadze, czy tak jest.",
   "Przedmioty muszą być podobnej wielkości, a różnić się masą — inaczej dziecko zgaduje po rozmiarze i doświadczenie niczego nie rozstrzyga."),

 "c2_06": ("C2-06", "Plan w trzech krokach",
   ["karty etapów do ułożenia w kolejności",
    "tablica planu z polami 1–3 i miejscem na klips",
    "klipsy do odhaczania wykonanych etapów",
    "zadania projektowe: makieta, przepis, proste doświadczenie",
    "karta oceny: czy efekt zgadza się z planem"],
   ["Przedstaw cel i rozsyp karty etapów — nie układaj ich sam.",
    "Dziecko układa kolejność na tablicy i dopiero potem zaczyna pracę.",
    "Przy zawahaniu wskazuj tablicę zamiast podpowiadać słowami."],
   "Zanim zaczniesz, ułóż plan: co robimy najpierw, co potem, co na końcu. Po każdym skończonym kroku przypnij klips. Na końcu sprawdzimy, czy wyszło tak, jak zaplanowałeś.",
   "Wskazywanie tablicy zamiast podpowiadania jest tu całą metodą. Podpowiedź słowna przenosi plan z powrotem do Pani głowy, a miał zostać w głowie dziecka."),

 "c2_07": ("C2-07", "Cicha godzina pracy",
   ["kartoniki „potrzebuję pomocy” do postawienia na stoliku",
    "zegar pracy z widoczną tarczą",
    "teczki z zadaniami do wyboru, o różnej trudności",
    "przegródki na prace skończone",
    "słuchawki wygłuszające dostępne bez pytania"],
   ["Ogłoś cichą godzinę i ustaw zegar tam, gdzie wszyscy go widzą.",
    "Pokaż kartonik pomocy: „postaw, kiedy utkniesz” — i odejdź.",
    "Obchodź salę, reagując wyłącznie na postawione kartoniki."],
   "Zaczynamy cichą godzinę pracy. Wybierz teczkę i pracuj sam. Jeśli utkniesz, postaw kartonik przy sobie — podejdę. Nie musisz mnie wołać.",
   "Reaguj tylko na kartonik, także wtedy, gdy widzi Pani, że dziecko się męczy. Podejście bez sygnału uczy, że sygnał jest niepotrzebny, i konspekt przestaje działać."),

 "c2_08": ("C2-08", "Klub dobrych przegranych",
   ["gry planszowe z wyraźnym elementem losowym",
    "kodeks dobrego gracza w czterech punktach",
    "kartoniki ze zdaniami: „gratuluję”, „zagramy jeszcze raz”",
    "tablica błędów, które czegoś nauczyły",
    "medale dobrego gracza, nie dla zwycięzcy"],
   ["Przypomnij kodeks przed grą i poproś o nazwanie zasad.",
    "Po przegranej zapytaj o emocję, zanim poprosisz o gratulacje.",
    "Medal wręcz za sposób grania, nigdy za wynik."],
   "Zanim zagramy, przypomnij mi zasady dobrego gracza. Gramy do końca, gratulujemy wygranemu i próbujemy jeszcze raz. Przegrana też jest częścią gry.",
   "Kolejność jest tu istotna: najpierw nazwanie emocji, dopiero potem gratulacje. Gratulacje wymuszone przed nazwaniem złości uczą udawania, a nie radzenia sobie."),

 "c2_09": ("C2-09", "Wczoraj, dziś, jutro",
   ["kalendarz grupowy ze zdjęciami wydarzeń",
    "oś czasu z trzema polami: wczoraj – dziś – jutro",
    "karty dni tygodnia",
    "zdjęcia z ostatnich kilku dni, wydrukowane",
    "tabliczka pogody do codziennego uzupełniania"],
   ["Otwórz krąg przy kalendarzu i poproś o wskazanie dzisiejszego dnia.",
    "Pokaż zdjęcie z wczoraj i poproś o opowiedzenie, co się działo.",
    "Zapowiedz jutro i poproś o zdanie w czasie przyszłym."],
   "Popatrz na kalendarz i pokaż mi dzisiejszy dzień. Teraz zdjęcie z wczoraj — opowiedz, co wtedy robiliśmy. A na końcu powiedz, co będzie jutro.",
   "Zdjęcia z ostatnich dni robią tu całą robotę. Bez nich „wczoraj” jest dla sześciolatka słowem, a nie wspomnieniem, i oś czasu zostaje pusta."),

 "c2_10": ("C2-10", "Skrzynka strategii",
   ["tablica czterech strategii: oddech, przerwa, proszę o pomoc, dzielę na części",
    "zadania o rosnącej trudności, w tym jedno za trudne",
    "klepsydra odmierzająca przerwę",
    "skrzynka z gniotkami i drobiazgami do rąk",
    "karta „udało mi się mimo trudności”"],
   ["Omów cztery strategie i poproś o wskazanie znanych sobie.",
    "Daj zadanie trudniejsze niż zwykle i pozwól napotkać trudność.",
    "Przy zacięciu wskaż tablicę: „którą strategię wybierasz?”"],
   "To zadanie jest trudniejsze niż zwykle i możesz na chwilę utknąć. Kiedy tak się stanie, popatrz na tablicę i wybierz jeden sposób. Możesz odetchnąć, zrobić przerwę, poprosić o pomoc albo podzielić zadanie na części.",
   "Zadanie musi być naprawdę za trudne, inaczej nie ma czego ćwiczyć. Sześciolatek uczy się strategii wtedy, gdy jej potrzebuje, a nie gdy omawiamy ją przy łatwej pracy."),

 "c3_11": ("C3-11", "Wyraźnie i płynnie",
   ["lustro logopedyczne na wysokości twarzy dziecka",
    "karty obrazkowe z ćwiczoną głoską w nagłosie i wygłosie",
    "gra planszowa z wyrazami zawierającymi tę głoskę",
    "dyktafon do nagrania krótkiej wypowiedzi",
    "karta ćwiczeń dla rodziców, do zabrania do domu"],
   ["Pokaż układ artykulacyjny przed lustrem i poproś o powtórzenie.",
    "Przejdź na wyrazy z kart, potem na zdania w grze planszowej.",
    "Nagraj wypowiedź i odsłuchaj razem z dzieckiem."],
   "Popatrz w lustro i ustaw usta tak jak ja. Teraz powiedz tę głoskę, patrząc na siebie. Potem nazwiemy obrazki, a na końcu nagram, jak mówisz, i posłuchamy razem.",
   "Odsłuchanie własnego nagrania jest skuteczniejsze niż każda uwaga z zewnątrz. Dziecko słyszy różnicę samo i nie musi jej Pani nazywać."),

 "c3_12": ("C3-12", "Dźwiękowe puzzle",
   ["żetony-liczmany, po jednym na głoskę",
    "obrazki wyrazów 3- i 4-głoskowych",
    "pacynka mówiąca powoli, głoska po głosce",
    "kubeczki do układania głosek w kolejności",
    "lustro do kontroli artykulacji"],
   ["Pacynka mówi k–o–t; dziecko scala i podaje wyraz.",
    "Odwróć zadanie: obrazek, a dziecko dzieli wyraz, kładąc żetony.",
    "Zapytaj o pierwszą i ostatnią głoskę, wskazując konkretny żeton."],
   "Pacynka mówi bardzo powoli, głoska po głosce. Posłuchaj i powiedz, jaki to wyraz. Potem ja pokażę obrazek, a ty podziel jego nazwę na głoski i połóż tyle żetonów, ile ich słyszysz.",
   "Żeton na głoskę zamienia dźwięk w coś, co można dotknąć i policzyć. Bez niego dziecko zgaduje liczbę głosek, zamiast ją wyodrębniać."),

 "c3_13": ("C3-13", "Bajkopisarze",
   ["kostki opowieści z symbolami do losowania",
    "mapa bajki: bohater – problem – rozwiązanie – koniec",
    "pacynki bohaterów znanej bajki",
    "dyktafon do nagrania autorskiej wersji",
    "książka autorska grupy, uzupełniana przez rok"],
   ["Przeczytaj znaną bajkę i poproś o wskazanie bohatera i problemu na mapie.",
    "Dziecko odtwarza treść w czterech zdaniach, po jednym na pole mapy.",
    "Rzuć kostką: „a gdyby zamiast tego…” — dziecko przekształca fabułę."],
   "Znasz tę bajkę, więc opowiedz mi ją w czterech zdaniach, po jednym na każde pole mapy. A teraz rzucamy kostką i zmieniamy jedną rzecz. Opowiedz tę samą bajkę jeszcze raz, ale już inaczej.",
   "Mapa czterech pól trzyma opowieść w ryzach. Bez niej sześciolatek opowiada wszystko, co pamięta, i historia rozsypuje się na wyliczankę zdarzeń."),

 "c3_14": ("C3-14", "Debata przedszkolna",
   ["przedmiot mówcy — mówi tylko ten, kto go trzyma",
    "tabliczki tak/nie do głosowania, po jednej na dziecko",
    "plakat ze zdaniem-wzorem: „uważam, że…, ponieważ…”",
    "tematy debat bliskie dzieciom, bez dobrej odpowiedzi",
    "tablica argumentów w dwóch kolumnach"],
   ["Przedstaw temat i przeprowadź głosowanie tabliczkami przed rozmową.",
    "Pokaż zdanie-wzór i poproś o wypowiedź według niego.",
    "Zapisuj argumenty w dwóch kolumnach i przeczytaj je na koniec."],
   "Dzisiaj rozmawiamy o tym, czy zwierzę może mieszkać w przedszkolu. Najpierw zagłosuj tabliczką. Potem powiedz swoje zdanie tak: uważam, że… ponieważ… Mówi ten, kto trzyma przedmiot mówcy.",
   "Temat musi być taki, w którym obie strony dają się obronić. Przy temacie z jedną słuszną odpowiedzią debata zamienia się w odpytywanie."),

 "c3_15": ("C3-15", "English corner",
   ["karty obrazkowe słownictwa z bieżącego kręgu tematycznego",
    "maskotka, która mówi wyłącznie po angielsku",
    "nagrania piosenek z prostym ruchem",
    "wydzielony kącik English corner",
    "stemple za udział, nie za poprawność"],
   ["Maskotka wita i wydaje polecenie z gestem — dziecko reaguje ruchem.",
    "Powtórz to samo polecenie bez gestu i poczekaj na reakcję.",
    "Zakończ piosenką z ruchem, w której wracają te same słowa."],
   "Nasza maskotka mówi tylko po angielsku. Posłuchaj i zrób to, o co prosi: stand up, sit down, clap your hands. Nie musisz powtarzać słów — wystarczy, że pokażesz ruchem, że rozumiesz.",
   "Reakcja ruchem jest tu pełnym osiągnięciem. Domaganie się powtórzenia słowa zbyt wcześnie wycisza dzieci, które rozumieją, ale jeszcze nie mówią."),

 "c4_16": ("C4-16", "Skrzyżowane ścieżki",
   ["karty ćwiczeń z nazwami, do powieszenia",
    "wstążki dla obu rąk",
    "muzyka rytmiczna o wyraźnym tempie",
    "znaczniki na podłodze wyznaczające miejsca",
    "tablica ćwiczeń dnia"],
   ["Pokaż ruch przekraczający linię ciała: łokieć do przeciwnego kolana.",
    "Nadaj ćwiczeniom nazwy i powieś karty — grupa nazywa je razem.",
    "Wydaj polecenie samym słowem, bez pokazu, i obserwuj wykonanie."],
   "Dotknij łokciem przeciwnego kolana — prawym łokciem lewego kolana. Teraz zamiana. Kiedy nazwiemy to ćwiczenie, wystarczy, że powiem jego nazwę, a ty je zrobisz bez pokazywania.",
   "Przejście od pokazu do samego polecenia jest tu celem, nie ozdobą. Dziecko, które ciągle potrzebuje wzoru, nie ma jeszcze zinternalizowanego schematu ruchu."),

 "c4_17": ("C4-17", "Prosty kręgosłup przy stoliku",
   ["piktogram prawidłowej pozycji: stopy, plecy, ręce",
    "podnóżki dla dzieci, które nie sięgają do podłogi",
    "lustro do samokontroli przy stoliku",
    "woreczki do ćwiczeń postawy",
    "krzesła dobrane wzrostem, oznaczone"],
   ["Omów piktogram i poproś o nazwanie trzech elementów pozycji.",
    "Poprowadź ćwiczenie z woreczkiem na głowie: chodzenie i siadanie.",
    "Przy pracy przy stoliku wskazuj piktogram zamiast upominać."],
   "Popatrz na obrazek: stopy na podłodze, plecy proste, obie ręce na stole. Powiedz mi te trzy rzeczy. Kiedy pokażę ten obrazek przy pracy, sprawdź swoją pozycję sam.",
   "Wskazanie piktogramu zamiast uwagi słownej pozwala poprawić pozycję bez przerywania pracy. Upomnienie zabiera uwagę zadaniu, obrazek — nie."),

 "c4_18": ("C4-18", "Mistrzowie ołówka",
   ["ołówki trójkątne i nasadki korygujące chwyt",
    "karty pracy grafomotorycznej o rosnącej trudności",
    "kalka do sprawdzania siły nacisku",
    "gumki i drobiazgi do rozgrzewki dłoni",
    "tablica mistrzów ołówka"],
   ["Poprowadź rozgrzewkę dłoni, zanim ktokolwiek weźmie ołówek.",
    "Sprawdź chwyt każdego dziecka: trzy palce, luźny nadgarstek.",
    "Podłóż kalkę i pokaż dziecku ślad: „tu było za mocno”."],
   "Najpierw rozgrzewamy palce, dopiero potem bierzemy ołówek. Trzymaj go trzema palcami. Pod kartą jest kalka — po skończeniu zobaczymy, gdzie naciskałeś za mocno.",
   "Kalka pokazuje nacisk, którego dziecko nie czuje. To jedyny sposób, żeby zobaczyło problem samo; słowo „za mocno” nie ma dla niego odniesienia."),

 "c4_19": ("C4-19", "Szkoła zapinania",
   ["tablice manipulacyjne z guzikami, suwakami i rzepami",
    "but treningowy ze sznurowadłem w dwóch kolorach",
    "instrukcja wiązania rozłożona na obrazki",
    "własne ubranie dziecka do przeniesienia ćwiczenia",
    "dyplom mistrza zapinania"],
   ["Ćwiczcie na tablicy, dopóki ruch nie jest płynny — nie na ubraniu.",
    "Podaj but treningowy z dwukolorowym sznurowadłem i instrukcję.",
    "Dopiero na końcu przenieś ćwiczenie na kurtkę dziecka."],
   "Najpierw poćwiczymy na tablicy, bo tu wszystko dobrze widać. Potem zawiążesz sznurowadło na bucie — popatrz na obrazki, każdy pokazuje jeden krok. Na końcu spróbujesz na swojej kurtce.",
   "Dwa kolory sznurowadła robią różnicę nie do przecenienia: dziecko widzi, która połowa jest która, i przestaje mylić ruchy w połowie węzła."),

 "c4_20": ("C4-20", "Ruch, który opowiada",
   ["nagrania dwóch wyraźnie kontrastowych utworów",
    "chusty i wstążki, po jednej na dziecko",
    "instrumenty do sygnałów start i stop",
    "karty nastrojów muzyki",
    "aparat do nagrania improwizacji"],
   ["Puść dwa kontrastowe utwory i poproś o wskazanie karty nastroju.",
    "Rozdaj chusty: „pokażcie tę muzykę” — bez podpowiadania jak.",
    "Zmień utwór bez zapowiedzi i obserwuj, czy ruch się zmienia."],
   "Posłuchaj tej muzyki i wskaż kartę, która do niej pasuje. Teraz weź chustę i pokaż tę muzykę ruchem — tak, jak czujesz. Za chwilę zmienię utwór bez uprzedzenia.",
   "Nie podpowiadaj, jak się poruszać. Cała wartość jest w tym, że dziecko samo tłumaczy dźwięk na ruch; pokazany wzór zamienia to w naśladowanie."),

 "c5_21": ("C5-21", "Gotowi w pięć minut",
   ["tablice manipulacyjne do przećwiczenia zapięć",
    "stoper i tabela własnych czasów dziecka",
    "lustro w szatni, na wysokości dziecka",
    "instrukcja wiązania w obrazkach, powieszona nisko",
    "dyplomy samodzielności"],
   ["Przypomnij kolejność i poproś o rozłożenie ubrania w tej kolejności.",
    "Uruchom stoper i pomagaj wyłącznie na wyraźną prośbę dziecka.",
    "Zapiszcie czas w tabeli — porównujecie z własnym, nie z cudzym."],
   "Rozłóż ubranie w kolejności, w jakiej będziesz je zakładać. Włączam stoper — sprawdzamy twój własny rekord, nie ścigamy się z nikim. Jeśli będziesz potrzebować pomocy, powiedz.",
   "Tabela czasów ma sens tylko wtedy, gdy dziecko porównuje się ze sobą. Porównanie między dziećmi zamienia szatnię w wyścig i najwolniejsze przestają próbować."),

 "c5_22": ("C5-22", "Sam nakładam, sam sprzątam",
   ["naczynia serwisowe i łyżki do nakładania",
    "noże i widelce dziecięce, tępe, ale prawdziwe",
    "podkładki ze wzorem nakrycia",
    "dzbanek z wodą, lekki i pełny do połowy",
    "karta dyżurnego stolika"],
   ["Postaw półmiski na środku i pozwól nakładać samodzielnie.",
    "Pokaż trzymanie noża i widelca, potem odejdź od stolika.",
    "Zapytaj o wielkość porcji, zanim dziecko zacznie jeść."],
   "Nakładaj sobie sam, łyżką z półmiska. Zastanów się, ile zjesz — zawsze możesz dołożyć. Wodę nalej z dzbanka, jest napełniony do połowy, żeby nie był za ciężki.",
   "Dzbanek pełny do połowy to nie drobiazg. Pełny wymusza pomoc dorosłego i przekreśla to, czego konspekt uczy."),

 "c5_23": ("C5-23", "Zdrowie na talerzu",
   ["piramida zdrowego żywienia w wersji dla dzieci",
    "piktogramy rutyn higienicznych",
    "produkty do sortowania: codziennie / rzadziej",
    "plakat o śnie i ruchu",
    "karta zdrowych nawyków tygodnia"],
   ["Dziecko sortuje produkty na poziomy piramidy i uzasadnia wybór.",
    "Zapytaj, dlaczego myjemy ręce — poproś o wyjaśnienie własnymi słowami.",
    "Rozdaj karty nawyków i poproś o zaznaczenie tych, które już ma."],
   "Popatrz na piramidę i połóż produkty tam, gdzie ich miejsce. Powiedz mi, dlaczego tak. Potem zaznacz na karcie te zdrowe nawyki, które już masz — nie te, które powinieneś mieć.",
   "Sortowanie bez uzasadnienia niczego nie sprawdza. Sześciolatek często układa poprawnie z pamięci; dopiero „dlaczego” pokazuje, czy rozumie."),

 "c5_24": ("C5-24", "Bezpieczna droga",
   ["miasteczko ruchu z taśmy: jezdnia, przejście, chodnik",
    "sygnalizator wykonany przez dzieci",
    "kamizelki odblaskowe",
    "znaki drogowe do rozpoznawania, duże",
    "krzesełka ustawione jak w autobusie do scenki"],
   ["Zbudujcie miasteczko razem — dzieci rozkładają przejście i znaki.",
    "Ćwiczcie zasadę zatrzymaj – popatrz – posłuchaj na przejściu.",
    "Odegrajcie scenkę w autobusie: ustępowanie miejsca, trzymanie się."],
   "Zanim wejdziesz na przejście: zatrzymaj się, popatrz w lewo i w prawo, posłuchaj. Powtórz to ze mną. Teraz przejdź przez nasze przejście i pokaż mi te trzy rzeczy.",
   "Zasada musi być wypowiadana przez dziecko przy każdym przejściu, nie tylko na początku zajęć. Wyuczona raz i niepowtarzana znika przed wyjściem na prawdziwą ulicę."),

 "c5_25": ("C5-25", "Moje granice",
   ["skala napięcia 1–5 z obrazkami",
    "karta umówionego sygnału zgłoszenia",
    "kącik regeneracji, dostępny bez pytania",
    "historyjki obrazkowe o granicach: moje ciało, moja przestrzeń",
    "zdjęcia osób zaufanych, wybranych przez dziecko"],
   ["Dziecko zaznacza swój poziom na skali i nazywa sygnały ciała.",
    "Ustalcie sygnał, którym zgłasza przekroczenie granicy, i przećwiczcie go.",
    "Odegrajcie scenkę: dziecko ćwiczy stanowcze „nie chcę tego”."],
   "Popatrz na skalę i pokaż, na którym poziomie teraz jesteś. Powiedz mi, po czym poznajesz, że masz już czwórkę — co się dzieje z twoim ciałem. Potem przećwiczymy, jak powiedzieć „nie chcę tego”.",
   "Sygnały ciała nazywa dziecko, nie Pani. Podpowiedziane „to znaczy, że jesteś zdenerwowany” zastępuje jego odczucie Pani interpretacją i skala przestaje mierzyć cokolwiek."),

 "c6_26": ("C6-26", "Restauracja dyżurnych",
   ["podkładki ze wzorem nakrycia, jedna na miejsce",
    "tace i wózek na naczynia",
    "fartuszki dyżurnych",
    "lista czynności dyżurnego w obrazkach",
    "dzwonek zapraszający do stołu"],
   ["Dyżurni sprawdzają na grafiku, co dziś do nich należy.",
    "Rozkładają nakrycia według wzoru na podkładce, bez przypominania.",
    "Przeliczają miejsca przy stoliku i przygotowują tyle nakryć."],
   "Sprawdź na grafiku, co dziś należy do ciebie. Policz, ile jest miejsc przy waszym stoliku, i przygotuj tyle samo nakryć. Kiedy skończycie, zadzwońcie i zaproście grupę.",
   "Przeliczenie miejsc to ukryty cel matematyczny tego dyżuru. Podanie liczby przez dorosłego odbiera dziecku jedyny moment, w którym liczy po coś."),

 "c6_27": ("C6-27", "Dyżury z rozliczeniem",
   ["grafik tygodniowy dyżurów, widoczny dla dzieci",
    "plany czynności dla każdego rodzaju dyżuru",
    "karta rozliczenia tygodniowego",
    "identyfikatory dyżurnych",
    "miejsce na piątkowy krąg podsumowujący"],
   ["W poniedziałek dziecko wybiera dyżur i zapoznaje się z planem.",
    "Przez tydzień obserwuj bez przypominania — czekaj na zgłoszenie.",
    "W piątek poprowadź krąg: każdy opowiada, jak mu poszło."],
   "Wybierz dyżur na cały tydzień i przeczytaj jego plan. Przez pięć dni pamiętasz o nim sam — nie będę przypominać. W piątek opowiesz nam, jak ci poszło i co było trudne.",
   "Brak przypominania jest tu warunkiem, nie zaniedbaniem. Dziecko, któremu się przypomina, wykonuje polecenie; dziecko, któremu się nie przypomina, pełni dyżur."),

 "c6_28": ("C6-28", "Porządek w mojej przestrzeni",
   ["zdjęcie wzorcowe uporządkowanej półki",
    "przegródki i pudełka z etykietami",
    "karta przeglądu tygodniowego",
    "minutnik na czas porządkowania",
    "aparat do zdjęcia półki po pracy"],
   ["Dziecko porównuje swoją półkę ze zdjęciem wzorcowym.",
    "Uruchom minutnik — porządkowanie ma koniec, nie trwa w nieskończoność.",
    "Zrób zdjęcie po pracy; dziecko porównuje je ze wzorcem."],
   "Popatrz na zdjęcie, jak powinna wyglądać półka, i porównaj ze swoją. Masz pięć minut. Na końcu zrobimy zdjęcie twojej półki i zobaczymy, czy jest podobne do wzoru.",
   "Zdjęcie wzorcowe zastępuje ocenę. Dziecko widzi różnicę samo i poprawia bez uwagi z zewnątrz — to jest przejście od sprzątania na polecenie do dbania o swoje."),

 "c6_29": ("C6-29", "Ogrodnicy z kącika przyrody",
   ["rośliny doniczkowe i uprawy w przezroczystych słoikach",
    "konewki z podziałką",
    "instrukcje pielęgnacji w obrazkach, przy każdej roślinie",
    "dziennik obserwacji z rubrykami na datę i pomiar",
    "lupy i linijki do mierzenia wzrostu"],
   ["Dziecko odczytuje z instrukcji, ile wody potrzebuje dana roślina.",
    "Odmierza wodę konewką z podziałką — nie „na oko”.",
    "Mierzy roślinę linijką i zapisuje wynik w dzienniku."],
   "Przy każdej roślinie wisi kartka. Przeczytaj, ile wody potrzebuje ta, i odmierz dokładnie tyle konewką. Potem zmierz ją linijką i zapisz w dzienniku, ile urosła od wczoraj.",
   "Podziałka na konewce i linijka zamieniają podlewanie w pomiar. Bez nich dyżur przyrodniczy jest czynnością porządkową, a nie obserwacją."),

 "c7_30": ("C7-30", "Rada grupy",
   ["tablica propozycji",
    "żetony do głosowania, po jednym na dziecko",
    "urna wyborcza",
    "protokół rady grupy do wypełnienia",
    "dzwonek otwierający i zamykający radę"],
   ["Otwórz radę dzwonkiem i zapisz wszystkie propozycje bez oceniania.",
    "Rozdaj po jednym żetonie i przeprowadźcie głosowanie do urny.",
    "Policzcie głosy razem i ogłoś wynik — także niezgodny z Pani zdaniem."],
   "Otwieram radę naszej grupy. Zgłoś swoją propozycję, zapiszę wszystkie. Potem każdy dostanie jeden żeton i wrzuci go przy tym pomyśle, który wybiera. Policzymy głosy razem.",
   "Wynik musi być wiążący, także wtedy, gdy wygra pomysł mniej wygodny. Jedna niezrealizowana uchwała wystarczy, żeby rada przestała być dla dzieci prawdziwa."),

 "c7_31": ("C7-31", "Kodeks naszej grupy",
   ["plakat kodeksu z miejscem na podpisy dzieci",
    "karty sytuacji do omówienia",
    "zdjęcia dzieci o różnych potrzebach",
    "tablica „różnimy się”",
    "pieczątka zgody dla każdego dziecka"],
   ["Zbierz propozycje zasad od dzieci, nie podawaj gotowych.",
    "Zapisz je i poproś o podpisanie kodeksu własnym znakiem.",
    "Przy trudnej sytuacji wskazuj kodeks zamiast upominać."],
   "Zastanówmy się, jakich zasad potrzebujemy w naszej grupie. Powiedz swoją propozycję, zapiszę ją. Kiedy ustalimy wszystkie, podpiszesz kodeks swoim znakiem — to będzie nasza umowa.",
   "Zasady zaproponowane przez dzieci działają, bo dzieci ich bronią. Kodeks napisany przez dorosłego jest kolejnym plakatem na ścianie."),

 "c7_32": ("C7-32", "Konsekwencje moich wyborów",
   ["plakat schematu przeprosin w trzech krokach",
    "karty sytuacji: co się stanie, jeśli…",
    "kącik naprawy relacji, dostępny w każdej chwili",
    "historyjki obrazkowe o skutkach zachowań",
    "dziennik dobrych naprawień"],
   ["Dziecko przewiduje skutek zachowania z karty, zanim je omówicie.",
    "Omów schemat przeprosin: zrobiłem – poczułeś – naprawię.",
    "Odegrajcie realną sytuację z sali i przećwiczcie naprawę."],
   "Popatrz na tę kartę i powiedz, co się stanie, jeśli tak zrobisz. Teraz nauczymy się przepraszać w trzech krokach: co zrobiłem, co przez to poczułeś, jak to naprawię. Sama „przepraszam” nie wystarczy.",
   "Trzeci krok — naprawa — jest tym, którego zwykle brakuje. Przeprosiny bez naprawy dziecko szybko odkrywa jako formułę, która kończy sprawę bez kosztu."),

 "c7_33": ("C7-33", "Pogotowie pomocne",
   ["karty sposobów pomagania: podpowiem, przytrzymam, pocieszę",
    "opaski pogotowia pomocnego",
    "tablica dobrych uczynków",
    "historyjki o bezradności i o pomaganiu",
    "pudełko podziękowań"],
   ["Omów trzy sposoby pomagania i poproś o ich nazwanie.",
    "Wskaż kolegę z trudnością i zapytaj, na czym ta trudność polega.",
    "Przypomnij zasadę: pomagam, nie wyręczam — i obserwuj."],
   "Są trzy sposoby pomagania: mogę podpowiedzieć, mogę przytrzymać, mogę pocieszyć. Popatrz, z czym kolega ma trudność, i wybierz sposób. Pamiętaj: pomagamy, ale nie robimy za kogoś.",
   "Rozróżnienie pomagam / wyręczam jest tu całą treścią. Sześciolatek pomaga najchętniej przez zrobienie za kolegę i trzeba mu pokazać, że to nie jest pomoc."),

 "c7_34": ("C7-34", "Przyjaźń i słowa, które ranią",
   ["papierowe serca, po jednym na dziecko",
    "karty zachowań: pomocne i raniące",
    "historyjki o przyjaźni i o wykluczeniu",
    "tablica przyjaciół grupy",
    "książka o wykluczeniu do wspólnego czytania"],
   ["Rozdaj serca i przy każdym raniącym zdaniu poproś o zgniecenie.",
    "Poproś o wyprostowanie serca — dziecko widzi trwałe zagniecenia.",
    "Posortujcie karty zachowań i porozmawiajcie o naprawie."],
   "Trzymasz w dłoni serce kolegi. Przy każdym przykrym słowie zgnieć je trochę. A teraz spróbuj je wyprostować. Popatrz — da się wygładzić, ale ślady zostają. Tak samo działają słowa.",
   "Nie kończ na zgniecionym sercu. Bez rozmowy o naprawie ćwiczenie zostawia poczucie winy i nic poza tym; naprawa jest tym, czego dziecko ma się nauczyć."),

 "c8_35": ("C8-35", "Zespół projektowy",
   ["karty podziału ról w zespole",
    "materiały projektowe wspólne dla zespołu, nie dla każdego osobno",
    "tablice zespołów",
    "mikrofon do prezentacji",
    "karta oceny współpracy, nie efektu"],
   ["Przedstaw zadanie zespołom i rozdaj karty ról do uzgodnienia.",
    "Obserwuj pracę; przy sporze wspieraj, ale nie rozstrzygaj za dzieci.",
    "Każde dziecko prezentuje swoją część, nie tylko lider zespołu."],
   "Pracujecie w zespole nad jednym zadaniem. Najpierw uzgodnijcie między sobą, kto co robi, i zapiszcie to na karcie ról. Na końcu każdy opowie o swojej części — nie tylko jedna osoba za wszystkich.",
   "Materiały wspólne dla zespołu, a nie po komplecie na dziecko, są tym, co wymusza współpracę. Przy własnym komplecie dzieci pracują obok siebie, nie razem."),

 "c8_36": ("C8-36", "Skończone i pokazane",
   ["skala samooceny z trzema buźkami",
    "teczki prac skończonych, osobne dla każdego dziecka",
    "tablica wystawy na wysokości oczu dziecka",
    "karta „z czego jestem dumny”",
    "stempel ukończenia"],
   ["Ustalcie kryterium ukończenia, zanim dziecko zacznie pracę.",
    "Odsuń się i nie przypominaj o pracy — praca ma być doprowadzona sama.",
    "Po skończeniu dziecko ocenia się na skali i wskazuje najlepszy fragment."],
   "Zanim zaczniesz, powiedz mi, po czym poznasz, że praca jest skończona. Potem pracuj sam, nie będę przypominać. Na końcu ocenisz ją na skali i pokażesz mi fragment, z którego jesteś najbardziej dumny.",
   "Kryterium ukończenia ustalone na starcie zmienia wszystko. Bez niego „skończone” znaczy „znudziło mi się”, i nie ma o czym rozmawiać przy samoocenie."),

 "c8_37": ("C8-37", "Turniej gier z regułami",
   ["gry planszowe i ruchowe o jasnych regułach",
    "tablica reguł w obrazkach, widoczna w czasie gry",
    "gwizdek sędziego",
    "tabela turniejowa",
    "medale fair play, przyznawane przez dzieci"],
   ["Spiszcie reguły na tablicy i poproś o powtórzenie własnymi słowami.",
    "Wyznacz sędziego spośród dzieci i oddaj mu gwizdek.",
    "Spory rozstrzygajcie, wskazując tablicę reguł, nie własnym autorytetem."],
   "Zanim zagramy, powtórz mi reguły swoimi słowami. Jedno z was będzie sędzią i to ono pilnuje kolejności. Jeśli się nie zgodzicie, sprawdzamy na tablicy reguł — tam jest zapisane, jak gramy.",
   "Odwoływanie się do tablicy zamiast do własnego zdania uczy, że reguła obowiązuje niezależnie od tego, kto ją przypomina. To warunek, żeby sędzia-dziecko był w ogóle słuchany."),

 "c8_38": ("C8-38", "Sklep z prawdziwą kasą",
   ["monety 1, 2 i 5 zł — prawdziwe albo wierne kopie",
    "cenniki z cyframi, ceny do 10 zł",
    "kasa z przegródkami na nominały",
    "towary z metkami",
    "portfele dzieci"],
   ["Dziecko rozpoznaje monety i nazywa ich wartość.",
    "Wybiera towar, odczytuje cenę i odlicza właściwą kwotę.",
    "Zamieńcie role: kupujący zostaje sprzedawcą i wydaje resztę."],
   "Popatrz na te monety i powiedz mi, ile jest warta każda z nich. Teraz wybierz towar, przeczytaj cenę i odlicz dokładnie tyle pieniędzy. Potem zamienimy się — ty będziesz sprzedawcą.",
   "Prawdziwe monety, nie żetony. Sześciolatek zna je z domu i to jedyny moment, w którym liczenie w sklepie łączy się z tym, co widzi poza przedszkolem."),

 "c8_39": ("C8-39", "Mali badacze świata",
   ["albumy, atlasy i encyklopedie dziecięce",
    "lupy i mikroskop dziecięcy",
    "tablica pytań grupy, uzupełniana przez cały rok",
    "karty małego badacza do zapisu odkrycia",
    "aparat do dokumentacji"],
   ["Dziecko wybiera z tablicy pytanie, które je interesuje.",
    "Pomóż odnaleźć źródło i właściwą stronę, ale nie czytaj odpowiedzi.",
    "Dziecko zapisuje lub dyktuje, czego się dowiedziało."],
   "Na tablicy są pytania, które sami zadaliście. Wybierz to, które cię ciekawi, i poszukaj odpowiedzi w atlasie albo albumie. Kiedy znajdziesz, zapisz albo podyktuj mi, czego się dowiedziałeś.",
   "Pytania muszą pochodzić od dzieci i zostawać na tablicy tygodniami. Pytanie zadane przez dorosłego na początku zajęć nie uruchamia szukania, tylko odpytywanie."),

 "c9_40": ("C9-40", "Kręgi przynależności",
   ["plansza kręgów przynależności: ja – rodzina – grupa – miejscowość",
    "zdjęcia rodzin dzieci, przyniesione z domu",
    "mapa miejscowości",
    "zdjęcia znanych miejsc w okolicy",
    "album grupy"],
   ["Dziecko umieszcza swoje zdjęcie w środku planszy.",
    "Przechodzicie krąg po kręgu: rodzina, grupa, miejscowość.",
    "Na mapie dziecko wskazuje miejsca, które zna."],
   "W środku tej planszy jesteś ty — połóż tu swoje zdjęcie. Teraz następny krąg: kto jest w twojej rodzinie? Potem nasza grupa, a na końcu nasza miejscowość. Pokaż mi na mapie miejsce, które znasz.",
   "Zdjęcia rodzin przynoszą dzieci z domu i to jest część zadania. Zdjęcia dostarczone przez przedszkole zamieniają osobistą planszę w ćwiczenie z pojęć."),

 "c9_41": ("C9-41", "Polska na mapie",
   ["mapa Polski, duża, na podłodze albo na ścianie nisko",
    "godło i flaga",
    "nagranie hymnu",
    "zdjęcia miast i regionów",
    "materiały do wykonania kotylionu"],
   ["Dziecko odnajduje własną miejscowość na mapie, zanim padnie nazwa kraju.",
    "Pokaż godło i flagę; dziecko nazywa symbole i kolory.",
    "Włącz hymn i pokaż postawę — stoicie razem, bez komentarza."],
   "To jest mapa Polski. Znajdź na niej naszą miejscowość — pokażę ci mniej więcej gdzie, a ty wskaż dokładnie. Teraz popatrz na flagę i powiedz mi, jakie ma kolory. A to jest Warszawa, nasza stolica.",
   "Kolejność od własnej miejscowości do kraju, nie odwrotnie. Sześciolatek buduje pojęcie kraju z miejsc, które zna; zaczynanie od mapy całości daje słowo bez treści."),

 "c9_42": ("C9-42", "Moje dane, moje bezpieczeństwo",
   ["legitymacje przedszkolaka do wypełnienia",
    "zdjęcia osób zaufanych, wskazanych przez dziecko",
    "scenki: nieznajomy pyta o dane",
    "numer alarmowy 112 na plakacie",
    "opaski z danymi na wycieczki"],
   ["Dziecko podaje swoje imię, nazwisko i miejscowość do legitymacji.",
    "Odegrajcie scenkę: nieznajomy pyta o adres — dziecko ćwiczy odmowę.",
    "Wskażcie razem, komu dane podać wolno."],
   "Wpiszemy do legitymacji twoje imię, nazwisko i miejscowość. Teraz zagramy w scenkę: ja jestem kimś obcym i pytam cię o adres. Twoje zadanie to odmówić i odejść do dorosłego, którego znasz.",
   "Ćwiczcie odmowę, a nie samą wiedzę. Dziecko, które umie wyrecytować adres, ale nie ma przećwiczonego „nie powiem”, poda go pierwszej osobie, która zapyta pewnym głosem."),

 "c9_43": ("C9-43", "Strażnicy planety",
   ["pojemniki w kolorach frakcji z piktogramami",
    "czyste odpady do segregowania",
    "plakat obiegu wody i prądu",
    "licznik zużycia wody przy umywalce",
    "odznaki strażnika planety"],
   ["Dziecko nazywa, co trafia do każdego pojemnika, zanim zacznie segregować.",
    "Rozdaj zestaw pięciu odpadów i obserwuj bez poprawiania od razu.",
    "Pokaż licznik wody przy myciu rąk — liczba robi tu robotę."],
   "Popatrz na pojemniki i powiedz mi, co wrzucamy do każdego. Teraz masz pięć rzeczy — posegreguj je sam. Potem zobaczymy na liczniku, ile wody zużywasz, myjąc ręce.",
   "Odpady muszą być czyste i prawdziwe, nie obrazkowe. Segregacja obrazków sprawdza wiedzę; segregacja rzeczy uczy decyzji, którą dziecko podejmie potem w domu."),

 "c9_44": ("C9-44", "Kim będę, kim jestem",
   ["atrybuty i stroje zawodowe do przymierzenia",
    "karty zawodów i karty narzędzi, osobno",
    "zaproszenia dla rodziców-gości",
    "album zawodów rodziców grupy",
    "kącik zawodów z atrybutami"],
   ["Zaproszony rodzic opowiada o swojej pracy; dzieci zadają pytania.",
    "Dziecko dopasowuje narzędzia do zawodów i opisuje trzy z nich.",
    "Otwórz kącik zawodów i pozwól odegrać wybraną rolę."],
   "Dziś opowie nam o swojej pracy mama Zosi. Posłuchaj i zadaj jej pytanie. Potem dopasujesz narzędzia do zawodów i wybierzesz rolę, którą chcesz odegrać w naszym kąciku.",
   "Zaproszenie rodzica jest tu warte więcej niż komplet kart. Zawód opowiedziany przez kogoś, kogo dziecko zna, przestaje być obrazkiem i staje się czyjąś pracą."),
}

ZESTAW = Zestaw(POMOCE, "pomoce_c", "audio_c", "6 lat", "Pomoce_dydaktyczne_6_lat.html")
