# -*- coding: utf-8 -*-
"""Pomoce dydaktyczne do konspektów wersji B (5 lat).

Ta sama karta co w wersji A, ale pomoce są trudniejsze: więcej kroków po
stronie dziecka, więcej materiału do wyboru, więcej sytuacji, w których to
dziecko prowadzi zabawę, a nauczyciel tylko przygotowuje warunki.

Układ karty i osadzanie mediów: `pomoce_karta`.
"""

from pomoce_karta import Zestaw

# kod → (nr konspektu, tytuł pomocy, [co przygotować], [trzy kroki], tekst nagrania, wskazówka)
POMOCE = {
 "b1_01": ("B1-01", "Detektywi opowieści",
   ["opowiadania pięciominutowe z wyraźną akcją i jednym zwrotem",
    "lupy detektywistyczne — po jednej na dziecko",
    "karty historyjki obrazkowej, cztery sceny, do ułożenia po czytaniu",
    "odznaki „detektyw opowieści” z filcu",
    "tablica z czterema pytaniami w obrazkach: kto, gdzie, co się stało, dlaczego"],
   ["Rozdaj lupy i odznaki, zapowiedz, że po czytaniu będą pytania.",
    "Czytaj całość, ale zatrzymaj się tuż przed rozwiązaniem akcji.",
    "Po czytaniu dziecko układa cztery sceny i odpowiada na dwa pytania z tablicy."],
   "Dziś jesteśmy detektywami opowieści. Słuchaj uważnie, bo potem zapytam, co się wydarzyło. Weź lupę i szukaj śladów w obrazkach.",
   "Zatrzymaj czytanie tuż przed rozwiązaniem akcji — pięciolatek, który sam próbuje zgadnąć zakończenie, słucha reszty opowiadania inaczej niż ten, któremu wszystko podano."),

 "b1_02": ("B1-02", "Fabryka rytmów",
   ["klocki logiczne różniące się kolorem, kształtem i wielkością",
    "dwie obręcze do segregowania",
    "paski do układania rytmów, długie na co najmniej osiem elementów",
    "taśma produkcyjna z szarego papieru — scenografia fabryki",
    "karty zamówień z wzorem rytmu do odtworzenia"],
   ["Dziecko segreguje klocki do obręczy według jednej cechy i nazywa kryterium.",
    "Zmień kryterium i poproś o przesegregowanie tego samego zbioru.",
    "Podaj kartę zamówienia; dziecko układa rytm dwuelementowy do końca paska."],
   "Nasza fabryka przyjmuje zamówienie. Najpierw poukładaj klocki do obręczy i powiedz mi, dlaczego tak. Potem ułóż rytm z karty, aż do końca paska.",
   "Poproś o nazwanie kryterium — dziecko, które powie „bo są okrągłe”, myśli o cesze; dziecko, które tylko układa, może kopiować układ sąsiada."),

 "b1_03": ("B1-03", "Sklep pod piątką",
   ["kącik sklepowy: drewniane owoce i warzywa, dwa koszyki",
    "listy zakupów z kropkami zamiast cyfr",
    "kasa i żetony do płacenia",
    "trzy płytkie tacki do układania liczonych elementów",
    "kartoniki z cyframi od jednego do dziesięciu"],
   ["Dziecko bierze listę i odczytuje z niej liczbę kropek.",
    "Przekłada towar na tackę po jednym, licząc na głos.",
    "Podaje wynik bez ponownego liczenia i dokłada kartonik z cyfrą."],
   "Otwieramy nasz sklep. Popatrz na listę i przekładaj owoce na tackę, po jednym. Na końcu powiedz mi, ile ich jest.",
   "Tacka rozwiązuje najczęstszy błąd — dziecko liczące w kupce wraca do tych samych przedmiotów; przekładanie po jednym wymusza zasadę jeden do jednego."),

 "b1_04": ("B1-04", "Kwadrans badacza",
   ["licznik kroków z pięcioma polami do zakrywania",
    "zadania wieloetapowe: mozaika, sekwencja, sortowanie",
    "klepsydra dziesięciominutowa, ustawiona w polu widzenia",
    "karta „skończone” do podpisania przez dziecko",
    "słuchawki wygłuszające dostępne bez pytania"],
   ["Pokaż licznik i policzcie razem, ile kroków ma dzisiejsze zadanie.",
    "Po każdym ukończonym kroku dziecko samo zakrywa jedno pole.",
    "Po ostatnim polu podpisujecie kartę „skończone” i odkładacie pracę."],
   "Zaczynamy kwadrans badacza. Popatrz na licznik: masz pięć kroków do zrobienia. Po każdym kroku zakryj jedno pole i pracuj dalej.",
   "Licznik pokazujący, ile zostało, działa lepiej niż zegar odmierzający czas — pięciolatek nie czuje minut, ale doskonale widzi, że zostały dwa pola."),

 "b1_05": ("B1-05", "Polowanie na litery",
   ["karty z pojedynczymi literami i cyframi, duże i wyraźne",
    "litery rozwieszone w sali: na drzwiach, pudełkach, półkach",
    "kartoniki z imionami dzieci",
    "stemple z literami i poduszka do stemplowania",
    "masa plastyczna do lepienia kształtów liter"],
   ["Dziecko bierze kartonik ze swoim imieniem i wybiera z niego jedną literę.",
    "Szuka takiej samej litery w sali i przynosi kartę do stolika.",
    "Utrwala znalezioną literę: odbija stempel albo lepi ją z masy."],
   "Idziemy na polowanie na litery. Weź kartonik ze swoim imieniem i poszukaj takiej samej litery w sali. Kiedy znajdziesz, przynieś ją do mnie.",
   "Zacznij od liter imienia — to jedyny napis, który pięciolatek uważa za naprawdę swój, i właśnie przy nim najszybciej odkrywa, że znaki coś znaczą."),

 "b2_06": ("B2-06", "Instrukcja mistrza budowy",
   ["instrukcje obrazkowe trzyetapowe — budowla, praca plastyczna, eksperyment",
    "kaski i identyfikatory „mistrz budowy”",
    "materiał do każdego zadania w osobnym pojemniku",
    "tablica ukończonych zleceń z miejscem na żeton"],
   ["Wręcz identyfikator i połóż instrukcję tak, by dziecko ją widziało cały czas.",
    "Gdy dziecko utknie, wskaż kolejny obrazek zamiast mówić, co robić.",
    "Po skończeniu dziecko samo dokłada żeton na tablicy zleceń."],
   "Jesteś dziś mistrzem budowy. Na kartce są trzy kroki. Zrób pierwszy, potem popatrz na drugi. Kiedy nie wiesz, co dalej, zajrzyj na kartkę.",
   "Wskazuj instrukcję zamiast podpowiadać — celem nie jest ukończone zadanie, lecz nawyk sięgania po instrukcję, który zostanie z dzieckiem w szkole."),

 "b2_07": ("B2-07", "Most między zajęciami",
   ["plan dnia z ruchomym wskaźnikiem, przestawianym przy każdej zmianie",
    "minutnik wizualny pokazujący kurczący się kolor",
    "rytmiczna wyliczanka porządkowa, zawsze ta sama",
    "karta „co robię, gdy skończę” — jedno zadanie pomostowe"],
   ["Dwie minuty przed zmianą włącz minutnik i pokaż go dziecku.",
    "Po sygnale przestaw wskaźnik na planie i zacznij wyliczankę.",
    "Dziecko, które skończyło pierwsze, wykonuje zadanie z karty pomostowej."],
   "Zaraz kończymy tę zabawę. Popatrz na minutnik: zostało już niewiele. Kiedy skończysz, odłóż rzeczy i usiądź na dywanie.",
   "Zadanie pomostowe likwiduje najtrudniejszy moment — dziecko, które wie, co robić po skończeniu, nie zaczyna nowej zabawy tuż przed przejściem."),

 "b2_08": ("B2-08", "Kolejka po skarb",
   ["tablica kolejki ze zdjęciami dzieci ułożonymi pionowo",
    "klepsydra dwuminutowa, widoczna z miejsca czekania",
    "gra planszowa wielkoformatowa rozłożona na podłodze",
    "skrzynia ze skarbem — nagroda zespołowa, nie indywidualna",
    "karty strategii czekania: kibicuję, liczę, patrzę na klepsydrę"],
   ["Ustaw kolejkę na tablicy i pokaż dziecku, które jest w kolejności.",
    "Wręcz kartę strategii — dziecko dostaje zajęcie na czas czekania.",
    "Po rundzie przesuń znacznik kolejki i otwórzcie skrzynię wspólnie."],
   "Popatrz na tablicę: twoje zdjęcie jest drugie. Kiedy czekasz, kibicuj koledze i pilnuj klepsydry. Za chwilę będzie twoja kolej.",
   "Daj dziecku zajęcie na czas czekania — kibicowanie koledze zamienia puste oczekiwanie w rolę, a rola jest znośna nawet dla niecierpliwych."),

 "b2_09": ("B2-09", "Moje stanowisko pracy",
   ["listy obrazkowe materiałów potrzebnych do każdego zadania",
    "zdjęcie wzorcowe gotowego stanowiska, oprawione i postawione obok",
    "pojemniki z etykietami obrazkowymi",
    "tacki do pracy indywidualnej, wyznaczające obszar dziecka",
    "karta samooceny porządku z dwiema minami"],
   ["Dziecko bierze listę obrazkową i kompletuje materiały na tacce.",
    "Porównuje ułożenie ze zdjęciem wzorcowym, zanim zacznie pracę.",
    "Po pracy odkłada wszystko na miejsce i zaznacza minę na karcie samooceny."],
   "Przygotuj swoje stanowisko. Popatrz na zdjęcie i połóż wszystko tak samo. Po pracy porównaj jeszcze raz i odłóż rzeczy na miejsce.",
   "Zdjęcie gotowego stanowiska zastępuje ciąg poleceń — dziecko porównuje obraz z rzeczywistością samo, a dorosły przestaje być listą kontrolną."),

 "b2_10": ("B2-10", "Najpierw próbuję, potem proszę",
   ["plakat zasady w dwóch obrazkach: próbuję → proszę",
    "zadania z celową trudnością: brakujący element układanki, ciasne zamknięcie",
    "kartonik „potrzebuję pomocy” do położenia na stoliku",
    "zdania-wzory na karcie: „nie mogę…, pomożesz?”"],
   ["Podaj zadanie z ukrytą trudnością i usiądź obok, nie nad dzieckiem.",
    "Gdy pojawi się trudność, odczekaj pełne dziesięć sekund w milczeniu.",
    "Po samodzielnej próbie wskaż plakat i pomóż sformułować prośbę."],
   "U nas jest taka zasada: najpierw próbuję, potem proszę. Spróbuj sam jeden raz. Jeśli się nie uda, powiedz: nie mogę, pomożesz mi?",
   "Milcz przez pełne dziesięć sekund — to najtrudniejszy element tych zajęć dla dorosłego i najważniejszy dla dziecka, które właśnie odkrywa własną skuteczność."),

 "b3_11": ("B3-11", "Radio Przedszkole",
   ["mikrofon zabawkowy albo dyktafon z możliwością odsłuchu",
    "znaczek reportera przypinany na czas nagrania",
    "zdjęcia z wydarzeń w sali, robione tego samego dnia",
    "tablica pytań reportera w obrazkach: kto, co, gdzie, kiedy",
    "głośnik do wspólnego odsłuchania nagrania"],
   ["Dziecko wybiera zdjęcie i zakłada znaczek reportera.",
    "Mówi do mikrofonu, pomagając sobie pytaniami z tablicy.",
    "Odsłuchujecie nagranie razem i dziecko decyduje, czy chce powtórzyć."],
   "Radio Przedszkole zaprasza do mikrofonu. Popatrz na zdjęcie i opowiedz, co się wydarzyło. Powiedz kto, gdzie i co robił. Potem posłuchamy nagrania.",
   "Odsłuchanie własnego nagrania robi więcej niż dziesięć poprawek — dziecko samo słyszy, czego zabrakło, i następnym razem mówi pełniej."),

 "b3_12": ("B3-12", "Kronika dnia",
   ["kronika grupy — album, do którego wklejacie zdjęcia każdego dnia",
    "karty porządkujące: najpierw – potem – na końcu",
    "zdjęcia robione aparatem w ciągu dnia, wydrukowane od razu",
    "pisak do podpisywania zdjęć",
    "pieczątka kronikarza dla dziecka, które opowiedziało"],
   ["Wybierzcie trzy zdjęcia z dzisiejszego dnia.",
    "Dziecko układa je pod kartami: najpierw, potem, na końcu.",
    "Opowiada trzema zdaniami, wkleja zdjęcia i przybija pieczątkę."],
   "Piszemy dziś naszą kronikę. Ułóż trzy zdjęcia: co było najpierw, co potem, a co na końcu. Teraz opowiedz mi to trzema zdaniami.",
   "Rób zdjęcia w ciągu dnia — pięciolatek opowiada nieporównanie chętniej o tym, co widzi na ekranie, niż o tym, co ma odtworzyć z pamięci."),

 "b3_13": ("B3-13", "Rozmowa przy stoliku",
   ["przedmiot mówcy: gładki kamyk albo mały mikrofon",
    "karty startowe pytań z obrazkami — „co lubisz…?”",
    "stolik do rozmów z dwoma krzesłami naprzeciw siebie",
    "piktogram dwustronny: słucham – mówię",
    "klepsydra trzyminutowa wyznaczająca długość rozmowy"],
   ["Posadź dwoje dzieci naprzeciw siebie i połóż kamyk na środku.",
    "Pierwsze dziecko bierze kamyk, zadaje pytanie z karty i oddaje kamyk.",
    "Po odpowiedzi kamyk wraca — druga runda należy do drugiego dziecka."],
   "Siadacie naprzeciwko siebie do rozmowy. Mówi ten, kto trzyma kamyk. Drugi słucha i nie przerywa. Zadaj pytanie, posłuchaj odpowiedzi i podaj kamyk dalej.",
   "Kamyk w dłoni działa lepiej niż przypomnienie „nie przerywaj” — reguła staje się widoczna i dziecko samo pilnuje, kto ma teraz głos."),

 "b3_14": ("B3-14", "Rymowana kuchnia",
   ["garnek „rymowana kuchnia” i drewniana łyżka",
    "obrazki-składniki dobrane w rymujące się pary",
    "wiersze czterowersowe z gestem przypisanym każdemu wersowi",
    "karty z parami rymów do dobierania",
    "fartuszki kucharskie"],
   ["Dzieci wrzucają do garnka obrazki, które rymują się parami.",
    "Recytujcie zwrotkę razem, wykonując gest do każdego wersu.",
    "Dziecko mówi zwrotkę samo; przy zacięciu podpowiadasz gestem, nie słowem."],
   "Gotujemy dziś w rymowanej kuchni. Wrzucamy do garnka słowa, które brzmią podobnie. Powiedz wierszyk razem ze mną i pokazuj ruchy rękami.",
   "Gest przypisany wersowi jest najskuteczniejszą podpowiedzią — gdy zabraknie słowa, ręka sama je przypomina, bez wyręczania przez dorosłego."),

 "b3_15": ("B3-15", "Teatr bez słów",
   ["karty pantomimy w dwóch kolorach: emocje i czynności",
    "kapelusz aktora zakładany na czas występu",
    "lustro, w którym dziecko sprawdza własną minę przed pokazem",
    "fotografie min do porównania",
    "kurtyna z materiału zawieszona w kąciku"],
   ["Dziecko losuje kartę i sprawdza minę w lustrze, zanim wyjdzie.",
    "Pokazuje treść karty samą miną i gestem, bez jednego słowa.",
    "Grupa zgaduje; jeśli nie odgadła, dziecko poprawia gest i pokazuje raz jeszcze."],
   "Zagramy w teatr bez słów. Wylosuj kartę i pokaż to samą miną i rękami, bez mówienia. Zobaczymy, czy koledzy odgadną.",
   "Publiczność jest tu narzędziem uczenia — dziecko poprawia gest nie na prośbę dorosłego, lecz dlatego, że koledzy nie odgadli, co pokazywało."),

 "b4_16": ("B4-16", "Olimpiada czterech ruchów",
   ["cztery stacje, każda z jednym symbolem ruchu — skok, podskok, rzut, czworakowanie",
    "szarfy w kolorach drużyn",
    "woreczki do rzutu i obręcze jako cele",
    "gwizdek i strzałki kierunkowe naklejone na podłodze",
    "medale i dyplomy olimpijskie na zakończenie"],
   ["Obejdźcie stacje i nazwijcie ruch z każdego symbolu — raz, przed startem.",
    "Dziecko wykonuje ruch po sygnale słownym, bez twojego pokazu.",
    "Na gwizdek drużyny przechodzą na kolejną stację zgodnie ze strzałkami."],
   "Zaczynamy naszą olimpiadę. Na każdej stacji jest obrazek. Popatrz na niego i zrób ten ruch. Kiedy usłyszysz gwizdek, biegniesz na następną stację.",
   "Symbol na stacji zwalnia nauczyciela z powtarzania poleceń — dziecko odczytuje zadanie z obrazka i całą uwagę kieruje na ruch, nie na słuchanie."),

 "b4_17": ("B4-17", "Linoskoczkowie",
   ["lina albo taśma naklejona prosto na podłodze, długości co najmniej dwóch metrów",
    "parasolki i wachlarze jako rekwizyty linoskoczka",
    "ławeczka gimnastyczna dla chętnych na wyższy poziom",
    "woreczki do niesienia na głowie",
    "muzyka cyrkowa"],
   ["Wyznacz punkt na ścianie i poproś, żeby dziecko na niego patrzyło.",
    "Dziecko stoi na jednej nodze, licząc razem z tobą do pięciu.",
    "Przechodzi po linii dwa metry, z rekwizytem albo woreczkiem na głowie."],
   "Jesteś dziś linoskoczkiem. Stań na linie i patrz na punkt przed sobą, nie pod nogi. Idź powoli do końca liny.",
   "Powiedz „patrz na punkt przed sobą”, nie „patrz pod nogi” — wzrok skierowany w dół rozstraja równowagę, którą właśnie ćwiczymy."),

 "b4_18": ("B4-18", "Pracownia nożyczek",
   ["nożyczki osobno dla dzieci prawo- i leworęcznych, wyraźnie rozróżnione kolorem",
    "paski papieru z jedną grubą linią prostą",
    "masa plastyczna do rozgrzewki dłoni",
    "duże koraliki i żyłka do nawlekania",
    "tacka na gotowe prace"],
   ["Zacznij od rozgrzewki: dziecko lepi z masy kulkę i wałek.",
    "Podaj nożyczki dopasowane do ręki i pasek z jedną grubą linią.",
    "Dziecko tnie po linii; gotową pracę odkłada na tackę."],
   "Najpierw rozgrzewamy dłonie w masie. Ulep kulkę i wałek, żeby paluszki się obudziły. Teraz weź nożyczki i tnij dokładnie po grubej linii.",
   "Rozgrzewka dłoni przed nożyczkami skraca naukę o tygodnie — ugniatanie masy przygotowuje te same mięśnie, które później prowadzą ostrze po linii."),

 "b4_19": ("B4-19", "Szlaczki na ścianie",
   ["papier przypięty do sztalugi albo do ściany, na wysokości oczu dziecka",
    "krótkie kredki — same wymuszają chwyt trójpalcowy",
    "nasadki korygujące dla dzieci, które ich potrzebują",
    "wzory szlaczków do odwzorowania",
    "tablica i kreda jako wariant"],
   ["Przypnij kartkę pionowo — nadgarstek sam ustawi się w wyproście.",
    "Podaj krótką kredkę i sprawdź chwyt raz, na początku pracy.",
    "Dziecko rysuje szlaczek do końca kartki i zamalowuje pole."],
   "Dziś rysujemy na stojąco. Weź krótką kredkę w trzy paluszki. Rysuj szlaczek do końca kartki i naciskaj delikatnie.",
   "Pionowa powierzchnia sama ustawia nadgarstek w wyproście — to najprostszy sposób poprawy chwytu, skuteczniejszy niż jakiekolwiek przypominanie."),

 "b4_20": ("B4-20", "Laboratorium przelewania",
   ["dzbanki, miski i łyżki w kilku wielkościach",
    "kasza, ryż i woda barwiona jako materiał do przesypywania",
    "tace z uchwytami i podniesionym brzegiem",
    "pipety i lejki do wariantu z wodą",
    "ściereczki w zasięgu ręki dziecka"],
   ["Postaw materiał na tacy z brzegiem — rozsypane zostaje na tacy.",
    "Dziecko przesypuje łyżką między naczyniami, powoli i bez pośpiechu.",
    "Na koniec przenosi tacę z dwoma kubkami na wyznaczone miejsce."],
   "Witaj w laboratorium przelewania. Przesypuj kaszę łyżką powoli, z miski do miski. Jeśli coś się rozsypie, ściereczka leży obok. Wycieramy i próbujemy dalej.",
   "Ściereczka w zasięgu ręki zmienia rozsypanie w naturalny element pracy — dziecko, które sprząta samo, próbuje dalej zamiast rezygnować ze wstydu."),

 "b5_21": ("B5-21", "Detektyw czystych rąk",
   ["brokat albo farba udająca „zarazki” do jednorazowego eksperymentu",
    "instrukcja obrazkowa powieszona nad umywalką, na wysokości oczu dziecka",
    "piosenka-minutnik wyznaczająca czas mycia",
    "lupa detektywistyczna do sprawdzania dłoni",
    "plakat o drobnoustrojach dla chętnych"],
   ["Raz zrób eksperyment: nasyp brokatu na dłonie i pokaż, gdzie zostaje.",
    "Dziecko myje ręce według obrazków, dopóki gra piosenka.",
    "Sprawdźcie efekt lupą — szczególnie kciuki i przestrzenie między palcami."],
   "Jesteś detektywem czystych rąk. Popatrz na obrazki nad umywalką i myj po kolei. Nie zapomnij o kciukach i o miejscach między palcami.",
   "Brokat pokazuje to, czego nie widać — po jednym takim eksperymencie dzieci myją kciuki i przestrzenie między palcami bez żadnego przypominania."),

 "b5_22": ("B5-22", "Wyścig z suwakiem",
   ["plan obrazkowy kolejności ubierania, powieszony w szatni",
    "tablice manipulacyjne z suwakiem, guzikami i rzepami — do ćwiczeń poza szatnią",
    "klepsydra w szatni, żeby pośpiech miał widoczną miarę",
    "lustro na wysokości dziecka",
    "tabela osiągnięć szatniowych"],
   ["Suwak, guziki i rzepy ćwiczcie na dywanie, na tablicach manipulacyjnych.",
    "W szatni dziecko ubiera się według planu obrazkowego, samo.",
    "Pomoc podajesz wyłącznie przy suwaku — i tylko wtedy, gdy dziecko poprosi."],
   "Ubieramy się sami. Popatrz na plan i wkładaj rzeczy po kolei. Poproś mnie tylko wtedy, kiedy dojdziesz do suwaka.",
   "Ćwicz suwak poza szatnią — w szatni jest pośpiech, kurtki i piętnaścioro dzieci; tablica manipulacyjna na dywanie daje spokój potrzebny do nauki."),

 "b5_23": ("B5-23", "Restauracja pod dobrą łyżką",
   ["podkładki z narysowanym nakryciem — widać, gdzie leży widelec, a gdzie łyżka",
    "serwetki w podajniku dostępnym dla dzieci",
    "widelce i łyżki w rozmiarze dziecięcym",
    "karta zasad restauracji w czterech obrazkach",
    "dzwoneczek otwarcia restauracji"],
   ["Dzwoneczek otwiera posiłek; dzieci nakrywają według podkładek.",
    "Usiądź i zjedz razem z dziećmi przy tym samym stole.",
    "Po posiłku dziecko wyciera buzię serwetką i dziękuje."],
   "Otwieramy naszą restaurację. Popatrz na podkładkę i połóż widelec i łyżkę na swoich miejscach. Po posiłku wytrzyj buzię serwetką i powiedz: dziękuję.",
   "Usiądź i zjedz z dziećmi — pięciolatek uczy się kultury stołu z obserwacji dorosłego przy tym samym stole, nie z instrukcji wygłaszanej nad stołem."),

 "b5_24": ("B5-24", "Strażnicy bezpieczeństwa",
   ["aparat do zdjęć — zasady ilustrujecie zdjęciami samych dzieci",
    "tablica zasad z fotografiami, powieszona przy wyjściu",
    "odznaki strażnika bezpieczeństwa",
    "pacynki do odegrania scenek „co się stanie, gdy…”",
    "plan placu zabaw z zaznaczonymi strefami"],
   ["Dzieci same wymyślają trzy zasady i pozują do zdjęć ilustrujących każdą.",
    "Powieście tablicę i przypominajcie zasady przed każdym wyjściem — raz.",
    "Odznakę dostaje dziecko, które w czasie wyjścia zasady zastosowało."],
   "Jesteście dziś strażnikami bezpieczeństwa. Popatrz na naszą tablicę i przypomnij mi trzy zasady. Na placu zabaw pilnujemy ich razem.",
   "Zasada wymyślona przez dzieci i zilustrowana ich zdjęciem jest przestrzegana nieporównanie lepiej niż plakat kupiony i powieszony przez dorosłego."),

 "b5_25": ("B5-25", "Barometr energii",
   ["barometr energii ze wskazówką i trzema polami: nisko – w sam raz – wysoko",
    "klipsy ze zdjęciami dzieci do przypinania na barometrze",
    "kącik ruchu: mata i poduszki do skakania",
    "kącik ciszy: namiot i kilka książek",
    "karty strategii: skaczę, oddycham, piję wodę"],
   ["Rano każde dziecko przypina swój klips na barometrze.",
    "W ciągu dnia dziecko może przestawić klips bez pytania o zgodę.",
    "Po przestawieniu wybiera kartę strategii i idzie do właściwego kącika."],
   "Popatrz na nasz barometr energii. Przypnij swój klips tam, gdzie teraz jesteś: nisko, w sam raz albo wysoko. Potem idź do kącika, którego potrzebujesz.",
   "Nazwij głośno własny poziom energii — dorosły, który mówi „potrzebuję chwili ciszy”, uczy samoregulacji skuteczniej niż jakikolwiek plakat o emocjach."),

 "b6_26": ("B6-26", "Zdjęcie przed i po",
   ["zdjęcia wzorcowe kącików, oprawione i postawione w każdym kąciku",
    "aparat albo tablet, którym zdjęcie robi dziecko, nie dorosły",
    "etykiety obrazkowe na pojemnikach",
    "tablica porównawcza z dwoma miejscami: przed i po",
    "minutnik wyznaczający czas sprzątania"],
   ["Przed sprzątaniem dziecko robi zdjęcie „przed” i włącza minutnik.",
    "Sprząta swoje miejsce pracy, porównując je ze zdjęciem wzorcowym.",
    "Robi zdjęcie „po” i wiesza obie fotografie na tablicy porównawczej."],
   "Kończymy pracę i sprzątamy swoje miejsce. Popatrz na zdjęcie: tak ma wyglądać kącik. Kiedy będzie gotowe, zrób zdjęcie i porównamy je razem.",
   "Zdjęcie zrobione przez dziecko zmienia sprzątanie w zadanie z widocznym efektem — porównanie dwóch obrazów ocenia lepiej niż uwaga dorosłego."),

 "b6_27": ("B6-27", "Dyżurni tygodnia",
   ["grafik tygodniowy ze zdjęciami dzieci — jeden dyżur na cały tydzień",
    "fartuszki i identyfikatory dyżurnych",
    "plany obrazkowe trzech dyżurów: stołowego, przyrodniczego, bibliotecznego",
    "karta samooceny z uśmieszkami",
    "dzwonek do zgłoszenia zakończenia dyżuru"],
   ["W poniedziałek dziecko wybiera dyżur i zostaje przy nim cały tydzień.",
    "Wykonuje oba etapy z planu obrazkowego, bez twojej pomocy.",
    "Zgłasza koniec dzwonkiem i zaznacza uśmieszek na karcie samooceny."],
   "W tym tygodniu masz swój dyżur. Popatrz na plan: najpierw pierwsza część, potem druga. Kiedy skończysz, zadzwoń dzwonkiem i powiedz mi, że gotowe.",
   "Pozwól wybrać dyżur na cały tydzień — powtarzalność buduje mistrzostwo, a wybór buduje odpowiedzialność; codzienna rotacja odbiera jedno i drugie."),

 "b6_28": ("B6-28", "Umowa o zabawki",
   ["karty umowy z dwoma polami na imiona i miejscem na ustaloną kolejność",
    "klepsydry trzy- i pięciominutowa do wyboru",
    "atrakcyjne zabawki celowo w jednym egzemplarzu",
    "szpital zabawek — pudełko na rzeczy do naprawy",
    "taśma i klej do wspólnych napraw"],
   ["Gdy pojawi się spór, wyjmij kartę umowy i zapiszcie na niej dwa imiona.",
    "Dzieci ustalają kolejność i wybierają klepsydrę; ty tylko prowadzisz rozmowę.",
    "Po przesypaniu piasku dziecko samo przekazuje zabawkę — nie odbieraj jej."],
   "Zabawka jest jedna, a chętnych dwoje. Umówcie się: kto bawi się pierwszy i jak długo. Kiedy piasek się przesypie, sam przekażesz ją koledze.",
   "Nie odbieraj zabawki po sygnale — pozwól dziecku samemu ją przekazać. Umowa dotrzymana własnymi rękami uczy więcej niż umowa wyegzekwowana."),

 "b6_29": ("B6-29", "Pakowanie na wyprawę",
   ["listy obrazkowe rzeczy — osobna na worek, osobna na plecak wycieczkowy",
    "worki i plecaki dzieci",
    "karty rzeczy do wyboru: część potrzebna, część wyraźnie zbędna",
    "zdjęcia pogody do dopasowania do listy",
    "tablica odpraw przy drzwiach"],
   ["Zacznijcie od segregowania kart: co potrzebne, a co zostaje w sali.",
    "Dziecko pakuje swoje rzeczy według listy obrazkowej.",
    "Przy tablicy odpraw sprawdza listę punkt po punkcie, zanim wyjdzie."],
   "Pakujemy się na wyprawę. Najpierw wybierz, co jest potrzebne, a co zostaje w sali. Potem sprawdź listę i policz, czy masz wszystko.",
   "Zacznij od wyboru rzeczy potrzebnych i niepotrzebnych — pakowanie bez tego etapu jest przepisywaniem listy, a nie decydowaniem, co naprawdę zabieram."),

 "b7_30": ("B7-30", "Zaproszenie do zabawy",
   ["karty zaproszeń z rysunkami zabaw do wręczenia koledze",
    "kącik dwuosobowy z jednym zestawem zabawek na dwoje",
    "tablica „z kim się dziś bawiłem” ze zdjęciami dzieci na magnesach",
    "gry, w które nie da się zagrać w pojedynkę"],
   ["Dziecko wybiera kartę zaproszenia i wręcza ją wybranemu koledze.",
    "Bawią się w kąciku dwuosobowym, gdzie zestaw zabawek jest jeden.",
    "Po zabawie oboje zaznaczają się nawzajem na tablicy magnesami."],
   "Weź kartę zaproszenia i zaproś kolegę do zabawy. Macie jeden zestaw na dwoje, więc bawcie się razem. Na koniec zaznaczcie na tablicy, z kim się dziś bawiliście.",
   "Jeden zestaw zabawek na dwoje dzieci tworzy naturalną potrzebę współpracy — dwa komplety dają zabawę równoległą, którą łatwo pomylić ze wspólną."),

 "b7_31": ("B7-31", "Zespół z pomysłem",
   ["zadania zespołowe: makieta, plakat, wspólna budowla",
    "materiał w jednym komplecie na cały zespół",
    "karta podziału ról z miejscem na to, kto co robi",
    "tablica pomysłów z pustymi karteczkami",
    "dzwonek narady zespołu"],
   ["Postaw jeden komplet materiału na środku stołu — po jednym na zespół.",
    "Każde dziecko zgłasza jeden pomysł i przypina karteczkę na tablicy.",
    "Zespół wypełnia kartę podziału ról, zanim zacznie pracę."],
   "Pracujecie razem, w parze. Macie jeden komplet materiałów, więc musicie się umówić. Powiedz koledze swój pomysł i ustalcie, kto co robi.",
   "Jeden komplet materiału na zespół jest całą metodą — bez niego dzieci pracują obok siebie i nigdy nie muszą się umówić."),

 "b7_32": ("B7-32", "Słowa, które pomagają",
   ["plakat zwrotów pokazanych w konkretnych sytuacjach, nie w oderwaniu",
    "pacynki do odegrania scenek",
    "skrzynka „miłych słów” z otworem na karteczki",
    "karteczki z podziękowaniami dla kolegów",
    "lustro do sprawdzenia własnej miny"],
   ["Odegraj pacynkami tę samą scenkę dwa razy: bez zwrotu i ze zwrotem.",
    "Zapytaj dzieci, czym te dwie scenki się różniły.",
    "W ciągu dnia przypominaj zwrot raz i wrzucajcie karteczki do skrzynki."],
   "Mamy słowa, które naprawdę pomagają. Proszę, dziękuję i przepraszam. Popatrz na obrazek i powiedz, którego słowa tu potrzeba.",
   "Pokaż scenkę bez zwrotu i ze zwrotem — pięciolatek uczy się grzeczności, gdy zobaczy jej skutek, a nie gdy usłyszy, że „tak się mówi”."),

 "b7_33": ("B7-33", "Mapa uczuć",
   ["koło emocji z czterema polami: radość, złość, smutek, strach",
    "historyjki społeczne z ilustracjami",
    "lustro emocji",
    "karty sytuacji zdarzających się w tej właśnie sali",
    "pacynki do odegrania zakończenia historii"],
   ["Przeczytaj krótką historyjkę i zatrzymaj się na trudnym momencie.",
    "Dziecko ustawia wskazówkę koła emocji i mówi, dlaczego tak sądzi.",
    "Zapytaj, co mogłoby bohaterowi pomóc, i odegrajcie to pacynkami."],
   "Popatrz na naszą mapę uczuć. Jak myślisz, co czuje teraz bohater i dlaczego? A co mogłoby mu pomóc?",
   "Pytanie „co mogłoby mu pomóc” jest ważniejsze niż samo nazwanie emocji — empatia zaczyna działać dopiero wtedy, gdy prowadzi do działania."),

 "b7_34": ("B7-34", "Trzy kroki zgody",
   ["plakat trzech kroków zgody powieszony nad stolikiem mediacji",
    "stolik mediacji z dwoma krzesłami, z dala od miejsca zdarzeń",
    "karty rozwiązań: na zmianę, razem, losujemy",
    "przedmiot mówcy",
    "pacynki do ćwiczenia mediacji na spokojnie, przed konfliktem"],
   ["Po konflikcie przeprowadź dzieci do stolika mediacji — zmiana miejsca uspokaja.",
    "Każde dziecko z przedmiotem mówcy opowiada, o co był spór.",
    "Połóż dwie karty rozwiązań i pozwól dzieciom wybrać jedną z nich."],
   "Siadamy przy stoliku zgody. Powiedz mi swoimi słowami, o co był spór. Mam dwa rozwiązania. Wybierzcie to, które wam pasuje.",
   "Prowadź mediację przy stoliku, nie w miejscu zdarzenia — zmiana miejsca sama obniża napięcie i sygnalizuje, że zaczyna się rozmowa, a nie kara."),

 "b8_35": ("B8-35", "Mój pomysł na zajęcia",
   ["plan zajęcia z trzema punktami, odsłanianymi po kolei",
    "patyczki ze zdjęciami dzieci — znaczniki zgłoszeń do odpowiedzi",
    "skrzynka pomysłów dzieci, otwierana raz w tygodniu",
    "materiały do zadań przygotowane w tackach",
    "dzwonek prezentacji"],
   ["Pokaż plan trzech punktów i odsłaniaj je w trakcie zajęcia.",
    "Do zgłoszeń używajcie patyczków — każde dziecko podnosi swój.",
    "Raz w tygodniu wyjmij pomysł ze skrzynki i naprawdę go zrealizuj."],
   "Popatrz na plan naszych zajęć: mamy trzy zadania. Kiedy chcesz coś powiedzieć, podnieś swój patyczek. A jeśli masz pomysł na kolejne zajęcia, wrzuć go do skrzynki.",
   "Skrzynka pomysłów naprawdę musi działać — jeśli choć raz zrealizujesz temat wrzucony przez dziecko, aktywność całej grupy zmienia się na stałe."),

 "b8_36": ("B8-36", "Miasto z podziałem ról",
   ["cztery kąciki tematyczne: sklep, dom, przychodnia, warsztat",
    "atrybuty ról i identyfikatory do przypięcia",
    "tablica ról z klipsami — widać, kto jest kim",
    "rekwizyty otwarte: pudełka i tkaniny, które mogą być czymkolwiek",
    "kasa, recepty, narzędzia — po jednym komplecie na kącik"],
   ["Dzieci ustalają role we dwoje i przypinają klipsy na tablicy ról.",
    "Zakładają identyfikatory i biorą atrybuty swojej roli.",
    "Wejdź do zabawy jako klient albo pacjent, nie jako nauczyciel."],
   "Otwieramy nasze miasto. Umówcie się we dwoje, kto jest sprzedawcą, a kto kupuje. Przypnijcie swoje klipsy na tablicy ról i zostańcie w nich do końca zabawy.",
   "Wejdź w rolę klienta, nie w rolę nauczyciela — pytanie zadane z wnętrza zabawy rozwija fabułę, pytanie z zewnątrz ją kończy."),

 "b8_37": ("B8-37", "Pracownia ulepszeń",
   ["materiały recyklingowe i plastyczne w otwartych pojemnikach, wszystkie widoczne",
    "karty technik: wydzieranka, stempel, kolaż",
    "sznurek z klipsami jako galeria prac",
    "karta samooceny z jednym pytaniem: co bym poprawił",
    "aparat do dokumentowania prac"],
   ["Podaj temat, ale nie technikę — dziecko wybiera dwie samodzielnie.",
    "Pracuje, mając wszystkie materiały w zasięgu wzroku i ręki.",
    "Po skończeniu odpowiada na jedno pytanie: co byś jeszcze zmienił."],
   "Dziś pracujesz w pracowni ulepszeń. Wybierz sam dwa sposoby pracy i materiały, które ci pasują. Kiedy skończysz, powiedz mi, co byś jeszcze w tej pracy zmienił.",
   "Pytanie „co byś zmienił” zamienia pracę plastyczną w projektowanie — i jest jedyną oceną, która nie odbiera dziecku poczucia autorstwa."),

 "b8_38": ("B8-38", "Orkiestra przedszkolna",
   ["instrumenty perkusyjne w trzech kolorach — po jednej grupie na kolor",
    "partytura obrazkowa: kolorowe pola pokazujące, kto kiedy gra",
    "batuta dyrygenta",
    "nagrania piosenek do wspólnego refrenu",
    "krzesełka ustawione w łuk, jak w prawdziwej orkiestrze"],
   ["Rozdaj instrumenty według koloru i posadź dzieci w łuk.",
    "Zaśpiewajcie refren razem, zanim dojdą instrumenty.",
    "Prowadź batutą po partyturze — dzieci patrzą na planszę, nie na ciebie."],
   "Nasza orkiestra zaczyna grać. Popatrz na partyturę: kiedy zapali się twój kolor, grasz ty. Najpierw śpiewamy refren razem, potem gramy.",
   "Partytura z kolorami zastępuje ciągłe „teraz wy” — dzieci patrzą na planszę zamiast na nauczyciela i po raz pierwszy naprawdę grają razem."),

 "b8_39": ("B8-39", "Polecenie dla całej grupy",
   ["dzwonek albo umówione klaśnięcie — zawsze ten sam sygnał uwagi",
    "piktogramy najczęstszych poleceń dnia",
    "gra „Szymon mówi” w wersji polskiej, do ćwiczeń na wesoło",
    "tablica poleceń dnia z ruchomym wskaźnikiem",
    "stoper do mierzenia czasu reakcji grupy"],
   ["Zawsze najpierw sygnał uwagi, dopiero potem treść polecenia.",
    "Powiedz polecenie raz, do całej grupy, i pokaż odpowiedni piktogram.",
    "Nie powtarzaj indywidualnie; poczekaj i zmierz czas reakcji grupy."],
   "Słuchajcie, mam polecenie dla całej grupy. Kiedy usłyszysz dzwonek, to znaczy, że zaraz coś powiem. Powiem to raz, a wy wykonujecie.",
   "Stały sygnał uwagi przed poleceniem jest ważniejszy niż samo polecenie — dziecko nie ignoruje treści, tylko nie wie, że komunikat właśnie się zaczął."),

 "b9_40": ("B9-40", "Herb naszej grupy",
   ["duży karton na herb, podzielony na tyle pól, ile jest dzieci",
    "zdjęcia zwyczajów grupy: poranny krąg, urodziny, dyżury",
    "farby i materiały plastyczne",
    "hymn albo piosenka grupy",
    "tabliczka z nazwą grupy do zawieszenia pod herbem"],
   ["Obejrzyjcie zdjęcia zwyczajów i nazwijcie, co u nas zawsze się dzieje.",
    "Każde dziecko maluje w herbie swoje własne pole.",
    "Powieście herb z tabliczką i nauczcie się piosenki grupy."],
   "Robimy herb naszej grupy. Każde dziecko maluje w nim swój własny kawałek. Powiedz mi, jak nazywa się nasza grupa i co u nas zawsze robimy.",
   "Herb tworzony wspólnie działa tylko wtedy, gdy każde dziecko namaluje w nim swój fragment — symbol nadany przez dorosłego pozostaje dekoracją."),

 "b9_41": ("B9-41", "Nasze przedstawienie",
   ["plan przedstawienia w obrazkach, z zaznaczoną kolejnością wejść",
    "stroje i rekwizyty na wieszaku, dostępne przed próbą",
    "tablica ról ze zdjęciami dzieci",
    "nagranie próby do wspólnego odsłuchania",
    "programy dla widzów przygotowane przez dzieci"],
   ["Pokaż plan i wskaż, które miejsce w kolejności zajmuje dziecko.",
    "Przećwiczcie rolę: jedno zdanie albo jeden ruch, nie więcej.",
    "Nagrajcie próbę i obejrzyjcie ją razem — bez twoich uwag."],
   "Przygotowujemy nasze przedstawienie. Popatrz na plan: twoja rola jest trzecia. Powiesz jedno zdanie. Nagramy próbę i posłuchamy jej razem.",
   "Nagranie próby jest najlepszym reżyserem — dziecko, które zobaczy siebie, poprawia głos i postawę bez jednej uwagi ze strony dorosłego."),

 "b9_42": ("B9-42", "Wyprawa czterech pór roku",
   ["sprzęt sezonowy: sanki, lupy, wiaderka, latawce",
    "lista obrazkowa sprzętu do sprawdzenia przed wyjściem",
    "karty zabaw sezonowych do wyboru przez dzieci",
    "worek na skarby przyrody",
    "aparat do dokumentowania wyprawy"],
   ["Przed wyjściem dzieci wybierają z kart zabawę na dziś.",
    "Sprawdzają listę obrazkową i pomagają spakować sprzęt.",
    "Na miejscu realizują wybraną zabawę i zbierają skarby do worka."],
   "Wychodzimy na naszą wyprawę. Wybierzcie z kart zabawę na dziś i sprawdźcie listę sprzętu. Pomóż mi spakować to, czego będziemy potrzebować.",
   "Pozwól dzieciom wybrać zabawę z kart przed wyjściem — grupa, która sama zaplanowała wyprawę, wychodzi szybciej i bawi się dłużej."),

 "b9_43": ("B9-43", "Widzowie i krytycy",
   ["karta zasad widza w czterech obrazkach",
    "bilety wstępu wręczane dzieciom przed wejściem na widownię",
    "karty opinii: podobało mi się i nie podobało mi się",
    "książka opinii grupy do wklejania kart",
    "zdjęcia z wydarzenia do rozmowy po występie"],
   ["Wręcz bilety i przejdźcie razem „wejście na widownię”.",
    "Przypomnij zasady z karty raz, zanim zacznie się występ.",
    "Po występie dziecko wybiera jedną z dwóch kart opinii i wkleja ją do książki."],
   "Weź swój bilet i wejdź na widownię. Oglądamy w ciszy do samego końca, a potem bijemy brawo. Po występie pokażesz mi, co ci się najbardziej podobało.",
   "Bilet w dłoni zmienia zachowanie widza — dziecko, które przeszło przez „wejście na widownię”, traktuje przedstawienie inaczej niż zajęcia w sali."),

 "b9_44": ("B9-44", "To ja — imię i nazwisko",
   ["wizytówki dzieci z imieniem i nazwiskiem",
    "pieczątki i stempelki do zabawy w biuro",
    "formularze i długopisy — biuro musi wyglądać jak biuro",
    "lustro z ramką i miejscem na podpis",
    "legitymacje przedszkolaka do wypełnienia"],
   ["Urządźcie biuro: formularze, pieczątka, stempel z datą.",
    "Dziecko przychodzi po legitymację i podaje imię oraz nazwisko.",
    "Wypełniasz formularz przy dziecku i wręczasz gotową legitymację."],
   "Witaj w naszym biurze. Żeby dostać legitymację, trzeba podać swoje imię i nazwisko. Powiedz mi je wyraźnie, a ja wypełnię formularz.",
   "Zabawa w biuro daje powód do podawania danych — bez realnego celu pytanie „jak się nazywasz?” brzmi jak sprawdzian, a nie jak rozmowa."),

}


ZESTAW = Zestaw(POMOCE, "pomoce_b", "audio_b", "5 lat", "Pomoce_dydaktyczne_5_lat.html")
