# -*- coding: utf-8 -*-
"""Pomoce dydaktyczne do konspektów uzupełniających — obszar techniczny i cyfrowy.

Wersja U powstała po to, żeby domknąć podstawę do 113/113, i długo nie miała
kart pomocy — konspekty niosły same arkusze do wydruku. Obszary techniczny (6)
i cyfrowy (7) najbardziej tego brakowało: to tam nauczyciel prowadzi
doświadczenie, którego nie da się opisać jednym zdaniem, i tam najczęściej
potrzebuje gotowego polecenia do dziecka.

Układ karty i osadzanie mediów: `pomoce_karta`. Ten moduł zna tylko treść.
"""

from pomoce_karta import Zestaw

# kod → (nr konspektu, tytuł, [co przygotować], [trzy kroki], polecenie, wskazówka)
POMOCE = {

 "u6_29": ("U6-29", "Pudełko materiałów",
   ["pudełko z pięcioma próbkami: gąbka, folia, tkanina, papier, drewno",
    "dwie miski z wodą i zakraplacz",
    "karta doświadczenia z kolumną na przewidywanie",
    "tacki, po jednej na dziecko",
    "ściereczki — woda ma prawo się rozlać"],
   ["Dziecko dotyka próbek i opisuje je własnymi słowami.",
    "Zaznacza na karcie, co przewiduje, zanim kropnie wodą.",
    "Kropi i porównuje wynik z własnym przewidywaniem."],
   "Dotknij każdej próbki i powiedz mi, jaka jest. Teraz zaznacz na karcie, która przepuści wodę — zaznacz, zanim sprawdzisz. Dopiero potem weź zakraplacz i przekonaj się, czy zgadłeś.",
   "Kolumna z przewidywaniem musi być wypełniona przed kropleniem. Dziecko, które zapisuje sam wynik, dowiaduje się, co się stało; dziecko, które zapisało przewidywanie, dowiaduje się, że się myliło — i to jest w tym doświadczeniu treść."),

 "u6_30": ("U6-30", "Jak powstaje dom",
   ["cztery obrazki etapów budowy, do ułożenia w kolejności",
    "próbki: cegła, drewno, szkło, beton",
    "klocki i taca z piaskiem",
    "zdjęcia budowy z okolicy, zrobione podczas spaceru",
    "tablica etapów"],
   ["Dziecko układa etapy budowy w kolejności, bez podpowiedzi.",
    "Dopasowuje próbkę materiału do etapu, w którym się pojawia.",
    "Buduje wieżę na luźnym piasku i sprawdza, co się dzieje."],
   "Ułóż obrazki tak, jak powstaje dom — od pierwszej rzeczy do ostatniej. Potem dopasuj materiały: co jest potrzebne na początku, a co na końcu. Na koniec zbuduj wieżę na piasku i zobacz, czy ustoi.",
   "Wieża na luźnym piasku ma się przewrócić i o to chodzi. Fundament opowiedziany nie znaczy nic; fundament, którego zabrakło, dziecko rozumie od razu."),

 "u6_31": ("U6-31", "Równia i kołowrót",
   ["dwie deski i klocki do ustawiania równi pod różnym kątem",
    "szpulki, sznurek i korba na kołowrót",
    "ciężarki i autka",
    "stoper",
    "zdjęcia urządzeń domowych z równią i kołowrotem"],
   ["Dziecko puszcza autko z równi i obserwuje zjazd.",
    "Zmienia kąt i porównuje, kiedy autko jedzie szybciej.",
    "Podnosi ciężarek ręką, potem kołowrotem, i ocenia różnicę."],
   "Puść autko z tej górki i popatrz, jak zjeżdża. Teraz podnieś deskę wyżej i puść jeszcze raz — powiedz mi, kiedy było szybciej. Na koniec spróbuj wciągnąć ciężarek ręką, a potem korbą.",
   "Różnicę między ręką a korbą dziecko musi poczuć, nie usłyszeć. Zestaw ciężarek tak, żeby ręką było naprawdę ciężko — lekki ciężarek psuje całe doświadczenie."),

 "u6_32": ("U6-32", "Zapal światło",
   ["baterie paluszki w koszyczku",
    "przewody z krokodylkami",
    "żarówka na podstawce i brzęczyk",
    "schemat obwodu w postaci rysunku, nie opisu",
    "taca, na której obwód zostaje między zajęciami"],
   ["Dziecko nazywa elementy i ogląda schemat rysunkowy.",
    "Domyka obwód ostatnim przewodem podanym przez Panią.",
    "Składa cały obwód samodzielnie, według schematu."],
   "Popatrz na schemat i nazwij części: bateria, przewód, żarówka. Teraz podam ci ostatni przewód — podłącz go i zobacz, co się stanie. Potem złóż wszystko sam, od początku, patrząc na rysunek.",
   "Pierwsze domknięcie obwodu zostawiamy dziecku, nawet jeśli trwa długo. Obwód złożony przez dorosłego świeci tak samo, a dziecko nie wie, dlaczego."),

 "u6_33": ("U6-33", "Skąd bierze się energia",
   ["latarka na baterie i lampka na kabel",
    "kalkulator solarny",
    "trzepaczka ręczna i młynek",
    "tablica z czterema polami źródeł zasilania",
    "prawdziwa bateria wyjęta z latarki"],
   ["Dziecko uruchamia urządzenia i sprawdza, co je zasila.",
    "Kładzie każde urządzenie pod właściwym polem tablicy.",
    "Zasłania panel kalkulatora dłonią i obserwuje, co się dzieje."],
   "Spróbuj włączyć każde z tych urządzeń i powiedz mi, skąd bierze siłę. Połóż je na tablicy pod właściwym znakiem. A teraz zasłoń dłonią to okienko na kalkulatorze — popatrz, co się stało.",
   "Kalkulator solarny jest tu najważniejszy: to jedyne urządzenie, przy którym dziecko widzi, że zasilanie znika i wraca. Bateria wyjęta z latarki działa podobnie — pokaż ją, nie opowiadaj o niej."),

 "u6_34": ("U6-34", "Regulamin warsztatu",
   ["regulamin obrazkowy, ustalony wspólnie z dziećmi",
    "opaska kontrolera bezpieczeństwa",
    "narzędzia dziecięce",
    "zaślepki do gniazdek",
    "karta odprawy przed pracą"],
   ["Dzieci czytają obrazki regulaminu i nazywają zasady.",
    "Wyznaczony kontroler zakłada opaskę i obchodzi stanowiska.",
    "Odprawa przed pracą: sprawdzamy narzędzia, kable, przestrzeń."],
   "Popatrz na regulamin i powiedz mi zasady swoimi słowami. Dziś ty jesteś kontrolerem bezpieczeństwa — załóż opaskę i sprawdź stanowiska. Powiedz, czy tu jest bezpiecznie, zanim zaczniemy pracę.",
   "Kontrolerem jest dziecko, nie Pani. Zasada sprawdzona przez kolegę wraca potem sama; zasada wyegzekwowana przez dorosłego działa tylko, gdy dorosły patrzy."),

 "u6_35": ("U6-35", "Co robi to za nas",
   ["trzepaczka ręczna i mikser",
    "tarka i młynek",
    "stoper",
    "karty urządzeń",
    "tablica z dwiema kolumnami: ręcznie i urządzeniem"],
   ["Dziecko wykonuje to samo zadanie ręką, z pomiarem czasu.",
    "Powtarza je urządzeniem, znowu ze stoperem.",
    "Porównuje oba czasy zapisane na tablicy."],
   "Ubij to najpierw trzepaczką — mierzę czas. Teraz to samo mikserem, znowu z zegarem. Popatrz na tablicę i powiedz mi, o ile szybciej poszło z urządzeniem.",
   "Liczba sekund robi tu całą pracę. Zdanie „maszyna jest szybsza” dziecko przyjmuje i zapomina; zmierzone czterdzieści sekund różnicy zostaje."),

 "u6_36": ("U6-36", "Spacer komunikacyjny",
   ["kamizelki odblaskowe",
    "karta spaceru z piktogramami do zaznaczania po drodze",
    "znaki drogowe zabawkowe",
    "makieta skrzyżowania w sali",
    "zdjęcia przystanku i przejścia"],
   ["Dziecko przeprowadza pionek przez przejście na makiecie.",
    "Na spacerze nazywa mijane środki transportu i zaznacza je na karcie.",
    "Przed przejściem mówi zasadę na głos, zanim ruszy."],
   "Najpierw przeprowadź pionek przez przejście na makiecie i powiedz, gdzie się zatrzymuje. Na spacerze zaznaczaj na karcie to, co zobaczysz. Zanim wejdziemy na przejście, powiedz mi zasadę: zatrzymuję się, patrzę w lewo, w prawo, słucham.",
   "Karta wypełniana w trakcie spaceru, nie po powrocie. Uzupełniona w sali zbiera to, co dziecko wiedziało wcześniej, a nie to, co dzisiaj zobaczyło."),

 "u6_37": ("U6-37", "Dziesięć dni z zabawką",
   ["skrzynia materiałów z odzysku: pudełka, rolki, korki, nakrętki",
    "karta projektu z dziesięcioma polami",
    "półka projektowa, na której praca zostaje między dniami",
    "taśma, sznurek, klej",
    "aparat do zdjęć kolejnych etapów"],
   ["Dziecko wymyśla zabawkę i rysuje plan w pierwszym polu karty.",
    "Codziennie wraca do pracy i zaznacza kolejny dzień.",
    "Po dziesięciu dniach pokazuje zabawkę i opowiada, co zmieniało."],
   "Popatrz, co jest w skrzyni, i wymyśl zabawkę, którą z tego zrobisz. Narysuj plan w pierwszym polu karty. Będziesz do niej wracać przez dziesięć dni — nie sprzątamy jej, zostaje na półce.",
   "Długość tego projektu jest jego treścią. Skrócony do jednego dnia przestaje uczyć wracania do zaczętej pracy, a to jedyna rzecz, której tu nie da się nauczyć inaczej."),

 "u6_38": ("U6-38", "Makieta naszej okolicy",
   ["duża płyta jako wspólna podstawa",
    "pudełka, rolki, korki, farby i papier",
    "zdjęcia okolicy zrobione przez dzieci na spacerze",
    "tabliczki z imionami przy fragmentach makiety",
    "plan makiety narysowany przed budowaniem"],
   ["Dziecko fotografuje na spacerze budynek, który wybrało.",
    "Wybiera swój fragment płyty i podpisuje go imieniem.",
    "Buduje swój budynek i ustawia go we właściwym miejscu."],
   "Na spacerze zrób zdjęcie budynku, który chcesz zbudować. Wybierz sobie kawałek płyty i podpisz go swoim imieniem. Teraz zbuduj swój budynek i postaw go tam, gdzie stoi naprawdę.",
   "Makieta budowana bez planu i bez zdjęć rozrasta się w losowe miasto. Zdjęcie zrobione przez dziecko jest tu warunkiem, żeby to była nasza okolica, a nie jakakolwiek."),

 "u7_39": ("U7-39", "Do czego to służy",
   ["prawdziwe urządzenia, choćby niedziałające: telefon, aparat, tablet, radio",
    "karty zadań: zrobić zdjęcie, zadzwonić, posłuchać",
    "tablica dopasowań",
    "zdjęcia urządzeń w użyciu",
    "koszyk, w którym urządzenia stoją dostępne"],
   ["Dziecko ogląda urządzenia i nazywa te, które zna.",
    "Mówi po jednym zastosowaniu każdego z nich.",
    "Do karty zadania dobiera właściwe urządzenie."],
   "Popatrz na te urządzenia i nazwij te, które znasz. Powiedz mi, do czego służy każde. A teraz pokażę ci kartę z zadaniem — wybierz urządzenie, którym się to zrobi, i połóż przy nim kartę.",
   "Urządzenia mają być prawdziwe, nawet zepsute. Dziecko, które trzyma aparat w ręku, rozumie, do czego służy; dziecko, które ogląda obrazek aparatu, uczy się obrazka."),

 "u7_40": ("U7-40", "Umowa ekranowa",
   ["klepsydra, widoczna dla dziecka przez cały czas",
    "plakat umowy ekranowej, podpisany przez dzieci",
    "karty czynności z ekranem i bez",
    "paski do układania planu dnia",
    "obrazek zmęczonych oczu"],
   ["Dziecko ogląda film i obserwuje przesypujący się piasek.",
    "Odkłada urządzenie na koniec klepsydry, bez przypominania.",
    "Wykonuje ćwiczenie na oczy i mówi, jak się czuje."],
   "Włączam film, a obok stawiam klepsydrę — możesz na nią zerkać. Kiedy piasek się przesypie, odkładasz urządzenie sam. Potem popatrzymy przez chwilę w okno i powiesz mi, jak się czują twoje oczy.",
   "Umowa obowiązuje też dorosłych w sali i to jest pierwsza rzecz, którą dzieci sprawdzają. Klepsydra musi być widoczna dla dziecka — odliczanie w głowie dorosłego niczego nie uczy."),

 "u7_41": ("U7-41", "Nie mówię obcym",
   ["pacynka nieznajomego",
    "karty informacji prywatnych: imię, adres, zdjęcie, przedszkole",
    "karta „mówię dorosłemu”",
    "tablica z dwiema kolumnami: mówię i nie mówię",
    "zdjęcia zaufanych dorosłych, wskazanych przez dziecko"],
   ["Pacynka pyta dziecko o adres; dziecko ćwiczy odmowę.",
    "Dziecko sortuje karty informacji na dwie kolumny.",
    "Wskazuje na zdjęciach dorosłego, do którego pójdzie."],
   "Ta pacynka będzie cię o coś pytać. Kiedy zapyta o adres, powiedz jej: nie powiem. Potem posortujemy karty — co możesz powiedzieć, a co jest tajemnicą — i pokażesz mi dorosłego, do którego idziesz.",
   "Ćwiczymy odmowę, nie wiedzę. Dziecko, które umie wyrecytować adres, ale nie ma przećwiczonego „nie powiem”, poda go pierwszej osobie pytającej pewnym głosem."),

 "u7_42": ("U7-42", "Reklama a prawda",
   ["gazetki reklamowe",
    "prawdziwe produkty z tych reklam, postawione obok",
    "lupa",
    "tablica z dwiema kolumnami: na obrazku i naprawdę",
    "waga i miarka"],
   ["Dziecko wskazuje w gazetce, co reklama zachęca kupić.",
    "Porównuje zdjęcie z prawdziwym produktem postawionym obok.",
    "Nazywa różnice: wielkość, kolor, ilość w opakowaniu."],
   "Popatrz na tę gazetkę i pokaż mi, co ona zachęca kupić. A teraz postawię obok prawdziwy produkt — porównaj go ze zdjęciem. Powiedz mi, co się zgadza, a co wygląda inaczej.",
   "Prawdziwy produkt musi stać obok gazetki. Rozmowa o reklamie bez rzeczy do porównania kończy się na tym, że dziecko powtarza zdanie dorosłego o reklamach."),
}

ZESTAW = Zestaw(POMOCE, "pomoce_u", "audio_u", "uzupełnienia",
                "Pomoce_dydaktyczne_uzupelnienia.html")
