# -*- coding: utf-8 -*-
"""Pomoce dydaktyczne do konspektów wersji A (3–4 lata).

Każda pomoc to jedna karta A4 dla nauczyciela: zdjęcie poglądowe „tak ma to
wyglądać", lista rzeczy do przygotowania, trzy kroki użycia i — tam, gdzie
konspekt tego potrzebuje — nagrane polecenie dla dziecka głosem nauczycielki.

Zdjęcia są ilustracjami poglądowymi, nie fotografiami konkretnych produktów:
pokazują układ i charakter pomocy, żeby nauczyciel wiedział, co skompletować.

Ten moduł trzyma tylko treść; układ karty i osadzanie mediów są w
`pomoce_karta`. Rejestr POMOCE jest kluczowany numerem konspektu, a build.py
dołącza kartę do modalu tego konspektu.
"""

from pomoce_karta import Zestaw

# kod → (nr konspektu, tytuł pomocy, [co przygotować], [trzy kroki], tekst nagrania, wskazówka)
POMOCE = {
 "d1_01": ("D1-01", "Czarodziejski woreczek",
   ["błyszczący woreczek ze sznurkiem ściągającym, nieprzezroczysty",
    "5 drobiazgów o wyraźnie różnej fakturze: szyszka, pompon, gładki koralik, tektura falista, muszla",
    "mały dzwoneczek — sygnał otwarcia woreczka",
    "płaska taca, na której leżą przedmioty przed schowaniem"],
   ["Pokaż dziecku wszystkie przedmioty na tacy i nazwij każdy razem z nim.",
    "Schowaj jeden do woreczka przy dziecku, zadzwoń dzwoneczkiem.",
    "Dziecko wkłada rączkę i zgaduje po dotyku, zanim zajrzy."],
   "Mam tu czarodziejski woreczek. Włóż do niego rączkę i poszukaj czegoś w środku. Nie zaglądaj — najpierw sprawdź paluszkami, co to jest.",
   "Faktury muszą się wyraźnie różnić. Dwa gładkie przedmioty w jednym woreczku to dla trzylatka zagadka nie do rozwiązania."),

 "d1_02": ("D1-02", "Małpka robi to, co ja",
   ["pacynka-małpka na rękę, z wyraźną buzią",
    "bębenek albo tamburyn do wystukiwania rytmu",
    "arkusz naklejek z łapką małpki — do oznaczania udanych prób",
    "lustro w sali, żeby dziecko widziało swój ruch"],
   ["Załóż pacynkę i wykonaj nią jeden prosty ruch: klaśnięcie, tupnięcie.",
    "Poproś dziecko, żeby zrobiło to samo — najpierw razem z tobą.",
    "Za każdą udaną próbę dziecko przykleja sobie łapkę małpki."],
   "To jest małpka. Małpka bardzo lubi, kiedy ktoś robi tak samo jak ona. Popatrz na nią uważnie i zrób to samo.",
   "Pacynka działa lepiej niż polecenie wprost — dziecko naśladuje zabawkę chętniej niż dorosłego i nie czuje się oceniane."),

 "d1_03": ("D1-03", "Klepsydra skarbów",
   ["klepsydra dwuminutowa, najlepiej z kolorowym piaskiem",
    "drewniane pudełko na „skarb dnia” z zamykaną pokrywką",
    "żetony w kształcie diamentów — po jednym za każde przeczekane odwrócenie",
    "parawan albo kącik za regałem, gdzie skarb czeka niewidoczny"],
   ["Pokaż skarb, schowaj go do pudełka i odwróć klepsydrę.",
    "Bawcie się czymś innym, dopóki piasek się nie przesypie.",
    "Po przesypaniu otwórzcie pudełko razem i dodajcie żeton."],
   "Odwracam klepsydrę. Kiedy piasek przesypie się na dół, otworzymy pudełko ze skarbem. A my w tym czasie się pobawimy.",
   "Klepsydra musi być widoczna przez cały czas. Czekanie z sygnałem, który widać, jest dla trzylatka zupełnie inną sytuacją niż czekanie w ciemno."),

 "d1_04": ("D1-04", "Kolorowe domki",
   ["dwa kartonowe domki z wyraźnie różnymi dachami — żółtym i zielonym",
    "klocki dokładnie w tych dwóch kolorach, po 4–5 sztuk",
    "dwa pluszaki w tych samych kolorach — mieszkańcy domków",
    "lniany woreczek do losowania klocków"],
   ["Przedstaw mieszkańców: żółtego i zielonego misia w swoich domkach.",
    "Dziecko losuje klocek z woreczka i niesie go do właściwego domku.",
    "Na koniec razem sprawdźcie, czy każdy klocek trafił do siebie."],
   "Zobacz, mamy dwa domki. W żółtym domku mieszkają żółte rzeczy, a w zielonym zielone. Zanieś klocek do jego domku.",
   "Zacznij od dwóch kolorów, nie od czterech. Trzeci kolor dodaj dopiero wtedy, gdy sortowanie na dwa idzie bez zastanowienia."),

 "d1_05": ("D1-05", "Pudełko z niespodzianką",
   ["cztery pojemniki o różnych zamknięciach: pokrywka, zamek błyskawiczny, zakrętka, kokardka",
    "drobne niespodzianki do środka — po jednej na pojemnik",
    "karta „próbowałem sam” z czterema polami na naklejki",
    "mata antypoślizgowa, żeby pojemnik nie uciekał"],
   ["Ustaw pojemniki w rzędzie, od najłatwiejszego do najtrudniejszego.",
    "Dziecko otwiera po kolei — pomagaj dopiero po jego trzeciej próbie.",
    "Za każdy otwarty samodzielnie pojemnik naklejka na kartę."],
   "W każdym pudełku czeka niespodzianka. Ale każde otwiera się inaczej. Spróbuj sam, a ja poczekam.",
   "Odczekaj trzy próby, zanim pomożesz. To najtrudniejsza część tych zajęć — dla dorosłego, nie dla dziecka."),

 "d2_06": ("D2-06", "Zaproszenie od misia",
   ["pacynka-miś, która „zaprasza” do zabawy",
    "karty-zaproszenia ze zdjęciem konkretnej zabawy z sali",
    "dwa stoliki z gotowymi zestawami, żeby zaproszenie od razu dało się przyjąć",
    "koszyk na wykorzystane zaproszenia"],
   ["Miś podchodzi do dziecka i wręcza kartę ze zdjęciem zabawy.",
    "Dziecko ogląda zdjęcie i idzie do stolika, który na nim widzi.",
    "Po zabawie wrzuca zaproszenie do koszyka — zabawa ma domknięcie."],
   "Miś ma dla ciebie zaproszenie. Zobacz, co jest na obrazku. Chodź, pobawimy się w to razem.",
   "Zdjęcie na karcie musi pokazywać zestaw dokładnie tak, jak stoi na stoliku. Rysunek albo inne ujęcie i trzylatek nie rozpozna, o co chodzi."),

 "d2_07": ("D2-07", "Dwa kroki do końca",
   ["paski z planem obrazkowym — dwa albo trzy okienka, nie więcej",
    "klipsy albo żetony do odhaczania zrobionych kroków",
    "zadania trzyetapowe: nawlekanie, przesypywanie, prosta układanka",
    "pudełko „skończone” z otwieranym wiekiem"],
   ["Pokaż pasek i nazwij razem z dzieckiem, co jest pierwsze.",
    "Po każdym kroku dziecko przypina klips na okienku.",
    "Gotową pracę wkłada do pudełka „skończone”."],
   "Popatrz na nasz plan. Najpierw robimy to, a potem to. Kiedy skończysz, odkładamy pracę do pudełka.",
   "Pudełko „skończone” jest ważniejsze, niż wygląda. Trzylatek potrzebuje fizycznego znaku, że praca się zamknęła — inaczej wraca do niej albo nie może odejść."),

 "d2_08": ("D2-08", "Pociąg dnia",
   ["plan dnia w kształcie pociągu, zawieszony na wysokości wzroku dziecka",
    "zdjęcia aktywności w okienkach wagonów — z waszej sali, nie z internetu",
    "magnetyczna lokomotywka pokazująca, gdzie jesteśmy teraz",
    "dzwonek albo grzechotka jako sygnał zmiany",
    "klepsydra minutowa — „ostatnia chwila” przed przejściem"],
   ["Rano przejdźcie pociąg od początku i nazwijcie wagony.",
    "Przy każdej zmianie przesuń lokomotywkę i zadzwoń.",
    "Minutę przed zmianą odwróć klepsydrę i uprzedź."],
   "Nasz pociąg jedzie przez cały dzień. Teraz jesteśmy tutaj, a zaraz pojedziemy dalej. Zobacz, co będzie następne.",
   "Zdjęcia muszą być z waszej sali. Dziecko rozpoznaje swoje miejsce i swoje zabawki, nie ilustrację przedszkola w ogóle."),

 "d2_09": ("D2-09", "Nasze trzy zasady",
   ["trzy piktogramy zasad na tablicy — dokładnie trzy, nie więcej",
    "gest przypisany każdej zasadzie, ten sam za każdym razem",
    "pacynka „Zapominalski”, która zasady łamie",
    "zielone żetony „udało się”",
    "zdjęcia dzieci z grupy przestrzegających zasad"],
   ["Wprowadź zasady po jednej, każdą z własnym gestem.",
    "Pacynka łamie zasadę — dzieci ją poprawiają i pokazują gest.",
    "Za przestrzeganie w ciągu dnia dziecko dostaje zielony żeton."],
   "Mamy w sali trzy zasady. Popatrz na obrazki i pokaż je razem ze mną. Kiedy ci się uda, dostajesz zielony żeton.",
   "Niech to pacynka łamie zasady, nie dziecko. Poprawianie Zapominalskiego uczy tego samego, ale bez wstydu."),

 "d2_10": ("D2-10", "Wyspa spokoju",
   ["stały kącik z poduszką i kocem — zawsze w tym samym miejscu",
    "dwa, trzy przedmioty kojące: gniotek, butelka sensoryczna",
    "karta z obrazkiem „idę na wyspę”, dostępna dla dziecka",
    "piktogram oddechu: wąchamy kwiatek, dmuchamy świeczkę"],
   ["Pokaż wyspę, gdy dziecko jest spokojne — nie w środku kryzysu.",
    "W trudnej chwili nazwij emocję i zaproponuj wyspę, nie każ.",
    "Usiądź obok i oddychajcie razem według piktogramu."],
   "Widzę, że jest ci teraz trudno. Chodź ze mną na wyspę spokoju. Powąchamy kwiatek i zdmuchniemy świeczkę. Poczekam z tobą.",
   "Wyspa nigdy nie może być karą ani miejscem zsyłki. W chwili, w której stanie się „idź się uspokoić”, przestaje działać."),

 "d3_11": ("D3-11", "Zrób to, o co proszę",
   ["cztery przedmioty codzienne: kubek, łyżka, miś, klocek",
    "koszyk „skrzynia zadań”",
    "obrazki trzech czynności: weź, połóż, daj",
    "pacynka, która czasem wydaje polecenia zamiast dorosłego"],
   ["Nazwij przedmioty razem z dzieckiem, zanim zaczniesz prosić.",
    "Wydaj jedno krótkie polecenie i poczekaj bez powtarzania.",
    "Podziękuj konkretnie: „podałeś mi misia, dziękuję”."],
   "Mam prośbę. Podaj mi proszę misia. Dziękuję, bardzo mi pomogłeś.",
   "Nie powtarzaj polecenia od razu. Trzylatek potrzebuje kilku sekund na przetworzenie — powtórka zaczyna proces od nowa."),

 "d3_12": ("D3-12", "Powiem, czego chcę",
   ["tablica AAC czteropolowa: pić, jeść, toaleta, pomoc",
    "brelok z tymi samymi symbolami — zawsze przy dziecku",
    "kubek, jabłko i symbol toalety jako konkrety obok tablicy",
    "zdjęcia sytuacji, w których symbole się przydają"],
   ["Powieś tablicę tam, gdzie potrzeba naprawdę powstaje: przy stole, przy drzwiach.",
    "Modeluj: sam pokazuj symbol, mówiąc, czego chcesz.",
    "Na każde wskazanie reaguj natychmiast — symbol musi działać."],
   "Chcesz mi coś powiedzieć? Pokaż na tablicy, czego potrzebujesz. Już wiem. Zaraz to przyniosę.",
   "Reaguj na wskazanie zawsze, nawet gdy wiesz, że dziecko nie jest głodne. Symbol, który czasem nie działa, przestaje być używany."),

 "d3_13": ("D3-13", "Zdanie z obrazka",
   ["duże obrazki, na każdym jedna wyraźna czynność",
    "paski do układania zdania — trzy pola: kto, co robi, gdzie",
    "pacynka „ciekawska”, która dopytuje",
    "telefon albo dyktafon do nagrania próbki mowy"],
   ["Pokaż obrazek i zapytaj najpierw: kto tu jest?",
    "Dołóż drugie pytanie: co robi? Ułóż odpowiedzi na paskach.",
    "Poproś o całe zdanie i nagraj je — nagranie pokazuje postęp."],
   "Popatrz na obrazek. Kto tu jest i co robi? Powiedz mi całym zdaniem.",
   "Nagrywaj co dwa tygodnie to samo zdanie. Postępu w mowie nie widać z dnia na dzień, ale w nagraniach sprzed miesiąca słychać go wyraźnie."),

 "d3_14": ("D3-14", "Kto? Co? Gdzie?",
   ["kostka z trzema symbolami pytań: postać, przedmiot, domek",
    "ilustracje sytuacyjne z kilkoma postaciami i przedmiotami",
    "zdjęcia dzieci z grupy i zdjęcia sali",
    "pacynka zadająca pytania zamiast dorosłego"],
   ["Rzuć kostką i nazwij, jakie pytanie wypadło.",
    "Dziecko szuka odpowiedzi na ilustracji i pokazuje palcem.",
    "Dopiero potem poproś o słowo — najpierw wskazanie, potem nazwa."],
   "Rzucamy kostką. Wypadło pytanie: kto tu jest? Poszukaj na obrazku i mi pokaż.",
   "Zaczynaj od zdjęć waszej grupy. „Kto to?” przy znajomej twarzy jest pytaniem o wiele łatwiejszym niż przy obcej ilustracji."),

 "d3_15": ("D3-15", "Twarze i gesty",
   ["cztery duże karty z wyrazistymi minami: wesoła, smutna, zdziwiona, spokojna",
    "dwie karty z gestami: dłoń „stop” i gest „chodź”",
    "lusterko, w którym dziecko widzi własną minę",
    "zdjęcia sytuacji z sali pasujących do każdej miny"],
   ["Pokaż kartę i nazwij minę, potem zrób ją razem z dzieckiem.",
    "Dziecko szuka tej samej miny u siebie w lusterku.",
    "Połącz minę z sytuacją: „kiedy tak wyglądasz, to znaczy, że…”."],
   "Popatrz na te buzie. Ta jest wesoła, a ta smutna. Pokaż mi wesołą buzię w lusterku.",
   "Zacznij od dwóch min, nie od czterech. Wesoła i smutna muszą być pewne, zanim dojdzie zdziwienie."),

 "d4_16": ("D4-16", "Ścieżka leśnych zwierząt",
   ["cztery niskie pachołki, dwa woreczki i niska ławeczka",
    "ślady zwierząt wycięte z filcu — stopki i łapki, przyklejone do podłogi",
    "opaski z uszami zwierząt: zając, miś, lis",
    "bębenek do sygnału start i stop"],
   ["Przejdź trasę pierwszy, nazywając, jakie zwierzę teraz idziemy.",
    "Dziecko idzie po śladach, naśladując ruch zwierzęcia.",
    "Na dźwięk bębenka wszyscy zastygają w bezruchu."],
   "Dziś idziemy leśną ścieżką. Popatrz na ślady na podłodze i idź po nich. Kiedy usłyszysz bębenek, zatrzymujemy się.",
   "Ślady muszą trzymać się podłogi. Kartka, która ucieka spod stopy, zamienia ćwiczenie równowagi w naukę upadania."),

 "d4_17": ("D4-17", "Schodki do chmurki",
   ["naklejki-stópki na stopniach, wyraźnie lewa i prawa",
    "poręcz na wysokości dziecka, nie dorosłego",
    "chmurka z filcu na ścianie u szczytu schodów — widoczny cel",
    "rymowanka „raz stopień, dwa stopień” powtarzana za każdym razem"],
   ["Stań obok dziecka od strony bez poręczy.",
    "Rytmizuj wejście rymowanką — rytm porządkuje ruch.",
    "Na górze dotknijcie chmurki: wejście ma domknięcie."],
   "Wchodzimy po schodkach do chmurki. Stawiaj stopę na naklejce, trzymając się poręczy. Raz stopień, dwa stopień.",
   "Nie trzymaj dziecka za rękę od strony poręczy. Ma się uczyć trzymać poręczy, nie ciebie."),

 "d4_18": ("D4-18", "Piłka wędrowniczka",
   ["duża lekka piłka i mniejsza piłka sensoryczna",
    "szeroki kosz i płaska obręcz jako cele",
    "taśma na podłodze wyznaczająca linię rzutu",
    "trzy kolorowe znaczniki w rosnących odległościach"],
   ["Zacznij od najbliższego znacznika i szerokiego kosza.",
    "Po trafieniu przesuń się o jeden znacznik dalej.",
    "Chybienie kwitujcie spokojnie: „poszła obok, rzucamy jeszcze raz”."],
   "Nasza piłka jest wędrowniczką. Stań na linii i rzuć ją do kosza. Nie szkodzi, jeśli nie trafi. Spróbujemy jeszcze raz.",
   "Cel ma być tak duży, żeby trafienie było prawdopodobne. Radość z celowania buduje się na trafieniach, nie na próbach."),

 "d4_19": ("D4-19", "Wieża i korale",
   ["duże drewniane klocki, lekkie i stabilne",
    "sztywna żyłka albo sznurowadło z twardą końcówką",
    "duże koraliki i makarony rurki",
    "prosty sorter kształtów",
    "mata antypoślizgowa pod pracą"],
   ["Zacznij od wieży z trzech klocków — sukces ma przyjść szybko.",
    "Przy nawlekaniu podaj sznurowadło z twardą końcówką, nie miękką nitkę.",
    "Skończ sorterem: to zadanie z jasnym końcem."],
   "Zbudujemy wieżę. Kładź klocek na klocku, powoli, żeby się nie przewróciła. A potem nawleczemy korale na sznurek.",
   "Sznurowadło z twardą końcówką robi całą różnicę. Miękka nitka zniechęca w dziesięć sekund."),

 "d4_20": ("D4-20", "Muzyczne pociągi",
   ["nagrania kilku znanych piosenek",
    "instrumenty perkusyjne: marakasy, bębenek, kołatki",
    "obręcze na podłodze wyznaczające miejsca w kole",
    "karty-obrazki z prostymi ruchami: klaśnięcie, tupnięcie, obrót"],
   ["Rozłóż obręcze — każde dziecko ma swoje miejsce.",
    "Muzyka gra: pociąg jedzie. Muzyka cichnie: stajemy w obręczy.",
    "Wylosuj kartę ruchu i wykonajcie go wszyscy razem."],
   "Kiedy gra muzyka, nasz pociąg jedzie. Kiedy muzyka cichnie, zatrzymujemy się w obręczy. Słuchaj uważnie.",
   "Obręcz na podłodze rozwiązuje spór o miejsce, zanim się zacznie. Bez niej połowa zabawy schodzi na przepychanie."),

 "d5_21": ("D5-21", "Sygnał na czas",
   ["symbol toalety na karcie i na breloku przy dziecku",
    "nakładka na sedes i stabilny stopień",
    "plan obrazkowy trzech kroków: siusiu, spłuczka, ręce",
    "tabela z uśmieszkami — znak, nie nagroda"],
   ["Wprowadź symbol, gdy dziecko jest spokojne, nie w pośpiechu.",
    "Reaguj na pokazanie symbolu natychmiast, bez komentarza.",
    "Po wszystkim razem przejdźcie plan trzech kroków."],
   "Pamiętasz nasz znak? Kiedy poczujesz, że chcesz siusiu, pokaż mi obrazek. Pójdziemy razem, spokojnie.",
   "Nigdy nie komentuj wpadki przy innych dzieciach. Jedno zawstydzenie cofa naukę o tygodnie."),

 "d5_22": ("D5-22", "Cztery kroki mycia",
   ["instrukcja obrazkowa nad umywalką, na wysokości oczu dziecka",
    "mydło w piance z dozownikiem — łatwiejsze niż kostka",
    "krótka piosenka jako minutnik pocierania",
    "ręczniki papierowe w zasięgu ręki, nie na półce dorosłego"],
   ["Przejdź cztery kroki razem, pokazując palcem na instrukcji.",
    "Pocierajcie ręce tak długo, jak trwa piosenka.",
    "Wycieranie też jest krokiem — nie kończcie na wodzie."],
   "Myjemy rączki w czterech krokach. Woda, mydło, pocieramy, wycieramy. Pocieramy tak długo, jak trwa nasza piosenka.",
   "Piosenka zastępuje odliczanie i działa lepiej. Trzylatek nie ma pojęcia, ile trwa trzydzieści sekund, ale wie, kiedy piosenka się kończy."),

 "d5_23": ("D5-23", "Łyżka i kubek",
   ["miska z wysokim, zagiętym brzegiem — jedzenie samo wraca na łyżkę",
    "łyżka z pogrubioną rączką",
    "kubek szeroki u podstawy, trudny do przewrócenia",
    "mata antypoślizgowa pod miską",
    "śliniak albo fartuszek — bałagan jest wliczony"],
   ["Usiądź obok, nie naprzeciw — łatwiej pokazać ruch.",
    "Podaj łyżkę do dłoni dziecka i pozwól nabrać samodzielnie.",
    "Rozlanie kwituj spokojnie i wytrzyjcie razem."],
   "Trzymamy łyżkę w rączce. Nabieramy powoli i niesiemy do buzi. Jak coś spadnie, to nic. Wytrzemy razem.",
   "Miska z zagiętym brzegiem to najważniejszy element zestawu. Bez niej jedzenie ucieka z łyżki i dziecko się zniechęca."),

 "d5_24": ("D5-24", "Ubieram się sam",
   ["plan obrazkowy kolejności ubierania, pionowy, na ścianie",
    "ławeczka na wysokości dziecka",
    "naklejki lewy–prawy w butach: dwie połówki jednego obrazka",
    "lustro w szatni na wysokości dziecka"],
   ["Pokaż plan i nazwij pierwszą rzecz do wzięcia.",
    "Zostaw dziecku najłatwiejszy element do samodzielnego założenia.",
    "Buty sprawdzajcie po obrazku: całość znaczy dobrze."],
   "Ubieramy się po kolei. Popatrz na obrazki i weź to, co jest pierwsze. Ja poczekam, a ty spróbuj sam.",
   "Naklejki-połówki w butach uczą lewej i prawej bez tłumaczenia. Obrazek się zgadza albo nie — dziecko widzi to samo."),

 "d5_25": ("D5-25", "Mój termometr samopoczucia",
   ["tablica sygnałów: zmęczony, głodny, boli, chcę biegać",
    "kącik odpoczynku z poduszką, zawsze dostępny",
    "symbol „odpoczynek” na breloku przy dziecku",
    "zdjęcia dzieci z grupy w różnych stanach"],
   ["Pytaj o samopoczucie w spokojnych momentach, nie tylko przy kryzysie.",
    "Dziecko pokazuje sygnał na tablicy — słowo nie jest konieczne.",
    "Reaguj zgodnie z sygnałem, żeby tablica miała moc sprawczą."],
   "Jak się teraz czujesz? Pokaż mi na naszej tablicy. Jesteś zmęczony? To chodź, odpoczniemy chwilę.",
   "Cztery sygnały wystarczą. Rozbudowana tablica emocji jest dla starszych — trzylatek potrzebuje odróżnić głód od zmęczenia."),

 "d6_26": ("D6-26", "Sprzątanie z piosenką",
   ["trzy niskie pojemniki otwarte od góry, każdy w innym kolorze",
    "obrazek zawartości naklejony na froncie każdego pojemnika — klocki, autka, pluszaki",
    "zdjęcie wzorcowe posprzątanego kącika, oprawione i postawione na półce",
    "głośniczek z jedną, zawsze tą samą piosenką sprzątania (2 minuty)",
    "wiklinowy koszyk na „zgubki” zebrane z podłogi"],
   ["Włącz piosenkę i postaw obok dzieci zdjęcie wzorcowe kącika.",
    "Wskazuj obrazek na pojemniku, nie mów, gdzie co ma być: „klocki mieszkają tu”.",
    "Zanim piosenka ucichnie, porównajcie kącik ze zdjęciem i dołóżcie, czego brakuje."],
   "Sprzątamy razem, dopóki gra piosenka. Popatrz na obrazek na pudełku i włóż tam zabawkę. Zobacz, jak ładnie wygląda nasz kącik.",
   "Obrazek na froncie pojemnika musi pokazywać zawartość, nie kategorię. „Klocki” dziecko rozpozna po zdjęciu klocków, a nie po symbolu zabawki."),

 "d6_27": ("D6-27", "Każda rzecz ma swój dom",
   ["znaczek rozpoznawczy dziecka — ten sam symbol na półce, wieszaku i kubku",
    "niska półka na kapcie, dostępna bez wspinania się",
    "kubek na tacce, oznaczony tym samym znaczkiem",
    "tabliczka z trzema obrazkami: kapcie – kubek – worek"],
   ["Rano pokaż dziecku jego znaczek na półce i na kubku — ten sam.",
    "Wskaż tabliczkę i odczytaj kolejność: najpierw kapcie, potem kubek.",
    "Dziecko samo odkłada dwie rzeczy; ty czekasz, nie podajesz."],
   "Każda rzecz ma swój dom. Poszukaj swojego znaczka na półce. Tam mieszkają twoje kapcie.",
   "Ten sam znaczek na półce, wieszaku i kubku jest kluczem — jeśli miejsca oznaczone są różnie, dziecko uczy się trzech rzeczy zamiast jednej."),

 "d6_28": ("D6-28", "Mali pomocnicy",
   ["tablica dyżurów ze zdjęciami dzieci w okrągłych ramkach",
    "dwa fartuszki dyżurnego w rozmiarze dziecięcym",
    "drewniana taca z uchwytami po bokach",
    "plan obrazkowy dwóch kroków: serwetki → kubki",
    "serwetki i kubki przygotowane w zasięgu ręki dziecka"],
   ["Rano wskaż zdjęcie dyżurnego na tablicy i podaj fartuszek.",
    "Pokaż plan: najpierw serwetki, potem kubki — i zejdź z drogi.",
    "Podziękuj za konkret: „dzięki tobie każdy ma kubek”, nie poprawiaj po dziecku."],
   "Dziś ty jesteś dyżurnym. Załóż fartuszek i weź tacę. Najpierw serwetki, potem kubki.",
   "Dyżur musi być naprawdę potrzebny — dzieci natychmiast wyczuwają zadanie pozorne i tracą motywację, gdy dorosły poprawia wszystko po nich."),

 "d7_29": ("D7-29", "Latarnia uwagi",
   ["lampion na baterie, ciepłe światło, bezpieczny w dziecięcych rękach",
    "poduszki do siedzenia w kręgu, po jednej na dziecko",
    "mały dzwonek sygnałowy — otwiera i zamyka rundę",
    "karta rund z rzędem uśmieszków do zaznaczania kolejek"],
   ["Zadzwoń dzwonkiem i zapal lampion — to znak, że zaczyna się runda.",
    "Mówi tylko to dziecko, które trzyma lampion; reszta słucha.",
    "Po wypowiedzi dziecko podaje lampion dalej i zaznacza uśmieszek."],
   "Zapalamy naszą latarnię. Kiedy latarnia świeci, słuchamy tego, kto mówi. Zaraz będzie twoja kolej.",
   "Światełko zawsze wędruje razem z głosem — nie dopuszczaj, by mówiło dziecko bez lampionu, bo sygnał przestaje być czytelny."),

 "d7_30": ("D7-30", "Podaj misia",
   ["miś lub inna maskotka, którą dzieci już znają i lubią",
    "dziergany koc wyznaczający pole zabawy",
    "tablica podań z okrągłymi magnesami — jeden magnes za jedno podanie",
    "piosenka „podaj dalej”, którą można zatrzymać w dowolnym momencie"],
   ["Usiądźcie na kocu w kręgu i puść piosenkę; miś wędruje z rąk do rąk.",
    "Zatrzymaj muzykę — dziecko, które trzyma misia, przytula go i podaje dalej.",
    "Po każdej pełnej rundzie dziecko przykleja magnes na tablicy podań."],
   "Podajemy misia dookoła. Kiedy dostaniesz misia, przytul go i podaj dalej. Każdy go potrzyma.",
   "Przerwana piosenka działa lepiej niż polecenie „podaj” — cisza jest sygnałem, że ruch należy do dziecka."),

 "d7_31": ("D7-31", "Mostek do przedszkola",
   ["plan obrazkowy rytuału pożegnania — dokładnie trzy kroki, zawsze te same",
    "przedmiot przejściowy przyniesiony z domu, dostępny przez cały dzień",
    "zdjęcie rodziny powieszone w szatni na wysokości oczu dziecka",
    "koszyk „pierwsza zabawa” przy drzwiach — jedna atrakcyjna rzecz na wejście"],
   ["W szatni przejdźcie trzy kroki z planu: przytulenie, pomachanie, wejście.",
    "Rodzic wychodzi po trzecim kroku — bez wracania i bez przedłużania.",
    "Podaj dziecku koszyk z pierwszą zabawą, żeby miało dokąd wejść."],
   "Mama zaraz pójdzie do pracy. Przytulamy się, machamy przez okno i idziemy się bawić. Mama wróci po podwieczorku. Zawsze wraca.",
   "Rytuał chroni tylko wtedy, gdy jest identyczny każdego dnia — wydłużanie przytulania „na prośbę” wydłuża płacz, nie skraca go."),

 "d7_32": ("D7-32", "Lusterko emocji",
   ["lusterko dziecięce w miękkiej, zaokrąglonej oprawie",
    "dwie duże karty emocji: radość i złość, grube kontury, bez detali",
    "pacynka „Zły-Wesoły Zajączek” z odwracaną buzią",
    "naklejki z buźkami do zaznaczania rozpoznanych emocji"],
   ["Poczekaj, aż emocja pojawi się naprawdę — nie ćwicz min na zapas.",
    "Podaj lusterko i nazwij to, co widać: „to jest złość”.",
    "Dobierzcie kartę pasującą do miny, a potem pokaż, jak złość odchodzi."],
   "Popatrz w lusterko. Widzisz, jaką masz teraz minę? To jest złość. Złość wolno czuć. Zaraz jej pomożemy odejść.",
   "Nazywaj emocję dopiero, gdy mina już jest — słowo doklejone do własnej twarzy dziecka utrwala się szybciej niż słowo z karty."),

 "d7_33": ("D7-33", "Czarodziejskie słowo POMOC",
   ["karta POMOC z jednym symbolem otwartej dłoni, bez napisu",
    "pudełko z celowo twardym zamknięciem",
    "zakręcona butelka z ulubioną naklejką widoczną w środku",
    "gest „pomoc” — dłoń położona na dłoni, ten sam za każdym razem"],
   ["Podaj dziecku pudełko, którego samo nie otworzy, i bądź obok.",
    "Gdy pojawi się frustracja, pokaż kartę i gest, a potem powiedz słowo.",
    "Reaguj natychmiast — otwórzcie pudełko razem, zaraz po sygnale."],
   "To pudełko trudno otworzyć. Kiedy nie dajesz rady, powiedz: pomocy. Powiedziałeś i już jestem. Zrobimy to razem.",
   "Prośba musi być tańsza niż płacz: reaguj na sygnał „pomoc” szybciej i cieplej niż na jakikolwiek inny sposób wołania."),


 "d8_34": ("D8-34", "Moje miejsce w grupie",
   ["zdjęcie dziecka w okrągłej ramce, przypięte do jego stałego miejsca",
    "plan dnia w obrazkach, powieszony na wysokości wzroku dziecka",
    "album ze zdjęciami sali, łazienki, leżakowni i nauczycielek",
    "pudełko „mój skarb z domu”, dostępne przez cały dzień"],
   ["Rano zaprowadź dziecko na jego miejsce i pokaż jego zdjęcie.",
    "Przy każdej zmianie wskaż na planie, co się teraz dzieje.",
    "Gdy dziecko się wycofuje, otwórzcie razem pudełko ze skarbem."],
   "To jest twoje miejsce. Popatrz na plan i zobacz, co robimy teraz. Jestem tutaj z tobą.",
   "Stałe miejsce jest ważniejsze niż ładne miejsce. Nie przestawiaj krzesełka dziecka w adaptacji, nawet gdy układ sali się zmienia."),

 "d8_35": ("D8-35", "Kącik lalek i garaż",
   ["atrybuty ról podane wprost: chusta, czapka, kierownica, torebka",
    "lalka z wózkiem, naczynia, trzy samochody",
    "dwa kąciki tematyczne wyraźnie oddzielone — dywanikiem albo regałem",
    "zdjęcia ról powieszone na ścianie każdego kącika"],
   ["Zaproponuj rolę konkretnie: „bądź kierowcą”, nie „pobaw się”.",
    "Podaj atrybut do ręki — czapkę albo kierownicę — i wejdź w rolę obok.",
    "Podtrzymuj zabawę pytaniem z wewnątrz roli: „dokąd jedziemy?”."],
   "Dziś ty jesteś kierowcą. Załóż czapkę i weź kierownicę. Powiedz mi, dokąd jedziemy.",
   "Atrybut robi rolę. Trzylatek, który dostał kierownicę, jest kierowcą od razu; ten, któremu tylko powiedziano, kim jest, wychodzi z roli po minucie."),

 "d8_36": ("D8-36", "Dywanik zajęć",
   ["poduszki ze znaczkami dzieci, zawsze na tych samych miejscach",
    "plan zajęcia z trzech obrazków: piosenka → zadanie → oklaski",
    "pacynka, która prowadzi zajęcie zamiast dorosłego",
    "pudełko z materiałami do zadań, otwierane dopiero w swoim kroku"],
   ["Zaproś na dywan i pomóż znaleźć poduszkę ze swoim znaczkiem.",
    "Pokaż plan trzech kroków i odsłaniaj je po kolei.",
    "Zamknij zajęcie oklaskami — dzieci wiedzą wtedy, że wolno wstać."],
   "Siadamy na swoich poduszkach. Popatrz na plan: najpierw piosenka, potem zadanie. Zostajemy razem na dywanie do końca.",
   "Dziesięć minut to górna granica dla trzylatka. Lepiej skończyć zajęcie o minutę za wcześnie niż o minutę za późno — wtedy dziecko wraca na dywan chętnie."),

 "d8_37": ("D8-37", "Budowniczowie",
   ["klocki różnej wielkości i faktury — drewniane, plastikowe, tekturowe",
    "materiały wtórne: rolki, pudełka, kubeczki papierowe",
    "dwa zdjęcia gotowych budowli jako inspiracja, nie jako wzór do skopiowania",
    "pusta tabliczka z klipsem do „podpisania” budowli"],
   ["Rozłóż dwa rodzaje materiału i pozwól dziecku wybrać samodzielnie.",
    "Nie buduj za dziecko; buduj obok, własną konstrukcję.",
    "Na koniec zapytaj, co powstało, i postaw tabliczkę przy budowli."],
   "Wybierz, z czego chcesz budować. Możesz wziąć klocki, rolki albo pudełka. Potem opowiesz mi, co zbudowałeś.",
   "Wybór materiału jest częścią celu. Podanie dziecku gotowego zestawu klocków zamienia inicjowanie zabawy w wykonywanie polecenia."),

 "d8_38": ("D8-38", "Bawimy się razem",
   ["chusta animacyjna z uchwytami na brzegu",
    "obrazek zasady zabawy — jeden, duży, widoczny z każdego miejsca",
    "znaczniki miejsc w kole, po jednym na dziecko",
    "tamburyn albo kołatka do sygnałów startu i końca"],
   ["Ustaw dzieci na znacznikach i pokaż obrazek zasady — raz.",
    "Prowadź zabawę sygnałem instrumentu, nie głosem.",
    "Zakończ wyraźnym sygnałem i wspólnym złożeniem chusty."],
   "Bierzemy chustę w rączki. Kiedy usłyszysz dzwonek, podnosimy ją wysoko do góry. Bawimy się razem do końca.",
   "Jedna zasada na zabawę. Druga dodana „przy okazji” sprawia, że dziecko przestaje trzymać się obu."),

 "d9_39": ("D9-39", "Nasze święto",
   ["plan obrazkowy uroczystości: piosenka → laurka → poczęstunek",
    "laurki przygotowane wcześniej przez dzieci",
    "korona urodzinowa dla solenizanta",
    "piosenka „Sto lat” z ustalonymi gestami",
    "słuchawki wygłuszające dostępne dla dzieci wrażliwych na hałas"],
   ["Dzień wcześniej przejdźcie plan uroczystości obrazek po obrazku.",
    "Przydziel dziecku jeden konkretny element — laurkę albo refren.",
    "Zostaw słuchawki w zasięgu i pozwól z nich skorzystać bez pytania."],
   "Dziś mamy w grupie święto. Popatrz na plan: najpierw piosenka, potem laurka. Podaj laurkę i powiedz: wszystkiego najlepszego.",
   "Uroczystość jest głośna i nieprzewidywalna — dlatego jeden ustalony wcześniej element daje dziecku miejsce, w którym wie, co robić."),

 "d9_40": ("D9-40", "Idziemy w parze",
   ["kolorowe kamizelki odblaskowe w rozmiarze dziecięcym",
    "linka spacerowa z uchwytami rozmieszczonymi parami",
    "gwizdek albo grzechotka — jeden, zawsze ten sam sygnał zatrzymania",
    "zdjęcia trzech punktów trasy: co po drodze zobaczymy"],
   ["Przed wyjściem pokaż zdjęcia trasy i przypomnij sygnał zatrzymania.",
    "Dobierzcie pary; każde dziecko trzyma swój uchwyt na lince.",
    "Na trasie ćwiczcie zatrzymanie na sygnał — także tam, gdzie nie trzeba."],
   "Idziemy na spacer. Znajdź swoją parę i chwyć uchwyt na lince. Kiedy usłyszysz sygnał, zatrzymujemy się.",
   "Ćwicz zatrzymanie w miejscach bezpiecznych, zanim będzie potrzebne przy jezdni. Sygnał musi być odruchem, nie decyzją."),

 "d9_41": ("D9-41", "Plac zabaw według zasad",
   ["tablica zasad placu — trzy obrazki, powieszona przy wejściu",
    "chorągiewki oznaczające granice strefy zabawy",
    "gwizdek do sygnału powrotu, ten sam co na spacerze",
    "kosz z zabawkami piaskowymi: wiaderko, łopatka, foremka"],
   ["Przy wejściu przejdźcie trzy zasady z tablicy — obrazek po obrazku.",
    "Rozstaw chorągiewki, żeby granica strefy była widoczna.",
    "Na koniec daj sygnał gwizdkiem i zbierzcie zabawki do kosza."],
   "Na placu zabaw czekamy na swoją kolej. Popatrz na tablicę: na zjeżdżalni jest jedno dziecko. Kiedy usłyszysz gwizdek, wracamy do mnie.",
   "Chorągiewki działają lepiej niż wołanie „nie odchodź”. Trzylatek nie ocenia odległości, ale widzi, gdzie kończy się jego pole."),

 "d9_42": ("D9-42", "Teatrzyk i książka",
   ["książki z dużymi ilustracjami, jedna scena na stronę",
    "pacynki bohaterów opowiadania",
    "dwa obrazki do wyboru po czytaniu — jeden pasuje, drugi nie",
    "poduszki do słuchania, ułożone półkolem",
    "kukiełkowy parawan do krótkich scenek"],
   ["Usiądźcie na poduszkach i pokaż okładkę, zanim zaczniesz czytać.",
    "Czytaj całość bez przerywania; pacynki wchodzą przy dialogach.",
    "Po czytaniu połóż dwa obrazki i poproś o wskazanie pasującego."],
   "Siadamy na poduszkach, zaczynamy opowieść. Słuchaj uważnie, co robi nasz bohater. Potem pokażesz obrazek, który do niej pasuje.",
   "Wybór z dwóch obrazków sprawdza rozumienie, a pytanie „o czym było?” sprawdza mowę. To dwie różne umiejętności — nie mieszaj ich w jednym zadaniu."),

}


ZESTAW = Zestaw(POMOCE, "pomoce_a", "audio_a", "3–4 lata")
