# -*- coding: utf-8 -*-
"""Cele SMART do wskaźników FBA w układzie banku KPOF: wiek × poziom wsparcia.

Druk FBA-C (`dane_fba.py`) daje jeden cel do wskaźnika, a kryterium i horyzont
bierze z punktacji funkcji u konkretnego ucznia. Ten moduł jest tym samym
materiałem ułożonym tak, jak układa go bank celów SMART: **trzy wersje wiekowe
po trzy poziomy wsparcia**, czyli 25 × 3 × 3 = 225 celów, z których nauczyciel
wybiera komórkę, zamiast przepisywać cel pod dziecko.

Wersje wiekowe są te same, co w banku:

    A · 3–4 lata     symbol podany do ręki, krótkie czasy, proste zachowanie
    B · 5 lat        karta leżąca na stoliku plus słowo, czasy średnie
    C · 6 lat        słowo zamiast karty, nazywanie własnego stanu, planowanie

Poziom wsparcia zmienia **warunki zadania**, nie funkcję zachowania. Na każdym
poziomie dziecko uczy się tej samej drogi do tej samej funkcji — różni się to,
ile dostaje podpory:

    Poziom III   podpora dorosłego albo podanie pomocy do ręki   3 z 5 ·  4 tygodnie
    Poziom II    pomoc w zasięgu, dziecko sięga po nią samo      4 z 5 ·  8 tygodni
    Poziom I     bez pomocy przedmiotowej, zachowanie trudniejsze 4 z 5 · 12 tygodni

Kryterium na Poziomie I zostaje 4 z 5, a nie rośnie do 5 z 5 — rośnie trudność
samego zachowania, nie liczba prób. Cel „za każdym razem" jest w przedszkolu
celem nie do osiągnięcia i psuje ewaluację, zamiast ją domykać.

Treść komórki to samo zachowanie; kryterium i horyzont dokłada `build_tabela.py`
z poziomu, więc jedna zmiana progu przechodzi przez wszystkie 225 celów.
"""

POZIOMY = [
    ("p3", "Poziom III", "3 z 5", "4 tygodni",  "podpora dorosłego, pomoc podana do ręki"),
    ("p2", "Poziom II",  "4 z 5", "8 tygodni",  "pomoc w zasięgu, dziecko sięga po nią samo"),
    ("p1", "Poziom I",   "4 z 5", "12 tygodni", "bez pomocy przedmiotowej, zachowanie trudniejsze"),
]

WERSJE = [("A", "3–4 lata"), ("B", "5 lat"), ("C", "6 lat")]

# Wskaźniki kwestionariusza w brzmieniu przedszkolnym („dziecko", nie „uczeń").
# Kolejność i numeracja jak w kwestionariuszu funkcji: I.1–V.5.
CELE = {
 "I": dict(nazwa="Ucieczka / unikanie", wskazniki=[
  dict(wskaznik="Zachowanie pojawia się, gdy dziecko ma wykonać trudne lub nielubiane zadanie.",
       zastepcze="rozpoczęcie zadania",
       A=["Weźmie do ręki pierwszy element zadania podany przez nauczyciela",
          "Rozpocznie zadanie po pokazaniu karty „najpierw praca, potem zabawa”",
          "Rozpocznie zadanie po jednym poleceniu i wykona pierwszy krok samo"],
       B=["Rozpocznie zadanie, gdy nauczyciel wykona pierwszy krok razem z nim",
          "Rozpocznie zadanie w ciągu minuty po wskazaniu pierwszego kroku na karcie",
          "Rozpocznie trudne zadanie w ciągu minuty i wykona dwa kroki bez podpowiedzi"],
       C=["Rozpocznie trudne zadanie po wybraniu, od którego z dwóch kroków zaczyna",
          "Rozpocznie trudne zadanie w ciągu minuty i powie, co robi jako pierwsze",
          "Rozpocznie trudne zadanie i doprowadzi je do końca, prosząc o pomoc zamiast przerywać"]),
  dict(wskaznik="Zachowanie nasila się przy poleceniach lub wymaganiach.",
       zastepcze="wykonanie polecenia",
       A=["Wykona polecenie pokazane gestem i obrazkiem, przy dorosłym obok",
          "Wykona polecenie po jednym powtórzeniu i pokazaniu obrazka",
          "Wykona polecenie usłyszane raz, bez pokazywania obrazka"],
       B=["Wykona polecenie po powtórzeniu i zapowiedzi „jeszcze dwie rzeczy i koniec”",
          "Wykona polecenie po jednym powtórzeniu, bez odmowy i odchodzenia od stolika",
          "Wykona dwa polecenia po kolei, usłyszane raz"],
       C=["Wykona polecenie po powtórzeniu i pokazaniu, ile zostało do końca",
          "Wykona polecenie po jednym powtórzeniu i powie, kiedy skończy",
          "Wykona serię trzech poleceń zapowiedzianych naraz, bez przypominania"]),
  dict(wskaznik="Po zachowaniu dziecko zostaje zwolnione z zadania albo odprowadzone.",
       zastepcze="powrót do zadania po przerwie",
       A=["Wróci do stolika po przerwie, prowadzone za rękę przez nauczyciela",
          "Wróci do stolika po sygnale dźwiękowym i dokończy jeden element",
          "Wróci do stolika po przerwie i dokończy zadanie zaczęte przed nią"],
       B=["Wróci do zadania po trzyminutowej przerwie i wykona jedną, wskazaną część",
          "Wróci do zadania po przerwie i dokończy połowę tego, co zostało",
          "Wróci do zadania po przerwie i dokończy je w całości"],
       C=["Wróci do zadania po przerwie i powie, co zostało do zrobienia",
          "Wróci do zadania po przerwie i dokończy je bez przypominania",
          "Samo zdecyduje o końcu przerwy w umówionym czasie i wróci do zadania"]),
  dict(wskaznik="Zachowanie rzadziej występuje, gdy zadanie jest łatwe lub atrakcyjne.",
       zastepcze="podjęcie trudniejszego zadania",
       A=["Podejmie trudniejsze zadanie ułożone po dwóch łatwych, z pomocą dorosłego",
          "Podejmie trudniejsze zadanie po dwóch łatwych, po pokazaniu, co ma zrobić",
          "Podejmie trudniejsze zadanie po dwóch łatwych, bez pokazywania"],
       B=["Wykona serię „dwa łatwe, jedno trudne” przy nauczycielu siedzącym obok",
          "Wykona serię „dwa łatwe, jedno trudne”, prosząc o pomoc przy trudnym",
          "Wykona serię „dwa łatwe, jedno trudne” samodzielnie"],
       C=["Wybierze z dwóch zadań to trudniejsze przynajmniej raz w serii",
          "Wykona trudniejsze zadanie po dwóch łatwych i oceni, co było łatwe, a co trudne",
          "Zaplanuje kolejność zadań tak, by trudne wypadło w środku, i wykona ją"]),
  dict(wskaznik="Po „odpuszczeniu” zadania zachowanie ustaje — ucieczka działa.",
       zastepcze="prośba o przerwę",
       A=["Poda nauczycielowi kartę „przerwa” podaną do ręki, zamiast odejść od stolika",
          "Weźmie ze stolika kartę „przerwa” i pokaże ją, zamiast odejść od stolika",
          "Poprosi o przerwę słowem „przerwa”, zamiast odejść od stolika"],
       B=["Pokaże kartę „przerwa” po przypomnieniu, zamiast przerwać zadanie krzykiem",
          "Pokaże kartę „przerwa” samo, zanim przerwie zadanie",
          "Poprosi o przerwę słowami i wróci do zadania po jej końcu"],
       C=["Pokaże kartę „przerwa” przy pierwszym sygnale zmęczenia zadaniem",
          "Poprosi o przerwę słowami i powie, ile jej potrzebuje",
          "Poprosi o przerwę, ustali z nauczycielem jej długość i dotrzyma umowy"]),
 ]),
 "II": dict(nazwa="Sensoryczne / autostymulacja", wskazniki=[
  dict(wskaznik="Zachowanie pojawia się także wtedy, gdy dziecko jest samo.",
       zastepcze="korzystanie z przedmiotu do regulacji",
       A=["Weźmie gniotek podany przez nauczyciela i ściśnie go zamiast machać rękami",
          "Sięgnie po gniotek z pudełka przy stoliku w czasie pracy samodzielnej",
          "Sięgnie po wybrany przedmiot do regulacji i odłoży go po skończeniu zadania"],
       B=["Skorzysta z taśmy na nodze krzesła po przypomnieniu dorosłego",
          "Skorzysta z taśmy albo gniotka samo, w czasie pracy przy stoliku",
          "Wybierze przedmiot do regulacji i użyje go, nie przerywając zadania"],
       C=["Wskaże na karcie, czego potrzebuje, i skorzysta z podanej formy",
          "Samo sięgnie po formę regulacji z kącika wyciszenia i wróci do zadania",
          "Wybierze formę regulacji i powie, dlaczego akurat tej potrzebuje"]),
  dict(wskaznik="Zachowanie wydaje się dostarczać przyjemnych wrażeń (ruch, dźwięk, dotyk).",
       zastepcze="nazwanie potrzeby sensorycznej",
       A=["Wskaże na dwóch obrazkach, czy chce się kołysać, czy ściskać",
          "Wskaże na karcie z trzema obrazkami, jakiego wrażenia potrzebuje",
          "Powie albo pokaże, czego potrzebuje: ruchu, ucisku czy ciszy"],
       B=["Wskaże wrażenie na karcie diety sensorycznej po pytaniu dorosłego",
          "Wskaże wrażenie na karcie samo i wybierze jedną z dwóch form",
          "Nazwie słowem, jakiego wrażenia potrzebuje, i wybierze formę"],
       C=["Wskaże na karcie potrzebne wrażenie i wybierze formę z tego pola",
          "Nazwie potrzebę i wybierze formę, która nie przeszkadza innym dzieciom",
          "Zaplanuje z nauczycielem, które wrażenia dostanie w ciągu dnia i kiedy"]),
  dict(wskaznik="Zachowanie występuje niezależnie od reakcji otoczenia.",
       zastepcze="zaplanowana przerwa sensoryczna",
       A=["Pójdzie do kącika wyciszenia prowadzone za rękę, gdy zadzwoni minutnik",
          "Pójdzie do kącika wyciszenia po sygnale minutnika, za dorosłym",
          "Pójdzie do kącika wyciszenia po sygnale minutnika samo"],
       B=["Skorzysta z zaplanowanej przerwy sensorycznej po jednym przypomnieniu",
          "Skorzysta z zaplanowanej przerwy po sygnale, bez przypominania",
          "Skorzysta z przerwy i wróci do zajęć po jej zakończeniu, bez wołania"],
       C=["Skorzysta z przerwy po sygnale i odhaczy ją na swoim planie dnia",
          "Weźmie przerwę we własnym czasie, gdy poczuje, że jej potrzebuje",
          "Zaplanuje przerwy na swoim planie dnia i skorzysta z nich zgodnie z planem"]),
  dict(wskaznik="Zachowanie nasila się przy nudzie albo braku aktywności.",
       zastepcze="zajęcie się czymś w wolnej chwili",
       A=["Wybierze zabawkę z dwóch podanych, gdy skończy zadanie",
          "Wybierze zajęcie z tacki „skończyłem” i zajmie się nim przez dwie minuty",
          "Wybierze zajęcie z półki i zajmie się nim przez pięć minut"],
       B=["Wybierze z trzech obrazków, co robi po skończeniu zadania",
          "Wybierze zajęcie z listy „gdy skończę wcześniej” i zajmie się nim pięć minut",
          "Zajmie się wybranym zajęciem do końca pracy grupy, bez przypominania"],
       C=["Wybierze zajęcie z listy i powie, co wybrało",
          "Zajmie się wybranym zajęciem pięć minut i nie przeszkadza pracującym dzieciom",
          "Zaproponuje własne zajęcie na czas oczekiwania i doprowadzi je do końca"]),
  dict(wskaznik="Zachowanie trudno przerwać uwagą albo poleceniem.",
       zastepcze="zamiana na formę zastępczą",
       A=["Przerwie kręcenie się, gdy nauczyciel położy dłoń na jego dłoni i pokaże zabawkę",
          "Przerwie autostymulację po pokazaniu karty „stop — zamiana”",
          "Przerwie autostymulację po pokazaniu karty i weźmie formę zastępczą"],
       B=["Zakończy autostymulację w ciągu minuty od sygnału wzrokowo-dotykowego",
          "Zakończy autostymulację w ciągu 30 sekund od sygnału i weźmie gniotek",
          "Zakończy autostymulację po samym sygnale wzrokowym i wróci do zajęć"],
       C=["Zakończy autostymulację po sygnale i przejdzie do formy zastępczej",
          "Zamieni autostymulację na formę zastępczą, gdy samo to zauważy",
          "Powie, kiedy trudno mu przestać, i poprosi o pomoc w zamianie"]),
 ]),
 "III": dict(nazwa="Uwaga", wskazniki=[
  dict(wskaznik="Zachowanie pojawia się, gdy dorosły zajmuje się czymś innym.",
       zastepcze="czekanie na uwagę",
       A=["Poczeka 30 sekund przy zajętym dorosłym, trzymając kartę „czekam”",
          "Położy kartę „potrzebuję pomocy” i poczeka minutę",
          "Położy kartę i poczeka dwie minuty przy swoim stoliku"],
       B=["Położy kartę „potrzebuję pomocy” po przypomnieniu i poczeka minutę",
          "Położy kartę samo i poczeka dwie minuty, nie odchodząc od stolika",
          "Poczeka trzy minuty, zajmując się zadaniem do czasu podejścia nauczyciela"],
       C=["Położy kartę i poczeka dwie minuty przy zadaniu",
          "Poczeka trzy minuty i w tym czasie zrobi kolejny krok zadania",
          "Poczeka do końca rozmowy nauczyciela z innym dzieckiem, nie przerywając jej"]),
  dict(wskaznik="Po zachowaniu dziecko otrzymuje uwagę (upomnienie, rozmowę).",
       zastepcze="akceptowalna prośba o uwagę",
       A=["Dotknie ramienia nauczyciela zamiast krzyczeć, po przypomnieniu gestu",
          "Podniesie rękę albo pokaże kartę, żeby zawołać nauczyciela",
          "Podniesie rękę i poczeka, aż nauczyciel podejdzie"],
       B=["Podniesie rękę po przypomnieniu, zamiast zaczepiać inne dzieci",
          "Podniesie rękę samo i poczeka na skinienie nauczyciela",
          "Poprosi o uwagę słowami: „czy możesz do mnie podejść”"],
       C=["Podniesie rękę i poczeka, zamiast zachowania trudnego",
          "Poprosi o uwagę słowami i powie, w czym potrzebuje pomocy",
          "Poczeka na swoją kolej w rozmowie i poprosi o uwagę w przerwie zajęć"]),
  dict(wskaznik="Zachowanie nasila się w grupie albo przy publiczności.",
       zastepcze="wypowiedź w swojej kolejce",
       A=["Powie jedno słowo w rundzie, gdy dostanie do ręki maskotkę mówiącego",
          "Powie zdanie w rundzie, trzymając maskotkę, i odda ją dalej",
          "Poczeka na swoją kolej w rundzie i powie zdanie bez maskotki"],
       B=["Poczeka na swoją kolej w rundzie z podpowiedzią wzrokową nauczyciela",
          "Poczeka na swoją kolej i nie wchodzi w słowo innym dzieciom",
          "Poprowadzi rundę: poda głos następnej osobie i samo poczeka na swoją"],
       C=["Zgłosi się do wypowiedzi w rundzie i poczeka na kolej",
          "Wypowie się w kolejce i wysłucha do końca dziecka przed sobą",
          "Wypowie się na forum grupy i odniesie się do tego, co powiedziało inne dziecko"]),
  dict(wskaznik="Zachowanie ustaje, gdy dziecko dostanie indywidualną uwagę.",
       zastepcze="uwaga „z wyprzedzeniem”",
       A=["Skorzysta z minuty uwagi na powitanie i przejdzie do zabawy za dorosłym",
          "Skorzysta z dwóch minut uwagi na początku dnia i przejdzie do zabawy",
          "Skorzysta z uwagi na powitanie i wróci do zabawy po sygnale"],
       B=["Skorzysta z zaplanowanej rozmowy na starcie zajęć i wróci do stolika z dorosłym",
          "Skorzysta z dwóch minut rozmowy i wróci do zadania po sygnale",
          "Skorzysta z rozmowy i samo wróci do zadania, bez przypominania"],
       C=["Skorzysta z dwóch minut uwagi na początku zajęć i wróci do pracy",
          "Poprosi o rozmowę w umówionym momencie dnia zamiast w trakcie zajęć",
          "Umówi się z nauczycielem na porę rozmowy i dotrzyma tej umowy"]),
  dict(wskaznik="Dziecko patrzy na reakcję dorosłego w trakcie zachowania.",
       zastepcze="umówiony gest zamiast sprawdzania",
       A=["Poszuka wzrokiem nauczyciela i pokaże kartę zamiast rzucić zabawką",
          "Uniesie dłoń, żeby dorosły na nie spojrzał",
          "Uniesie dłoń i poczeka na skinienie, zamiast sprawdzać reakcję zachowaniem"],
       B=["Uniesie dłoń po przypomnieniu, zamiast zaczepiać, żeby dorosły zareagował",
          "Uniesie dłoń samo i poczeka na odpowiedź",
          "Powie, że chce pokazać, co zrobiło, zamiast zwracać uwagę zachowaniem"],
       C=["Uniesie dłoń zamiast sprawdzania reakcji dorosłego",
          "Pokaże swoją pracę nauczycielowi w umówionym momencie",
          "Powie wprost, że chce pochwały albo uwagi, zamiast zachowania trudnego"]),
 ]),
 "IV": dict(nazwa="Dostęp do przedmiotu / aktywności", wskazniki=[
  dict(wskaznik="Zachowanie pojawia się, gdy dziecko nie może dostać tego, czego chce.",
       zastepcze="przyjęcie odmowy",
       A=["Wybierze jedną z dwóch zabawek podanych po odmowie",
          "Wybierze jedną z dwóch propozycji po odmowie i zajmie się nią",
          "Przyjmie odmowę i wybierze inne zajęcie samo"],
       B=["Wybierze z dwóch propozycji po odmowie, przy dorosłym obok",
          "Przyjmie odmowę i wybierze jedną z dwóch alternatyw samo",
          "Przyjmie odmowę i zaproponuje, czym zajmie się zamiast tego"],
       C=["Wybierze jedną z dwóch alternatyw po odmowie",
          "Przyjmie odmowę, powie, że jest mu przykro, i wybierze inne zajęcie",
          "Przyjmie odmowę i zapyta, kiedy będzie mogło dostać to, o co prosiło"]),
  dict(wskaznik="Zachowanie nasila się przy odmowie albo zabraniu przedmiotu.",
       zastepcze="oddanie przedmiotu po zapowiedzi",
       A=["Odda zabawkę do ręki nauczyciela po zapowiedzi i sygnale minutnika",
          "Odłoży zabawkę na półkę po sygnale minutnika",
          "Odłoży zabawkę po sygnale i przejdzie do następnej aktywności"],
       B=["Odda przedmiot po zapowiedzi „jeszcze dwie minuty” i przypomnieniu",
          "Odda przedmiot po zapowiedzi i sygnale, bez przypominania",
          "Odda przedmiot i samo odłoży go na miejsce po zakończeniu zabawy"],
       C=["Odda przedmiot po zapowiedzi i sygnale minutnika",
          "Zakończy zabawę w zapowiedzianym czasie i odłoży przedmiot",
          "Samo ustawi minutnik na koniec zabawy i dotrzyma tego czasu"]),
  dict(wskaznik="Po zachowaniu dziecko otrzymuje pożądany przedmiot albo aktywność.",
       zastepcze="prośba o przedmiot",
       A=["Poda kartę z obrazkiem przedmiotu zamiast go wyrywać",
          "Pokaże kartę albo powie „proszę” zamiast wyrywać przedmiot",
          "Powie „poproszę” i poczeka na odpowiedź"],
       B=["Poprosi o przedmiot słowem „proszę” po przypomnieniu",
          "Poprosi pełnym zwrotem „poproszę o…” i poczeka",
          "Poprosi pełnym zwrotem i przyjmie odpowiedź, także odmowną"],
       C=["Poprosi o przedmiot pełnym zwrotem zamiast sięgać po niego",
          "Poprosi o przedmiot i powie, do czego jest mu potrzebny",
          "Poprosi kolegę o przedmiot i umówi się z nim, kiedy go odda"]),
  dict(wskaznik="Zachowanie ustaje, gdy dziecko dostanie to, czego chciało.",
       zastepcze="czekanie na przedmiot",
       A=["Poczeka 30 sekund na przedmiot, trzymając kartę „czekam”",
          "Poczeka minutę na przedmiot z wizualnym licznikiem",
          "Poczeka dwie minuty na przedmiot, zajmując się czymś innym"],
       B=["Poczeka dwie minuty z licznikiem, przy dorosłym obok",
          "Poczeka trzy minuty na przedmiot, korzystając z licznika",
          "Poczeka trzy minuty bez licznika, zajęte innym zadaniem"],
       C=["Poczeka trzy minuty na przedmiot z wizualnym licznikiem",
          "Poczeka do końca zajęć na przedmiot i wróci po niego",
          "Umówi się z nauczycielem, kiedy dostanie przedmiot, i doczeka do tej pory"]),
  dict(wskaznik="Zachowanie występuje przy oczekiwaniu na coś atrakcyjnego.",
       zastepcze="czynność „w międzyczasie”",
       A=["Zajmie się zabawką podaną na czas czekania na atrakcję",
          "Weźmie zadanie z pudełka „w międzyczasie” i zajmie się nim",
          "Zajmie się zadaniem w międzyczasie do sygnału rozpoczęcia atrakcji"],
       B=["Wykona zadanie z pudełka po przypomnieniu dorosłego",
          "Wykona zadanie w międzyczasie i dostanie żeton",
          "Wykona dwa zadania w międzyczasie, bez przypominania"],
       C=["Wykona zadanie „w międzyczasie” w czasie czekania na atrakcję",
          "Wybierze sobie zajęcie na czas czekania i doprowadzi je do końca",
          "Zaplanuje, czym zajmie się w czasie czekania, i wykona ten plan"]),
 ]),
 "V": dict(nazwa="Regulacja emocji / napięcie", wskazniki=[
  dict(wskaznik="Zachowanie pojawia się przy zmianie, niespodziance albo przeciążeniu.",
       zastepcze="przejście do zmienionej aktywności",
       A=["Przejdzie do nowej aktywności za dorosłym, po pokazaniu obrazka zmiany",
          "Przejdzie do nowej aktywności po przełożeniu karty na planie dnia",
          "Przejdzie do zmienionej aktywności po zapowiedzi, bez płaczu"],
       B=["Przejdzie do zmienionej aktywności po uprzedzeniu i pokazaniu zmiany",
          "Przejdzie do zmienionej aktywności po samej zapowiedzi słownej",
          "Przyjmie zmianę planu i powie, co teraz będzie robić"],
       C=["Przejdzie do zmienionej aktywności po pokazaniu zmiany na planie",
          "Przyjmie niezapowiedzianą zmianę i zapyta, co będzie dalej",
          "Zaproponuje, jak przestawić plan po zmianie, i przejdzie do nowej aktywności"]),
  dict(wskaznik="Zachowaniu towarzyszą objawy napięcia (płacz, pobudzenie).",
       zastepcze="nazwanie napięcia",
       A=["Wskaże buźkę pokazującą, jak się czuje, z dwóch podanych",
          "Wskaże kolor na termometrze emocji: zielony albo czerwony",
          "Wskaże jeden z trzech kolorów termometru i nazwie emocję słowem"],
       B=["Wskaże kolor na termometrze po pytaniu dorosłego",
          "Wskaże kolor samo, przy pierwszych objawach napięcia",
          "Nazwie emocję słowem i powie, co mu pomoże"],
       C=["Wskaże kolor na termometrze przy pierwszych objawach napięcia",
          "Nazwie emocję i jej powód: „złoszczę się, bo…”",
          "Rozpozna napięcie, zanim urośnie, i powie, czego potrzebuje, żeby je obniżyć"]),
  dict(wskaznik="Zachowanie występuje w sytuacjach stresu albo przebodźcowania.",
       zastepcze="skorzystanie ze strefy wyciszenia",
       A=["Pójdzie do kącika wyciszenia prowadzone za rękę i zostanie tam minutę",
          "Pójdzie do kącika wyciszenia po pokazaniu karty i zostanie trzy minuty",
          "Pójdzie do kącika wyciszenia samo, gdy zrobi się głośno"],
       B=["Skorzysta z kącika wyciszenia po propozycji dorosłego, przez trzy minuty",
          "Skorzysta z kącika wyciszenia na własną prośbę, przez pięć minut",
          "Poprosi o wyciszenie i wybierze formę: oddech, koc albo słuchawki"],
       C=["Skorzysta z kącika wyciszenia po propozycji dorosłego",
          "Poprosi o wyciszenie samo i wybierze formę, która mu pomaga",
          "Skorzysta ze strategii oddechowej przy stoliku, bez wychodzenia z zajęć"]),
  dict(wskaznik="Zachowanie ustaje po wyciszeniu albo odzyskaniu równowagi.",
       zastepcze="powrót do zajęć",
       A=["Wróci do grupy za dorosłym po wyciszeniu",
          "Wróci do grupy po sygnale, w ciągu dwóch minut",
          "Wróci do grupy samo i włączy się w zabawę"],
       B=["Wróci do zajęć po wyciszeniu, przy dorosłym obok",
          "Wróci do zajęć w ciągu trzech minut od zakończenia wyciszenia",
          "Wróci do zajęć i dokończy zadanie przerwane przed wyciszeniem"],
       C=["Wróci do zajęć w ciągu pięciu minut od zakończenia strategii",
          "Wróci do zajęć i powie, co pomogło mu się uspokoić",
          "Wróci do zajęć i naprawi to, co się wydarzyło — przeprosi albo posprząta"]),
  dict(wskaznik="Zachowanie jest trudne do przewidzenia, wybucha nagle.",
       zastepcze="sygnał przed wybuchem",
       A=["Pokaże czerwoną kartę podaną przez dorosłego, gdy zaczyna się złościć",
          "Sięgnie po czerwoną kartę ze stolika przy pierwszych oznakach złości",
          "Pokaże czerwoną kartę, zanim zacznie krzyczeć"],
       B=["Pokaże czerwoną kartę po zauważeniu przez dorosłego pierwszych sygnałów",
          "Pokaże czerwoną kartę samo, zanim dojdzie do wybuchu",
          "Powie „robi się czerwono” i poprosi o pomoc, zanim wybuchnie"],
       C=["Pokaże czerwoną kartę przy pierwszym sygnale napięcia",
          "Nazwie pierwszy sygnał napięcia i poprosi o przerwę",
          "Rozpozna swój sygnał ostrzegawczy i samo użyje strategii, zanim wybuchnie"]),
 ]),
}


def stan():
    """(funkcji, wskaźników, celów) — do kontroli po dopisaniu treści."""
    wsk = sum(len(f["wskazniki"]) for f in CELE.values())
    cele = sum(len(w[kod]) for f in CELE.values() for w in f["wskazniki"]
               for kod, _ in WERSJE)
    return len(CELE), wsk, cele
