# -*- coding: utf-8 -*-
"""Dane do wypełnienia druku IPET — Zofia Lewandowska (grupa Biedronki, 2026/2027).
Źródła: WOPF (public/wopf-dane.json — średnie KPOF, karta ABC·FBA, ToM, kwestionariusz mowy,
profil sensoryczny, profil biopsychospołeczny, zalecenia z orzeczenia PPP.4223.87.2026),
druki obserwacji pogłębionej, skrypt szkolenia (wyd. 2 po audycie z 5.09.2026)."""

D = dict(
  imie='Zofia Lewandowska', grupa='Biedronki', data='30.09.2026',
  # --- I. Dane dziecka
  ur='30.06.2022', grupa_pelna='Biedronki (4-latki)', rok='2026 / 2027',
  nr_dok='IPET/ZL/1/2026-2027 · ważne do 31.08.2027 (etap wychowania przedszkolnego; modyfikacja po każdej ocenie okresowej)',
  placowka='Przedszkole publiczne w Koszalinie (oddział ogólnodostępny, grupa Biedronki)',
  podst_orz='autyzm dziecięcy — trudności w komunikacji społecznej, regulacji emocji i przetwarzaniu sensorycznym',
  nr_orz='orzeczenie nr PPP.4223.87.2026 z 12.05.2026 — Poradnia Psychologiczno-Pedagogiczna w Koszalinie',
  podst_wsp='orzeczenie o potrzebie kształcenia specjalnego (ważne na etap wychowania przedszkolnego) · WOPF z 25.09.2026 — rekomendacja: Poziom II wsparcia + zajęcia rewalidacyjne wg orzeczenia',
  # --- Mój głos
  glos_sposob={1,2,3,4,5,6,7},   # indeksy zaznaczonych sposobów (0..7)
  glos_mocne='„Umiem budować wysokie wieże z klocków" (wskazane obrazkiem: klocki, huśtawka, tor równowagi). Szybko biegam, nie spadam z równoważni. Pamiętam, gdzie co leży w sali (pamięć wzrokowa 3,6 — KPOF I).',
  glos_trudnosc='Hałas (wskazanie obrazka „zatkane uszy"), sprzątanie zabawek, kiedy „coś się nagle zmienia", nowe jedzenie na talerzu. „Nie lubię, jak jest głośno" — pokazała słuchawki.',
  glos_komunikacja='Mowa czynna: zdania 2–3-wyrazowe (kwestionariusz mowy 6/10), rozumienie poleceń dwuetapowych (8/10). Wspomagająco: gest, piktogramy, pasek komunikacyjny „proszę / pomóż / stop". Wskazówki: mów krótko, poprzedź gestem i obrazkiem, daj czas na odpowiedź (5–7 s), nie używaj ironii ani zdań warunkowych.',
  glos_lubie='Klocki i budowanie, huśtawka i tor równowagi w ogrodzie, miś, kolega Antek, pani Kasia (znany dorosły), kącik wyciszenia z poduchami.',
  glos_nielubie='Głośne zabawy całą grupą, dzwonek, sprzątanie klocków „za szybko", zmiana planu bez uprzedzenia, nowe smaki, dotykanie kleistych mas.',
  glos_zabawy='Budowanie z klocków (samodzielnie i z dorosłym „na niby"), zabawy ruchowe w ogrodzie, układanki i dopasowywanie wg cechy, oglądanie książeczek obrazkowych.',
  glos_pomaga={'cisza','przewidywalny plan dnia','piktogramy','ruch','przerwy','wsparcie nauczyciela'},
  glos_inne='Słuchawki wyciszające, minutnik przed sprzątaniem, symbol „koniec", kącik wyciszenia, pochwała od razu.',
  glos_buzka='Dobrze',
  glos_marzenie='„Bawić się z Antkiem w klocki" (wskazane obrazkiem) · „iść na huśtawkę".',
  # --- WOPFU cz. I
  mocne={0,1,4,6,7},  # wg listy 10 (0..9)
  mocne_inne='Rozumienie mowy 8/10 (polecenia dwuetapowe) · kontakt z jednym wybranym kolegą · reaguje na pochwałę i plan obrazkowy · zabawy konstrukcyjne, zabawa „na niby" z dorosłym · poruszanie się 4,4 (KPOF IV — zasób).',
  motyw={2,3,4,5,6},
  motyw_inne='Pochwała natychmiast po zachowaniu; nagroda = zabawa klockami / huśtawka (First-Then); tablica wyboru z 3 obrazkami; przerwa ruchowa jako wzmocnienie co 20 min; system spójny dom–przedszkole.',
  bariery={0,4,5,6,9},
  bariery_inne='Wybiórczość pokarmowa (nadwrażliwość oralna) · zabawa równoległa, nie tematyczna · brak inicjowania kontaktu i proszenia o pomoc · bariera środowiskowa: liczna grupa, hałas, nagłe zmiany planu (WOPF sekcja XII).',
  abcA={0,1,2}, abcB={0,1,4}, abcC={0,2,4,7},
  # --- KPOF
  kpof=[('3,6','N, R, S','W','I'),('3,2','N, R, S','W','I'),('2,5','N, R, S','W','II'),('4,4','N, R, S','W','I'),
        ('3,0','N, R, S','W','I'),('3,5','N, R','W','I'),('1,6','N, R, S','W','III'),('3,2','N, R, S','W','I'),('2,5','N, R, S','W','II')],
  kpof_poziom='II',
  # --- Zalecenia z orzeczenia — bank (str. 7–8): zestawy zaznaczeń w grupach 1..6
  zorz={1:{0,1,2,4,5,6,7}, 2:{0,1,2,5}, 3:{0,1,2,3,4,6,7}, 4:{0,1,2,3,5}, 5:{0,1,2,3,4}, 6:{0,1,2,3,5}},
  zorz_dod='Dieta sensoryczna wg profilu (nadreaktywność słuchowa 14/24 i wzrokowa 9/24): słuchawki wyciszające w hałasie, miejsce pracy tyłem do okna, ograniczenie dekoracji nad stolikiem; bez przymusu przy posiłkach (wybiórczość pokarmowa — współpraca z terapeutą SI); kontrola profilu sensorycznego 05.2027; przerwy proprioceptywne co 20 min (noszenie „ciężkich" zadań, kamizelka obciążeniowa wg SI).',
  # tabela 2 — zalecenia z orzeczenia i sposób realizacji
  zorz_tab=[
   ('Kształcenie specjalne w przedszkolu ogólnodostępnym z nauczycielem współorganizującym (obowiązkowo — autyzm)',
    'Nauczyciel współorganizujący w grupie Biedronki przez cały czas pobytu (§ 7 ust. 2 rozp.); wspiera przejścia między aktywnościami, zabawę z rówieśnikiem i realizację dostosowań.'),
   ('Zajęcia rewalidacyjne: komunikacja i AAC oraz trening umiejętności społecznych — 2 × 30 min tygodniowo',
    'Rewalidacja 2 × 30 min: (1) komunikacja i AAC — logopeda; (2) TUS wg programów P1 ToM · P2 ABC/FBA · P3 kompetencje — nauczyciel-terapeuta / psycholog. Sekcja 6A.'),
   ('Terapia integracji sensorycznej 1 × 45 min i terapia logopedyczna 2 × 30 min',
    'SI 1 × 45 min — terapeuta SI (A. Mazur); zajęcia logopedyczne 2 × 30 min — neurologopeda (P. Kowalczyk). Sekcje 6A i 6B.'),
   ('Stały, przewidywalny plan dnia z wizualnym wsparciem, uprzedzanie zmian, przerwy sensoryczne co 20 min',
    'Plan obrazkowy dnia na wysokości dziecka, karta „co teraz / co potem", minutnik + symbol „koniec" przed sprzątaniem, przerwa ruchowa co 20 min — nauczyciele grupy (sekcje 4b, 5).'),
   ('Ograniczenie hałasu i liczby bodźców w sali, kącik wyciszenia, słuchawki wyciszające',
    'Kącik wyciszenia (poduchy, namiot), słuchawki dostępne w sali i na uroczystościach, miejsce przy stoliku tyłem do okna, mniej dekoracji — sekcja 5b.'),
   ('Współpraca z rodzicami — spójne strategie w domu i w przedszkolu, konsultacje co 6 tygodni',
    'Konsultacje z rodzicami co 6 tygodni (koordynator), wspólny plan PBS i pasek komunikacyjny w domu, warsztat dla rodziców w II półroczu — sekcje 9, 10.'),
   ('Wielospecjalistyczna ocena co najmniej dwa razy w roku szkolnym (wrzesień, styczeń; zalecana maj)',
    'Ocena wstępna 25.09.2026 (WOPF); ocena okresowa 29.01.2027 i 18.06.2027; kontrola profilu sensorycznego 05.2027 — sekcja III.3.'),
  ],
  zopin_tab=[('nie dotyczy — dziecko posiada orzeczenie o potrzebie kształcenia specjalnego; odrębnej opinii poradni nie wydano',
              'zalecenia realizowane na podstawie orzeczenia (tabela 2) i wyników WOPF (tabela zaleceń z WOPF)')],
  # --- Zalecenia z WOPF — bank (str. 10–11), grupy 1..6
  zwopf={1:{0,2,3}, 2:{0,1,2,3,4,5}, 3:{3,5}, 4:{0,1,2,3,4}, 5:{1,3,4,5}, 6:{0,1,2,3}},
  zwopf_dod='Zachowanie kluczowe (karta ABC·FBA, 12 zapisów 08–22.09.2026): rzucanie klockami i krzyk po zapowiedzi sprzątania — funkcja: uwaga dorosłego + komunikat o dyskomforcie (13/15). Plan PBS: uprzedzanie (minutnik), zachowanie zastępcze „koniec" na pasku komunikacyjnym, natychmiastowa pochwała za spokojne zakończenie. Teoria umysłu (19.09.2026): rozpoznawanie emocji 1/2, przyjmowanie perspektywy 0/2 — cele wg programu P1.',
  # zestawienie wybranych z WOPF (str. 12): (zalecenie, sposób/sfera)
  zwopf_tab=[
   ('Wydłużać czas na wykonanie zadania i dzielić je na etapy (małe kroki)','Sfera 1: zadania w 3 krokach z planem obrazkowym, wydłużony czas — nauczyciele grupy, w każdej aktywności przy stoliku.'),
   ('Wspierać uwagę i pamięć — krótkie zadania, powtórzenia, przypomnienia','Sfera 1: krótkie zadania (do 5 min) w hałasie sali ze słuchawkami; jedno przypomnienie zamiast wielu poleceń.'),
   ('Stosować wsparcie wizualne (plan aktywności, piktogramy, wzory)','Sfera 1 i 6: plan dnia, karta „co teraz / co potem", instrukcja obrazkowa zadania — nauczyciel współorganizujący.'),
   ('Uczyć rozpoznawania i nazywania emocji oraz strategii samoregulacji','Sfera 2: karty emocji w kręgu codziennie, „termometr emocji", kącik wyciszenia — nauczyciele + psycholog (P1, P3).'),
   ('Reagować jednolicie na trudne zachowania (model ABC / PBS)','Sfera 2: plan PBS dla wszystkich dorosłych — uprzedzanie, minutnik, „koniec", pochwała; rejestr ABC prowadzony dalej (P2).'),
   ('Trenować umiejętności społeczne — czekanie na kolej, współdziałanie','Sfera 2: TUS 1 × 30 min (rewalidacja) + zabawa w parze z Antkiem w grupie z modelowaniem nauczyciela.'),
   ('Zapewnić przerwy ruchowe i aktywność naprzemienną · włączyć elementy SI','Sfera 3: przerwa proprioceptywna co 20 min, tor równowagi, „ciężkie" zadania; SI 1 × 45 min — terapeuta SI.'),
   ('Rozwijać komunikację funkcjonalną i inicjowanie kontaktu · wprowadzać AAC wg potrzeb','Sfera 4: pasek komunikacyjny „proszę / pomóż / stop" w sali i w domu; inicjowanie kontaktu z jednym rówieśnikiem — logopeda + nauczyciele.'),
   ('Modelować wypowiedzi i dawać czas na odpowiedź · współpracować z logopedą','Sfera 4: rozbudowa zdania 2–3-wyrazowego, ćwiczenia artykulacyjne 2 × 30 min; techniki logopedy przenoszone do grupy.'),
   ('Stosować plany wizualne czynności · uczyć w sytuacjach naturalnych · wzmacniać próby samodzielności','Sfera 5: sekwencja obrazkowa mycia rąk i ubierania, buty na rzepy przed wyjściem, pochwała za każdą próbę — nauczyciele + rodzice.'),
   ('Stosować przewidywalny rytm dnia i uprzedzać o zmianach · uczyć radzenia sobie ze zmianą','Sfera 6: stały rytm dnia, uprzedzanie „za 2 minuty koniec", stopniowe wprowadzanie zmian z obrazkiem — nauczyciel współorganizujący.'),
   ('Rozwijać zabawę — od równoległej do wspólnej i tematycznej','Sfera 6: zabawa konstrukcyjna z jednym rówieśnikiem 5 min dziennie przy wsparciu dorosłego, potem zabawa tematyczna „na niby".'),
  ],
  # --- Cele SMART — sfery 1..6
  sfery={
   1: dict(poziom='I', trud={1}, wynik='Obszar „Uczenie się i stosowanie wiedzy" — wynik 3,6 / 5 (KPOF I, zasób) oraz „Edukacja i zabawa" 3,2 / 5 (KPOF VIII); przyczyną trudności jest przeciążenie sensoryczne i krótka uwaga w hałasie, nie brak możliwości poznawczych — co odpowiada kwalifikacji:', chip='Poziom I — wsparcie minimalne',
      motyw='Pochwała natychmiastowa, plan obrazkowy z nagrodą po 3 zadaniach (First-Then: klocki), zadania na materiale, który Zofia lubi (dopasowywanie, układanki).',
      cele=[('Cel edukacyjny','podczas zajęć przy stoliku Zofia wykona 3-etapowe zadanie manipulacyjne (dopasowywanie wg cechy) według planu obrazkowego, z jednym przypomnieniem dorosłego, poprawnie w 4 na 5 prób — do 29.01.2027; pomiar: karta obserwacji zadań (stan wyjściowy: wymaga 3–4 przypomnień).'),
            ('Cel terapeutyczny','w sytuacji hałasu w sali Zofia utrzyma uwagę na zadaniu przez 5 minut, korzystając ze słuchawek wyciszających i miejsca tyłem do okna, w 4 na 5 prób — do 29.01.2027; pomiar: obserwacja uwagi w dzienniku.')],
      zint='Wszyscy nauczyciele stosują krótkie, jednoznaczne polecenia poparte obrazkiem, dzielą zadanie na 3 kroki, dają dodatkowy czas i jedno przypomnienie; nauczyciel współorganizujący dba o słuchawki i miejsce pracy; logopeda i psycholog utrwalają te same instrukcje na zajęciach.',
      metody={0,1,2}, formy={0,1,2,3}, inne='Praca w kąciku wyciszenia przy przeciążeniu; instrukcja obrazkowa zadania.',
      pomoce='Plan obrazkowy zadania (3 kroki), układanki i sortery do dopasowywania wg cechy, klocki, słuchawki wyciszające, minutnik, karty pracy z jednym poleceniem.'),
   2: dict(poziom='III', trud={0,1,2,3,4,5}, wynik='Obszar „Wzajemne kontakty i związki międzyludzkie" — wynik niski 1,6 / 5 (KPOF VII, obszar priorytetowy) oraz „Życie w grupie i społeczności" 2,5 / 5 (KPOF IX); ToM: rozpoznawanie emocji 1/2, przyjmowanie perspektywy 0/2 — co odpowiada kwalifikacji:', chip='Poziom III — wsparcie znaczne',
      motyw='Wzmocnienia pozytywne natychmiast po spokojnym zakończeniu zabawy, system „First-Then" (najpierw sprzątanie, potem huśtawka), tablica wyboru nagród, kolega Antek jako partner zabawy.',
      cele=[('Cel społeczny','podczas zabawy konstrukcyjnej z jednym rówieśnikiem Zofia zainicjuje kontakt (poda klocek, powie „daj" lub wskaże na pasku „proszę") w 3 na 5 sytuacji, z podpowiedzią gestem dorosłego — do 29.01.2027; pomiar: karta postępów TUS (stan wyjściowy: nie inicjuje kontaktu).'),
            ('Cel terapeutyczny','po zapowiedzi sprzątania (minutnik + symbol „koniec") Zofia zakończy zabawę bez krzyku i rzucania klockami w 7 na 10 sytuacji — do 29.01.2027; pomiar: rejestr ABC (stan wyjściowy: 3–4 epizody tygodniowo, 20–40 s).'),
            ('Cel emocjonalny','w kręgu porannym Zofia rozpozna i wskaże na kartach 3 emocje (radość, złość, smutek) u siebie lub u bohatera historyjki w 4 na 5 prób — do 29.01.2027; pomiar: karta obserwacji ToM (program P1, cele C1–C2).')],
      zint='Zespół stosuje jeden plan PBS (uprzedzanie, minutnik, „koniec", pochwała) i jednolity system motywacyjny; nauczyciele modelują zabawę w parze, psycholog prowadzi TUS wg P1 · P2 · P3 i przekazuje techniki do grupy; rodzice stosują ten sam plan w domu.',
      metody={0,1,2,3}, formy={0,1,2,3}, inne='Zabawa w parze z wybranym rówieśnikiem (Antek) 5 min dziennie; pacynki i scenki „co czuje miś?".',
      pomoce='Karty emocji, „termometr emocji", historyjki społeczne o sprzątaniu i czekaniu na kolej, minutnik, symbol „koniec", pacynki, plansza zasad, kącik wyciszenia.'),
   3: dict(poziom='I', trud=set(), wynik='Obszar „Motoryka i poruszanie się" — wynik wysoki 4,4 / 5 (KPOF IV, największy zasób); profil sensoryczny: propriocepcja — poszukiwanie bodźców (11/24), układ przedsionkowy w normie (5/24) — co odpowiada kwalifikacji:', chip='Poziom I — wsparcie minimalne',
      motyw='Ruch jako nagroda i regulacja: huśtawka, tor równowagi, noszenie „ciężkich" zadań; docenianie wysiłku, przerwa ruchowa po zadaniu przy stoliku.',
      cele=[('Cel terapeutyczny','na sygnał piktogramu „przerwa" Zofia wykona ćwiczenie proprioceptywne (przeniesienie skrzynki z klockami, tor równowagi) i wróci do zadania w ciągu 1 minuty w 4 na 5 prób — do 29.01.2027; pomiar: karta dnia nauczyciela współorganizującego.'),
            ('Cel edukacyjny','Zofia wykona ćwiczenie grafomotoryczne (ślad po torze, lepienie z masy) bez wycofywania się przy kontakcie z nową fakturą w 3 na 5 prób, bez przymusu — do 29.01.2027; pomiar: obserwacja na zajęciach SI i w grupie.')],
      zint='Nauczyciele wprowadzają przerwy ruchowe co 20 minut i zabawy równoważne w ogrodzie; terapeuta SI (1 × 45 min) ustala dietę sensoryczną i przekazuje ją do sali; nowe faktury oswajane stopniowo, bez przymusu.',
      metody={2,3}, formy={1,2,3}, inne='Kamizelka obciążeniowa wg wskazań SI; swobodny dostęp do huśtawki i toru równowagi.',
      pomoce='Tor równowagi, huśtawka, skrzynka z klockami („ciężkie" zadania), masy plastyczne o różnej fakturze, kamizelka obciążeniowa, piktogram „przerwa".'),
   4: dict(poziom='II', trud={2,3,4,5}, wynik='Obszar „Porozumiewanie się i mowa" — wynik obniżony 2,5 / 5 (KPOF III); kwestionariusz mowy 17.09.2026: rozumienie 8/10, mowa czynna 6/10, artykulacja 4/10, komunikacja w grupie 3/10 (priorytet) — co odpowiada kwalifikacji:', chip='Poziom II — wsparcie umiarkowane',
      motyw='Pochwała za każdą próbę komunikacji (gest, obrazek, słowo), tablica wyboru, obrazkowe wzmocnienia, ulubiona zabawa jako nagroda po ćwiczeniach artykulacyjnych.',
      cele=[('Cel komunikacyjny','w sytuacji potrzeby (picie, pomoc, przerwa) Zofia użyje paska komunikacyjnego „proszę / pomóż / stop" lub słowa samodzielnie, bez podpowiedzi, w 7 na 10 sytuacji — do 29.01.2027; pomiar: karta komunikacji w grupie (stan wyjściowy: komunikacja w grupie 3/10).'),
            ('Cel edukacyjny','przy oglądaniu obrazka sytuacyjnego Zofia zbuduje wypowiedź 3-wyrazową z modelowaniem logopedy w 7 na 10 prób — do 29.01.2027; pomiar: karta postępów logopedy (stan wyjściowy: zdania 2–3-wyrazowe z pełnym modelowaniem).')],
      zint='Wszyscy dorośli honorują gest i pasek komunikacyjny (także przy śniadaniu i w ogrodzie), mówią krótko, poprzedzają polecenie gestem i obrazkiem, dają 5–7 s na odpowiedź; logopeda prowadzi terapię 2 × 30 min i rewalidację AAC, techniki przechodzą do grupy i do domu.',
      metody={0,1,2,3}, formy={0,2,3}, inne='Inicjowanie kontaktu z jednym rówieśnikiem; wybiórczość pokarmowa (sfera oralna) — wspólnie z terapeutą SI.',
      pomoce='Pasek komunikacyjny (proszę / pomóż / stop), tablice i karty PECS, piktogramy czynności, lustro logopedyczne, obrazki sytuacyjne, książeczki obrazkowe.'),
   5: dict(poziom='I', trud={0,1,2}, wynik='Obszar „Dbanie o siebie i samoobsługa" — wynik 3,0 / 5 (KPOF V) i „Życie domowe" 3,5 / 5 (KPOF VI); Zofia samodzielnie je i pije, sygnalizuje potrzebę toalety; ubieranie przy pomocy dorosłego, mycie rąk wg sekwencji obrazkowej — co odpowiada kwalifikacji:', chip='Poziom I — wsparcie minimalne',
      motyw='Tablica osiągnięć z naklejką za samodzielność, wyjście na dwór jako naturalna nagroda po założeniu butów, autonomia wyboru (które buty, który ręcznik).',
      cele=[('Cel terapeutyczny','podczas przygotowania do wyjścia na dwór Zofia założy samodzielnie buty na rzepy w 4 z 5 kolejnych wyjść — do 29.01.2027; pomiar: karta samodzielności (stan wyjściowy: zakłada z pomocą dorosłego).'),
            ('Cel edukacyjny','przed posiłkiem Zofia umyje ręce według sekwencji obrazkowej (5 kroków) z jednym przypomnieniem w 4 na 5 prób — do 29.01.2027; pomiar: karta monitoringu samodzielności.')],
      zint='Zespół stosuje stałą rutynę i sekwencje obrazkowe w łazience i szatni, stopniowo wycofuje pomoc („wygaszanie podpowiedzi"), wzmacnia każdą próbę; rodzice stosują tę samą sekwencję w domu (instruktaż koordynatora).',
      metody={0,1,2,3}, formy={0,1,3}, inne='Posiłki bez presji — nowe smaki obok znanych, stały schemat posiłku (profil sensoryczny).',
      pomoce='Sekwencje obrazkowe (mycie rąk, ubieranie), buty na rzepy, tablica osiągnięć z naklejkami, piktogramy w szatni i łazience, sztućce z grubym uchwytem.'),
   6: dict(poziom='I', trud={2,3}, wynik='Obszar „Ogólne zadania i obowiązki" — wynik 3,2 / 5 (KPOF II) i „Edukacja i zabawa" 3,2 / 5 (KPOF VIII); trudność w przejściach między aktywnościami (sprzątanie, wyjście do ogrodu) i w zabawie swobodnej (obok, nie z) — co odpowiada kwalifikacji:', chip='Poziom I — wsparcie minimalne',
      motyw='Karta „co teraz / co potem" z nagrodą po przejściu, kontrakt obrazkowy, przerwa ruchowa po zakończeniu zadania, pochwała za spokojne przejście.',
      cele=[('Cel terapeutyczny','po sygnale „za 2 minuty koniec" i pokazaniu karty „co potem" Zofia przejdzie do kolejnej aktywności w ciągu 1 minuty bez protestu w 7 na 10 przejść — do 29.01.2027; pomiar: karta dnia (stan wyjściowy: protest przy większości zmian).'),
            ('Cel społeczny','w zabawie swobodnej Zofia włączy się do zabawy tematycznej z jednym rówieśnikiem na 5 minut przy wsparciu nauczyciela współorganizującego w 3 na 5 prób — do 29.01.2027; pomiar: obserwacja zabawy w dzienniku.')],
      zint='Nauczyciele utrzymują stały rytm dnia, uprzedzają o zmianach tym samym sygnałem, prowadzą dziecko przez przejścia z kartą „co potem"; nauczyciel współorganizujący modeluje zabawę z rówieśnikiem; psycholog wprowadza zmiany stopniowo (P2).',
      metody={0,2,3}, formy={0,2,3}, inne='Stopniowe wprowadzanie nowych sytuacji (uroczystości, spacer) z obrazkiem i „próbą generalną".',
      pomoce='Plan dnia obrazkowy, karty „co teraz / co potem", minutnik / klepsydra, symbol „koniec", pojemniki z obrazkiem na klocki, checklisty sprzątania (3 kroki).'),
  },
  # realizacja zaleceń w sferach (str. 14,16,18,20,22,24): dla każdej sfery listy (orzeczenie, wopf), załącznik
  real={
   1: dict(orz=[('Stały, przewidywalny plan dnia z wizualnym wsparciem','plan obrazkowy dnia i instrukcja obrazkowa zadania — nauczyciele grupy, codziennie'),
                ('Ograniczenie hałasu i liczby bodźców w sali','słuchawki wyciszające, miejsce tyłem do okna, mniej dekoracji — nauczyciel współorganizujący'),
                ('Nauczyciel współorganizujący kształcenie','prowadzi przez zadania w 3 krokach, jedno przypomnienie zamiast wielu poleceń')],
           wopf=[('Wydłużać czas i dzielić zadanie na etapy','zadania do 5 min, plan 3 kroków, dodatkowy czas — w każdej aktywności przy stoliku'),
                 ('Wspierać uwagę — krótkie zadania, przypomnienia','jedno zadanie na raz, minutnik, pochwała po ukończeniu'),
                 ('Wykorzystywać zainteresowania dziecka','dopasowywanie i układanki jako materiał zadań; klocki jako nagroda')],
           uwagi='Odpowiedzialni: K. Wiśniewska (nauczyciel grupy), nauczyciel współorganizujący; termin: od 1.10.2026, kontrola 29.01.2027.',
           zal=('', '', '', '')),
   2: dict(orz=[('Zajęcia rewalidacyjne — trening umiejętności społecznych','TUS 1 × 30 min wg programów P1 · P2 · P3 — psycholog / nauczyciel-terapeuta; techniki przenoszone do grupy'),
                ('Współpraca z rodzicami — spójne strategie','plan PBS i system nagród ujednolicony dom–przedszkole; konsultacje co 6 tygodni'),
                ('Nauczyciel współorganizujący kształcenie','mediacja w zabawie z rówieśnikiem, prowadzenie przez przejścia (minutnik, „koniec")')],
           wopf=[('Reagować jednolicie na zachowania trudne (ABC / PBS)','wszyscy dorośli: uprzedzanie → minutnik → „koniec" → pochwała; rejestr ABC dalej prowadzony'),
                 ('Uczyć rozpoznawania i nazywania emocji','karty emocji w kręgu codziennie, „termometr emocji", historyjki — nauczyciele + psycholog'),
                 ('Trenować czekanie na kolej i współdziałanie','zabawa w parze z Antkiem 5 min dziennie z modelowaniem; gry z regułą „teraz ty — teraz ja"')],
           uwagi='Odpowiedzialni: M. Zielińska (psycholog) — TUS i plan PBS; K. Wiśniewska — realizacja w grupie; A. Nowak — koordynacja i rejestr ABC. Termin: od 1.10.2026; ocena 29.01.2027.',
           zal=('rew', 'Program rewalidacyjny 1 — „Teoria umysłu i empatia" (ToM) · 2 — „Zachowanie: model ABC i FBA" · 3 — „Kompetencje społeczno-emocjonalne"', 'Zał. 1 · 2 · 3', 'psycholog / nauczyciel-terapeuta · TUS 1 × 30 min tyg. (w ramach rewalidacji 2 × 30 min)')),
   3: dict(orz=[('Terapia integracji sensorycznej 1 × 45 min','terapeuta SI (A. Mazur) — dieta sensoryczna, przekazanie zaleceń do sali'),
                ('Przerwy sensoryczne co 20 min','przerwa proprioceptywna: tor równowagi, noszenie „ciężkich" zadań — nauczyciele grupy')],
           wopf=[('Zapewnić przerwy ruchowe i aktywność naprzemienną','zadanie przy stoliku → przerwa ruchowa → zadanie; sygnał piktogramem „przerwa"'),
                 ('Włączyć elementy SI wg potrzeb','kamizelka obciążeniowa wg SI, stopniowe oswajanie faktur, bez przymusu')],
           uwagi='Odpowiedzialni: A. Mazur (terapeuta SI), nauczyciel współorganizujący; kontrola profilu sensorycznego 05.2027.',
           zal=('', '', '', '')),
   4: dict(orz=[('Zajęcia rewalidacyjne — komunikacja i AAC','rewalidacja 1 × 30 min — logopeda; pasek komunikacyjny „proszę / pomóż / stop" w sali'),
                ('Terapia logopedyczna 2 × 30 min','ćwiczenia oddechowe i artykulacyjne, rozbudowa zdania — neurologopeda (P. Kowalczyk)'),
                ('Współpraca z rodzicami','pasek komunikacyjny i modelowanie wypowiedzi w domu — instruktaż logopedy')],
           wopf=[('Rozwijać komunikację funkcjonalną i inicjowanie kontaktu','zgłaszanie potrzeb paskiem lub słowem; inicjowanie kontaktu z jednym rówieśnikiem'),
                 ('Modelować wypowiedzi i dawać czas na odpowiedź','5–7 s na odpowiedź, powtórzenie poprawnej formy bez poprawiania'),
                 ('Wspierać rozumienie poleceń','polecenia krótkie, poparte gestem i obrazkiem — wszyscy dorośli')],
           uwagi='Odpowiedzialni: P. Kowalczyk (neurologopeda), nauczyciele grupy; termin: od 1.10.2026, ocena 29.01.2027.',
           zal=('pp', 'Program zajęć logopedycznych — rozwój mowy czynnej, artykulacja, komunikacja funkcjonalna (AAC)', 'Zał. 4', 'neurologopeda · 2 × 30 min tyg.')),
   5: dict(orz=[('Współpraca z rodzicami — spójne strategie','ta sama sekwencja obrazkowa mycia rąk i ubierania w domu — instruktaż koordynatora'),
                ('Stały, przewidywalny plan dnia','stałe rutyny w łazience i szatni, sekwencje obrazkowe na wysokości dziecka')],
           wopf=[('Stosować plany wizualne czynności','sekwencja 5 kroków mycia rąk, obrazki ubierania w szatni'),
                 ('Uczyć w sytuacjach naturalnych i wzmacniać próby','buty na rzepy przed każdym wyjściem, naklejka na tablicy osiągnięć'),
                 ('Stopniowo zmniejszać wsparcie','pomoc fizyczna → gest → obrazek → samodzielnie („wygaszanie podpowiedzi")')],
           uwagi='Odpowiedzialni: K. Wiśniewska, nauczyciel współorganizujący, rodzice; termin: od 1.10.2026; ocena 29.01.2027.',
           zal=('', '', '', '')),
   6: dict(orz=[('Stały plan dnia, uprzedzanie zmian','sygnał „za 2 minuty koniec", karta „co potem" — nauczyciele grupy'),
                ('Nauczyciel współorganizujący kształcenie','prowadzenie przez przejścia i włączanie do zabawy tematycznej z rówieśnikiem')],
           wopf=[('Stosować przewidywalny rytm dnia i uprzedzać o zmianach','ten sam sygnał u wszystkich dorosłych; zmiany planu pokazywane obrazkiem'),
                 ('Rozwijać zabawę — od równoległej do wspólnej','zabawa konstrukcyjna z jednym rówieśnikiem 5 min dziennie, potem zabawa „na niby"'),
                 ('Uczyć radzenia sobie ze zmianą','„próba generalna" przed uroczystością, historyjka społeczna o zmianie planu')],
           uwagi='Odpowiedzialni: K. Wiśniewska, nauczyciel współorganizujący, M. Zielińska (P2); termin: od 1.10.2026; ocena 29.01.2027.',
           zal=('', '', '', '')),
  },
  # cele programów P1..P3 (str. 16)
  progcele=[('P1 · Teoria umysłu i empatia — Zał. 1',['C1 — wspólne pole uwagi: Zofia podąży wzrokiem za wskazaniem dorosłego i spojrzy na przedmiot w 4 na 5 prób.','C2 — emocje: rozpozna i wskaże 3 emocje na kartach (radość, złość, smutek) w 4 na 5 prób.']),
            ('P2 · Zachowanie: model ABC i FBA — Zał. 2',['C1 — uprzedzanie: po sygnale minutnika zakończy zabawę bez krzyku w 7 na 10 sytuacji.','C2 — zachowanie zastępcze: zamiast rzucania klockami wskaże „koniec" lub „stop" na pasku w 7 na 10 sytuacji.']),
            ('P3 · Kompetencje społeczno-emocjonalne — Zał. 3',['C1 — czekanie na kolej: w grze z regułą „teraz ty — teraz ja" poczeka na swoją kolej w 3 na 5 prób.','C2 — inicjowanie: poda klocek lub powie „daj" do rówieśnika w 3 na 5 sytuacji.'])],
  # 4a / 4b
  zint_wspolne={0,1,2,3,4,5,6,7}, zint_naucz={0,1,2,3}, zint_spec={0,1,2,3},
  zint_cel='Nadrzędny cel na rok 2026/2027: Zofia bezpiecznie i przewidywalnie uczestniczy w życiu grupy — komunikuje potrzeby (mowa + pasek komunikacyjny), przechodzi między aktywnościami bez zachowań trudnych i bawi się z jednym rówieśnikiem. Wspólne strategie wszystkich dorosłych: (1) plan PBS: uprzedzanie → minutnik → „koniec" → pochwała; (2) polecenia krótkie, z gestem i obrazkiem, 5–7 s na odpowiedź; (3) dieta sensoryczna w sali (słuchawki, miejsce tyłem do okna, przerwa ruchowa co 20 min); (4) jeden system motywacyjny (First-Then, tablica wyboru); (5) wspólny zeszyt komunikacji z rodzicami i jedna karta ewaluacji celów.',
  zint4b={0:{0,1,2,3},1:{0,1,2,3},2:{0,1,2,3},3:{0,1,2,3},4:{0,1,2,3},5:{0,1,2,3}},
  zint4b_uwagi='Sygnał uprzedzania jest jeden dla wszystkich: „za 2 minuty koniec" + minutnik. Nikt nie odbiera klocków „na siłę" — czekamy na sygnał „koniec". Pochwała opisowa natychmiast („skończyłaś spokojnie"). Zeszyt komunikacji z rodzicami uzupełnia nauczyciel grupy codziennie; specjaliści wpisują zalecenia raz w tygodniu.',
  # 5 dostosowania
  dost_met={0,1,2,3,4,5,6}, dost_srod={1,2,3,4,5}, dost_inne='Bez ocen i wymagań szkolnych — dostosowujemy sposób realizacji podstawy programowej (Dz.U. 2026 poz. 378): polecenie z gestem i obrazkiem, dłuższy czas na reakcję, miejsce w kole blisko nauczyciela, sprawdzanie umiejętności przez pokazanie zamiast powiedzenia, sztućce z grubym uchwytem, słuchawki, obrazki do komunikacji. Każde dostosowanie ma źródło w barierze opisanej w WOPF (sekcja XII).',
  dost5b={0,2,3,4,5}, dost5c={0,1,2,3,4,5},
  # 6A rewalidacja: indeks wiersza -> (h/tydz., okres, realizator) ; wiersze 0..10 katalog, 11..13 = P1..P3
  rew={0:('1 × 30 min','Rok szk. 26/27','Psycholog (M. Zielińska)'),5:('1 × 30 min','Rok szk. 26/27','Neurologopeda (P. Kowalczyk)'),6:('1 × 45 min','Rok szk. 26/27','Terapeuta SI (A. Mazur)'),
       11:('w TUS · 1 × 30 min','Rok szk. 26/27','Psycholog / nauczyciel-terapeuta'),12:('w TUS · 1 × 30 min','Rok szk. 26/27','Psycholog / nauczyciel-terapeuta'),13:('w TUS · 1 × 30 min','Rok szk. 26/27','Psycholog / nauczyciel-terapeuta')},
  pp={1:('2 × 30 min','Rok szk. 26/27','Neurologopeda (P. Kowalczyk)'),7:('co 6 tyg. · 45 min','Rok szk. 26/27','Koordynator + specjaliści')},
  # 7–9
  nw='Tak', nw_h='25 h/tyg. — cały czas pobytu dziecka w grupie', asyst='Nie', poziom_wsp='II',
  icf=[('e330','przy przeciążeniu (hałas, zmiana) rzuca klockami i krzyczy — wymaga dorosłego, który uprzedzi i przeprowadzi przez przejście','zadania wymagają podziału na 3 kroki i jednego przypomnienia; bez dorosłego przerywa pracę','nie inicjuje kontaktu, nie prosi o pomoc — dorosły modeluje kontakt z rówieśnikiem'),
       ('d310 / d330','nie zgłasza dyskomfortu słowem — komunikat pojawia się jako zachowanie trudne (ABC 13/15)','rozumie polecenia dwuetapowe (8/10), ale mowa czynna 6/10 — potrzebuje modelowania i AAC','komunikacja w grupie 3/10 — potrzebuje paska komunikacyjnego i pośrednika w rozmowie'),
       ('d250 / d240','w hałasie i przy nagłej zmianie — napięcie, krzyk (3–4 × tyg.); potrzebuje kącika wyciszenia i słuchawek','radzenie sobie ze stresem ogranicza udział w zajęciach kierowanych całej grupy','wycofuje się z zabaw grupowych; uczestniczy w uroczystościach tylko przy wsparciu dorosłego')],
  rodzice={0,1,2,3,4,5,6,7},
  wsp={0:{0,1,2,3,4},1:{0,1,2,3,4},2:{0,1,2,3,4},3:{0,1,3}},
  # III
  zespol=[('Koordynator zespołu','mgr Anna Nowak','koordynacja WOPF i IPET, zwoływanie spotkań, rejestr ABC, kontakt z rodzicami co 6 tyg.'),
          ('Nauczyciel prowadzący grupę','mgr Katarzyna Wiśniewska','obserwacja w grupie (KPOF), plan obrazkowy dnia, zeszyt komunikacji z rodzicami'),
          ('Pedagog specjalny','mgr Anna Nowak','dobór dostosowań, profil biopsychospołeczny, monitorowanie celów SMART'),
          ('Psycholog','mgr Marta Zielińska','ToM, plan PBS, TUS wg P1–P3, wsparcie emocjonalne dziecka i rodziców'),
          ('Logopeda / neurologopeda','mgr Piotr Kowalczyk','zajęcia logopedyczne 2 × 30 min, rewalidacja AAC, kwestionariusz mowy'),
          ('Nauczyciel wychowania przedszkolnego','mgr Katarzyna Wiśniewska (grupa Biedronki)','realizacja podstawy programowej z dostosowaniami, sekwencje samodzielności'),
          ('Terapeuta SI / rehabilitant','mgr Agnieszka Mazur','terapia SI 1 × 45 min, profil sensoryczny, dieta sensoryczna w sali'),
          ('Nauczyciel współorganizujący kształcenie','[imię i nazwisko — po zatrudnieniu]','wsparcie w grupie przez cały czas pobytu: przejścia, zabawa z rówieśnikiem, dostosowania')],
  miejsce='Koszalin, 30.09.2026',
  ewal_data='29.01.2027 (I ocena okresowa) · 18.06.2027 (II ocena okresowa)',
  ewal_wnioski='',
  # załączniki: numer/data dla wierszy 0..19 (indeks) — pozostałe „…"
  zal={0:'Zał. 5 · harmonogram ocen: 29.01.2027, 18.06.2027 · kontrola SI 05.2027',3:'Zał. 6 · karty celów SMART sfer 1–6 (str. 13–24)',4:'Zał. 7 · protokół zespołu z 25.09.2026 (WOPF, Poziom II)',
       7:'Zał. 8 · warsztat dla rodziców (II półrocze) i konsultacje co 6 tyg.',8:'Zał. 4 · program zajęć logopedycznych (2 × 30 min)',9:'w P3 (Zał. 3) — TUS 1 × 30 min',
       14:'Zał. 9 · program rewalidacji AAC (1 × 30 min)',15:'Zał. 10 · program SI (1 × 45 min)'},
  zal_p=['Zał. 1 · 30.09.2026','Zał. 2 · 30.09.2026','Zał. 3 · 30.09.2026'],
  # IV katalogi
  kat_rew={0,1,5,6}, kat_pp={5}, kat_dost={0:{0,1,2,3,4,5},1:{0,2,3,4,5},2:{0,1,2,4,5},3:{0,1,2,3,4,5}},
  progpp=[('Logopedyczne (pomoc PP) — program zajęć logopedycznych (Zał. 4)','2 × 30 min tyg. · neurologopeda')],
  dost_wyb=[('Wsparcie wizualne: plan dnia, karta „co teraz / co potem", instrukcja obrazkowa','wszystkie aktywności; nauczyciel współorganizujący aktualizuje plan codziennie'),
            ('Komunikacja wspomagająca: pasek „proszę / pomóż / stop", PECS','w sali, szatni, ogrodzie i w domu — ten sam pasek'),
            ('Ograniczenie bodźców: słuchawki, miejsce tyłem do okna, mniej dekoracji, kącik wyciszenia','sala grupy Biedronki; słuchawki także na uroczystościach'),
            ('Uprzedzanie o zmianach: sygnał „za 2 minuty koniec", minutnik, symbol „koniec"','każde przejście między aktywnościami'),
            ('Podział zadania na 3 kroki, wydłużony czas, jedno przypomnienie','zajęcia przy stoliku, zadania kierowane'),
            ('Przerwy sensoryczne / ruchowe co 20 min','dieta sensoryczna wg profilu; tor równowagi, „ciężkie" zadania'),
            ('Polecenia krótkie, z gestem i obrazkiem; 5–7 s na odpowiedź; sprawdzanie przez pokazanie','wszyscy dorośli; również rodzice w domu'),
            ('Wsparcie nauczyciela współorganizującego; pomoc „ręka na rękę" tylko przy nowej czynności','cały czas pobytu w grupie; wygaszanie podpowiedzi')],
  # karta kontrolna — braki
  braki=[('Wpisanie nazwiska nauczyciela współorganizującego po zatrudnieniu (arkusz organizacji)','30.09.2026','dyrektor',True),
         ('Podpisy członków zespołu i rodziców po spotkaniu zespołu','30.09.2026','koordynator',False),
         ('Ujednolicenie daty urodzenia dziecka w KPOF (druk KPOF: 30.06.2015 — błąd) z metryczką','15.10.2026','K. Wiśniewska',False),
         ('Zał. 9–10: programy rewalidacji AAC i SI — dołączyć wydruki','15.10.2026','P. Kowalczyk / A. Mazur',False)],
  weryf_data='30.09.2026',
)
