# -*- coding: utf-8 -*-
"""Bank celów SMART do twierdzeń KPOF (druk KPOF-T). Każde twierdzenie ma:
   krok  — obserwowalne zachowanie (co dziecko zrobi albo powie; forma dokonana),
   syt   — sytuacja, w której to widać,
   pomiar — narzędzie pomiaru.
Poziom wsparcia zmienia WARUNKI (ile podpory), nie sam krok — jak w tabeli ToM autorki.
Kryteria: Poziom III — 3 z 5 sytuacji · 4 tygodnie; Poziom II — 4 z 5 · 8 tygodni; Poziom I — 4 z 5 · 12 tygodni."""

OBSZARY = {'I':'Uczenie się i stosowanie wiedzy','II':'Ogólne zadania i obowiązki','III':'Porozumiewanie się i mowa','IV':'Motoryka i poruszanie się','V':'Dbanie o siebie i samoobsługa','VI':'Życie domowe (czynności użyteczne)','VII':'Wzajemne kontakty i relacje','VIII':'Edukacja i zabawa','IX':'Życie w grupie i społeczności'}

# warunki wsparcia wg obszaru: (Poziom III, Poziom II, Poziom I)
WSPARCIE = {
 'I':  ('z dorosłym obok, po pokazaniu i z podpowiedzią obrazkową', 'po jednym pytaniu lub podpowiedzi obrazkowej dorosłego, samodzielnie', 'bez podpowiedzi, w naturalnej sytuacji w grupie'),
 'II': ('z dorosłym obok, z planem obrazkowym i przypomnieniem przy każdym kroku', 'z planem obrazkowym w zasięgu, po jednym przypomnieniu dorosłego', 'samodzielnie, bez planu obrazkowego i bez przypomnienia'),
 'III':('z modelowaniem wypowiedzi przez dorosłego i z podpowiedzią obrazkową lub gestem', 'po pytaniu naprowadzającym dorosłego, bez modelowania', 'z własnej inicjatywy, w rozmowie z rówieśnikiem lub dorosłym'),
 'IV': ('z asekuracją i pomocą fizyczną dorosłego', 'po pokazie dorosłego, z ustnym przypomnieniem, bez pomocy fizycznej', 'samodzielnie, w swobodnej zabawie ruchowej'),
 'V':  ('z pomocą fizyczną dorosłego „ręka na rękę” i z sekwencją obrazkową', 'z sekwencją obrazkową w zasięgu, po jednej podpowiedzi słownej', 'samodzielnie, bez podpowiedzi, w codziennej rutynie'),
 'VI': ('razem z dorosłym, krok po kroku, z podpowiedzią obrazkową', 'po jednym przypomnieniu dorosłego, z obrazkiem w zasięgu', 'samodzielnie i z własnej inicjatywy'),
 'VII':('z dorosłym jako pośrednikiem, po modelowaniu i podpowiedzi gestem', 'po jednej podpowiedzi dorosłego, samodzielnie wobec rówieśnika', 'z własnej inicjatywy, w naturalnej sytuacji z rówieśnikami'),
 'VIII':('z dorosłym obok, po wprowadzeniu do aktywności i z podpowiedzią', 'po jednym zaproszeniu lub podpowiedzi dorosłego, samodzielnie', 'samodzielnie i z własnej inicjatywy, bez wprowadzenia dorosłego'),
 'IX': ('z dorosłym obok, po uprzedzeniu obrazkiem i z podpowiedzią', 'po jednym przypomnieniu dorosłego, samodzielnie', 'samodzielnie, jak pozostałe dzieci w grupie'),
}
KRYT = {'p3':('3 z 5 sytuacji','4 tygodnie'),'p2':('4 z 5 sytuacji','8 tygodni'),'p1':('4 z 5 sytuacji','12 tygodni')}

# --- wersja A · 3–4 lata (42 twierdzenia)
A = {
 1:('skieruje wzrok na pokazywany przedmiot i pozostanie przy nauczycielu przez całą krótką prezentację','podczas zajęć w kręgu (do 3 minut)','karta obserwacji zajęć w kręgu'),
 2:('powtórzy prostą czynność lub gest pokazany przez dorosłego lub dziecko','w zabawie naśladowczej i w piosence z pokazywaniem','arkusz obserwacji zabaw naśladowczych'),
 3:('utrzyma uwagę na jednej zabawie lub zadaniu przez 5 minut','przy stoliku i w kąciku zabaw','minutnik + karta uwagi'),
 4:('posortuje przedmioty według jednej cechy (kolor albo wielkość) do dwóch pojemników','w zabawie sorterem i klockami','karta zadań manipulacyjnych'),
 5:('sięgnie po narzędzie albo poprosi o pomoc, gdy zadanie się nie udaje','w zabawie z przeszkodą (zamknięte pudełko, wysoka półka)','arkusz obserwacji zabawy'),
 6:('podejmie zabawę lub zadanie zaproponowane przez dorosłego w ciągu minuty od zaproszenia','przy przejściu do zajęć kierowanych','karta dnia'),
 7:('dokończy rozpoczętą krótką czynność (układankę, rysunek) do widocznego końca','przy stoliku, zadania do 5 minut','karta zadań'),
 8:('przejdzie do kolejnego punktu dnia (posiłek, zabawa, odpoczynek) po sygnale','przy przejściach między aktywnościami','karta przejść / plan dnia'),
 9:('zastosuje prostą zasadę zabawy lub sali (czekanie, odkładanie na miejsce) po jej przypomnieniu','w zabawie swobodnej i w kręgu','arkusz obserwacji zasad'),
 10:('uspokoi się po trudnej sytuacji w ciągu 3 minut, korzystając z proponowanej strategii (przytulenie, kącik, oddech)','po konflikcie lub frustracji','rejestr ABC / karta emocji'),
 11:('wykona proste polecenie skierowane do niego indywidualnie (jednoetapowe)','w codziennych sytuacjach w sali','karta rozumienia poleceń'),
 12:('zgłosi potrzebę (picie, toaleta, pomoc) słowem, gestem albo obrazkiem/AAC','w sytuacji potrzeby w ciągu dnia','karta komunikacji'),
 13:('zbuduje zdanie z 2–3 wyrazów zrozumiałe dla nauczyciela','w zabawie i przy oglądaniu obrazków','karta rozwoju mowy'),
 14:('odpowie na proste pytanie „kto?”, „co?”, „gdzie?” o obrazek lub sytuację','przy oglądaniu książeczki','karta rozwoju mowy'),
 15:('zareaguje właściwie na komunikat niewerbalny (gest „stop”, kiwnięcie, ton głosu)','w zabawie i przy przejściach','arkusz obserwacji komunikacji'),
 16:('przejdzie tor z przeszkodami (przekroczy, obejdzie, przeskoczy niski element) bez upadku','na zajęciach ruchowych i w ogrodzie','karta sprawności ruchowej'),
 17:('wejdzie i zejdzie po schodach krokiem naprzemiennym, trzymając poręcz','przy wyjściu do ogrodu','karta obserwacji motoryki'),
 18:('rzuci piłkę oburącz do dorosłego i podejmie próbę złapania','w zabawie piłką na dystansie 1,5 m','karta sprawności ruchowej'),
 19:('zbuduje wieżę z 6 klocków / nawlecze 5 dużych koralików / dopasuje 4 kształty do otworów','w zabawie manipulacyjnej','karta zadań manipulacyjnych'),
 20:('włączy się w zabawę ruchową lub rytmiczną i wykona pokazywane ruchy','na zajęciach muzyczno-ruchowych','arkusz obserwacji zajęć ruchowych'),
 21:('zgłosi potrzebę toalety i skorzysta z niej, prosząc o pomoc tylko przy ubraniu','w ciągu dnia w przedszkolu','karta samodzielności'),
 22:('umyje ręce według sekwencji (woda, mydło, spłukanie, wytarcie)','przed posiłkiem i po toalecie','karta samodzielności / sekwencja obrazkowa'),
 23:('zje posiłek łyżką lub widelcem i napije się z kubka bez rozlewania','podczas śniadania i obiadu','karta posiłków'),
 24:('założy lub zdejmie element ubrania (buty na rzepy, kurtkę, czapkę)','w szatni przed wyjściem i po powrocie','karta obserwacji szatni'),
 25:('zgłosi zmęczenie, głód, złe samopoczucie lub potrzebę ruchu słowem, gestem albo obrazkiem','w ciągu dnia','karta komunikacji potrzeb'),
 26:('odłoży zabawki do właściwych pojemników po sygnale sprzątania','po zabawie swobodnej','karta sprzątania'),
 27:('odłoży swoje rzeczy (kapcie, kubek, worek) na oznaczone miejsce','po przyjściu i przy wyjściu','karta samodzielności'),
 28:('wykona prostą czynność porządkową na prośbę (rozłoży serwetki, przyniesie kosz)','przed posiłkiem i po zajęciach','karta dyżurów'),
 29:('spojrzy na osobę, która do niego mówi, i zareaguje (spojrzeniem, gestem, słowem)','gdy zwraca się do niego dorosły lub dziecko','arkusz obserwacji kontaktu'),
 30:('poda zabawkę koledze albo odpowie na jego inicjatywę (uśmiech, gest, słowo)','w zabawie równoległej obok rówieśnika','arkusz obserwacji zabawy'),
 31:('pożegna się z rodzicem i włączy się w zabawę w ciągu 5 minut','rano przy rozstaniu','karta adaptacji'),
 32:('pokaże emocję w sposób czytelny (mina, gest, słowo, karta) adekwatnie do sytuacji','w sytuacjach radości, złości i smutku','karta emocji'),
 33:('podejdzie do znanego dorosłego i poprosi o pomoc słowem, gestem albo obrazkiem','gdy zadanie lub sytuacja go przerasta','karta komunikacji'),
 34:('wejdzie do sali i włączy się w rutynę grupy (powitanie, kącik) bez protestu','rano i po zmianie otoczenia','karta adaptacji'),
 35:('podejmie prostą rolę w zabawie tematycznej (karmienie misia, gotowanie) na 3 minuty','w zabawie swobodnej','arkusz obserwacji zabawy'),
 36:('pozostanie w kręgu przez całe krótkie zajęcia (do 10 minut) i wykona wspólne zadanie','na zajęciach zorganizowanych','karta zajęć zorganizowanych'),
 37:('zbuduje z klocków własną konstrukcję i nazwie ją albo pokaże','w kąciku konstrukcyjnym','arkusz obserwacji zabawy'),
 38:('włączy się w zabawę grupową prowadzoną przez nauczyciela (koło, berek, piosenka)','na zajęciach ruchowych','arkusz obserwacji zajęć'),
 39:('weźmie udział w uroczystości grupy (usiądzie z grupą, wykona wspólny gest, zaśpiewa fragment)','podczas urodzin i świąt grupy','karta uroczystości'),
 40:('wyjdzie z grupą na spacer, trzymając się pary lub liny, i wróci bez protestu','podczas wyjść poza salę','karta wyjść'),
 41:('podejmie zabawę w ogrodzie z zachowaniem zasady (pozostanie w wyznaczonym miejscu, czeka na zjeżdżalnię)','na placu zabaw','karta obserwacji placu zabaw'),
 42:('wysłucha czytanej książeczki, muzyki lub teatrzyku do końca (5 minut), pozostając na miejscu','podczas czytania i teatrzyku','karta zajęć'),
}
# --- wersja B · 5 lat (44 twierdzenia)
B = {
 1:('odpowie na 3 proste pytania o treść wysłuchanego opowiadania','po czytaniu w kręgu','karta rozumienia tekstu'),
 2:('posortuje przedmioty według dwóch cech i ułoży rytm z 3 elementów','w zabawie klockami i kartami','karta zadań matematycznych'),
 3:('przeliczy elementy zbioru do 6 i poda ich liczbę liczebnikiem głównym','w zabawie i przy nakrywaniu do stołu','karta zadań matematycznych'),
 4:('utrzyma uwagę na zadaniu kierowanym przez 15 minut, nie odchodząc od stolika','na zajęciach kierowanych','minutnik + karta uwagi'),
 5:('rozpozna i nazwie 5 wybranych liter lub cyfr','w zabawie literami i cyframi','karta obserwacji czytania'),
 6:('wykona zadanie według 3-etapowej instrukcji od początku do końca','na zajęciach kierowanych','karta zadań'),
 7:('przejdzie między aktywnościami po sygnale w ciągu minuty bez protestu','przy przejściach w ciągu dnia','karta dnia'),
 8:('poczeka na swoją kolej (do 2 minut) bez przepychania i krzyku','w grach i przy wyjściu do szatni','arkusz obserwacji zasad'),
 9:('przygotuje sobie miejsce do pracy i posprząta je po skończeniu','przy stoliku','karta samodzielności'),
 10:('poprosi o pomoc lub skorzysta z podpowiedzi dorosłego zamiast rezygnować','przy trudnym zadaniu','karta zadań'),
 11:('wypowie zdanie rozwinięte (5 i więcej wyrazów) zrozumiałe dla osoby spoza rodziny','w rozmowie i przy opisie obrazka','karta rozwoju mowy'),
 12:('opowie o zdarzeniu z przedszkola w 3 zdaniach po kolei','w rozmowie w kręgu','karta rozwoju mowy'),
 13:('podtrzyma rozmowę: odpowie i zada pytanie zwrotne','w rozmowie z dorosłym i rówieśnikiem','arkusz obserwacji rozmowy'),
 14:('wyrecytuje krótki wierszyk lub ułoży rymowankę do podanego słowa','na zajęciach językowych','karta zajęć językowych'),
 15:('użyje gestu, mimiki lub ruchu adekwatnie do treści wypowiedzi lub zabawy','w zabawie tematycznej i dramie','arkusz obserwacji komunikacji'),
 16:('wykona sekwencję ruchów: bieg, skok obunóż, czworakowanie, rzut','na torze przeszkód','karta sprawności ruchowej'),
 17:('ustoi na jednej nodze 5 sekund i przejdzie po linii stopa za stopą','na zajęciach ruchowych','karta sprawności ruchowej'),
 18:('wytnie nożyczkami po linii prostej i nawlecze 8 koralików','na zajęciach plastycznych','karta zadań manualnych'),
 19:('narysuje kształt (koło, krzyżyk) chwytem trójpalcowym bez nadmiernego nacisku','przy stoliku','karta grafomotoryki'),
 20:('przeniesie i ustawi przedmioty o różnej wielkości (kubek z wodą, klocek, koralik) bez upuszczenia','w zabawie i przy dyżurze','karta zadań manualnych'),
 21:('umyje ręce i twarz oraz wyczyści nos samodzielnie','w codziennych rutynach','karta samodzielności'),
 22:('ubierze się i rozbierze samodzielnie, w tym zapnie zamek kurtki','w szatni','karta obserwacji szatni'),
 23:('zje posiłek widelcem i łyżką, siedząc przy stole do końca posiłku','podczas posiłków','karta posiłków'),
 24:('zastosuje zasadę bezpieczeństwa (chodzi po sali, czeka na zjeżdżalnię, nie wychodzi za furtkę)','w sali i na placu zabaw','arkusz obserwacji zasad'),
 25:('zgłosi potrzebę ruchu lub odpoczynku i skorzysta z kącika wyciszenia','w ciągu dnia','karta komunikacji potrzeb'),
 26:('posprząta po sobie miejsce zabawy i pracy po sygnale','po zabawie i zajęciach','karta sprzątania'),
 27:('wykona dyżur (rozda materiały, zbierze kubki) do końca','przed posiłkiem i zajęciami','karta dyżurów'),
 28:('podzieli się wspólną zabawką po uzgodnieniu kolejności','w zabawie swobodnej','arkusz obserwacji zabawy'),
 29:('spakuje worek lub plecak i przygotuje się do wyjścia (buty, kurtka) bez pomocy','przed wyjściem na dwór','karta obserwacji szatni'),
 30:('zaprosi wybranego kolegę do zabawy i pozostanie w niej 5 minut','w zabawie swobodnej','arkusz obserwacji zabawy'),
 31:('zgłosi własny pomysł do wspólnej zabawy i przyjmie pomysł kolegi','w zabawie w małej grupie','arkusz obserwacji współdziałania'),
 32:('użyje zwrotu grzecznościowego (dzień dobry, proszę, przepraszam) w odpowiedniej sytuacji','przy powitaniu, prośbie, konflikcie','arkusz obserwacji zasad'),
 33:('nazwie emocję drugiej osoby i poda, dlaczego ją czuje','w rozmowie o sytuacji z grupy lub bajki','karta emocji'),
 34:('zaproponuje rozwiązanie sporu (losowanie, na zmianę) zamiast krzyku lub siły','w konflikcie w zabawie','rejestr ABC / arkusz konfliktów'),
 35:('włączy się w zajęcia kierowane i zrealizuje własny pomysł w zadaniu otwartym','na zajęciach kierowanych','karta zajęć'),
 36:('rozwinie zabawę tematyczną z podziałem ról przez 10 minut','w zabawie swobodnej','arkusz obserwacji zabawy'),
 37:('wykona pracę plastyczną lub budowlę według własnego pomysłu i wprowadzi ulepszenie','w kąciku plastycznym i konstrukcyjnym','karta wytworów'),
 38:('zaśpiewa piosenkę z grupą i wykona układ taneczny','na zajęciach muzycznych','karta zajęć muzycznych'),
 39:('wykona polecenie skierowane do całej grupy bez indywidualnego powtórzenia','na zajęciach i przy przejściach','karta rozumienia poleceń'),
 40:('powie, do której grupy należy, i weźmie udział w zwyczaju grupy (piosenka, rytuał)','w kręgu porannym','karta zajęć'),
 41:('odegra uzgodnioną rolę w występie lub uroczystości','podczas przygotowań i występu','karta uroczystości'),
 42:('weźmie udział w przygotowaniu wyjścia i w zabawie sezonowej na powietrzu','podczas wyjść i zabaw sezonowych','karta wyjść'),
 43:('powie, co mu się podobało w teatrzyku, koncercie lub na wystawie','po wydarzeniu kulturalnym','karta zajęć'),
 44:('poda swoje imię i nazwisko na pytanie dorosłego','w codziennych sytuacjach','karta obserwacji'),
}
# --- wersja C · 6 lat (44 twierdzenia)
C = {
 1:('ułoży historyjkę obrazkową z 4 obrazków i objaśni kolejność zdarzeń','na zajęciach językowych','karta rozumienia tekstu'),
 2:('przeczyta 5 prostych wyrazów lub krótki napis w sali','w zabawie napisami','karta obserwacji czytania'),
 3:('odwzoruje 5 liter po śladzie i zapisze 3 litery samodzielnie, planując ruch','przy stoliku','karta grafomotoryki'),
 4:('odczyta cyfry do 10 i rozwiąże proste dodawanie lub odejmowanie na konkretach','w zabawie i sytuacji użytkowej (sklep)','karta zadań matematycznych'),
 5:('sprawdzi swoje przypuszczenie w doświadczeniu (co pływa, co jest cięższe) i poda wynik','na zajęciach badawczych','karta doświadczeń'),
 6:('ułoży plan zadania w 3 krokach i wykona je po kolei','w zadaniu konstrukcyjnym lub plastycznym','karta zadań'),
 7:('pracuje samodzielnie przez 20 minut zajęć kierowanych bez przypomnień','na zajęciach kierowanych','minutnik + karta uwagi'),
 8:('po przegranej w grze pozostanie w niej i weźmie udział w kolejnej rundzie','w grach z regułami','arkusz obserwacji gier'),
 9:('poda, co było wczoraj, co jest dziś i co będzie jutro, korzystając z planu tygodnia','w kręgu porannym','karta zajęć'),
 10:('doprowadzi trudne zadanie do końca, stosując znaną strategię (przerwa, oddech, prośba o wskazówkę)','przy zadaniu wymagającym wysiłku','karta zadań'),
 11:('wypowie zdanie poprawnie pod względem gramatycznym i artykulacyjnym (bez zamian głosek)','w rozmowie i opowiadaniu','karta rozwoju mowy'),
 12:('podzieli wyraz 3–4-głoskowy na głoski i złoży wyraz z podanych głosek','na zajęciach przygotowujących do czytania','karta analizy i syntezy'),
 13:('opowie własną historię lub przekształci zakończenie bajki w 4 zdaniach','na zajęciach językowych','karta rozwoju mowy'),
 14:('przedstawi swoją opinię i uzasadni ją jednym argumentem wobec grupy','w rozmowie w kręgu','arkusz obserwacji rozmowy'),
 15:('wykona proste polecenie w języku obcym (stand up, sit down, clap)','na zajęciach języka obcego','karta zajęć językowych'),
 16:('wykona ćwiczenie koordynacyjne (podskoki z klaskaniem, rzut do celu) i utrzyma równowagę w chodzie po ławeczce','na zajęciach ruchowych','karta sprawności ruchowej'),
 17:('utrzyma prawidłową postawę przy stoliku przez 15 minut (stopy na podłodze, plecy oparte)','przy pracy przy stoliku','karta obserwacji postawy'),
 18:('kreśli litery chwytem pisarskim z kontrolowanym naciskiem, bez odrywania i przerywania linii','przy ćwiczeniach grafomotorycznych','karta grafomotoryki'),
 19:('zapnie 3 guziki i zawiąże sznurowadło','w szatni','karta obserwacji szatni'),
 20:('wykona improwizację ruchową do muzyki i zatrzyma się na sygnał','na zajęciach muzyczno-ruchowych','karta zajęć muzycznych'),
 21:('zapnie suwak, guziki i zawiąże buty samodzielnie','w szatni','karta samodzielności'),
 22:('nałoży sobie posiłek i zje go sztućcami, zachowując porządek przy stole','podczas posiłków','karta posiłków'),
 23:('zadba o higienę z własnej inicjatywy (umyje ręce bez przypomnienia) i powie, po co to robi','w codziennych rutynach','karta samodzielności'),
 24:('przejdzie przez jezdnię po sygnale i w wyznaczonym miejscu oraz zastosuje zasadę w autobusie','podczas wyjść poza teren','karta wyjść'),
 25:('zgłosi zmęczenie lub przeciążenie i wskaże sytuację niebezpieczną (obcy, gorące, ostre)','w ciągu dnia i podczas wyjść','karta komunikacji potrzeb'),
 26:('nakryje do stołu dla grupy, nałoży posiłek i posprząta po posiłku','podczas posiłków','karta dyżurów'),
 27:('wykona dyżur (podlewanie, rozdawanie, porządkowanie) bez przypomnienia','w ciągu tygodnia','karta dyżurów'),
 28:('utrzyma porządek w swojej półce i szufladzie przez tydzień','w sali','karta samodzielności'),
 29:('podleje rośliny i zadba o kącik przyrody według harmonogramu','w kąciku przyrody','karta dyżurów'),
 30:('weźmie udział w głosowaniu grupy i zaakceptuje decyzję niezgodną z własną','przy wyborze zabawy lub tematu','arkusz obserwacji współdziałania'),
 31:('zastosuje zasadę grupy i uwzględni potrzebę innego dziecka (zamiana, ustąpienie)','w zabawie i w kręgu','arkusz obserwacji zasad'),
 32:('przeprosi po konflikcie i nazwie konsekwencję swojego zachowania','po konflikcie','rejestr ABC / arkusz konfliktów'),
 33:('pomoże koledze w zadaniu lub pocieszy smutne dziecko (podejdzie, zaproponuje pomoc)','w zabawie i na zajęciach','arkusz obserwacji kontaktu'),
 34:('wskaże wypowiedź lub zachowanie, które mogłoby kogoś skrzywdzić, i zaproponuje inne','w rozmowie o sytuacji w grupie','karta emocji'),
 35:('wykona zadanie w zespole 3–4 dzieci i zaprezentuje wspólny efekt','na zajęciach zespołowych','karta zajęć zespołowych'),
 36:('doprowadzi zadanie edukacyjne do efektu i powie, z czego jest zadowolony','na zajęciach kierowanych','karta zadań'),
 37:('zagra w grę z regułami do końca, przestrzegając zasad i kolejności','w grach planszowych i ruchowych','arkusz obserwacji gier'),
 38:('rozpozna monety, „zapłaci” w zabawie w sklep i policzy resztę na konkretach','w zabawie w sklep','karta zadań matematycznych'),
 39:('znajdzie odpowiedź na pytanie w książce, obrazku lub u innej osoby i przekaże ją grupie','na zajęciach badawczych','karta zajęć'),
 40:('powie, do jakiej rodziny, grupy i miejscowości należy, i wyjaśni, co to znaczy','w rozmowie w kręgu','karta zajęć'),
 41:('wymieni nazwę kraju i stolicy oraz rozpozna 3 symbole narodowe','na zajęciach o Polsce i przy uroczystościach','karta zajęć'),
 42:('poda imię, nazwisko i adres oraz wskaże, komu wolno je podać','w rozmowie z dorosłym','karta obserwacji'),
 43:('posegreguje odpady do właściwych pojemników i zakręci wodę po umyciu rąk','w codziennych rutynach','karta obserwacji'),
 44:('opisze pracę 3 zawodów i odegra rolę zawodową w zabawie','w zabawie tematycznej','arkusz obserwacji zabawy'),
}
WERSJE = {'A':('3–4 lata',A),'B':('5 lat',B),'C':('6 lat',C)}
