/* Katalog pomocy dydaktycznych PCTP Koszalin — treść merytoryczna.
   Skład: generuj.js                                                        */

const KATEGORIE = [
  { id: "A", nazwa: "Emocje i regulacja", hex: "#E8450A",
    opis: "Materiały do rozpoznawania, nazywania i regulowania emocji — od zeszytu dla nastolatka po planszę do powieszenia w sali." },
  { id: "B", nazwa: "Komunikacja i AAC", hex: "#2E6FB7",
    opis: "Dla dziecka, które nie mówi, mówi niefunkcjonalnie albo traci mowę w stresie. Karty, tablice i sygnały." },
  { id: "C", nazwa: "Organizacja przestrzeni i dnia", hex: "#0D7D5C",
    opis: "Plan dnia, Kącik Ciszy, oznaczenia sali — dostosowania, które działają, zanim pojawi się trudność." },
  { id: "D", nazwa: "Dokumentacja i diagnoza", hex: "#2D1B69",
    opis: "Szablony ekosystemu EduPlaner 2026: WOPF, IPET, raporty, arkusze obserwacji i analizy zachowań." },
];

const POMOCE = [
  /* ── A · Emocje i regulacja ────────────────────────────────────────── */
  { kod: "A1", kat: "A", polecane: true,
    nazwa: "Zeszyt „Kolorowy Świat Emocji” — część 1",
    podtytul: "Zeszyt ćwiczeń dla nastolatka ze spektrum autyzmu",
    opis: "Pięć emocji, pięć kolorów, jedna droga za każdym razem. Osiem stron w każdym rozdziale, zawsze w tej samej kolejności — przewidywalność jest tu elementem terapeutycznym, nie ozdobnikiem.",
    postac: "Plik PDF do samodzielnego wydruku", format: "58 stron A4 + okładka, pełny kolor, 7,5 MB",
    dlaKogo: ["Nastolatek w spektrum autyzmu", "Uczeń, któremu trudno nazwać emocje", "Zajęcia rewalidacyjne i pomoc psychologiczno-pedagogiczna"],
    jakUzywac: ["Jeden rozdział to osiem stron — do zrobienia w dzień albo rozłożenia na tydzień",
                "Nie trzeba iść po kolei; otwiera się kolor, który pasuje do dzisiaj",
                "Drukuj tyle egzemplarzy, ilu masz uczniów — w zakresie licencji"],
    pasuje: ["Szkolenie A1 — Kolorowy Świat Emocji", "Pomoce A3, A4, A5, A6"],
    licencja: "indywidualna · placówkowa · szkoleniowa" },

  { kod: "A2", kat: "A", polecane: true,
    nazwa: "Konspekty zajęć 3–4 lata",
    podtytul: "Siedem konspektów z 21 celami SMART",
    opis: "Przedszkolna wersja metody pięciu kolorów. Cykl na dwanaście tygodni, z bohaterem Misiem Kolorkiem, który zmienia chustkę razem z emocją. Każdy konspekt ma trzy cele SMART — po jednym na poziom wsparcia I, II i III.",
    postac: "PDF do druku oraz Word do edycji", format: "22 strony A4",
    dlaKogo: ["Nauczyciele wychowania przedszkolnego", "Nauczyciele współorganizujący w przedszkolu", "Psycholodzy i pedagodzy przedszkolni"],
    jakUzywac: ["Zajęcia po 20 minut, jeden kolor na tydzień",
                "Cele SMART przenosi się wprost do sekcji III IPET-u",
                "Karta obserwacji na końcu jest gotowym załącznikiem do ewaluacji"],
    pasuje: ["Szkolenie A2 — Emocje w przedszkolu", "Pomoce A3, A4, A6, C1, C2"],
    licencja: "indywidualna · placówkowa · szkoleniowa" },

  { kod: "A3", kat: "A",
    nazwa: "Karty emocji",
    podtytul: "Sześć kart do wycięcia i zalaminowania",
    opis: "Pomoc komunikacyjna na chwile, gdy trudno powiedzieć słowami. Pięć emocji plus karta „Nie wiem jeszcze”: coś czuję, ale nie umiem tego nazwać, potrzebuję chwili.",
    postac: "PDF do wydruku i laminowania", format: "arkusz A4, karty 7 × 9 cm",
    dlaKogo: ["Dziecko niemówiące i korzystające z AAC", "Mutyzm wybiórczy", "Każde dziecko w sytuacji przeciążenia"],
    jakUzywac: ["Zalaminuj i wepnij do książki komunikacyjnej albo powieś na sznurku przy stanowisku",
                "Pokazanie karty jest pełnoprawną odpowiedzią — nie proś o dopowiedzenie słowem",
                "Wersja powiększona A5 sprawdza się w pracy grupowej"],
    pasuje: ["Szkolenia A1, A2, D1", "Pomoce A1, A2, B1"],
    licencja: "w zakresie licencji zeszytu albo osobno" },

  { kod: "A4", kat: "A",
    nazwa: "Termometr emocji",
    podtytul: "Skala 1–5 do codziennego zaznaczania",
    opis: "Najprostsze narzędzie pomiaru w całym zestawie. Dziecko zakreśla liczbę: 1 — prawie wcale, 5 — bardzo dużo. Po tygodniu widać wzorzec, po miesiącu — dane do ewaluacji.",
    postac: "PDF do wydruku, wersja jednorazowa i suchościeralna", format: "A4 pionowo, wariant A5 na biurko",
    dlaKogo: ["Wszystkie grupy wiekowe", "Zajęcia indywidualne i grupowe", "Praca w domu z rodzicem"],
    jakUzywac: ["Wprowadź jako stały rytuał — ta sama pora każdego dnia",
                "Wersję suchościeralną zalaminuj i używaj z pisakiem",
                "Zebrane wyniki są dowodem postępu do oceny efektywności IPET-u"],
    pasuje: ["Szkolenia A1, A2, B4", "Pomoce A1, A2, A7, D5"],
    licencja: "placówkowa" },

  { kod: "A5", kat: "A",
    nazwa: "Plan na trudny dzień",
    podtytul: "Plakat pięciu kroków do powieszenia",
    opis: "Zatrzymaj się · nazwij kolor · oddychaj · zrób jedną rzecz z listy · powiedz komuś. Zawsze w tej samej kolejności. Plus pola na trzy telefony, umówiony sygnał przerwy i miejsce na ochłonięcie.",
    postac: "PDF do wydruku", format: "A3 na ścianę, A4 do teczki, A5 do plecaka",
    dlaKogo: ["Uczeń z zaburzeniami lękowymi i regulacji", "Dziecko w spektrum autyzmu", "Sala lekcyjna i pokój dziecka"],
    jakUzywac: ["Wypełnijcie pola razem, na spokojnie — zanim będą potrzebne",
                "Powieś tam, gdzie dziecko naprawdę spojrzy, nie tam, gdzie jest miejsce",
                "Wersję A5 dziecko nosi przy sobie"],
    pasuje: ["Szkolenia A1, C1, C2", "Pomoce A1, C2, C3"],
    licencja: "placówkowa" },

  { kod: "A6", kat: "A",
    nazwa: "Gra planszowa „Ścieżka Kolorów”",
    podtytul: "Plansza, zasady i 24 karty do wycięcia",
    opis: "Gra o emocjach dla 2–4 osób. Na każdym polu gracz mówi jednym zdaniem, kiedy ostatnio czuł tę emocję. Wpisana zasada „pas”: zawsze można nie odpowiedzieć, bez tłumaczenia się.",
    postac: "PDF do wydruku i wycięcia", format: "plansza A3 lub 2 × A4, karty 6 × 9 cm",
    dlaKogo: ["Grupa 2–4 dzieci", "Zajęcia TUS i rozwijające kompetencje emocjonalno-społeczne", "Świetlica i praca w rodzinie"],
    jakUzywac: ["Dwie wersje trudności: nazwanie koloru albo opowiedzenie sytuacji",
                "Gramy do końca, nie do wygranej — chodzi o rozmowę, nie o wyścig",
                "Wersja przedszkolna: plansza skrócona do trzech kolorów"],
    pasuje: ["Szkolenia A1, A2, A3", "Pomoce A1, A2, A3"],
    licencja: "w zakresie licencji zeszytu albo osobno" },

  { kod: "A7", kat: "A",
    nazwa: "Paleta emocji — plakat grupowy",
    podtytul: "Pięć kolorów, jedna ściana, cała grupa",
    opis: "Plakat, na którym każde dziecko zaznacza naklejką swój kolor dnia. Porównanie pierwszego i ostatniego tygodnia cyklu to najprostszy dowód efektywności, jaki da się załączyć do dokumentacji.",
    postac: "PDF do wydruku wielkoformatowego", format: "A2 albo A1",
    dlaKogo: ["Grupa przedszkolna i klasa", "Świetlica", "Gabinet terapeutyczny"],
    jakUzywac: ["Zaznaczanie w porannym kręgu, codziennie o tej samej porze",
                "Naklejki w kolorze albo pisak suchościeralny",
                "Zachowaj zdjęcie palety z pierwszego tygodnia — będzie punktem odniesienia"],
    pasuje: ["Szkolenia A2, B4", "Pomoce A2, A4, D5"],
    licencja: "placówkowa" },

  /* ── B · Komunikacja i AAC ─────────────────────────────────────────── */
  { kod: "B1", kat: "B", polecane: true,
    nazwa: "Zestaw startowy kart komunikacyjnych",
    podtytul: "Dwadzieścia cztery symbole na pierwszy miesiąc",
    opis: "Od czego zacząć AAC, gdy dziecko nie mówi, a zespół nie ma doświadczenia. Prośba, odmowa, przerwa, pomoc, toaleta, jedzenie, picie, boli — plus emocje i podstawowe czynności dnia.",
    postac: "PDF do wydruku i laminowania", format: "3 arkusze A4, symbole 5 × 5 cm",
    dlaKogo: ["Dziecko niemówiące", "Mowa niefunkcjonalna albo zawodząca w stresie", "Dziecko po urazie i z afazją"],
    jakUzywac: ["Zacznij od czterech kart, nie od wszystkich dwudziestu czterech",
                "Modeluj: dorosły też pokazuje kartę, nie tylko mówi",
                "Te same symbole muszą być w placówce i w domu"],
    pasuje: ["Szkolenie D1 — AAC pierwsze kroki", "Pomoce B2, B3, B4, C1"],
    licencja: "placówkowa" },

  { kod: "B2", kat: "B",
    nazwa: "Karty „Przerwa” i „Potrzebuję pomocy”",
    podtytul: "Dwie karty, które gaszą najwięcej sytuacji",
    opis: "Dwa sygnały, których brak najczęściej kończy się wybuchem albo ucieczką z sali. Dziecko podaje kartę zamiast krzyku — i dostaje przerwę bez negocjowania.",
    postac: "PDF do wydruku, wersja na smycz i na ławkę", format: "karty 6 × 8 cm oraz 10 × 14 cm",
    dlaKogo: ["Uczeń z przeciążeniem sensorycznym", "Dziecko w spektrum autyzmu", "Klasa ogólnodostępna"],
    jakUzywac: ["Ustal z zespołem, że karta jest honorowana zawsze — bez pytania „dlaczego”",
                "Karta musi być w zasięgu ręki, nie w szufladzie nauczyciela",
                "Wprowadź w spokojnej sytuacji, nigdy po raz pierwszy w trakcie wybuchu"],
    pasuje: ["Szkolenia C1, C2, D1", "Pomoce A5, B1, C2, C3"],
    licencja: "placówkowa" },

  { kod: "B3", kat: "B",
    nazwa: "Tablica komunikacyjna",
    podtytul: "Wzór do wydruku i rozbudowy",
    opis: "Układ pól, logika rozmieszczenia symboli i miejsce na rozbudowę w czasie. Wzór, na którym zespół uczy się myśleć o AAC, zanim zdecyduje się na płatny program.",
    postac: "PDF do wydruku i laminowania", format: "A3 na stół, A4 do teczki",
    dlaKogo: ["Dziecko korzystające z AAC", "Logopedzi i terapeuci", "Nauczyciele współorganizujący"],
    jakUzywac: ["Dokładaj pola stopniowo — nie od razu pełną tablicę",
                "Zachowaj stałe miejsce symbolu; przesunięcie kosztuje tygodnie nauki",
                "Wersję A4 dziecko ma przy sobie na wyjściach"],
    pasuje: ["Szkolenie D1 — AAC pierwsze kroki", "Pomoce B1, B2, B4"],
    licencja: "placówkowa" },

  { kod: "B4", kat: "B",
    nazwa: "Karta „Nie wiem jeszcze”",
    podtytul: "Sygnał, którego najczęściej brakuje",
    opis: "„Coś czuję, ale nie umiem tego nazwać. Potrzebuję chwili.” Karta dla dziecka, które nie potrafi wskazać emocji — i dla dorosłego, który przestaje wtedy dopytywać.",
    postac: "PDF do wydruku i laminowania", format: "karta 7 × 9 cm, zestaw 6 sztuk na arkuszu",
    dlaKogo: ["Dziecko w spektrum autyzmu", "Aleksytymia", "Każdy, kto potrzebuje czasu na odpowiedź"],
    jakUzywac: ["Wprowadź razem z kartami emocji, nie później",
                "Po pokazaniu karty przerwij pytania — to jest jej cały sens",
                "Wróć do tematu po kilkunastu minutach, jeśli dziecko będzie gotowe"],
    pasuje: ["Szkolenia A1, A2, D1", "Pomoce A3, B1"],
    licencja: "w zakresie licencji zeszytu albo osobno" },

  /* ── C · Organizacja przestrzeni i dnia ────────────────────────────── */
  { kod: "C1", kat: "C", polecane: true,
    nazwa: "Plan dnia obrazkowy",
    podtytul: "Sześćdziesiąt piktogramów i listwa do zawieszenia",
    opis: "Najskuteczniejsze pojedyncze dostosowanie dla dziecka w spektrum. Lęk rośnie, gdy nie wiadomo, co będzie; maleje, gdy plan wisi na wysokości wzroku i można go dotknąć.",
    postac: "PDF do wydruku i laminowania", format: "60 piktogramów 6 × 6 cm + listwa 100 cm",
    dlaKogo: ["Grupa przedszkolna i klasa", "Dziecko w spektrum autyzmu", "Dziecko z zaburzeniami lękowymi"],
    jakUzywac: ["Powieś na wysokości wzroku dziecka, nie dorosłego",
                "Zdejmowanie obrazka po zakończonej czynności jest częścią metody",
                "Zmianę planu zapowiadaj, przekładając piktogram — nie tylko słowem"],
    pasuje: ["Szkolenia A2, C1, C3", "Pomoce C2, C3, C4"],
    licencja: "placówkowa" },

  { kod: "C2", kat: "C",
    nazwa: "Kącik Ciszy — zestaw do skompletowania",
    podtytul: "Lista wyposażenia, oznaczenia i zasady",
    opis: "Nie mebel, tylko procedura. Zestaw zawiera listę wyposażenia do skompletowania na miejscu, gotowe oznaczenia i kartę zasad — kto może wejść, na jak długo i kiedy wraca.",
    postac: "PDF: oznaczenia, karta zasad, lista zakupowa", format: "oznaczenia A4 i A5, lista A4",
    dlaKogo: ["Sala przedszkolna i lekcyjna", "Świetlica", "Gabinet i sala doświadczania świata"],
    jakUzywac: ["Umieść tak, żeby dziecko doszło bez przechodzenia przez całą salę",
                "Kącik nie jest karą — nigdy nie odsyłaj tam za zachowanie",
                "Pokaż go wszystkim dzieciom, zanim komukolwiek będzie potrzebny"],
    pasuje: ["Szkolenia A2, C1, C2", "Pomoce A5, B2, C3"],
    licencja: "placówkowa" },

  { kod: "C3", kat: "C",
    nazwa: "Sygnał STOP",
    podtytul: "Krążek i piktogram dla całego zespołu",
    opis: "Jeden sygnał, ten sam u wszystkich dorosłych w sali — także u pomocy nauczyciela i woźnej. Podniesiony krążek znaczy: zatrzymujemy się i liczymy do trzech.",
    postac: "PDF do wydruku i laminowania", format: "krążek Ø 15 cm, piktogram A5",
    dlaKogo: ["Grupa przedszkolna i klasa", "Dziecko z trudnościami regulacji", "Świetlica i stołówka"],
    jakUzywac: ["Ustalcie sygnał na radzie, zanim wejdzie do sali",
                "Ćwiczcie w spokojnej sytuacji, w formie zabawy",
                "Sygnał musi być zawsze taki sam — inaczej przestaje działać"],
    pasuje: ["Szkolenia A2, C2", "Pomoce A5, C2"],
    licencja: "placówkowa" },

  { kod: "C4", kat: "C",
    nazwa: "Oznaczenia sali",
    podtytul: "Etykiety na szafki, kąciki i strefy",
    opis: "Obrazek plus podpis na każdej szafce, półce i strefie. Dziecko, które nie czyta, odkłada rzecz na miejsce; dziecko, które czyta, uczy się słowa przy okazji.",
    postac: "PDF do wydruku i laminowania", format: "etykiety 8 × 5 cm i 15 × 10 cm, 80 wzorów",
    dlaKogo: ["Sala przedszkolna", "Klasa I–III", "Świetlica i biblioteka"],
    jakUzywac: ["Ten sam symbol na szafce dziecka, na jego półce i w planie dnia",
                "Etykiety strefowe powieś na wysokości wzroku dziecka",
                "Puste wzory pozwalają dopisać własne nazwy"],
    pasuje: ["Szkolenia C1, C3", "Pomoce C1, C2"],
    licencja: "placówkowa" },

  /* ── D · Dokumentacja i diagnoza ───────────────────────────────────── */
  { kod: "D1", kat: "D", polecane: true,
    nazwa: "Szablon WOPF",
    podtytul: "Wielospecjalistyczna ocena poziomu funkcjonowania",
    opis: "Dokument w układzie dziewięciu obszarów KSzOF, z miejscem na kody ICF, profil sensoryczny i mocne strony. Struktura prowadzi zespół tak, żeby z oceny dało się wyprowadzić cele.",
    postac: "Word (.docx) do edycji", format: "A4, marka PCTP, Arial",
    dlaKogo: ["Zespoły opracowujące IPET", "Pedagodzy specjalni, psycholodzy, logopedzi", "Poradnie psychologiczno-pedagogiczne"],
    jakUzywac: ["Wypełniaj obszarami, nie chronologicznie — łatwiej utrzymać spójność",
                "Opis funkcjonalny zamiast etykiety diagnostycznej",
                "Zakończ przejściem do celów: każdy obszar z trudnością powinien mieć cel w IPET-cie"],
    pasuje: ["Szkolenie B1 — WOPF krok po kroku", "Pomoce D2, D3, D4"],
    licencja: "placówkowa" },

  { kod: "D2", kat: "D", polecane: true,
    nazwa: "Szablon IPET",
    podtytul: "Dziewięć sekcji rzymskich z tabelą celów SMART",
    opis: "Pełny indywidualny program edukacyjno-terapeutyczny: kwalifikacja poziomu wsparcia, cele SMART w modelu KSzOF + ICF, dostosowania, model ABC, organizacja zajęć, współpraca, ewaluacja i zatwierdzenie — z podstawą prawną przy każdej sekcji.",
    postac: "Word (.docx) do edycji", format: "A4, marka PCTP, Arial",
    dlaKogo: ["Zespoły opracowujące IPET", "Nauczyciele współorganizujący", "Dyrektorzy nadzorujący dokumentację"],
    jakUzywac: ["Poziom wsparcia zaznaczasz w sekcji II — cele dobierasz do niego",
                "Kolumna podstawy prawnej jest wypełniona; sprawdź tylko aktualność",
                "Sekcję ewaluacji przygotuj od razu, nie na koniec roku"],
    pasuje: ["Szkolenia B2, B3, B4", "Pomoce D1, D3, D5"],
    licencja: "placówkowa" },

  { kod: "D3", kat: "D",
    nazwa: "Raport Ucznia",
    podtytul: "Synteza dla dyrekcji i rodzica",
    opis: "To, czego nie da się przekazać, podając komuś dwudziestostronicowy IPET. Jedna do dwóch stron: kim jest dziecko, nad czym pracujemy, co się udało, co dalej.",
    postac: "Word (.docx) do edycji", format: "A4, 1–2 strony",
    dlaKogo: ["Rozmowy z rodzicem", "Dyrekcja i organ prowadzący", "Przekazanie ucznia do innej placówki"],
    jakUzywac: ["Pisz językiem, którym mówisz do rodzica — bez kodów ICF",
                "Zawsze zaczynaj od mocnych stron",
                "Aktualizuj po każdej ocenie efektywności"],
    pasuje: ["Szkolenia B1, B4, D2", "Pomoce D1, D2, D4"],
    licencja: "placówkowa" },

  { kod: "D4", kat: "D",
    nazwa: "Baza Uczniów",
    podtytul: "Ewidencja i zestawienia dla całej placówki",
    opis: "Arkusz, który odpowiada na pytania dyrektora bez przeglądania teczek: ilu uczniów z orzeczeniami, na jakich poziomach wsparcia, ile godzin rewalidacji, kiedy kończą się terminy.",
    postac: "Excel (.xlsx)", format: "arkusz z zestawieniami i filtrami",
    dlaKogo: ["Dyrektorzy i wicedyrektorzy", "Koordynatorzy pomocy psychologiczno-pedagogicznej", "Sekretariaty"],
    jakUzywac: ["Jedno miejsce prawdy — wszystkie inne dokumenty ciągną dane stąd",
                "Ustaw przypomnienia o terminach ważności orzeczeń",
                "Dane wrażliwe: przechowuj zgodnie z polityką ochrony danych placówki"],
    pasuje: ["Szkolenie D2 — EduPlaner 2026", "Pomoce D1, D2, D3"],
    licencja: "placówkowa" },

  { kod: "D5", kat: "D",
    nazwa: "Karta obserwacji celów SMART",
    podtytul: "Dowód postępu zbierany na bieżąco",
    opis: "Tabela, w której po każdych zajęciach wpisuje się jedną liczbę. Po semestrze karta jest gotowym załącznikiem do oceny efektywności — bez odtwarzania roku z pamięci.",
    postac: "PDF do wydruku oraz Word do edycji", format: "A4, jedna karta na dziecko",
    dlaKogo: ["Prowadzący zajęcia specjalistyczne i rewalidacyjne", "Nauczyciele współorganizujący", "Zespoły oceniające efektywność"],
    jakUzywac: ["Wypełniaj bezpośrednio po zajęciach, nie zbiorczo raz w miesiącu",
                "Zapisuj wynik w formie ułamka: 4/5, 3/5 — tak jak brzmi kryterium celu",
                "Kolumna uwag jest ważniejsza niż liczba, gdy wynik odbiega od normy"],
    pasuje: ["Szkolenia A2, B2, B4", "Pomoce A2, A4, D2"],
    licencja: "placówkowa" },

  { kod: "D6", kat: "D",
    nazwa: "Arkusz ABC",
    podtytul: "Analiza zachowań trudnych",
    opis: "Poprzednik — Zachowanie — Konsekwencja. Arkusz wymusza opis obserwowalny zamiast interpretacji, dzięki czemu dwie osoby zapiszą to samo zdarzenie tak samo.",
    postac: "PDF do wydruku", format: "A4, dziesięć zdarzeń na arkuszu",
    dlaKogo: ["Nauczyciele i wychowawcy", "Pedagodzy specjalni i psycholodzy", "Zespoły ośrodków i świetlic"],
    jakUzywac: ["Wypełniaj bezpośrednio po zdarzeniu, nie na koniec dnia",
                "Opisuj to, co widać i słychać — bez „był zdenerwowany”",
                "Dziesięć zdarzeń wystarczy zwykle do postawienia hipotezy funkcji"],
    pasuje: ["Szkolenie C2 — Zachowania trudne", "Pomoce D2, D5"],
    licencja: "placówkowa" },

  { kod: "D7", kat: "D",
    nazwa: "Arkusz kwalifikacyjny do poziomu wsparcia",
    podtytul: "Decyzja zespołu z podstawą prawną",
    opis: "Ścieżka decyzyjna prowadząca zespół przez pytania, które trzeba zadać, zanim padnie odpowiedź: poziom I, II czy III. Z formami pomocy i podstawą prawną przy każdym poziomie.",
    postac: "PDF do wydruku oraz Word do edycji", format: "A4, dwie strony",
    dlaKogo: ["Zespoły opracowujące IPET", "Dyrektorzy", "Koordynatorzy pomocy psychologiczno-pedagogicznej"],
    jakUzywac: ["Wypełniajcie na posiedzeniu zespołu, wspólnie — nie z góry",
                "Uzasadnienie decyzji zapisz zdaniem, nie samym zaznaczeniem",
                "Przy zmianie poziomu w trakcie roku wypełnij nowy arkusz"],
    pasuje: ["Szkolenie B3 — Trzy poziomy wsparcia", "Pomoce D1, D2"],
    licencja: "placówkowa" },
];

const ZESTAWY = [
  { kod: "Z-PRZ", nazwa: "Zestaw przedszkolny", sklad: ["A2", "A3", "A4", "A6", "C1", "C2", "C3"],
    opis: "Wszystko, czego potrzebuje grupa przedszkolna na cały cykl dwunastu tygodni: konspekty, karty, gra, plan dnia, Kącik Ciszy i sygnał STOP." },
  { kod: "Z-EMO", nazwa: "Zestaw emocji — komplet", sklad: ["A1", "A3", "A4", "A5", "A6", "A7", "B4"],
    opis: "Pełna linia materiałów do pracy z emocjami: zeszyt dla nastolatka, karty, termometr, plan na trudny dzień, gra i paleta grupowa." },
  { kod: "Z-AAC", nazwa: "Zestaw komunikacyjny", sklad: ["A3", "B1", "B2", "B3", "B4", "C1"],
    opis: "Start w AAC dla placówki, która nie ma jeszcze doświadczenia: karty startowe, tablica, sygnały przerwy i plan dnia." },
  { kod: "Z-DOK", nazwa: "Zestaw dokumentacyjny EduPlaner", sklad: ["D1", "D2", "D3", "D4", "D5", "D6", "D7"],
    opis: "Komplet szablonów ekosystemu EduPlaner 2026 — od oceny funkcjonalnej po ewidencję całej placówki." },
];

module.exports = { KATEGORIE, POMOCE, ZESTAWY };
