/* Konspekty „Kolorowy Świat Emocji — Przedszkole 3–4 lata"
   Treść merytoryczna oddzielona od składu (generuj.js).
   PCTP Koszalin · ekosystem EduPlaner2026-MJ-PCTP                      */

const BRAND = {
  fiolet: "2D1B69", pomarancz: "E8450A", zielony: "0D7D5C", czerwony: "B8350D",
  bezowy: "C47A10", atrament: "1A1A2E", szept: "5B5B72",
  tloFiolet: "F4F2FA", tloPomarancz: "FDF1EC", tloZielony: "EDF6F2",
  linia: "D9D5E8", biel: "FFFFFF",
};

const KOLORY_EMOCJI = {
  zolty:     { hex: "F2B21A", nazwa: "żółty" },
  niebieski: { hex: "2E6FB7", nazwa: "niebieski" },
  czerwony:  { hex: "D33B2C", nazwa: "czerwony" },
  rozowy:    { hex: "E0619B", nazwa: "różowy" },
  szary:     { hex: "6E7681", nazwa: "szary" },
  paleta:    { hex: "2D1B69", nazwa: "pięć kolorów" },
};

/* ── Poziomy wsparcia — definicje wspólne dla wszystkich konspektów ───── */
const POZIOMY = [
  { rzymska: "I", nazwa: "Poziom I — wsparcie w bieżącej pracy grupy",
    kto: "Dziecko realizuje podstawę programową razem z grupą. Wystarcza dostosowanie metod, form i warunków prowadzone przez nauczyciela wychowania przedszkolnego.",
    formy: [
      "bieżąca praca z dzieckiem podczas zajęć — dostosowanie metod i form",
      "wsparcie wychowawcze i opiekuńcze udzielane na bieżąco",
      "modyfikacja warunków zewnętrznych i organizacyjnych (miejsce w kręgu, oświetlenie, poziom hałasu)",
    ],
    podstawa: "§ 6 ust. 1 pkt 1 i pkt 2 Rozp. MEN o warunkach organizowania kształcenia specjalnego" },
  { rzymska: "II", nazwa: "Poziom II — zajęcia specjalistyczne w małej grupie",
    kto: "Dziecko potrzebuje dodatkowo pracy w grupie do 4 osób, prowadzonej przez specjalistę: psychologa, pedagoga specjalnego lub logopedę.",
    formy: [
      "zajęcia rozwijające kompetencje emocjonalno-społeczne (2 × 20 min tygodniowo)",
      "zajęcia logopedyczne — gdy trudność dotyczy komunikacji",
      "zajęcia korekcyjno-kompensacyjne",
      "porady i konsultacje dla rodziców",
    ],
    podstawa: "§ 6 ust. 1 pkt 3 Rozp. MEN o warunkach organizowania kształcenia specjalnego w zw. z § 6 ust. 2 Rozp. MEN z 09.08.2017 r. o pomocy psychologiczno-pedagogicznej" },
  { rzymska: "III", nazwa: "Poziom III — wsparcie indywidualne i rewalidacja",
    kto: "Dziecko potrzebuje pracy jeden na jeden oraz stałej obecności dorosłego w grupie. Cele zapisuje się z uwzględnieniem podpowiedzi i modelowania.",
    formy: [
      "zajęcia rewalidacyjne indywidualne (2 × 30 min tygodniowo)",
      "wsparcie nauczyciela współorganizującego kształcenie",
      "pomoc nauczyciela / asystent dziecka",
    ],
    podstawa: "§ 6 ust. 1 pkt 5 oraz § 7 ust. 2 Rozp. MEN o warunkach organizowania kształcenia specjalnego" },
];

/* ── Siedem konspektów ────────────────────────────────────────────────── */
const KONSPEKTY = [
  {
    nr: 1, kolor: "paleta", czas: "20 minut",
    temat: "Pięć kolorów Misia Kolorka — poznajemy emocje",
    podtytul: "Zajęcia wprowadzające do cyklu",
    celOgolny: "Zbudowanie w grupie wspólnego kodu porozumiewania się o emocjach: pięć kolorów, pięć emocji. Dziecko dostaje narzędzie, którym może pokazać, jak się czuje, zanim nauczy się to powiedzieć.",
    celeOperacyjne: [
      "wskazuje pięć kolorów: żółty, niebieski, czerwony, różowy, szary",
      "łączy trzy podstawowe kolory z emocją: żółty — radość, niebieski — smutek, czerwony — złość",
      "pokazuje kartę w wybranym kolorze w odpowiedzi na pytanie „jak się dzisiaj czujesz?”",
      "uczestniczy w zabawie ruchowej z chustą animacyjną",
    ],
    smart: [
      { poziom: "I", kszof: 3, obszar: "Porozumiewanie się", icf: "d310 · b152",
        cel: "Do końca 2. tygodnia cyklu dziecko podczas porannego kręgu wskaże palcem kolor odpowiadający emocji nazwanej przez nauczyciela (żółty — radość, niebieski — smutek, czerwony — złość) w 4 na 5 prób, bez podpowiedzi dorosłego.",
        forma: "Bieżąca praca w grupie; poranny krąg codziennie", kryterium: "4/5 prób w dwóch kolejnych obserwacjach",
        podstawa: "§ 6 ust. 1 pkt 1" },
      { poziom: "II", kszof: 7, obszar: "Kontakty i relacje międzyludzkie", icf: "d137 · b1520",
        cel: "Do końca 4. tygodnia cyklu dziecko na zajęciach w grupie do 4 osób dopasuje kartę koloru do zdjęcia twarzy pokazującej daną emocję w 4 na 5 prób, po najwyżej jednej podpowiedzi wzrokowej.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 prób na trzech kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 1, obszar: "Uczenie się i stosowanie wiedzy", icf: "d130 · d137",
        cel: "Do końca 8. tygodnia cyklu dziecko w pracy indywidualnej z nauczycielem dopasuje 3 karty kolorów do 3 zdjęć twarzy, korzystając z podpowiedzi gestowej i modelowania, w 3 na 5 prób.",
        forma: "Zajęcia rewalidacyjne indywidualne 2 × 30 min tygodniowo; wsparcie nauczyciela współorganizującego", kryterium: "3/5 prób w dwóch kolejnych sesjach",
        podstawa: "§ 6 ust. 1 pkt 5 oraz § 7 ust. 2" },
    ],
    metody: ["pogadanka z ilustracją", "pokaz i naśladowanie", "zabawa dydaktyczna z kartami", "zabawa ruchowa z chustą animacyjną", "metoda ośrodków zainteresowań"],
    formy: ["praca z całą grupą w kręgu", "praca indywidualna z kartą koloru"],
    srodki: ["pluszowy Miś Kolorek", "pięć kart kolorów formatu A5 (żółta, niebieska, czerwona, różowa, szara)", "zdjęcia twarzy dzieci pokazujących emocje — powiększone karty emocji z zeszytu", "chusta animacyjna", "pudełko z przedmiotami w pięciu kolorach", "bębenek"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Nauczyciel wita dzieci piosenką „Kolorowe dzień dobry”. Sadza Misia Kolorka na środku kręgu.", d: "Dzieci siadają w kręgu, witają Misia machnięciem ręki." },
      { czas: "4 min", etap: "Wprowadzenie — pudełko kolorów", n: "Wyjmuje z pudełka po jednym przedmiocie w każdym kolorze i nazywa kolor. Pyta: „Co jeszcze jest żółte?”", d: "Dzieci nazywają kolor, podają skojarzenia, dotykają przedmiotów." },
      { czas: "7 min", etap: "Część główna — kolor to emocja", n: "Pokazuje kartę koloru i zdjęcie twarzy. Mówi krótko: „Żółty to radość. Radość to kiedy jest nam dobrze”. Powtarza dla niebieskiego i czerwonego. Różowy i szary tylko nazywa — bez rozwijania.", d: "Dzieci powtarzają nazwę emocji, pokazują minę, dopasowują kartę do zdjęcia." },
      { czas: "4 min", etap: "Zabawa ruchowa — kolorowa chusta", n: "Podnosi chustę. Na hasło koloru dzieci w ubraniu w tym kolorze przebiegają pod chustą.", d: "Dzieci biegają pod chustą, reagują na hasło koloru." },
      { czas: "2 min", etap: "Domknięcie — jak się dziś czuję", n: "Podaje każdemu dziecku po kolei zestaw kart. Pyta: „Jak się dzisiaj czujesz?”", d: "Dziecko podnosi wybraną kartę. Nie musi tłumaczyć wyboru." },
    ],
    dostosowania: [
      "Spektrum autyzmu — pokaż plan zajęć w pięciu obrazkach na początku; zapowiedz, że zajęcia skończą się piosenką.",
      "Dziecko niemówiące / AAC — karta koloru jest pełnoprawną odpowiedzią; nie wymagaj słowa.",
      "Nadwrażliwość słuchowa — bębenek zastąp klaśnięciem; uprzedź przed każdym dźwiękiem.",
      "Niepełnosprawność intelektualna — pracuj tylko na trzech kolorach (żółty, niebieski, czerwony).",
      "ADHD — skróć część główną do 5 minut, zabawę ruchową przesuń na środek zajęć.",
      "Nieśmiałość / mutyzm — pozwól odpowiedzieć przez podanie karty nauczycielowi do ręki, nie na forum.",
    ],
    ewaluacja: ["Ile dzieci samodzielnie wskazało kolor przy pytaniu o samopoczucie?", "Które kolory dzieci nazywały spontanicznie, a które wymagały podpowiedzi?", "Czy zabawa ruchowa nie przeciążyła grupy — jak wyglądał powrót do kręgu?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje, próbuje radzić sobie z ich przeżywaniem",
      "Obszar II, pkt 6 — rozróżnia emocje i uczucia przyjemne i nieprzyjemne",
      "Obszar III, pkt 9 — komunikuje się z dziećmi i osobami dorosłymi, wykorzystując komunikaty werbalne i pozawerbalne",
      "Obszar I, pkt 5 — uczestniczy w zabawach ruchowych",
    ],
    notatka: "Nie wprowadzaj wszystkich pięciu emocji naraz. Trzylatek utrzyma trzy. Różowy i szary na tych zajęciach tylko się pojawiają — jako kolory, nie jako pojęcia. Wrócą w konspektach 5 i 6.",
  },

  {
    nr: 2, kolor: "zolty", czas: "20 minut",
    temat: "Żółty dzień Misia Kolorka — co mnie cieszy",
    podtytul: "Radość · kolor żółty",
    celOgolny: "Rozpoznawanie radości u siebie i u innych po sygnałach z twarzy i ciała oraz nazywanie sytuacji, które radość wywołują.",
    celeOperacyjne: [
      "pokazuje radość mimiką: uśmiech, uniesione policzki",
      "wskazuje na ilustracji dziecko, któremu jest wesoło",
      "podaje jedną sytuację, w której było mu wesoło",
      "reaguje ruchem na muzykę w zabawie „żółty taniec”",
    ],
    smart: [
      { poziom: "I", kszof: 3, obszar: "Porozumiewanie się", icf: "d330 · d350",
        cel: "Do końca 3. tygodnia cyklu dziecko w kręgu podsumowującym poda jedną rzecz, która sprawiła mu dzisiaj radość — słowem albo przez wskazanie obrazka — na 4 z 5 zajęć.",
        forma: "Bieżąca praca w grupie; krąg podsumowujący na koniec dnia", kryterium: "4/5 zajęć w ciągu dwóch tygodni",
        podstawa: "§ 6 ust. 1 pkt 1" },
      { poziom: "II", kszof: 7, obszar: "Kontakty i relacje międzyludzkie", icf: "d335 · b1520",
        cel: "Do końca 5. tygodnia cyklu dziecko na zajęciach w małej grupie pokaże radość samą mimiką na polecenie „pokaż radość” w 4 na 5 prób.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 prób na dwóch kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 1, obszar: "Uczenie się i stosowanie wiedzy", icf: "d137 · d177",
        cel: "Do końca 8. tygodnia cyklu dziecko w pracy indywidualnej wybierze spośród dwóch kart (radość / smutek) tę, która pasuje do przyjemnego zdarzenia opowiedzianego przez nauczyciela, w 3 na 5 prób, z podpowiedzią słowną.",
        forma: "Zajęcia rewalidacyjne indywidualne 2 × 30 min tygodniowo", kryterium: "3/5 prób w dwóch kolejnych sesjach",
        podstawa: "§ 6 ust. 1 pkt 5" },
    ],
    metody: ["opowiadanie z ilustracją", "pokaz mimiki i naśladowanie przed lustrem", "zabawa muzyczno-ruchowa", "praca plastyczna — stemplowanie"],
    formy: ["praca w kręgu", "praca w parach przy lustrze", "praca indywidualna przy stoliku"],
    srodki: ["Miś Kolorek w żółtej chustce", "duże lustro albo lusterka indywidualne", "żółte wstążki dla każdego dziecka", "ilustracje dzieci w sytuacjach radosnych", "żółta farba, gąbki do stemplowania, kartony", "nagranie wesołej melodii"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Wita dzieci piosenką. Pokazuje Misia w żółtej chustce: „Dzisiaj Miś jest żółty. Wiecie, co to znaczy?”", d: "Dzieci witają się, odpowiadają, rozpoznają kolor." },
      { czas: "5 min", etap: "Opowiadanie o żółtym dniu", n: "Opowiada krótką historię: Miś dostał balonik, bawił się z przyjacielem, było mu ciepło w brzuszku. Pyta: „Po czym poznaliście, że Misiowi jest wesoło?”", d: "Dzieci słuchają, wskazują znaki na ilustracji: uśmiech, podniesione ręce." },
      { czas: "5 min", etap: "Lustro radości", n: "Rozdaje lusterka. Prosi: „Pokaż radosną minę. Zobacz, co robią Twoje usta i oczy”.", d: "Dzieci ćwiczą mimikę przed lustrem, porównują miny z kolegą." },
      { czas: "4 min", etap: "Żółty taniec", n: "Włącza muzykę, rozdaje żółte wstążki. Zatrzymuje muzykę — dzieci zastygają w radosnej minie.", d: "Dzieci tańczą ze wstążkami, na przerwę w muzyce zastygają." },
      { czas: "3 min", etap: "Domknięcie — moja żółta kartka", n: "Rozdaje kartony. Prosi o odbicie dłoni żółtą farbą i pyta każde dziecko, co dziś je ucieszyło.", d: "Dziecko stempluje dłoń i podaje jedną rzecz — słowem albo wskazaniem obrazka." },
    ],
    dostosowania: [
      "Spektrum autyzmu — nie wymagaj kontaktu wzrokowego przy lustrze; wystarczy patrzenie na własne odbicie.",
      "Nadwrażliwość dotykowa — zamiast farby zaproponuj naklejkę albo kredkę.",
      "Dziecko niemówiące / AAC — pytanie „co Cię ucieszyło” zamień na wybór z trzech obrazków.",
      "ADHD — żółty taniec przesuń przed lustro radości; ruch pierwszy, skupienie potem.",
      "Niepełnosprawność ruchowa — wstążkę przymocuj do nadgarstka opaską.",
      "Nadwrażliwość słuchowa — muzyka cicho, uprzedź przed włączeniem, zaproponuj słuchawki wygłuszające.",
    ],
    ewaluacja: ["Ile dzieci pokazało radość samą mimiką, bez podpowiedzi?", "Czy dzieci podawały własne sytuacje, czy powtarzały za innymi?", "Które dziecko potrzebowało wyboru obrazkowego zamiast odpowiedzi słownej?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje",
      "Obszar II, pkt 4 — przedstawia swoje emocje i uczucia, używając charakterystycznych dla dziecka form wyrazu",
      "Obszar IV, pkt 2 — wyraża swoje rozumienie świata za pomocą prac plastycznych",
      "Obszar I, pkt 5 — uczestniczy w zabawach ruchowych, w tym rytmicznych i muzycznych",
    ],
    notatka: "Radość jest najłatwiejsza do rozpoznania i dlatego zaczynamy od niej. Jeśli dziecko nie potrafi nazwać własnej radości, pozwól mu wskazać cudzą na ilustracji — to ten sam krok rozwojowy, tylko o poziom niżej.",
  },

  {
    nr: 3, kolor: "niebieski", czas: "20 minut",
    temat: "Niebieski Miś — kiedy jest mi smutno",
    podtytul: "Smutek · kolor niebieski",
    celOgolny: "Oswojenie smutku jako emocji dozwolonej i przemijającej oraz nauczenie dziecka jednego konkretnego sposobu poproszenia o wsparcie.",
    celeOperacyjne: [
      "wskazuje na ilustracji dziecko, któremu jest smutno",
      "nazywa dwa znaki smutku: opuszczone kąciki ust, spuszczona głowa",
      "podaje jeden sposób pocieszenia kolegi",
      "pokazuje niebieską kartę, gdy jest mu smutno",
    ],
    smart: [
      { poziom: "I", kszof: 5, obszar: "Dbanie o siebie i samodzielność", icf: "d240 · b1521",
        cel: "Do końca 4. tygodnia cyklu dziecko w sytuacji smutku (rozstanie z rodzicem, przegrana w zabawie) podejdzie do nauczyciela albo pokaże niebieską kartę, zamiast płaczu bez komunikatu, w 3 na 5 sytuacji.",
        forma: "Bieżąca praca w grupie; wsparcie wychowawcze udzielane na bieżąco", kryterium: "3/5 sytuacji odnotowanych w karcie obserwacji",
        podstawa: "§ 6 ust. 1 pkt 1 i pkt 2" },
      { poziom: "II", kszof: 7, obszar: "Kontakty i relacje międzyludzkie", icf: "d710 · b152",
        cel: "Do końca 6. tygodnia cyklu dziecko na zajęciach w małej grupie wskaże na ilustracji dziecko, któremu jest smutno, i poda jeden sposób pocieszenia (przytulenie, podanie zabawki), w 4 na 5 prób.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 prób na dwóch kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 3, obszar: "Porozumiewanie się", icf: "d360 · d240",
        cel: "Do końca 10. tygodnia cyklu dziecko poda dorosłemu kartę „Przytul” jako sygnał potrzeby bliskości w 3 na 5 sytuacji trudnych, przy wsparciu nauczyciela współorganizującego.",
        forma: "Zajęcia rewalidacyjne indywidualne; wsparcie nauczyciela współorganizującego przez cały dzień", kryterium: "3/5 sytuacji w ciągu dwóch tygodni",
        podstawa: "§ 6 ust. 1 pkt 5 i pkt 6" },
    ],
    metody: ["opowiadanie terapeutyczne", "analiza ilustracji", "drama — scenka pocieszania", "relaksacja przy muzyce"],
    formy: ["praca w kręgu", "praca w parach", "praca indywidualna z kartą"],
    srodki: ["Miś Kolorek w niebieskiej chustce", "ilustracje sytuacji smutnych bliskich doświadczeniu 3-latka", "karty „Przytul”, „Chcę być sam”, „Pomóż mi”", "niebieska tkanina — „kałuża smutku”", "spokojna muzyka", "chusteczki"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Wita dzieci. Pokazuje Misia w niebieskiej chustce z opuszczoną głową: „Miś jest dziś niebieski. Zgubił swojego balonika”.", d: "Dzieci witają się, zauważają zmianę w postawie Misia." },
      { czas: "5 min", etap: "Opowiadanie — Miś zgubił balonik", n: "Opowiada krótko o stracie. Nie pociesza na siłę: „Misiowi jest smutno. Smutek jest w porządku. On minie”.", d: "Dzieci słuchają, mogą przytulić Misia, opowiadają o własnych stratach." },
      { czas: "5 min", etap: "Znaki smutku", n: "Pokazuje ilustracje. Pyta: „Skąd wiesz, że jej jest smutno? Co robią usta? Co robi głowa?”", d: "Dzieci wskazują znaki na ilustracji i pokazują je na sobie." },
      { czas: "4 min", etap: "Scenka — jak pocieszyć", n: "Zaprasza pary: jedno dziecko jest smutne, drugie pociesza. Modeluje: przytulenie, podanie zabawki, usiądnięcie obok.", d: "Dzieci odgrywają scenkę w parach, zamieniają się rolami." },
      { czas: "3 min", etap: "Domknięcie — kałuża smutku", n: "Rozkłada niebieską tkaninę. „Możemy zostawić tu smutek i wrócić do zabawy”. Włącza spokojną muzykę.", d: "Dzieci kładą dłoń na tkaninie, wstają i wracają do kręgu." },
    ],
    dostosowania: [
      "Dziecko po stracie lub w kryzysie rodzinnym — uprzedź rodzica o temacie zajęć; nie wywołuj dziecka do opowiadania.",
      "Spektrum autyzmu — scenkę pocieszania modeluj najpierw na Misiu, nie na dziecku; dotyk tylko za zgodą.",
      "Nadwrażliwość dotykowa — pocieszenie przez podanie zabawki zamiast przytulenia jest równie dobre.",
      "Dziecko niemówiące / AAC — karta „Przytul” trafia do książki komunikacyjnej i zostaje z dzieckiem po zajęciach.",
      "Mutyzm wybiórczy — nie proś o wypowiedź na forum; wystarczy wskazanie na ilustracji.",
      "Niepełnosprawność intelektualna — zostań przy dwóch znakach smutku (usta, głowa), pomiń resztę.",
    ],
    ewaluacja: ["Czy dziecko odróżniło smutek od złości na ilustracjach?", "Ile dzieci samodzielnie zaproponowało sposób pocieszenia?", "Czy któreś dziecko zareagowało na temat silniej, niż zakładano — czy potrzebna jest rozmowa z rodzicem?"],
    podstawaProgramowa: [
      "Obszar II, pkt 6 — rozróżnia emocje przyjemne i nieprzyjemne, ma świadomość, że przeżywają je wszyscy ludzie",
      "Obszar II, pkt 7 — szuka wsparcia w sytuacjach trudnych dla niego emocjonalnie",
      "Obszar II, pkt 8 — wczuwa się w emocje i uczucia osób z najbliższego otoczenia",
      "Obszar III, pkt 8 — obdarza uwagą inne dzieci i osoby dorosłe",
    ],
    notatka: "Najczęstszy błąd na tych zajęciach to pocieszanie zamiast towarzyszenia. Zdanie „nie płacz, nic się nie stało” unieważnia emocję. Zamiast tego: „widzę, że jest Ci smutno. Jestem obok”.",
  },

  {
    nr: 4, kolor: "czerwony", czas: "20 minut",
    temat: "Czerwony Miś — co robię, kiedy się złoszczę",
    podtytul: "Złość · kolor czerwony",
    celOgolny: "Oddzielenie złości od zachowania krzywdzącego oraz wyćwiczenie jednego prostego sposobu zatrzymania się, zanim złość zamieni się w uderzenie.",
    celeOperacyjne: [
      "nazywa dwa znaki złości w ciele: zaciśnięte pięści, gorąca twarz",
      "zatrzymuje się na hasło „STOP — Miś liczy do trzech”",
      "wykonuje ćwiczenie oddechowe „Balonik”",
      "wie, gdzie w sali jest Kącik Ciszy",
    ],
    smart: [
      { poziom: "I", kszof: 2, obszar: "Ogólne zadania i obowiązki", icf: "d250 · b1521",
        cel: "Do końca 4. tygodnia cyklu dziecko w sytuacji złości (odebranie zabawki, odmowa dorosłego) zatrzyma się na sygnał nauczyciela „STOP — Miś liczy do trzech” i policzy razem z nim do trzech, w 3 na 5 sytuacji.",
        forma: "Bieżąca praca w grupie; sygnał stosowany przez wszystkich dorosłych w sali", kryterium: "3/5 sytuacji odnotowanych w karcie obserwacji",
        podstawa: "§ 6 ust. 1 pkt 1" },
      { poziom: "II", kszof: 5, obszar: "Dbanie o siebie i samodzielność", icf: "d570 · b1521",
        cel: "Do końca 6. tygodnia cyklu dziecko na zajęciach w małej grupie wykona ćwiczenie oddechowe „Balonik” (wdech nosem, długi wydech ustami) trzy razy pod rząd na polecenie, w 4 na 5 prób.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 prób na dwóch kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 2, obszar: "Ogólne zadania i obowiązki", icf: "d250 · d720",
        cel: "Do końca 10. tygodnia cyklu dziecko na sygnał dorosłego przejdzie do wyznaczonego Kącika Ciszy zamiast reakcji agresywnej, w 3 na 5 sytuacji, z podpowiedzią gestową i fizycznym towarzyszeniem dorosłego.",
        forma: "Wsparcie nauczyciela współorganizującego przez cały dzień; zajęcia rewalidacyjne indywidualne", kryterium: "3/5 sytuacji w ciągu dwóch tygodni",
        podstawa: "§ 6 ust. 1 pkt 5 oraz § 7 ust. 2" },
    ],
    metody: ["opowiadanie z elementem problemowym", "modelowanie zachowania przez nauczyciela", "ćwiczenia oddechowe", "zabawa z elementem odreagowania"],
    formy: ["praca w kręgu", "praca indywidualna z gniotkiem", "praca z całą grupą w zabawie ruchowej"],
    srodki: ["Miś Kolorek w czerwonej chustce", "czerwony krążek — sygnał STOP", "baloniki (po jednym na dziecko)", "gniotki lub piłeczki sensoryczne", "gazety do zgniatania", "wyznaczony Kącik Ciszy z poduszką"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Wita dzieci. Pokazuje Misia z zaciśniętymi łapkami: „Miś jest dziś czerwony. Ktoś zabrał mu klocki bez pytania”.", d: "Dzieci witają się, zauważają napięte łapki Misia." },
      { czas: "4 min", etap: "Złość wolno czuć", n: "Mówi krótko i wprost: „Złość wolno czuć. Nie wolno nią bić. Zaraz nauczymy się, co robić zamiast bicia”.", d: "Dzieci słuchają, pokazują, jak wygląda zła mina." },
      { czas: "4 min", etap: "Znaki złości w ciele", n: "Pokazuje na sobie: zaciśnięte pięści, gorąca twarz, szybki oddech. Prosi o powtórzenie.", d: "Dzieci zaciskają pięści, dotykają policzków, sprawdzają, czy są ciepłe." },
      { czas: "5 min", etap: "STOP i Balonik", n: "Podnosi czerwony krążek: „STOP — Miś liczy do trzech”. Potem rozdaje baloniki i ćwiczy wdech nosem, długi wydech ustami.", d: "Dzieci zatrzymują się na sygnał, liczą do trzech, nadmuchują baloniki." },
      { czas: "4 min", etap: "Domknięcie — Kącik Ciszy", n: "Pokazuje Kącik Ciszy: „Tu można pójść, kiedy jest za dużo. Zawsze można wrócić”. Zaprasza każde dziecko, by weszło i wyszło.", d: "Dzieci po kolei wchodzą do kącika, siadają na chwilę i wracają do kręgu." },
    ],
    dostosowania: [
      "Zaburzenia zachowania — sygnał STOP wprowadź najpierw w spokojnej sytuacji, nigdy po raz pierwszy w trakcie wybuchu.",
      "Spektrum autyzmu — Kącik Ciszy oznacz obrazkiem; pokaż go przed zajęciami, nie w trakcie eskalacji.",
      "Nadwrażliwość słuchowa — baloniki mogą pęknąć; zaproponuj dmuchanie przez słomkę do wody.",
      "ADHD — dodaj etap zgniatania gazet po ćwiczeniu oddechowym; ciało musi coś zrobić z energią.",
      "Dziecko niemówiące / AAC — karta „Potrzebuję przerwy” wisi przy Kąciku Ciszy i jest równoważna z prośbą.",
      "Nadwrażliwość dotykowa — nie dotykaj dziecka w złości bez zapowiedzi; prowadź gestem.",
    ],
    ewaluacja: ["Ile dzieci zatrzymało się na sygnał STOP przy pierwszej próbie?", "Czy ćwiczenie oddechowe faktycznie obniżyło napięcie, czy tylko zajęło czas?", "Czy Kącik Ciszy jest w miejscu, do którego dziecko dojdzie samo, bez przechodzenia przez całą salę?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje, próbuje radzić sobie z ich przeżywaniem",
      "Obszar II, pkt 2 — szanuje emocje swoje i innych osób",
      "Obszar III, pkt 7 — respektuje prawa i obowiązki swoje oraz innych osób",
      "Obszar I, pkt 5 — uczestniczy w zabawach ruchowych",
    ],
    notatka: "Sygnał STOP działa tylko wtedy, gdy jest zawsze taki sam i gdy używają go wszyscy dorośli w sali — także woźna i pomoc nauczyciela. Ustalcie go na radzie przed rozpoczęciem cyklu.",
  },

  {
    nr: 5, kolor: "rozowy", czas: "20 minut",
    temat: "Różowy Miś — kiedy chcę się schować",
    podtytul: "Wstyd · kolor różowy",
    celOgolny: "Rozpoznanie wstydu jako uczucia, które przychodzi przy innych ludziach i mija, oraz zbudowanie w grupie bezpieczeństwa po pomyłce.",
    celeOperacyjne: [
      "wskazuje na ilustracji postać, która zasłania twarz albo chowa się",
      "nazywa dwa znaki wstydu: czerwone policzki, spuszczony wzrok",
      "wypowiada jedno zdanie na forum grupy, pozostając przy stoliku",
      "kończy zadanie po pomyłce, zamiast je porzucić",
    ],
    smart: [
      { poziom: "I", kszof: 3, obszar: "Porozumiewanie się", icf: "d310 · b152",
        cel: "Do końca 5. tygodnia cyklu dziecko wskaże na ilustracji postać, która zasłania twarz lub chowa się, i nazwie to „wstyd” albo „chce się schować”, w 4 na 5 prób.",
        forma: "Bieżąca praca w grupie; praca na materiale obrazkowym", kryterium: "4/5 prób w dwóch kolejnych obserwacjach",
        podstawa: "§ 6 ust. 1 pkt 1" },
      { poziom: "II", kszof: 7, obszar: "Kontakty i relacje międzyludzkie", icf: "d350 · b1266",
        cel: "Do końca 7. tygodnia cyklu dziecko na zajęciach w małej grupie wypowie na forum jedno zdanie (imię i ulubiona zabawka), pozostając przy stoliku, na 4 z 5 zajęć.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 zajęć w ciągu trzech tygodni",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 8, obszar: "Edukacja przedszkolna — rola dziecka w grupie", icf: "d240 · b1266",
        cel: "Do końca 10. tygodnia cyklu dziecko w obecności nauczyciela współorganizującego dokończy rozpoczęte zadanie po popełnieniu błędu, zamiast wycofać się, w 3 na 5 sytuacji, po jednorazowym komunikacie „to nic, próbujemy dalej”.",
        forma: "Wsparcie nauczyciela współorganizującego; zajęcia rewalidacyjne indywidualne", kryterium: "3/5 sytuacji odnotowanych w karcie obserwacji",
        podstawa: "§ 6 ust. 1 pkt 5" },
    ],
    metody: ["opowiadanie terapeutyczne", "analiza ilustracji", "zabawa w chowanego z chustą", "modelowanie reakcji na pomyłkę"],
    formy: ["praca w kręgu", "praca w parach", "praca indywidualna"],
    srodki: ["Miś Kolorek w różowej chustce", "chusta do zasłaniania", "ilustracje postaci zasłaniających twarz", "lusterka", "prosta układanka, w której łatwo się pomylić", "różowe naklejki"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Wita dzieci. Pokazuje Misia zasłaniającego łapkami pysk: „Miś przewrócił się przy wszystkich. Teraz się chowa”.", d: "Dzieci witają się, zauważają zasłonięty pysk Misia." },
      { czas: "5 min", etap: "Kiedy chce się schować", n: "Opowiada o pomyłce Misia. Mówi: „To się nazywa wstyd. Przychodzi, gdy ktoś nas widzi. I zawsze mija”.", d: "Dzieci słuchają, pokazują, jak się chowają, gdy im wstyd." },
      { czas: "4 min", etap: "Znaki wstydu", n: "Pokazuje ilustracje i lusterka: czerwone policzki, wzrok w dół, głowa w ramionach.", d: "Dzieci sprawdzają w lusterku, dotykają policzków, naśladują postawę." },
      { czas: "4 min", etap: "Zabawa — schowaj się i wróć", n: "Zasłania chustą dziecko, które chce. Po chwili odsłania: „Byłeś schowany. Wróciłeś. Nic się nie stało”.", d: "Chętne dzieci chowają się pod chustą i wracają do kręgu." },
      { czas: "4 min", etap: "Domknięcie — pomyłka jest w porządku", n: "Układa układankę i celowo myli się na oczach dzieci. Mówi głośno: „Pomyliłam się. To nic, próbuję dalej”. Rozdaje układanki.", d: "Dzieci układają, mylą się, powtarzają zdanie za nauczycielem, kończą zadanie." },
    ],
    dostosowania: [
      "Mutyzm wybiórczy — cel z poziomu II realizuj etapami: najpierw szept do nauczyciela, potem do jednego kolegi, dopiero na końcu na forum.",
      "Spektrum autyzmu — zabawa w chowanego pod chustą tylko dla chętnych; zapowiedz z góry, że chusta zostanie zdjęta po trzech klaśnięciach.",
      "Nieśmiałość — dziecko może odpowiedzieć „przez Misia”: mówi do pluszaka, nie do grupy.",
      "Dziecko niemówiące / AAC — zdanie na forum zastąp pokazaniem swojego zdjęcia i karty z ulubioną zabawką.",
      "Niepełnosprawność intelektualna — zostań przy jednym znaku wstydu (czerwone policzki).",
      "Zaburzenia lękowe — nie zasłaniaj dziecka chustą bez wyraźnej zgody; niech samo ją na siebie naciągnie.",
    ],
    ewaluacja: ["Czy dzieci odróżniły wstyd od strachu?", "Ile dzieci wypowiedziało zdanie na forum bez zachęty?", "Jak grupa zareagowała na pomyłkę nauczyciela — czy pojawił się śmiech i jak został domknięty?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje",
      "Obszar II, pkt 6 — rozróżnia emocje i uczucia przyjemne i nieprzyjemne",
      "Obszar III, pkt 1 — przejawia poczucie własnej wartości jako osoby",
      "Obszar III, pkt 5 — ocenia swoje zachowanie w kontekście podjętych czynności i zadań",
    ],
    notatka: "Wstyd to emocja samoświadomościowa — u 3-latka dopiero się pojawia, u 4-latka jest już czytelna. Na tym etapie pracujemy na poziomie rozpoznania obrazkowego, nie autorefleksji. Nie oczekuj, że dziecko opowie o własnym wstydzie.",
  },

  {
    nr: 6, kolor: "szary", czas: "20 minut",
    temat: "Szary Miś — czego się boję",
    podtytul: "Strach · kolor szary",
    celOgolny: "Zmniejszenie napięcia przed nieznanym przez dwie konkretne rzeczy: uprzedzenie planem obrazkowym i jedno ćwiczenie uziemiające.",
    celeOperacyjne: [
      "nazywa dwa znaki strachu: szybkie bicie serca, ściśnięty brzuch",
      "ogląda plan obrazkowy przed nową sytuacją i wskazuje, co będzie pierwsze",
      "wykonuje ćwiczenie „Rozejrzyj się” — wymienia trzy rzeczy, które widzi",
      "wie, gdzie leży jego przedmiot uspokajający",
    ],
    smart: [
      { poziom: "I", kszof: 9, obszar: "Życie w społeczności — udział w wydarzeniach grupy", icf: "d175 · d240",
        cel: "Do końca 5. tygodnia cyklu dziecko przed nową sytuacją (wyjście poza teren, wizyta gościa, zmiana sali) obejrzy z nauczycielem plan obrazkowy i wskaże, co będzie pierwsze, w 4 na 5 sytuacji.",
        forma: "Bieżąca praca w grupie; plan obrazkowy dnia wywieszony na wysokości wzroku dziecka", kryterium: "4/5 sytuacji odnotowanych w karcie obserwacji",
        podstawa: "§ 6 ust. 1 pkt 1 i pkt 2" },
      { poziom: "II", kszof: 5, obszar: "Dbanie o siebie i samodzielność", icf: "d160 · d240",
        cel: "Do końca 7. tygodnia cyklu dziecko na zajęciach w małej grupie wymieni trzy rzeczy, które widzi w sali (ćwiczenie „Rozejrzyj się”), po komunikacie nauczyciela o narastającym napięciu, w 4 na 5 prób.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 prób na dwóch kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 5, obszar: "Dbanie o siebie i samodzielność", icf: "d571 · b1521",
        cel: "Do końca 10. tygodnia cyklu dziecko weźmie do ręki przedmiot uspokajający z wyznaczonego miejsca zamiast płaczu lub ucieczki z sali, w 3 na 5 sytuacji, z podpowiedzią gestową dorosłego.",
        forma: "Wsparcie nauczyciela współorganizującego; zajęcia rewalidacyjne indywidualne", kryterium: "3/5 sytuacji w ciągu dwóch tygodni",
        podstawa: "§ 6 ust. 1 pkt 5 oraz § 7 ust. 2" },
    ],
    metody: ["opowiadanie z ilustracją", "praca z planem obrazkowym", "ćwiczenie uziemiające", "zabawa z latarką"],
    formy: ["praca w kręgu", "praca indywidualna z planem", "praca z całą grupą"],
    srodki: ["Miś Kolorek w szarej chustce", "plan obrazkowy dnia (piktogramy)", "latarka", "szara tkanina — „mgła”", "przedmioty uspokajające dzieci (przytulanka, gniotek)", "ilustracje sytuacji budzących niepokój u 3-latka"],
    przebieg: [
      { czas: "3 min", etap: "Rytuał powitania", n: "Wita dzieci. Pokazuje Misia pod szarą tkaniną: „Miś jutro idzie w nowe miejsce. Nie wie, co tam będzie”.", d: "Dzieci witają się, zaglądają pod tkaninę." },
      { czas: "4 min", etap: "Strach mówi: nie wiem, co będzie", n: "Nazywa mechanizm prosto: „Strach robi się większy, kiedy nie wiemy, co będzie. I mniejszy, kiedy już wiemy”.", d: "Dzieci opowiadają, czego się boją — bez przymusu." },
      { czas: "4 min", etap: "Znaki strachu w ciele", n: "Pokazuje na sobie: serce bije szybko, brzuch się ściska, ręce się pocą. Prosi o sprawdzenie u siebie.", d: "Dzieci kładą dłoń na sercu i na brzuchu, nazywają, co czują." },
      { czas: "5 min", etap: "Plan zdejmuje mgłę", n: "Zdejmuje z Misia szarą tkaninę i pokazuje plan obrazkowy: „Najpierw to, potem to”. Prosi dzieci o wskazanie pierwszego obrazka.", d: "Dzieci wskazują kolejne obrazki, układają je po kolei." },
      { czas: "4 min", etap: "Domknięcie — Rozejrzyj się", n: "Prowadzi ćwiczenie: „Wymień trzy rzeczy, które widzisz. Dwie, które słyszysz. Jedną, której możesz dotknąć”. Świeci latarką na wskazywane przedmioty.", d: "Dzieci wymieniają przedmioty, dotykają, uspokajają oddech." },
    ],
    dostosowania: [
      "Zaburzenia lękowe — nie proś dziecka, żeby opowiedziało, czego się boi, przy całej grupie; wystarczy udział w części z planem.",
      "Spektrum autyzmu — plan obrazkowy zostaw w sali na stałe, nie tylko na te zajęcia; to najskuteczniejsze dostosowanie z całego cyklu.",
      "Nadwrażliwość wzrokowa — latarkę kieruj na przedmioty, nigdy w stronę twarzy.",
      "Dziecko niemówiące / AAC — ćwiczenie „Rozejrzyj się” realizuj przez wskazywanie palcem, bez nazywania.",
      "Niepełnosprawność intelektualna — skróć ćwiczenie do „trzy rzeczy, które widzę”; pomiń dźwięki i dotyk.",
      "Doświadczenie traumy — uprzedź rodzica o temacie zajęć i skonsultuj udział dziecka z psychologiem.",
    ],
    ewaluacja: ["Czy dzieci potrafiły wskazać pierwszy element planu bez podpowiedzi?", "Które dziecko nie chciało mówić o strachu — czy zostało to uszanowane?", "Czy ćwiczenie „Rozejrzyj się” obniżyło napięcie w grupie przed dalszą częścią dnia?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje, próbuje radzić sobie z ich przeżywaniem",
      "Obszar II, pkt 3 — przeżywa emocje w sposób umożliwiający mu adaptację w nowym otoczeniu",
      "Obszar II, pkt 7 — szuka wsparcia w sytuacjach trudnych dla niego emocjonalnie",
      "Obszar IV, pkt 5 — odpowiada na pytania, opowiada o zdarzeniach z przedszkola",
    ],
    notatka: "U 3–4-latka mówimy „strach”, nie „lęk”. Strach dotyczy konkretnej rzeczy tu i teraz i tylko taki jest dla tego wieku dostępny. Nazwa „lęk” wraca dopiero w wersji dla nastolatka.",
  },

  {
    nr: 7, kolor: "paleta", czas: "25 minut",
    temat: "Paleta Misia Kolorka — gra „Kolorowa Ścieżka”",
    podtytul: "Zajęcia podsumowujące cały cykl",
    celOgolny: "Zebranie pięciu kolorów w jedną całość i przeniesienie ich do zabawy, w której dziecko używa emocji w kontakcie z rówieśnikami.",
    celeOperacyjne: [
      "wskazuje kolor odpowiadający swojemu dzisiejszemu samopoczuciu",
      "nazywa pięć emocji przypisanych do kolorów",
      "czeka na swoją kolej w grze planszowej",
      "odbiera dyplom ukończenia cyklu",
    ],
    smart: [
      { poziom: "I", kszof: 3, obszar: "Porozumiewanie się", icf: "d350 · b152",
        cel: "Do końca 12. tygodnia cyklu dziecko w porannym kręgu samodzielnie wskaże kolor odpowiadający swojemu dzisiejszemu samopoczuciu, przez 4 z 5 dni w tygodniu.",
        forma: "Bieżąca praca w grupie; poranny krąg jako stały rytuał dnia", kryterium: "4/5 dni przez dwa kolejne tygodnie",
        podstawa: "§ 6 ust. 1 pkt 1" },
      { poziom: "II", kszof: 7, obszar: "Kontakty i relacje międzyludzkie", icf: "d720 · d880",
        cel: "Do końca 12. tygodnia cyklu dziecko rozegra z trojgiem rówieśników jedną rundę gry „Kolorowa Ścieżka”, czekając na swoją kolej, w 4 na 5 rund.",
        forma: "Zajęcia rozwijające kompetencje emocjonalno-społeczne, 2 × 20 min tygodniowo", kryterium: "4/5 rund na dwóch kolejnych zajęciach",
        podstawa: "§ 6 ust. 1 pkt 3" },
      { poziom: "III", kszof: 8, obszar: "Edukacja przedszkolna — rola dziecka w grupie", icf: "d880 · d137",
        cel: "Do końca 12. tygodnia cyklu dziecko przy wsparciu dorosłego przejdzie 5 pól gry, na każdym wskazując kolor pola, poprawnie w 3 na 5 pól, z podpowiedzią wzrokową.",
        forma: "Wsparcie nauczyciela współorganizującego podczas gry; zajęcia rewalidacyjne indywidualne", kryterium: "3/5 pól w dwóch kolejnych rozgrywkach",
        podstawa: "§ 6 ust. 1 pkt 5" },
    ],
    metody: ["gra dydaktyczna", "zabawa zespołowa z zasadami", "pogadanka podsumowująca", "uroczyste wręczenie dyplomu"],
    formy: ["praca w kręgu", "praca w zespołach 3–4-osobowych", "praca z całą grupą"],
    srodki: ["plansza „Kolorowa Ścieżka” w wersji przedszkolnej — pola w pięciu kolorach", "duża kostka do gry z kropkami", "pionki — figurki albo nakrętki", "pięć kart kolorów dla każdego dziecka", "paleta grupowa — plakat do zaznaczania", "dyplomy ukończenia cyklu", "Miś Kolorek w pięciu chustkach"],
    przebieg: [
      { czas: "4 min", etap: "Rytuał powitania i paleta", n: "Wita dzieci. Rozkłada plakat z pięcioma kolorami: „Poznaliśmy pięć kolorów Misia. Kto pamięta, co znaczy żółty?”", d: "Dzieci przypominają emocje, wskazują kolory na plakacie." },
      { czas: "4 min", etap: "Jak się dziś czuję", n: "Podchodzi do każdego dziecka z zestawem kart: „Który kolor jest dziś Twój?”. Zaznacza wybór na plakacie grupowym.", d: "Dziecko wybiera kartę i przykleja swoją naklejkę przy kolorze." },
      { czas: "3 min", etap: "Zasady gry", n: "Pokazuje planszę i tłumaczy trzy zasady: rzucamy kostką, nazywamy kolor pola, czekamy na kolej. Wprowadza zasadę „pas”.", d: "Dzieci oglądają planszę, powtarzają zasady, wybierają pionki." },
      { czas: "10 min", etap: "Gra „Kolorowa Ścieżka”", n: "Dzieli grupę na zespoły 3–4-osobowe. Krąży między stolikami, wspiera przy czekaniu na kolej.", d: "Dzieci grają, rzucają kostką, nazywają kolor pola, czekają na swoją kolej." },
      { czas: "4 min", etap: "Domknięcie — dyplomy", n: "Wręcza każdemu dyplom, czyta imię na głos: „Za poznanie pięciu kolorów”. Prosi o oklaski dla każdego dziecka.", d: "Dzieci odbierają dyplomy, biją brawo pozostałym." },
    ],
    dostosowania: [
      "Spektrum autyzmu — pokaż planszę dzień wcześniej; zasada „pas” musi być wypowiedziana i pokazana obrazkiem przed startem gry.",
      "ADHD — skróć rundę do 5 pól; dłuższa gra przekracza możliwość czekania na kolej w tym wieku.",
      "Dziecko niemówiące / AAC — nazwanie koloru zastąp wskazaniem karty w tym samym kolorze.",
      "Niepełnosprawność ruchowa — kostkę zastąp kostką z większą ścianką albo aplikacją; pionek podaj z uchwytem.",
      "Niepełnosprawność intelektualna — graj na planszy skróconej do trzech kolorów.",
      "Mutyzm wybiórczy — dziecko może grać, wskazując kolory palcem, bez wypowiadania nazw.",
    ],
    ewaluacja: ["Ile dzieci samodzielnie wskazało swój kolor dnia?", "Czy zasada „pas” była używana i czy grupa ją uszanowała?", "Które cele SMART z poziomów I–III zostały osiągnięte, a które wymagają przedłużenia na kolejny cykl?"],
    podstawaProgramowa: [
      "Obszar II, pkt 1 — rozpoznaje i nazywa podstawowe emocje",
      "Obszar II, pkt 4 — przedstawia swoje emocje i uczucia, używając charakterystycznych dla dziecka form wyrazu",
      "Obszar III, pkt 7 — respektuje prawa i obowiązki swoje oraz innych osób",
      "Obszar III, pkt 8 — obdarza uwagą inne dzieci i osoby dorosłe",
    ],
    notatka: "Te zajęcia domykają cykl i jednocześnie dają dane do ewaluacji IPET-u. Plakat z paletą grupową zachowaj — porównanie z pierwszym tygodniem jest najprostszym dowodem efektywności, jaki można załączyć do dokumentacji.",
  },
];

module.exports = { BRAND, KOLORY_EMOCJI, POZIOMY, KONSPEKTY };
